code/graphics/opengl/gropengltexture.cpp
The normally faster version that was used before misbehaved if that
texture unit already used the specified texture object which caused the
glTexSubImage3D to cause out of bounds issues some times.
This fixes #1554.
=> Make sure updating a texture uses the right texture unit

code/object/objectsnd.cpp
If no flyby sounds are defined for a species, do not attempt to play any. This fixes #1559,
=> Sanity checking in maybe_play_flyby_snd

code/graphics/opengl/gropengldeferred.cpp
Reverting PR #1557, since the changes there mess up the godray effect. Some more work seems to be needed there.
=> Revert changes from #1555

.travis.yml, CMakeLists.txt
This will automatically enable ccache when it is detected on the system
and use it for faster compilations.
=> Enable ccache when available

code/hud/hud.cpp, code/tracing/categories.cpp, code/tracing/categories.h, freespace2/freespace.cpp
While debugging a performance issue reported on Discord I noticed that
the HUD rendering code does not have any tracing scopes. This adds a few
tracing scopes to that code to make performance debugging a bit easier.
=> Add tracing scopes for HUD rendering

code/graphics/2d.cpp, code/weapon/weapons.cpp
The first issue was a wrong usage of `memset`. The commit message contains more information on what the bug was.
The second issue was another `sprintf` warning which I fixed by using our `SCP_string` variant of that function.
=> Fix two minor issues detected by GCC7 warnings

code/menuui/readyroom.cpp
Previously the campaign room caused a heap-use-after-free error
(detected by AddressSanitizer) when loading the campaign failed two
times. This fixes the error by resetting the text pointers to their
default values when freeing the campaign list data.
=> Reset campaign room text pointers when freeing campaign data

code/lab/lab.cpp
The crash described in #1561 was caused by a `NULL` ai profile. The
profile was not set because the lab system already had a loaded ship
object (see line 2230). These changes make sure that the loaded ship
object is deleted before closing the lab system which ensures that the
ai profile is set the next time the lab is initialized.
This fixes #1561.
=> Reset loaded ship object when closing the F3 lab

code/utils/unicode.h
When `Unicode_text_mode` was false, `unicode::num_codepoints()` would return (the `size_t` equivalent of) a negative number, because it was checking the distance from `end` to `start` instead of the distance from `start` to `end`.
Fixes #1571.
=> Correct backwards arguments in unicode::num_codepoints().

code/def_files/deferred-f.sdr, code/def_files/main-f.sdr
Ditches the Blinn-Phong specular lighting model with the GGX BRDF. Should make specular highlights look even more closer to reality.
=> Replaced Blinn-Phong BRDF with GGX BRDF

code/def_files/main-f.sdr
Flipped specular minimum floor to be done before gamma correction. Adjusted minimum specular value to 0.03 from 0.04 since that's Substance Painter's minimum. Brought back fresnel factor from the Blinn Phong function since that's needed for retail models.
=> Specular lighting shader fixes

code/graphics/opengl/gropengltexture.cpp
Cubemaps following https://github.com/scp-fs2open/fs2open.github.com/commit/bd62ceeeb0d1b64d8b8a066519e40680e8b8a5f2 get allocated with immutable storage. But because it only allocates the number of available mip levels, this prevents additional mip levels being generated when we need to generate them using glGenerateMipMap.
This rectifies this issue by making sure we allocate the exact amount of storage we need. This fixes https://github.com/scp-fs2open/fs2open.github.com/issues/1577
=> Fix gloss-dependent blurred reflections

code/fs2netd/fs2netd_client.cpp
This was reported by @chief1983 on Discord. The standalone server crashed
with a `SIGBUS` error caused by an invalid socket file handle in
`FS2NetD_DataReady()`. This should fix that by adding additional checks
where necessary to make sure that our socket is valid when the socket
functions are used.
=> Fix SIGBUS crash in fs2netd

code/graphics/render.cpp, code/graphics/render.h, code/hud/hudbrackets.cpp
This improves the rendering performance of the target hotkey brackets a
bit which caused a significant slowdown previously.
=> Add simple NanoVG draw buffer for better performance

code/jumpnode/jumpnode.cpp
Because it really wasn't, before.
=> Improve the JumpNode::SetName assertion to be readable by non-coders

code/scripting/api/libs/base.cpp
This can be used to check if an API function is available in the current
version of the engine without causing runtime errors.
=> Add lua function for checking the engine version

code/def_files/main-f.sdr, code/def_files/main-g.sdr, code/def_files/main-v.sdr, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltnl.cpp
This will enable a workaround for Nvidia GPUs which will disable the new clipping optimization since it caused issues with those GPUs.
This fixes #1579.
=> Add a workaround for clipping planes on NVIDIA

.travis.yml, ci/travis/check_release.sh, code/graphics/paths/nanovg/nanovg.c, code/graphics/paths/nanovg/stb_image.h
There are a few new warnings in GCC7 so this makes sure that no warning
gets missed by our CI setup. The new configuration should be updated to
the newest GCC version whenever possible.
=> Add GCC 7 configuration for Travis CI

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/util/GPUMemoryHeap.cpp, code/graphics/util/GPUMemoryHeap.h, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/source_groups.cmake, code/tracing/categories.cpp, code/tracing/categories.h, code/utils/HeapAllocator.cpp, code/utils/HeapAllocator.h, test/src/source_groups.cmake, test/src/utils/HeapAllocatorTest.cpp
This changes the model loading code such that all index and vertex data
is packed in a single GPU buffer for each data type (index and vertex
data are still in separate buffers). This reduces the amount of buffer
rebinding needed when rendering a scene which will reduce the CPU
overhead. Furthermore, this opens up possibilities of future
improvements for which it is beneficial if all data is in the same
buffer (e.g. MultiDrawIndirect rendering).
To manage where to put the data in the GPU buffer I implemented a
custom HeapAllocator which manages where data can be put. It uses a very
primitive first-fit algorithm but that is sufficient for this usage
type. This does add quite a lot of overhead while allocating GPU model
data (I did some tracing and some allocation calls took as long as …
=> Pack vertex and index data into one buffer

code/osapi/outwnd.cpp
In recent builds, the engine seems determined to only write logs with the +Parse parameter in debug_filter.cfg enabled. _Somehow_, and don't ask me how, the part of the code that was supposed to check if a given filter is enabled got optimized away in FASTDBG; this slight alteration seems to fix that.
This fixes #1552.
=> Fix for debug_filters defaulting to +Parse

code/graphics/opengl/gropengl.cpp
Since OGL debug messages are only useful for coders, most of the time, we shouldn't print them to the general log unless they're actually critical
=> Reduce the amount of Debug message spam due to non-fatal OGL warnings

code/parse/parselo.cpp
This also converts an assertion into a proper error message which would
contain the actual file and line number.
=> Improve error messages in stuff_int_list

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/weapon/weapons.cpp
This also came up while digging around the lighting-related commandline parameters. In the previosu render pipeline, excluding missiles from lighting made sense; there was a lot of cost associated with it. Now, things are reversed: Excluding models from lighting is more expensive than lighting them, thus this parameter no longer serves any useful purpose.
=> Remove the -missile_lighting commandline parameter

code/ship/ship.cpp
This assertion could be hit if the player died and the engine tried to
play a sound for the now destroyed ship. Since the existing code already
had a check for the case that the object is an observer I just added
another case for `OBJ_GHOST`.
=> Fix assertion failure in ship_get_sound

code/pilotfile/plr.cpp
Having an invalid radar range in the pilot file should not be a fatal error.
=> Downgrade the invalid radar range error in the plr reader code to a warning

code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp, code/weapon/beam.cpp, code/weapon/beam.h
Intended armor type behaviour: Subtracting 500 damage from a beam with a tabled damage of 3100 causes the beam to do ~0.85x damage
Actual armor type behaviour: Subtracting 500 damage from a beam with a tabled damage of 3100 causes the beam to do 0 damage on low time accelerations and 1x damage at high time accelerations, as the damage is subtracted every frame and beam damage is recalculated according to frametimes each frame
Hopefully fixed armor type behaviour: Subtracting 500 damage from a beam with a tabled damage of 3100 causes the beam to do ~0.85x damage
=> Fixes beam behaviour with additive/cap/etc damage types

code/graphics/light.cpp, code/graphics/opengl/gropengldeferred.cpp, code/lighting/lighting.cpp, code/lighting/lighting.h, code/model/modelrender.cpp
This also fixes an issue where an uninitialized variable was used as an index
=> Use an enum class to mark light types

code/lab/lab.cpp
By clamping lab_cam_phi to [0.01, 3.13], we can avoid situations where the object being viewed jumps around due to the camera code running into gimbal lock.
=> Make the lab's camera smoother

code/scripting/api/libs/base.cpp
This can be used by scripts to implement language specific behavior.
=> Add lua functions for accessing the current engine language

code/ship/ship.cpp
The +additive armor type no longer heals a subsystem when you shoot a subsystem with a low damage weapon and the weapon has less damage than the damage subtraction
=> Negative damages no longer heal subsystems

code/ai/ai_profiles.cpp
By making `parse_ai_profiles_tbl()` actually check the return value of `skip_to_start_of_string_either()` (and break if the appropriate characters aren't found), AI profile tables should no longer keep parsing past the end of the file and into invalid memory, until they either find an "#End" in memory somewhere or just plain crash.
As a pleasant bonus, a missing "#End" should now generate an appropriate error message.
=> Make AI profile tables actually stop parsing if #End is missing.

code/mission/missionparse.cpp
=> Print out a warning if we can't find a dockpoint during missionparse

code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/lighting.sdr, code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/shadows.sdr, code/graphics/opengl/gropenglshader.cpp, code/source_groups.cmake
This can be used for keeping code for common functionality in one file
(e.g. lighting functions). The code which detects include statements is
pretty simple so it may break if it is used in a more complicated.
Circular includes are detected and treated as an error.
There was a slight difference between the GGX function from the main
shader and the deferred shader. The deferred shader didn't use the
fresnel value stored in the G-buffer for some reason. I changed the code
so that both shaders use the same parameters.
@SamuelCho Please let me know if that difference was intentional.
=> Add support for includes in shader files

code/osapi/outwnd.cpp
This is somewhat related to #1616 and #1615. I feel that enabling all the extra filters by default is a mistake.
=> The extra debug filters really should not be enabled by default.

code/graphics/opengl/gropengltnl.cpp
While working through the atexit table, this function somehow got called, leading to the debug_filter.cfg being altered, as explained in #1615. While this does fix one immediate cause of the behaviour in #1615, it opens up a few more questions: Why gr_opengl_delete_buffer is called at this point, for example.
=> Do not try to delete opengl buffers when we have no idea what they are

code/def_files/data/effects/deferred-clear-f.sdr, code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/deferred-v.sdr, code/def_files/data/effects/lighting.sdr, code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-v.sdr, code/def_files/data/effects/shadows.sdr, code/graphics/2d.h, code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengldeferred.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h, code/graphics/util/UniformBufferManager.cpp, code/graphics/util/uniform_structs.h, code/model/modelrender.cpp
This moves all lighting operations into the deferred shading phase of
the rendering pipeline. Previously, directional lights were applied to
all objects while they were being rendered. This was probably done to
avoid doing multiple full screen passes later but caused some problems
since the color information in the G-buffers was not correct for doing
later lighting operations.
This was especially noticeable in dark scenes where point lights would
appear to ignore the color of the rendered objects. This should be fixed
with these changes.
I did some performance testing and to my surprise this actually improves
performance in very demanding scenes. My guess would be that applying
the shadows while rendering the objects caused a lot of overdraw which
is not the case anymore since shadows are …
=> Use deferred shader for applying directional lights

code/model/modelrender.cpp
Since the lab isn't doing weird special case rendering anymore, this check is unnecessary
=> Make glowpoints in the lab work correctly

code/weapon/weapons.cpp
The electronics flag only worked if your weapon had a shockwave speed of 0. If it had a shockwave speed > 0 you had to have an AoE.
This fixes that
=> Fixes electronics flag behavior with shockwaves

code/model/modelread.cpp
don't add no_collide (& similar) submodels to the bsp trees
this has been in the fotg branch for ages without causing any apparant
issues
=> add small bsp tree optimisation

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/uniforms.cpp, code/nebula/neb.cpp, code/object/objectsort.cpp, code/starfield/starfield.cpp
Specifying the fog rendering options is now handled by the materials
system and the implementation of `gr_set_fog` was pretty much empty so I
removed it.
=> Remove gr_set_fog

code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr
This is a minor cleanup of how the engine passes vertex attribute data
from one shader stage to the next. The current code uses standalone
attribute variables which require a unique name over the entire shader
program which means that the variable names need to be different when a
geometry shader is used which makes the code more complicated and harder
to understand.
Also, if other shader stages (e.g. the tesselation shader) this change will make
it easier to add support for this shader without introducing even more
conditional attribute names.
=> Use vertex interface blocks for vertex shader attributes

code/def_files/data/effects/main-f.sdr
The emissive part of the lighting was not using the fog values properly
so ships didn't rendered right in nebulas. This fixes that by applying
the standard fog color transform to the emissive part of the scene.
=> Handle emissive light properly in nebulas

code/globalincs/globals.h, code/globalincs/systemvars.h, code/graphics/light.cpp, code/graphics/opengl/gropengldeferred.cpp
This is sort of a companion piece to the discussion in #1634. I feel that using a global limit on lights makes no real sense anymore; it is far better to control the number of lights we're adding than trying to impose a hard cap on things.
=> Remove the MAX_LIGHTS define

code/gamesnd/gamesnd.cpp
This can happen if a script tries to determine the length of a sound
before actually playing it. This fixes the assertion by loading the
sound when it is necessary.
=> Load unloaded sounds when trying to determine sound length

code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengl.cpp, code/hud/hudtarget.cpp, code/model/model.h, code/model/modelrender.cpp
There were actually multiple issues here. The addition of color mask and
stencil state to the material system overwrote the state set by the
hardpoint renderer so the stencil buffer was never written or read
correctly. I fixed this by introducing three new model render flags
(there were a few open slots in the bit mask so I used those) which set
the correct state using the material system. That also makes setting up
the rendering environment much easier.
Second, `gr_opengl_stencil_set` used mixed up parameter values which were
probably broken when I introduced more detailed stencil state tracking.
I restored those values to how they were in 3.8.
This fixes the other issue reported in #1640.
=> Fix stencil rendering in hardpoint rendering

code/hud/hudtarget.cpp
The previous fix to the weapon orientation failed to account for the
change from local to global space for the weapon position. This fixes
that by rotating the model positions to world space before submitting
the render call.
This fixes #1647.
=> Fix rendering position of hardpoint models

fred2/eventeditor.cpp
ANI and EFF are fairly outdated, so we should encourage people to start using APNG for things like head anis. This is also a QoL improvement for modders that are already using APNG.
=> Make APNG the default file extension for the Event Editors head ani file dialog

ci/appveyor/build.ps1, qtfred/CMakeLists.txt
This caused issues for some users and was an accidental change
introduced by the qtFRED merge.
=> Disable building targets with runtime DLLs as default

code/scripting/lua/LuaConvert.cpp
This is probably a bug from when I changed how those functions worked.
The function is supposed to return if it successfully retreived a value
from the Lua stack but instead of returning `true` if it was, it returned
the value it just retrieved. This works fine if that value is `true` but
causes issues if it was `false`.
=> Fix wrong return value when getting boolean value from Lua

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/opengl/gropengltexture.cpp
This addresses #1658. It introduces a new commandline parameter, `-anisotropic_filter`, which takes an int argument which is then used as the anisotropic filtering value in OpenGL. If it is not set, we default to the highest supported level (this has performance implications, of course; I am open to suggestions for a better default than 1...)
=> Make the OGL_Anisotropy setting more usable

code/utils/RandomRange.h
The minimum and maximum values were not initialized correctly which
caused code which relied on those values to fail unexpectedly.
This assigns the value properly and adds a documentation note which
clarifies when the values are valid.
=> Assign minimum and maximum value properly in RandomRange

code/graphics/opengl/gropengltexture.cpp
When I made the texture array changes I forgot to test the texture
detail feature which caused some visual corruption when using a texture
detail which was less than the maximum. This should fix that.
=> Fix texture detail errors

qtfred/source_groups.cmake, qtfred/src/ui/dialogs/MissionSpecDialog.cpp, qtfred/src/ui/dialogs/ObjectOrientEditorDialog.cpp, qtfred/src/ui/dialogs/SelectionDialog.cpp, qtfred/src/ui/dialogs/WaypointEditorDialog.cpp, qtfred/src/ui/util/SignalBlockers.cpp, qtfred/src/ui/util/SignalBlockers.h, qtfred/src/ui/widgets/sexp_tree.cpp
SignalBlockers provides an easy way to block all Qt signals from a widget and all of the widget's descendants. Its intended use is to block signals in qtFRED dialogs' UI update functions.
=> Add SignalBlockers to qtFRED

qtfred/src/main.cpp, qtfred/src/mission/management.cpp, qtfred/src/mission/management.h
This copies the original FRED code for initializing the individual game
systems to qtFRED. This should fix the various issues caused by missing
game system initialization calls.
=> Copy original FRED initialization code

code/cmdline/cmdline.cpp, code/sound/openal.cpp, code/sound/openal.h
The initial JSON flags output lacked this information but it is needed
for proper support by the launcher. This adds a new entry in the JSON
structure without changing anything else so it does not require a new
output version.
=> Write EFX support information to JSON output

code/graphics/uniforms.cpp
This was missed when converting the model uniforms to a uniform buffer
and caused some issues with team colors. This sets that uniform to the
value it had before the uniform buffer changes.
This fixes #1683.
=> Set team_glow_enabled uniform to proper value

code/asteroid/asteroid.cpp, code/asteroid/asteroid.h, code/io/keycontrol.cpp, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/object/objcollide.cpp, code/object/objcollide.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/shipfx.cpp, code/ship/shipfx.h, code/ship/shiphit.cpp
For your consideration, these patches contain various minor tweaks to help tidy up the code base.
For several files, the 'static' keyword has been applied to various routines.  On my local development machine, applying these patches reduces the size of the resulting image by about 8 kB (Ubuntu 16.04 with gcc version 5.4). Admittedly, this is pretty minor in the larger scheme of things, and mileage with other compilers may vary.
A few routines were discovered to not be in use (for several years if my searches were done correctly) and thus this set includes a patch to remove them.
=> Minor clean up

qtfred/CMakeLists.txt, qtfred/src/main.cpp
The CMake code did not specify that qwindows.cll also needed to be
distributed with the application which caused errors for users who had
not installed Qt on their system.
This should make qtFRED redistributable without needing a QT
installation.
=> Fix Windows deployment issue

code/mission/missionparse.cpp
This fixes two possible assertions and two possible buffer overflows
which could have been caused by a mission with wrong values for
$num_stages and $num_icons.
This fixes #1664.
=> Validate number of parsed briefing stages and icons

code/scripting/api/libs/mission.cpp, code/scripting/api/objs/waypoint.cpp
Since `atoi` returns 0 on error the code tries to access the waypoint list
with index -1 which causes an assert in the lookup code. This fixes that
by using the error detection capabilities of `strtol`.
=> Fix Assert in Lua API when passing invalid name to mn.WaypointList

code/particle/effects/BeamPiercingEffect.cpp, code/particle/effects/GenericShapeEffect.h, code/particle/effects/SingleParticleEffect.cpp, code/particle/particle.cpp, code/particle/particle.h, code/particle/util/ParticleProperties.cpp, code/particle/util/ParticleProperties.h, code/scripting/api/libs/testing.cpp, code/weapon/beam.cpp, code/weapon/muzzleflash.cpp, code/weapon/weapons.cpp
The current particle system uses dynamic allocation of particle
instances for keeping track of particle instances. This adds unnecessary
overhead in case the code does not need a handle to this particle which
is the case in pretty much all instances.
The new non-persistent particles are stored in a standard vector without
dynamic allocation which should make the processing steps using this
vector much faster and allow better scalability in case more particles
are used by a mission.
=> Improve handling of non-persistent particles

code/def_files/data/effects/main-f.sdr, code/model/modelrender.cpp
There were actually two bugs here that were fixed:
1. The model draw list code disabled the fog rendering when it thought
it was it deferred rendering mode but did not account for explicitly
disabling the deferred renderer.
2. The fog effect was applied to both the emissive color and the base
color simultaneously which caused visual errors when rendering fogged
objects using the deferred renderer.
This fixes #1717.
=> Fix fog rendering in forward renderer

freespace2/freespace.cpp
The viewer mode check seemed to be wrong but I am not entirely sure if I
fixed this correctly. The `Viewer_mode` variable is a big mess of bitflags
that are not very consistent in what they mean.
=> Fix "show-ship" flag

code/parse/sexp.cpp
These operators used to warn and return NAN if they were given a bit index out of range.  For FREDding convenience, out-of-range bit indexes are now a no-op.  This is particularly helpful in the situation where a FREDder needs to evaluate an extended bit array, one 32-bit chunk at a time, e.g.
0-31 bits: offset 0
32-63 bits: offset -32
64-95 bits: offset -64
96-127 bits: offset -96
Because the sexp system always evaluates every argument, three out of four branches were always evaluated with invalid bit indexes (negative or too large) even if the sexp logic only used one branch.  The new method silently bypasses this behavior.
=> make the set-bit and is-bit-set operators fail gracefully

code/parse/sexp.cpp, code/parse/sexp.h, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Returns true if the ship is in a turret's FOV, false otherwise.  Requested by JSRNerdo.  Uses the object_in_turret_fov internal function which is the same one used by the turret code when it checks whether it can fire.  Optionally uses an argument for distance/range.
=> is-in-turret-fov sexp

appveyor.yml, ci/appveyor/build.ps1
Apparently, Appveyor has removed the Qt version 5.7 from their servers
which was used by FSO previously. I have updated the paths to use Qt
5.9.5 instead but there is a problem with Visual Studio 2013 since
there is no 32-bit Qt version for that compiler installed in the
Appveyor system.
For that reason, I decided to use Visual Studio 2015 instead for the
32-bit builds which means that Visual Studio 2013 will not be tested by
Appveyor anymore. Since no one is using that compiler version anymore
that shouldn't be a big issue.
This should fix the CI issues seen on recent PRs and commits.
=> Fix Appveyor Qt build issue

.clang-tidy, .travis.yml, ci/travis/clang-tidy-diff.py, ci/travis/clang_tidy.sh
This will only check the lines that were changed by a commit or pull
request. This makes it possible to enable more clang-tidy checks without
having to fix all occurrences of the warnings in the code base.
Please note that the changes do not work correctly with rebased branches
due to the way Travis CI supplies the commit range. Pull requests will
always be checked properly though.
=> Use clang-tidy-diff to only check changed lines

code/model/modelinterp.cpp
Fall back to `submodel_get_two_random_points()` if the model does not have a collision tree.  This fixes #1708.
=> fix issue #1708

code/globalincs/pstypes.h, code/globalincs/toolchain/clang.h, code/globalincs/toolchain/gcc.h, code/globalincs/toolchain/mingw.h, code/globalincs/toolchain/msvc.h, code/mission/missionmessage.cpp, code/parse/parselo.cpp, code/utils/unicode.cpp
The code did not account for unicode escape sequences when inserting
scrambling characters which distorted the text and fequently caused
invalid UTF-8 sequences to appear in the text. This fixes that by
using the text iterators already present in the game code. I needed to
rewrite the logic of this block a bit since the previous logic could not
be converted to the way we need to handle unicode sequences at the
moment.
This fixes #1720.
=> Fix scrambling unicode messages

code/bmpman/bm_internal.h, code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/globalincs/pstypes.h, code/globalincs/toolchain/clang.h, code/globalincs/toolchain/gcc.h, code/globalincs/toolchain/mingw.h, code/globalincs/toolchain/msvc.h, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropenglbmpman.cpp, code/graphics/opengl/gropenglbmpman.h, code/graphics/opengl/gropengltexture.cpp, code/graphics/opengl/gropengltexture.h, code/mod_table/mod_table.cpp, code/scripting/api/objs/texture.cpp, freespace2/freespace.cpp
This changes how the bitmap slots are managed by the bmpman system.
Instead of allocating a fixed-size array when the game starts this will
manage multiple "blocks" of bitmap slots. When the engine runs out of
slots in the already allocated blocks it simply creates a new block and
allocates the new slot in that.
This removed the hard limit on how many bitmaps can be loaded at the
same time and should fix issues encountered by mods which use a lot of
bitmap slots (I'm looking at you Spoon).
This implements the idea described in #1503.
I will create a post in the test build forum once the builds have finished compiling. Until this has received more testing it should not be merged.
=> Add new bmpman slot management system

code/hud/hudbrackets.cpp, code/hud/hudtarget.cpp, code/hud/hudtargetbox.cpp, code/io/keycontrol.cpp, code/lab/lab.cpp, code/menuui/techmenu.cpp, code/mission/missionbriefcommon.cpp, code/missionui/missiondebrief.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/network/multi_ingame.cpp, code/playerman/playercontrol.cpp, code/scripting/api/objs/object.cpp, code/scripting/api/objs/weaponclass.cpp, code/ship/ship.cpp, code/stats/medals.cpp, code/stats/medals.h, code/weapon/emp.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp, freespace2/freespace.cpp
This fixes or implements a few things requested in #1730.
New features:
- Alternative name for medals that is only used for displaying their name. This allows them to be translated without causing issues with the medal SEXPs.
- A game_settings option for disabling all currently built-in translations. Since the parts of the engine where this was used have been updated with proper translation support, the built-in translations are not needed anymore. They can be disabled with a game_settings option so that backwards compatibility is not broken.
=> Implement various translation features requested by Novachen

.clang-format
This is largely based on how the existing code is formatted and is in no
way enforced by CI or anything else. This is only so that we actually
have a clang format file in the VCS since it's very useful.
This is the basic version of #1715 without all the CI based format checking.
I would really like to get this into master so that I don't have to continue
keeping an untracked `.clang-format` file in my checkout.
=> Add initial clang-format config file

code/mission/missionparse.cpp
This turns the Warning about missing 640 interface art into a log print.  This applies to all instances of 640/1024 interface art that can be specified in FRED, e.g. loading screens, cbrief and briefing backgrounds, and ship/weapon selection backgrounds.
This fixes #1601.
=> Change Warning about missing 640x480 interface art to a log statement

.clang-format, code/cfile/cfile.cpp, code/cutscene/Decoder.h, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/ffmpeg/FFMPEGDecoder.h, code/cutscene/ffmpeg/SubtitleDecoder.cpp, code/cutscene/ffmpeg/internal.h
This allows to use external subtile files (currently only SRT is
configured) for providing subtitles for movie files. This should be more
universal since it also supports container formats with no support for
subtitle streams.
To use this code the srt file needs to be named
`<movie name>-<language code>.srt` where the language code is the file
extension name specified in the localization table. For english the
`-...` part can be omitted.
=> Add support for external subtitle files

code/localization/localize.cpp
The current code drops trailing white space which can cause issues if
the translated string is used in concatenations. The retail tstrings.tbl
has some entries with white space at the end but since those strings are
not used for concatenations (or else this issue would have been found
earlier) this change should not cause issues there.
This fixes #1739.
=> Respect trailing white space in tstrings.tbl strings

code/sound/ds3d.cpp
Since there is no OpenAL context if sound is disabled there were errors
when calling `alGetError` on a non-existant context. This fixes that by
aborting the sound API call when the sound system wasn't initialized.
=> Fix OpenAL errors when sound is disabled

code/graphics/2d.h
Multiple function pointer dereferences are valid in C but do not change
the result of the operation. The graphics API has some function
definitions which use multiple pointer dereferences while the rest of
the functions do not.
This changes all occurences of the double dereferences to normal GR_CALL
declarations to keep the style in the API definitions consistent.
=> Remove unnecessary function pointer dereferences in gr API

code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilesystem.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, code/osapi/osregistry.cpp, code/osapi/osregistry.h, freespace2/freespace.cpp
There were some reports that using a newer launcher together with an
outdated launcher was causing some issues since the new launcher would
write the new config file which would cause FSO to ignore the changes of
the old launcher since the new config file already exists.
This fixes that by adding a check for when the config locations were
last modified. On Linux and Mac it checks when the old config locations
were modified last while on Windows it checks the registry to determine
if there was a change after the new config file was created.
=> Enable legacy config mode if legacy config is newer

code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr, code/graphics/2d.h, code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropenglshader.cpp, code/graphics/uniforms.cpp, code/graphics/util/uniform_structs.h, code/hud/hudtarget.cpp, code/libs/renderdoc/renderdoc.cpp, code/libs/renderdoc/renderdoc.h, code/libs/renderdoc/renderdoc_app.h, code/model/modelrender.cpp, code/model/modelrender.h, code/source_groups.cmake
This adds support for rendering models using thick lines (that means
lines wider than 1 pixel) which is required by the hardpoint HUD gauge.
This feature was present before the switch to OpenGL code and had to be
removed since the core profile does not support rendering lines wider
than 1 pixel.
This uses a geometry shader for converting all the triangles from a
model to 3 quads along the triangle lines which are as thick as set by
the model renderer. Geometry shaders are quite slow if they generate a
lot of geometry (and this generates 4 times the usual amount of geometry
in the shader) so it's probably not a very fast rendering operation but
it is only needed once per frame so it shouldn't be too bad.
I also added support for the RenderDoc API since I needed that for
debugging and it …
=> Render hardpoint model outlines using geometry shaders

qtfred/source_groups.cmake, qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp, qtfred/src/mission/dialogs/MissionGoalsDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/MissionGoalsDialog.cpp, qtfred/src/ui/dialogs/MissionGoalsDialog.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h, qtfred/ui/EventEditorDialog.ui, qtfred/ui/FredView.ui, qtfred/ui/MissionGoalsDialog.ui
The sexp_tree widget makes the model based dialog a bit ugly here since
it is required for some model operations even though it is a UI
component. In the future it could be split into a model component and an
UI component to allow better separation between model and UI.
This fixes #1698.
=> Port goal editor dialog code to qtFRED

code/lab/lab.cpp, code/object/object.cpp, code/object/object.h, freespace2/freespace.cpp
This adds a step to the post-mission cleanup where we explicitly go through Objects and call obj_delete on everything not already deleted; this obviously needs testing.
Also a few cleanup steps in lab_init to make sure the lab isn't contaminated by leftover data from previously played missions.
=> Delete all objects on mission end (Fix for #1653)

code/osapi/osapi.cpp, code/osapi/outwnd.cpp
This should make it a bit easier to determine if FSO is using the new
config file or the old one from only a log file.
This also adds a log line which states the reason for why the legacy or
new config location was chosen which will make it easier to debug issues
with that code.
=> Write full log path and add legacy mode reason to log file

code/parse/sexp.cpp, code/ship/ship.cpp
The `cap-waypoint-speed` sexp only works for speeds above 0; this PR changes the documentation to clarify that.
I also tweaked an if() block in `ship_return_time_to_goal` because it used a >=0 comparison whereas every other comparison used >0.  (This is only for consistency, because the >0 check is used before this point would be reached.)
This fixes #1758.
=> clarify documentation in cap-waypoint-speed

code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltnl.cpp
This removes the clipping plane submodel removal code and replaces it
with shader code that generates vertices outside the clipping volume if
a model should not be rendered. This even improved performance since
clipping no longer needs to be active for all model rendering
operations.
This finally fixes #1579.
=> Discard submodels by generating clipped vertices

code/bmpman/bmpman.cpp
The TGA loading code pretends that it does pixel conversion but doesn't
actually do that. This changes ensures that this circumstance is
communicated to the caller of bm_lock which will allow that code to
handle the case properly.
This was reported by Bomb3rman on discord.
=> Fix loading of TGA files with unexpected bit depths

code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/graphics/opengl/gropenglshader.cpp
This adds an identification of the OpenGL implementation to the shader
content hash to avoid issues when using the same FSO install with
multiple graphics drivers.
Also adds support for querying the supported binary formats and
gracefully handling missing support for the format of a stored shader.
This can be useful when downgrading the version of a graphics driver
since the older version may not support the binary format yet.
=> Improve handling of the shader cache

code/gamesnd/gamesnd.cpp
If a sound did not receive a valid sound name then the parsing function
would exit early and not set the pitch range properly. This would cause
a divide by zero if the duration of the sound was queried.
This moves the initialization of the pitch range to the start of the
parsing functions which makes sure that the range is initialized even if
the function exits early.
=> Make sure that sound pitch range is initialized properly

code/graphics/opengl/gropengldeferred.cpp
This was not present previously which meant that the command line values
were simply ignored by the engine. This adds the scaling back in which
should restore the lighting behavior to the previous status.
=> Apply spec_* values to lights in deferred pass

code/ship/ship.cpp
When a ship with three primary banks has a `Nolink` weapon in one bank, the other two banks are still allowed to link; if that `Nolink` weapon has a limited ammo supply, however, depleting that ammo supply would disallow primary linking even though the weapon never contributed to primary linking in the first place. This commit changes the logic to only care if the depleted weapon doesn't have the `Nolink` flag. The ideal solution is probably to change how primary linking works so that even if the weapon doesn't have the `Nolink` flag the remaining primaries can still link, but that would be much more involved.
=> Nolink ballistic primaries no longer disallow linking when depleted.

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp
By enabling the "$Use Actual Primary Range:" profile flag (which can also be set on a per-AI-class basis), the code to determine if the AI should fire its primary weapons will not only perform its current "range based on speed of weapon and target" calculation, but it will also compute the weapon's actual range and not fire if the target is outside of it.
=> Add AI profile flag to allow primary weapons to consider range.

code/bmpman/bmpman.cpp, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h
Caching bitmaps between missions is no longer a problem for modern
system and this will improve the default load times when playing more
than one mission.
=> Enable cache bitmaps by default and remove option

.travis.yml, cmake/toolchain-gcc.cmake, code/bmpman/bmpman.cpp, code/cfile/cfile.cpp, code/cfile/cfilesystem.cpp, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/ffmpeg/VideoDecoder.cpp, code/libs/ffmpeg/FFmpeg.cpp, code/mission/missioncampaign.cpp, code/mission/missionmessage.cpp, code/network/chat_api.cpp, code/network/multi_pxo.cpp, code/parse/sexp.cpp, code/pilotfile/plr.cpp, code/ship/ship.cpp, code/ship/ship.h, code/stats/medals.cpp, code/tracing/FrameProfiler.cpp, code/utils/strings.h, lib/opengl/gl/CMakeLists.txt, qtfred/src/mission/Editor.cpp, qtfred/src/mission/missionsave.cpp
GCC 8 has a few new warnings that were triggered in the FSO source code. This fixes those issues. The most common issue was a possible buffer overflow when using `sprintf`. I fixed that by introducing a safe variant of the function which uses `snprintf` for ensuring that no buffer overflow occurs. To make the transition easier I added a template function which automatically deduces the size of the output array. This also upgrades the GCC version used by Travis to 8 to ensure no new warnings are added.
There were also a few deprecation warnings when using FFmpeg 4.0. I solved those by adding version checks and using the appropriate new code.
=> Fix GCC8 and FFmpeg warnings

fred2/addvariabledlg.cpp
This is present in the variable modification dialog but not in the
editor which is used for adding a variable. This also adds the
validation to the editor for adding a new variable.
=> Validate variable name when adding new variable

code/scripting/api/objs/ship.cpp
Lua's `Ship.TargetSubsystem` VIRTVAR, when set, would write to an attribute of the `Ships[]` array based on an objnum instead of a ship instance index. Since `MAX_OBJECTS` is drastically higher than `MAX_SHIPS`, then depending on how many objects happen to be in the mission, an out-of-bounds array access can be easily generated. This commit makes sure to use the objnum instead as an index to the `Objects[]` array, and then retrieve the ship instance from it.
=> Stop accessing Ships[] array with an objnum.

.clang-format, code/object/object.cpp, code/object/object.h, code/scripting/ade.cpp, code/scripting/api/LuaEventCallback.cpp, code/scripting/api/LuaEventCallback.h, code/scripting/api/objs/object.cpp, code/source_groups.cmake, code/utils/event.h
The current scripting hook is pretty simple and straight forward but it
makes a couple of scripting applications harder to implement than
needed.
For example, a lot of scripts need to do some work every frame
for all or some objects. The script needs to manage an internal list of
all the objects that are affected by that list which includes removing
invalid objects to conserve resources. This effectively mirrors what the
engine already does and adds unnecessary overhead.
In these changes I added a generic event system which can be used by any
part of the code for providing callbacks when a specific event occurs.
As an example, I added hooks for the pre- and post-move events to the
object class which are called before and after physics are applied to an
object.
I integrated that feature …
=> Add more generic scripting callback system

code/math/vecmat.cpp
This is definitely open for discussion, but here's my reasoning:
1. This warning is something a modder cannot do anything about
2. Even for coders, it is hard to impossible to actually figure out the cause of most of these
3. Therefore, interrupting gameplay during debugging for this is not warranted, in my opinion.
=> Downgrade null vec3d warning to a log print

code/scripting/api/libs/mission.cpp
The Lua type for matrices is called orientation instead of matrix.
=> Fix inconsistency in Lua background API documenation

code/graphics/2d.cpp, code/io/keycontrol.cpp, code/io/keycontrol.h
I added this hack a long time ago and it always bothered me why I didn't
come up with a better solution. This is the better solution which uses
the popup_active function for determining if gr_flip is called within a
popup.
=> Remove hack for On Frame scripting hook and quit mission popup

code/scripting/api/libs/mission.cpp, code/ship/ship.cpp
Ideally it wouldn't be an optional argument at all, but that would break backwards-compatibility, so instead it'll just return an invalid ship handle instead of calling `ship_create()` with a class of `-1`. In addition, the `Assert` from `ship_create()` meant to guard against invalid `ship_type` values is now an `Assertion` that actually says what the invalid value of `ship_type` was, to make future debugging easier.
=> Lua's createShip() function now checks for a valid ship class.

code/gamesnd/gamesnd.cpp, code/menuui/optionsmenu.cpp, code/mission/missionmessage.cpp, code/mission/missionmessage.h, code/mission/missiontraining.cpp, code/network/multi_voice.cpp, code/scripting/api/libs/audio.cpp, code/scripting/api/objs/message.cpp, code/scripting/api/objs/sound.cpp, code/scripting/api/objs/sound.h, code/ship/shipfx.cpp, code/sound/channel.h, code/sound/ds.h, code/sound/sound.cpp, code/sound/sound.h
This converts the previous int handles to a strongly-typed wrapper
handle which will make the API more self-documenting and will ensure
that wrongly used handles are detected at compile time.
I already found a few mistakes with these changes which I also fixed
here.
=> Use strongly-typed handles for sound entries

code/pilotfile/csg.cpp
The previous code simply set a boolean flag to indicate that the data is
"invalid" which failed the campaign loading operation. With these
changes, those entries will simply be skipped. That can happen if a mod
added or removed a ship or weapon class or if two campaigns share the
same campaign name.
=> Don't make invalid data in campaign file fatal

code/scripting/api/libs/tables.cpp
The bounds check was not correct for 1-based indices. I moved the
Lua->C++ index conversion before the bounds check so that it makes
more sense.
Also, atoi isn't a reliable way for converting a string to an integer.
=> Fix bounds check and string->int conversion in lua ship classes API

code/ship/ship.cpp
Previously, if `parse_weapon_targeting_priorities()` couldn't find a weapon matching the name, it wouldn't parse the "+Target Priority:" line, so it would cause a parsing error when the parser failed to find "$Name:" or "#End" there. Now, the "match not found" codepath still parses it so that no mismatch occurs. Also, I reordered the function so that the parsing wasn't happening in the middle of a loop through the list of weapon types, because it made me cringe.
=> Make parse_weapon_targeting_priorities() work when weapon missing.

code/cfile/cfile.cpp, code/cutscene/Decoder.cpp, code/cutscene/Decoder.h, code/cutscene/VideoPresenter.cpp, code/cutscene/VideoPresenter.h, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/ffmpeg/VideoDecoder.cpp, code/cutscene/ffmpeg/VideoDecoder.h
This allows to directly display RGB(A) movies without transcoding them
to YUV first. This allows the movie player to support APNG files (which
are supported natively by FFmpeg) with an alpha channel and without
converting them to YUV first.
=> Add support for movies with RGB(A) pixel format

code/cutscene/VideoPresenter.cpp, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h
This was causing issues when using the new scripting API in JAD where
there were a lot of 2D operations which filled up the immediate mode
buffer. The reason was that GL_ARB_vertex_attrib_binding the relative
offset is limited and the movie code adds the immediate buffer offset to
the vertex layout which then hit the offset limit set by OpenGL.
This fixes that by using the normal byte offset method which is already
used by the render_primitives functions.
=> Use byte offset into immediate buffer for movie rendering

code/ai/aigoals.cpp, code/fs2netd/fs2netd_client.cpp, code/hud/hud.cpp, code/hud/hudtargetbox.cpp, code/io/keycontrol.cpp, code/menuui/barracks.cpp, code/menuui/playermenu.cpp, code/network/multi.cpp, code/network/multiui.cpp
In the code there are some strings from features added by the SCP that uses two different IDs for the same string. This PR cleans them up, so that only one ID is used.
The IDs that were occupied by duplicates aswell IDs that were already unused before are now replaced by previously untranslated strings, that are now translateable through the strings.tbl.
This contain all requests i made in #1738. except from the bindable controls.
=> Strings.tbl translation adjustments

code/asteroid/asteroid.cpp, code/particle/ParticleManager.cpp, code/particle/ParticleManager.h, code/particle/effects/CompositeEffect.cpp, code/particle/effects/GenericShapeEffect.h, code/ship/ship.cpp, code/ship/ship.h, code/weapon/beam.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Nightmare discovered an off-by-one error when checking the validity of a
particle effect handle. Since the new ID system makes that much easier
and less error-prone I decided to go ahead and convert all handles to
an ID typedef which also fixes the reported bug.
=> Use type-safe handles for particle effects

code/model/modelread.cpp
This will make the error message clearer instead of just showing a
cryptic Assert message. This cannot be handled by a simple warning since
capping num_debris_objects to MAX_DEBRIS_OBJECTS would then cause issues
when reading the rest of the header.
=> Convert debris object count Assert to Error

.clang-tidy, ci/travis/script.sh, ci/travis/valgrind.supp, code/def_files/data/scripts/cfile_require.lua, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/scripting/ade.cpp, code/scripting/ade.h, code/scripting/lua.cpp, code/source_groups.cmake, test/gtest/include/gtest/internal/gtest-internal.h, test/gtest/include/gtest/internal/gtest-port.h, test/src/scripting/require.cpp, test/src/source_groups.cmake, test/src/util/FSTestFixture.cpp, test/test_data/scripting/require/defaultRequire/data/scripts/lib.lua, test/test_data/scripting/require/defaultRequire/data/scripts/test.lua, test/test_data/scripting/require/overrideRequire/data/scripts/cfile_require.lua, test/test_data/scripting/require/overrideRequire/data/scripts/test.lua, test/test_data/scripting/require/overrideRequire/data/tables/scripting-mod.tbm
This allows to use the built-in lua "require" function with our file
system. This will help organize complicated scripts and it will also
allow to use libraries which were designed for this system.
To enable this change, this includes a new mechanism which allows to
load scripts from the default file system so that the files don't need
to be included in every mod. The default files can be overridden by a
mod if a special mod-table option has been set, similar to how external
shaders are handled right now.
=> Add a lua loader that uses the CFile system

code/ai/aibig.cpp, code/ai/aibig.h, code/ai/aicode.cpp
I am starting to get a little more free time for a little while, so I thought that I would take a crack again at trying to clean up some the APIs--specifically those in aibig.cpp that are known to have unused parameters.
For those few routines, I ...
1. applied the 'static' keyword to the routine when it seemed appropriate.
2. applied the 'const' keyword to parameters where it seemed appropriate.
3. updated the arguments where those routines were called.
In theory, these changes should result in fractionally more efficient code as those unused parameters no longer need to be processed by the caller.
Hopefully these proposed changes are met with your satisfaction.
=> Remove unused parameters

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
This solves #1802 by always writing a newline after the mission notes and before `$End Notes:`, to ensure that `$End Notes:` won't be parsed as a comment.
=> Write newline after mission notes

code/object/object.cpp, code/object/object.h, freespace2/freespace.cpp
The `Objects` array is destroyed when the game exits at which point the Lua state object which was used by the callbacks doesn't exist anymore. This causes a crash since the event code tries to deallocate the Lua function reference with an invalid Lua state pointer.
This fixes that by clearing all object array elements when the game closes, before the Lua state is destroyed.
=> Fix crash on game shutdown if Lua object callbacks are used

code/hud/hudescort.cpp, code/hud/hudmessage.cpp, code/hud/hudobserver.cpp, code/hud/hudsquadmsg.cpp, code/hud/hudtarget.cpp, code/hud/hudtargetbox.cpp, code/io/keycontrol.cpp, code/mission/missionhotkey.cpp, code/mission/missionlog.cpp, code/mission/missionlog.h, code/mission/missionparse.cpp, code/mission/missionparse.h, code/network/multi_pmsg.cpp, code/network/multimsgs.cpp, code/network/multimsgs.h, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp, code/ship/ship.h, fred2/missionsave.cpp, freespace2/freespace.cpp, qtfred/src/mission/missionsave.cpp
This adds a mission file option for ships which allows specifying a
different string which should be used for displaying the name of the
ship to the user. This name will not be used in SEXPs or other ship
lookup functions so it can be freely translated and two ships can also
have the same display name.
The new feature can be used by adding `$Display name: <string>` after `$Name`
for a ship in a mission file. I think I added proper support for FRED
(and qtFRED) so that this new value is properly saved but it would be
great if someone could test that.
This implements one of the features requested in #1730.
Display name support is still missing from the events screen since
the same data is also used by various SEXPs where the actual ship name
is used.
=> Add ship display name feature

code/bmpman/bmpman.cpp, code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilesystem.cpp, code/cfile/cfilesystem.h, code/graphics/generic.cpp, code/graphics/opengl/gropenglshader.cpp, code/hud/hudconfig.cpp, code/lab/lab.cpp, code/menuui/barracks.cpp, code/menuui/playermenu.cpp, code/mission/missioncampaign.cpp, code/pilotfile/csg.cpp, code/pilotfile/csg_convert.cpp, code/pilotfile/pilotfile_convert.cpp, code/pilotfile/plr.cpp, code/pilotfile/plr_convert.cpp, code/playerman/managepilot.cpp, code/sound/ffmpeg/WaveFile.cpp, fred2/campaigneditordlg.cpp, fred2/mainfrm.cpp, qtfred/src/mission/Editor.cpp, test/src/cfile/cfile.cpp
Some usages of CFile require that operations only operate on a specific set of files instead of operating on the entire CFile system. This was already hacked-in for the player files which need to be in the root directory instead of in the mod directory.
With these changes that hack could be removed and replaced. This also allows moving the shader cache from a per-mod cache to a global cache in the top-level user directory (which was actually the reason why I began working on this).
=> Add CFile API for specifying the file location

fred2/customwingnames.cpp, fred2/management.cpp, fred2/management.h, fred2/missionnotesdlg.cpp, fred2/missionsave.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/dialogs/CustomWingNamesDialogModel.cpp, qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp, qtfred/src/mission/missionsave.cpp
Currently, quotation marks play havoc when entered into mission info text fields like title, author name, etc.  An odd number of them renders the mission invalid (and FRED does not give a helpful error, so it can be confusing what the problem is) and an even number causes the game and FRED to ignore everything after the first mark.  Because of this, I don't think there's any problem is just stripping them, which is what this PR does.
Also, I improved handling of #1802 (the designer notes semicolon issue) by writing a newline only if necessary.  This prevents a bunch of useless newlines from accumulating every time the mission is saved.
Finally, the git diff for `management.h` is a mess because of the clang formatter, but I only added the prototypes for `strip_quotation_marks` and …
=> Improve parsing of mission info text fields

lib/discord/src/CMakeLists.txt
The CMake file did not contain the required target_link_libraries which
made the build fail when compiling it for the FastDebug configuration.
=> Fix MSVC linking issue in new Discord Code

code/graphics/paths/NanoVGRenderer.cpp, code/graphics/paths/nanovg/fontstash.h, code/graphics/paths/nanovg/nanovg.c
The original issue was reported by Novachen in #1754 where a significant
slowdown was encountered in the controls menu (Ship and Misc tabs). I
traced the cause of the slowdown to repeated uploads of the NanoVG font
atlas texture even though no changes were necessary.
The root cause of the issue was that NanoVG did not handle invalid UTF-8
sequences at the end of a string properly. The UTF-8 decoder returned a
success code even though no code point was decoded which lead the rest
of the code to believe that the font atlas needed to be recreated.
This fixes #1754 by properly handling that case.
This also fixed an assertion failure if NanoVG was asked to render
2D elements without any vertices.
=> Properly handle invalid UTF-8 sequences in NanoVG

code/hud/hudartillery.cpp, code/math/vecmat.cpp, code/math/vecmat.h
This contains a fix for `vm_vec_random_cone` and a more efficient version of the sphere equivalent.
The primary issue with the original `vm_vec_random_cone` function was it's use of 3 rotations of the input vector in an arbitrary order that results in a square cone output as opposed to the assumed circular cone output. The new version generates a unit vector in the correct half angle region, then rotates it into the orientation provided or constructed from the input vector.
This is a fix for #1812
=> Fix vm_vec_random_cone/sphere functions

code/libs/discord/discord.cpp, freespace2/freespace.cpp
This was needed by the restart dialog action and got removed since the
Discord changes needed to know if a mission was active or not.
I removed the code which changed the mission file name and replaced it
with some internal handling in the discord code which should now handle
mission restarts better.
This fixes #1815.
=> Don't reset mission file name on mission end

fred2/management.cpp, qtfred/src/mission/management.cpp
This was reported by @ngld who experienced issues with Knossos since FRED
did not terminate properly when asked to provide the command line flags.
This should fix that.
=> Terminate FRED/qtFRED when command line demands it

code/globalincs/pstypes.h, code/math/vecmat.h
This makes it a bit easier to use the vector types since they are now
usable with the standard C++ operators.
=> Add C++ operators for vector math operations

code/cutscene/Decoder.h, code/cutscene/ffmpeg/AudioDecoder.cpp, code/cutscene/ffmpeg/AudioDecoder.h, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/ffmpeg/FFMPEGDecoder.h, code/cutscene/ffmpeg/SubtitleDecoder.cpp, code/cutscene/ffmpeg/SubtitleDecoder.h, code/cutscene/ffmpeg/VideoDecoder.cpp, code/cutscene/ffmpeg/VideoDecoder.h, code/cutscene/ffmpeg/internal.h, code/cutscene/player.cpp, code/cutscene/player.h, code/scripting/api/libs/graphics.cpp
This adds a playback property for making the movie loop to the start
when the end is reached. The way this is done is by simply keeping the
decoder running even if the end of the movie is reached. Then the movie
is reset to the beginning and decoding continues. The player detects
this reset by examining the frame times which keeps the playback
constant.
This also includes support for this in the movie scripting API.
=> Add support for looping movies

code/missionui/missionweaponchoice.cpp
In PR #1736, commit ae149b6061ba92949c34592da1f390f430dc4c7e, one of the arguments was accidentally removed from a varargs function.  This PR puts it back.
EDIT: This PR fixes issue #1829.
=> fix bug introduced in pr #1736

code/scripting/api/libs/mission.cpp
Wookieejedi and Axem noticed that mn.getMissionFilename() sometimes returns the filename with the .fs2 extension, and sometimes not depending if you are in a campaign or tech room.  This PR ensures that the extension will always be included.
Presumably we do actually want to make them consistent, due to the principle of least astonishment, but do we want to standardize on having the extension, or not having the extension?  Pinging @AxemP for his input.
=> make sure getMissionFilename never has a .fs2 extension

code/menuui/readyroom.cpp, code/mission/missioncampaign.cpp, code/mission/missionload.cpp, code/mission/missionload.h, code/mod_table/mod_table.cpp, code/network/multiui.cpp
This works just like `#Ignored Campaign File Names`, just with missions.
```
#Ignored Mission File Names
$Mission File Name: 1.fs2
$Mission File Name: 2.fs2
```
etc.
This will only ignore standalone missions, not missions that are included in campaigns.  It works for both single-player and multiplayer.  I have tested it in both the tech room and the multiplayer "create game" screen.  Based on code searches, these are the only two places in the code where standalone missions are listed.
This PR addresses #1666 and its duplicate #1826.
=> add game_settings feature to ignore single missions

code/mission/missioncampaign.cpp, code/mission/missioncampaign.h, code/network/multiui.cpp
Since multiplayer and singleplayer campaign lists are generated in two different functions, the `#Ignored Campaign File Names` feature never ignored multiplayer campaigns.
This fixes #1838.
=> ignore multiplayer as well as singleplayer campaigns

code/hud/hudtarget.h, code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/ship/ship.h
Requested for FotG - allow dedicated scanning ship options
e.g. Y-wing Longprobe & TIE/rc
=> add per-ship-class scanning range feature

code/def_files/data/effects/main-f.sdr
HDR color space conversion for spec maps only happened in one code path, not all of them. This fixes #1843
=> HDR color space conversion for spec maps is not applied correctly

code/def_files/data/effects/fog-f.sdr
This makes the deferred fog rendering code use the nebula background
instead of the single fog color for the background.
This is not an ideal solution since objects fade to the fog color
instead of the color of the background but it's better than rendering no
background.
=> Fix nebula background rendering

code/graphics/line_draw_list.cpp
This should make the line draw list class behave identically to the old
line rendering functions. This caused a few issues where the lines were
drawn outside the scissor area which made them invisible.
This fixes #1655.
=> Apply clipping offsets when using the line draw list

code/osapi/osapi.cpp
This adds the runtime and compile version of the used SDL library to the
start of the debug log. This was requested by ngld and should make
diagnosing some errors easier.
=> Write SDL version to debug log

code/ship/ship.cpp
Previously the logic for `share fire direction` in relation to `salvo mode` and `use multiple guns` would result in removal of the `share fire direction` unless they were both present ( !A || !B ) whereas it should only get removed if neither is present ( !A && !B ). This is a fix for #1852 .
=> Fix share_fire_direction logic

code/menuui/playermenu.cpp
This rewrites the text of the warning popup which says "The currently active mod has generated X warnings..."  The paragraph is broken up to avoid Wall of Text syndrome, and the wording is made a bit friendlier.
=> rewrite the mod warning dialog a bit

code/fireball/fireballs.cpp, code/fireball/fireballs.h, code/object/object.cpp, code/parse/sexp.cpp, code/ship/shipfx.cpp
The warp-effect SEXP can now specify other animations from fireball.tbl that are not necessarily the standard or Knossos animations.  Additionally, the SEXP can now specify the duration for the opening and closing of the warp effect.
=> add additional parameters to warp-effect

code/mission/missiontraining.cpp
There is a following bug: if you set Voice volume level to zero, messages in some training missions will skip too fast (2 sec). For example in FSPort mission "Basic Training Stage 4" file btm-04.fs2
It is because with zero volume message timing is not recalculated.
I tested it and now all is OK.
=> Training messages fix.

code/fireball/fireballs.cpp, code/fireball/fireballs.h, code/parse/sexp.cpp, code/parse/sexp.h, fred2/management.cpp, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/main.cpp, qtfred/src/mission/management.cpp, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
This is a minor overhaul of fireball.tbl, with improvements in both sexps and modular tables.
Modular tables now work as one would expect -- the default fireball.tbl defines values and -fbl.tbm can override them or add new ones.  Previously new fireballs could not be added, and the old way of reconciling the modular table was hard to understand and even harder to adapt for new options.
Each fireball entry can now have a unique ID, which is generated if not specified by the table.  This can be used by the `explosion-effect` and `warp-effect` SEXPs to specify the fireball, rather than the old way of specifying the index.  (The old way still works.)  The unique ID is also another way of overriding a tbl entry via tbm.
This PR also, incidentally, fixes a couple of minor UI problems when …
=> Remodularize fireball.tbl

code/fireball/fireballs.cpp, code/fireball/fireballs.h, code/fireball/warpineffect.cpp
This allows different fireball.tbl entries to have different auxiliary warp effects.  There is actually a warpglow02 bitmap specified in the retail VPs, so the Knossos entry can now be edited to use that bitmap if desired.  (This is not done in the new code for compatibility reasons; the MVPs currently do not specify a replacement warpglow02.)  In the same way, the Knossos entry (or any new entries) can have different "warp balls" and warp models.
This also fixes a small bug in #1865, where `$Unique ID:` was inadvertently not allowed because it is parsed before `$Name:`.
=> Custom warp glows, balls, and models

code/cmdline/cmdline.cpp
The `show_mem_usage` flag was removed two years ago but it still shown in the launcher.
=> Don't show nonexistent memory usage flag

code/mod_table/mod_table.cpp, code/playerman/player.h, code/playerman/playercontrol.cpp, code/ship/shipfx.cpp
This converts the player warpout defines into variables that can be set from the mod_settings.tbl.
This was done at the request of Spoon and Axem because the exponential thrust curve screws over a fair chunk of ships from WoD, making them take an egregious amount of time to warp out.
=> Make player warpout settings customizable

code/ship/shipfx.cpp, code/ship/shipfx.h
I found a bug that the hyperspace warpin effect does not play warpin sounds set in ships.tbl. So I looked at "int WE_Hyperspace::warpStart()" code line 4322 in shipfx.cpp, and I found that it is missing a section that actually plays any of the warpin sounds. The other WE (WarpEffects) have these lines specified below in their warpStart(), but not WE_Hyperspace. The sections WE_Hyperspace::warpStart() are missing are added with this PR. This addresses Issue #1889.
=> Fix missing Warpin sounds from Hyperspace Warpin Effect 

code/mission/missionparse.cpp
Fixes bug by adding the conditional hook call "On Ship Arrive" to docked wings that arrive. Previously, ships in a docked wing that would arrive would not trigger the "On Ship Arrive" hook variable.
=> Fixes missing "On Ship Arrive" with Docked Wings

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aibig.cpp, code/ai/aicode.cpp
Requested by @MjnMixael and @FrikgFeek on Discord and also [two years ago on the forums](https://www.hard-light.net/forums/index.php?topic=92274.0).
Note that turning this on renders the `free-afterburner-use` option in the `alter-ship-flags` SEXP moot, because there's no way to effectively turn that off when this flag is on.
=> Add "$free afterburner use" flag to ai_profiles.tbl

code/bmpman/bmpman.cpp, code/mission/missionbriefcommon.cpp
Also, if we can't open an existing file, we should at least display a warning.
=> If an icon can't be loaded, display an error instead of asserting.

code/lab/lab.cpp
Currently, the POF filename shown in the bottom right is correct for the first model chosen but does not update when any other ship is selected.
=> Update displayed POF name in the F3 lab when new ship is selected

code/scripting/scripting.cpp, code/scripting/scripting.h, code/ship/ship.cpp
Previously there were no hooks that could be used to tell if a ship departed via docking bay, because the only departure related hook, "On Warp Out", only triggered when a ship departed via hyperspace. This PR adds a conditional hook that executes when a ship departs via any departure method (ie docking bay). It is called with "$On Ship Depart".
=> Add '$On Ship Depart' Conditional Hook

code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/io/keycontrol.cpp, code/parse/sexp.cpp
Fixes #1855 
From the comment, `hud-cease-targeting` turning off autotargeting may be intentional.  For safety's sake, I created a new function for the SEXPs, but since `hud-cease-targeting` is only used otherwise as a default case when rendering the target box and when the `STOP-TARGETING-SHIP` key is pressed, changing it might be preferable.
=> ship-invisible doesn't turn off autotargeting

code/lab/lab.cpp
Addresses part of #1710 
It looks like the current behavior is a leftover from the old lab, where each entry had options for viewing ship LODs.  Now it's just a nuisance.
=> Show ship directly when clicking on it in the F3 lab

code/ship/shiphit.cpp
The physical center of a group of docked objects isn't necessarily the physical center-of-mass.
=> calculate physics whack from docked center-of-mass, not docked center

code/model/model_flags.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp
This adds the "no sparks" flag for subsystems which disables the
generation of spark sources for that subsystem when it is hit.
This was requested by Axem.
=> Add option for disabling spark spawning for subsystem

code/scpui/SoundPlugin.cpp
Currently if an element consists of multiple parts, the hover sound will be played even while moving between these parts.
For example if you move between the text label and icon on the pilot select screen, you'll hear the hover sound even though you never leave the button.
This PR fixes this by only acting on events that are triggered on the element where the sound property is set and ignoring any other events that propagate from children.
=> Only play UI sounds if the event is triggered on the element where the property is set.

code/graphics/opengl/gropengltnl.cpp
Fix for:
```
Trying to create 1024x1024 32-bit shadow framebuffer
Failed to create framebuffer: Incomplete framebuffer attachment
Trying to create 1024x1024 16-bit shadow framebuffer
Shadow framebuffer created successfully.
```
Tested on Intel, Nvidia and it works:
```
Trying to create 1024x1024 32-bit shadow framebuffer
Shadow framebuffer created successfully.
```
But I have no knowledge about OpenGL, so please check it. ;)
=> Fix for incomplete attachment in shadow framebuffer

code/lab/lab.cpp
This changes the model rotation method from a "trackball" to a "turntable" model. 
By default, rotations are entirely disabled in the lab. By pressing "R", you can cycle through the rotation modes (Disabled -> Yaw only -> Pitch only -> Yaw and Pitch -> Disabled), the "S" key allows you to set the rotation speed (Fast -> Slow -> Slowest -> Fast).
NOTE: This only affects the model (i.e. rotations while holding down the left mouse button), not the background/camera (i.e. rotations while holding the right mouse button).
=> Make the lab camera better

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/sound/fsspeech.cpp, code/sound/fsspeech.h, code/sound/speech.h, freespace2/freespace.cpp
This replaces the previously used defines with inline functions which
fixes a few warnings if the macros were ever used. This also changes
fsspeech.cpp so it is compiled always since it has no dependency on the
underlying speech system.
=> Cleanup the speech API code a bit

appveyor.yml
They updated their Qt version and didn't update the documentation page.
This fixes the recent build errors by using the 5.9 symlink which is
linked to the most recent version.
=> Fix Appveyor Qt directory

code/lab/lab.cpp
In the case of `Num_pilot_squad_images` being 0, the lab should not trigger the modified assert and insignias should be prevented from rendering.
=> Fix oversights when a mod has zero Insignias

code/decals/decals.cpp
This tracks the original object type of a decal and marks a decal as
invalid if the type changes. This should fix a bug reported by Spoon.
=> Add additional validity check for decals

code/scripting/api/objs/model.cpp, code/scripting/api/objs/particle.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/texturemap.cpp
These were all cases where the parameter was the new value when setting
a variable. The variables should always be initialized when that code is
reached but it is still better to check the pointers before using them.
These were found by @niffiwan.
=> Check optional scripting parameters before using them

code/object/objectsort.cpp
Run nebula test once per frame rather than once
per object.
Use a common function to avoid drifting errors.
=> objectsort: Move nebula detection to common area

code/object/objectsort.cpp
if an object is a ship, it is a model. No need
to check twice.
=> objectsort: remove useless check

code/scripting/scripting.cpp, code/scripting/scripting.h, code/weapon/weapons.cpp
This hook is distinct from `$On Weapon Fired:` in that it triggers each time `weapon_create` is called by the engine. Additionally, the weapon object itself is included as a hookvar `Weapon`.
=> Add On Weapon Created Hook

code/math/vecmat.h, code/mission/missionparse.cpp, code/object/objectdock.cpp, code/object/objectdock.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/shipfx.cpp, code/ship/shipfx.h, code/ship/shiphit.cpp
This is a rewrite of the code which calculates positions and distances for warpin and warpout.  Instead of assuming the object's length is twice its radius, it calculates the size using the model minimums and maximums.  Instead of using the object's center, it calculates the geometric center using the same method.  In this way all model offsets are properly canceled out and the warp portals are displayed at the proper coordinates.  The various hackish adjustments for ships like the Colossus have been removed.
Note: ship warpin/warpout distances using the new code are not precisely identical to the old code, but they are pretty close.
This fixes #1874.  This also fixes a potential bug where a Knossos could suddenly jump position when a HUGE ship comes through the portal but not through the …
=> Fix warp clipping

code/graphics/opengl/gropenglshader.cpp
Shaders lookup in opengl_get_shader_idx performance reduces from
O(n) shader to O(1).
Signed-off-by: Matthew Khouzam <matthew.khouzam@gmail.com>
=> Add a cache map for shaders in order to accelerate shader lookup

code/scripting/api/objs/streaminganim.cpp
The move constructor was written wrongly which caused issues when moving
the value into the Lua memory. This fixes that issue.
This fixes #1944.
=> Fix move constructor of streaminganim_h

code/scripting/api/objs/sound.cpp
This was missing from the API code and was uncovered by the new
scripting API changes.
=> Add missing parameters to soundfile:play

code/parse/sexp.cpp
Bad data can cause the name search to fail, and if `change-ai-class` was called with an invalid AI class, it could cause later invalid array accesses (using an index of `-1`).
=> Don't rely on Assert to check for a valid AI class in SEXP code.

code/particle/effects/GenericShapeEffect.h, code/utils/RandomRange.h
This makes some general changes to the particle parsing code. It moves
the trail effect option to the end of the options list to remove an
ambiguity in the resulting parsing code. This is done in a backwards
compatible manner so existing tables will not be broken by this.
This also introduces support for specifying single number ranges
without the parentheses to make that easier to use.
=> Improve particle parsing code

code/object/objcollide.cpp
This PR is based on some Discord discussion.  Apparently this is a known optimization but nobody has bothered to submit a PR yet. :p
From comments by @TRBlount:
> Turns out
if you make the vectors in that function static
that function goes from 1.5ms
to 0.2ms
> by making the vectors static, you no longer have to worry about reallocating unless you add even MORE objects to the scene
> the speedup is basically taking advantage of the fact that the data pointer inside the vector isn't being moved around as often
=> simple optimization for obj_sort_and_collide

code/lab/lab.cpp, code/lab/wmcgui.cpp, code/lab/wmcgui.h
Redo of #1926 because I messed up the Git history there.
Currently, the rendering options sliders in the lab for ambient, static and bloom are initially set to 0 by default, even though the actual values are what is passed in on the command line. This PR changes that so that the sliders accurately reflect the true values.
This also adds the ability to reset a ship to the default position, rotation and lighting when 'v' is pressed.
These changes should improve the experience of trying out different lighting settings.
=> Set initial slider values to the command line parameters and add functionality to reset view

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ship/ship.cpp
Implements [Mantis 3198](http://scp.indiegames.us/mantis/view.php?id=3198).
This does pretty much what the title says:  currently if a primary bank is unequipped, rearming will result the player having a new weapon.  Because this is intentional from retail, this PR adds an AI flag to disable that behavior.
=> AI profile flag for support to not equip new primary

.clang-format, code/parse/sexp/sexp_lookup.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h
This can be used by the various subsystems for cleaning up Lua
references before the Lua state is destroyed. This avoids having
dangling references to the Lua state which would cause segfaults later
on.
The first subsystem to use this is the dynamic SEXP system which had
dangling references due to keeping Lua references to the SEXP functions.
This fixes #1954.
=> Add Lua state destruction event

cmake/toolchain-apple-clang.cmake, cmake/toolchain-clang.cmake, cmake/toolchain-gcc.cmake, code/graphics/opengl/gropenglbmpman.cpp, code/io/joy-sdl.cpp, code/libs/ffmpeg/FFmpeg.cpp, qtfred/src/mission/FredRenderer.cpp
Enable compiler warnings for unused functions in gcc and clang toolchain files.
fixes #1955
=> enable Warnings for unused functions

code/model/modelread.cpp
In a Release build, there was absolutely no code making sure that the text "$glow_texture=" was actually present in the properties field of a glow point bank, beyond a simple `strlen()` check. Even in Debug builds, there was no guarantee that the text was at the start of the properties field; it was just assumed (without even an assertion verifying it). Now, the assertions have been removed and the appropriate conditions are checked in both Release and Debug.
=> Avoid using Asserts for data security in modelread properties-reading code.

code/mission/missionparse.cpp, code/ship/ship.cpp
Since FRED and FS2 load mission data slightly differently, the warp effect loading code had to be slightly reorganized in order for the warp effects to not be based on invalid data.  Additionally, the warp effects had to be initialized a little bit later so that it could accommodate a new set of warp parameters from the parse object.  As a bonus, this PR also handles warp effects being reassigned in change_ship_class.
EDIT: This PR now also properly accommodates .tbm parsing.
This fixes #1969.
=> fix some bugs with the per_ship_warp_type feature

code/graphics/paths/NanoVGRenderer.cpp
This was causing issues since the new bitmap data was never stored in
the internal buffer FSO uses for getting the image data. Instead, it was
only uploaded to the GPU texture which could be deleted at any time.
This was the case when changing the "3D Hardware Texture" setting which
causes a texture flush.
This fixes #1961.
=> Update internal NanoVG bitmap data buffer when updating texture

code/parse/sexp.cpp
This is a follow-up to commit 1614384a6ab35a5e63909dd825a6a6acb3d31aff.  `Error` is to be avoided if possible because almost all sexp problems are recoverable, and we don't want to bring the entire game to a halt.
Also add some more information to warnings about sexp operators on strings.
=> replace most Errors in sexp.cpp with Warnings

code/particle/ParticleEffect.h, code/particle/ParticleSource.cpp, code/particle/ParticleSource.h, code/particle/ParticleSourceWrapper.h, code/particle/effects/BeamPiercingEffect.cpp, code/particle/effects/BeamPiercingEffect.h, code/particle/effects/CompositeEffect.cpp, code/particle/effects/CompositeEffect.h, code/particle/effects/GenericShapeEffect.h, code/particle/effects/ParticleEmitterEffect.cpp, code/particle/effects/ParticleEmitterEffect.h, code/particle/effects/SingleParticleEffect.cpp, code/particle/effects/SingleParticleEffect.h, code/particle/util/EffectTiming.cpp, code/particle/util/EffectTiming.h, code/utils/RandomRange.h
This allows specifying how many times per second an effect should be
triggered for a particle source instead of triggering the effect every
frame. This will allow modders to achieve more consistent particle
effects regardless of FPS.
=> Add support for "Effects per second" feature

code/mission/missionmessage.cpp
`MESSAGE_SOURCE_SPECIAL` indicates messages whose sender starts with "#", indicating that it's not a ship; however, the code was looking up the source as a ship name regardless, and if the message had a persona set, failing to find that ship name would result in the message failing to send. Commit f67596bc5e6b0253a70bfc6f8d389396b204f5c7 (a.k.a. SVN revision 5383) was supposed to fix this, however it was checking if `q->source` was `MESSAGE_SOURCE_SPECIAL` when `q->source` was one of the `HUD_SOURCE_*` #defines (specifically, `MESSAGE_SOURCE_SPECIAL` resulted in `HUD_SOURCE_TERRAN_CMD`). It turned out there was an unused `HUD_SOURCE_*` #define which behaves identically to `HUD_SOURCE_TERRAN_CMD`, namely `HUD_SOURCE_IMPORTANT`. By making `MESSAGE_SOURCE_SPECIAL` use `HUD_SOURCE_IMPORTANT` …
=> Avoid ship name lookup when sending "special" messages.

code/scripting/api/libs/base.cpp
When setting `LUA_ADDITIVE_BUTTON_CONTROL`, the `setButtonControlMode()` function (in `l_Base`) would return "LUA OVERRIDE BUTTON CONTROL", and when setting `LUA_OVERRIDE_BUTTON_CONTROL`, "LUA ADDITIVE BUTTON CONTROL" would be returned. This commit simply swaps these back so that the appropriate return value is with the corresponding enum value.
I'm assuming this won't break any existing scripts (because there's rarely a reason to look at the return value when setting the button control mode), but it's theoretically possible it might.
=> Swap back return values for lua setButtonControlMode() function.

code/scripting/api/objs/control_info.cpp
When using a string to define the appropriate control in the `useButtonControl()` function (in `l_Control_Info`), the command definition was being divided by 32 when the appropriate mathematical operator was modulo; as a result, the only controls that could actually wind up being referenced are these four: `TARGET_NEXT`, `MAX_THROTTLE`, `END_MISSION`, and `MULTI_MESSAGE_HOSTILE`. By using the modulo operator, the string lookup now appropriately references the relevant button.
=> Use modulo instead of division in Lua useButtonControl() function.

code/scripting/api/objs/control_info.cpp
If various functions on `l_Control_Info` were called while `Player` was `nullptr`, FSO would CTD due to a null pointer dereference. This commit adds `nullptr` checks to avoid the problem.
=> Add checks for Player being nullptr to l_Control_Info.

code/hud/hudtargetbox.cpp, code/ship/ship.h, code/weapon/weapons.cpp
Somewhere along the line, "sentry gun" was replaced with "escape pod" in the inverted is_flyable check.  This made the game think an escape pod wasn't flyable and therefore things like waypoint orders were not displayed.  This PR fixes that.
Additionally, I fixed a potential bug in weapons.cpp where the HUGE flag should really check against HUGE ships.  And there's a no-op formatting change in hudtargetbox.cpp.
=> fix some flag information

code/ai/aicode.cpp, code/mission/missionparse.cpp, code/parse/sexp.cpp, code/scripting/api/libs/mission.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/ship/shipfx.h
The core bug fixed here is #1982.  After ship_create sets up the ship, parse_object_create_sub does further initialization by copying some values from the parse object.  In most cases there are sensible defaults, but a few special cases require some post-processing...
- ship sounds
- the new way of initializing warp effects to allow per-ship customization
- intrinsic-no-shields
- an arrival entry in the mission log
- script hooks
I also took a further look at normal ship creation and tweaked some things...
- initialize ai mode in ai_object_init
- remove redundant assigment of ship name from parse_object_create_sub (it's also done in ship_create)
- remove redundant goal clearing from parse_object_create_sub (it's also done in ai_clear_ship_goals via ship_create)
- avoid overwriting the …
=>  some tweaks and minor improvements to ship initialization

code/parse/sexp.cpp
Currently is-docked always returns true if only a single argument is
supplied. This is probably as designed (except for not erroring on a
single arg) however it's quite easy to update to work for a single
argument and this case is useful for FotG, and might be useful for
others.
=> make is-docked work with a single argument

.circleci/config.yml, code/cutscene/cutscenes.h, code/gamesnd/gamesnd.h, code/pilotfile/csg_convert.cpp, code/pilotfile/pilotfile_convert.cpp, code/pilotfile/pilotfile_convert.h
Given the recent changes at TravisCI it seemed like a good idea to investigate other possibilities for handling our CI. This adds the configuration necessary for compiling our code with CircleCI for Linux.
Their resources also appear to be better than TravisCI so builds complete much faster and their workflow system for building a pipeline of builds is also very interesting.
There were a few code changes required for making the newer clang version happy but nothing major.
=> Add CircleCI config file

code/cfile/cfile.h, code/scripting/api/libs/cfile.cpp, code/scripting/api/objs/file.cpp, code/scripting/api/objs/file.h
This adds some auto-closing code to the scripting API of the CFile
system. If a file has to be auto-closed then an error will be displayed
to let the the script writer know that something is wrong.
This should not break existing scripts since causing file handle leaks
should never happen and if it does, this will make it easier to find
these issues.
This depends on the changes of #1881.
=> Add scripting file handle auto-closing and error message 

code/mission/missionparse.cpp, code/object/collidedebrisship.cpp, code/object/collidedebrisweapon.cpp, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/object/collideweaponweapon.cpp, code/object/object.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp, code/weapon/beam.cpp
In this block of code, the conditions were checked with a set of four hook variables but then subsequently run with only two.  This adds all four previously used variables.  More importantly, it adds the hook variables with expected and user-friendly names, since 'self' and 'object' are not necessarily intuitive.
This should fix #1996.
=> make sure to set all hook variables when the script hook is called

.travis.yml, ci/travis/check_release.sh, ci/travis/ftp_deploy.sh
We need to build our own `curl` binary since Homebrew doesn't support `--with-libssh2` anymore.
I've also added caching to both the Linux and macOS code to avoid rebuilding curl for each nightly.
Not sure if the caching actually works but according to [the docs](https://docs.travis-ci.com/user/caching/) it should work.
=> Compile curl ourselves on macOS and cache the result

code/scripting/api/libs/graphics.cpp
This PR fixes a bug where an invalid lua font handle would not be properly returned as invalid. An invalid handle is returned properly if the font name is invalid, but not if the index is invalid. This PR fixes that.
=> Fixes bug with lua font handle

code/object/collideshipship.cpp, code/object/objectdock.cpp, code/object/objectdock.h, code/radar/radarsetup.cpp, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h, code/ship/shipfx.cpp
There's a number of issues fixed here:
* Radar blips of docked ships were the wrong colour in stage 1
* You could target docked ships in stage 1
* Docked ships thrusters were visible in stage 1
* Hyperspace warptype ship could initially appear at their
warp-destination, then spring back to the correct location to complete
the rest of their warpin (because a docked ship had higher speed than
the dock leader)
There may also be a number of other subtle bugs with docked warpin;
e.g. I suspect (but haven't tested) that AI turrets could fire on
docked ships during warpin
These should also be fixed
Lastly, fixes issue #1867
=> Fix issues with docked ships warping

code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilearchive.cpp, code/cfile/cfilearchive.h, code/prefix_header.h
The only thing a CFILE contained was a version field which isn't used
anymore so that could be removed which basically meant that CFILE was
just an indirection to a Cfile_block which I then just renamed to CFILE.
The CFILE type is an opaque handle now since the contents are not
relevant to a user of Cfile.
=> Unify Cfile blocks and CFILE handles

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp, code/hud/hudparse.h
Currently, the player is unable to see a RTT hud gauge if in chase view. This adds an option in the `hud_gauges.tbl` that tells the game whether to draw a gauge based on if chase view is the active view. So for example, a modder using RTT mapped gauges can now make a HUD that displays on the interior of the ship (ie RTT with the cockpit model) and a HUD that displays when the player switches to chase view. If merged I will update the wiki for usage in `hud_gauges.tbl`.
=> Add `Chase View Only` Option for HUD Gauges

code/controlconfig/controlsconfigcommon.cpp, code/hud/hud.cpp, code/localization/localize.cpp, code/menuui/playermenu.cpp
This commit add Ids for existing strings, that were not translateable before. Now they can be translated through the strings.tbl.
The string limit of FSO was bumped up to 1641 for this.
The following is translateable now:
- The 'or' seperator in the Keypress Directive gauge, if one function is bound to two keys.
- The Supernova warning.
- The error message that is displayed before the pilot selection screen, if something is wrong with the loaded modification.
=> New translateable strings for the strings.tbl

code/mission/missionload.cpp, code/mission/missionload.h, code/mission/missionparse.cpp, code/mission/missionparse.h, code/scripting/api/libs/mission.cpp, fred2/freddoc.cpp, fred2/freddoc.h, fred2/fredstubs.cpp, freespace2/freespace.cpp, freespace2/freespace.h, qtfred/src/fredstubs.cpp, test/src/test_stubs.cpp
Previously, when a sexp syntax error was encountered, the engine would display an Error dialog which would usually result in aborting the entire game session.  This PR changes things so that a Warning dialog is displayed and the engine stops loading the mission.
This addresses one of the complaints in #1995.
=> cancel mission load when a syntax error is found

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp, code/hud/hudparse.h, code/hud/hudscripting.cpp, code/hud/hudscripting.h, code/scripting/ade_args.cpp, code/scripting/ade_args.h, code/scripting/api/objs/hudgauge.cpp, code/scripting/api/objs/hudgauge.h, code/source_groups.cmake
The new gauge can be accessed by the scripting API with which a function
can be set which will be called when this gauge is rendered. This can be
used for exposing the HUD gauge positioning and RTT options to the
scripting API without a lot of work needed for the script writer.
There is currently only one rendering function implemented since this is
only a proof of concept.
=> Add new HUD gauge type for scripted gauges

code/scripting/api/objs/hudgauge.cpp
Adds an additional draw function, `drawImage` to the new Scripted Gauge API. It testing it is most useful when using with a dynamic texture, ie per-frame changes can be drawn to the dynamic texture, then the texture is drawn to the scripted HUD gauge. In other words, a scripter can draw whatever they want to a dynamic texture then simply just use one line (`:drawImage`) to have it all be updated on on the scripted HUD gauge. 
Putting this here just for my reference as well. 
```
$On Gameplay Start: [
if dy_texture == nil then 
dy_texture = gr.createTexture(250, 250, TEXTURE_DYNAMIC) --canvas_size, set by gauge type
end
local scriptied_gname = "Custom Gauge" --or whatever the name of the scripted gauge is in hud_gauges.tbl. 
if hu.getHUDGaugeHandle(scriptied_gname) and …
```
=> Add `drawImage` to Scripted Gauge

code/hud/hud.cpp, code/hud/hud.h, code/scripting/api/objs/hudgauge.cpp
This adds the following functions to the scripted gauge API: `drawCircle`, `drawRect`, and `drawLine`. Also note that I created an additional function, for `HUDGauge:renderCircle_unfilled`, because the precedent shown by having two functions for `gr_unfilled_circle` and `gr_circle` and adding a fourth argument to `renderCircle` seemed to affect a lot of other functions.
=> Add more draw functions to scripted gauge

code/scripting/api/objs/hudgauge.cpp
Fixes a minor bug that incorrectly draws Rectangles too big on a scripted HUD gauge. The third and fourth arguments needed to be width and height, not x2 and y2.
=> Fixes minor bug with `drawRectangle` for scripted HUD gauges

ci/travis/check_release.sh
This reverts commit 5fa5a199bf1ed533f78a652b09baaba937c911fe.
This should hopefully fix generating the VERSION_NAME on Travis CI.
=> Revert "Test the upload"

code/hud/hudartillery.cpp, code/hud/hudartillery.h
Allows subspace strikes to choose which fireball to use for the warp effect. If absent, `FIREBALL_WARP` is used as the default (which was the previous hardcoded behavior).
"+WarpEffect:" can be specified as either an index or using the fireball's unique ID.
Requested (and tested) by @AxemP.
=> Add "+WarpEffect:" field to ssm.tbl.

code/model/model.h, code/model/modelread.cpp, code/model/modelrender.cpp
Add a submodel property that overrides the hard-coded distance
multipliers applied to the distances at which details boxes & spheres
are rendered. The distance multipliers are set by the "model detail"
setting in the options screen. Note that this is different to the LOD
distance multipliers which are not hard-coded.
This allows some more creative uses of detail boxes & spheres, e.g. to
stop models subobjects from being rendered when they're out of player
view. Past testing showed a reasonable performance improvement with
complicated models.
This is a submodel property rather than global, or a ship flag, to allow
flexibility, i.e. a single model could choose this option only for the
submodels that want to use detail boxes/spheres in this fashion, while
other detail boxes/spheres use the …
=> detail boxes can ignore default distance scaling

code/model/modelrender.cpp, code/model/modelrender.h, code/ship/ship.cpp
This PR fixes issue #2015, which is a bug where using `show ship` caused detail_box calculations to incorrectly use world coordinates for submodels on the player's ship, rather then the correct local coordinates.
This PR replaces the one that got mangled by re-basing issues. I apologize for the inconvenience.
=> Fix `detail_box` calculations when using `show ship`

code/model/modelrender.cpp, code/model/modelrender.h, code/ship/ship.cpp
This provides a cleaner fix for the bug where using show ship caused detail_box calculations to incorrectly work on the player's ship. 
This PR also reverts the changes made by PR #2018 (that's why there are so many deletions).
Sorry for the repeated PR's and big thank you to m!m for his assistance and patience.
=> Cleaner fix for show-ship bug with detail_box calculations

code/scripting/api/libs/audio.cpp, code/scripting/api/objs/message.cpp, code/scripting/api/objs/sound.cpp, code/scripting/api/objs/sound.h
This can be used by scripts for explicitly freeing up some memory when
necessary.
=> Add unload function for freeing audio memory of a soundfile handle

code/hud/hudtarget.cpp
Fixes #1827
Every g3_start_frame must have a matching g3_end_frame. Thus, a return in the middle of a function after an opening g3_start_frame must make sure to call g3_end_frame before it leaves to avoid a dangling frame
context.
As described in the bug report a floating point rounding issue could be the trigger for the problem.
=> fix bug #1827: targeting brackets stuck in top left corner

code/parse/sexp.cpp, code/parse/sexp.h
Several changes here:
* Made the "magic number" sexp return values even more unlikely, in case FREDders want to use numbers around -37000
* Optimize `eval_sexp` by not running the positive/negative number reconciliation code if the negative number is a magic number
* ~~Always check `SEXP_KNOWN_TRUE` when checking `SEXP_TRUE`, and likewise for false. This may not be needed, but better safe than sorry.~~
* Add `is-nan` which checks for not-a-number values
* Add `nan-to-number` which casts NaNs to 0
* Add `functional-if-then-else` which is like the ?: ternary operator
=> Three sexps and some sexp improvements

code/scripting/api/objs/vecmath.cpp
When setting individual elements of a matrix through lua, we need to mark the matrix as either having out of date angles or out of date vectors.
This fixes #2031
=> Fix for error in validation of matrices accessed by lua

code/ai/aigoals.cpp
Making wp_list null lets ai_mission_goal_achievable reset the waypoints
list correctly, otherwise it thinks the waypoints are ok when in fact
something has invalidated them
Fixes #2033
=> Null wp_list on setting order, same as for sexps

code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp, code/ship/shiphit.h
This allows modders to restrict the amount of rotation in a death roll.
It's fairly simple to fit in with the existing code which has a lot of
hard coded constants. The intended use case is to restrict pitch &
heading changes so there's less chance of rapid forward rolls or flat
spins, especially with faster-than-FS2 ships.
I'd almost rather rewrite the entire code to dynamically use ships mass
& velocity except for retail compatibility issues.
=> Allow death max rotation to be set per ship

code/parse/sexp.cpp
While scouring sexp.cpp for all the NaN changes (to be in a future PR), I made a number of miscellaneous changes not directly related to the NaN fixes.  I thought it would be good to make a separate PR so the NaN PR is not unduly cluttered.
By the way, this should fix the `query-orders` sexp.  That sexp was using `eval_sexp` when it should have used `eval_num`.
=> various sexp formatting and cleanup changes

code/object/objectsnd.cpp, code/ship/ship.cpp, code/ship/ship.h
Previously, flyby sounds were only specified on a per-species basis. This PR allows each ship class to use a specific flyby sound. This will allow modders to set the custom sound in `ships.tbl` using the new `$Flyby Sound:` field.
=> Adds per-class flyby sounds

code/parse/sexp.cpp, code/parse/sexp.h
This PR adds a sexp that returns the integer value of a ship or wing hotkey. No hotkey returns -1, F5 returns 0, F6 returns 1, ... The sexp takes one argument, the ship or wing name.
=> Adds `get-hotkey` sexp

code/parse/sexp.cpp
In single-player, or while running as a server, `sexp_deal_with_ship_flag()` makes sure that `object_flag`, `ship_flag`, and `p_object_flag` aren't `NUM_VALUES` (i.e. not set) before trying to call `flags.set()` with them. However, the client code in `multi_sexp_deal_with_ship_flag()` had no such security checks, and as such would try to set `NUM_VALUES`, which is outside the range of valid flags; this led to a crash in Release builds and an Assertion otherwise.
=> Check flags are valid in multi_sexp_deal_with_ship_flag().

code/scripting/scripting.cpp, code/scripting/scripting.h, code/ship/ship.cpp, code/ship/shiphit.cpp
Implements the feature request from issue #610.
As an aside, this PR also patches the `ship_set_subsystem_strength` function (which is only used by the debug console and in the event you fire at your training instructor) to use the same code as the `set-subystem-strength` sexp.  This properly handles submodels blown off, sounds, etc.
=> add $On Subsystem Destroyed scripting hook

code/graphics/grbatch.cpp, code/graphics/opengl/gropenglstate.cpp, code/render/batching.cpp, code/stats/scoring.cpp
I was looking for places where `SCP_unordered_map` could be used instead of `SCP_map` and found a few spots where iterating through maps could be improved.
This PR removes some pointless checks for empty maps and converts a few `map::iterator`-based for loops to range-based fors.  This will make it easier for a possible switch to `SCP_unordered_map` in the future but even if this doesn't happen, it still makes the code more readable.
Note that there are a some explicit `SCP_map::iterator` type declarations which I did not switch to `auto` because I don't know what the policy is for iterators declared outside a loop.  I can change those if desired.
=> Clean up map::iterator usage

code/ship/ship.cpp, code/ship/ship.h
This PR allows modders to set, on a per ship class basis, the fields for what hull and shield integrity the AI wing-men send the "Help" message at. One good use case is when ships have low hit points, thus now the modder can set AI can call for help sooner then at simply 30% hull.
=> Add per ship class options for when AI sends "Help Me" message

code/parse/sexp.cpp, code/ship/shipfx.cpp, code/ship/shiphit.cpp
Fixes #605.  If a parent subobject is destroyed while a child subobject still has hitpoints, the child subobject is destroyed as well.  Conversely, if a child subobject is repaired while a parent subobject is destroyed, the parent subobject is also repaired.
~~This PR is based on the `on_subsystem_destroyed` branch of PR #2037.  I will rebase this onto master after that PR has been merged.~~  Okay, this PR is now based on master.
=> properly handle destruction/repair of subsystem tree

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/model/modelrender.cpp
This PR adds a table entry that allows modders to specify the RGBI values for the damage and emp arc colors (which were previosuly hardcoded).
This option adds the table entry to `Game_settings.tbl` under `#Graphic Settings` with the lines:
```
$EMP Arc Color:
+Primary Color Option 1: rgb
+Primary Color Option 2: rgb
+Secondary Color Option 1: rgb
$Damage Arc Color:
+Primary Color Option 1: rgb
+Primary Color Option 2: rgb
+Secondary Color Option 1: rgb
```
=> Adds Table Option to Modify Arc Colors

code/ai/aicode.cpp
Current the AI always selects capital+ weapons vs big/huge ships. This
makes the AI take shields into accounts, and not use the weapon if
either the shields are still up, or the weapon isn't good vs shields.
I don't greatly like the magic number 1.33 to determine if a weapon is
good vs shields, I'm happy to take alternative suggestions. I have
checked DE, WoD & BP tables and I don't think this change will affect
any of them (picked them because they either use capital+ weapons or
have shielded capships)
There's one DE weapon that the AI won't select anymore while shields
are up; however its fluff says it's bad vs shields and suggests a
paired shield-breaker so think it should be OK.
=> Fix AI selection of capital+ weps vs shields

code/model/modelcollide.cpp, code/model/modelread.cpp, code/ship/shipfx.cpp
We should not be referencing bsp_info for submodel data specific to live game objects. When I migrated the rendering and collision code to the polymodel instance system, these stragglers fell between the cracks.
This should fix https://github.com/scp-fs2open/fs2open.github.com/issues/2046
=> Make sure various model rendering/collision code reference submodel instances instead of the prototype data

code/ai/aigoals.cpp, code/mission/missionparse.cpp, code/mission/missionparse.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h
Evaluating `has-departed-delay "Alpha 1"` during a debriefing stage yields incorrect results in current FSO builds.  This is because the sexp short-circuits and evaluates to false if the ship hasn't arrived yet.  Unfortunately, the arrival check was flawed.
To handle respawns in multiplayer, player ships are not removed from the arrival queue.  A naive test for a yet-to-arrive ship by checking the arrival queue will therefore return false positives for player ships.  The solution is to not only check the list but also check whether the ship was in fact created.
I added a new function `mission_check_ship_yet_to_arrive` and substituted it for `mission_parse_get_arrival_ship` where appropriate.  I also checked all uses of `mission_parse_get_arrival_ship` that were *not* substituted to make …
=> properly indicate that player ships have departed at the end of a mission

code/missionui/missionweaponchoice.cpp
Previously if the 3D weapon flag was used it would always create a weapon icon and override any pre-existing icons the modder would specify. This PR fixes that by adding an extra set of conditionals, which specifies two things.
1) If a weapon has an icon file name then that icon should be used and not overwritten by an image of the pof.
2) If the weapon does not have an `$Anim:` but does have a model then that model should be used if the 3D_weapon flag is enabled.
=> Bug fix: adds missing conditional when using weapon icons and 3D weapon selection

code/inetfile/chttpget.cpp
Coverity spotted this dead code.  Looks like the original coder forgot that they had checked for !p already or was a case of mindless copy-pasting code..
Because
pcode = strchr(p,' ')+1;
keeps pcode from being null, it looks like it is safe to remove.
=> Coverity 1093382

code/ai/aiturret.cpp
Extremely rare bug caused by use of multiple protect from weapon flags. One of the Ai-Turret functions was setting only one of the flags because "else if" was typed instead of "if".
Possible improvements to related files to come in *other* PR's.
=> Fix#1791 ChangeIFF & Laser_Flag

code/physics/physics.cpp
Copy paste error, I can think of no reason to compare Max y and Min z, and the code afterward is using it as just a factor in multiplication.  My guess is that it would just cause unpredictable results, especially at coordinates with high y or z values.
=> Coverity 1093370

code/jpgutils/jpgutils.cpp
The assert already checks for the file being Null, so why check again?
In case anyone decides to remove the assert, let's just comment the check out.  (But in my humble opinion, it's a big deal if we're trying to open a jpeg that doesn't exist.)
Both checks were introduced during a bugfix early in the SCP.
=> Coverity 1093387

code/parse/sexp.cpp
This adds `set-object-position` functionality for ships and wingmen still on the arrival list.  Requested by JSRNerdo.
EDIT: Also added `set-object-orientation`, `set-object-facing`, and `set-object-facing-object`.
=> Allow positioning sexps to work on ships yet to arrive

code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/LuaSEXP.cpp
NaN should propagate through the SEXP tree, but not all SEXPs do this properly.  The problem was made worse after I introducted `eval_num()` which silently ignored NaN values.  This commit adds new boolean arguments to `eval_num()` to flag NaN results, and changes all calls of `eval_num()` to properly handle the new arguments.  Additionally, this adds `eval_nums()` and `eval_array()` functions to more smoothly handle cases where many numbers appear in a row.
=> when evaluating numeric SEXPs, handle NaN properly

code/lab/lab.cpp
This fixes bug #1987. A more detailed analysis and reasoning is given there.
=> fix bug #1987: thruster rendering in lab

code/ai/aicode.cpp
Adds a check to see if the subsystem is the same before resetting aspect lock.
More of an enhancement to expected behavior than a bugfix. 
#1916
=> "Fix" 1916

code/parse/sexp.cpp
Minor typo, doesn't really matter, but it's so easy to fix.
I checked the diff, this typo is only in comments or sexp descriptions, so shouldn't impact any usage.
=> fix typo: defualt->default

code/parse/sexp.cpp
This re-implements the eval_nums function to use C varargs, instead of C++11 template parameter packs.  This is necessary because Visual Studio has a bug where template parameter packs corrupt heap memory somehow.
This should fix #2081.
=> fix for issue #2081

code/parse/sexp.cpp
This reverts #2083 and implements a proper fix.  Turns out nothing was wrong with Visual Studio; instead the heap was corrupted by inadvertent assignments to `Sexp_nodes[-1]` in `rand_sexp`.
This should really fix #2081.
=> Issue 2081 actual fix

.travis.yml, code/mod_table/mod_table.cpp, code/network/psnet2.cpp, code/network/stand_gui.cpp, code/osapi/osregistry.cpp
This will make the PR builds fail if one of the Windows builds (MSVC or MinGW) fails so that no new compile breaks are introduced on those platforms.
=> Do not allow failure for Windows Travis builds anymore

CMakeLists.txt, ci/appveyor/build.ps1, cmake/toolchain-msvc.cmake, code/globalincs/crashdump.cpp, code/globalincs/crashdump.h, code/source_groups.cmake, freespace2/freespace.cpp, qtfred/CMakeLists.txt
This will write Mini dumps in the event that the executable causes a
crash. This will allow us to take a closer look at any crashes without
having to reproduce them. This will also upload the PDBs of the builds
to our servers so we can use those for resolving symbols in the crash
dumps.
=> Write Minidumps when a crash occurs

code/io/joy-sdl.cpp
Not sure why we didn't catch this earlier but this should hopefully fix
the crash. The cause was that we constructed an SCP_string from a null
pointer instead of using the empty string as the default.
=> Fix crash in joystick code

code/parse/sexp.cpp
As per the discussion in https://github.com/scp-fs2open/fs2open.github.com/issues/2092,
if you specify the turn time, these can behave quite weirdly.
Some mods that we don't want to break backwards compatability with use
that mode, but at least we can note the pitfalls in help.
I don't love the text I wrote here, open to suggestions.
=> update set-object-facing and set-object-facing-object sexp help

code/cfile/cfilesystem.cpp
When running a mod on non-windows, that isn't packed into VP files, the
mod can break when loading. On non-windows filesystems, the file
order isn't guaranteed to be alphabetical (but it is on Windows).
As a result, we load tables in an effectively random order.
Lots of mods rely on the filesystem ordering to e.g. implement a very
loose dependency system for their lua scripts.
Referenced on the forum here:
https://www.hard-light.net/forums/index.php?topic=95750.msg1885275#msg1885275
Here's a log from Solaris failing to run:
https://fsnebula.org/log/5d7b4414cb0d332b466b5ee2#True-138
Instead, always sort filesystem listing by name *before* applying the
provided sort order.
I've built a few different versions of this patch, and like this one the
best. The other ones I tried:
1. Adding a …
=> fix modular table loading errors on non windows

code/parse/parselo.cpp, code/parse/parselo.h
bookmark stack.
The stack is First In Last Out, so the parser will resume its most recently saved parsing location before going onto the oldest.
Another mechanism will be needed to ensure double-parsing doesn't occur when resuming from a bookmark, such as an [indexer](https://github.com/z64555/fs2open.github.com/tree/feature/parse_index).
=> Extends the existing parse pausing system (used by bmpman) to use a

fred2/missionsave.cpp, fred2/shipeditordlg.cpp, qtfred/src/mission/missionsave.cpp
Replacement PR for #595.  This consists of @downwash's changes plus @MageKing17's suggestion to add the departure cue check on mission save. 
This should also fix Mantis 2869.
=> Only update arrival/departure location if ship is not part of a wing

code/parse/sexp.cpp
The default loop increment is 1, not 0.  When for-counter was converted to use eval_nums in PR #2035, this was inadvertently broken.
=> fix default loop increment in for-counter

code/io/keycontrol.cpp, code/menuui/optionsmenu.cpp
This PR does several things:
1) Properly pause and unpause music when Escape is pressed
2) Properly pause and unpause music when F2 is pressed (which is how F1, F3, and F4 handle it)
3) Continue to play music when F2 is pressed while the player is in the main hall
4) Properly fix the subspace sound issue; PR #2078 put the fix in the wrong place.
This fixes #2099 and #1433.
=> Handle pausing and unpausing music in certain screens

code/parse/sexp.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
~~The grant-medal and was-medal-granted sexps will now translate medal names, in the same way that tech-add-intel-xstr translates intel entries.  There is also some minor cleanup and the specifying of correct default -1 numbers for the xstr-capable sexps.~~
~~This fixes #1285.~~
With Novachen's comment, this PR drops the modifications to `grant-medal` and `was-medal-granted`, and just does some cleanup with XSTR and CTEXT.
=> miscellaneous XSTR cleanup

code/parse/parselo.cpp
This bug has been around since the original public source code release!
The error message character calculation did not agree with the actual error check.  This PR fixes that.  Thanks to Novachen on Discord for discovering this.
=> fix bug in copy_text_until error message

code/cfile/cfilesystem.cpp
The intent behind this sort (added in #2094) was to make the order of files returned by the filesystem consistent across platforms; however, the sort occurred not only after the filesystem search, but after the packfile search, which changed the order files load in on all filesystems instead of making it consistent. This moves the sort to be after the filesystem search but before the packfile search, hopefully making load order consistent once more.
=> Move filename sort in cf_get_file_list() to before packfile search.

code/pilotfile/csg.cpp
When loading a .plr file, `HUD_config.rp_dist` is loaded and then sanity-checked; if the value is out of bounds, a `Warning` is generated and `RR_INFINITY` assigned. `HUD_config.rp_dist` is also loaded when loading a .csg file, however the sanity check isn't present; this copies the block over so the behavior is identical.
=> Make .csg loading code check rp_dist, just like .plr loading does.

code/pngutils/pngutils.cpp
This probably isn't the kind of information that should appear in the average debug log, since it's unlikely to be of use in standard troubleshooting.
=> Give PNG warnings their own category, so they're hidden by default.

code/model/modelread.cpp, code/parse/sexp.cpp
Just a couple random things I came across while looking for other things; "glowpoint present" should be "glowpoint preset", and there is no "op_num function".
=> Correcting a couple debug typos.

.clang-tidy, code/cfile/cfilesystem.cpp, code/osapi/osapi.cpp
Since FSO does not support Unicode characters in filesystem paths on
Windows yet, it is necessary to catch these issues early on and display
an appropriate error message. These changes do that by going through the
path with our UTF-8 decoder and detecting any characters that are out of
the ASCII range.
=> Fix #2086: Detect unsupported characters in root paths

code/object/object.cpp
Since the Lua state is destroyed before all the object events, this was
causing issues. This should fix that by clearing the events when the lua
state is destroyed.
=> Clear object events when Lua state is shut down

code/ship/ship.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Although not technically a bug, several mods have been misled by the description of the "$Rearm Rate:" weapons table setting, and specifying an initial ammo value that is less than 100 for ballistic primaries would force the ballistic ammo to be loaded all at once, with "$Rearm Rate:" just specifying how long that one load would take.
This allows modders to use more realistic behavior for things like anti-turret ballistic primaries, where initial ammo could be in the thirties instead of the thousands, so that any number above zero can be added per load.  
Paired with this pull request, I am going to update the wiki entry for "$Rearm Rate:" to reflect what it actually does (tells the engine how many times per second to add munitions)
#1848
=> For Issue #1848 - Add option to change default rearm values

code/ai/ai_flags.h, code/ai/aicode.cpp, code/parse/sexp.cpp, code/physics/physics.cpp, code/physics/physics.h, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp
Add some useful flags for ship maneuvers:
* don't bank when turning (changing heading does not change bank)
* don't clamp max velocity (maneuvers can exceed tabled values)
* instantaneous acceleration
Also allow perpetual (non-expiring) ship maneuvers.  These flags are available in both sexps and scripts.
=> Enhanced ship maneuvers

code/physics/physics.cpp
There was an extra check specifically for reverse velocity that I missed.
=> fix an oversight with dont-clamp-max-velocity

fred2/missionnotesdlg.cpp
`m_end_to_mainhall` was missing for some reason, and `m_override_hashcommand` copied it and thereby made the same mistake
=> add missing lines for flags

code/fs2netd/tcp_client.h, code/globalincs/linklist.h, code/globalincs/pstypes.h, code/graphics/2d.h, code/graphics/line.h, code/network/multi_options.cpp, code/network/multi_pxo.cpp, code/network/multi_rate.cpp, code/network/multi_respawn.cpp, code/network/multi_team.cpp, code/network/multi_voice.cpp, code/network/multimsgs.cpp, code/network/multimsgs.h, code/network/multiui.cpp, code/object/object.h, code/pcxutils/pcxutils.cpp, code/tracing/Monitor.h, code/weapon/beam.cpp, fred2/fred.h, freespace2/freespace.cpp
These Coverity issues are all caused by the same code being copy and pasted in three different places.
There does not seem to be actual danger of the negative array access, but the changes that "fix" it are also slight optimizations (placing a few variable assignments outside loops so that it only has to call the function once).
In short, I am basically just moving code around to avoid duplicate checks that coverity is suspicious of, and in other places checking for the negative array index explicitly.
=> Address Coverity 1297186,187,188, 190

code/fireball/warpineffect.cpp
Covertity is complaining about us initializing members of the verts array while the first vert has members that are uninitialized.
So this is just a quick change to us excplicitly initializing r, b, g, and a of verts 1-4, from the r, b, g, and a that we already set in vert 0.
=> Coverity1370825

.github/workflows/pr-workflow.yaml, .travis.yml, code/mission/missionparse.cpp, code/scripting/lua/LuaFunction.cpp, code/scripting/lua/LuaFunction.h, code/scripting/lua/LuaValue.cpp, code/scripting/lua/LuaValue.h, code/stats/scoring.h, code/weapon/weapons.cpp, qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp, qtfred/src/ui/dialogs/EventEditorDialog.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Only one warning type this time, the implicit copy operator for types
with a copy constructor has been deprecated so we need to delcare them
ourself.
=> Update Travis to GCC 9 and fix warnings

code/ai/aigoals.cpp, code/parse/sexp.cpp
1) When considering whether a disable/disarm/destroy-subsys goal is achievable, check the actual status of the subsystem, not the mission log.  This fixes #2124.
2) When setting the subsystem strengths to random values, submodels should be destroyed or repaired as appropriate (which should have been included in #2042 but was missed) and the aggregate subsystem information should be recalculated (which has been missing since retail).
=> Two subsystem-related fixes

code/network/multi_fstracker.cpp
Due to the order in which the standalone code initializes, PXO table validation and mod detection ends up being broken. This makes sure that PXO is initted when table validation occurs. Is only called when PXO is supposed to be used.
=> init tracker when attempting to validate game data

code/network/stand_gui-unix.cpp
On Linux/OS X the standalone server never reads in the existing user ini file which causes the current config to be reset to default values when it's later saved. Using knossos or other launcher probably hides this bug from being noticed in general.
=> fix standalone causing user config reset on *nix

code/jumpnode/jumpnode.cpp, code/jumpnode/jumpnode.h, code/model/modelrender.cpp
Allows jump nodes to use instrinsic/dumb rotation again by exposing the jump node class to the model instancing code and adding a check for it in modelread.  For #1682
=> Fix Dumb_Rotate Regression

.clang-tidy, tools/CMakeLists.txt, tools/strings_tool/CMakeLists.txt, tools/strings_tool/strings_tool.cpp
This uses clangs LibTooling for parsing the FSO source files to ASTs
which can then be used for extracing the strings used in XSTR calls.
This supports both standard XSTR calls and UI_XSTR definitions and
writes the resulting information in the strings.tbl format to stdout.
It also detects duplicate translation id usages with different text
values.
The tool is entirely optional and is automatically disabled if the clang
development libraries could not be found by CMake. I only tested this
on Linux so other platforms may encounter problems.
=> Add tool for extracting XSTR calls

code/scripting/lua/LuaFunction.cpp, code/scripting/lua/LuaValue.cpp, code/scripting/lua/LuaValue.h
This should never have worked but was only discovered by the recent
switch to the default copy constructors for some reason.
=> Handle invalid Lua reference correctly

.travis.yml, ci/travis/before_install.sh, ci/travis/clang_tidy.sh, ci/travis/install.sh, ci/travis/valgrind.supp
I propose upgrading the version of clang-tidy that we use.  This is motivated by a recent feature:
> New option _MinTypeNameLength_ for **`modernize-use-auto`** check to limit the minimal length of type names to be replaced with `auto`. Use to skip replacing short type names like `int`/`bool` with `auto`. Default value is 5 which means replace types with the name length >= 5 letters only (ex. `double`, `unsigned`).
It drives me nuts when `clang-tidy` wants to use `auto` instead of `int`.  I force-merged a previous PR because I refused to change it, and the same thing is happening again on #2026.
=> upgrade clang-tidy to 8.0, the latest stable release

code/hud/hudparse.cpp, code/math/vecmat.cpp, code/math/vecmat.h, code/radar/radar.cpp, code/radar/radar.h, code/radar/radarngon.cpp, code/radar/radarngon.h, code/source_groups.cmake
This features adds the Ngon radar gauge, which is a derivative of the standard radar gauge. Instead of the standard's oval plot area, the Ngon radar gauge has a polygonal plot area.
The projection algorithm is the same as the standard's radar, so all the Ngon does is clamp the blip to the edges of the plot area.
I also refactored the standard radar plotting code a bit, there was some clamping in the original code that didn't work right, so blips could be drawn on top of the oval's edges. I'm not counting this as a bugfix, though.
Included is a test .tbm that activates a hexagonal plot area with "points up."
[radar_test-hdg.tbm.txt](https://github.com/scp-fs2open/fs2open.github.com/files/767768/radar_test-hdg.tbm.txt)
=> [Feature] Ngon Radar

code/hud/hudparse.cpp
Axem just reported that his custom hud's radar gauge was broken from when we merged the ngon radar.  Taking a look at the code, it looks like what went wrong is that moving gauge_load_common() down the function for modder's convenience broke gauge_load_common()'s assumed parsing order, forcing the retail gauge to rear its head.
Now, I moved it back up to where it was before ngon radar was merged, and Axem reported it fixed.
This just means that for the radar case, "Ngon Sides:" and "Ngon Offest:" have to come before "Origin:" and "Offset:" in the table.
=> Patch n gon radar

cmake/platform-win32.cmake, code/bmpman/bmpman.cpp, code/inetfile/cftp.cpp, code/inetfile/cftp.h, code/inetfile/chttpget.cpp, code/inetfile/inetgetfile.cpp, code/mission/missionparse.cpp, code/network/chat_api.cpp, code/network/multi_pxo.cpp, code/network/multilag.cpp, code/network/multiui.cpp, code/network/multiutil.cpp, code/network/psnet2.cpp, code/network/psnet2.h, code/network/stand_gui.cpp, code/sound/voicerec.cpp, code/stats/stats.cpp, freespace2/freespace.cpp, qtfred/src/ui/QtGraphicsOperations.h, wxfred2/CMakeLists.txt
This moves from winsock 1.1, which was deprecated 20 years ago, to winsock2. Some obsolete platform specific #ifdef's and unneeded windows headers were also removed.
=> switch to using winsock2

code/ai/aicode.cpp
Originally the scripting hook `On Waypoints Done` only provided the ship or wing. This PR adds the the `Waypointpath` that was completed as an additional hook variable (ie hv.Waypointpath). Also, I tested and can confirm the new hook variable works as expected. 
Expands on PR #1985.
=> Add waypoint-path hook variable to `On Waypoints Done` Hook

code/parse/sexp.cpp
The default fade argument is `true`, as specified by the sexp help, not false.  This probably doesn't matter here as the multi packet should receive all sexp arguments anyway, but better to be consistent.
=> very small fix to multi_sexp_close_sound_from_file

code/mission/missioncampaign.cpp
Very small change: Correct me if I'm wrong, but there's no need to try to load the default campaign twice with the same exact function arguments.
=> Only Try To Load a Campaign Once

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/uniforms.cpp, code/lab/lab.cpp
This commit disables emissive lighting on objects by default (as the new HDR process makes it unnecessary) and switches the -no-emissive commandline parameter to -emissive; Setting that parameter will restore the old behaviour. The -no-emissive parameter is retained to avoid user-facing error messages.
In addition, this commit sets the default bloom value to 25.
=> Makes slight adjustments to the lighting defaults.

code/math/vecmat.cpp
It turns out that `vm_extract_angles_matrix` would return a pitch value that was occasionally not the actual pitch from the 3x3 matrix. The pitch line in the code uses a modified `cosp` as the denominator to calculate the pitch angle. I researched what the calculation should be and found a more accurate way than using the modified `cosp` is to use `( fvec.xyz.x^2 + fvec.xyz.z^2 )^0.5` I tested using the new calculation thoroughly and in each test it returned the proper pitch value from the 3x3 orientation matrix.
=> Fixes the extraction of pitch

code/network/multi_fstracker.cpp, code/network/multi_fstracker.h, code/network/multi_options.cpp
This will use default settings related to PXO if one of the following conditions is met:
- `multi.cfg` is missing or a required field is missing
- the settings in `multi.cfg` are from retail FS2
- the settings in `multi.cfg` are from FS2NetD
Fresh installs and mods configured for FS2NetD should now work without any extra steps.
=> sanitize parsed multi.cfg settings for PXO

code/parse/sexp.cpp
Set-secondary-weapon and set-secondary-ammo have been up to now been allowed to exceed tabled cargo sizes, as long as you didn't put a value for requested_ammo in the sexp.
The new limits would be kept from the last secondary weapon in the slot, definitely not ideal behavior.
*Have not yet completely tested this fix!*  I only know the changes to one of the functions works for sure.  The changes to set_secondary_ammo need to be tested as well.
=> Keep set-secondary-weapon from using nonsense

code/graphics/shadows.cpp, code/lab/lab.cpp
1) Initialize `Shadow_quality` to its default value.  According to the Internet, enums (even enum classes) do not have default constructors and are not guaranteed to be 0-initialized.
2) Add an explicit check for `Cmdline_emissive` in the lab instead of a cast.  The cast warning was tripping the warning-as-error checks in continuous integration.
=> Two small fixes

code/ai/aigoals.cpp, code/scripting/scripting.cpp
The `On Goals Cleared` scripting hook resulted in FRED not working, thus this PR adds a check for a valid scripting state to `SetHookObjects` and `RunCondition`. Now FRED will run properly. Fixes PR #2159.
=> Fix FRED not working

code/menuui/readyroom.cpp, code/mission/missioncampaign.cpp
This is a follow-up to #1450, based on feedback and preference.  Instead of always resetting campaign progress, just switch to the campaign.  The player can then explore the tech room database or the finished missions if he chooses.
This also fixes a few bugs:
1) Ever since the tech-database-reset feature was introduced in 2003 or so, the game incorrectly checked the campaign being unselected, not the campaign being selected.
2) Not all campaign loading failure types were recorded in `mission_load_campaign`.
=> don't restart if we are switching to a previously finished campaign

code/mission/missionparse.cpp
Sanity checking for repeat counts shouldn't crash the game, so change from Error to Warning and use a sensible default.  Also copy the check (with minor modification) to also check trigger counts.
=> better sanity-checking for repeat_count, and also check trigger_count

code/sound/ds.cpp
The Z coordinate, from negative to positive, means "front to back", so a Z value of 1.0 (with relative playback, which is what 2D sounds use) means "as far back as possible", i.e. the rear speakers. It's hard to know if this was intentional or not, but feedback from an actual user with a surround setup (@MjnMixael) is that the opposite is preferable.
Fixes #2173.
=> Make 2D sounds play from front speakers instead of rear.

code/controlconfig/controlsconfigcommon.cpp, code/playerman/playercontrol.cpp
Free look will now move in the same directions as ship controls, whether pitch or yaw, and whether using keyboard or mouse/joystick.
Also, remove an inaccurate comment, since freelook has been enabled.
=> Fix Free look turning in the wrong directions

.travis.yml, ci/travis/clang_tidy.sh
First one is to allow MinGW failures since that is unreliable at the
moment. Second one is a fix for the regex used by clang-tidy so that it
doesn't try to analyze CMake files.
=> Fix some CI issues

code/hud/hudtargetbox.cpp
Previously, subsystem brackets in the target ship gauge were not always drawn in the correct location when using RTT with the gauge. This PR fixes that (#1303) by accounting for screen scaling of brackets when using RTT.
=> Fix RTT Subsystem Bracket Bug

code/ship/ship.cpp
If you modified an existing ship type without using `+nocreate`, it would both modify it and add it to the vector again, leading to (at the very least) wasted memory. I copied over some more standard behavior from other parsing functions to hopefully avoid problems with modular objecttypes.
=> Standardize nonstandard "+nocreate" behavior in objecttypes.tbl

code/cfile/cfile.h, code/inetfile/cftp.cpp, code/inetfile/cftp.h, code/inetfile/chttpget.cpp, code/inetfile/chttpget.h, code/inetfile/inetgetfile.cpp, code/inetfile/inetgetfile.h, code/network/multi_pxo.cpp, code/windows_stub/config.h
This will get the inetgetfile, cftp, and chttpget code working again so that it can be used for PXO banners ("ads" on the chat screen). It does not make the banners clickable as that might lead to issues and requires further discussion.
=> fix PXO banners (and inetgetfile stuff)

code/cutscene/cutscenes.cpp, code/cutscene/cutscenes.h, code/pilotfile/csg.cpp, code/pilotfile/csg_convert.cpp
There are now three states for cutscenes: always viewable, where they will appear no matter what; never viewable, where they will never appear; and viewable, which can be modified during the campaign.  Currently cutscenes will go from not-viewable to viewable, but organizing the flags this way will allow a future feature to make cutscenes not-viewable, if that is desired.
There's also a small edit to csv_convert to guard against array overflows.  Not directly related to the feature but it's in the same place and affects the same code.
=> add $Never Viewable flag for cutscenes

code/menuui/barracks.cpp, code/menuui/playermenu.cpp
This will update the pilot file setting that remembers player mode (single or multi). The setting was read and written correctly but never actually updated when changing modes.
=> properly save single/multi mode setting

fred2/fredview.cpp
According to the CreateProcess() documentation, passing NULL in the eighth argument starts a process in the same directory as the original process, which is what we're trying to do.
Please note this is a Windows only solution, and cannot be ported to QTFred.
Addresses #1775, already tested on Release and Debug.
=> Open FSO from FRED Using FRED's Directory

freespace2/freespace.cpp
A quick update that should allow for the FPS gauge to be hidden together with the rest of the HUD. Sounds useful for anyone wanting to take clean screenshots.
Also, thanks @wookiejedi for showing me how to do this.
(Will that even work? that's my first real meeting with GitHub so I'm a bit anxious.)
=> Hide FPS counter with the rest of HUD

code/scripting/api/libs/graphics.cpp, code/scripting/lua.cpp
Previously deprecated enum for lua function hasViewmode() didn't have a warning.  This fixes that. (And only does it once per instance, test confirmed)
Also, I am adding a check to omit it while writing scripting.html so that modders don't accidentally pick start using it.
It still has the correct behavior from the last time it was edited, tested via a script written by @wookieejedi which checks each flag per frame.  The camera modes are enabled via keyboard controls.  Pressing number pad . turns on the external camera, and pressing number pad enter locks that camera.  The script showed that the check for VM_EXTERNAL_CAMERA_LOCKED returned true only when both VM_EXTERNAL and VM_CAMERA_LOCKED are true.
Only step left for us to is change wiki documentation and do a quick check for …
=> Add deprecation warning for VM_EXTERNAL_CAMERA_LOCKED

fred2/fred.cpp, fred2/management.cpp, qtfred/src/mission/management.cpp
This PR allows modders/FREDers to actually see what default controls available are in FRED and not the hard coded ones from `Control_config` that may not be relevant for their mod. For example, a mod may disable many controls and change the default key for many controls in the table, but that is currently not reflected in FRED since FRED simply checks the hard-coded ones from `Control_config`. I tested this and it works exactly as expected.
Example:
Previously, if the modder specifies a default key for, say, `Enter Subspace (End Mission)` as `Enter` instead of `Alt-J` in `Controlconfigdefaults.tbl` then the game will only look for if `Enter` was pressed, whereas the `key-pressed` tree in FRED will not show that and will still show `Alt-J`. Then if the FREDer uses `Alt-J` it won't ever …
=> Allow sexp-tree for `key-pressed` to actually show what the mod will use

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/weapon/weapons.cpp
Adds a new mod table option "$Default Dinky Shockwaves:" that toggles the behavior. See issue #774 for more information.
Needless to say, fixes #774.
=> Make Dinky Shockwaves not dinky by default.

code/lab/lab.cpp, code/missionui/missiondebrief.cpp, code/object/objectsort.cpp, fred2/fredstubs.cpp, freespace2/freespace.cpp, freespace2/freespace.h, qtfred/src/fredstubs.cpp, test/src/test_stubs.cpp
The main file, freesapce.cpp is really hard to undestand, so I tried to clean it a bit.
Removes a lot of dead code in the main file freespace2/freespace.h and .cpp.
Touches some other files, where the code was closely linked to the main file.
This should not change any functionality. 
As before with these fairly large cleanups. I will remove anything where a reviewer has objections, to get the rest moved along and maybe create a new PR with the controversial changes for review.
=> Refactore: cleanup freespace.cpp

code/ship/ship.cpp
This fixes string comparison of ship names in multi.  Any respawned ship would be given a default name and would return false for any future name comparison.
The most visible affect of this was being given the default loadout and fighter on respawn instead of the fighter and weapons you selected, but Taylor was spotting a lot of potential other break points as he looked through other unrelated multi issues on mantis.
This PR replaces the old behavior with a warning that puts the burden on the modder/mission creator to fix the issue.
Change to 0f6240c because I forgot to add the check that the game was in singleplayer mode.
=> Fix Multiple Multi Backend Issues

freespace2/freespace.cpp
When dead, particularly in multi, the mission is closed out even if we aren't done with it. Various menus are still accessible but once you exit the menu it returns to processing the game frame as normal, except everything got closed out which triggers a multitude of asserts and other problems. This should fix Mantis 2377 and anything related.
=> avoid ending mission on death unless we should

code/weapon/trails.cpp
Trails.next is initialized on `level_init()` but not `level_close()`. This can cause issues if `game_frame()` is called after the mission is closed out.
=> fix Trails.next pointing to invalid address

code/math/staticrand.cpp, code/math/staticrand.h
several of the bitwise manipulations on signed integers are technically undefined behaviour.
I made the internal variables unsigned and the results are then converted to signed ints as before.
This should not actually change any observable results.
Did some cleanup as well, while I was at it.
Fixes the first part of  #1210
=> make internal variables in static_rand unsigned.

code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/io/keycontrol.cpp
This PR reduces the number of controls back down to 127 so as to keep multi compatibility.
=> Fixes accidental break with multi due to max key numbers

code/network/multi_observer.cpp, code/network/multi_observer.h, code/network/multimsgs.cpp, code/network/multiutil.cpp, code/network/multiutil.h
Catch-all cleanup of multiutil.cpp. I did my best on these changes, but I am not attached to them, so please make any necessary requests for further changes.  No functionality at all should be changed.
I tried to split the commits into three categories: 
Category 1) the removal of 1 unused function with functionality that exists elsewhere, code that has been commented out since the source code was released, and 2 globals that were there to be stored by the engine and incremented and nothing else. (Their discovery during bug hunting -- and my general mental exhaustion from the same -- inspired this PR)
Category 2) changing NULL to nullptr
Category 3) Changing int3()'s into assertion()'s, error()'s, or verify()'s
=> Multiutil.cpp cleanup#1

code/network/multi_obj.cpp
Already tested. 
Any server build created this year will crash any client connected to it because it will send a packet containing hull updating information, but accidentally unset the flag for new hull info. The client was therefore unaligned with the packet, causing the local subsystem_update array to think there were 255 subsystems.
=> Urgent Multi Fix

code/parse/sexp.cpp
In the case of "any wingman", the sexp logic was flipped.
=> fix disable/enable builtin messages for wingmen

code/missionui/missionweaponchoice.cpp
Overview: This PR restores all expected functionality of the `3D weapon selection` flag while also providing modders with a way to use both 3D models and custom weapon icons simultaneously.
PR #2055 provided a way for modders to use 3D weapons while still using specified weapon icons. Unfortunately, that resulted in weapon icons not changing to an image of the 3D model when the `3D weapon selection flag` was used. It was requested on the forum that this behavior be restored. This PR restores that behavior while still allowing modders to use 3D weapon models and their own weapon icons. 
Instead of the approach taken in PR #2055, this PR will automatically show a 3D weapon model if there is no weapon animation specified and if a weapon tech model is specified. Thus, if a modder wants to use …
=> Restore 3D Weapon Icons when Flag Used

code/def_files/data/effects/fog-f.sdr
This was previously using the wrong direction of the conversion so it
produced wrong values. This should fix that and should hopefully bring
the nebula experience back to how it is supposed to look.
=> Fix fog depth computation

code/math/vecmat.cpp
A few early on descriptions in this file are inconsistent or even plain wrong.  This should correct that.
Also, rename vm_vec_imag() to vm_vec_inv_mag_quick() to better describe what it is.
=> vecmat.cpp quick cleanup

code/mission/missionparse.cpp, code/physics/physics.h, code/ship/ship.cpp
It turns out that the code that set initial ship velocities did not account for local ship rotation changes. This bug is only noticeable when ships are very high speeds, high initial velocities, and have high drift values thus it was never recognized before. This PR fixes that by ensuring that the velocity vectors are set appropriately. As discussed with Goober on Discord, this fixed behavior is indistinguishable when using FS ships and most mods, thus the behavior will be on by default.
=> Fix Setting of Initial Velocity

code/ai/aiturret.cpp
When the `+Max Delay:` and `+Min Delay` for `Fire Wait` were added they were only added to primary firing and not turret firing. Specifically, `turret_set_next_fire_timestamp` uses only `winfo_p->fire_wait` while `ship_fire_primary` uses the delays. Checking with the original author DahBlount they specified it was an oversight, thus this PR fixes that and allows the delays to now work properly with turret firerates.
=> Fix Min and Max Delays for Fire-rate not working for Turrets

code/network/multi_obj.cpp
These function calls have been around since retail.  What they were supposed to do was allow the :V: team to get a baseline of how much data the object updating system would use without the limiting system.
However, the way that multi_rate_add works, is that it say to the limiting system, "The client is getting a lot of data, so limit it some more." And that eventually causes debug build object updates to slow to a crawl, making bug hunting in debug builds difficult.
Removing these functions calls will allow us to track multi bugs a little bit easier (and less frustrating).
=> Remove Debilitating Debug Function Calls

code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp
This PR tidies up the comments in the initial velocity setting, properly sets the player's throttle, and cleans up issues with initial velocity setting and hyperspace warpin types.
Note the removed code block for hyperspace warpin ending was removed because it is not needed, as physics calculations already handles that. Also the calculations that were there did not properly account for initial ship velocity setting.
=> Cleanup Reaming Issues with Initial Velocity

code/ai/aiturret.cpp, code/ship/ship.cpp
Previously, using `Max` and `Min` for fire-rate delays resulted in guns firing that were not within the specified range. This PR fixes that while also simplifying the code. This solution uses `frand_range()`, which is already used in each of those functions so I figured it would be fine to use that function here. It also simplifies the code:
`wait *= frand_range(wip->min_delay, wip->max_delay)`
instead of previously
`next_fire_delay = (((float)rand()) / (((float)RAND_MAX + 1.0f) * (winfo_p->max_delay - winfo_p->min_delay + 1.0f) + winfo_p->min_delay))`.
=> Fixes calculations for random fire rates when using min and max delays

code/ai/aiturret.cpp
In `aiturret.cpp` there is a `mprintf`, `mprintf(("nothing ok to fire\n"));`. This print statement greatly pollutes the debug log in missions with turreted ships. I'm not sure what this message helps debug, thus I propose commenting it out.
=> Proposal to cleanup debug log statement regarding turret fire

code/parse/parselo.cpp
error_display shows the line where the error was detected. Warning
itself is pretty useless for parsing related errors so I replaced all
Warnings (where appropriate) with an equivalent error_display.
=> Replace Warning with error_display in parselo

code/scripting/api/objs/ship.cpp
This PR will allow scripters to change the ship flag `gun convergence`. When enabled this flag uses the normals set in the model to fire from, not the ship's forward orientation. 
For reference:
https://wiki.hard-light.net/index.php/Ships.tbl#.22gun_convergence.22
=> Adds Scripting Support for the Ship Flag `gun convergence`

code/network/multiutil.cpp
Should fix rare multi crash where reserving net signatures for spawned munitions would cause an ushort overflow, triggering an assert in multi_set_network_signature.
Link to mantis issue: http://scp.indiegames.us/mantis/view.php?id=2129
@notimaginative if you could take a quick look to make sure I'm understanding the situation correctly.
In draft because this is not yet tested, because I do not have a multi testing solution yet.
=> Mantis#2129 Address Rare Multi Crash

code/controlconfig/controlsconfigcommon.cpp
For some reason my repo had some critical issues and I was unable to commit to the PR #2210. I have closed that PR and opened this one given the discussion in #2210. The result of that discussion was `but omit line 594`. That is what this PR does.
=> Fix overriding the default values in control table for `disabled`

code/cmdline/cmdline.cpp, code/graphics/2d.cpp
Three main changes in this PR:
1) The enums for the "easy settings" launcher options are now clearer and more explicit, and the enum assignments for a lot of graphics options are now fixed, as they were incorrect due to code rot.
2) Some of the command-line flags options have been recategorized: -window, -fullscreen_window, -nomotiondebris and -noscalevid are now Gameplay; and -fps is now HUD.
3) Since post-processing is required for nebula fading, it now defaults to on, and the flag has been changed to -no_post_process.
=> Clean up launcher settings a bit

code/cmdline/cmdline.cpp
This should avoid causing warnings to pop up when users still have this
in their command line.
=> Add -post_process to deprecated flags section

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/shipfx.cpp
Previously, Engine Wash Intensity didn't actually do anything in the code. This adds a game table setting, `$Use Engine Wash Intensity:`, that let's modders specify to the game to actually take the intensity value into account when calculating engine wash effects.
I was going to use a boolean check at each time `wash_intensity` was used, but since the `ship_intensity` value is cumulative that means that each `wash_intensity` needs to be applied to it's respective thruster before being added to the cumulative total.
=> Allows Modders to Actually Use Engine Wash Intensity

code/hud/hudtarget.cpp
Weapon names with a `#` should not display text after that `#` in the HUD. For the most part this works, but there were a few cases this didn't (such as primaries using the weapon name). This PR fixes two spots that fell between the cracks. Note that line 6109 was added in that section/order because that is where it appeared in that order on line 6026.
=> Fix weapon names not filtering # in HUD gauge

code/hud/hudtargetbox.cpp
It seems that when RTT for cockpits was added that the scaling of ships in the target box fell through the cracks. Properly specifying the `clip_aspect` fixes the issue. This PR fixes issue #2250.
In detail, the `HudGaugeTargetBox::renderTargetSetup` function scales the drawn ship model by `gr_screen.clip_aspect`. When using RTT gauges the clip_aspect changes from the default, so that changed aspect ration needs to be used instead of the default `gr_screen.clip_aspect`.
=> Fixes RTT Target Box Scaling

code/network/multi.cpp, code/network/multi_ingame.cpp, code/network/multi_obj.cpp, code/network/multi_obj.h, code/network/multiui.cpp
This function does not have any contents and should be removed to make the code more readable.
(I'm trying to keep misc changes made in another branch)
It looks like it was here to update a timestamp that might have been planned to be attached to some packets, but no packets use such a timestamp, and such a timestamp could actually be counterproductive, since pings vary.  We rely on sequence numbers within packets instead.
=> CleanUp Unused Function

.github/workflows/pr-workflow.yaml, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/def_files/data/effects/batched-v.sdr, code/def_files/data/effects/default-material-v.sdr, code/def_files/data/effects/deferred-v.sdr, code/def_files/data/effects/effect-screen-g.sdr, code/def_files/data/effects/effect-v.sdr, code/def_files/data/effects/passthrough-v.sdr, code/def_files/data/effects/shield-impact-v.sdr, code/def_files/data/effects/video-v.sdr, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/matrix.cpp, code/graphics/matrix.h, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/util/UniformBufferManager.cpp, code/graphics/util/UniformBufferManager.h, code/graphics/util/uniform_structs.h, code/source_groups.cmake
This is a generic way to get matrix data to shaders without using
(old-school) uniforms. This is another step towards more compatibility
with how new APIs (Vulkan) do things to increase the odds for a Vulkan
port at some point.
=> Use uniform blocks for matrices

code/def_files/data/effects/rocketui-v.sdr
And actually compile the shader this time to check if the changes
actually fixed the error.
This fixes #2266. Really! Pinky swear!
=> Actually fix shader compilation error

code/particle/effects/ConeShape.h
If anything less than or equal to 0 was specified it would trigger some
kind of an assert in the standard library since that is not a valid
value for a normal distribution. Now a parse warning is generated and a
safe default value is used.
This fixes #2269.
=> Handle invalid standard deviation properly

.dockerignore, .gitignore, code/graphics/paths/nanovg/stb_truetype.h, docker/build.sh, docker/standalone/Dockerfile, docker/standalone/fs2_open.ini, docker/standalone/multi.cfg
This adds a Dockerfile which compiles FSO for the alpine Linux
distribution and then creates a standalone image based on those
binaries. That sidesteps the problem that existed with trying to use the
AppImage binaries on that distribution.
This produces a much smaller image (78MB instead of 230MB) so it should
be a bit more managable. Building can be done like this:
```
docker build --build-arg build_type=FastDebug -t scpfs2open/fso-standalone -f docker/standalone/Dockerfile .
```
=> Add Dockerfile for compiling minimal standalone image

CMakeLists.txt, code/CMakeLists.txt, code/globalincs/pstypes.h, code/graphics/paths/NanoVGRenderer.cpp, code/graphics/paths/nanovg/stb_truetype.h, code/missionui/fictionviewer.cpp, code/mod_table/mod_table.cpp, code/network/multi_team.cpp, code/network/stand_gui.cpp, code/osapi/osapi.cpp, code/osapi/outwnd.cpp, code/osapi/outwnd.h, fred2/fred.cpp, freespace2/freespace.cpp, qtfred/src/main.cpp, qtfred/src/mission/management.cpp, test/src/util/FSTestFixture.cpp
This mostly meant for special docker standalone server builds where it
might be useful to have full release performance but also have the logs
available if necessary. This now always compiles the log statements but
enables or disables them with a constexpr so they should not appear in
actual release binaries.
=> Add compile time option to enable logging in release builds

code/network/multi_fstracker.cpp, code/network/multiutil.cpp, code/network/stand_gui-unix.cpp, code/network/stand_gui.cpp, code/network/stand_gui.h, code/osapi/osapi.cpp, freespace2/freespace.cpp
The standalone did not initialize SDL and so did not receive the quit
signal when it was sent SIGTERM or SIGINT. This fixes that by making the
standalone server just use the normal os initialization code.
Also includes some other code cleanup and some more logging to make it
more apparent in the log what is currently happening at standalone
startup.
=> Fix standalone signal handling

CMakeLists.txt, code/CMakeLists.txt, code/cutscene/player.cpp, code/io/keycontrol.cpp, code/network/multi_pause.cpp, code/scripting/api/libs/audio.cpp, code/sound/IAudioFile.h, code/sound/audiostr.cpp, code/sound/ds.cpp, code/sound/ds.h, code/sound/ffmpeg/FFmpegAudioReader.cpp, code/sound/ffmpeg/FFmpegAudioReader.h, code/sound/ffmpeg/FFmpegWaveFile.cpp, code/sound/ffmpeg/FFmpegWaveFile.h, code/sound/sound.cpp, code/source_groups.cmake, docker/build.sh, docker/standalone/Dockerfile, freespace2/freespace.cpp, lib/CMakeLists.txt
This does some refactoring to make it possible to cimpile and run FSO
without needing to link to FFmpeg. Since that eliminates support for
cutscenes or sound this is mostly useful for running a standalone server
which has no need for this anyway.
This reduces the image size of the standalone Docker image to only 20MB
and also resolves any licensing issues that might have existed.
=> Make FFmpeg an optional requirement

.editorconfig, .github/workflows/standalone-image-workflow.yaml, docker/build.sh
This way we will always have standalone images in an official repository.
=> Build docker standalone image on tag push

code/missionui/missionscreencommon.cpp
Small follow-up to #2270 and #2272.  As noted by @AxemP, Lua is 1-based, so the briefing stages should be 1-based.
=> change briefing stage hook to 1-based

code/ai/aicode.cpp, code/ai/aigoals.cpp, code/asteroid/asteroid.cpp, code/controlconfig/controlsconfig.cpp, code/cutscene/ffmpeg/AudioDecoder.cpp, code/graphics/2d.cpp, code/graphics/generic.cpp, code/graphics/vulkan/VulkanRenderer.cpp, code/io/cursor.cpp, code/io/joy-sdl.cpp, code/mission/missionbriefcommon.cpp, code/mission/missionload.cpp, code/mission/missionmessage.cpp, code/mission/missionparse.cpp, code/model/modelanim.cpp, code/model/modelread.cpp, code/network/multi_voice.cpp, code/network/multimsgs.cpp, code/network/multiui.cpp, code/osapi/osapi.cpp, code/osapi/osregistry.cpp, code/parse/generic_log.cpp, code/parse/sexp.cpp, code/scpui/rocket_ui.cpp, code/sound/ds.cpp, code/sound/ds3d.cpp, code/tracing/ThreadedEventProcessor.h, fred2/MFCGraphicsOperations.cpp
There are several places in the code where mprintf and nprintf did not have newlines at the end of their strings.  I ran a regexp search and I think I got them all.  Here it is in case any regexp gurus catch something I missed:
`[m|n]printf\(\(\"[^\";]*[^n]\"[^\";]*\)\)`
=> add newlines to mprintf and nprintf

fred2/fred.rc, fred2/mainfrm.cpp
PR #1514 made this change to avoid having to constantly update fred.rc with new FSO versions, but it was inadvertently reverted in commit 9ac97f24223a7446d4364acfdb451c90697d6577; this also reverts PR #2286, since that's a somewhat more hackish solution to the same problem.
=> Restore fred.rc version fix.

code/weapon/weapons.cpp
This is a fix for a bug introduced in commit 26d40553b2800f8d2dbd41eccc54d5a7d593e6a3, on 2015-11-08.  "Trivial efficiency improvement by calculating a pointer once & reusing it."  As it turns out, that was only true for weapons homing in on weapons.  For weapons homing in on ships, that was an invalid pointer, but fortunately the pointer was never actually used.  Not sure why this wasn't caught with code analysis, but it was definitely caught when `Weapon_info` was changed to a vector.
=> fix an incorrect optimization

code/sound/sound.cpp
The sound was passed the data from before the resampling took place so
it though it would be playing a stereo sound and rightly cause an
assertion. This fixes that by refreshing the properties after appliying
the resampling properties.
=> Fix assertion when playing downsampled sounds

code/lab/lab.cpp
In the #2294 PR, I inadvertently missed one of the loop iterator variables, so all entries in the weapon list actually pointed to whatever index `Num_weapon_subtypes` was.  This fixes that.  I also looked through the PR and confirmed that this was the only place I made that mistake.
This fixes #2303.
=> fix small error in lab

code/scripting/api/objs/ship.cpp
Although not used very often, ai_info.target_signature should be set to -1 whenever no target is specified, just like everywhere else in the code to make sure that the code is as predictable as possible.  It references the shipnum (afaict). Having it set to zero instead could potentially cause unwanted and unpredictable behavior, albeit in a small percentage of cases.
This seems to be a small oversight present since almost the beginning of the scripting system.
(Found while trying to figure out why the heck would the Object update packet send this ai info at all??)
=> Make sure aip->net_signature always defaults to -1 for no target.

code/graphics/opengl/gropengltnl.cpp
This was using the wrong functions which caused videos not to show up
properly. This fixes #2310.
=> Fix wrong matrix function calls

code/menuui/mainhallmenu.cpp, code/menuui/mainhallmenu.h
This PR makes the main hall cheat check for Vasudan graphics, instead of Vasudan music.  This is better because the Vasudan main hall cheats (fishes and headz) affect the graphics, and other mods may use the same graphics with different music, or the same music with different graphics.
=> improve detection of vasudan main hall for cheats

code/network/multi_voice.cpp, code/network/multimsgs.cpp
These locals were causing confusion because they were named the same as ai.target_signature.
Use target_net_signature when talking about net_signature, but leave it at target_signature when talking about ai.target_signature.
=> Clarify Variable Names

code/model/modelread.cpp
This is a simple hack to fix an annoying problem on multi-monitor setups. As it turns out the subsystem targeting reticle is coded so it has the same width-to-height ratio as the screen the game is being played on. While on screens with a 16:9 or 4:3 aspect ratio this is fine because the reticle looks more or less square, on ultra-wide monitors or multi-monitor setups this is incredibly annoying, as shown in the following image where I'm targetting the engines on the GTCv Escher in one of the missions of the Derelict campaign while playing on my triple-monitor setup:
The fix resolves this problem, forcing the reticle to always be square by choosing the smallest of the reticle's width/height and assigning it to height/width. This gives far more desirable results:
Also, my changes work as …
=> Force subsystem targetting reticle to be square, even on non-square aspect ratios.

code/io/keycontrol.cpp, code/ship/ship.cpp
The crashes in #2316 were both caused by references to weapon indexes of -1, which should never have worked. Previously the game silently got away with this, but with the Weapon_info conversion to vector, index bounds are now enforced.
This PR prevents invalid index referencing in both the weapons cheat and the red-alert ammo count check.  It also does a bit of cleanup to make the functions match their counterparts.
This fixes #2316.
=> Weapon bugfixes

code/model/modelread.cpp
A follow-up to #2315. I Verifyed that the math of the old calculations is valid, except it shouldn't calculate both the width and height of the bounding box separately (it should only calculate height and use that for both). Then I cleaned up that function a little bit, reducing the number of local variables and the number of floating-point operations.
I have tested these changes on regular resolutions (1024 x 768):
As well as exotic resolutions (5760 x 1080):
=> Cleaned up code that renders subsystem target boxes. (Follow-up to #2315)

code/localization/localize.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp
This is the best way to address Mantis 2715.
http://scp.indiegames.us/mantis/view.php?id=2715
I took a look at allowing empty banks in the course of working on PR #2318, and it was completely intractable.  But in order to prevent certain "funnies" such as violation of bank restrictions, it's a good idea to ensure all banks are populated.
This PR adds a new XSTR for a popup message, and incidentally adds another XSTR to a message that should have had one already but didn't.
=> prevent player leaving the loadout screen with incomplete weapons

code/object/waypoint.cpp, fred2/fredview.cpp, qtfred/src/mission/EditorViewport.cpp
See Mantis 3171:
http://scp.indiegames.us/mantis/view.php?id=3171
This PR properly resets waypoint lists as-needed so that multiple lists can be copied.
This also removes two Asserts that never worked and are not needed anyway.
=> Fix Mantis 3171

code/hud/hudtargetbox.cpp
There is a special function, `hud_find_target_distance`, which is used in most places for target distance.  However it wasn't used for jump nodes in this location.
Incidentally, the player's target's distance is cached, and this distance will always be current for the target box, so we can use the cached value and save a function call.
=> use consistent jump node distances on HUD

code/parse/sexp.cpp
In the SEXP parser, zero-length strings are valid, as are zero-length operators.  But zero-length numbers are interpreted as missing arguments, since their only syntactic separators are spaces and the parser skips over whitespace.  And in any case, zero-length numbers are not semantically valid anyway.  This PR adds a sanity check to intercept all zero-length numbers, as well as malformed numbers, and convert them to 0.
This fixes issue #2314.
=> sanity check missing numeric sexp arguments

code/missionui/missionshipchoice.cpp
Yet another obscure edge case from Aftermath: Reboot.  The FREDder ought not to create this situation in the first place, but if he does, don't enter an endless loop.
=> add a missing edge case to the weapon bank check

code/missionui/missionshipchoice.cpp
Ships which do not have the maximum number of primary and secondary banks (3 and 4) will have gaps in the loadout slots, so be sure to only check the weapon slots that the ship class is actually equipped with.
=> actually fix the weapon-bank check

freespace2/freespace.cpp
This updates #2299 and restores the use of `event_music_level_start(-1)` in `freespace.cpp`. This call was removed in #2299 because it was thought to be redundant but removal of that call resulted in music not playing upon mission restarts. This PR restores that call and fixes that issue (tested and confirmed with multiple restarts).
=> Reinstates necessary soundtrack function call on level load

code/hud/hudtargetbox.cpp, code/ship/ship.cpp, code/ship/ship.h
Currently `$Closeup_Pos:` and `$Closeup_Zoom:` control the camera zoom and position values for the Techroom, briefing, and HUD Target Box. Unfortunately, with very large long ships this results in an issue, to fit the view of an entire big ship in the HUD Target Box the zoom and position must be set a certain way which results in the ship looking very far away when viewed in the Techroom. This PR adds two new fields, `$Closeup_pos_targetbox:` and `$Closeup_Zoom_targetbox:`, that control camera position and zoom but only for the HUD Target Box. Now modders can set values for both and have the ships look properly zoomed in both the Techroom and HUD Target Box. The new HUD Target Box values are optional, and if not specified they default to the values for `$Closeup_Pos:` and `$Closeup_Zoom:` …
=> Adds Scaling for Target Box Models Separate from Techroom

.travis.yml, appveyor.yml, ci/travis/ftp_deploy.sh
The swc.fs2downloads.com FTP mirror hasn't been liking the 7z binaries from AppVeyor since December 14.  Most fail entirely or end up corrupted.  Need to make sure we update the nightlybuild config.yml at the same time this is merged so the forum post and the actual uploads agree with each other.  File is already updated in place as config.yml.new on the server, just need to replace it.
=> Use datacorder in CI instead of fs2downloads

ci/travis/ftp_deploy.sh
I think this will do the trick.  I confirmed that the resulting curl call works with a test file, which should mean that anything I changed has now been tested to work, after this fix is deployed.  Just need to use the ~ path like in the Indiegames call since apparently the sftp method doesn't work with a relative path like the ftp one did before.
=> Use full path  in SFTP, unlike the FTP one this was modified from.

code/missionui/missionbrief.cpp, code/missionui/missionshipchoice.cpp
As noticed in Discord, in loop1-2 some of your wingmen have missing weapons, but as the ships are locked it's impossible for the player to modify them.  These ships should not be part of the check.
=> allow empty weapons on locked ships

code/mission/missionmessage.cpp
It turns out that the extant placeholder wav has an underscore in the filename, so add that to the list.
=> add overlooked generic file

fred2/fred.cpp, fred2/fredview.cpp, fred2/fredview.h, fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
See: http://scp.indiegames.us/mantis/view.php?id=2867
FSO-specific features should now all be properly marked off with checks for retail format.
This PR also simplifies the `Format_fs2_open`, `Format_fs2_retail`, and `Format_fs1_retail` flags into the single `Mission_save_format` variable.
=> bring save format up to date (Mantis 2867)

code/iff_defs/iff_defs.cpp, code/iff_defs/iff_defs.h, code/mission/missionhotkey.cpp, code/scripting/api/objs/team.cpp
This is in response to Mantis 1424:
http://scp.indiegames.us/mantis/view.php?id=1424
Since retail, the hotkey lists have been determined based on what attacks the player.  Mod makers may want to change this, so this PR adds the following options:
* Default - retail behavior
* Friendly/Enemy (or Hostile) - display in the specified list regardless of who attacks whom
* None - don't display in the hotkey list at all
This PR also slightly cleans up the hotkey list function with a small optimization and a few tweaky fixes for edge cases.
=> add +Hotkey Team: to override IFF designation in hotkey list

code/ship/shipfx.cpp
Previously if a ship's glowmaps were deactivated via sexp, then the glow maps would reactivate at the ship's final explosions. This PR fixes that by carrying that flag into the ship explosion FX code.
=> Fix Glowmap flag not carrying over to final ship explosion

code/hud/hudtarget.cpp
Modify the early-out condition to remain in the function if we still need to render a dumbfire lead indicator.
Fixes #2335.
=> fix issue 2335

code/cmdline/cmdline.cpp, code/graphics/opengl/gropenglpostprocessing.cpp
Deprecates the -fxaa and -smaa cmdline parameters in favour of a more generalized -aa; This also ensures that the smaa render targets are always initialized.
=> Unify the way post-process antialiasing is switched on

code/ship/ship.cpp
Due to code rot, the support ship hull repair code was a bit more tangled than it should have been, so I tidied it up.  I also fixed a bug Sarn noticed where a support ship would think all subsystems were repaired if the hull repair rate was set to 0.
=> clean up the support ship code a bit

code/ai/aicode.cpp, code/mission/missionparse.cpp, code/model/model.h, code/model/modelread.cpp
See: http://scp.indiegames.us/mantis/view.php?id=2791
Instead of firing an Int3() when a ship has no arrival paths, just log it and continue.  And change the upstream warnings, which should have been more visible, from WarningEx to Warning.
Also, warn if model paths do not have unique names, and warn if there is a gap in the path sequence.
=> Fix mantis 2791

code/ship/ship.cpp
The sexps that activate and deactivate glowmaps are very useful for ships, though previously the glowmap status was not passed to the ship's cockpit. This PR adds the ability for glowmap status to carry to this ship's cockpit (if it has one). This feature has been tested and works as expected.
=> Updates glowmap settings for a ship to also apply to ship's cockpit

code/io/keycontrol.cpp, code/localization/localize.cpp
`+Shift+R will enable or disable support ships
`+Shift+U will scan or unscan the targeted ship, or ship subsystem
=> add two useful cheat keys

code/ai/aiturret.cpp
I was comparing the retail and FSO versions of `ai_fire_from_turret()` in hopes of resolving Mantis 804:
http://scp.indiegames.us/mantis/view.php?id=804
Function excerpts here:
[fso.txt](https://github.com/scp-fs2open/fs2open.github.com/files/4578819/fso.txt)
[retail.txt](https://github.com/scp-fs2open/fs2open.github.com/files/4578820/retail.txt)
There has been a lot of code drift, but on a preliminary inspection the code appears to be correct, with the notable exception of this little bit.  In SVN revision 5399 KeldorKatarn submitted a "fix" for the fire-down-normals flag that made turrets always fire directly at the enemy, instead of in the direction the turrets were facing.  This PR puts it back the way it's supposed to be.
=> fix some code rot

code/localization/localize.cpp, code/localization/localize.h, code/menuui/readyroom.cpp, code/mission/missionparse.cpp, code/network/multiui.cpp, test/src/menuui/test_intel_parse.cpp
Certain mods provide their own tstrings.tbl, but this runs into trouble when you localize data meant for one mod using a tstrings.tbl meant for another mod.  See the Mantis ticket:
http://scp.indiegames.us/mantis/view.php?id=2942
and also the HLP post:
http://www.hard-light.net/forums/index.php?topic=85041.msg1716600#msg1716600
This PR adds an optional flag that will check the untranslated string against the "default language" translated string.  The two strings should be identical.  If they aren't, the code assumes there is a tstrings.tbl mismatch.
I modified the mission listing code to enable this check when localizing mission info (titles and descriptions), and to avoid adding the mission to the list if there is a mismatch.  Fortunately, I think mission listing is the only place where …
=> implement XSTR check as described in Mantis 2942

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/hud/hudtarget.cpp, code/ship/ship.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
Implements the requested features in #1851
Doublefiring can be turned off for AIs and/or players separately through AI profiles flags. Went with that instead of gamesettings largely because that seems consistent with other similar behavior options, and I can conceivably see someone wanting to vary it between missions.
It can also be turned off on a per-weapon basis through a new weapon flag.
Originally attempted in PR #2328, but the feedback there led to enough course corrections that I felt a clean slate was for the better.
=> Disable doublefire take 2

code/ship/ship.cpp
This PR allows the `ship_render_show_ship_cockpit` function to properly detect replacement textures. Fortunately just a one line fix. Tested and works as expected. Fixes #2380.
=> Fixes texture replace not working with show ship

code/def_files/data/effects/effect-f.sdr, code/model/modelread.cpp
Having recalled that other SCP folks stated `pow` should not be used to for simple squaring, I figured it might be a good idea to update the two instances I found where that was the case. Note these were the only instances applicable I could find in the whole code base.
=> Update cases of pow(x,2) to just multiply values

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp, code/hud/hudsquadmsg.cpp, code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/mission/missionmessage.cpp, code/ship/ship.cpp, code/ship/ship.h, code/sound/voicerec.cpp
This adds an ai_profiles flag that checks comm systems for non-player ships.  If their comm system is damaged, they will not send messages and you will not be able to issue squadmsg orders.
See also:
http://scp.indiegames.us/mantis/view.php?id=1947
Also, this PR fixes a few bugs:
1) message scramble status incorrectly took priority over subsystem health status
2) synthesized speech could be stopped when only the head animation needed to be stopped
3) don't allow messages that are never played to delay messages that *are* played
=> implement Mantis 1947, treat ship comm systems the same as player comm systems

code/weapon/weapons.cpp
In any case, if no valid filename for a model can be found the render type should be set to `WRT_NONE`.
=> Make sure modular tables can overwrite weapon model info

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp, code/globalincs/version.h, code/mod_table/mod_table.h
See Mantis 3147:
http://scp.indiegames.us/mantis/view.php?id=3147
I was awaiting a response, and then a response never happened. :)  So I implemented the flag myself.  The new flag should enable the fixed behavior when active, and default to retail behavior when inactive.
The original changes were committed in SVN revision 11284.  Here is the diff from that revision:
```
Index: aicode.cpp
===================================================================
--- aicode.cpp	(revision 11283)
+++ aicode.cpp	(revision 11284)
@@ -5644,7 +5644,7 @@
float	dot;
vec3d	v2t;
-	if (!( vm_vec_mag_quick(&G_predicted_pos) < AICODE_SMALL_MAGNITUDE )) {
+	if ( !(vm_vec_mag_quick(&G_predicted_pos) < AICODE_SMALL_MAGNITUDE ) && !(aip->submode == SM_AVOID) ) {
if ( vm_vec_cmp(&G_predicted_pos, &G_fire_pos) ) { …
```
=> add an ai-profiles flag to govern the Mantis 3147 fix

fred2/shipgoalsdlg.cpp
The ship goals dialog was incorrectly assigning a goal target name for every dockpoint, which could quickly cause the limit to be exceeded if the FREDder browsed a lot of dockpoints.
This also indicates a need to fix the goal target name system as the behavior is unchecked if it exceeds the limit.  That is addressed in #2389.
=> fix improper usage of ai_get_goal_target_name

.clang-tidy
These are far too pedantic, and were not related to the feature in #2298 anyway.
This will fix the CI complaints in #2392 and #2394, as well as the CI complaint which delayed merging of #2298 itself.
=> revert the clang-tidy changes from #2298

.clang-tidy
This enables the clang readability checks that I found to be sensible. I
disabled a few that would have caused a lot of unnecessary warnings in
our code.
=> Enable sensible clang readability checks

code/missionui/missionshipchoice.cpp
Based on feedback, this PR now allows gaps in weapon loadouts, but if any gaps exist they must come at the bottom.
=> modify weapons loadout check

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/weapon/weapons.cpp
I coded up this feature to do two things:
* print a spreadsheet allowing comparison of damage per second, rate of fire, and other useful info
* print statistics to allow easy copy+paste of MediaVP-style weapon descriptions
I found this useful for the MediaVPs, Scroll, and FSPort, so I thought other people might find it useful too.  Use the `-weaponspew` command-line option in a debug build, and you'll find all the information printed to the log file.
=> Weapon statistics for comparison and extended descriptions

code/parse/sexp.cpp
This code is highly inefficient (find_parent_operator() is O(n) for Num_sexp_nodes, and it runs every frame for all sexps with negative values) and should not actually be necessary.  But it is useful as a debug tool, so I added some #ifdef's.
=> make some debug code only run in debug

code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/localization/localize.cpp, code/localization/localize.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/scripting/api/libs/base.cpp, fred2/management.cpp, qtfred/src/mission/management.cpp
Since the original release of FS2, internal strings have been translated to their English entries in strings.tbl but external strings have not been translated to their English entries in tstrings.tbl.  It appears that string translation was universal until it was disabled via a hack, probably due to FRED idiosyncrasies (see comment in `fred_init()`), and then not re-enabled for release.  PR #2343 re-enabled it, but this turned out to have undesirable side-effects since many mods used incorrect XSTR indexes for external strings.
This PR restores the previous behavior and also cleanly separates localization into translated and untranslated modes.  FRED will always run in untranslated mode.  FSO will run in translated mode for all languages except English, where it will run in untranslated …
=> clean up handling of translated vs. untranslated English

code/ai/aigoals.cpp, code/mission/missionparse.cpp, code/parse/sexp.cpp, code/parse/sexp.h, code/ship/ship.cpp, code/ship/ship.h
This is a first-level pass at optimizing SEXP execution.  In brief, rather than each SEXP node parsing and looking up each argument every frame, this PR saves the value in the SEXP node after it is determined.  Most SEXP data types (e.g. wings, IFFs, messages) will not change their reference for the duration of a mission.
At this point, ships, numeric literals, and variables are all cached.  Since ships can change status during the mission, this PR also introduces a ship registry that maintains the ship status and references to pointers.  This registry is applicable outside the SEXP system; see the example in the AI goal code.
To keep changes manageable, I limited the ship-related changes to mostly those SEXPs which used `sexp_get_ship_from_node`.  After this PR is merged I intend to make …
=> SEXP data caching

.github/workflows/pr-workflow.yaml
Otherwise 32-bit might bet binaries for 64-bit or the other way around.
=> Use architecture specific cache for Qt

code/hud/hud.cpp, code/io/keycontrol.cpp, code/localization/localize.cpp, code/localization/localize.h, code/menuui/playermenu.cpp, code/mission/missionlog.cpp, code/network/multi_endgame.cpp, code/network/multi_pinfo.cpp, code/network/multiui.cpp
This is a minor follow-up to PR #2390.  There are a few small differences between untranslated strings and the internal strings in strings.tbl; this PR fixes them.
=> tweak some untranslated internal XSTR strings

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
This is a follow-up to #2348.  One part of the change wasn't tested, and it turned out to be important.
=> fix corrupted retail save format

code/mission/missionparse.cpp
In PR #2318, I consolidated the code a little too much.  The partial-loadout checks should not have been under the `SUBSYS_STATUS_NO_CHANGE` check, because this would cause partial loadouts to fail if the percentage was adjusted but the actual weapon in the loadout was not changed.
Thanks to @wookieejedi for spotting this bug.
=> fix incorrect consolidation

code/scripting/api/libs/graphics.cpp
Previously the scripting call `gr.drawOffscreenIndicator` did not properly draw the indicator and/or return coordinates. After some bug hunting it turns out it is because there gauge was not being set to active. This PR adds that line and restores the intended functionality. Tested and works as expected.
=> Fixes gr.drawOffscreenIndicator

code/ai/aigoals.cpp, code/mission/missionparse.cpp, code/parse/sexp.cpp, code/parse/sexp.h, fred2/fredview.cpp, fred2/messageeditordlg.cpp, fred2/voiceactingmanager.cpp
Awhile back, the get_operator_const and get_operator_index functions were enhanced to cache the result of the operator lookup.  But this only works when called on the node itself, not the text.  So let's call these functions on the node whenever possible.
=> use get_operator_* optimizations

code/parse/sexp.cpp, code/parse/sexp.h
The `special_argument_appears_in_sexp_tree` function can run multiple times per event, especially for repeating events, so it's a good idea to cache the result.  This avoids the need to iterate through potentially the entire tree, checking every single node.
=> optimize sexp tree lookup

code/ai/ai.h, code/ai/aicode.cpp, code/ai/aigoals.cpp, code/ai/aigoals.h, code/autopilot/autopilot.cpp, code/mission/missionparse.cpp, code/network/multi_sexp.cpp, code/network/multi_sexp.h, code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/LuaSEXP.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp, code/ship/shiphit.h
This is part of the ongoing sexp refactor.  Assorted functions outside sexp.cpp have been affected, so I separated them out into this PR to help keep reviews manageable.  Additionally:
1) `eval_wing` has been added to complement `eval_ship`.  Both of these functions are also now more forgiving, cache-wise, for nodes that might allow multiple data types.
2) A `name` field has been added to the ship registry for convenience.
3) An `exited_index` field has been added to the ship registry to track exited ships.
4) Lua sexps now take advantage of caching.
5) A bug with simulated hull has been fixed in `repair-subsystem`.
6) A subtle bug for exited ships has been fixed in `is-iff`.
=> additional infrastructure for sexp caching and ship registry

code/parse/sexp.cpp
This is part of the ongoing sexp overhaul relating to performance and caching.  This PR combines functions for several sexps that are very similar, and it also uses the `eval_ship` speedy lookup function.  As a bonus, it allows `turret-tagged-only` and `turret-tagged-clear` to run for multiple ships at a time.
=> consolidate several sexps related to beams and turrets

code/autopilot/autopilot.cpp, code/autopilot/autopilot.h, code/hud/hudnavigation.cpp, code/hud/hudtarget.cpp, code/hud/hudtarget.h
This was suggested by the sexp overhaul but is useful on its own too.  Some of the `const` changes cascade a bit.
=> add const-correctness to the autopilot API

code/mission/missionparse.cpp
This PR fixes the logic for setting weapon amounts for both the pilot and subsystems of a ship. Previously, in PR #2413 this distinction was not checked, which resulted in partial weapon amounts not setting properly. This PR properly adds that check and distinction.
=> Fix Pilot and Subsystem Weapon Loading

code/scripting/api/objs/ship.cpp, code/scripting/api/objs/subsystem.cpp
Previously, using the script function ArmorClass did not properly display the actual armor class, instead it always displayed -1. This PR fixes that. I have tested these changes and they now properly display the armor class.
=> Fix minor mis-setting of script function for displaying armor string

.clang-tidy
This removes `readability-avoid-const-params-in-decls` from the list of things clang checks.  Function declarations and headers should be the same, so it makes no sense to warn about `const` in one but not the other.
This also alphabetizes the exceptions for easier reading.
=> update .clang-tidy based on Discord comments

code/ship/ship.h, code/ship/shiphit.cpp
There is a slight discontinuity where ships that are destroyed have their mission log entries added a bit before `ship_cleanup` is called.  This addresses that.
=> refine ShipStatus::EXITED state

code/graphics/2d.cpp, code/scpui/RocketRenderingInterface.cpp, code/scpui/RocketRenderingInterface.h, code/scripting/api/libs/engine.cpp, code/scripting/api/objs/tracing_category.cpp, code/scripting/api/objs/tracing_category.h, code/source_groups.cmake, code/tracing/categories.cpp, code/tracing/categories.h, code/tracing/tracing.h
This can be used by Lua code to trace the runtime of their code in the
same way the engine already is capable of doing for most in-mission and
mission loading code.
Also adds some tracing scopes to the libRocket code
=> Add scripting API for tracing custom code

code/hud/hudscripting.cpp, code/parse/sexp/LuaSEXP.cpp, code/scripting/ade.cpp, code/scripting/ade_api.h, code/scripting/api/LuaEventCallback.h, code/scripting/api/libs/async.cpp, code/scripting/api/objs/promise.cpp, code/scripting/api/objs/tracing_category.cpp, code/scripting/lua/LuaFunction.cpp, code/scripting/lua/LuaFunction.h, code/scripting/scripting.cpp, code/scripting/scripting.h, test/src/scripting/lua/Function.cpp
This will ensure that Lua functions will always be executed in the
correct Lua state. Since we now have multiple threads (which are
different lua_State objects) it is possible that the current code could
execute a Lua function in the main state instead of the thread that is
currently executing. This can lead to weird behavior and probably also
to issues inside Lua.
=> Ensure Lua functions are executed in correct state

code/parse/sexp.cpp, code/ship/ship.h
This PR uses `eval_ship` and `eval_wing` to optimize `object_ship_wing_point_team` and `sexp_deal_with_ship_flags`.  The API changed a bit, but to ensure compatibility, there are fields and functions to support the old behavior.  These are temporary and will be removed when all changes have been merged via PRs.
=> another stage of the sexp refactor

code/math/staticrand.cpp, code/math/staticrand.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Implements half of #2423, specifically the child weapon spawn angle part. I know at least one person besides me wants this, so I figure it's better to get it in asap rather than wait for me to finish deciding how much I want to match the existing more complex $fof options.
=> Settable minimum spawn angles.

code/parse/parselo.cpp
This is a follow-up to PR #2373.  Tomimaki noticed that the first character was truncated in the cutscene description, and it turned out that the algorithm was slightly wrong.
=> fix compact_multitext_string

freespace2/freespace.cpp
If a standalone has only one player connected in a dogfight mission it will crash because the standalone will start self-destructing.  Not fully sure why this doesn't crash in other circumstances, but this check should just be here, anyway, because the standalone ship should never self-destruct.
=> Prevent Standalone Crash

code/lab/lab.cpp, code/ship/ship.cpp, code/ship/ship_flags.h, code/weapon/weapons.cpp
This reenables rendering of external weapon models in the lab.
This also adds actions to change a ship's loadout and fire guns. Note that weapons that have a firewait or require lock-on will not work here.
Also note that the lab will no longer open instantly, since we need to load all the weapon data now.
=> Allow weapons in the lab

code/parse/sexp.cpp, code/parse/sexp.h
When special arguments are used, the current node cannot be cached because it always contains `"<argument>"`.  So this feature adds the ability to forward the caching to the SEXP node that contains the value being referenced.  To enable this, the internal argument list now contains both the argument text and the node it comes from.  (If there is no node, such as with `for-counter` which generates its data dynamically, the reference will be -1.)
This also fixes a bug where values in certain `"<argument>"` nodes were incorrectly cached.
=> cache on the argument node

code/scripting/ade.cpp, code/scripting/ade.h, code/scripting/doc_html.cpp, code/scripting/doc_html.h, code/scripting/doc_json.cpp, code/scripting/doc_json.h, code/scripting/hook_api.cpp, code/scripting/hook_api.h, code/scripting/lua.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h, code/scripting/scripting_doc.h, code/source_groups.cmake
I added a pretty generic container structure for the scripting
documentation when adding JSON output. However, I did not use that new
structure for the HTML output since that was just too much work.
This moves the HTML output over to the new structure so now the
scripting API handling code is independent from how the resulting
documentation is generated. I also moved that code out of the main
scripting code which removes quite a lot of clutter in those files.
This is mostly a straight port of the old code with no significant
changes (except the changes to make it use the new data).
=> Unify and clean up Lua documentation generation

code/globalincs/pstypes.h, code/globalincs/systemvars.cpp, code/hud/hudartillery.cpp, code/menuui/mainhallmenu.cpp, code/parse/sexp.cpp
As noticed in issue #2458, intercom sounds did not stop when pausing the game or loading a mission.  I fixed this by augmenting `main_hall_stop_ambient()` to also stop the intercom.
Additionally, it turns out that the intercom delays were not being calculated correctly due to a very bizarre random number formula.  I overloaded `rand32()` to add a min/max variant and used this instead.
=> fix a couple things with mainhall intercom sounds

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/weapon/weapons.cpp
In response to request #2407, this expands -weaponspew to optionally list all non-beam weapons.
=> expand -weaponspew to all non-beam weapons

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/ai_profiles.h, code/ai/aibig.cpp, code/ai/aibig.h
Previously, the default distance for determining if a ship had finished a point in a model subsystem path was only 5. This worked fine for ships with low damp or no Newtonian physics. However, it did not work well with ships that use higher damps or Newtonian physics, because those ships continually overshoot that 5 meter distance and get stuck flying in a large circle trying to reach that point. This fix allows modders to set an AI flag to specify that the path distance check uses a larger value of 775 for points that are not the last point in the path. The value of 775 was chosen because it seemed like the average value that PCS2 made for path points when they were autogenerated. If desired I can add a game settings option that allows modders to set this value.
I did not use the radius …
=> Add Large Radius Option as AI Flag for Following Subsystem Path Points

code/parse/sexp.cpp
Boolean needs to be false not true since `disarmed-delay` is not checking disabled status. Tested fix and confirms it works.
=> Fix new version of `disarmed-delay`

code/parse/sexp.cpp
The previous method worked for FSO, but not FRED.  This method works for both.
=> fix argument detection in sexps

code/graphics/generic.cpp, code/graphics/generic.h, code/missionui/missioncmdbrief.h, code/scpui/RocketRenderingInterface.cpp, code/scpui/RocketRenderingInterface.h, code/scpui/elements/AnimationElement.cpp, code/scpui/elements/AnimationElement.h, code/scripting/ade_args.cpp, code/scripting/ade_args.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/cmd_brief.cpp, code/scripting/api/objs/cmd_brief.h, code/source_groups.cmake
This adds access to the command briefing data parsed from the mission
file to the scripting API so it can be used by the UI scripts for the
high res UI.
Also switches the animation support to using the generic anim to use
streaming to improve performance.
=> Add support for libRocket command briefing

code/parse/sexp.cpp
1) Something wookieejedi noticed: destroying all turrets didn't trigger the DISARMED mission log event.  This is because a code ordering decision intended to accommodate the destroyed check caused the hitpoints to not be correct when they were checked within `do_subobj_destroyed_stuff`.  Instead I changed the blow-up check to use the same code for set-strength as for sabotage-strength.  This handles destruction properly and also tracks hitpoints properly.
2) Aggregate points were being recalculated for every subsystem operation where they only needed to be recalculated at the end of the sexp, so I moved that.
=> fix a few things with subsystem sexp operations

code/scripting/api/objs/physics_info.cpp
Many physics values are exposed to scripting, including rotational damp. This PR exposes the linear damp to scripting. Note, in the code base linear damp is called `side_slip_time_const`.
=> Expose 'Damp' to Scripting

code/parse/sexp.cpp
Due to a copy+paste error, the `get-damage-caused` sexp referred to the wrong exited ship.
This fixes #2501.
=> fix exited ship mismatch

code/hud/hudets.cpp, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp, code/ship/ship.h
Previously a ship's shields and weapon regeneration per second rates were only stored in the `ship_info` strut, thus they should not be changed during a mission or via scripting (see #2236 and and #2239). There are many precedents for taking a `ship_info` value and copying it to a `ship_object` value so the value can be changed on a per ship basis in mission (auto aim FOV is one of many examples). This PR thus copies the shield and weapon recharge values to the `ship_object` and exposes those new values to scripting.
=> Add Shield and Weapon Regen Rates to Ship Object and Expose to Scripting

code/ai/aicode.cpp
Previously, the ship table value `+Weapon Min Range:` was only ever used for turret firing calculations. This PR adds it as part of the distance weapon firing check for other instances, but only if the AI flag `Use_actual_primary_range` is used.
=> Allow AI Flag Use Primary Range to work with Min Range Too

code/weapon/weapons.cpp
When resolving targets for local ssms, check both the weapon's target_num _and_ it's tracking info.
=> Fix issue with local ssms not actually working correctly when being fired from a turret

code/ai/aicode.cpp
1) Prevent ships from turning in `ai_turn_towards_vector` if they have the `immobile` flag.  This was missed because it is a rotation that doesn't originate in `obj_move_call_physics`.
2) Prevent ships from evading shockwaves if they're playing dead.
Also there is a small conversion of an int to a bool.
=> a few fixes for ships which shouldn't move

code/parse/sexp.cpp, code/parse/sexp.h
I looked for possibilities to reduce the size of the parse/sexp.cpp file.
I did not fine any obvious code duplication, so here is a small PR with changes to reduce the amount of warnings from clang-tidy.
Best reviewed on a per commit basis.
The last commit contains only white-space changes which replaces all occurrences of 4 white-space with a tab, to make the indentation consistent within the file.
=> small cleanup in  sexp.cpp

code/hud/hudmessage.cpp
Tracked down another Volition bug, first reported by recead.  When messages do not have the ": " substring (which only happens when they are from MSG_SOURCE_NONE), they would calculate the wrong string size.  This is because the two-character offset was added to the pointer *before* the pointer was checked for null, and so non-matches were considered matches with strings beginning at memory offset 2.
=> fix HUD message offset for messages that come from [none]

code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/ship.h
The ship registry previously stored the ship name as a pointer, but that pointer was reused when subsequent waves of a wing overwrote a p_object from the first wave.  So, the name is now copied into an array.
Additionally, subsequent waves of a wing are now "eagerly" stored in the ship registry so that the p_object reference can be stored as well.
=> fix ship registry in regards to wings with multiple waves

.clang-format, code/parse/sexp/DynamicSEXP.h, code/parse/sexp/EngineSEXP.cpp, code/parse/sexp/EngineSEXP.h, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/LuaSEXP.h, code/parse/sexp/SEXPParameterExtractor.cpp, code/parse/sexp/SEXPParameterExtractor.h, code/parse/sexp/sexp_lookup.cpp, code/source_groups.cmake
This adds a "clear-debris" SEXP with a new system for declaring SEXPs
outside of sexp.cpp. This makes it easier to keep code modules self
contained since they do not need to export previously private
functionality just for having missiong being able to interface with it.
This is mostly a proof-of-concept which only supports basic parameter
types (booleans and integers).
As for the reasoning why this could just be added to sexp.cpp: It's already 1MB big. Let's not add more...
=> Add system for adding SEXPs externally

fred2/campaigneditordlg.cpp, fred2/campaigntreewnd.cpp, fred2/campaigntreewnd.h, fred2/management.cpp
FRED's handling of mission loading and creation is a bit wonky.  The `stars_post_level_init()` function should run for each new mission, not just once when FRED is started.  That fixes a background editor crash and I also did a bit of other cleanup.
=> fix background bug when loading subsequent missions

code/network/multi_obj.cpp
This just uses vm_vec_normalize_safe.  If two objects spawn on top of each other, the code will now sort them properly without printing a null vec3d warning.
Fixes Mantis 2181:
http://scp.indiegames.us/mantis/view.php?id=2181
=> fix Mantis 2181

code/mission/missionparse.cpp
There was an AI class validity check for the pilot, but not for turret weapons.  This fixes that.
Also, the p_object parameter to this functino was named `objp`, which is misleading because that's usually used for object.  I renamed it p_objp.
Fixes Mantis 2871:
http://scp.indiegames.us/mantis/view.php?id=2871
=> fix Mantis 2871

code/controlconfig/controlsconfig.cpp, code/globalincs/pstypes.h, code/localization/localize.cpp, code/localization/localize.h
If we specify an XSTR index, we want the internal control lookup to happen regardless of whether the game is running in untranslated mode or not.
=> fix XSTR lookup for $Has XSTR:

code/mission/missioncampaign.cpp
`skipmemymissionyo` used to completely hose the player's campaign file, but it turns out this can be prevented with one weird trick!
=> fix skipmemymissionyo

code/mission/missionparse.cpp
The #2528 fix broke ships destroyed before mission start because their arrival delay was *already* set up.  So this change adds a special exception for that.
This fixes #2563.
=> sometimes the FSO code is like Jenga

fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
This was a fun one.  Volition used a bizarre and very poorly named "flag" static variable to track iterations through the `verify_and_fix_arguments` function.  I'm not sure how this actually works, but on comparing with the original public source code I see that @asarium didn't quite fix the "declaration masks class variable" compiler warning the right way.  This rolls back that 2016 change and fixes it properly.
The effect of this fix is so that FRED will correctly handle arguments when node data types change, such as when the modify-variable argument is changed from a numeric variable to a string variable.
=> fix FRED's verify_and_fix_arguments

test/src/math/test_vecmat.cpp
I calculated mag_quick's exact relative error (used also by dist_quick) and am using that instead of an absolute value. Also uses a seed for the random tests to avoid one in a thousand compiles failing for someone.
=> Relative error for mag and dist_quick, and seeded vecmat tests

code/ai/aicode.cpp
Allowing not big or huge ships to recover from collisions with large ships by attempting to fly away, also allows cargo containers, navbuoys, and sentry guns to attempt it. This keeps it to small ships: fighters, bombers, support ships and escape pods.
=> Prevent cargo containers from recovering from a collision

code/parse/parselo.cpp, code/parse/parselo.h, code/pilotfile/JSONFileHandler.cpp
1) Write all non-UTF-8 strings to JSON, either by converting or truncating
2) Add `coerce_to_utf8` function
3) Tweak `read_raw_file_text` because the function returns length on success, not 0
Fixes Mantis ticket:
http://scp.indiegames.us/mantis/view.php?id=3209
=> some UTF-8 improvements

code/object/collideshipship.cpp
When the collision code is precluding things from colliding due being docked, it only checks for directly docked objects. `dock_check_find_docked_object` functions identically in this role, but also checks for indirectly docked objects.
=> Prevent indrectly docked ships from colliding

code/graphics/2d.cpp
Standalones would crash if they had an error dialog pop up because of a nullptr.  This just checks for the nullptr and returns early to prevent the crash.
=> Fix Standalone Crashes

code/weapon/shockwave.cpp, code/weapon/shockwave.h, code/weapon/weapons.cpp
Currently 3D shockwaves from weapons will always have their orientations fixed at 0,0,0 unless explicitly tabled otherwise. There's really no reason for them not to be simply randomized if the modder didn't set a specific orientation, and it looks quite jarring once you notice it.
=> Randomized weapon shockwave orientations

code/network/gtrack.cpp
A loop mistakenly using value instead of reference caused servers to be bombarded with game queries.
=> Fix query bomb in PXO game tracker

code/parse/sexp.cpp
For older campaigns which used show-subtitle, the eval_num conversion inadvertently changed the rgb to default to 0, instead of 255.  This restores the default to 255.
=> fix show-subtitle

code/ship/ship.cpp
Improves physics initialization for ships; a few changes here.
Firstly, a check for density. Ships should never have density 0.
Now that density has been sanity checked it can't ruin attempts at compensating for 0 mass when it scales the new mass at the end by density (*facepalm*).
And then, as the comments state, invalid MOI got a warning earlier, but not zero MOI because it might not be a big deal. Now it is a bigger deal so warn for zero MOI.
Only if we have a truly invalid MOI do we "compensate" by setting it zero (instead of just using the bad MOI anyway (*facepalm*)). Zero MOI is not great either, but if the intention is to try and sweep this problem under the rug for release, zero MOI is the safest bet. It'll just be immovable (rotationally), and if you're not paying close …
=> Improve physics_ship_init safety

code/ui/inputbox.cpp, code/ui/ui.h
By special request of Cyborg. Pressing CTRL+v in an active input box will append any text from the system clipboard into the control.
=> Allow pasting clipboard contents into input boxes

code/network/multi_endgame.cpp, freespace2/freespace.cpp
And also a minor typo
The issue in other words is that stuff rendered on the last frame of the mission will be stuck on the sidebars for a long time.
Just tested and this works on release and debug. Open to moving the fix somewhere, just let me know if there's a more proper place.
=> Fix sidebars retaining old rendering from mission quick exit

code/math/vecmat.cpp, code/math/vecmat.h, test/src/math/test_vecmat.cpp
The functions derived from `vm_vec_mag_quick` run *slower* than `vm_vec_mag`, according to @Baezon who did some testing.  So this PR makes all calls to the _quick functions use their more accurate counterparts.
=> make _quick quicker

code/network/multiteamselect.cpp, code/network/multiteamselect.h, code/network/multiutil.cpp, code/object/object.cpp
Gotta love your retail bugs!
Function was returning 0 instead of 1 when the team captains were messaging AI.  
Yes we could replace this with a fancier check than, "does the ship name end in 1???"  But we should come up with that system and fix all the places it relies on that behavior at once.
Edit: forgot to mention, this does not affect multi compatibility at all.
Edit2: Realized != matches the function better and keeps everyone else from messaging, so that's what we should go with instead.
=> Allow Team Leaders to Send Messages

code/network/multiui.cpp
Because pxo can be enabled through the options screen in the game join screen, we may have PXO games enabled when we're not connected, so we should go back to the PXO screen and connect if that's true.
By the way, this is tested and works as expected.
=> Go back to login if you're trying to use PXO

code/object/objectdock.cpp, code/object/objectdock.h, code/physics/physics.cpp, code/physics/physics.h, code/scripting/api/objs/physics_info.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp
Fixes #2525 . Basically this will, after calculating the center of mass of the docked ships and their aggregate MOI, 'whack' each individual ship with corrected rotational and linear velocities so that all ships in the aggregate move along with what the aggregate would rotate and move with. Also replaces all outside callings of physics_apply_whack with ship_apply_whack, so this checking can be done. 
In general, physics_apply_whack shouldn't be called in lieu of ship_apply_whack or you'll get the previous issues. Also physics_apply_whack is now properly passed a world position, instead of a local position as it was doing before, fixing some weird whack behavior you could get and appeared to be retail!
Of note: this does NOT alter shockwaves or collisions, only weapons fire! They will …
=> Fix physics whack for docked ships

code/globalincs/pstypes.h, code/math/vecmat.h, code/scripting/api/libs/base.cpp
What it says on the tin.  Previously there was no access to the `vm_vector_2_matrix` API.  One or more of the vectors may be nil or missing.
=> add scripting function to create matrix from vectors

fred2/eventeditor.cpp, fred2/eventeditor.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
The old way of finding the closest match of sexp text to entered text didn't work very well.  This method uses Levenstein distance.
This also fixes the bug where when text was matched to an existing operator, and the operator used in the event editor, the underlying incorrect text was still in the mission file.
=> fix sexp auto-complete for manually-entered text

CMakeLists.txt, code/CMakeLists.txt, code/graphics/2d.cpp, code/source_groups.cmake, lib/CMakeLists.txt
This makes it possible to still compile FSO on platforms that are not
supported by the Vulkan headers.
=> Make Vulkan an optional component

code/parse/parselo.cpp
When I rewrote `strip_comments()` to take quotes into account, I didn't correspondingly update `get_line_num()`.  This fixes that.  I discovered that a Lua file with a lot of semicolons inside quotes was erroneously getting the past-EOF warning.
Also, in the event that the warning *is* tripped, this exits the loop instead of repeatedly displaying the warning.
=> fix line number counting

code/ai/aicode.cpp, code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/ship/ship_flags.h
This allows the ship-maneuver flags to be used by default in a ship class.
=> add ship-maneuver flags to ship_info

code/libs/renderdoc/renderdoc_app.h
This seemed to be all that was necessary for this to compile on OpenIndiana.
=> fix/sun_renderdoc: Make Solaris a recognized platform for renderdoc.

code/ship/ship.cpp
If a ship is destroyed or departed, the special_ship index would get out of sync.  This fixes that.
=> adjust special_ship index if a ship exits a wing

code/starfield/starfield.cpp
'sun' is a reserved keyword on Sun, so use 'bgsun' here instead.  Fixed compilation on OpenIndiana.
=> fix/sun_sun: Use 'bgsun' instead of 'sun'

code/inetfile/chttpget.cpp
This include is needed on Sun platforms for it to have access to FIONBIO.
=> fix/sun_fionbio: Load filio.h on Sun for FIONBIO

code/cfile/cfile.cpp, code/scpui/rocket_ui.cpp
There are fonts with an .otf extension that are similar to .ttf, and in fact can be opened with our TTF code.  So this adds support for that extension.
=> add OTF fonts

code/ship/ship.cpp
Ship recoil modifier isn't cloned or moved in ship_info's clone() and move(), which causes ships to have it essentially uninitialized, and causes all sorts of issues with the physics when a recoil-enabled weapon is fired.
=> Fix usage of ship_recoil_modifier

code/network/chat_api.cpp, code/network/multi_pxo.cpp
Fix bug where searching for a player that isn't online or doesn't exist will cause the next attempt to get pilot info to fail. This failure also triggered a memory access bug in the pilot info error handling.
=> Fix pilot info bug and crash in PXO chat lobby

code/parse/sexp/LuaSEXP.cpp
If you make an error in the Lua SEXP parameter listing, FRED can encounter a modulo-by-zero error in the operator menu listing.  This avoids that.
=> add sanity check to Lua SEXP arguments

code/scripting/scripting.cpp, code/scripting/scripting.h
Since the old system is deprecated it needs to be made obvious that new
hooks should not be added using that system.
=> Add comment about new hooks system to legacy hook list

code/ai/aicode.cpp
Previously, `ai_link_energy_levels_always` or `ai_link_ammo_levels_maybe` could allow a ship to link weapons even if the `No_primary_linking` flag was setfor that ship. This PR fixes that by added a check for `No_primary_linking` before `ai_link_energy_levels_always` or `ai_link_ammo_levels_maybe` is evaluated.
=> Fix Missing Check for Primary Linking

code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/LuaSEXP.h
This is specifically for OPF_SHIP.  Currently if you specify a LuaSEXP with OPF_SHIP, it only works for ships that are present in the mission when the SEXP is called.  This is my attempt at a LuaSEXP parameter variant that will return a valid ship name regardless of the ship status.  It required a bit of finagling the existing API.
=> add the ability to use multiple sexp parameter variants

code/network/multi_fstracker.cpp
Simple fix, already tested.
Adds a function to check if PXO is in use rather than just initialized, so that a very important flag can be properly set.
=> Fix Non-Standalone Servers Failing to Switch Between PXO and Non-PXO

code/menuui/mainhallmenu.cpp
Leaving the ability to go onto the multi screens causes undesired behavior and asserts. (like trying to validate the tables when there is no connection in the first place.)
This also only sets the game state to multi once we're sure that we're going to enter a multi game.
Already tested
=> Keeps players From Accessing Multi Screens When No Connection Available.

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp, code/weapon/weapons.cpp
As is, and far as I've been able to test with a significant chunk of retail, and a few WiH and JAD missions, enabling this flag shouldn't result in any changed behavior. This will lay the groundwork for a better implementation of `ai_turn_towards_vector()` which doesn't result in strong frametime-dependance.
=> Add 'Process AI before Physics' flag

code/scripting/api/libs/audio.cpp, code/scripting/api/objs/audio_stream.cpp, code/scripting/api/objs/audio_stream.h, code/scripting/api/objs/enums.cpp, code/scripting/api/objs/enums.h, code/source_groups.cmake
The previous API only allowed very limited access to the audio stream
system. These changes add full support for playing all types of audio
streams via a dedicated API.
=> Add generic audio stream API

code/ai/aicode.cpp, code/network/multimsgs.cpp, code/object/collideshipweapon.cpp, code/object/objectdock.cpp, code/parse/sexp.cpp, code/physics/physics.cpp, code/physics/physics.h, code/scripting/api/objs/physics_info.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp, code/weapon/beam.cpp, code/weapon/weapons.cpp
This changes all calls to `ship_apply_whack` so that a world position is sent, making them all, most importantly, consistent (this was not true before). All of these paths have been tested to work properly except for the script functions, the scripting implementation is still dark voodoo magic to me, so extra care to ensure I have implemented it properly would be appreciated.
Edit: Also unintentionally fixes #1763 , recoil had always supplied a world position, causing the unusually strong recoil.
=> Supply world coordinates in whack function calls

code/weapon/weapons.cpp
During the free-flight period the coast speed of a missile was being calculated based on the free-flight time, rather than based on the final speed. This returns the logic to what it was in retail, as besides the enclosing condition there isn't any evident reason for the duration to be a factor here.
=> Restored retail-like handling of speed during freeflight time.

code/debris/debris.cpp, code/debris/debris.h, code/gamesnd/gamesnd.cpp, code/gamesnd/gamesnd.h, code/hud/hud.cpp, code/object/collideshipship.cpp, code/ship/ship.cpp, code/ship/ship.h
1) Add debris ambient sounds, specified on a per-class basis
2) Allow -1 to be recognized by `parse_game_sound` (when specifying no-sound for something)
3) Make `CockpitEngineSnd` work for no sounds
4) Add the ability to specify collision sounds
=> Several small sound-related enhancements

lib/lua/luaconf.h
This allows external libraries to load the Lua API from our executable
even if it is linked statically. This is useful for a Lua debugger which
needs to interact with the Lua API.
=> Enable dllexport for Lua API

code/scripting/ade_args.h, code/scripting/api/LuaCoroutineRunner.cpp, code/scripting/scripting.h
These variables can be used for changing the behavior of the ade_ API
functions. However, they apply to all the ade_get calls so if there is a
call to ade_get_args from an ade_get_args call then it will reuse the
previously set values and produce incorrect results.
This captures those variables as soon as possible and then resets them
so that subsequent calls start with the default values for those
variables.
=> Capture Ade skip arguments locally

code/math/vecmat.cpp, code/math/vecmat.h, code/object/objectdock.cpp, code/weapon/beam.cpp
Since the whacking for docked ships code now needs to invert ships inv_moi's where never before this was needed, the numbers produced could end up much too small for floating points and get inverted into infinity and it all goes bad from there. This turns inverse_matrix's calculations into doubles to handle the entire range of floats (the determinant ends up with cubes of the original inv_moi, limiting its accuracy and range significantly when constrained to a float). Any ship with moi values smaller than 1.4323644 × 10^-13 were affected.
This also provides special cases to handle zero (or any other non-invertable) MOIs properly as well, if it is attempted to invert.
=> Banish the Black Void

code/fireball/fireballs.cpp
GCC 10.1.0 complained about the filename overwriting itself in the old version of the code.  This was a false positive, but the code wasn't terribly clear, so I cleaned it up a bit.
=> clean up fireball filename init

code/ship/ship.cpp
After the multilock PR #2207, ships without secondary weapons will crash the game.  This can easily be seen in the very first training mission of the FS2 main campaign, and it is due to an invalid bank access in `ship_stop_secondary_fire`.  The `current_secondary_bank` is 0, but there are 0 secondary banks.  The Assert catches this, but that's not enough.
This change fixes the crash, as it initializes the current banks to -1 instead of 0.  However I'm not familiar with the new multilock way of doing things so I can't say if that is correct in all cases.
=> fix crash from multilock merge

code/scripting/ade.cpp, code/scripting/scripting.h
This fixes three issues where the Lua stack was not cleaned up properly:
- On hook execution, the return value was left on the stack
- For ADE initialization, the global tables were left on the stack
- In libRocket, a metatable was left on the stack
=> Fix various issues of an unbalanced Lua stack

code/debris/debris.cpp, code/debris/debris.h, code/mission/missionparse.cpp, code/scripting/api/libs/mission.cpp, code/scripting/api/objs/debris.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/ship/shiphit.cpp
1) Make Debris dynamic, and use a soft limit at 64 pieces (the old MAX) where the game will try to remove old pieces
2) Add scripting functions to tell whether the debris is a tiny generic/vaporized piece, rather than a modeled piece of ship
3) Allow per-class specification of death roll sounds and subsystem explosion sounds
4) Fix an off-by-one bug in the Debris[] Lua indexer
=> Debris enhancements

code/parse/sexp.cpp, code/parse/sexp.h
These sexps work just like for-counter, supplying arguments for when-argument.  They will list all ships that are present in the mission and are of a certain class or type.
=> add for-ship-class and for-ship-type sexps

code/hud/hudlock.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Pretty much what it says on the tin. A lock is considered valid if it can match into any of the non-empty restriction lists, or if all are empty. Also warnings for invalid names in any of the lists.
=> Allow multilock missiles to restrict lock based on class or species

code/parse/sexp.cpp
All SEXPs that use the new ship registry with`eval_ship` had returned `SEXP_KNOWN_*` or `SEXP_NAN_FOREVER` if the ship entry was not found.  However, ships spawned with `ship-create` will not be in the ship registry and thus these SEXPs would be short-circuited before they ever had a chance to run on the ship.
Since FRED does ship argument error checking, it is far more likely an empty registry entry would be caused by a not-yet-created ship than by an error in the SEXP.  So, I changed all the applicable code to return the non-short-circuiting value.
=> ship-create protecc

code/ai/ai_profiles.cpp, code/ai/ai_profiles.h, code/hud/hudtarget.cpp
Adds a flag that will allow the lead indicator to predict changes in predicted position parabolically based on current rotvel. Allows for better prediction for turning targets but still limited by high time-to-target or fast turn speeds (a parabola can only approximate a circle so far). Might add circular prediction for high rotvel targets at some point but would be more complicated.
=> Allow for second-order lead indicator prediction

code/model/modelread.cpp
Just for sanity's sake.  This just displays a Warning without modifying the dockpoint name.  I considered an nprintf but figured a Warning was more appropriate.
This resolves #2606.
=> add warning for duplicate dockpoints

code/localization/localize.cpp, test/src/menuui/test_intel_parse.cpp
Back in PR #2390, I fixed translation behavior in `lcl_ext_localize_sub` for SCP_string, but neglected to also fix it for `char*`.  This PR remedies that.
I also fixed the string comparison since `SCP_string.compare()` is not case-insensitive.
This bug was discovered while tracking down test inconsistencies in PR #2663, so the test framework is doing its job. :+1:
=> synchronize localization

code/network/multi_campaign.cpp
Campaign.type is not properly set for MP clients and cannot be relied upon.  This may be a temporary fix until I can research better how to set Campaign.type on clients correctly, if it is possible at all.
=> Patch a Crash Point

code/ship/ship.cpp
Overlooked this detail from the multilock PR. Empty banks are allowed to exist and should be treated as "unable to fire".
=> Don't trigger ship_start/stop_secondary_fire assert on empty bank

code/hud/hudartillery.cpp, code/weapon/weapons.cpp
First, in hudartillery.cpp, change some errors to warnings (actually `error_display(1, ...)` to `error_display(0, ...)`, but same difference).
Second, change a `Warning` to an `error_display(0, ...)`, and make it actually name the SSM strike instead of just reporting the name of the weapon it's using.
Third, do the `weapon_info_lookup()` earlier so we can use `error_display()` to point to the right line, and tell the modder that an invalid weapon invalidates the entire SSM strike (instead of just silently discarding the whole thing at the end).
Finally, in weapons.cpp, change `validate_SSM_entries()` to mention if `Ssm_info` is empty (instead of, say, telling the modder that the index needs to be between 0 and 4294967295—or, rather, -1 expressed as an unsigned 32-bit integer, since …
=> Improve error reporting related to SSM strikes.

cmake/toolchain-clang.cmake, cmake/toolchain-gcc.cmake
This does two things:
1. Use thin archives which speeds up static library creation by only
storing references to the object files instead of copying them all
2. Allow to use the gold linker with GCC along with an option for
incremental linking. Since this is undesirable for non-development
builds it is disabled by default.
=> Improve Linux linking performance

code/scripting/ade.cpp
This allows the coder to test for the existence of a hook variable by comparing it to `nil`.  The engine will currently error out and crash if you try to access a nonexistent table field, which is useful for catching typos, but has the disadvantage of disallowing a perfectly reasonable Lua coding practice.  So this change checks whether the missing field is part of `HookVariables`, and if so, rather than throwing an error, it just prints a message to the log.
This is sort of a hackish approach, and will eventually be superseded by a rewrite of the Lua hook variable handling, which @asarium plans to do at some point in the future.
=> temporary hack to increase flexibility of hook variables

code/ai/ai.h, code/ai/aicode.cpp, code/math/vecmat.cpp, code/math/vecmat.h
The AI code makes not one, not two, but three unnecessary and damaging checks for formation and attempting to handle bank. I've commented each location for the problems for each one causes, and how often it wouldn't even do what they were attempting. 
The desired behavior is obvious (as it is mentioned in the code multiple times), while a non-wing leader is flying in formation, it should attempt to match bank with the leader and also move to their assigned relative position. The retail code has the ship turn towards its assigned position, and then later in the function turn to match the leader's orientation. This is wrong in several ways that I've commented, but `ai_turn_towards_vector` comes with an optional `rvec` argument for exactly this reason!! I've added a function that will …
=> Fix AI banking when in formation

code/math/vecmat.cpp, code/math/vecmat.h, test/src/math/test_vecmat.cpp
And also add a unit test for it. Currently, orthogonalize is not guaranteed to actually return an orthogonal matrix if two of the vectors are the same, so the logic is tightened up to ensure orthogonal vectors while retaining as much of the original matrix as possible. This _appears_ to obsolete fix_matrix as well, but it seems like it's used by FRED to have different vector preferences.
=> Improve vm_orthogonalize_matrix safety

code/math/vecmat.h
int epsilon is 0, not a very useful threshold.
=> Fix usage of float instead of int epsilon

code/debris/debris.cpp, code/network/multimsgs.cpp, code/parse/sexp.cpp, code/scripting/api/libs/mission.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/vecmath.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp, code/ship/shiphit.h
1) Add `Hitpos` to the variables passed to the `On Death` scripting hook.
2) When creating a ship using ship-create, allow specification of the team (in both sexp and script).  This allows the right team color to appear in the mission log for the ship arrival entry.
3) Add `getCenterPosition` because the ship local origin is not always at the exact center of the model.
4) Add `getDistanceSquared`.
5) Add a "Ship" hook variable (which duplicates "Self") to the On Death scripting hook.
6) If there is no explosion sound, don't try to play it.  (Same for rearm start sound.)
7) Move the monitor tracing statements for debris creation to where the debris is actually created
=> miscellaneous scripting and ship-destruction enhancements

code/hud/hudlock.cpp
The last fix attempt could actually result in contention based on how many lock slots are locked. This remedies the problem by waiting until after all lock slots have been checked to set the ai_info variable.
=> Properly fix #2685

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp, code/hud/hudtarget.cpp, code/hud/hudtarget.h
Admiral Nelson led me to discover that the HUD gauges expected "right" or no string at all for the gauge alignment.  I added basic recognition of LEFT and RIGHT alignment.  Someone more familiar with the HUD than me can flesh it out more.
=> fix alignments in the hud gauge parsing

code/debris/debris.cpp, code/debris/debris.h
With dynamic debris, as soon as the Debris vector was reallocated it invalidated the `prev` and `next` pointers.  I figured out how to dispense with the actual list entirely, since we mainly need to know how many hull debris pieces there are and whether an individual piece is on the "list".
This is a follow-up to #2649.
=> handle Hull_debris_list for dynamic debris

code/weapon/weapon.h, code/weapon/weapons.cpp
The free flight speed value was added to the weapons table for 3.6.14 but never fully implemented, and subsequently the partial implementation was removed. This restores and completes the feature.
A sort of followup to PR #2632
Resolves #2408, at least the heart of it.
=> Restoring the free flight speed missile table value to functioning

code/ai/ai.h, code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aibig.cpp, code/ai/aicode.cpp, code/parse/sexp.cpp, code/weapon/swarm.cpp, code/weapon/weapons.cpp
Since the overwhelming majority of calls to `ai_turn_towards_vector` use the ship's `srotation_time`, the function is refactored to not need a turn_time passed in at all, and it will presume srotation is being used. The exceptions to this now use a 'turnrate_mod` to change the default. For instance, formation flying calls to the function pass in (1,1,0.2) to have slower than normal banking when turning for that purpose, which restores the similar retail behavior I overlooked in PR #2673 (EDIT: I have since changed formation flying to use a flag instead of this system since it only changed acceleration, but this is the idea).
This allows the default presumption to be changed to the ship's tabled values for each axis, instead of srotation, with the new flag. I will note this in the …
=> Add "$respect ship axial turnrate differences:" flag (and fix a bug with 2673)

code/parse/sexp.cpp, code/parse/sexp.h, code/scripting/api/libs/mission.cpp, code/scripting/api/objs/object.cpp
Collision groups as previously coded were unusable due to Lua 5.1's lack of support for bitwise operators.  This fixes that deficiency in two ways:
1) Objects now have the functions `addToCollisionGroup` and `removeFromCollisionGroup`
2) An `evaluateNumericSEXP` function has been added for returning SEXP results as numbers (so that scripts can use the bitwise SEXP operators)
=> various collision group fixes

code/network/multiteamselect.cpp
According to the testing we've been able to do, this fixes the weird load out memory bug.  It wasn't from the wing_index being negative 1, it was from the wing index being greater than 3.
=> Fix the loadout memory bug

code/ai/aigoals.cpp
The way that this function was structured before would 1. Change the AI mode of player ships (very minor) 2. Keep AI in player wings from doing anything because they were trying to form on the wing of the standalone ship placeholder. 
To clarify, this doesn't mean that they will now start out fighting without order. Instead, they should start out only forming on the wing of their team leader. 
Need to do some more testing to make sure that this is 100% fixed, since Alpha 4 was acting strange during the last test, but otherwise, the initial test looked good.  
Mainly just need to test Team vs. Team on standalone.  This is apparently impossible on one computer, as I just tried and both clients hit an assert.
=> Change MP Initial Player Wing Ship Behavior to Match SP

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/weapon/shockwave.cpp, code/weapon/shockwave.h
Fixes #2526  by making the array a vector and also adds a Shockwaves always damage bombs game_setting.tbl setting and a Shockwaves_consistently_apply_damage game_settings.tbl setting.  The second one keeps bombs and asteroids from being hit more than once by shockwaves, like ships do!
=> Fix 2526 and Add Two Game_setting.tbl flags

cmake/toolchain-gcc.cmake
gc-sections is misbehaving on SunOS since #2669, so skip the part that adds it to restore old behavior unless a proper fix can be found.
The linker flags for SunOS were previously just hardcoded, not using any previously defined variable.  Now it is appending instead, and the --gc-sections flag that it appends is causing it to break due to something with Threads.
```
CMake Error at freespace2/CMakeLists.txt:22 (ADD_EXECUTABLE):
Target "Freespace2" links to target "Threads::Threads" but the target was
not found.  Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?
CMake Error at freespace2/CMakeLists.txt:22 (ADD_EXECUTABLE):
Target "Freespace2" links to target "Threads::Threads" but the target was
not found.  Perhaps a find_package() call is …
```
=> Don't add --gc-sections linker arg on SunOS

code/ai/aicode.cpp, code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/ship.h, code/species_defs/species_defs.cpp, code/species_defs/species_defs.h, fred2/fred.rc, fred2/missionsave.cpp, fred2/resource.h, fred2/wing.cpp, fred2/wing_editor.cpp, fred2/wing_editor.h, qtfred/src/mission/missionsave.cpp
Adds the "$Custom wingmate relative positions:" field to species_defs.tbl. Pretty self-explanatory, modders can now specify whatever positions they want for wingmates to occupy while formation flying. I'll be sure to note in the documentation that these are unscaled by size, and provide the retail positions for reference.
=> Allow for arbitrary wingmate relative positions

code/ai/aicode.cpp, code/network/multiutil.cpp, code/object/object.cpp
This fixes two points at which multi can crash. One is during respawn. The net_signature needs to be set to zero on Ghost Object deletion to facilitate respawn properly. (FSO can get confused between two objects with the same net_signature if it tries to look them up via net_signature, so set the dead one to 0 and the new one from the parse object will be set correctly)
The other fix is during dogfight missions and has to do with errant rearm requests (which are invalid because the player is a traitor in dogfight mode).
It is actually a fix for [Mantis 2175](http://scp.indiegames.us/mantis/view.php?id=2175
) 
From my comments on that ticket. "Checking explicitly for a rearm or repair request before canceling it for traitors is the fix. "
*These changes have been part of all builds that I …
=> Fix Two Multi Crash Points

code/ai/aiturret.cpp
when a turret tries to fire on a ship with a protection flag set, it now logs to the debug log instead of immediately crashing the game if you don't have a debugger
=> removes int3 in turret firing code

code/scripting/scripting.h, test/src/scripting/api/hookvars.cpp
The previous version used the wrong function for the map and so values
added later were not written to the map and so not available to Lua.
This fixes that by using the simple array operator.
=> Allow overwriting hook variables

code/menuui/mainhallmenu.cpp
This is a follow-up to #2675 which fixes the main hall naming for halls which have custom names and are not the first resolution.
=> fix main hall indexing in modular tables

code/menuui/optionsmenu.cpp, freespace2/freespace.cpp
This is a follow-up to #2100.  Don't pause/unpause the audio if we are moving from/to the Control Config or HUD Config screens.  We could hit F2 and move around a bit before resuming the game, so we don't want the audio to resume until we're ready.
=> handle audio pause/unpause for all of the F2 screens

code/camera/camera.cpp, code/camera/camera.h, code/globalincs/systemvars.h, code/hud/hudtarget.cpp, code/io/keycontrol.cpp, code/object/object.cpp, code/object/object.h, code/playerman/playercontrol.cpp, freespace2/freespace.cpp
Three main changes. 
1. Send real frametime to `playercontrol_read_stick` while changing the external view, `frame_time` was modified by time compression causing the external view to be come very difficult to move with joystick (or mouse) while on high time compression.
2. Use an exponential factor when increasing/decreasing the external and chase camera distance, so now it doesn't become unreasonably slow when you're far from your view target or viewing a large target. (capped at 30km now)
3. The biggest change, allow the external camera to get much closer than 2* radius, and instead limiting by an ellipsoid determined by the bounding box. Due to the camera now being more "sensitive" to distance changes (it is more obvious now that you can get much closer), the external camera is more …
=> Add some quality of life improvements to external camera

code/ai/ai.h, code/ai/aicode.cpp, code/autopilot/autopilot.cpp, code/mission/missionparse.cpp
`leader_objp` can't be relied on to provide the formation since it could be some random object the wing was ordered to form up on. Now the wingnum is passed in so the formation is based on whoever is doing the forming up. Also update the new logic for the autopilot version of `get_absolute_wing_pos`.
=> Fix a bug with form-on-wing on a object outside the wing

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Follow-up to PR #2674.  The auto-generated display name shouldn't be saved to the mission file.
This incidentally also fixes newline writing for a couple of lines.
=> don't save display name if it's auto-generated

code/graphics/software/font.cpp, code/localization/localize.cpp, code/localization/localize.h
Without this change certain font tables can hit the meaningless LCL_MAX_FONTS limit, as fotg did.
LCL_MAX_FONTS is kept around just to facilitate parsing of the hard-coded table.
I am not an expert by an means in this part of the code.  I ran both retail and fotg, which uses a font table with more than 5 entries and it seems to work.
Related to #2650
=> Change special_char_indexes to a vector

code/ai/aiturret.cpp, code/mission/mission_flags.h, code/mission/missionparse.cpp, code/scripting/api/objs/parse_object.cpp, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp, code/ship/ship_flags.h, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
Previously the code assumed that an empty display name was the same as no display name.  This adds a flag so that empty names are allowed.
Related to #2674.
=> support zero-length display names

code/camera/camera.cpp, code/hud/hudtarget.cpp
Adds a bit more buffer to the early out for the camera bbox collision function since shields count towards the bounding box, but not the radius. 1.5x should work in practically all situations.
Also no need to reset the camera distance when you're external but not viewing from another ship, changing target in that case doesn't change your camera view.
=> Two small fixes to the external camera

code/ai/ai.h, code/ai/aicode.cpp, code/ai/aigoals.cpp
Every frame every ship flying in formation object mode loops through all objects in order to find its slotnum to determine its rank and file position in the formation. This instead stores the number in `ai_info` and only recalculates when an order to enter or leave formation object mode is processed or a ship that was flying in the mode dies (and also does so for all ships flying off a given ship in one pass).
=> Store and reuse formation object slotnum

code/object/waypoint.h
Somehow this function declaration had the wrong arguments, and the function it declares was unreachable.  So this fixes the arguments so we can reach the function. (Especially because I want to use this in multi)
=> Fix declation of waypoint function so it can be used

code/mission/missionparse.cpp
PR #2718 introduced the Has_display_name flag, but for mission parsing, the parse object flags were cleared subsequent to their assignment.  This moves the flag reset earlier in the function.
=> fix display name

code/libs/jansson.cpp, code/libs/jansson.h, code/scripting/ade_args.cpp, code/scripting/ade_args.h, code/scripting/api/libs/base.cpp, code/scripting/api/objs/bytearray.cpp, code/scripting/api/objs/bytearray.h, code/scripting/api/objs/file.cpp, code/scripting/lua/LuaTable.cpp, code/scripting/lua/LuaTable.h, code/scripting/util/LuaValueDeserializer.cpp, code/scripting/util/LuaValueDeserializer.h, code/scripting/util/LuaValueSerializer.cpp, code/scripting/util/LuaValueSerializer.h, code/source_groups.cmake, test/src/scripting/api/base.cpp, test/test_data/scripting/base/data/scripts/serializeTest.lua, test/test_data/scripting/base/serializeBoolean/data/scripts/test.lua, test/test_data/scripting/base/serializeNil/data/scripts/test.lua, test/test_data/scripting/base/serializeNumber/data/scripts/test.lua, test/test_data/scripting/base/serializeString/data/scripts/test.lua, test/test_data/scripting/base/serializeTable/data/scripts/test.lua, test/test_data/scripting/data/scripts/assert.lua
This can be used by script code for reliably storing Lua values without
having to build a custom serialization format.
The C++ code can also be used by other code modules that want to
serialize data. The new classes simply return a byte array with an
unspecified format.
At the moment this uses a plain JSON encoding but could be extended in
the future to include either compression or BSON encoding if necessary.
The format is future compatible by using a simple header to identify
different kinds of formats.
=> Add Lua API for serializing values

code/graphics/software/FSFont.cpp, code/graphics/software/FSFont.h, code/graphics/software/FontManager.cpp, code/graphics/software/FontManager.h, code/graphics/software/font.cpp, code/graphics/software/font.h, code/localization/localize.cpp, code/localization/localize.h
Now tested on Retail, Admiral Nelson's 4K mod and FotG . Special characters all appear normally.
1. Stores the filename from the table Parser into the font struct so we can lookup fonts via their filename.
2. Allow "+Special Character Font:" to specify the first entry with the same filename's special character index for their own special character index, provide a default if not, or allow the modder to specify them manually, but do not override already recorded values if the default is picked in order to protect retail behavior.
3. Vectorize Special Character Indexes, so that we don't have a table limit that will randomly crash FSO based on what table you happened to write! Woohoo! But provide a minimum to again protect retail behavior.
=> Minor Refactor of Special Character Index Handling

code/localization/localize.cpp
If a mod is running in Unicode mode, ignore Special Character Index if the table happens to supply it.
=> don't break the parser in Unicode mode

code/ship/ship.cpp
This PR adds a scripting hook which triggers when a ship fires a countermeasure. It has two variables, the ship firing the countermeasure and the number of countermeasures remaining. I have tested and it works as expected. This new hook complements the preexistsing `On Secondary Fire` and `On Primary Fire` hooks.
=> Add Scripting Hook `On Countermeasure Fire`

code/ai/aicode.cpp
Keep multi from crashing from an out of bound check when trying to set up a formation for a respawning ship.
=> Fix an ai check

code/localization/localize.cpp
When I wrote the original change to a vector instead of an array, I was working on the assumption that this section of code was parsed after other code that had already made sure that the special_char_indexes vector was at least three entries.  Further testing has revealed this is not always true, and this fix keeps it from crashing.
=> Fix special Char crash

code/ship/ship.cpp
Just happened to stumble across this randomly.
=> Fix a small copy-paste error in parse_ship_values

code/parse/sexp.cpp
Crashes in the multi version of Mystery of the Trinity turned up this bug.  Three multi sexps were setting char arrays to `nullptr`. Not sure *why* instead of making a `TOKEN_LENGTH` array like the rest of the file.  The `memcpy` in the `GET_STRING` macro would cause the crash when it determined it could not write to address `0000000000000000`.
~~What a mystery!~~
Just tested.  Now works as expected.
=> Fix Change IFF Multi Sexp (AKA Mystery of the Nullptr)

code/network/multimsgs.cpp
If a ship has less than two primary weapons the client will set the primary weapon type to 255 instead of -1 due to the data type.
A proper fix for this bug is already included in the multi_packet_fixes PR which allows for more than 255 weapon types for primaries.
=> Fix multi crash when ship has less than two primary weapons

code/missionui/redalert.cpp, code/network/multimsgs.cpp, code/network/multiteamselect.cpp
Still needs a little more testing to verify it works properly on standalone, host, and clients.
Should address the following issues:
- support sync state before entering mission
- return to briefing for sync and stats saving
- handle campaign progression properly
- initialize net_player state properly (fixes #2560)
=> Make redalert missions work better in multi

code/missionui/redalert.cpp, code/parse/sexp.cpp, freespace2/freespace.cpp
This makes the red-alert SEXP execute properly in multiplayer.
Note, this is just the SEXP and a bit of cleanup.  Multi-knowledgeable people will need to evaluate `red_alert_maybe_move_to_next_mission` to make sure that function will work properly in multiplayer.
=> add multi support for red-alert sexp

code/ship/ship.cpp, code/ship/ship.h
The weapon loadout arrays wasted a ton of memory in several ways.  First, only friendly fighters and bombers have weapon loadouts; most ship classes do not need this storage.  Second, as DahBlount noticed, only 8 bits are needed for the flags, while the fields were using standard 32-bit ints.  Third, there are currently 500 weapon types but most loadouts only provide a dozen or so options.
This refactors the loadout storage to keep a short vector of weapon-flag pairs for each bank, and the bank storage is allocated only when needed.  The new `allowed_weapon_bank` class provides `operator[]` implementations so that the new API is almost completely compatible with the old one.  The only things that require the new API are assignments, since `operator[]` is read-only.  (A writable …
=> optimze memory usage by weapon loadout

code/ship/ship.cpp, code/ship/shipfx.cpp
This PR might be a bit confusing if you aren't familiar with the games, but several changes were made:
Stages were added (or more accurately, unused stages were actually used) at the very beginning and end of the effect, for when the "sweeper" is a line and gaining/shrinking in width before/after gaining/shrinking in height.
The first and final two stages when the sweeper is changing size were adjusted to move more smoothly to follow the canonical motion of the effect, as well as timings adjusted.
Allow the sweeper to follow the position of the ship at all stages.
And add the sweeper-type warp to the exclusions from requiring a specific speed before the warp may commence (if a speed was not manually specified). Canonically, Homeworld ships were shown warping regardless of their speed. …
=> Improve Homeworld warp effect

code/ai/aiturret.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
This PR adds a table entry that allows modders to specify the damage threshold for when turrets become less accurate due to weapon subsystem damage. A Game table setting is easier to set once and tune, thus this PR allows that efficient exposure to the modder and does not require a large change or complex table entry.
=> Expose Weapons SS Damage Threshold for Turret Inaccuracy

code/ai/aiturret.cpp, code/scripting/api/objs/subsystem.cpp
The scripted code previously didn't check to see if a weapon bank was valid before firing it, which could have led to memory problems and starting March 15 would actually crash the game.  This adds a few safety checks.
=> make the scripted turret firing code a bit more robust

code/ai/aicode.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/object/object.cpp, code/physics/physics.cpp, code/physics/physics.h, code/ship/ship.cpp, code/weapon/weapons.cpp
Puts issue #487 into a well-deserved grave. I have a lot to say about this PR, even just for posterity reasons so I'm chunking it up into sections.
THE PROBLEM
First, an overview of the problem. In retail for a given AI controlled entity on a given frame, physics happens first, but nothing interesting happens here because the AI's influence hasn't been introduced yet, so we'll just sort of gloss over this first physics step. Later in the frame the AI is run (or `weapon_home` for missiles), it does its decision procedure and decides it wants to turn toward something. In order to do this, it runs `angular_move` which the AI feeds with its angular velocity and acceleration limits, and current angular velocity, and then proceeds to do the basic math -- for each axis it slows down or speeds up …
=> Remove turning framerate dependence for AI

cmake/toolchain-gcc.cmake, code/scpui/RocketLuaSystemInterface.cpp, code/scpui/RocketLuaSystemInterface.h, code/scpui/rocket_ui.cpp, code/source_groups.cmake
This gives every document their own environment instead of using the
global environment. Previously it was necessary to store variables in
the global namespace since otherwise they could not be accessed by event
listeners.
This creates a separate environment table for every document so that all
<script> blocks and event handlers share the same "global" environment.
=> Give Lua libRockets documents their own environment

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp, code/ship/shipfx.cpp, code/weapon/beam.cpp
I went into this PR expecting to implement this, only to find this was always intended! Simply using `Viewer_mode` to determine if the player is in the cockpit is no longer enough as `VM_CAMERA_LOCKED` is true from the get-go. It was modified in PR #848 , but I'm not sure if that behavior (camera_locked being on from the start) is actually a bug or not.
Regardless I've handled the logic slightly differently to allow muzzle flashes to go deep enough to create light, but not the flash animation itself. The idea here is to quietly sweep under the rug the obnoxious bitmaps that would've been flashing in the players face, rather than implying the muzzle flash never existed in the first place.
Also extends the logic to beams, so you can now use BGreens for testing purposes without the entire …
=> Suppress muzzle flashes from the player (and add a flag to re-enable it)

code/ship/shield.cpp
This refers to a global array containing all the shield tris involved in all current shield hits, it's of fixed size and each shield hit is only allowed to contribute 40 tris, any more and it prints that, and bails. Any other triangles involved in the shield hit won't be rendered.
That array is only used when "Shield Effects" detail level is less than 5, and since this will happen practically every time there's a shield hit on a modern ship,  I've had the mprintf only print if that's case. Below max detail the shield hits indeed look terrible, half or more of the triangles don't render and the effect is cut into pieces along the shield. I'm not sure if this is a real problem that should be addressed or what, since it seems that practically no one plays below max given no one has reported …
=> Suppress "Too many triangles in shield hit" log spam

code/math/fvi.cpp, code/math/fvi.h, code/weapon/beam.cpp
The `beam_get_cone_dot` function used for early collision culling will claim that non-slashers could possibly collide in a "very small" cone of 50 degrees. This is obviously absurdly conservative and, more problematically, I could also adversarially beat it and get erroneous early outs. This led me down a rabbit hole of profiling every step of the beam collision process and attempting multiple approaches to improve performance and most importantly, be actually correct in all cases. 
From this profiling I've learned that memory access is almost certainly a greater barrier to speed now as opposed to math, and the various functions calls and basic math trying their damndest to skirt around ever using a square root are no longer really relevant on modern architecture. Replacing the 'dot test' …
=> Improve beam collision optimization

code/parse/sexp.cpp, code/parse/sexp.h
Useful for multiplayer missions.  Lists all currently valid player ships in the mission.  Works in both singleplayer and multiplayer.
=> add for-players sexp

code/weapon/weapons.cpp
This scales down the blast force based on the ship's contribution to its total docked mass, if docked. This will prevent crazy scenarios like small ships being docked to big ships swinging around the big ship like crazy if the small one gets hit by a shockwave, and generally makes ships more resistant to shockwaves if they are docked/the more/bigger ships are docked like one would expect. 
As the comment says this is still not technically generating the correct rotations, since the shockwave will apply a rotational force based on the dimensions of ship's bbox and its orientation to the shockwave; an aggregate bbox would have to be specially calculated and handled for this purpose. While I plan on doing that eventually, this should prevent any egregious or damaging behavior that you could …
=> Improve shockwave handling for docked ships

code/ship/ship.cpp, code/weapon/weapons.cpp
When flags are parsed, they can be reset.  This is a problem for flags that are set based on lines elsewhere in the entry, so each table uses its own method to get around it.  However, not all flags used this method - particularly the new `Has_display_name` flags.  This brings the flag management up to date.
=> fix flags in ships.tbl and weapons.tbl

code/ship/ship.cpp, code/ship/shiphit.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
This is useful if you want to make a weapon that doesn't generate smoke particles on impact.
=> add No_impact_spew weapon flag

code/scripting/api/libs/hookvars.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h, test/src/scripting/api/hookvars.cpp, test/test_data/scripting/hookvars/withHookVars/data/scripts/test.lua
Previously, if a script called a function that called another scripting
hook, some hook variables might be removed. This was the case since
after executing the hook the code would remove the set hook variables
again. If these variables had the same name as previously set variables,
they would overwrite and corrupt the state the original script expected.
This was unexpected behavior for script writers so this puts values on a
stack and only adds or removes from the stack instead of overwriting
values. This should make the hook variable state consistent for scripts
even if scripting hooks are called indirectly.
=> Use a stack for scripting hook variables

code/graphics/software/VFNTFont.cpp, code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/mission/missionmessage.cpp, code/mission/missiontraining.cpp, code/mission/missiontraining.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h, code/stats/medals.cpp, code/stats/medals.h, code/weapon/weapon.h, code/weapon/weapons.cpp
1) Fix underline length calculation in message scrollback
2) Use SCP_string for message source and message text (which allows ships with long display names to work without crashing)
3) Upgrade assorted functions to work with SCP_string
=> Message size fix

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/hud/hudets.cpp
Using the `No_shields` flag for ships is common usage in multiple mods, and as it turns out ships with that flag set will not have the AI manage ETS values due to an early return in the `ai_manage_ets` function. This PR adds an AI flag to allow ships with no shields to manage ETS regarding weapons and engines. This flag was tested and works as expected.
=> Flag to allow ships with no shields to manage ETS

code/hud/hudobserver.cpp, code/io/timer.cpp, code/math/vecmat.cpp, code/math/vecmat.h, code/mission/missionparse.cpp, code/network/multi.cpp, code/network/multi.h, code/network/multi_ingame.cpp, code/network/multi_obj.cpp, code/network/multi_obj.h, code/network/multi_respawn.cpp, code/network/multimsgs.cpp, code/network/multiutil.cpp, code/network/multiutil.h, code/object/waypoint.cpp, code/ship/ship.cpp, code/ship/ship.h, freespace2/freespace.cpp
All right, the second big change.  This basically reworks nearly every part of the object update packet.  I may not have touched the support ship section, but that may be it.
**Things that need to be finished before merging:**
~~1. Need better handling for AI because their movement is literally in another physics system as discovered by @Baezon .~~ Decided that this isn't strictly needed.  The "issue" is that there is minor forward and back jittering of only AI controlled craft. But it's so small that accuracy is not affected.  I will just spend the time writing the lua packet, instead.
~~2. Bug on standalones.  Crash occurs if waypoints are in use.  Cause not yet discovered.~~
~~3. Need to abort adding information to the packet and fix flags once the packet is filled.~~ 
**This …
=> Object update packet upgrade

code/ai/aicode.cpp
Pretty simple fix, `ai_turn_towards_vector` never used `delta_bank_const` so 'Banking Constant' would be ignored for them in most cases. ~~This is default 1, so this won't affect retail.~~ The default is actually 0.5 as mentioned below.
=> Fix banking constant not applying to AI

code/ai/aicode.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
In combination with framerate independent turning, allows modders to actually get the numbers they're listing on the table, rather than attempting to compensate, and also has more logical handling of rotdamp so it will actually effect AI ships more-or-less as it does players (rather than reversed as it is in retail, where more rotdamp meant faster acceleration). I used the '+' on the flag here to hopefully try and indicate more that it is explicitly dependent on the framerate independent turning flag.
=> Add 'AI respect tabled turn time and rotdamp' flag

code/hud/hudets.cpp
This one line fix properly specifies which ship to use for ETS managment. The recent merge of `Non-shielded ships manage ETS` had a object reference error, so this rectifies that. Thanks to Axem for finding this!
=> Fix to Non Shielded Ships Manage ETS

code/ai/aicode.cpp, code/physics/physics.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Allows missiles to accelerate to their maximum turning speed, adds an interesting extra dynamic to their flight, and also makes their path look a bit more realistic, but does require `Framerate_independent_turning`
=> Add 'Turning Acceleration Time' to missiles

code/particle/particle.cpp, code/particle/particle.h, code/particle/util/ParticleProperties.cpp, code/particle/util/ParticleProperties.h
Adds the 'Length' field to particles in particles.tbl, which, when specified, will render the particle like a laser, with the head and tail radius as the 'Size', and the length... as the 'Length'. Importantly also orienting the bitmap along its velocity vector. I'm still acclimating to the fancier C++ structures, so some oversight would be appreciated.
=> Allow for 'laser-style' particles

code/ship/ship.cpp
If you create a kamikaze ship with ship-create, it won't work properly, because the explosion values are not initialized to -1 as expected.  This fixes that.
=> fix a very special case with ship field initialization

code/mission/missiontraining.cpp
A follow-up of sorts to #2801, but independent of it.  If a directive line is not split, the HUD should handle it properly rather than Asserting and displaying the same line twice.
=> properly handle directives with long words

code/weapon/weapons.cpp
Both noticed by @MageKing17 . Homing missiles normally inherit the forward component of their parent object's velocity (plus their intrinsic initial speed), which is all well and good if the missile is pointing forward, but quite nonsensical in any other direction. They should inherit the parent object's velocity *in the direction of missile firing*. 
Additionally, since inheriting this speed is default, `Use_additive_weapon_velocity` should not be double dipping on their speed!
=> Two fixes to initial missile physics set-up

code/network/multi_obj.cpp
Puts a bit more space in the object update packet for the "Stop".  It wasn't properly accounted for previously and would eventually crash in busy missions.
=> stop needs more space so as not to crash during really busy scenes

code/ai/ai.h, code/ai/aicode.cpp
This array was never updated with two AI modes that Sushi created in 2009, leading to mysterious crashes in Debug mode.
=> Add Missing Entries to Submode_text array

code/hud/hudtarget.cpp, code/ship/ship.cpp, code/ship/ship.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Fixes #2812 , and makes remote detonation more robust and flexible in general. The retail handling is pretty crude and does a bunch of futzing about with the missile's objnum and signature, presumably to avoid having to loop through all the missiles in the mission... except that it needs to do this anyway because of dual fire. Now it handles it entirely like dual fire, just loop through all the missiles, if they're mine, a remote detonator, and weren't spawned this frame (preventing premature detonation of child remote detonators being produced by this very loop), then detonate it.
Also puts brackets around all of your remote detonators, retail *did* explicitly comment that only one bracket was on purpose which make sense for dual fire, but when considering things like child spawned …
=> Fix some inconsistencies with remote detonation

code/hud/hudbrackets.cpp
For some reason the entire block that draws brackets, not just for your target, but for message senders, asteroids, remote detonated missiles, and the rest, is gated by your target not being in deathroll, so while it is, you get no brackets on anything. This fixes it so it only excludes your target's brackets.
=> Fix a bug with hud brackets during target deathroll

code/graphics/2d.cpp, code/graphics/2d.h
This will make it easier to have a graphics interface without relying on
global objects since the object can be kept alive in the function
object. No other functional changes since the existing syntax is also
valid for function objects.
=> Change graphics interface to function objects

code/ai/ai.h, code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aibig.cpp, code/ai/aicode.cpp
Tired of enemies afterburning directly into the broad side of an Orion? Not anymore! 
Adds the "$better combat collision avoidance for fightercraft:" flag. While fighting, and only while fighting, (that is, `AIM_CHASE`) small ships will project their velocity outward to predict collisions and avoid colliding with big or huge ships that it finds, before executing any of its submodes. This is sort of collision detection is usually only done while in an attack submode, and only along the me-to-my-target vector, making it only useful to circumvent intervening obstacles. For this reason (and probably also for now irrelevant performance reasons), the timings used by the function are relatively long, so a `time_scale` parameter was added so it could be used much more frequently by the general …
=> Improved collision avoidance for fighters

code/anim/packunpack.cpp
Fixes #2811
Code was moved around between 3.8.0 and 19.0.0 which broke the colored backgrounds of paletted HUD gauges.
Palette index 15 is used by the HUD gauge graphics to indicate background area of HUD gauges. When the code to remap palette indexes to alpha values was moved to packunpack.cpp in Commit 72a797f, palette index 15 was mistakenly mapped to alpha value 0 (nothing) rather than the alpha that palette index 1 would get (which is what retail/3.8.0 code does) causing all HUD gauges to be missing their dark transparent backgrounds.
Also: the code maps palette indexes [0, 15] to alpha values [0, 255]. But due to an oversight (palette index 15 not being part of this gradient and being mapped to a lower value) alpha value 255 is never used so the range of alpha values for HUD gauges …
=> Fix missing background color in paletted HUD gauges

code/scripting/scripting.cpp, test/src/scripting/api/hookvars.cpp
There are some usages where a hook variable is removed blindly which
caused issues in multi.
This fixes #2824.
=> Make removing non-existent hook-vars a no-op

code/ship/ship.cpp, code/weapon/weapons.cpp
`weapon_hit` should handle decrementing `remote_detonaters_active` to cover all the cases where a remote missile is destroyed, after all there's many more cases of you losing a remote missile rather than just you detonating it.
=> Fix `remote_detonaters_active` decrementing

.clang-format, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/decal_draw_list.cpp, code/graphics/grbatch.cpp, code/graphics/grbatch.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h, code/graphics/paths/NanoVGRenderer.h, code/graphics/render.cpp, code/graphics/render.h, code/graphics/util/GPUMemoryHeap.cpp, code/graphics/util/GPUMemoryHeap.h, code/graphics/util/UniformBuffer.cpp, code/graphics/util/UniformBuffer.h, code/graphics/util/UniformBufferManager.cpp, code/graphics/util/UniformBufferManager.h, code/graphics/vulkan/vulkan_stubs.cpp, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/render/batching.cpp, code/render/batching.h, code/scpui/RocketRenderingInterface.cpp, code/scpui/RocketRenderingInterface.h, code/ship/shield.cpp
This converts the previous plain int type for a buffer handle to an
instance of our ID class which provides type safety.
=> Add type safe handle for graphics buffers

code/particle/ParticleManager.cpp, code/particle/ParticleManager.h, code/particle/effects/SingleParticleEffect.cpp, code/particle/util/ParticleProperties.cpp, code/particle/util/ParticleProperties.h
This PR adds the ability to specify a list of bitmaps for a particle effect to choose from. The selected bitmap will be randomly chosen from the list when the individual particle is created. This feature allows modders to make much more varied particle effects much more efficiently. I've tested this with a variety of single and composite effects with both lists and single filenames and everything works as expected.  
Thanks to m!m for all his help with the implementation and preliminary early review!
=> Add 'Choose Random Bitmap' for particle effects

code/ship/ship.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
When enabled, let's a burst reset back to 0 if the full fire wait has elapsed, even if it was 'in the middle' of a burst.
=> Add "resets" burst flag

code/hud/hudlock.cpp, code/hud/hudlock.h, code/hud/hudparse.cpp, code/ship/ship.cpp, code/ship/ship.h
The multilock patch did not handle `Lock_anim` in the best way, and handled `Lock_gauge` in a very bizarre way, despite the fact that they are two simple hud animations.  This changes the `lock_info` struct to track the correct `time_elapsed` value for both, and changes the locking code to use the values in the correct way.
Additionally, this properly loops the lock triangles on the FS1 lock indicator.  Strangely, even prior to the multilock merge it appears that the triangles wouldn't have animated more than a quarter turn.
Finally, this prevents the FS1 lock indicator from blinking, since in retail FS1 it didn't blink.
Tested with FSPort and no-mods.  Fixes #2826.
=> redo the locking animations for multilock

code/debris/debris.cpp
Fixes #2834, a bug where non-capital ships did not generate debris pieces from their hull.  It turns out this bug was introduced in #2416.  If the `DoesNotExpire` flag is substituted for the `lifeleft` variable , it should be done in all locations.
=> fix debris expiration

code/io/mouse.cpp
This was due to the fact that only the main 3 buttons (left, right, and middle) were given hooks for mouse button events.
=> Fixes #2844 where mouse buttons X1 and X2 were not detected.

Copying.md, Unlicense.md
Here is the currently proposed updated terms of licensing for FSO. 
Alongside this change, a list of members that have opted into the new terms under Unlicense will be maintained at [**Licensing**](https://github.com/scp-fs2open/fs2open.github.com/wiki/Licensing).
=> Update terms of Licensing

code/weapon/weapon.h, code/weapon/weapons.cpp
Useful if a laser's bitmap doesn't visually map well to the radius the modder thinks it should have, or otherwise wants a weapon to have a particular radius. Ship-weapon collisions still only check against a ray so this won't affect them, which I may attempt to address at some point, but the specific requester only need it for weapon-weapon collisions so this should be fine for now.
=> Add '$Collision Radius Override' to weapons

code/object/objcollide.cpp, code/weapon/beam.cpp
`pair->b == b->objp` in `beam_collide_missile` (that is, `colliding_missile == beam->objp` ) used to cull collisions will never be true, `beam->objp` will always be a ship, but I've replaced it with a similar check that weapon-weapon collisions do to ensure they never collide if fired from the same parent. Beams don't have `parent_sig` so it has some looking up to do first, essentially preventing a ship's beams from shooting down its own missiles. This is an absurdly unlikely situation normally, but becomes significantly more likely with continuous spawn.
Also renames the abysmally named beam variables in the collision functions so you don't have horribly confusing looking lines like `pair->b == b->objp` (`pair->b` is the other collider, `b` is the beam).
And also removes the bizarre …
=> Better excluding of beam-weapon collisions with the same parent

code/object/collideweaponweapon.cpp, code/ship/ship.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
Because the weapon could still be interceptable and simply not a bomb, and fixed and moved the check into the proper place. And also renamed `Hard_target_bomb` to `No_radius_doubling` because it was a confusing name and... well why wasn't it called that from the get go they shouldn't have different names anyway
Closes #2850
=> Don't warn for "no radius doubling" if the weapon isn't a bomb

code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/ship/ship.cpp
9 year old bug. This will now switches from Player_obj to the shooting object if the shooting object is a player object.  The edited function now uses Player_obj as the default parameter to maintain the same balance for those mods that use this feature.
=> Allow polish_position() to use any player's position in multi

code/weapon/weapons.cpp
It was never initialized, and so could be corrupting all weapons' radius.
=> Fix a bug with collision_radius_override

code/ship/ship.cpp
In commit 3b2af702f764b7f7a7bd5fc35eef6586a6e02cb5, the hash truncation was changed so that instead of being part of the HUD, it's stored as the class's display name. However, this action was performed before `+Use Template:` was parsed, which would then overwrite the display name and clear the `Has_display_name` flag. I've moved it so that it now happens after the copy operation (and added a check for an existing display name, in case the template defines one). I use a new boolean variable to indicate that default display name creation needs to happen rather than duplicate that code.
=> Don't perform automatic hash truncation before template-copying.

lib/libpng/png.c, lib/libpng/png.h, lib/libpng/pngconf.h, lib/libpng/pngdebug.h, lib/libpng/pngerror.c, lib/libpng/pngget.c, lib/libpng/pnginfo.h, lib/libpng/pngmem.c, lib/libpng/pngpread.c, lib/libpng/pngpriv.h, lib/libpng/pngread.c, lib/libpng/pngrio.c, lib/libpng/pngrtran.c, lib/libpng/pngrutil.c, lib/libpng/pngset.c, lib/libpng/pngstruct.h, lib/libpng/pngtrans.c, lib/libpng/pngwio.c, lib/libpng/pngwrite.c, lib/libpng/pngwtran.c, lib/libpng/pngwutil.c
We should update libpng to close the  vulnerability that existed up through 1.6.36. We currently use 1.6.28.
See http://www.libpng.org/pub/png/libpng.html
"libpng versions 1.6.36 and earlier have a use-after-free bug in the simplified libpng API png_image_free(). It has been assigned ID CVE-2019-7317. The vulnerability is fixed in version 1.6.37, released on 15 April 2019."
=> Update libpng to version 1.6.37

code/network/multi.cpp, code/network/multi.h, code/network/multi_obj.cpp, code/network/multi_obj.h, code/network/multimsgs.cpp, code/network/multimsgs.h, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/object/objcollide.cpp, code/object/objcollide.h, code/object/object.cpp, code/ship/ship.cpp, code/ship/ship.h
This creates a packet that sends the relative position and orientation info for a primary or dumbfire missile shot.  The client creates this packet when firing those two types of weapons and sends it to the server.  The server goes back to the frame that the client fired the weapon and quickly re-simulates all the frames in-between.
This includes collision detection, restoring positions, orientations and velocities, but not subsystem orientations.
Now that the object update packet is merged, note that this is mainly to ensure that high ping clients can fire primary shots with the same accuracy on server and client.
=> Multiplayer Resimulation for Client Fired Linear Weapons (Rollback)

code/ai/aiturret.cpp, code/hud/hudartillery.cpp, code/network/multimsgs.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/weapon/beam.cpp, code/weapon/beam.h, code/weapon/weapons.cpp
Adds a `beam_has_valid_params` function that beams use to validate their vital inputs. This was being handled pretty much ok already, but having an actual exhaustive list of the ways beams can be fired and what sorts of data they're actually supposed to have is A. less confusing and B. useful for multiplayer, which was the main impetus for this change. The changes to beam packet sending/receiving are here mostly just not to break anything in general, as @notimaginative will have a much better version of these soon. 
~~Also finishes removing `delta_ang` . This was only ever used in some dubious collision checking for beams that was fixed in #2735 , and `BEAM_T` which returns the 0-1 value of the beam's lifetime where it uselessly multiplied and divided by `delta_ang`.~~ holding off on this …
=> Add beam parameter validation

freespace2/freespace.cpp
This was requested by Kiloku, since the "Self" hookvar (which points to the current Viewer_obj) is unreliable and not guaranteed to actually exist.
=> Add the "Player" hook variable to the CHA_HUDDRAW scripting trigger

code/network/multi_obj.cpp
This is for an edge case crash.  A small minority of AI values was causing crashes on clients because the target being nullptr was not being handled correctly with my upgraded object update code.  Because this only changes the logic that handles incoming information, there is no need for a multi bump.
Still needs testing, so leaving it in draft status for now.
=> AI Edge Case Fix

code/scripting/api/libs/base.cpp
The documention stating of its optional parameter `[boolean adjustForTimeCompression]` is inverse of what the function actually does, setting this to true will give you the real frametime, instead. So per @asarium's suggestion, I've deprecated the old function in favor of two separate functions for each kind of frametime. I'm still not super happy with this approach, but I'm not sure how else to handle it.
IF YOU HAVE ANY SCRIPTS USING THIS YOU MAY WANT TO DOUBLE CHECK ITS IMPLEMENTATION.
getFrametime(true) -> Real frametime.
getFrametime(false or omitted) -> time compressed frametime.
EDIT: This is the crux of #2364
=> Fix 'getFrametime' scripting function

code/weapon/weapons.cpp
When the weapon state is changed for the purposes of creating particle sources, while switching to the new one it checks if the old one was `WeaponState::INVALID` and if so attempts to create a `WeaponState::NORMAL` particle source. Given that the normal, not-invalid case creates a new source for the new state directly afterwards anyway, this is redundant and causes NORMAL weapon states (that is, particles spawned by primaries) to have double the particle sources.
Additionally an invalid `wp->homing_object` is `&obj_used_list` and not `nullptr`, this was causing all dumbfired missiles to not create any particle sources at all.
=> Two fixes to weapon states

code/ship/afterburner.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h
Exposes minimum fuel to afterburn, and allows specifying a minimum time between aferburnings and a requisite amount of fuel to burn, which will continue on its own until it is consumed.
Closes #2867
=> Add some new afterburner options

code/missionui/fictionviewer.cpp, code/missionui/missioncmdbrief.cpp, code/missionui/redalert.cpp, freespace2/freespace.cpp
Fixes crashing in multi where ships are locked by host while a
client is on fiction viewer, command brief, red alert, or cutscene.
=> Call common_select_init() before cutscenes where needed

code/model/modelanim.cpp
Even after some investigation, it was pretty difficult to for me to try and pry apart the model animation code and properly diagnose this. I stumbled on this merely by walking back changes in #2195 , which was confirmed to be the cause of #2882 . I've checked out other animations, mostly those from BP ships, and all of them continue to function normally after this change, and if anyone can think of any other cases, I'd be happy to test those as well.
The relevant code seems to be returning the total time of an animation, and in the problem case `psub->triggers[i].end + psub->triggers[i].start` was 9000, 9 seconds total, rather than 0. The other cases, such as the BP ships also go through this code without problem with or without this change so I'm not really sure what the root cause of …
=> Fix a bug with model animation

code/weapon/corkscrew.cpp, code/weapon/weapons.cpp
No particle spew during stage 3, don't update the trail for corkscrew missiles in stage 3, kill the old trail, and create a new one when entering/exiting warp, and make sure to use the model's radius for the warp effect, in case the object''s radius was overwritten. 
Closes #2792
=> Some visual fixes to local ssms

code/ship/ship.cpp, code/ship/ship.h
This variable is never used and could cause a memory leak if anything about it was accidentally altered.  Also, ship creation will end up creating an entry for every tri in the shield mesh,meaning that we're being pretty inefficient by keeping it in.
=> Remove the unused shield_integrity field

lib/freetype.cmake, lib/prebuilt.cmake
Requires the FreeType static library for Mac found in [scp-prebuilt repo's PR 7](https://github.com/scp-fs2open/scp-prebuilt/pull/7).
Fixes Issue #2370 .
=> Use prebuilt FreeType library on Mac

code/mission/missionparse.cpp, code/mission/missionparse.h, code/network/multiteamselect.cpp
Fixes a bug where the loadout will be different when respawning or with in-game joining if the iff of the ship/wing has changed since the mission started.
=> Prevent loadout issues in multi due to iff changes

code/weapon/shockwave.cpp, code/weapon/shockwave.h, code/weapon/weapons.cpp
`$Damage` only updates the shockwave's damage the first time through, future .tbms won't affect it. With this, changes to `$Damage` also affect the shockwave damage unless it was specifically set.
=> Fix a bug with shockwave damage parsing

code/asteroid/asteroid.cpp, code/debris/debris.cpp, code/model/modelrender.cpp, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/ship/shipfx.cpp, code/ship/shipfx.h, code/weapon/beam.cpp, freespace2/freespace.cpp
There was a lot of duplication with checks against the warp clip plane depending on if the ship was arriving or departing so I've modified the default and homeworld `getWarpOrientation` to invert when warping out as one might expect (those two are the only ones that need their orientation like this) (`getWarpOrientation` is only used for this purpose; culling stuff on the other side) and made a function to deal with handling what side a point is on, so all the cases can be handled consistently.
There were some sign errors and ordering issues with ship-weapon collisions that were fixed, and checks against the warp plane were added for several types of collisions.
This *only prevents* where otherwise it *would* have collided, if it *would not* have collided before, it will *still not* now. …
=> Fix some issues with warp collision

code/parse/sexp.cpp
Make sure that the oswpt object will have the correct status for an exited ship.
=> Make sure that the oswpt object will have the correct status 

code/network/multi_obj.cpp
Basically, if the anti rubber-banding code is too aggressive, ships (especially ships without afterburners) will be kept from moving forward at all.  This reduces the anti rubber-banding to half its original strength.
As discussed with @Baezon
=> Make Anti-Rubberbanding less aggressive to keep the client from showing nonsense
