code/ai/aicode.cpp
code/hud/hudlock.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

Moved the restrictions parsing so it applies to non-aspect seeking and non-multilock missiles as well, including single target missiles and heat seeking missiles. Renamed some stuff to make this clear.
Since IFF restrictions can now be specified, including friendlies, using IFF restrictions at all will preclude the normal IFF targeting restrictions (hostiles only, no friendlies, etc) so the `weapon_has_iff_restrictions()` function is used to determine if this is case.

Add IFF to missile lock restrictions, and now all missiles can use them

---

code/ai/ai.h
code/ai/ai_flags.h
code/ai/aicode.cpp
code/parse/sexp.cpp
code/physics/physics.h
code/scripting/api/objs/ship.cpp

Maneuvers normally clear any existing maneuvers before taking effect, with this flag it will not do that. Though it does refresh the duration of the old maneuver, which is unideal, this allows for independent sexp/scripting control over lateral and rotational maneuvers at the same time, which is incredibly useful.

Add 'Dont_override_old_maneuvers' flag to maneuvers

---

code/mission/missionhotkey.cpp

This very very slightly alters existing behaviour, in that hotkeys the player has *removed* will not persist the way they used to, but it fixes the far greater outstanding problem of mission-specified hotkeys, a very widely used tool nowadays, being dropped very frequently between replays.
Edit: after revision the fix will now reflect the old (weird) behaviour on any group the player has actually added to in the first 15 seconds of the mission, but otherwise will use the mission defaults.

Only save hotkeys if the player has actually added to the group, otherwise leave mission defaults in place

---

code/ai/aicode.cpp
code/ship/ship.cpp

`find_adjusted_dockpoint_info()` used for various docking procedures to determine the situation of a dockpoint, notably `DOA_DOCK_STAY` in order to stay rigidly docked to an object, normally returns `docker_p0` `docker_p1` and `docker_p0_norm`, *global* positions (and global directional vector). From these the 'true' position of the dockpoint and its orientation is calculated; its uvec for instance is the p1->p0 directional vector. However since these are global positions being used to create a normalized vector, they can be quite sensitive to floating point inaccuracy when the distances are great (only 20km or so for Mystery of the Trinity can occasionally cause this to be visible).
Since every caller of `find_adjusted_dockpoint_info()` uses these points to make the position and …

Reduce docking 'jitter'

---

code/mission/missionparse.cpp
code/ship/ship.cpp
code/ship/ship.h

So, this should actually *fix* invalid squadron names in multi.  Already tested as working for the test case.  Cannot seem to get the warning to show up, though...

Warn about and correct invalid squadron wings in multi

---

code/network/multiui.cpp

When pressing escape, it was previously possible to attempt saving the stats multiple times, but this will keep it to just one attempt.

Fix multiplayer stat save

---

code/ship/ship.cpp
code/ship/ship.h

Another small death-related addition: whether a ship splits in two at the end of its death roll can now be set separately from a propagating explosion.

Separate ship splitting explosions from propagating explosions

---

code/ai/aicode.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/ship_flags.h
code/ship/shiphit.cpp

Two simple additions, a flags that makes big|huge ships do a deathroll (running AI on them despite being dying clobbers their `desired_rotvel` normally), and a multiplier for the intensity of the death roll rotation.

Death roll for big ships and a death roll multiplier

---

code/particle/effects/GenericShapeEffect.h

There are some possibilities where we could get an expired pointer when
we create a persistent particle. This adds a check for that to avoid
crashing the engine in those case.
This is related to #2928.

Cover edge case in particle code

---

code/parse/sexp.cpp

The apparent intention of this call to CDR is already fulfilled in eval_sexp on line 23113, which passes this value into child functions including sexp_allow_treason. As a result the latter function will end up CDR'ing into a one-element list, producing (), which evaluates to false, and the allow-treason sexp consequently fails to work.

Remove erroneous call to CDR.

---

code/network/multi_obj.cpp

This was always writing a warning about negative timestamps to the log.  But negative timestamp differentials are supposed to happen on the first two frames because there is no actual information to compare to.

Slightly alter when a timestamp warning is written to the log.

---

code/parse/sexp.cpp
code/parse/sexp.h

It takes a number as a maximum number of arguments that can be evaluated in a single call, but otherwise behaves very similarly to `any-of`; alternatively, if the number is 1, it's like an `in-sequence` that also skips arguments that don't satisfy the condition instead of just invalid ones.

Add "first-of" SEXP that behaves like "any-of" with a cap.

---

code/parse/sexp.cpp

This is a follow-up to PR #2942.  Given that the short-circuiting is now explicitly skipped for node trees containing the special argument, it should no longer be necessary to flush the conditional branch of the sexp tree.  (The .cache field is already skipped for special-arg nodes.)
The sexp tree is still explicitly flushed for `every-time` and `every-time-argument`.

don't flush the tree when evaluating the *-argument conditionals

---

code/parse/sexp.cpp

We should compare `sec_slot` to `MAX_SHIP_SECONDARY_BANKS`, not `MAX_SHIP_PRIMARY_BANKS`.

Fix turret-change-weapon comparing sec_slot to max primary banks.

---

code/hud/hud.cpp
code/hud/hud.h
code/scripting/api/libs/hud.cpp

Previously, the Scripting API functions setHUDGaugeColor and getHUDGaugeColor referred to HUD_config, which stores the configuration of the gauges by the user. However, modifying the configuration this way does not modify the gauge color in mission.
After this change, it does by accessing not the configuration but rather the currently loaded gauges.
In addition, a new virtvar is added to the HUD environment to allow scripts to query the number of existing gauges (so that this does not need to be hardcoded and subsequently be in danger of failing with an update of the gauges)

Scripting Bugfix: previous HUD set/get gauge color referred to config instead of ingame gauge

---

code/ai/aiturret.cpp

With `fire_down_normals` `ship_get_global_turret_info()` properly sets up `gvec` to be actually pointing in the direction the turret is, which is used by the turret firing code prior to this to determine things like being in fov, but when it comes to actually firing it doesn't bother and just fires straight at its target. This is fine normally, but given we have a specific flag to force firing down `gvec` its quite unintuitive that this won't be the case for normal weapons (it is only used by beams AFAICT).
Also a little readability change right next to it because it was bothering me. I dunno about you guys but if a big function call might need several different arguments, I prefer setting up the arguments beforehand, and calling the function once rather than a bunch of conditional calls …

Allow normal weapons to use 'fire down normals'

---

code/object/collideshipship.cpp

Refers to Issue #2953 
All I've done to fix this, is move some code. Namely, the function ship_ship_check_collision (which is supposed to _check_ if there is a collision) contained some code to already handle and process the collision (push objects around and notify AI). This code, I've moved after the override checks of the lua API. I did not modify this code (apart from the renaming of variables that were passed down into the function and the subsequent direct accessing as opposed to dereferencing the passed pointers) and copied it as a whole block.
Note, that the other functions for detection of those collisions (debris_check_collision, asteroid_check_collision, and so on) do exactly that, and only do detection and not physics handling, which is then processed after checking the …

Modified Ship-Ship Collision Overrides to fit other Ship-X collision Overrides

---

code/mod_table/mod_table.cpp

Asteroth's framerate-independent turning feature put a huge amount of work into remaining backwards-compatible with retail behaviour at 60FPS, and at this stage I've been playing with it turned on for everything for months and I've yet to find an identifiable bug due to it in any mod. I think it's definitely time to switch it on by default (leaving the table flags in place so that mods still have the option to disable it). The only thing it needs now is more thorough testing for full compatibility, and the best way to get that is to have it incorporated into the release candidate builds.

Turn framerate-independent turning on by default

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aiturret.cpp
code/mission/missionparse.cpp
code/ship/ship.cpp
code/ship/ship.h

I did a careful review of all the functions in aiturret.cpp.  This cleans up the code a bit to more closely follow the original code flow from the public code release (for ease of comparison) and fixes several bugs.
1) fixed other weapons on a turret being handicapped by spawning weapon fire rate
2) fixed beam-free flag on a turret with multiple weapons
3) fixed turret accuracy penalty never being applied
4) fixed weapon timestamp being overridden
5) fixed player sound not being played, if specified, with swarm turret weapons
6) fixed flak not jittering if it had the fire-down-normals flag
This finally resolves Mantis 804.
http://scp.indiegames.us/mantis/view.php?id=804

some fixes to aiturret code

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aicode.cpp
code/ai/aiinternal.h
code/ship/ship.cpp
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

This added the Weapon Flag "require exact los", which will prevent AI form firing it from a turret or as a secondary weapon if there is no clear line of sight from the AI's ship (center) to it's targeted ship (center)
In addition, this added the AI Profile Flag "$firing requires exact los:", which has the same effect, but applied to all turrets and AI controlled secondaries regardless of weapon or weapon flags

Add flag for AI to only fire Turrets / Secondaries when having clear Line of Sight

---

code/parse/sexp.cpp

Fixes issue #2960 
The existing logic for black fade-ins is overridden to use whatever color the previous fade-out did, and at some point during the end of the cutscene, the fade_out colors were being bashed to white.
edit:  As insurance, init the fade_out color to black at mission start with init_sexp

Save fade-out color, even if its black.

---

code/weapon/beam.cpp

Actually 0 width causes problems so I've capped it at a minimum 0.1 just like shrinking does. I think that's kind of high, and I'm also not a huge fan of doing this silently but this is exactly how shrink handles it so... dunno.

Fix an assert with 0 initial beam width

---

code/osapi/dialogs.cpp

By setting the parent window of dialogs to NULL instead of the FSO context, this should make them refocusable, even through the fullscreen context being blocked by the dialog itself.
Should fix #2949

When Fullscreen, dialogs have no parent now. Should fix #2949

---

code/hud/hud.cpp

Someone apparently already did the work of separating the render code from the lock tracking code, now we just make sure that this function always runs even if the hud is disabled. (it just makes sense for it to)  
I tried this out and it works as expected with hud disabled: turning away from your target breaks lock, turning towards your target allows you to acquire lock, and lock is maintained if it was already present and you are facing the target.
For issue #1821 
EDIT: Btw, the locking sounds still run with the HUD disabled, should I add logic that disables it if the hud is disabled?

Make sure lock indicators are done even if hud is disabled

---

code/CMakeLists.txt
code/globalincs/toolchain/msvc.h
code/network/multi.cpp
code/network/multi_endgame.cpp
code/network/multi_mdns.cpp
code/network/multi_mdns.h
code/network/multimsgs.cpp
code/network/multiui.cpp
code/network/psnet2.cpp
code/network/psnet2.h
code/source_groups.cmake
lib/CMakeLists.txt
lib/mdns/CMakeLists.txt
lib/mdns/LICENSE
lib/mdns/README.md
lib/mdns/mdns.c
lib/mdns/mdns.h

This replaces the original multicast code with mDNS/DNS-SD and should allow for LAN discovery with minimal to zero effort on the part of users.

Replace multicast code with mDNS/DNS-SD

---

.github/workflows/build-dist.yaml
ci/github/dist_functions.sh

This creates a new workflow which will build linux binaries for
FastDebug and Release, combine them in a second step, and then upload
them.

Build Linux nightlies with GitHub actions

---

.github/workflows/pr-workflow.yaml
ci/travis/valgrind.supp

This will make our builds independent of the underlying system and allow
for more reproducible builds since everything uses the same compilers
and environments.

Use container for Linux building

---

code/ai/aicode.cpp
code/mission/missionparse.cpp
code/missionui/redalert.cpp
code/model/model.h
code/model/modelanim.cpp
code/model/modelcollide.cpp
code/model/modelread.cpp
code/object/collideshipship.cpp
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/shipfx.cpp
code/ship/shiphit.cpp

Several housekeeping changes in preparation for the submodel rotation upgrade.  These are in a separate PR so as to not clutter up the upcoming main PR.  All changes should be no-ops.

Model preliminary edits

---

code/hud/hudlock.cpp

It would only lock on _out_ of sight subsystems. Whoops!

Fix line-of-sight checking for multilock

---

code/debris/debris.cpp
code/ship/shipfx.cpp
code/ship/shiphit.cpp

There were null checks for `Player_obj`, but whoever added the `No_pain_flash` flag bypassed them by dereferencing `Player_obj` in the top-level if() block.  This caused a crash when self-destructing ships in the F3 lab.
This PR moves the `Player_obj` check to the top-level block (which is also an implicit null check because `ship_objp` is not null by this point) which fixes the crash and also is more efficient.
EDIT: Added two more null checks for the same reason.

fix a CTD with the no-pain-flash flag

---

code/scripting/api/objs/subsystem.cpp

The object `instance` field is the index into Ships, not Objects.  In any case, position and orientation can be referenced directly.

fix a bit of improper referencing in rotateTurret

---

.github/workflows/pr-workflow.yaml
ci/linux/clang-tidy-diff.py
ci/linux/clang_tidy.sh

This action should bring the clang-tidy issues in a better format by
displaying them inline in the diff.

Use special GitHub action for clang-tidy

---

code/ai/aibig.cpp
code/ai/aicode.cpp
code/ai/aiturret.cpp
code/asteroid/asteroid.cpp
code/camera/camera.cpp
code/debris/debris.cpp
code/mission/missionparse.cpp
code/model/model.h
code/model/modelcollide.cpp
code/model/modelread.cpp
code/model/modelrender.cpp
code/network/multi_obj.cpp
code/object/collideshipship.cpp
code/object/collideshipweapon.cpp
code/particle/ParticleSource.cpp
code/scripting/api/objs/model_path.cpp
code/scripting/api/objs/subsystem.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/shipfx.cpp
code/ship/shipfx.h
code/ship/shiphit.cpp

More housekeeping changes to the model code, similar to PR #2971, prior to the submodel rotation upgrade.  This reduces the number of model lookups when iterating over submodels and subsystems, which makes collision and rendering code ever so slightly more efficient.  But it's mostly useful for type safety and organization.
This is now ready to review.

hoist model_get and model_get_instance out of a bunch of functions

---

.github/workflows/build-dist.yaml
.github/workflows/pr-workflow.yaml
ci/github/dist_functions.sh

Also run distribution builds in container. This uses the same container
for building PRs and distribution packages to ensure consistency
between them.
Also tries to fix an issue with a missing environment variable for the
tests.

Enable upload to datacorder for Linux builds

---

.github/workflows/build-dist.yaml
ci/appveyor/build.ps1
ci/github/dist_functions.sh
test/CMakeLists.txt

This is much faster since all build variations can be compiled at the
same time. Only applies to nightly builds for now.

Build Windows nightlies with GitHub actions

---

code/lab/dialogs/actions.cpp

The lab code didn't set subsystem strength for destroyed submodels.  This fixes that.

subobjects destroyed in the lab should stop spinning

---

code/lab/manager/lab_manager.cpp

Print the model filename in the bottom right when a ship or modelled weapon is being displayed in the lab

Fix oversight in the new lab HUD

---

code/ai/aibig.cpp
code/ai/aicode.cpp
code/ai/aiturret.cpp
code/asteroid/asteroid.cpp
code/debris/debris.cpp
code/decals/decals.cpp
code/hud/hudtarget.cpp
code/menuui/techmenu.cpp
code/mission/missionparse.cpp
code/missionui/redalert.cpp
code/model/model.h
code/model/modelanim.cpp
code/model/modelcollide.cpp
code/model/modelread.cpp
code/model/modelrender.cpp
code/network/multi_obj.cpp
code/network/multimsgs.cpp
code/object/collideshipship.cpp
code/parse/sexp.cpp
code/scripting/api/objs/subsystem.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/shipfx.cpp
code/ship/shiphit.cpp

Swifty's earlier model instance refactoring feature got 90% of the way to the goal, but there was still some parts of code that kept stuffing angles into the model for every game frame, rather than keeping the angles properly separate in the model instances.  This PR properly consolidates and compartmentalizes the angles to just the model instances.
(Gun submodel rotation, electrical arcing, and texture management are still stuffed into the model instead of handled in model instances, but those are probably best handled in a separate PR.)
This is a prerequisite to the upcoming animation system upgrade because the animation is a lot simpler if it is only handled in one data structure rather than three redundant data structures.

consolidate model instance code

---

code/scripting/api/libs/mission.cpp

This adds a functionality so that scripts can check whether the current mission is a nebula mission and if it is a subspace mission.

Add Scripting API isNebula and isSubspace

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
ci/appveyor/build.ps1
ci/linux/create_dist_pack.sh
ci/linux/dist_functions.sh
ci/linux/generate_appimage.sh

This uses GitHub actions for building Linux and Windows builds for
release tags.
Appveyor is now no longer used for building distribution packages and is
also not used for anything relevant anymore. If this works properly we
can disable that PR check to get better PR scalability.

Add GitHub workflow for building releases

---

code/hud/hudlock.cpp

This should handle #2952 by setting a consistent timestamp for locked indicators instead of accidentally inheriting them from indicators that are still locking.  Tested with normal and multilock missiles.
Took entirely too long to track down.

Set correct time stamp for already-locked indicators.

---

freespace2/freespace.cpp

Fixes #2966 
This needs some avid testing from other folks to ensure there's no side effects.  I'm not sure how SDL handles its error and debug outputs, so its possible this change may affect them.
Based on: [https://stackoverflow.com/questions/34539135/how-do-i-print-to-the-console-while-an-sdl-2-program-is-running](url)

In windows, attach to the console we're being evoked from and reopen STDIO streams.

---

code/debris/debris.cpp
code/debris/debris.h
code/graphics/shadows.cpp
code/hud/hudtargetbox.cpp
code/model/model.h
code/model/modelread.cpp
code/model/modelrender.cpp
code/model/modelrender.h
code/object/object.cpp
code/object/object.h
code/ship/ship.cpp
code/ship/shipfx.cpp

A small follow-up to #2992.  This removes arc information from bsp_info and moves it to submodel_instance.  It also adds a model instance to each debris chunk to keep track of it.

another model to model_instance refactor

---

code/mission/missionparse.cpp
code/missionui/redalert.cpp

Some subsystem code was being run for submodels when the subsystem didn't necessarily have a submodel attached.

additional null checks

---

code/model/modelread.cpp

Since angles are no longer written in three redundant places, the temporary hijacking of the turret angles in `model_make_turret_matrix` was overwriting the turret's proper position.  So this PR just saves the angles and restores them when the calculation is done.
Fixes #3013.

properly restore turret angles after calculating matrix

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
ci/linux/clang_tidy.sh

By only looking at the HEADs of the respective branches, we included
irrelevant changes in the diff passed to clang-tidy-diff so it was
possible to generate irrelevant warnings in a PR.

Fix clang tidy commit range

---

code/osapi/osapi.cpp

This can be useful when SDL produces log output that helps with
debugging an issue.

Capture SDL logs to our standard logging output

---

code/hud/hudtarget.cpp
code/model/model.h
code/model/modelread.cpp
code/model/modelrender.cpp
code/model/modelrender.h
code/ship/ship.cpp
code/ship/ship.h

Since instance-specific fields have been moved to polymodel_instance and submodel_instance, the gun_submodel_rotation field should also be moved.  This is also reworked a bit to keeping track of the rotation via the normal submodel instance angles.
This removes an unnecessary look_at field as well.

move gun_submodel_rotation from model to instance

---

code/model/modelinterp.cpp

This works around the Windows only limitation where the standard random
function only returns up to 2^15 which limits how many vertices in the
model can be picked.
Since we already have a function that handles this properly and returns
values in the entire integer range, using that fixes that low limit.

Make model point picking more flexible

---

code/ai/aicode.cpp

When weapon info flags were changed to the flagset model in #851 (commit 127976cd74e2205f928e7de79c5d89ad555f7796), two instances where `WIF2_CAPITAL_PLUS` was either actively desired or passively not prohibited were lost in the transition; this commit restores looking for `Weapon::Info_Flags::Capital_plus` when targeting a big ship, and no longer prohibits capital+ weapons from being selected if a bomber+ weapon is sought and smart secondary weapon selection is enabled.

Fix capital+ regression in AI code for secondary weapon selection.

---

freespace2/freespace.cpp

Keeps incompatible commandline options from running simultaneously, forces -start_mission to run in SP, and prints what FSO is doing to the debug log.
Previously running them simultaneously would run into an invalid game state that cannot be escaped by the user.  Also running -start_mission in multi mode would also lead to an invalid game state that cannot be escaped by the user.

Keep incompatible commandline options from running simultaneously

---

code/scripting/api/libs/graphics.cpp

This was 20.1 since I erronously thought that the "current" nightly
version was lower than that. This updates the version to a release that
has not been built yet.
Fixes #3027.

Update deprecation version of drawMonochromeImage

---

code/model/modelread.cpp

As implied in #3021, the choice of `break` vs. `return` is not necessarily obvious.  I figured some documentation would help.

add documentation to get_user_vec3d_value

---

code/ai/aicode.cpp
code/ai/aiinternal.h
code/ai/aiturret.cpp

As this feature is very new, it's probably fine to change it instead of adding a new flag.
This change make the actual firing point of the turret / secondary bank matter and not just raycast center to center, which should help for large capital ships using this flag.
While it seems to work for me, I'd like some help with testing. Pinging @EatThePath, as he requested this change for a specific mission it seems.

Changed require exact los to track from the exact firing point instead of center

---

code/object/objectdock.cpp

This is an issue that only occurs on release builds. I suspect debug builds silently filter bad ID's earlier when evaluating collisions.
The issue is not directly the object (presumably the player) being null, rather it's id being invalid. This filters this, but obviously doesn't really solve the underlying issue, of the player's ship being target for docking even after dying.
For more context, the stack was:
ship_ship_check_collision
->check_for_docking_collision (the aip2->mode == AIM_DOCK branch)
-> dock_check_find_docked_object
bad read on (now) line 119, the function call to dock_evaluate_all_docked_objects

Fix CTD on death while support is trying to dock

---

code/particle/ParticleManager.cpp

In the particle effect code there is a small hack required for getting
some constant pointers in a vector. However, there is another mechanism
where sources are not added to the sources vector if the sources are
currently being iterated through. That is necessary to avoid
accidentally invalidating the iterators.
The issue here was that the vector resizing hack was not applied to the
correct vector when we were currently iterating. This fixes that.
This fixes #2928.

Apply particle source hack to correct vector

---

code/network/multi_obj.cpp

This fixes one of the required fields for the support ship not being set for mulitplayer clients.

Set target name in ai goals to avoid an assert

---

.github/workflows/build-test.yaml
ci/linux/dist_functions.sh
ci/linux/upload_dist_package.sh

This was previously a feature of Travis and Appveyor and is very useful for producing all necessary builds for testing purposes.

Add GitHub actions test build support

---

code/math/vecmat.cpp
code/math/vecmat.h
code/model/modelread.cpp
code/network/multi_obj.h

Some things that clang noticed, plus a small usability improvement to the parsing of vectors in submodel properties.
Also add the `vm_vec_delta_ang_norm_safe` function.

some bugfixes from the submodel rotation branch

---

code/osapi/osapi.cpp

This may not be the correct approach for this, but the code here crashes without a window open or debug log created if SDL cannot get the preferred path.  I started encountering this crash without any noticeable cause except for the fact that my builds were being created in a sub-directory of documents (which I've been doing for 18 months without issue).  
I went with the option of having a pretty verbose warning message, telling the user FSO will attempt to use the current directory, but will probably crash without a warning message.
This avoids the immediate crash, and warns the user, but it cannot prevent the other things that will occur, like a possible crash when trying to load OpenAL.  
I don't mind switching to an Error instead of a warning if requested.

Prevent almost immediate crash and Warn User about corrupt/unreachable SDL.dll

---

code/weapon/weapons.cpp

Add calculations for the `puncture` flag, and handle beam damage factors appropriately.
Fixes #3044.

weaponspew fixes

---

code/missionui/missionweaponchoice.cpp
code/network/multimsgs.cpp
code/ship/ship.h

This is a bug that periodically appears on discord, most often when players see they've been given 60 trebs by the support ship.  Basically what happens is that there was a place in the code that was changing which weapon was used, but not the starting ammo.
I check all the places where the secondary weapon is changed, and there is also another instance of it in the multi-code.
Btw, there is one place in the scripting code where the weapon can be changed, but I am unsure if that one should also change the starting ammo, because there is another scripting function for changing starting ammo.

Fix the support ship refilling ships to the wrong secondary capacity

---

test/test_data/mod/future_targetted_version/data/tables/test-mod.tbm

I just tried building 21.0 which is a higher version than the one used
in the test data which broke this test.
This should be a high enough version to not break any time soon...

Increase test engine version to fix 21.0 tests

---

code/ai/aicode.cpp
code/model/modelrender.cpp

Prevent model instances from being overridden when they conflict with the model.  Fixes #3062.
Also fixes another spot that might be a problem.

fix a couple of issues

---

code/scripting/api/objs/ship_bank.cpp

Not tying this to 21.0 in case it somehow ends up being really complicated.  I don't want to hold up the process. This just makes sure that the rearmed ammo is changed when the scripting function in called.
EDIT: FYI, this is a pretty minor bug.

Make sure that scripting changes the starting ammo as well as the weapon

---

code/mission/missionparse.cpp
code/mission/missionparse.h
code/ship/ship.cpp
fred2/missionsave.cpp
fred2/shiptexturesdlg.cpp
qtfred/src/mission/missionsave.cpp

Adds a way for fred to distinguish whether texture replacements are from the table or from the mission file/ship texture dialog, by adding a bool to the struct.
Fixes #3069

Keep fred from adding extra texture replacements to mission file

---

code/math/vecmat.cpp
code/math/vecmat.h

The usage of this third vector is prone to cause some confusion given its vague and brief description. If you think of the rotation of a turret's base (a situation Goober has been in recently) where `v0` is its forward and `v1` is its desired angular position, feeding `uvec` with the turret's own up vector allows you to differentiate between a left or right turn.

Improve comment on vm_vec_delta_ang

---

code/object/collideshipship.cpp

The old version of this function was able to handle a -1 `goal_objnum` which can occasionally happen so the new version should too.

Safety for check_for_docking_collision

---

code/ai/aicode.cpp

If a ship had no primaries it could escape this check, leading to trying to get `Weapons[-1]`. Tested this fix with both ships with 0 and 1 primaries and saw the desired behavior in each.

off-by-one fix in early exit update_aspect_lock_information()

---

code/menuui/techmenu.cpp

This is a safer way of doing a dynamic size for tech entries that fixes a crash involving only the release executables.  As reported on discord.
It replaces a manually created array (if that is the correct name) with a few vectors.

Vectorize tech lists

---

code/ai/aicode.cpp
code/hud/hudlock.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

The previous method only handled ships, even though the target could be a non-ship. This handles all targets properly now, and I also changed its name because "can lock on ship" is pretty vague so I thought it better to be explicit that this is about lock restrictions

Safety for lock restriction handling

---

code/model/model.h
code/model/modelread.cpp
code/ship/shipfx.cpp

It appears that live debris is not supposed to have a parent submodel; see the retail NTF Boadicea.  This removes the parent from any live debris that might have it.
This should fix #3078.

de-parent live debris

---

code/model/modelread.cpp

As described in #3079, the old parsing of fvec and uvec used `strtod` and some POFs rely on this format.  This is a quickfix that uses the new parsing method for only `get_user_vec3d_value`.

interim patch for get_user_vec3d_value

---

code/hud/hudtarget.cpp
code/mission/missionparse.cpp
code/mission/missionparse.h
code/parse/parselo.cpp
code/parse/parselo.h
freespace2/freespace.cpp

For compatibility purposes some mods want alt names to truncate at the hash symbol.  But we can't actually do that at mission load,
since we have to save them again in FRED.  So this PR processes the names just before the mission starts.
To further complicate things, some mods actually want the hash to be displayed.  So this PR introduces the double-hash as an escape sequence for a single hash.

preprocess alt names before mission start

---

code/scripting/api/libs/graphics.cpp

Implements a catch for a -1 `modelnum` that the normal hud bracketing code uses, but the scripted version didn't. Still not great quality of life here, it would be nice if this actually looked at the laser's radii or length or something, but it works without breaking anything and the scripters can always mess with the padding if they need to.
Closes #3091

Fix a crash with scripted targeting brackets

---

code/model/modelrender.cpp

Fixes #3107 There were a few sign issues with the old implementation, and additionally cleaned up the readability of this very ugly bit of code. Works with the problem case, as well as other more complicated pulsing glowpoint set ups like the Orion.

Fix a bug with glowpoint timing

---

code/starfield/starfield.cpp

The background validation checks are somewhat convoluted, and misleading with multiple backgrounds, so this PR disables the standard main-background check if FRED is running.  It then adds a new FRED-specific background check that covers all backgrounds.
Additionally, this PR fixes a bug in an error message in `stars_get_first_valid_background`.
Fixes #3116.

make FRED validate all backgrounds, not just the active one

---

code/cmdline/cmdline.cpp
code/cmdline/cmdline.h

This option was likely part of an attempt to fix multi that never went anywhere. We now have rollback, which is on by default.

Remove Unused ClientDamage Commandline Option

---

freespace2/freespace.cpp

Multiplayer *must not* have its time affected by being in the background, because their clocks will come out of sync and ships from an out of focus multiplayer instance will appear to move in slow motion. This fixes the timing discrepancy by only doing `os_sleep ` for unfocused screens when in single player.
I don't think this is necessary for 21.0, but it could be helpful.

Fix unfocused multi interpolation inaccuracies

---

freespace2/freespace.cpp

Quick tweak for a very minor annoyance.  If we're going to have this debug statement, at least let it be run *after* debug statements are initialized.

Move Standalone Running statement to after the init of Debug Statements

---

code/def_files/data/effects/deferred-f.sdr

Before the fragment shader was calculating attenuation from one end of the beam as a point light, then doing the proper tube lighting distance calculation for culling but using the original attenuation calc for all other lighting. This just recalculates the attenuation after the proper distance is found, which fixes #2920 as well as slash beam lighting issues found while investigating that issue.

Properly recalculate tube light attenuation

---

code/menuui/techmenu.cpp
code/mission/missionbriefcommon.cpp
code/mission/missionbriefcommon.h
code/mission/missionparse.cpp
code/missionui/missionbrief.cpp
code/model/model.h
code/model/modelread.cpp
fred2/briefingeditordlg.cpp

These two situations mostly relied on the obsolete model code which didn't include model instances.  Data for submodel positions and for whether a submodel is blown off are now stored exclusively in model instances, not the model itself.
This fixes #3124.

properly use model instances for tech room and briefing popups

---

code/model/modelread.cpp

Follow-up to #3137.  I missed two important details in the first implementation: the triggered animation needs to be an "initial position" type, and `model_update_instance` needs to be run on all subobjects, not just turrets.
This should really fix #3123.  I still can't see the destroyed collector, but the Rahu no longer flickers when it spins around.

make model_set_up_techroom_instance a bit more robust

---

code/hud/hudconfig.cpp
code/hud/hudconfig.h
code/pilotfile/csg.cpp
code/pilotfile/plr.cpp

* Adds more safety checks for PLR and CSG reading for the HUD_config structure.
* Adds a #define for the HC_color array size
* Doxy's the HUD_config struct
Looking into causes of #3136 revealed the HUD_config struct is somewhat haphazard in initialization.  It makes the assumption that the struct will be properly initialized by a PLR or CSG read, or by creation of a new player.  No where else is the singleton struct init'd, making it a potential issue for data races should anything try to operate on non-init'd data.
@JohnAFernandez Is still looking into the cause of the data corruption due to a bad exit of the HUD Config menu.  This PR doesn't completely fix #3136 but it should at least prevent crashes due to bad data.

More safety checks for the HUD_config struct

---

code/menuui/techmenu.cpp

The tech room loop checked that all the lines could fit in the available screen real estate, but it didn't check to see that the number of lines was less than the array capacity.  Normally this never happened, but certain mods which use smaller fonts will overflow the limit.  This adds a proper bounds check and also increases the bounds so that more of the smaller lines can be used.

fix a rare crash in the tech room

---

code/menuui/techmenu.cpp

Reverts scp-fs2open/fs2open.github.com#3149
Since the original PR was just for a rare crash we do not need to do that before the final release. This will bring the master branch back to the state of RC4.

Revert "fix a rare crash in the tech room"

---

code/ship/ship.cpp

Previous bank also needs to be reset when swapping or this will cause crashes with scripts using it as a conditional.
As much I would love to PR all my features, I do think this should be in stable as JAD currently will very reliably crash on current builds, and I suspect this is also the cause of another similar bug reported in WoD recently.

Fix a bug with previous_bank and ship class swapping

---

code/object/collidedebrisship.cpp
code/object/collidedebrisweapon.cpp
code/weapon/beam.cpp

Collision groups were checked between ships, weapons, and beams, but not debris.  This adds debris.
Also the check for beams vs. ships was a little too far down the function, so I moved it up.

add collision group checks to debris

---

code/parse/sexp.cpp
code/scripting/api/libs/mission.cpp

Now that the hash truncation logic is part of the ship display name, ships created by script or sexp should check this as well.
This properly truncates ship names that have hash symbols if they are created with ship_create.

default display names for script/sexp-created ships

---

code/controlconfig/controlsconfigcommon.cpp

Should fix #3163 until the proper change with the controls code comes through.
In Unicode mode, these are now valid and display correctly, in non-unicode mode, it just displays as a blank / broken char, just like before.
I have no clue what encoding these were before, so I had to guess which characters were actually needed there, but I am reasonably sure to have picked the correct ones, save for polish, especially Arrow Up, which is now called "Kursor Góra". I am fairly sure it's what it was called before as well, but I cannot confirm that this spelling is actually correct.
Shouldn't matter too much anyways, since this will get deleted with controls6 anyways

Fix special char hex codes for utf8

---

code/hud/hudconfig.cpp

In trying to look for the real cause for #3136 , the only other thing we could find besides shoring up the struct and the player file loads is making sure that `HUD_config_inited` is set back to zero when the screen is closed.  The crash is so rare, and the work around in the player file and campaign file load are good enough that we can wait until @z64555's undo system is merged, and we can put that struct under that, in hopes that that fully fixes the issue.

Make sure the Hud_config_inited is reset when the screen is exited.

---

code/weapon/beam.cpp

Fixing tube lighting revealed a bug were the light remained on between the pulses of a anti-fighter beam cycle. This adds a check in  `beam_move_all_post()` to avoid that.
also adds a comment to `beam_type_d_get_status()` about the returns of that function, because I used that here and that comment would have saved me some time had it been there already.

Stop including tube lights between anti-fighter beam pulses

---

code/weapon/beam.cpp

Only useful with "Beams damage weapons", but an important step.

Use armor/damage types for beam-weapon damage

---

code/controlconfig/controlsconfig.cpp
code/controlconfig/controlsconfig.h
code/controlconfig/controlsconfigcommon.cpp
code/gamehelp/gameplayhelp.cpp
code/globalincs/undosys.cpp
code/globalincs/undosys.h
code/mission/missiontraining.cpp
code/pilotfile/pilotfile_convert.h
code/pilotfile/plr_convert.cpp
code/scripting/scripting.cpp
code/source_groups.cmake
test/src/pilotfile/plr.cpp

This PR combines branches `feature/controls`, `feature/controls1`, and `feature.controls2`. This was done because`feature/controls` breaks two features which are fixed in `feature/controls1` and `feature/controls2`, and the three should not be merged in individually.
<hr>
PR #2868 Controls0 - `feature/controls`
This changes the Controls_config array into an SCP_vector to allow scripting to add more controls as they wish, enabling mod devs to create new controls with scripting and not needing hardcode support in the future.  (Custom controls are still a ways off, however)
<hr>
PR #2884 Controls 1 - `feature/controls1`
This re-factors control presets and adds a bunch of features.
* Hardcoded defaults are now a preset.
* Mod devs may override the hardcoded defaults with the …

Controls 0, 1, and 2 - Vectorize Controls_config, Refactor Control Presets, and Use Undosys

---

code/network/stand_gui-unix.cpp

Since the return value of the json library is null in that case it
crashed the server when no value was specified.

Fix crash in server REST API when omitting framecap

---

code/asteroid/asteroid.cpp
code/debris/debris.cpp
code/model/model.h
code/model/modelanim.cpp
code/model/modelcollide.cpp
code/model/modelread.cpp
code/model/modelrender.cpp
code/network/multi_obj.cpp
code/network/multimsgs.cpp
code/object/collideshipship.cpp
code/scripting/api/objs/subsystem.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/shipfx.cpp

This is a rather substantial rewrite/refactor of the submodel rotation code.  Submodel rotation is now tracked via an axis-angle representation, which is used to calculate a matrix to represent the submodel orientation in the model instance.  The axis can be any unit vector, not limited to the standard X, Y, and Z vectors.
The submodel orientation is now used for position calculation in almost every place the submodel angles were previously used.  In conjunction with the simplification of KeldorKatarn's code, this saves a significant number of calculations for every movable submodel in every frame.  Hopefully this should lead to a measurable speedup in both rendering and collision detection.

Allow submodels to rotate around an arbitrary axis

---

code/gamesnd/gamesnd.cpp
code/model/modelread.cpp
code/parse/parselo.cpp
code/parse/parselo.h

One small detail that was overlooked in PR #3021... KeldorKatarn's old code used `strtod` while the new code used `stuff_float`.  This wouldn't be a problem except that a couple MVP models use annoyingly formatted floats like 8.9e-08.  So I decided to convert `stuff_float` to use `strtof` and do a few other minor improvements at the same time.

convert float parsing to use strtof

---

code/mission/missionparse.cpp

Quick hotfix due to two branches being merged that were both compatible with master but not with each other.

fix compilation

---

code/gamesnd/gamesnd.cpp

If a sound entry is left completely blank, literally just
```
+WarmupSound:
```
It will match the first index with an empty sound definition! This is bad.

Don't search for empty sound names

---

code/object/object.cpp
code/object/object_flags.h

This flag is vestigal.  It was likely used in the FS1 codebase and then was not removed by the rushed FS2 multi team.  Whether or not an object uses physics_sim is determined earlier in `multi_oo_is_interp_object()`, and so this flag is never set.  There are only calls for it to be removed.

Remove the Unused Just_updated Flag

---

code/ship/ship.cpp
code/ship/ship.h
code/weapon/trails.cpp
code/weapon/trails.h
code/weapon/weapons.cpp

Adds a field for an exponent to apply to the 0 - 1 alpha progress for non-linear decay.
Also allows texture to stretch by a specified amount rather than 1 full texture per trail segment. Switching `i` for `n` was necessary because `i` is measured from the tip to the tail, and thus the points move along with the trail, `n` are the points that are stable in space which is why they are needed. Before it was 1 texture per segment anyway so it didn't matter which it was.

Non-linear Trail decay and Texture stretch

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aicode.cpp
code/ship/ship.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

This PR provides modders with additional options to alter countermeasure values. Previously, countermeasures had a fixed, hardcoded fire wait time of 333 milliseconds, regardless of what `$Fire Wait:` was specified. Also, the AI would wait a fixed delay between firing of failed countermeasure launches and successful countermeasure launches. For successful launches the AI would double the fire wait. Also, Friendly ships would only use a fixed constant value for countermeasure firing chance, and not the value based on their class specific AI profile.
This PR exposes those values with the following options:
- Add main AI table flag: `$friendly ships use AI profile countermeasure chance:`. This will allow Friendly ships to use their AI class profile countermeasure firing chance instead of the …

Expose Additional Countermeasure Options to Modders

---

code/model/modelread.cpp

Multipart turrets that have no rotation specified in PCS don't have `movement_type` assigned properly within `modelread.cpp`, which eventually leads to a fatal crash. This two line fixe properly specifies the `movement_type` and fixes the crash. Tested and confirmed. Thanks to @Goober5000 for the assistance and troubleshooting.

Fix Bug with Reading Turret Rotation Axes

---

.github/CODEOWNERS
code/controlconfig/controlsconfigcommon.cpp

One of the changes in the Controls 0~2 PR hid the chocolate, which are a number of FSO feature controls that have little or no function with retail data.  While this did tidy up the retail controlsconfig menu, it broke a number of mods that counted on them being there.
So uh, going forward, I'd like to put in a policy in writing somewhere where if a new control can not be used in retail data, it gets default disabled.

Unhide chocolate

---

code/model/model.h
code/model/modelread.cpp

This PR re-implements the look_at feature, which has been broken for many years.  A look-at rotation is a type of intrinsic_rotation, just like dumb-rotations. The same code handles both; the only difference is whether submodel_rotate or submodel_look_at is called to apply the actual movement.
The previous look_at parsing code has been optimized by performing the name-to-submodel resolution when the model is actually parsed, instead of when the first look-at rotation is called.  This avoids the need to store a name in the submodel struct and also avoids cluttering the look_at function.
This PR is essentially bookkeeping, except for the submodel_look_at method.  This method takes advantage of the submodel rotation upgrade and calculates angles in almost the same way as the new turret …

reimplement look_at

---

code/mission/missionparse.cpp
code/parse/sexp.cpp
code/scripting/api/libs/mission.cpp
code/ship/ship.cpp

When looking at a debug log for more than just the particular error/warning, and attempting to narrow down a particular time frame for perhaps when an error may have occurred, there are very few landmarks to help get an idea of where in a mission something happens just through the log. Shader compilations, ani warnings, assorted minor errors, frames "too long" all are pretty useless to determine what the heck is going on in the mission at the time, even if you know what all these are.
This adds what I like to call 'landmark' logging. Merely prints when big|huge ships arrive, depart, or are destroyed providing 'landmarks' for orienting oneself temporally. Shouldn't be too spammy either, even in the worst scenarios several dozen prints will hardly put a dent in it.
For the non-arriving …

Add 'landmark' logging

---

code/controlconfig/controlsconfigcommon.cpp

This causes it to replace the first preset in the list, which more closely approximates the old behavior.

If the first #ControlConfigOverride isn't named, use "default".

---

code/cutscene/ffmpeg/FFMPEGDecoder.cpp
code/localization/localize.cpp
code/localization/localize.h
code/scripting/api/libs/base.cpp

This is a follow-up to #2390.  Retail used a weird hybrid approach where internal strings were translated but external strings were not.  This restores that behavior by adding another language, LCL_RETAIL_HYBRID, which is the default.  The game can still be run in completely untranslated or completely translated mode.
All three modes have been tested and translate strings, or not, as expected.  The `$Use tabled strings for the default language:` flag has also been tested and still works.

restore retail behavior of XSTR

---

code/weapon/beam.cpp
code/weapon/beam.h

This way `$Collision Radius Override:` can also be used for beam width if `+BeamWidth:` is not specified. For compatibility purposes `+BeamWidth:` is used for *both* if specified, the widest section is the fallback for both.

Split beam width for collision purposes and lighting purposes

---

code/ai/aicode.cpp

To determine when a waypoint is complete it compares the distance to the goal versus the distance it will travel this frame (plus some padding). The latter is estimated as the difference between `last_pos` and `pos`, due to the AI reordering with FIT (framerate independent turnrate) however those points will straddle any SEXP `set-object-position`s where before it would not, causing it to erroneously satisfy this condition if the distance moved was at least half the distance to the goal. 
Speed x frametime gives a more consistent estimate of the frame's travel in all scenarios.
Shoutout to Phantom Hoover for hunting this down!

Fix for waypoint completion with FIT

---

fred2/sexp_tree.cpp

The defensive coding in #3191 against illegal cut/delete operations was a little too defensive.  This properly allows deletion of events when necessary, and it still guards against a Cut operation being improperly called due to a shortcut key press.
Fixes #3216.

fix event node deletion behavior

---

fred2/eventeditor.cpp
fred2/eventeditor.h

Restores the MFC functions that were taken out in #3073.  These functions appeared redundant, but they were actually necessary to intercept the MFC handling of Enter and Escape.  In addition to fixing that behavior, this PR also adds some clarifying comments and renames some functions to prevent confusion.

fix event editor closing on key press

---

fred2/fredrender.cpp
fred2/management.cpp

This changes FRED to properly initialize a model instance on ship creation and also use that instance when rendering the ship.  This prevents destroyed submodels from appearing.  Fixes #3212.

add model instance support to FRED rendering

---

code/cfile/cfile.cpp
code/cutscene/ffmpeg/FFMPEGDecoder.cpp
code/globalincs/systemvars.cpp
code/globalincs/vmallocator.h
code/hud/hudwingmanstatus.cpp
code/io/joy-sdl.cpp
code/menuui/readyroom.cpp
code/mission/missioncampaign.cpp
code/mission/missionload.cpp
code/mod_table/mod_table.cpp
code/model/modelread.cpp
code/network/multi_data.cpp
code/network/multiutil.cpp
code/parse/parselo.cpp
code/parse/sexp/LuaSEXP.cpp
code/scripting/lua.cpp
code/utils/strings.h
fred2/voiceactingmanager.cpp
tools/embedfile/embedfile.cpp

This refactors the tolower/toupper code to use standards-conformant logic, and also adds some helpful utility functions.  Regular tolower/toupper must be supplied a value that can be represented as `unsigned char`, but the std:: functions are a bit more robust.
~~This is in draft status until #3223 is merged, as it depends on that.~~

additional case functions and checks

---

code/parse/sexp.cpp

This is a follow-up to #2687.  The final implementation of evaluateNumericSEXP different from the testing implementation in a small but crucial way that prevented it from actually working.  Since it used `eval_num`, it didn't evaluate the specified SEXP node but rather the CAR (first element) of the node list.  This fixes that by putting the node in a temporary SEXP list so that `eval_num` will look in the right place.

fix mn.evaluateNumericSEXP

---

.github/workflows/standalone-image-workflow.yaml

Docker Hub is going into a weird direction with their rate limits and
the GitHub Container Registry is better in that regard.
Old images will stay in Docker Hub for the time being though.

Store standalone image on GitHub

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
.github/workflows/build-test.yaml

The default Python version appears to be too recent so let's try to have
this action use the python package that is installed in our build image.

Try to fix linux nightly builds

---

code/mission/missionbriefcommon.cpp
code/mission/missionbriefcommon.h
code/species_defs/species_defs.cpp
code/species_defs/species_defs.h
fred2/management.cpp
freespace2/freespace.cpp
qtfred/src/mission/management.cpp

Adds modular table support for icons.tbl, with xxx-ico.tbm. icons.tbl can use either the 'old style' or 'new style' (explicit $species and $icon type) definitions, but .tbms must be done in the new style.
Additionally adds '$Borrows Briefing Icons from:' to species, to simply copy another species' icons. Unfortunately, because this is done *after* modular table parsing, this will override modular tables and thus any species icons that were coped from another cannot be modified through modular tables. This is unideal, but if this copying is done before modular tables, not all icons may even be defined yet, and also changes made to a 'lender' species icons will not propagate to its associated 'borrower' species (although this may be desirable).
A more complex form of parsing would need to …

Overhaul briefing icon parsing

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
.github/workflows/build-test.yaml
.github/workflows/pr-workflow.yaml

For some reason the last update of the PR pipeline did not update the
other workflows as well so we had some minor inconsistencies.
This should hopefully fix the nightly build issues for real this time.

Update Linux build image and make consistent

---

code/def_files/data/effects/deferred-f.sdr
code/graphics/opengl/gropengldeferred.cpp

Implements #3161 / fixes #3146. Extends tube light cylinder volumes to cover the end cap sphere volumes and removes those spheres. Before and after test videos available at https://www.youtube.com/watch?v=G5pXm7Jv8Us and https://www.youtube.com/watch?v=gC84qUBXJq8, but leaving in draft till I get some more general play time on the modified build to make sure no weird edge cases crop up

Cylinder only tube lights

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
.github/workflows/build-test.yaml
.github/workflows/pr-workflow.yaml

There was another break in that package so this should hopefully make
our builds more stable.

Force aqt to a known good version

---

code/globalincs/vmallocator.h

On some setups the hierarchy of #include files doesn't catch an `<iterator>`, so #include it explicitly.
(This fixes the "`std::back_inserter` not found" error on MSVC 2015.)

add missing #include

---

code/menuui/mainhallmenu.cpp

With modular tables, we might have modified an entry in the middle of the vector, in which case the next index would be an existing main hall.  If the next modular table then created a brand new main hall, it would overwrite that entry.  This makes sure the code always assumes the next main hall will come at the end of the list.

when we're finished parsing a main hall, the next main hall should be a new one

---

code/math/floating.cpp
code/math/floating.h
code/ship/ship.cpp
code/ship/ship.h
code/weapon/swarm.cpp
code/weapon/swarm.h
code/weapon/weapon.h
code/weapon/weapons.cpp

It was getting a bit old and crusty in swarm.cpp
Swarm missiles were doing *a lot* of bending over backwards and complicated overhead, fucking around with these 'paths' for the swarm missile (even going so far as to store state on the ship that fired it?? `next_swarm_path`) the whole purpose of which is to ensure that the swarm missiles choose different direction to 'zig' in, so they don't all follow the same perfect path which would look weird. What they did was massively overengineered for something that can be easily solved with the right RNG function.
`golden_ratio_rand()`, as the comment describes, has all the benefits of rng while avoiding runs and clumps, subsequent calls to the function will evenly spread themselves around the 0 - 1 range, and is perfectly suited for this purpose. …

Give swarm missile handling a well-deserved makeover

---

code/actions/ActionDefinitionManager.cpp
code/actions/ActionDefinitionManager.h
code/actions/expression/FunctionManager.cpp

Visual Studio has issues in earlier versions where it does not properly
support returning a type that has a deleted copy operator/constructor.
This works around that by checking for that error with CMake and
applying a workaround if that check fails.

Add a CMake platform check for proper non-copyable type support

---

code/scripting/api/objs/audio_stream.cpp
code/sound/audiostr.cpp

Addressing my issue #3225, I'm setting sane values found in other
parts of the sound system at stream creation, to be used or overwritten later.
Also fixed a potential leak of stream slots and deduplicated some code.

Set default volume on audiostream creation

---

code/scripting/api/objs/file.cpp

Previous message was cryptic, and since we are sure that the handle is invalid when it get's destructed (as it's out of scope in lua), we can just close the file then.
Still warn the user for the sake of best practices.

Changed File not closed error to a warning and automatic file close

---

code/weapon/beam.cpp
code/weapon/beam.h
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

To explain what this does:
A beam has sections that are translated over time according to the +Translation property of the sections of a beam.
This translation happens globally for all beams, and independently of if they are active or not.
This means, that the beam, when started, does not always look the same as the translation may be at a different point.
The new flag allows to make this more consistent, by tracking a beams translation offset (and resetting it to 0 before it gets rendered again). This allows for consistent beam appearances.
Usually, this is not a problem with continuous beams, but when using beams with projectile-like appearance like Talhydras did, then this flag allows for consistency in the moment you start up the beam.

Add flag for beams to track uoffset individually

---

code/parse/sexp.cpp
code/scripting/api/objs/ship.cpp

1) The ship-vanish SEXP (and script function) was already multiplayer-ready
2) The is-ship-visible SEXP was enhanced to add a second argument, which defaults to the player's ship in single-player mode
And this adds a few useful Asserts to the caching functions as well.

allow two SEXPs to be used in multiplayer that previously couldn't be

---

code/hud/hudtargetbox.cpp

The english "Impact:" is translateable for targetable bombs, but not for Asteroids in escort missions through asteroid fields. This PR fixes that. Both "Impact:" entries are now translateable through the same string in strings.tbl.

Translateable Asteroid Impact Time

---

code/hud/hudbrackets.cpp
code/hud/hudtargetbox.cpp

Never noticed this, as Asteroid translates to Asteroid in German 😆.
However after i switched to another language i found out, that the English name is used in the target monitor aswell in the target brackets.
This applies to the generated Asteroids you can target in Asteroid Fields, which is widely used in any kind of Escort Missions through them.
So this is actually a follow up to #3272.
This PR change the Asteroid's name to a translateable one by the strings.tbl.
I decided to use the already established ID 431, as that one is used for the displayed name after you clicked on the Asteroid Field icon image in mission briefings.
I can not think of a scenario, where this name should be any different.

Translateable Asteroid Name in Asteroid Fields

---

code/weapon/beam.cpp

This improves PR #3257 in two ways:
1) ~~If a beam has a `u_offset_local`, it will no longer step on the global `u_offset` every time it's fired~~
2) The frametime is updated after the beam fires, not before (so that the first frame will always be at offset zero)

addendum to u_offset

---

code/ai/aiturret.cpp
code/model/model.h
code/model/model_flags.h
code/model/modelread.cpp
code/scripting/api/objs/subsystem.cpp
code/ship/ship.cpp
code/ship/ship.h
code/weapon/beam.cpp

The code always assumed that turrets were part of a fixed reference frame with respect to the main model.  This updates the relevant turret calculation code (mainly FOV and turret normals) so that turrets now use the appropriate submodel functions.  As a result, turrets now work on movable submodels.
Note that most of the `turret_matrix` code has been ripped out because it assumes a fixed reference frame.  This isn't a problem because most of the code can be easily converted to use `turret_norm` via the submodel functions.  The only exception is the `Turret_alt_math` flag, whose code is rather inscrutable.  For those cases, I just regenerated a new turret matrix on the fly.  In the future, someone who is more familiar with that code should rewrite it to use `turret_norm`.

Turrets on movable submodels

---

code/nebula/neb.cpp
code/nebula/neb.h
freespace2/freespace.cpp

As part of a collab with @Goober5000 this is just the engine side of the changes, FRED will need to be updated at some point to allow setting of more than the first 6 without manually editing the mission file. The currently used methods for poof assignment uses a bitfield stored in an `int`, so we have 26 bits lying around that can be used without any significant data structure changes. 
Also comes with support for 0 (or not max) poofs, previously not possible, and a less confusing random poof picker (the assertion added should always be true because `neb2_render_poofs()` is the only thing that calls `neb2_get_bitmap()`.

Increase max nebula poofs to 32

---

code/parse/sexp.cpp

While skimming the differencs in @jg18's branch of PR #3253...
https://github.com/jg18/fs2open.github.com/tree/feature/sexp-containers-revised
...I noticed a TODO that is almost certainly a genuine bugfix.  As such, it deserves its own PR.  The line in question was last modified in 2012 by @Karajorma, and the bugfix should test for the special-arg in the entire actions tree rather than just the first action.

add small fix from SEXP containers PR

---

code/ai/aiturret.cpp
code/asteroid/asteroid.cpp
code/scripting/api/objs/subsystem.cpp
code/ship/ship.h

This correctly calculates the turret position from the center (zero position) of its submodel instead of using the offset from the main model.
This patches a few more parts of the code and also adds a missing locale argument.
Bugfix and follow-up to #3277.

a few turret fixes

---

code/asteroid/asteroid.cpp

Just like the `std::toupper` and `std::tolower` functions (see PR #3226), `std::isdigit` is designed to work with regular `char`, not `unsigned char`.
This fixes #3282.

fix character type for isdigit

---

code/mission/missionparse.cpp
code/parse/parselo.cpp
code/parse/parselo.h
fred2/eventeditor.cpp

Make some improvements to the annotation code and the parsing code:
1) A single plus sign or single minus sign is not a number, and this is what was causing the parser to treat the + on the following line as another number in the Path list.  This is the major fix for #3267.
2) If there is an unexpected character after a number, the number should be considered a bad token, versus just reading as much of the number as we can and considering the result valid.  This is a partial fix for #3265.
3) If the annotation contains unmodified information for a certain value (such as background color), don't render the unmodified values.
4) There are also a few minor fixes here, such as checking for all three possible annotation strings and slightly cleaning up the reporting of parse errors.

Various annotation fixes

---

code/def_files/data/effects/fog-f.sdr

Reverts #2222 and fixes the comment, it was in fact the *comment* that was in error, not the code. `depth_normalized` needs to be [-1, 1] that's what makes `view_depth` right below it accurately map to ingame meters.

Fix for nebula fogging distance

---

code/ship/ship.cpp

The `ship_info` parts of `alpha_decay_exponent` got missed.

Properly initialize trail alpha exponents for afterburner trails

---

code/ai/aicode.cpp
code/physics/physics.cpp

AI will erroneously overwrite turns from `set-object-facing`, so it should see if `ai_desired_orient` is already set (physics will wipe it out when it acts on it) and if so, don't overwrite it, the SEXP takes priority.
Sadly this means physics can't really tell if something is 'spinning too fast', the SEXP could be telling it to go way faster than normal. This isn't a huge loss, that spinning too fast stuff was mostly just some defense against physics bugs or degenerate cases to try and slow it down in a reasonable time, but this should be very rare.

Bugfix for FIT with set-object-facing

---

code/ship/ship.cpp

Basically the same problem as #3255. I've run out of excuses, but I ran through weapons, afterburner trails and contrails with and without the new fields and everything seems to be set properly.

Peoperly initialize alpha decay exponent for contrails

---

fred2/shipeditordlg.cpp

This prevents the message from firing if the wing index is -1 which would cause an array underflow.  Fixes #3280.

simple hotkey range check

---

code/parse/sexp.cpp

When various SEXP functions related to ammo were consolidated back in June (in commit 54409ec92887d2e6db92450a2ccf78d8fc90ff2d, PR #2480), certain safety catches meant to avoid having too much ammo or the wrong ammo capacity after changing weapons were lost. This commit adds code that should be functionally equivalent.

Fix ammo safety regressions.

---

fred2/fred.rc

The Space Bar is a valid shortcut, so indicate as such.  Fixes #3289.

add text to context popup

---

code/ai/aiturret.cpp
code/network/multimsgs.cpp
code/ship/ship.cpp
code/weapon/flak.cpp

This should be a perfectly fine thing to do, and only complains because flak muzzle flashes have a pointless wrapper function for the normal muzzle flash function that exists solely to complain about weapons being not flak. 
Closes #2415

Fix assert with combining flak and non-flak using substitute

---

code/fireball/fireballs.cpp
code/fireball/fireballs.h
code/object/object.cpp
code/scripting/api/libs/mission.cpp
code/scripting/api/objs/fireball.cpp

Vectorizes the fireball limit.  Thanks to @asarium for some great suggestions.  In draft until we get a proper stress test from @EatThePath 
For #2945

Remove the fireball limit

---

code/network/multi.cpp
code/network/multi.h
code/network/multi_obj.cpp
code/network/multi_obj.h
code/network/multi_observer.cpp
code/network/multiui.cpp
code/network/multiutil.cpp
code/object/collideshipship.cpp

Often in Multi, a client colliding with another ship, especially a capship, will result in instant death.  By limiting the maximum frequency of damage to client ships from ship-ship collisions to once every .2 seconds, instant death can be avoided in most cases.
Before
https://youtu.be/bUfe_dEUSeE
After
https://youtu.be/tFzUu3WlXxc

Limit instances of Client Collisions to Avoid Instant Death

---

code/mod_table/mod_table.cpp
code/mod_table/mod_table.h
code/playerman/playercontrol.cpp

If the mod has "$Player starts in Third Person View by Default: TRUE" in their game_settings.tbl or any such .tbm, missions will automatically put the player in the third person chase view. This was requested as a FR by Darius on January 17th.
This will NOT stop the player from going back into first person by pressing the key for it.
closes #3152

Adding "Start missions in Chase View by default" flag in game_settings.tbl

---

code/math/vecmat.cpp
code/math/vecmat.h
code/scripting/api/objs/vecmath.cpp
code/weapon/beam.cpp
code/weapon/trails.cpp

Randomly getting a point on a circle/sphere edge and scaling inward by `frand()` is *not* a uniform distribution, as the comments say, this will bias the distribution towards the center, so introduce a factor to combat this. The only thing that should be noticeably affected that isn't just visual is beam aim 'jitter', since this is retail an optional parameter is added to to maintain this 'bias' (and also for trails because they look better that way)
As an aside, randomizing a vector's coordinates and normalizing is *also* not a uniform distribution over a spherical surface (ironically that method was introduced in the same PR that introduced the proper method for random_cone, which has been used for circle and sphere now).

Fix probability distribution of vm_vec_random_in_circle/sphere

---

code/mission/mission_flags.h
code/playerman/playercontrol.cpp
fred2/fred.rc
fred2/missionnotesdlg.cpp
fred2/missionnotesdlg.h
fred2/resource.h
qtfred/src/ui/dialogs/MissionSpecDialog.cpp
qtfred/ui/MissionSpecDialog.ui

Follow-up to #3305.  Some mods may want one or two missions to start in chase view without having every single mission default to chase view.  So this adds a mission flag (with FRED and qtFRED support) that will enable this on a per-mission basis.

add mission flag for starting missions in chase view

---

freespace2/freespace.cpp

This properly clears ships if you are leaving the sync state for any other state besides the gameplay state.
Previously, if the player left this state and then started another game, the old ships would still be present and could causes nan crashes.

Make sure objects and ships get cleared if leaving mission sync

---

code/weapon/weapon.h
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

Adds "pierce ship" as a weapon info flag, which will not remove a weapon on collision with an object, and rather allow it to penetrate and continue flying until it's lifetime is 0, detonated by a player, or shot down.
Regarding possible particle spew upon leaving a pierced ship:
It seems insufficient to just flip the weapon direction for the collision checks to deal with backface collisions as soon as the weapon entered a ship. Larger changes would be necessary to properly check for backface collisions which are, for now, out of scope.

Add pierce ship weapon flag

---

code/parse/parselo.cpp
code/parse/parselo.h
code/utils/unicode.cpp
code/utils/unicode.h

This will fix #2994.
It consist of two parts, one two helper functions to convert strings of a known encoding into the encoding currently used by FSO. Even if we wanted to hardcode the alterative unicode match strings as opposed as determining them at runtime, we _will_ need these functions anyway for the controls6, as there the local-specific keynames by SDL are always in UTF-8 and need to be converted, which is why I would advocate for adding these functions anyways.
Part two is the actual matching. This is... kinda ugly here. Especially with the offset where the changes need to be made changing depending on the game being in unicode mode or not. At least it works, and will now start both in normal mode and unicode mode when not set to english. Though I am open to suggestions, in case …

Fix strings.tbl in unicode mode

---

code/mission/missionparse.cpp
code/network/multi.cpp
code/network/multi.h
code/network/multimsgs.cpp
code/network/multimsgs.h
code/network/multiutil.cpp
code/object/collideweaponweapon.cpp
code/scripting/api/objs/weapon.cpp
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

This PR contains all the changes that require a multi bump for 21_2:
- Upgrade velocity compression in OO packet, which prevents some of the back and forth shaking you will see as a client at the cost of slightly more bandwidth.
- Fixes the support ship bug by properly setting net singatures for ships in wings so that there's no overlap for the support ship and the last ship in the wing.
- Allows the client to shoot down bombs.  Previously bombs would be in wildly different positions on server and client.
- Fix a bug in the packer function for desired velocity and desired rotational velocity that kept the correct speed from displaying.
Closes #3031 
Closes #3170 
Does not work for all of 3042 --- Further testing reveals more interpolation problems even after making this change. 
Closes …

Multi 21 2 bump requiring changes

---

code/ship/ship.cpp
code/ship/ship_flags.h
code/ship/shiphit.cpp

Previously, the `no impact debris` flag was only utilized for subsystems. This PR adds that flag for the whole ship. It also will disable debris spew for subsystems when the ship flag is enabled.

Add `no impact debris` for whole ship

---

code/model/model.h
code/model/modelcollide.cpp
code/model/modelread.cpp
code/model/modelsinc.h

Changed SLDC system to SLC2, this replaced the char at the beginning of the node for an int in order for the tree to be aligned.
Added BSP_Defpoints data alignment and SLDC to SLC2 conversion for pof version < 2118.

SLC2, BSP alignment and POF version 2118 support

---

code/cfile/cfilecompression.cpp

This is a small bug that unfortunately i only managed to find today, since it does not affects functionality. Old code was reserving way too much memory to store the offset list. so i removed the max blocks calculation and just used the number of offsets*sizeof(int).
To compasate the lost Assertion at release builds, i moved the assertion checking the number of offsets that is read from file out of the NDEBUG.

fix over alloc to store lz4 offsets

---

freespace2/freespace.cpp

Because GS_STATE_MULTI_MISSION_SYNC is actually shared for a few different multi screens, we do actually need to check if we are going to the PXO or Multi Join screens.

Check for these states

---

code/hud/hudreticle.cpp

Most gauges in hud_gauges.tbl will display a Warning if they can't be loaded, but the reticle is an exception - it only prints a log statement.  This PR changes it to be consistent with the rest of the HUD gauges.
Fixes #3090.

change reticle log statements to warnings

---

code/ai/aiturret.cpp
code/ship/ship.h

This flag is useless, it attempts to hold on to targets that have gone out of fov by getting the gun as close as possible and firing in that direction, but that's not a great idea since that point could very well not be aiming at the ship at all, and furthermore the turret is constantly re-targeting either new subsystems on it's target or new targets in its fov, which this edge checks system doesn't touch anyway, so that work will get clobbered in moments after losing fov in the 'standard' way. 
Rather rolling a new function that isn't called in the right places, this flag will have another branch in `object_in_turret_fov`, the real function that determines whether to acquire a new target, and that's the function that is too conservative with regards to the target's size and proximity, …

Fix Fov_edge_checks

---

code/io/keycontrol.cpp
code/nebula/neb.cpp
code/nebula/neb.h

After loading the nebula poofs, resize the break_x and break_y values so they are equal to the largest poof bitmap in use.
Also reduce the break alpha value by 90% for all detail levels.
This closes #3250

Make nebula poof detail settings partially dynamic

---

code/network/multi_obj.cpp

I don't know when this was introduced but the bug is extremely obvious once someone hit the crash.  It should just be using the timestamp that the packet was received, not trying to put that timestamp into a vector whose index is server frame numbers.

Fix a rare but eventual crash in the interpolation code.

---

code/localization/localize.cpp

The "No XSTR entry in strings.tbl for index %d" message was previously printed to the log every time the string was accessed, which for commonly-used strings will clutter up the log.  This makes the message only appear once per missing index.

log missing XSTR strings only once

---

freespace2/freespace.cpp

Especially on 1080p screens, the frametime profile trace often runs off the bottom of the screen, making it useless for performance diagnostics. Splitting it is a simple workaround and should work fine for a debug feature.

Split frame profile trace into two onscreen columns if needed

---

code/ai/aibig.cpp

Fixes a typo from #3247. It's absence completely obliterates the behavior of this function.
Fixes #3343

My kingdom for a semicolon!

---

fred2/eventeditor.cpp
fred2/eventeditor.h

Instead of saving based on the m_cur_msg index, which may have been reset to -1, save on the most recent positive index.  This should keep track of modified text and dropdowns even when m_cur_msg is set to -1 when the message list loses focus.
Fixes #3308.

modify saving of edited messages

---

code/graphics/2d.cpp

So #3007 is a larger bug than just trying to access the player's target.  It happens when using a combination of the use of `$State: GS_STATE_GAME_PLAY` and `$On frame:` 
The real problem is that the game state is not changed from `GS_STATE_GAME_PLAY` during the mission load when restarting the mission.  So the script thinks it's in the mission, tries to access the target and then crashes.  But this won't be the only bug.  Any script that tries to access data on Frame will run into possible problems on mission restart.
This change checks that if we are currently in `GS_STATE_GAME_PLAY` that `Game_Mode` is set to `GM_IN_MISSION`.
It might be a slightly complicated way to do it, but it may be the only way possible without making a new game state for mission reload and dealing with all the …

Add a safety check to the $On Frame: Hook

---

code/ship/ship.cpp

The `+Targeted by 'Huge' weapons and Ignored by 'small only' weapons:` flag took over the the job of the simple `is_big_or huge()` hardcoded class flag when it comes to targeting for those weapons, and suitable defaults were added to the built-in objecttypes.tbl. Unfortunately, since this defaults to false otherwise, if a mod had their own objecttypes.tbl and used the same name as a hardcoded big class they before would've benefited from this hardcoded behavior, but now must include this new flag in order to maintain targeting behavior, breaking backwards compatability.
This checks to see if it is a .tbl and the same name as a hardcoded big|huge class and if so, sets the matching default. I'm unhappy with this solution, because its requires more references to the hardcoded classes, and …

Fix regression with huge/small only targeting

---

code/scripting/scripting.cpp
code/tracing/categories.cpp
code/tracing/categories.h

This will separate out Lua scripting hooks from the rest of our performance traces, allowing us to separate time spent in engine code and in modder-supplied scripts.

Add profiling trace for scripting hooks

---

code/fireball/fireballs.cpp

The wiki claims this is the case, but it isn't, but it should be. Fireballs without at least 1 LOD will not function, even if the rest of their data is good.

Make fireballs default to 1 LOD

---

freespace2/freespace.cpp

Fixes a bug recently introduced where the main hall ambient sounds and music aren't stopped after pre-briefing multi sync.

fix main hall sounds/music not getting stopped on multi clients

---

code/mission/missionparse.cpp
code/parse/parselo.cpp
code/parse/parselo.h
code/parse/sexp.cpp

This moves the ## to # escape sequence logic from `mission_process_alt_types` to its own function where it can be used elsewhere (such as for ship class and weapon class display names that need to do the same thing).  Also, this introduces a !! escape sequence for exclamation points that is needed for exclamation points to be used in scripts, as @naomimyselfandi pointed out.

make double-character consolidation reusable, and reuse it

---

freespace2/freespace.cpp

Address various issues that cropped up when the various pre-briefing states were fixed for multi. This should fix the various places where `common_select_close()` was getting called when it shouldn't, or not getting called at all.

Only close common_select when we should

---

code/ai/aiturret.cpp
code/model/model.h
code/model/modelread.cpp
code/scripting/api/objs/subsystem.cpp

According to some profiling done by @EatThePath this `ship_get_subsys` in `model_rotate_gun` is a surprisingly large expense. Among its users `model_rotate_gun` is definitely the odd man out, all the others are dealing with external user-provided strings, while the callers of `model_rotate_gun` in all cases already have the `ship_subsys` handy anyway, so the function is modified to take it as its argument instead of the `model_subsystem`.

Remove unecessary ship_get_subsys in model_rotate_gun

---

code/mission/missionparse.cpp
code/parse/parselo.cpp

We need to set bit flags to zero before stuffing.
fixes #3355

Fix event parsing by setting flags to zero before loading.

---

code/debris/debris.cpp

Generic debris used to be culled only based on a factor of the source ship's size, but I was only considering explosion debris which would be presumably sized appropriately to the ship in question. Regular impact debris is still always small so failing to cull it on a destroyer adds up extremely quickly.
This checks first for the builtin debris which is always small with the original 200m check, and then later does an actual debris size proportional cull once its radius is known. Doing two culls based on distance is kind awkward but i figured doing the first quick cull was better since that was the vastly more common scenario.
Closes #3368

Properly cull generic debris

---

fred2/fredview.cpp
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

They are currently allowed in the game, but not being allowed in Fred was an oversight of mine.
Tested and it works as expected.  A TVT mission will also load if it has a command brief defined, even though TVT will not show the command brief in-game.
As it's already allowed in-game, this should probably get into stable.

Allow Fred to Edit and Allow Command briefs in FRED

---

code/parse/sexp.cpp

Since the shield strength of the ships is being copied, you need to copy the special shield hitpoints, too, just like for hull.
Fixes #3374

Make Sure Special Shield Hitpoint Max Gets Transferred

---

code/parse/sexp.cpp

There were a few assertions in the SEXP code that would trip if an invalid variable name were specified in a SEXP, but nothing that actually stopped a Release build from performing an out-of-bounds array access if someone made a typo in notepad. Since, as far as I could tell, everything should go through `get_sexp_text_for_variable()` first, I changed its `Assert()` into an `Error()` that should hopefully ensure that we avoid ever doing anything with `Sexp_variables[-1]`.

Make an invalid variable name throw an error.

---

code/network/multi_respawn.cpp

If the client tries to respawn a player when the server is trying to end the game it will lead to a crash on the client side.  This sets the client's game to the correct state when an end game packet is received and adds extra checks before respawning.
I am hoping for a little more testing before this is merged.

Make sure the Netgame state is set to prevent a crash

---

code/ship/ship.cpp
code/weapon/weapons.cpp

This was an oversight from the last changing relating to alt names. This will apply the same hash stripping rules to display/alt names as are applied to normal ship names when generating a display name automatically.

Strip hashes from explicitly defined display names in tables.

---

code/network/multi_obj.cpp

Not all ships in the ships array are ships (if they were turned into observers), so we need to explicitly check that they are ships.  This fixes a crash where a player that has become an observer because of number of deaths does not crash the server when the server attempts rollback, because a weapon has taken the object slot that the player's ship used to have.

Explicitly check that the type is a ship.

---

fred2/fredrender.cpp

Could be because of variable overflows or from `thistime` somehow being much smaller than `lasttime`.
Hard to find the root cause, but manually setting the memory to bad values will no longer cause the freezing with this patch since we are explicitly checking for a negative value that is far too negative. 
Closes #3155

Keep Fred from freezing

---

code/parse/sexp.cpp

To be more user-friendly, and to accommodate buggy retail missions, make the one-argument version of `is-ship-visible` default to the first player in multiplayer mode..  Also, change the warning to an mprintf.

make is-ship-visible default to the first player

---

code/graphics/generic.cpp

This fixes #3399.
The problem is, that due to the exception for playing direction in APNG's made for first frames of backwards-playing doors ([code/graphics/generic.cpp#L493](https://github.com/BMagnu/fs2open.github.com/blob/79f5eda0d62343b823544a6cc5b13dd023708717/code/graphics/generic.cpp#L493)), the ``ga->current_frame`` got desynchronized from the actual ``framecount ga->png.anim->current_frame``.
This also allowed it to sometimes sink to -1 (which caused the sound crash, as that calculated a volume of over 100% with that), as well as caused it to never reach the end in a way that the animation system would count it as finished to start a new item from the same group.
Due to the early exit in the actual render function (that doesn't render the frame when the current frame and the …

Fix APNG Animation Framecounter

---

code/ship/shiphit.cpp

While there's code to avoid accessing the parent object of a parentless beam, there's no equivalent code to avoid accessing the parent object of a parentless weapon. This fixes this inconsistency.

Avoid out-of-bounds array access if killed by a parentless weapon.

---

code/graphics/generic.cpp

Reverts scp-fs2open/fs2open.github.com#3400, which introduces new bugs without quite fixing the issue it was supposed to solve. A more comprehensive fix for the original issue will have to wait until after 21.2.

Revert "Fix APNG Animation Framecounter"

---

code/parse/parselo.cpp

#3271 changed the logic of `stuff_token_list()` in such a way that the supplied index being used to access an array was no longer skipped if it was invalid; naturally, this means that this warning was now being inevitably followed up by an out-of-bounds array access. Adding a `!skip_this_entry` check should hopefully fix the problem while still allowing the loadout count parsing code below it to run, which was presumably the reason the `continue` statement was replaced with the `skip_this_entry` variable in the first place. Fixes #3405.

Avoid negative lookup when parsing loadouts.

---

code/missionui/missionbrief.cpp
code/missionui/missiondebrief.cpp

As reported by @Karajorma in https://www.hard-light.net/forums/index.php?topic=97412.msg1909252#msg1909252 text replacement for variables in briefings/debriefings doesn't take into account the effects of evaluating SEXPs used to determine whether to include the  briefing/debriefing stage.
This PR moves text replacement for variables so that it's applied on a per-stage basis and only if the stage is selected for inclusion (i.e., if its SEXP formula evaluates to true).
**Gotchas**:
1. Text replacement in multi assumes that variables and variable operations (e.g., modify) are replicated on all clients. The same will apply to SEXP containers, once those are added.
2. Debriefing SEXPs are unavoidably evaluated server-side multiple times: once for *every* team in `debrief_multi_server_stuff()`, …

Fix variable replacement in text in briefings and debriefings

---

fred2/weaponeditordlg.cpp

If the secondary weapon selection is None, the ammo count will be based on an incorrect weapon.  So guard against that.
Fixes #3393.

handle weapon "None" properly

---

code/parse/sexp.cpp

If the `for-players` collection has no valid arguments, don't short-circuit, just to be on the safe side.
Don't short-circuit at all for the `for-ship-*` sexps, because ships can arrive and depart.

tweak short-circuiting on the for-* sexps

---

code/asteroid/asteroid.cpp
code/debris/debris.cpp
code/fireball/fireballs.cpp
code/object/objcollide.cpp
code/object/object.cpp
code/object/object.h
code/weapon/beam.cpp
code/weapon/shockwave.cpp
code/weapon/weapons.cpp

This does three things.  1) It changes an INT3 and an Assertion that can be triggered if there are not enough object slots to debug log statements. 2) It removes some of the problematic logic that was causing crashes when trying to clear weapons when short on slots.  Previously, if none of the "safe" weapons could be removed, then it would resort to the oldest weapon, which could be colliding!  (this crash started my 4 hour search two nights ago)  3) It allows object creation to fail on purpose for certain types of objects like fireballs and asteroids instead of forcing weapons to be removed for them, if there are only 10 object slots remaining.
These changes are no longer urgent due to @Baezon's changes to how debris is being culled.  But they are still important changes until if/when …

Add guardrails to object cleanup during object creation

---

code/graphics/opengl/gropenglpostprocessing.cpp
code/math/floating.cpp
code/math/floating.h
code/math/vecmat.cpp
code/math/vecmat.h
code/model/modelread.cpp
code/radar/radar.cpp
code/radar/radarorb.cpp
code/weapon/swarm.cpp

Goober added `vm_vec_delta_ang_norm_safe` to clamp the input of an `acosf` because floating point inaccuracy can sometimes produce numbers slightly greater than 1 or less than 1. After I ran into the exact same problem in `vm_vec_interp_constant` I think it's clear this is not specific to that particular usage, and instead all the `asinf`s and `acosf`s should be sanitized when used.
This also removes the occasional inconsistent bounds checking a few of their callers already did, so it can be made consistent for all usages.

Turn all asinf and acosf into safe versions

---

code/network/multi_fstracker.cpp
code/network/multiutil.cpp
code/popup/popup.cpp
code/popup/popup.h

A new type of conditional popup which can be created, run multiple test conditions, then close. This provides an alternative to `popup_till_condition()` which simply creates a popup, runs a single test condition, then closes.
Fixes the dreaded popup sounds during mission and table validation in multi.

add new popup type to handle mission/table validation

---

qtfred/source_groups.cmake
qtfred/src/CheckedDataListModel.h

In preparation for the CampaignEditor, I'm introducing a templated ListModel to hold rows of internal data (of the required type), a label to display, and whether the row is checked. This model can hold, for example, rows of ship's indices, their displayed names and whether they're available when a campiagn begins.

QtFred: Model for ListView of checkboxes

---

code/mission/missionparse.cpp

The ship index was being checked against the weapon limit.
Fixes #3413.

use the proper range check

---

code/parse/sexp.cpp

As pointed out in #3419, subsystems can in fact have 0% maximum hull.
Fixes #3419.

remove unneeded warning

---

qtfred/src/FredApplication.cpp
qtfred/src/main.cpp
qtfred/src/ui/QtGraphicsOperations.cpp

Fixes blurry background image / stars and related Qt warning on startup, as well as a crash on quit, caused by deallocating a glsync too late.

Qtfred runtime fixes

---

code/localization/localize.cpp

Turns out some mods really do use XSTR ids higher than 9999.  This bumps the capacity from 4 digits to 7 digits.
Fixes #3422.

bump the buffer holding the XSTR id

---

code/scripting/api/libs/engine.cpp
code/scripting/scripting.cpp
code/scripting/scripting.h

String comparisons in lua hook evaluation take up a significant amount of runtime in FSO. This PR shifts those comparisons to hook creation instead of evaluation. Currently only covers the three most frequently evaluated hooks, which in profiling cleans up the vast majority of evaluation's footprint.
~~In draft because it's still pretty messy and slapdash in places, but I wanted to let people review the approach at the least.~~
Now prepared for final review.

Remove string comparisons and switch to vector in script conditions

---

fred2/sexp_tree.cpp

This properly handles variable additions by calling the replace-variable code on the new variable node immediately after the variable is added.  It's a bolted-on hack but it's the simplest way to fix the issue.  A better fix would be to completely redesign the way the sexp tree handles variables (and everything, really) but that would be a major undertaking.
Fixes #3298.

fix add-data for variable names

---

code/weapon/weapons.cpp

Check for nullptr first, otherwise weapons without parents will crash on creation.

Add nullptr check for obj_create priority

---

code/math/vecmat.h

vecmat.h won't compile on gcc11 unless limits.h is explicitly included.

gcc11: add missing include

---

code/graphics/shadows.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

The shadow cascade distances were tuned/added by swifty with the following logic:
`// these cascade distances are a result of some arbitrary tuning to give a good balance of quality and banding.`
Mods, especially TCs, may have very different sized ships compared to FS, and they may desire more precise control over shadow cascade distances.
This PR exposes those values with settings in the `game_settings.tbl`.
PR is tested and works as expected.

Expose Shadow Cascade Distances

---

code/graphics/2d.h
code/graphics/grstub.cpp
code/graphics/opengl/gropengldraw.h
code/graphics/opengl/gropengltnl.cpp
code/graphics/shadows.cpp
code/graphics/shadows.h
code/graphics/vulkan/vulkan_stubs.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h
code/ship/ship.cpp

This finishes @wookieejedi's work on cockpit self-shadow. With this, when shadows are enabled, cockpits will now self-shade automatically. Note, that due to the implementation (and different shadow parameters), cockpits will not get shaded by any other objects (including the rest of their parent craft). Still looks quite good in most situations, and like this there is little performance cost (unlike if we had to re-render the whole scene's shadowmap).
Closes #2023

Self-Shadow on 3D-Cockpits

---

code/mission/missionparse.cpp

Although this change my seem trivial on the surface, this prevents 'damaging' operations being repeatedly applied to `max_hits` directly. Without this the `current_hits` of the subsystem can end up slightly higher than its max hits, and trip https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/ship/ship.cpp#L10448 this assert when changing ship class.

Fix floating point error on subsys hits during ship class changing

---

code/weapon/emp.cpp

To keep the AI code from going crazy, we should keep the AI from targeting itself during/after EMP.  The AI will attempt to do this if they are set to traitor.
Closes #3366

Fix AI targeting itself during EMP

---

code/object/collideshipweapon.cpp

This extra culling for collision with a large ship depends on _constant velocity_, not it being a laser. This could otherwise cause homing lasers to be erroneously collision culled (and now also allows dumbfire missiles to benefit from this culling).

Fix collision culling for homing primaries

---

code/fireball/warpineffect.cpp
code/nebula/neb.cpp
code/nebula/neb.h
code/object/objectsort.cpp
code/ship/ship.cpp
code/weapon/trails.cpp

The mission-specific fog near/far/density values need to set before being used, but this is only done by the `neb2_get_fog_visibility(object *obj)` function so the other overload (that only takes a position) may not have this information when necessary. Although this is unlikely (as it is common for both functions to be called several times a frame), it should really be part of `neb2_post_level_init`. 
Pulling that out was basically the only real difference between the two so it can just be removed. Also puts a flag check on trail fading since it is new.

Some fixes to nebula fog set up

---

code/ai/aicode.cpp

The AI code seems to assume that bugs can never happen and that it only has to check to see if an index is -1.  The trouble is, with memory bugs, this is not always the case, and we need to add some asserts to prevent error message-less edge case crashes if they start occurring. 
The first commit in this PR gracefully handles a case in multi where the objnum is nonsense.   The others just add those safety checks to throw an assert so that we don't do a negative array access by accident.
Bug reported here: https://discord.com/channels/223511295431933953/423504150437953537/832038232623022110
The minidumps used to find the break point are here: https://discord.com/channels/223511295431933953/423504150437953537/832062427226963982

Fix ai update danger weapon and Add guardrails for other checks

---

code/cutscene/cutscenes.cpp
code/menuui/optionsmenumulti.cpp
code/menuui/readyroom.cpp
code/menuui/techmenu.cpp
code/mission/missionbriefcommon.cpp
code/mission/missionbriefcommon.h
code/mission/missiongoals.cpp
code/missionui/chatbox.cpp
code/missionui/missionshipchoice.cpp
code/network/multi_pxo.cpp
code/network/multiteamselect.cpp
code/network/multiui.cpp
code/parse/parselo.cpp
code/parse/parselo.h
code/popup/popup.cpp
code/scripting/api/libs/graphics.cpp

FSO's function to automatically linebreak text was previously only looking at the line lengths in pixels, and copying that into fixed length buffers. Hence, if you had characters using a lot of bytes per width (like in the NTP's Japanese translation with Kanjis) or a high resolution resulting in more characters per line being displayable (this is conjecture only, I haven't actually tested that this was an error before, but I am fairly certain it was), many functions using this linebreak functions could trip asserts, or worse, overrun their buffers causing CTD's. Thus, this also fixes #3438.
For the briefing parts specifically I also increased the buffer size, as this is a relatively safe thing to do, and otherwise lines could be broken earlier than the screens end, which is ugly (but not …

Fix erroneous line break generation for non-ASCII string and high resolutions

---

code/starfield/starfield.cpp

"Asteroth, who the heck cares about motion debris rendering" 
Well, you might be surprised to learn, at least on my machine in testing, occasionally motion debris rendering could take as long as _a millisecond_. By switching it to the batching system, it significantly reduces the render time.
As always, a bunch of other improvements and cleanup related to drawing the motion debris. It now fades in from a distance, the max distance increased as a result, and the total number increased as a result of _that_. The changes to the size aren't "real" changes, for reasons that are unclear to me, the switch of rendering methods significantly increased their apparent size, so I adjusted the size constants to compensate.

Optimize motion debris rendering

---

code/hud/hudgauges.h
code/hud/hudparse.cpp
code/parse/sexp.cpp
code/parse/sexp.h
fred2/management.cpp
fred2/sexp_tree.cpp
fred2/sexp_tree.h
qtfred/src/ui/widgets/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.h

This upgrades the HUD gauge parameters in two ways:
1) Removes the ugly legacy capitalized HUD gauge names, only used in `flash-hud-gauge`, from the SEXP context menu.  They will still work, but the default going forward will be the more readable retail gauge names.  The parameter type has also been renamed to `OPF_BUILTIN_HUD_GAUGE` to be more specific.
2) Adds a new `OPF_CUSTOM_HUD_GAUGE` to implement the feature requested in #3364.

Hud gauge parameter type

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/object/collideshipweapon.cpp

...despite full shields in that quadrant. If the ship moves towards the weapon in the frame, the next collision check for the weapon may start it *inside* the shield where last frame it may have ended just *outside* the shield. By adding in the ship's velocity we essentially take into account the apparent motion of the weapon from the ship's own moving reference frame. This was tested and works with regular and highly adversarial examples, such as very slow moving weapons which are normally very difficult to actually trigger collisions against for this reason.
The bigger issue, however, is backwards compatibility. I think almost everyone has noticed this happen at some point or another, and although I haven't specifically tested for it, I highly suspect this is the reason Seraphim and …

Fix a bug where shields could occasionally be pierced

---

code/parse/parselo.cpp

Replacing spaces with tabs to fix -Wmisleading-indentation

Fix GCC11 warning: whitespace cleanup

---

code/model/modelread.cpp
code/parse/parselo.h

Before:
```
Error: D:\Knossos\FS2\final-gen-1.2.0\core\data\missions\demo1.fs2(line 1):
Error: Expected float, found [ -0.972221$special=subsystem].
File: parselo.cpp
Line: 312
```
After:
```
Error: submodel turret10-base on INF_Selket.pof(line 1):
Error: Expected float, found [ -0.972221$special=subsystem].
File: parselo.cpp
Line: 312
```
This change also adds some logic to treat a `$` as a line break if necessary. That was added to fix the above error in already released mods since this error became visible only very recently and is present in an Inferno model released in 2015.

Provide better error messages for invalid vec3ds in POF files

---

code/object/objectsnd.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

Very confusingly $InFlightSnd is _not_ a 3d sound that the weapon emits, like EngineSnd for ships. It is a HUD sound that constantly plays while the player has one of these weapons in flight. This adds 'AmbientSnd' for weapons, as a counterpart to EngineSnd, any instance of this weapon passively emits this 3d sound as it moves.

Add weapon ambient sound

---

code/mission/missionparse.cpp
code/parse/sexp.cpp
code/parse/sexp.h
code/parse/sexp_container.cpp
code/parse/sexp_container.h
code/source_groups.cmake
fred2/missionsave.cpp
fred2/missionsave.h
qtfred/src/mission/missionsave.cpp
qtfred/src/mission/missionsave.h

First in a series of PRs to add SEXP containers, based on PR #3398 .
This PR adds
- definition (`struct sexp_container`) and basic bit flags
- parsing containers from mission (`.fs2`) files
- saving containers to mission files

karajorma's SEXP containers, Part 1: Definition, parsing, and saving

---

code/weapon/beam.cpp

Beam 'launch' sounds only play if their loop sound is provided as well. There's no real reason for this to be the case, they are logically disconnected, all those sounds that are valid should be played when appropriate, irrespective of the status of other sounds.

Minor beam sound fix

---

code/math/vecmat.cpp
code/math/vecmat.h
code/particle/ParticleEffect.h
code/particle/ParticleManager.cpp
code/particle/effects/VolumeEffect.cpp
code/particle/effects/VolumeEffect.h
code/source_groups.cmake

Adds the 'Volume' effect type, which spawns particles in a spherical volume. Options for biasing the particles towards the center or the edge, or 'stretching' it into an ellipsoid are provided as well.
Closes #2935

Add volume effects

---

code/weapon/weapons.cpp

Like the comment itself says, `max_allowed_player_homers` should only be used for the player, so y'know... might be good to actually _check_ for that. >.>

Fix heatseeker max homing limit for non-players

---

code/parse/sexp.cpp
code/scripting/api/libs/base.cpp

Validate values supplied to `rand` and `rand-multiple` SEXPs and also to `rand32()` scripting function before calling `Random::next()`, and issue a warning if the provided values are invalid.
Fixes issue #3459.

Validate user-provided values passed to Random::next()

---

code/ai/aicode.cpp

God _dang_ it, Sushi! Test your shit!! A single test with a seraphim or nephilim would tell you immediately that no, just because you put the flag in `set_predicted_enemy_pos` which, yes, is *one* of the places where it arbitrarily grabs the first firepoint does *not* mean the ship will start shooting from its center! Look at what the effect your code is. It's using that data to calculate *collision time* (from the fire point or center), which going to be negligibly affected by whether its counting from the firepoint or center anyway. At no point in that function does it actually *point the ship at something*. That's handled by `ai_turn_towards_vector`'s `rel_pos` parameter, so *that's* what you should be trying to affect.
I don't expect people to know all that, I know that because I've …

Fix Ai_aims_from_center flag

---

code/model/modelrender.cpp

Glowpoint rendering uses `batching_add_bitmap`'s 'depth' parameter, which instead of rendering the bitmap at the "regular" position in space directly moves the bitmap towards the camera by the 'depth' amount (for glowpoints, this is always the radius of the glowpoint). Despite knowing exactly how it is works, I have absolutely no idea what sort of effect this is meant to achieve, or what purpose it was intended for. While it might sound reasonable, in practice it simply looks terrible. It is immediately obvious that the glowpoint's bitmap is being 'detached' from its surface and magically floating towards you. Worse still, if you're closer than its radius the glow point is rendered _behind you_ looking even more absurd.
https://user-images.githubusercontent.com/17305613/120088919-8a841600- …

Remove glowpoint 'depth'

---

code/missionui/missionshipchoice.cpp
code/parse/parselo.cpp

Commit 6c2ebab01c2ab51c1fd1876370667d6f4400be7c (#3439) added a `max_line_length` argument to `split_str()`, but one call had the extra argument added in the wrong spot, and so a previously-pointless-but-harmless `ignored_char` of 0 became a `max_line_length` of 0, resulting (ultimately) in an exception in the unicode code when the iterator tried to decrement at the beginning of a ship's description. This gets rid of the argument entirely, rather than reordering them, because ignoring null characters doesn't really do anything anyway.
I've also added `Assertion`s to check `max_line_length` that should prevent this specific problem from occurring again in the future.

Fix calling split_str() with a maximum line length of 0.

---

code/weapon/weapon.h
code/weapon/weapons.cpp

Instead of always grabbing the closest, heatseekers can also be specified to grab a random target from those available. This is only for the case where the missile must grab a target on its own, such as being an "untargeted heat seeker" or having lost its target.

Add random homing target acquisition

---

code/parse/sexp.cpp
fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

The script-eval SEXP evaluates all arguments as individual script commands, which is not ideal because most FREDders expect the arguments to be concatenated.  Since the script-eval-block SEXP handles its arguments this way, it makes sense to hide the script-eval SEXP in FRED to prevent confusion.

deprecate script-eval

---

code/weapon/weapons.cpp

If a weapon has "inherit parent target" but not "child", a Warning will be generated. However, there is no dependency between the two flags; the weapon will function as the modder presumably expects. The Warning even seems to indicate this, by saying "No changes in behavior will occur" (as opposed to other similar warnings, which generally indicate that a flag will be ignored). Since the situation being warned about does not actually cause any issues, the Warning is entirely superfluous. As such, I've removed it outright.
Reported by @MatthTheGeek on Discord.

Remove superfluous warning about missing "child" flag.

---

code/weapon/beam.cpp
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

While a silly idea on the surface, modders can (and already do) use weapons for a wide variety of utilitarian purposes, far beyond just things you throw at other things to make them blow up. From triggering visual effects, audio effects, spawning other weapons, or any other thing might want them for, actual collisions might just be getting in the way of what they need.

Add "no collide" for weapons

---

code/ai/ai_profiles.cpp
code/ai/ai_profiles.h
code/ship/ship.cpp
code/ship/ship.h
code/weapon/weapon.h
code/weapon/weapons.cpp

Makes AIs only select secondary weapons that are in range of the AI's target. This is in addition to the normal selection filtering that AIs do to try to pick appropriate missiles. Controlled by a AIProfiles flag, which is set up for later expansion to multiple modes; I wanted to implement a preference for longer or shorter ranges when multiple weapons are in range, I'm deffering that to later rather than letting this languish on my drives any more.

Range aware secondary selection

---

code/parse/parselo.cpp

Here's a bug that's been around ever since version 3.6.  If the subsystem names were not essentially the same, the function wouldn't do the expected string comparison.

fix bug in subsystem_stricmp

---

code/object/objcollide.cpp

The collision system will predict how far into the future to defer its next collision check which does this based on the weapon's speed. If the weapon is accelerating however these predictions will be much too far in the future, as the prediction was made with its previous slower velocity in mind. While it's possible to have a secondary quadratic solution for the weapon's minimum speed in addition to its maximum speed it's much simpler to just exclude accelerating weapons from this and treat them more conservatively like missiles.
Note that once the weapon finishes accelerating it gets `CONST_VEL` and can benefit from this calculation again.

Fix collision culling for accelerating weapons... again

---

code/particle/particle.cpp

Particles start to fade out based on proximity at a hardcoded 30 meters, which can look very odd for particles smaller than 30 meters, so take the min of the two before starting to fade. 
This improves, but does not completely solve #3356. For reasons I'm unable to determine those pure white effects will still be noticeably shy of actually pure white even when the call to `batching_add_volume_bitmap` is passed 100% alpha (and that value survives all the way to the vertices being directly pushed to the batch), regardless of the view distance. Beyond that point, my confidence in being able to debug it drops rapidly.

Improve particle alpha handling for small particles

---

code/scripting/api/objs/physics_info.cpp

Like other similar functions, the `offset` should be initialized to nullptr and then checked to see if the user filled it. By initializing with a reference to `vmd_zero_vector`, if the user doesn't fill it, that vector add can be modifying the zero vector! Yikes!

Fix a bug with applyWhack scripting function

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/object/collidedebrisship.cpp
code/object/collideshipship.cpp

For some dumb reason, ship-ship collisions will try to count the damage as a shield hit for the heavier one. This adds a flag to make it hull damage for all involved parties.

Add No_shield_damage_from_ship_collisions flag

---

code/ai/aicode.cpp
code/asteroid/asteroid.cpp
code/io/keycontrol.cpp
code/object/collidedebrisship.cpp
code/object/collideshipship.cpp
code/object/collideshipweapon.cpp
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/shiphit.cpp
code/ship/shiphit.h
code/weapon/beam.cpp
code/weapon/shockwave.cpp
code/weapon/weapons.cpp

I wouldn't have bothered so soon after posting the issue, but I kept running into it so I guess I gotta do something about it.
When dealing damage, damage callers should pass in the appropriate damage type, rather than having `ship_do_damage` make wild guesses based only on the type of the damaging object which cut down on those obnoxious chains of if elses in there. The changes to collidedebrisship.cpp look daunting but I had to do some varaible renaming to avoid awkward stuff like carrying around `pship` and `shipp` or something.
The main behavioral changes of note here are that instant blasts from ship explosions and weapons now deal their associated shockwave damage type. That might sound worrying for weapons, but remember that the shockwave damage type for a weapon is by default the …

Improve damage type handling when dealing damage

---

code/model/modelread.cpp

With several upcoming POF format enhancements (byte alignment, external weapon rotation, submodel translation) it makes sense to warn users if they happen to load an unsupported POF file.

add warning for supported POF file versions

---

code/model/modelcollide.cpp
code/model/modelread.cpp
code/model/modelsinc.h

Changed SLDC system to SLC2, this replaced the char at the beginning of the node for an int in order for the tree to be aligned.
Added BSP_Defpoints data alignment and SLDC to SLC2 conversion for pof version < 2118.
Re-upload after #2691 got merged and reverted by accident.

POF 2118 and SLC2 support

---

code/object/objectsnd.cpp
code/object/objectsnd.h
code/scripting/api/objs/object.cpp

The default sound position should be the zero-vector, not nullptr.  Also, this adds a bit of extra type safety.

fix to #3476

---

code/ai/ai_flags.h
code/ai/aicode.cpp

In #2673 a chunk of code was removed https://github.com/scp-fs2open/fs2open.github.com/pull/2673/files#diff-5bc93e562f5e539d8b3dc382d359e76b27125c5607bab24aaeb6c8c2471e5a7aL14227
This code allowed ships in `Formation_object` or `Formation_wing` mode to turn much faster than normal (by actually setting `desired_rotvel` to non-zero, unlike the rest of the code, which means the physics damping no longer works against the ship). However, it really mucked up how the system should've worked, and ships don't really need any extra help while simply flying in formation. Later, @Goober5000 would report a bug to me, where I discovered that, very counter-intuitively, `Formation_wing` also applies to waypoint flying. Ships which before barely made their waypoint turns, were now unable without this …

Bugfix for waypoint turnrate

---

freespace2/freespace.cpp

This adds the scripting state to the list of states that checks whether it should reset data or not.
Fixes #3474

Add Menu and Mission resetting to scripting state.

---

code/scripting/api/libs/bitops.cpp
test/src/scripting/api/bitops.cpp
test/test_data/scripting/bitops/addBit/data/scripts/test.lua
test/test_data/scripting/bitops/setBit/data/scripts/test.lua
test/test_data/scripting/bitops/unsetBit/data/scripts/test.lua

Allow AND and OR to take up to 10 arguments.  Deprecate addBit and replace with setBit, and add unsetBit.

some bitwise operation enhancements

---

code/scripting/api/libs/bitops.cpp
code/scripting/api/objs/enums.cpp
code/scripting/api/objs/object.cpp

This adds `EnumAND` and `EnumOR` which will return new enums based on the specified operations.  These are handy for enums that correspond to bit fields, such as those used for object persistent sounds.

add bitwise operations with enums

---

code/missionui/missionbrief.cpp

Currently, the model previews during the briefing did not calculate a shadow map. This means that the actual render stage used the last used shadowmap to render (in case of a mission play through the techroom, this is most likely the shadow of the ship shown by default in the ship viewer of the techroom). This is obviously just wrong and will lead to shadows completely unpredictable and wrong in the mission briefing.
This adds proper shadow calculation.
Code is essentially copied from the techroom

Add shadow map generation for briefing

---

qtfred/src/CheckedDataListModel.h

My CheckedDataListModel wasn't flexible enough for use in the CampaignEditor's mission list so I rewrote it. It now stores simple types directly or takes ownership of a pointer to class types.

Rewrite of CheckedDataListModel

---

code/gamesequence/gamesequence.cpp
code/graphics/2d.cpp

Make `gameseq_get_state` return GS_STATE_INVALID if the stack is invalid.
With this change, the check for stack validity can be removed in `gr_flip`.
Follow-up to #3346.

actually use GS_STATE_INVALID

---

freespace2/freespace.cpp

#3360 actually broke a number of things because scripts were loaded before weapons and ships, so caching those conditions didn't actually work. I failed to realize that none of my test cases actually covered the use of those conditions. 
Changing the scripting init to only take place after everything else makes sense to me since as far as I can tell there are no hooks for 'on load' type actions, so scripts only should be acting on the final state anyway. I have done some testing on script heavy parts of FOTG and this seems to work, ~~but I'm putting this in draft until I can test or get test reports from a few more mods to make sure this doesn't do anything weird.~~ After more testing I'm confident enough to submit this fully.
@asarium I also beg your eyes since I think you're the most …

Moved script initialization to take place after all table loads

---

code/parse/parselo.cpp

https://github.com/scp-fs2open/fs2open.github.com/blame/ed2cc47093f2a1b2f8bd89c54784ad5a2de49179/code/parse/parselo.cpp#L3014
Attempts to restore the original error handling of `stuff_int_list` for `WEAPON_LIST_TYPE`, `WEAPON_POOL_TYPE`, and `SHIP_INFO_TYPE`. Where `WEAPON_LIST_TYPE` would merely warn and stuff -1, and the other two would stuff nothing and produce no warning or error. This changes it to warnings in all cases but only stuffing as it did before. Erroring instead of warning is a very harsh backwards compatibility break which people have been running into, and I would like to ease if possible.

Restore original error handling of stuff_int_list

---

code/ship/ship.cpp

Negative `$Hull Repair Rate` is explicitly allowed, so I do think it should be supported, even if not commonly used. If the hull strength drops below 0, make sure to actually kill the ship rather let it persist in that weird negative health zombie state.

Properly handle death due to negative hull repair rate

---

code/weapon/beam.cpp
code/weapon/beam.h

Another day, another completely dysfunctional feature...
```
+Attenuation:
Defines the point where the damage caused by the beam starts to attenuate. At maximum range damage is zero.
Syntax: Float, from 0 - firing point to 1 - no effect 
```
Just so we're clear how this *should* work.
Using `last_shot` to get the hit distance is wrong, because it is only updated to be the world hit position *after* the collision and damage has been handled. And if the ship doesn't stop the beam, that won't happen at all, `last_shot` will still be off in the distance. It should be directly using the collision info's world hit pos (this way different targets of the same beam also have differing amounts of damage depending on attenuation).
Also the calculation was backwards, it was instantly bringing the …

Bugfix for beam attenuation damage

---

code/weapon/beam.cpp

Shooter scale offsets (that is, not target scale) should mean the offset is centered on the target but scaled to a constant angular span from the point of view of the shooter. Using just 300 meters centered on the target still has a differing angular span depending on its distance, it should directly use the distance, this way the offset scale basis is constant no matter its position.
Also should use `turret_point` like the rest of this function, `last_start` isn't necessarily valid yet.

Bugfix type 5 shooter scale offset

---

code/localization/localize.cpp
fred2/management.cpp
qtfred/src/mission/management.cpp

Bug #3471 occurs because the game only keeps a translation table for the current language.  Since the mission list needs to compare untranslated strings against English strings, this adds a duplicate table for English.  However, it only keeps strings that are NAME_LENGTH or less, because the comparison only needs to be run against mission names.
Fixes #3471.

maintain a copy of the default translations to check against untranslated strings

---

code/hud/hudtarget.cpp
code/model/model.h
code/model/modelread.cpp
code/object/object.cpp
code/ship/ship.cpp
code/ship/ship.h

@EatThePath pointed out that external weapon models are always rendered in the same orientation as the parent ship, and many models would benefit from being rotated to different orientations.  This adds an angle offset as a property of gun and missile points.  It requires a bump in the POF version, which consequently requires the extra information to be added via a hex editor, at least until PCS2 is upgraded.
Gun and missile points are also cleaned up a bit, mostly by being dynamically allocated so that they don't waste so much memory (about 4kb for every model in the game).
Implements #3143.  ~~This is in draft status until tested.~~

Add external weapon model angle offset

---

.github/workflows/master-build.yaml
.github/workflows/pr-workflow.yaml

This sets up ccache to speed up some builds. I hope this also works with
forks since I don't know if those are allowed to use the main repo
cache.

Use ccache to speed up some PR builds

---

code/parse/sexp.cpp
code/parse/sexp.h
fred2/sexp_tree.cpp
fred2/sexp_tree.h
qtfred/src/ui/widgets/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.h

Checks whether the game is running in the specified language.  Since the fiction viewer doesn't use XSTR-style localization, this SEXP can be used to display different stages for different languages.

add is-language

---

code/lab/dialogs/actions.cpp
code/lab/dialogs/actions.h
code/lab/dialogs/backgrounds.cpp
code/lab/dialogs/backgrounds.h
code/lab/dialogs/class_descriptions.cpp
code/lab/dialogs/class_descriptions.h
code/lab/dialogs/class_options.cpp
code/lab/dialogs/class_options.h
code/lab/dialogs/class_variables.cpp
code/lab/dialogs/class_variables.h
code/lab/dialogs/lab_dialog.h
code/lab/dialogs/render_options.cpp
code/lab/dialogs/render_options.h
code/lab/dialogs/ship_classes.cpp
code/lab/dialogs/ship_classes.h
code/lab/dialogs/weapon_classes.cpp
code/lab/dialogs/weapon_classes.h
code/lab/labv2.cpp
code/lab/labv2_internal.h
code/lab/manager/lab_manager.cpp
code/lab/manager/lab_manager.h
code/lab/renderer/lab_renderer.cpp
code/lab/renderer/lab_renderer.h

Ensure the `LabManager` always cleans up game objects when it's destroyed.  The fact that it *wasn't* cleaning up when players go to the options menu was causing Issue #3127.
Also plug various memory leaks in the lab, specifically with
1.The `LabManager`'s `Renderer`
2. The `LabRenderer`'s `labCamera`
3. The `LabManager`'s `Dialogs` and any `LabDialog`s' `Subdialogs`/`subDialogs`.
The PR fixes (1) and (2) using `unique_ptr`s and (3) by always using `shared_ptr` for `LabDialog` objects.
The PR also makes `LabManager`'s `Screen` a `unique_ptr` to avoid having to manually delete it.
AFAICT, all other lab objects are managed in FSO-style linked lists, and it looks like the code is correctly managing the lists, but I would need to dig extra-deep to be 100% sure.

Fix leaking of game objects and memory in F3 lab

---

code/parse/sexp/LuaSEXP.cpp

Previously, luasexps could not be placed into subcategories that were not unique.
Not only did this include custom categories, but also built-in ones, so sexps couldn't be placed into categories like "Weapons, Shields, and Engines", as that exists both in status and in change.
This does away with this requirement (tbh, I am not sure why it was there in the first place).
If you specify a built in subcategory but it only exists in a different main category, this will now create a new subcategory in the main category specified, as I would expect from the luasexps

Allow non-unique sexp subcategories

---

code/object/objectsnd.cpp
code/object/objectsnd.h
code/scripting/api/objs/enums.cpp
code/scripting/api/objs/object.cpp
code/ship/ship.cpp

This adds two new enums to persistent sounds which can be utilized by scripts.
1. OS_PLAY_ON_PLAYER, which allows persistent sounds to play on the player's ship.
2. OS_LOOPING_DISABLED, which allows the scripter to set the sound to play once and not have to then call `removeSound` later. Very handy for playing an assigned sound once with one line.
Tested and everything works as expected.

Add More Options to Scripted Persistent Sounds

---

code/ai/aicode.cpp
code/hud/hudets.cpp
code/ship/ship.cpp
code/ship/ship.h

Adds an optional delay after hitting before shields will start to recharge.
In order for this to work on players `last_hit_time` needs to be properly updated for them too, and wasn't before, which should also make the behavior of player ships under AI control a bit more consistent.

Add shield regen hit delay

---

code/globalincs/pstypes.h
code/math/vecmat.cpp
code/math/vecmat.h

This is the product of a general effort on my part to understand and clean up the code and documentation surrounding 3D vectors, especially when it comes to multiplication. The main consequence is that `vm_vec_rotate`, `vm_vec_unrotate` and `vm_matrix_x_matrix` are now wrappers around cleaner `operator*` instances — a great deal of manual indexing and arithmetic has been replaced with structured calls to `vm_vec_dot`. The potential for using this as a hook for future vectorisation has been discussed but is still speculative.
I really wanted to clean up matrix4 in the same way but it turns out to be a weird mess that relies on behaviour inconsistent with the 3x3 matrix ops. For now I'm leaving it alone, rather than trying to standardise it in its quasi-broken state.

Reimplement matrix3 multiplication based on a common overloaded operator

---

code/ship/ship.cpp

A small oversight from AI multilock. Multilock missiles firing after the fact get an exemption from no dumbfire since the "locked" property is checked when the missiles are initially queued up to be fired, and not as they are being unloaded.

Bugfix with ai multilock and no dumbfire

---

code/hud/hudshield.cpp

This causes the little mini target hull/shield indicator just below the reticle to be handled like the regular shield indicator is, only use `Quadrant_xlate` if it has default shields, for model point shields simply use the .ani frames in the direct shield quadrant order. Importantly this will prevent single quadrant shields from indexing out of bounds (because it would use `Quadrant_xlate` to index the 1st shield quadrant for the 0th ani frame)

Fix model point shield handling for mini target shields

---

code/ship/ship.cpp

Using `n_quadrants` in `shield_set_strength` before possibly initializing it with `Model_point_shields`...
tsk tsk

Initialize `n_quadrants` before setting shield strength

---

code/math/vecmat.cpp
code/math/vecmat.h

Asteroth suggested I use the unit tests to profile the new matrix ops. Multiplication was slow as hell. I added inlining. The artificial unit test benchmark became fast! The total binary size seems the same. What could possibly go wrong?

Inline matrix multiplication ops for performance improvements

---

code/parse/sexp/LuaSEXP.cpp

Certain characters (especially the semicolon) couldn't be used in SEXP help.  By using the same character replacement as in briefings and messages, now they can.

allow characters in SEXP help

---

code/debris/debris.cpp
code/debris/debris.h

Removes this retail function that was actually perpetually postponing the death of debris at long distances instead of removing them.  Debris lifetime is suitably short for the small, non-hull pieces (only a few seconds), while large pieces are supposed to be permanent, since they can be visible even at longer ranges.   This function would also remove debris based on player position, which is not the correct approach, since the camera can be free from the player ship.
Additionally, there's no real reason to try to remove debris to save on performance, since even in a busy mission like Icarus, once this function is removed, there are at most 60 pieces of debris in the mission.

Remove Buggy Function and Let Debris End Naturally

---

code/network/gtrack.cpp
code/network/gtrack.h
code/network/ptrack.cpp
code/network/ptrack.h
code/network/valid.cpp

- allow for size of IPv6 game list packet (fixes #3543)
These larger packet sizes aren't required for
FS2/FS2_Open, but just keeps the code in sync.

bump tracker packet sizes to match server

---

code/mission/missionparse.cpp

https://github.com/scp-fs2open/fs2open.github.com/pull/3363/commits/2a9178318c5137dd7fcfdd1fb2e465b3c937d8cc #3363 put the event flag resetting a little bit too late, where it could end up wiping `MEF_USING_TRIGGER_COUNT`. It should be right at the top, before anything is done.

Adjust event flag reseting position

---

code/hud/hudlock.cpp

A bit of fallout from AI multilock, this was erroneously changed from `target_world_pos` (which had just been calculated for this purpose) to `lock_slot->obj->pos`, preventing locks on subsystems if the player is is out of range of the ship's center.

Fix a secondary range bug from AI multilock

---

code/mission/missioncampaign.cpp

If the loop mission and the next mission are the same, then don't show the campaign loop screen.  This prevents the campaign from getting into a campaign loop state if it shouldn't, and also allows campaign loops to be conditionally accessible.

fix campaign loop in certain cases

---

fred2/fred.cpp
fred2/fred.rc
fred2/fredrender.cpp
fred2/fredview.cpp
fred2/fredview.h
fred2/resource.h
qtfred/src/mission/EditorViewport.h
qtfred/src/mission/FredRenderer.cpp

Add some useful QoL improvements for turrets.
1) Each turret now not only displays its name, but also whatever weapons it is carrying.
2) A new menu option allows displaying info from all turrets at once.
Tested and works as expected.  See screenshot:

FRED turret info

---

qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
qtfred/src/ui/QtGraphicsOperations.cpp
qtfred/src/ui/widgets/ColorComboBox.cpp
qtfred/src/ui/widgets/renderwidget.cpp

This macro bypasses a compiler bug where MSVC can't distinguish the division symbol.  See https://bugreports.qt.io/browse/QTBUG-72073

work around MSVC 2015 and 2017 compiler bug

---

code/menuui/readyroom.cpp
code/network/multiui.cpp

As a follow-up to #2343, users might wonder why their mission isn't showing up in the tech room, so log a friendly message.

log when missions are skipped due to XSTR mismatch

---

code/mission/missiontraining.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

This adds a setting to game_settings.tbl to allow training messages to play to their full duration.  This avoids them getting pre-empted by other messages as noted in #3202.
To use, add this to game_settings.tbl:
```
#LOCALIZATION SETTINGS
$Don't pre-empt training message voice: true
```
Fixes #3202.

Training message preservation

---

code/ai/aiturret.cpp
code/ship/ship.cpp
code/weapon/weapon.h
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

This burst flag essentially sets burst shots to the number of firepoints of whatever is firing the weapon at the moment. This is useful for mods like FotG, where multiple turrets all use the same weapon, but have differing numbers of firepoints, where the burst length should correspond to it, and circumvents the cumbersome use of many weapon copies.

Add "num firepoints for burst shots" flag

---

qtfred/src/mission/Editor.h
qtfred/src/mission/EditorViewport.h
qtfred/src/ui/FredView.cpp
qtfred/src/ui/FredView.h
qtfred/ui/FredView.ui

There are several updates to the menu in FRED that hadn't yet been ported over to qtFRED.  This PR ports over the changes to the menu and toolbars, viz. a few added menu options, a menu reorganization, some caption changes, and some shortcut key changes.
This partially addresses #3341.

Qtfred menu update

---

code/ship/shipfx.cpp

If the ship has a specially defined generic debris model, don't use it for subsystem destruction. The entire ship and and its subsystems are usually quite different in size, and so look very silly if they spew generic debris sized for an 'entire ship' explosion. Possibly different kinds of generic debris for subsystem destruction and weapon impacts is on the table, but I'll uh, defer that until asked for. For now, it is only meant for when the ship explodes.

Minor improvement for generic debris on subsystems

---

code/mission/missionbriefcommon.cpp
code/missionui/missionbrief.cpp

If the briefing icon doesn't actually show a ship, then don't use the ship icon override.
Also remove a redundant assignment.

fix briefing icons changing to ships unexpectedly

---

fred2/management.cpp
qtfred/src/mission/Editor.cpp

This function has to be called on game/FRED/qtFRED start, and returns immediately every time after that.  So there is no reason for it to be hear on mission close.

Remove extra AI Profiles call

---

code/ship/ship.cpp

Always ensure that `p_objp` is not null before accessing it, SEXP or script created ships will have no parse object. There is only one other place where `p_objp` is accessed https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/ship/ship.cpp#L10855, but this apparently will only happen in the loadout screen so it should be safe.
As for texture replacements, (as always the diff is confusing but I just wrapped it in p_objp != nullptr) as the comment states, the new positions may be different so we can't import the old ones and if this ship also doesn't have a parse object then it's out of luck and will need to have texture-replace reran on it.

Fix a nullptr bug with change_ship_type

---

code/parse/parselo.cpp

When an empty string is encountered in the weapon list, it's valid, but the -1 should actually be stored, not skipped.
This bug was preventing ship weapons from being explicitly set to None.

fix WEAPON_LIST_TYPE parsing for -1

---

code/osapi/osapi.cpp

This allows FSO to assume that it's in portable mode if it detects Unicode characters in the path provided by SDL.  I tested this by creating a local account with Unicode characters.  It not only runs as expected, but also keeps Knossos from getting stuck on the executable when trying to parse the command line.  
Fixes #3173

Force portable if unicode

---

code/ship/ship.cpp

PR #3064 inadvertently caused all goals to display Time To: Unknown, even though time was only supplied for docking and waypoints.  This restores the original behavior where the Time To: line simply wasn't displayed.

fix Time To: Unknown on the HUD

---

code/cmdline/cmdline.cpp

Fix memory error with `-password` cmdline option and add warning for when the string is too long and gets trimmed.
(Volition bug from retail)

fix error with -password cmdline option

---

code/mission/missionbriefcommon.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

Adds the `$Custom briefing icons always override standard icons:` option to game_settings.tbl.  Implements #3575.
(Also adds the `Dont_preempt_training_voice` flag reset to `mod_table_reset()` since that was missing before.)

allow custom briefing icons to always override standard icons

---

code/mission/missionparse.cpp
code/ship/ship.cpp

Some more bugs from assumptions of ships having parse objects. Beam free by default and turrets that are supposed to start locked should be handled in `subsys_set()` instead of just `parse_create_object_sub()`. I would've liked to remove `Beam_free_all_by_default` handling from `parse_create_object_sub()` entirely, in addition to starting locked, since it should be redundant now, but turrets freed in this way have their initial fire timestamp set to a different value for some reason.

Move some flag setting to subsys_set()

---

code/model/modelanimation.cpp
code/model/modelanimation.h
code/model/modelread.cpp

Fixes two issues identified with the Animation Rework first Phase:
1. Multipart turrets had base and turret angles switched.
2. Initial Type Animations, when called again (due to something like FRED saving and reloading), have already been "completed" and will not start again. This introduces a "forced reset and start" mode for animations, to handle cases like these initial type animations restarting instead of not continuing. Might also be useful for other types of animations in the F3 lab later.

Anim Rework Phase 1 Fixes

---

code/model/model.h
code/model/modelanimation.cpp
code/model/modelanimation.h
code/model/modelread.cpp
code/ship/ship.cpp

Adds a missing copy function in the ship_info class missing so far that was occasionally clearing the animations before,
Additionally, convert turret-based AnimationSubmodels into their own child class to properly modularize that code due to all the required exceptions for turret handling everywhere. Also properly sets cur_angle and desired_base/gun_angle for proper behaviour once the turrets target anything.

Animation Rework Phase 1 Fixes #2

---

code/model/modelanimation.cpp
code/model/modelanimation.h
code/model/modelanimation_segments.cpp
code/model/modelanimation_segments.h
code/ship/ship.cpp

Another round of fixes.
This time, templates caused three problems:
When defining animations for templates, the ship_info_index is yet undefined. For simplicities sake, ship_info information required to find turret model numbers are looked up using ship_info names. This is stable, even for templates.
When copying ship_infos for instantiating templates, animationsegments are not unique anymore. Hence, all the unique pointer actually need to be shared pointers, since the same pointer data is accessed by multiple ship_infos.
To be able to override a ship template's animation data, animations are now all named, with the names being unique. For the old tables, this name is the subobject name. This means that overriding a submodel will then also override the corresponding animation instead of …

Animation Rework Phase 1 Fixes #3

---

fred2/bgbitmapdlg.cpp

Previously, on closing the background editing dialog, FRED would clear all poof bits, not just the ones set by the checkboxes.
Since, if someone edited the mission file to add new custom poofs, they probably don't want them reset every time they edit the background.
This changes this, so only the bits that can actually be set again through the checkboxes are cleared. Eventually, and in qtFred, we'd ideally want a dynamic number of checkboxes here.
For now just a quick fix that enables modders to still edit backgrounds when using many custom poofs

FRED: Don't clear poof flags for poof 7 and after

---

fred2/fred.cpp
fred2/fred.rc
fred2/fredrender.cpp
fred2/fredrender.h
fred2/fredview.cpp
fred2/fredview.h
fred2/resource.h
qtfred/src/mission/EditorViewport.h
qtfred/src/mission/FredRenderer.cpp
qtfred/src/ui/FredView.cpp
qtfred/ui/FredView.ui

This option is helpful because the mesh outlines will often obscure important information like submodel names and turret weapons.

add Draw Outlines on Selected Ships option

---

fred2/createwingdlg.cpp
fred2/shipeditordlg.cpp
fred2/waypointpathdlg.cpp
fred2/wing_editor.cpp
qtfred/src/mission/dialogs/FormWingDialogModel.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
qtfred/src/mission/dialogs/WaypointEditorDialogModel.cpp

Partial revert of Mantis 2053, added in 7d4f9f0fb5:
http://scp.indiegames.us/mantis/view.php?id=2053
The patch was speculative and there was never a confirmed bug.  By contrast, there are plenty of existing missions that use Unknown as a ship, wing, or jump node name and work just fine.

ships, wings, etc. can share names with teams

---

fred2/bgbitmapdlg.cpp
fred2/bgbitmapdlg.h
fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

Inspired by #3584, this properly saves and restores any number of nebula poofs handled by the game.  FRED will only display checkboxes for the first six, since it still uses the static UI, but everything else is handled behind the scenes.

handle nebula poofs dynamically in FRED

---

code/weapon/beam.cpp

Fixes #3590 
Just a small oversight, even a turret-fired beam is not guaranteed to have a target, if fired using `fire-beam-at-coordinates`. That *should* guarantee that is has coordinates at least, so assert if neither is the case.

Handle turret fired type 5 beams without targets properly

---

code/graphics/generic.cpp
code/graphics/generic.h
code/menuui/mainhallmenu.cpp

This is a partial fix of issues related to APNG animations in mainhalls; specifically, issue #3399 (plus a safety check to avoid the related assertion from https://github.com/scp-fs2open/fs2open.github.com/issues/3399#issuecomment-826017373). I'm marking this as a draft for now, because it should be tested thoroughly before being merged (and also because I hope to fix some related issues before 21.4, like cheat animations, but that will require going deeper into the APNG code itself rather than just the generic animation code). However, if this gets tested and seems to work well enough by itself (it should at least be an improvement over the status quo), we can remove draft status and I can make another PR later for the other stuff (hence why I'm not tagging this as unfinished).
Fixes …

Fix APNG misc mainhall animations.

---

qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
qtfred/src/ui/QtGraphicsOperations.cpp
qtfred/src/ui/widgets/ColorComboBox.cpp
qtfred/src/ui/widgets/renderwidget.cpp

Per ngld's suggestion, this adds a version check around the disabling of the qfloat16 overloads.
Follow-up to #3557.

add a version guard for MSVC compiler bug fix

---

code/model/modelanimation.cpp
code/model/modelanimation.h
code/object/object.cpp

This fixes one critical issue with the animation rework:
The stepAnimation call was done once per frame _per ship_, which is obviously wrong. For initial animations (that don't require stepping), this has no visual impact, but a massive performance issue. The call is moved to the correct place, once per frame, with this PR.
Additionally, since the (due to turrets) very common initial animations don't require stepping at all, they now have special handling to save on unnecessary performance waste. With this, the new animation system should again be not noticeable in performance.

Animation Rework Phase 1 Fixes 4 / Performance Issues

---

code/mission/missionparse.cpp

The SD Demon doesn't use the support ship icon anymore, and hasn't since FSPort switched from FS2-style icons to FS1-style icons.

fix icon on FS1 mission import

---

code/globalincs/systemvars.cpp
code/menuui/optionsmenu.cpp
code/nebula/neb.cpp
code/nebula/neb.h
code/render/3ddraw.cpp

Follow up to #3507. Due to the confluence of 3 old bugs, the nebula poofs people were getting had significantly more 'oomph' (density, opacity *and* size) than a straightforward analysis of the code would suggest, all of which are compensated for in this PR.
1. Despite literally handing ~0.5 alpha to the renderer, for reasons I can't determine, the actual results were significantly more opaque. Since the new rendering actually displays the proper amount of alpha, I've basically just guess and checked comparisons to adjust; the apparent alpha is actually more like 0.8
2. Unlike all other `Detail` settings, nebula detail has an extra level of indirection for no reason; any changes to nebula detail must update  `neb2_set_detail_level()` rather than just using the value directly. Likely …

Fix for 'anemic' poofs

---

code/object/objcollide.cpp
code/object/objcollide.h

A few times in the code, notably by usages of `set-object-position`, collision pairs `next_check_time`'s must be recalculated due to being invalidated for some reason (like an object teleporting). By default, it will set all pairs to be rechecked in 25ms. This is a very bad idea, and should never be set into the future by any amount. A pair which is validly imminently to be checked could end up getting deferred into the future past when it should be colliding. If that SEXP is used every frame and your framerate is better than 40, *all collisions are in effect disabled* as they get indefinitely deferred into the future.
They should always be set to time out on the very next check, and since nothing uses this optional parameter and I see very little reason to actually allow this, it has …

Fix collision retiming to never be in the future

---

code/weapon/shockwave.cpp
code/weapon/weapons.cpp

Converting from degrees to radians is *not* 2PI / 180 it's PI /180, so use the macro that has this figured out already. Yes, this will break the rotations of all currently defined shockwave rotations, but at least you can actually rotate into all orientations instead of just half of them now...
Additionally remove a redundant radian conversion when rendering 2D shockwaves, as this effectively prevents any usage of the rotation beyond a few degrees.
Also move `rot_angles` into the shockwave code, it should be modifying the new shockwave, not the `shockwave_create_info`.
Fixes #3603

Some fixes to shockwave rotation

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aicode.cpp

1) Several AI profiles options were getting reset on every iteration through the loop.  They should only be reset when the profile is initially created.
2) Keeping track of AI hits on the player ship was added by Sushi in 9246a2f74d and needs to be guarded by a flag.  This flag has been enabled for mods that set the required FSO version.

some ai_profiles fixes

---

code/controlconfig/controlsconfig.cpp

Essentially, the wrong constant was used in the call to std::move which happened to be 1 element too long fo both Axis_map_to[] and Axis_map_to_defaults[].  Some compilers would complain about this, but apparently mine didn't catch it when I made the code changes.

Fixes a typo in controlconfig that causes an issue with std::move.

---

freespace2/freespace.cpp

#3571 includes a sort of 'sway' to the camera as the ship moves, which is literally calculated based on the old position of the camera trying to keep up with its proper position. Due to this, if the ship moves in significant or unexpected ways, this camera 'catch-up' makes it quite obvious. Since FotG has requested it, and since as far as I'm concerned they should probably be the authority on how it should work, it is disabled during the extreme acceleration of hyperspace, so it doesn't leave the camera in the dust.
This is also an issue for `set-object-position` or its derivatives, but the solution will be more complicated there.

No chase cam 'slewing' during hyperspace

---

code/ai/aicode.cpp

...if available, it's simply nullptr otherwise. That they got this far that means the ship is attempting to fire a missile at its target, and if it has a `targeted_subsys` then in all other scenarios this means necessarily it is attempting to fire it locked on that subsystem. (the other cases already handle this properly)
Fixes #3611

Single target multilock missiles should use `targeted_subsys`

---

code/localization/localize.cpp
code/parse/parselo.cpp
code/parse/parselo.h

The old XSTR parsing code was a bit of a mess and did not even properly enforce its format.  These new routines enforce the actual XSTR format and warn when it is malformed, which is helpful for catching table errors as early as possible.  This fixes #3627 and also catches mismatched quotes and other common XSTR errors.  No more wondering why comments are being mysteriously parsed instead of ignored!

rewrite XSTR to be more robust

---

code/parse/sexp.cpp
code/starfield/starfield.cpp
code/starfield/starfield.h
fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

The mission-set-nebula sexp never initialized the nebula range, which is usually done in the background editor.  This PR allows the range to be specified, and sets it to 3000 (the same default as in the background editor) if not specified.
Fixes #3619.

fix nebula range in mission-set-nebula

---

code/gamesnd/gamesnd.cpp
code/menuui/optionsmenu.cpp
code/mission/missionmessage.cpp
code/mission/missiontraining.cpp
code/network/multi_voice.cpp
code/object/objectsnd.cpp
code/scripting/api/libs/audio.cpp
code/sound/sound.cpp
code/sound/sound.h

If an entry in a game sound fails to load, mark the sound as invalid and don't try to load it afterwards.  This is the "permanent fail" fix for #3388.

handle invalid gamesnds

---

code/ai/aicode.cpp
code/ai/aiinternal.h
code/ai/aiturret.cpp

`ai_fire_from_turret()` has been renamed to something more appropriate `ai_turret_execute_behavior()` to make it clear that it's more general than literally just shooting at things. The function needs to be evaluated regardless of whether there are enemies on the field or the turret has a target because that is where resetting is done. The function is perfectly capable of determining on its own that there are no valid targets and not to do anything other than possibly reset.

Fix turrets not resetting sometimes

---

code/sound/sound.cpp

Looping 3D sounds are defined as sounds played using `snd_play_3d()` with the `looping` argument set to `1`. These include beam fire and object-persistent sounds (see objectsnd.cpp), which include the engine and subsystem operation sounds of other ships.
Intended to fix Issue #3414.

Apply adjust-audio-volume SEXP for effects to looping 3D sounds

---

code/hud/hudwingmanstatus.cpp
code/ship/ship.cpp

If a wing has a hash symbol, it needs to match the squadron status gauge for the equivalent name without the hash.  This could happen for in-mission jumps or cases where a wing leaves and comes back.
Also remove an obsolete function.

match wing names and aliases on the status gauge

---

fred2/eventeditor.cpp

This syncs up the Close and Cancel behavior.  In both cases, if there are any changes, FRED will display a prompt.

confirm cancel in Event Editor

---

freespace2/freespace.cpp

This might fix #2961.  By explicitly running the garbage collector before a mission starts, this will ensure each mission begins with a clean slate.

run Lua garbage collector on mission start

---

code/parse/sexp/LuaSEXP.cpp

The return type of "shipname" is a string, so if the ship can't be found, return an empty string instead of an invalid ship.

correct shipname return type

---

code/lab/manager/lab_manager.cpp

Fixes a regression introduced by #3636.
Due to the turrets now doing actual submodel processing, they'll try to acquire targets, which CTD's due to the asteroid list being uninitialized (and not just empty).

Fix Turrets in Lab

---

code/def_files/data/effects/main-f.sdr

This is based off a GDC talk given by valve in 2015: http://media.steampowered.com/apps/valve/2015/Alex_Vlachos_Advanced_VR_Rendering_GDC2015.pdf (Page 43)
This decreases the glossiness of surfaces if the derivatives of the normal buffer change too quickly in respect to screen space.
Example of tweak in use:
https://www.youtube.com/watch?v=YjyqpeVCY9I
Default settings, no AA.

Anti-glint shader trick to reduce glimmer on distant objects

---

code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

As somebody who is not experienced with the history of FS modding or its tables, `mod_table.cpp` not being related to modular tables, and instead actually being the file in charge of `game_settings.tbl` was a major source of confusion for me.

Added comment to clarify that the mod_table is about game_settings.tbl

---

fred2/mainfrm.cpp

Explicitly check whether the mission has been saved, because the automatic check doesn't provide a way to detect that it has been cancelled.
Fixes #3654.

fix the cancel behavior when FRED is closed

---

qtfred/source_groups.cmake
qtfred/src/AssociatedPlainTextDocument.h

Another spinoff from the campaign editor & following some talk on discord with cyborg and dahblount, I've written up a relatively simple way to integrate QPlainTextEdits with our common model/view design, wrapping its contents into a submodel.
See also the comments in the new file.

Simplify QPlainTextEdit usage

---

code/scripting/api/libs/mission.cpp

This makes a loop over all ships much faster in lua, as before, each access to mn.Ships[i] in lua required iterating the Objects array, while the iterator will provide the next element of the ship_objects list in constant time.

LUA: Add iterator over ships in mission

---

code/parse/sexp.cpp

This allows the change-iff SEXP to take in another team to change.
A usecase for this can be an event that makes every neutral craft hostile for example, and this change allows for that without having to list all potentially neutral wings and crafts in the sexp

Add full team option to change-iff SEXP

---

code/hud/hudartillery.cpp
code/ship/ship.cpp
code/weapon/beam.cpp
code/weapon/beam.h
code/weapon/weapon.h
code/weapon/weapons.cpp

Gets rid of the whole terribly confusing `BEAM_TYPE_A`, `...TYPE_B`, 0, 1, 2, 3, bullshit and makes everything use clearly named enums for beam types. Tables can still use numbers but will also accept string names for them, and adds a warning for an unrecognized type (which was not done before).
Fixes #3668

Clean up beam type naming scheme

---

code/ai/aicode.cpp
code/ai/aiturret.cpp
code/hud/hud.cpp
code/hud/hudtarget.cpp
code/io/keycontrol.cpp
code/mission/missionparse.cpp
code/missionui/missionweaponchoice.cpp
code/object/object.cpp
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/ship.h
code/weapon/swarm.cpp
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

This is essentially the ballistic flag in reverse for secondaries:
With this flag, secondaries no longer consider ammo for shooting, ammo will not be displayed on the hud, rearmed, or anything.

Add ammoless secondaries

---

code/ship/ship.cpp

Even if all of its secondary weapons are -1, that is, they do not have those banks at all, its current secondary bank will still be set to 0, so check `secondary_bank_weapons` as well before using. Follow-up for #3589

Fix a possible crash with `ship_secondary_bank_has_ammo`

---

fred2/ship_select.cpp

The IDC_FILTER_SHIPS_IFF is not properly cleared resulting in the dialog crashing on second opening due to the data being duplicated and and pushing filter_iff out of range.

Fix Crash On second opening of select box cause by #3634

---

code/gamesnd/gamesnd.cpp
code/gamesnd/gamesnd.h
code/scripting/api/objs/sound.cpp
code/ship/ship.cpp

a) add a new method `gamesnd_game_sound_exists`
b) add script support for this new method
c) use this method when checking for existence of ballistic rearming sounds
d) prevent "empty" and "none" sounds from triggering warnings

make gamesnd a little more robust

---

.github/workflows/build-nightly.yaml
.github/workflows/build-release.yaml
.github/workflows/nightly-trigger.yml
ci/post/file_list.py
ci/post/forum.py
ci/post/installer.py
ci/post/main.py
ci/post/nebula.py
ci/post/nightly.mako
ci/post/release.mako
ci/post/requirements.txt
ci/post/util.py

Once I've added the new secrets, this change should be ready. I haven't been able to test this as much as I'd like but I'll watch the nightlies over the next few days to ensure that everything's working fine.
These changes move most of the functionality from the nightlybuild repo to the CI scripts in this repo which will stop GitHub from disabling nightly builds occasionally because the nightlybuild repo is inactive. It will also allow us to re-run release builds if they fail since the re-run will also trigger the Nebula and forum post.
Finally, this change will build (and post) release builds whenever a new `release_*` tag is pushed which will allow us to do point releases.
This PR has to be merged at the same time as https://github.com/scp-fs2open/nightlybuild/pull/69 !

Refactor CI scripts to make release builds more robust and flexible

---

code/mission/missioncampaign.cpp
code/parse/sexp.cpp

Some instances of the ship syntax checker will check other nodes in the sexp tree.  In those cases, make sure to accommodate special-arg nodes.
This also merges syntax checking for goal/event names and docker/dockee points since they are highly similar.
Fixes #3758.

polish sexp syntax checking 

---

code/parse/sexp.cpp

Don't assign strings that are too long for the string variable capacity.

guard against CTD in sexp variables

---

code/camera/camera.cpp
code/camera/camera.h
code/parse/sexp.cpp

This adds an optional extra factor to `show-subtitle` and `show-subtitle-text` to adjust the line height.  Useful for double-spacing, 1.5-spacing, etc.

allow subtitles to use different line spacing

---

code/missionui/missionscreencommon.cpp
code/model/model.h
code/model/model_flags.h
code/model/modelcollide.cpp
code/model/modelinterp.cpp
code/model/modelread.cpp
code/model/modelrender.cpp
code/network/multi_obj.cpp
code/object/collideshipship.cpp
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/shipfx.cpp

1) Changes the submodel flags to use a flagset instead of several booleans
2) Adds `rotate_accel` to allow submodel rotation acceleration to be specified
Submodel acceleration can now be instant; dumb-rotating submodels always instantly accelerate (and have always done so)

refactor submodel flags and add $rotate_accel

---

code/hud/hudlock.cpp

This only applies to 'incidental' multilocks, not primary targets.
Closes #3775

Dont exclude primary targets from 'no dead subsys targeting'

---

code/weapon/weapons.cpp

They did not use the laser glow size constants, making them too small.

Correctly size glow head-on bitmaps

---

code/graphics/render.cpp
code/graphics/render.h
code/scripting/api/libs/graphics.cpp

@Goober5000 pointed out that lua functions should use radians for angles by default. Since the rectangle rotation feature has only been implemented recently (and as far as I know I'm the only one who's used it), the impact is low enough that changing this is feasible.

Change rectangle rotation to use radians

---

code/cfile/cfilesystem.cpp

- simplify OS specific code
- make sure loose files are always sorted the same regardless of OS or filesystem
- reduce differing behavior in cf_get_file_list*() variants
- refactor case-sensitive directory handling to work everywhere it's needed

clean up some inconsistencies in cfilesystem

---

code/weapon/weapons.cpp

Thanks to Kestrellius for noticing these little things lol
Laser glows have a differently placed 'tail' position than the regular laser bitmap which should be used.

Correctly position tail for laser head on glows

---

code/missionui/missionweaponchoice.cpp

By specifying a different techroom model, the weapon loadout screen can display a different model than used ingame.
However, when loaded it would also reinitialize the model_subsystems of the ship_info, and thus change the model_num of the subsystems. This causes a bunch of problems down the line. Since the recent change to subsystem rotation handling, a corrupt model_num can just cause straight CTD's on mission start.
This addresses this by not loading the ship_info's subsystems with the techmodel, but a seperate submodel buffer, thus not erroniously overwriting the subsystem data.

Fix Weapon-Loadout-Specific Models

---

code/ai/ai_profiles.cpp
code/ai/ai_profiles.h
code/ai/aiturret.cpp

This the time at which a turret will reacquire a target, maybe finding a new one, maybe re-affirming the current one, etc. If you have very fast missiles and very fast CIWS even 2 seconds can be too long a delay, but potentially comes with performance problems, as the check that it triggers has to search all ships and weapons, and is done per turret.

Expose turret re-targeting delay

---

code/ai/ai_profiles.cpp

I don't know why all the other flags are lowercase, but they are and I forgot, and this will bother me unless I fix it.

Uncapitalize "Turret" in turret target recheck time

---

code/lighting/lighting_profiles.cpp

since the content of the name these are matched against is converted to lowercase, the builtin names also need to be lowercase to be able to match.

Fix the Tonemapper strings

---

code/mod_table/mod_table.cpp

The game setting table allows  modders to set the default noise levels for new pilots, but the game did not actually use the values set in mod table. This PR fixes that and adds safety range checks, too. Tested and works as expected.

Fix Default Sound Levels in Game Settings Table

---

code/scripting/api/libs/graphics.cpp

This was a request I got recently. The reason they are new functions rather than some boolean flag in the original ones is just that it'd make the original function too unwieldy.  
This is especially useful with the recent feature that allows drawing rotated images, since the rotation axis is the image's center. 
I couldn't find a good way to avoid duplication in the `drawImage` functions.

Add functions to draw rectangles and images by passing the center position 

---

code/asteroid/asteroid.cpp
code/asteroid/asteroid.h
code/mission/missionparse.cpp
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

Instead of throwing asteroids at the first big ship you find in the field, the FREDder can specify an arbitrary list of ships that are the sole targets for asteroids, which disables the retail behavior. Only the engine side changes, as FRED currently no means to populate the requisite "$Asteroid targets" field in the mission file, which hopefully @Goober5000 can help with.

Allow for arbitrary asteroid targets in missions

---

code/mission/missionbriefcommon.h
code/mission/missionparse.cpp
code/missionui/missionbrief.cpp
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp
qtfred/ui/BriefingEditorDialog.ui

Implement #3757 Adding a new optional line to the missionfile for a briefing icon $Closeup label after $label. Currently has to be added in text editor though i have added a field in QTFred's briefing editor for when someone completes it.

Substitute Ship Label

---

code/parse/sexp.cpp
code/parse/sexp.h
code/parse/sexp/LuaSEXP.cpp
code/scripting/api/objs/oswpt.cpp
code/scripting/api/objs/oswpt.h
code/source_groups.cmake

This finally remedies my biggest annoyance with LuaSEXPs: It is now possible to specify OSWPT-types as arguments, allowing for custom sexps to work for much broader situations.
As convenience functions, it's not only possible to access OSWPT data directly, but rather supply a function that should then be applied to every ship (or parse object) this OSWPT applies to, allowing for the creation of easy "do n for all Ships/Wings/Teams" SEXPs with little effort.
The newly added argument types are called the following (they include the oswpt prefix to signify that all of these return an OSWPT object, and just differ in how they can be populated in FRED), and are generally equivalent to their built-in SEXP counterparts:
```
ship+waypoint
ship+wing
ship+wing+team
ship+wing+ship_on_team+waypoint …
```

Expose OSWPT to Lua and allow for LuaSEXP argument

---

code/cfile/cfilesystem.cpp

Fixes bug in the old dynamic cf_get_file_list() introduced by the
3734 PR. That PR used SDL_strlcpy() to copy the filename which
always null terminates the string, but was only given the length
of the string itself as the available space, so the last character
was removed.

fix file name getting trimmed in cf_get_file_list()

---

code/globalincs/systemvars.cpp

By default, new pilots have `Model` and `Nebula` detail only set to 4/5 (all others are on 5/5). Furthermore, clicking `Very High` on the model presets options still does not increase the `Model` or `Nebula` detail, as they remain at 4/5. This occurs with making a new pilot in retail, along with making new pilots in mods with a game settings default detail level of `Ultra`.
Simply changing the default values in the code for `Model` and `Nebula` detail to match the other detail levels is the easiest and cleanest solution IMO. I would be happy to alter this though to use a game settings table flag instead, if that is preferred.

Set Default Detail Levels to be Consistent at Ultra Settings

---

code/ship/awacs.cpp

Fix crash related to PR #3634 changes due to when the awacs info is setup. Awacs is setup/updated on each game frame. However this happens after multi packets are processed that frame, so a client can send related info to the server before the server has had the chance to init awacs causing a crash due to the vector being empty. This should provide a safety catch for when such an out of order issue occurs.

fix multi awacs crash due to code init order

---

code/bmpman/bmpman.cpp
code/bmpman/bmpman.h
code/ship/ship.cpp

Log when falling back to loading a thruster texture as a static image instead of animated, and log when loading the texture fails entirely.
Fixes issue #3644.

Clarify logging when loading thruster textures as static images

---

code/mission/missiongoals.cpp
code/mission/missiongoals.h
code/mission/missionparse.cpp
fred2/campaigntreewnd.cpp
fred2/fredview.cpp
qtfred/src/mission/Editor.cpp

1) Sync formatting of each place SEXP errors are reported
2) Add error location (event or goal) if possible when mission is loaded
Note that the two FRED error dialogs already indicate the event or goal.

improve SEXP error handling a bit

---

code/model/modelanimation.cpp
code/model/modelanimation.h
code/network/multi.h
code/network/multimsgs.cpp
code/network/multimsgs.h
code/object/object.cpp
code/parse/encrypt.cpp
code/parse/encrypt.h
code/weapon/weapons.cpp

This PR changes the multi message for the Animations to use netcode signatures instead of PMI ID's.
At the same time, protection against nonexistant animations or objects was added.
Furthermore, animation ID's are now only a function of a unique animation name and a name of whatever class this animation is defined for. This means, that for an animation that has the same name and is used in the same ship or weapon class, the id will be the same as well, making it usably stable for multi.
Closes #3836 
Small logging fixes to close #3842 as well.

Animation Rework Phase 3 - Fixes for Multi

---

code/localization/localize.cpp
code/localization/localize.h

One of my XSTR and localization fixes from last year did not account for the presence of custom languages.  This PR uses the correct threshold and also adds a warning in case some mod really wants to define more than 6 additional languages.

fix language indexing for custom languages

---

code/hud/hudtarget.cpp
code/hud/hudtarget.h
code/ship/ship.cpp
code/weapon/beam.cpp

It was completely ignored before. Just to be sure, I checked retail and no secondary had any energy consumption listed, nor did any of the high-profile mods I checked, which makes sense, since usually people will use retail weapons as a base.
Additionally, the weapon energy bar will now only flash if the weapon in question is actually starved of energy. Being out of missiles, or ballistics with no ammo will not flash the energy bar (ballistics used to do so even if they were merely out of ammo).

Make secondaries use $energy consumed

---

code/object/object.cpp

In #3720 there was some code which fired stream weapons for all ships, and then set `has_fired` to 1 (regardless if it even had any stream weapons), thus preventing the code removed in this PR from ever triggering and stopping primary fire. After it was removed  this would trigger every time, thus stopping weapons with submodel rotation rate requirements from ever reaching them. The code can be safely removed as both players and AI handle stopping their own primary fire on their own.
Fixes #3848

Fix weapons with submodel rotation firing

---

code/hud/hudreticle.cpp

I'm not going to pretend like whoever wrote this "should've" known this, because this is pretty esoteric, but since phys_info is subject to runtime change through scripting, the HUD should display based on that, rather than the static info from the table.

Use phys_info for max AB speed display instead of ship_info

---

fred2/eventeditor.cpp

~~This PR also establishes the semantics that after the Events Editor is closed for any reason, `Event_editor_dlg` is always deleted.~~
~~Note that the behavior being added to `OnCancel()` already exists in `OnClose()`.~~
Clarify why the function `event_editor::OnCancel()` is empty.

Add comment on why event_editor::OnCancel() is blank

---

code/ship/awacs.cpp
code/ship/awacs.h

Awacs team arrays only need to be initialized once but were expanded by Iff_info.size() every second of a mission and never cleared.
(Also includes cleanup)

set up awacs team arrays just the once

---

code/object/objcollide.cpp
freespace2/freespace.cpp

Some object collision info can grow significantly between missions but was only cleared at shutdown. This moves it to level close instead to keep things from getting out of hand.

reset object colliders after each mission

---

code/cfile/cfilesystem.cpp

The cfilesystem cleanup PR (3734) failed to take pathtype extension filtering into account when indexing loose files. This adds back that functionality to prevent extra/unknown files from being indexed.
Fixes #3863

take pathtype extensions into account during file indexing

---

code/mission/missionparse.cpp
code/parse/sexp.cpp
code/parse/sexp.h

Some SEXP errors, although they indicate real problems, will not prevent the mission from running.  Add these as exceptions.  Implemented per requests from users of Blue Planet and Solaris.
Supersedes #3870.

make certain SEXP errors nonfatal

---

code/hud/hudtargetbox.cpp
code/scripting/api/objs/weapon.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

A weapon fired without a lock has a proper `target_sig` but no `homing_object` and will not home, so when setting the target of a weapon through scripting check for that case as well, to prevent edge cases where a weapon might not allow one to set the target manually through scripting.
All the rest is adding a clarity function for how 'no homing object' is represented, which has always confused me because it looks weird. Some odd pointer shenanigans, but it works.

Fix scripted setting of weapon targets

---

code/def_files/data/effects/tonemapping-f.sdr
code/graphics/opengl/gropenglpostprocessing.cpp
code/graphics/util/uniform_structs.h
code/lighting/lighting_profiles.cpp
code/lighting/lighting_profiles.h

Moved the PPC tonemapper intermediate calculations to C-side to clean up shader compatibility with older versions of opengl. Followup to #3838

PPC tonemapper values followup

---

code/lighting/lighting_profiles.cpp

Further testing of the PPC shaders revealed serious visual errors with certain settings, this adds some safety boundaries from John Hable's implementation. I have not been able to reproduce the corruption issues with these changes in place.

Added ppc calculation initial value bounding and calculation fixes

---

code/math/vecmat.cpp
code/math/vecmat.h
code/model/modelanimation.cpp

Turrets will now correctly calculate their default position based on POF'd rotation axis. Previously, this could cause problems.
This now also properly supports the case if a turret has been rotated off-axis by an animation, and will set the turret angle for AI and stuff to the closest possible angle on the rotation axis.
Should fix #3876

Animation Rework Phase 3, Turret fix

---

code/particle/util/ParticleProperties.cpp

Previously the `bm_page_in_aabitmap` call in `ParticleProperties::pageIn()` used -1 as the number of frames. It seemed particles with more than 1 frame still worked correctly, but likely prevent preloading of particles. This PR fixes that to use the actual number of frames. Fixes #3706  
Thanks for @notimaginative for catching this. Would be useful to have review by @asarium even though it's just a few lines.

Fix Particles `pageIn()` to use actual number of frames

---

code/bmpman/bmpman.cpp
code/bmpman/bmpman.h
code/cfile/cfilesystem.cpp

Fix a broken cfile optimization and tweak bm_load() so that it can take advantage of existing optimizations when searching for files in a known path type.

file loading performance fixes

---

code/hud/hudtarget.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

In FS2, the HUD will automatically target the first turret on any BIG or HUGE ship.  In FS1, this did not happen.  This adds a flag to disable the new behavior.
The change is needed because the scan view cone is significantly constrained when any turrets or subsystems are targeted.  This makes Playing Judas quite a bit more difficult than it was designed to be.

add game_settings flag to not target turrets

---

code/particle/util/ParticleProperties.cpp

It turns out the particle preloading fix revealed a long standing bug in the particle `pageIn()` function--it should be calling `bm_page_in_texture()` instead of `bm_page_in_aabitmap()`. It's been wrong the entire time and we didn't notice because of the frame bug, which was fixed in #3884. Without this fix, when it's preloaded it locks the image as 8-bit, when it force loads it's 24-bit. 
Tested and works as expected. Fixes #3890. It also has the added benefit of making the code cleaner because the `bm_page_in_texture()` loads the frames if none are specified. 
Massive thanks to taylor for spotting this!

Fix Particle `PageIn()` (V2)

---

code/hud/hud.cpp

The timestamp fix/cleanup in #3878 revealed a longstanding bug with HUD gauge timestamps--the timestamps were never set to something valid later.
This is a widespread issue in the code (beyond just hud.cpp), fortunately Goober is modifying the timestamp code to accommodate invalid timestamps.
Tested and works as expected. Fixes #3894.

Revert timestamp changes for HUD

---

code/parse/sexp.cpp

Change the threshold logic to return the correct elements from the beginning of the list, not the end.  Fixes #3896.

fix first-of to return the correct arguments

---

code/pilotfile/csg.cpp

Use correct version var when inside CSG stuffs.
*LOVE* that action at a distance!

Fix 3892 Amendment

---

code/cfile/cfilesystem.cpp

Remove limit on number of roots and files supported by cfilesystem.

make cfile root and file blocks dynamic

---

code/graphics/2d.h
code/graphics/software/font.cpp
code/missionui/chatbox.cpp
code/network/multi_pxo.cpp
code/network/multiui.cpp

Multiplayer screens such as PXO lobby, chat boxes, and multi-game setup screens had hard coded values for the number of lines to display. These would only work correctly with the default .vf font01 from retail. If a mod or user used a TTF or other .vf font than text would spill over. This PR makes these values take into the account the font used.
Tested and works as expected with TTF fonts and the retail fonts.  Marking as draft to see what others think.

Fix text overflow on multi-related screen

---

freespace2/freespace.cpp

This appears to be a bug present since the initial lightshafts code was added, while a check is made to see if the sun is occluded, the `||` conditional short circuits, and causes lightshafts to always be rendered:
Had a quick discussion with @TRBlount and @EatThePath and we all agreed that the original intention was probably to block lightshaft rendering when the sun was occluded, so `&&` would make more sense.

Fix shadow check on lightshafts

---

code/lab/dialogs/render_options.cpp
code/lab/renderer/lab_renderer.cpp
code/lab/renderer/lab_renderer.h
code/lighting/lighting_profiles.cpp
code/lighting/lighting_profiles.h

This punches a bunch of holes in the abstraction of light profiles that I will want to revisit when I get light profiles fully featured, but this is too useful for previewing different settings to sit on until then.

Add tonemapping options to lab render settings

---

code/math/vecmat.cpp

In #3891, for the handling of a zero case in ``vm_closest_angle_to_matrix``, the sign of a variable should have been considered for calculating the angle. Thus, some turrets were flipped by 180 degrees.

Fix turrets sometimes being backwards

---

code/controlconfig/controlsconfig.cpp
code/controlconfig/controlsconfig.h
code/pilotfile/csg.cpp

Preset identification should only be invert agnostic when reading a CSG<7 file, for all other uses of control_config_get_current_preset(), it should be exact equality with the preset.
Agnostic equals was added by @Goober5000 to address an issue with LUA scripts that attempted to invert axes controls.  In addition, there was a bug where a tester was switching back and forth between pre-Controls5 test builds only to have the conversion process continously trigger, because the CSG files did not save the invert flag and its generated preset was not exactly equal with the preset generated by his player file or current bindings.  PLR files did have the invert flag in them, however.
!!Notice!! I don't have time right now to do a full build test nor a run test, so please test this before merging. …

Fix #3901: Inverted Controls Don't Save

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aiturret.cpp

Previously, turrets with ammo would end up firing one extra shot, resulting in a -1 ammo.
This was because of the check `ammo[bank_to_fire] >= 0`, in `aiturret.cpp`. This PR adds an AI flag to have the turret only fire if the ammo is greater than 0 (`ammo[bank_to_fire] > 0`), as opposed to greater than or equal to 0.
Tested and the flag fix works as expected.

Add AI to Fix Negative Turret Ammo

---

code/controlconfig/controlsconfig.cpp
code/controlconfig/controlsconfigcommon.cpp

Move dynamic XSTR stuff out of `controlsconfig.cpp` and move it into `controlsconfigcommon.cpp`.
- Needed because these strings are used in places other than the controls menu.

Fix issue #3912

---

code/mission/missionparse.cpp

Previously, multiplayer missions with wings with waves would incorrectly set the `net_signature` of ships in the initial wave. The code is supposed to only set the `net_signature` if it was past the initial wave. This is because original ships in the wave have their `net signature` set at mission parse. (Note, the check `wingp->current_wave > 1` is also used in the docking code to check for initial wave or not status).
This PR fixes that and has been confirmed to work via multiplayer tests.

Fix incorrect net signature for wave ships

---

code/ai/aicode.cpp

The previously added flag `Fighterbay_arrivals_use_carrier_orient` (#3698) incorporated the parent ship's `rvec`, which greatly helped align emerging ships from fighter bays. In parent some ships though, emerging ships still showed a `uvec` that did not match the parent ship (such as FotG's Star Destroyer). This PR allows the `Fighterbay_arrivals_use_carrier_orient` flag to take parent `uvec` into account.
Note, that departing the mission into a bay already has code to ensure a `wheels-down` landing.
PR is tested and works as expected/fixes `uvec` issue.

Allow AI flag for bay orientation to account for parent `uvec`

---

code/libs/ffmpeg/FFmpegHeaders.h

```
FFmpeg commit e67e02d15672 [1] dropped avcodec.h from avformat.h includes hence
add an include for it to fix build after that commit.
[1]: https://github.com/FFmpeg/FFmpeg/commit/e67e02d15672a87da1b0566e197a1e19dc7e1e33
```

FFmpeg deprecations fix for FFmpeg >= 5

---

code/gamesnd/eventmusic.cpp

The timestamp fix/cleanup in #3878 revealed a longstanding bug with music timestamps--the timestamps were never set to something valid later.
This is a widespread issue in the code, fortunately Goober is modifying the timestamp code to accommodate invalid timestamps.
Fixes #3929.

Revert timestamp change for event music

---

code/ai/aicode.cpp

For a long time, bay door animations would not trigger if the player was arriving from the bay as the the only ship in the wing. This was fixed by adding a check for the player. This check uses the `Player_obj` to check if the ship is as player, which does not work on standalones since the `Player_obj` is always the Standalone Ship.
This PR changes the check to check if the flag `Player_ship` is set, which is a common strategy used to make these kinds of checks work on standalones.
Tests show the old behavior still works as expected (including sole-player arrivals, player with other ships, and only AI ships).

Fix Bay Door Animations for Multi and Lone Player Ship

---

code/bmpman/bmpman.cpp

The file used by bmp_load()/bm_load_animation() is a hardcoded interface image on standalone servers. If the value of dir_type isn't ALL or INTERFACE then it can't find the image. For ship textures this can cause primary weapon hits to not register on the server.

fix missing texture bug on standalone

---

code/gamesnd/eventmusic.cpp
code/gamesnd/eventmusic.h
code/io/timer.cpp
code/io/timer.h
code/menuui/credits.cpp
code/network/multi.cpp
code/popup/popup.cpp
code/scripting/api/libs/mission.cpp
fred2/fredstubs.cpp
freespace2/freespace.cpp
freespace2/freespace.h
qtfred/src/fredstubs.cpp
test/src/test_stubs.cpp

Previously, the game used a dead-reckoning system for measuring time, where several time counters were incremented as long as time was running.  This unfortunately has no way to synchronize time in the long term, and therefore in-game time will tend to run faster or slower than real time by a few percent, depending on various factors.
This PR redesigns the timestamp system to use the SDL time counter which will always keep it in sync with real time.  However this necessarily involves a bit of clever handling when the game is paused and unpaused.  It also revealed several minor bugs in several places in the code where timestamps were handled.
~~This PR is currently in draft status until the design can be updated to handle time compression.  In all other respects it should be working.~~ …

convert the FSO timestamp system to use SDL time

---

code/missionui/missioncmdbrief.cpp

Add a logging statement to let modders know that the command briefing is deliberately using, or not using, scroll buttons.
Fixes #3550.

log whether command briefing is using scroll buttons

---

fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

Since `sexp_list_item::text` is an `SCP_string`, these `strdup()` calls are unnecessary and are leaking memory.
For context, these objects are used to populate the right-click menu options for, e.g., Replace Data.

Remove unnecessary/leaky strdup() calls in sexp_list_item in FRED/QtFRED

---

code/graphics/2d.cpp
code/model/modelinterp.cpp
code/network/multi_fstracker.cpp
code/network/multi_obj.cpp
code/network/multi_obj.h
code/network/multi_portfwd.cpp
code/particle/ParticleManager.cpp
code/particle/effects/SingleParticleEffect.cpp
code/particle/particle.cpp
code/weapon/trails.cpp
code/weapon/weapons.cpp
freespace2/freespace.cpp

Various fixes and optimizations for standalone servers, plus minor general fixes.
- reduces memory usage for standalones 35-40 MB by not initializing unneeded stuff
- fix crash on standalone reset if level has never loaded
- fix small portfwd memory leak

Standalone fixes/optimizations

---

code/cmdline/cmdline.cpp
code/cmdline/cmdline.h
code/fireball/fireballs.cpp
code/fireball/fireballs.h
code/fireball/warpineffect.cpp
code/mission/missionparse.cpp
code/mission/missionparse.h
code/parse/sexp.cpp
code/parse/sexp.h
code/ship/ship.cpp

Set the flag for the Knossos warp effect being used when the effect is part of the normal warpin/warpout without involving the Knossos device.
Change the flag from `int` to `bool` and tweak a few things.
Also make sure the warp model is used if it is explicitly specified in the fireball tbl.
Fixes #3917.

TBP warp fix

---

fred2/sexp_tree.cpp
fred2/sexp_tree.h
qtfred/src/ui/widgets/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.h

Follow-up to PR #3940 to remove `sexp_list_item` functions `add_data_dup()` and `set_data_dup()`, which are no longer needed.

Remove _dup() functions from sexp_list_item in FRED and QtFRED

---

code/missionui/missiondebrief.cpp

Training missions don't save kills so make sure that we don't try to back out kills by mistake when replaying a training mission.
Fixes #3916

fix training mission stats bug

---

code/cmdline/cmdline.cpp
code/cmdline/cmdline.h
code/controlconfig/controlsconfig.cpp
code/io/timer.cpp
code/io/timer.h
fred2/fredstubs.cpp
freespace2/freespace.cpp
qtfred/src/fredstubs.cpp
test/src/test_stubs.cpp

If a breakpoint is hit in the code, the SDL time will keep running even though FSO doesn't realize things are effectively, if not actually, paused.  Detect this situation and adjust the timestamp offset to compensate.

accommodate elapsed time during debugging

---

code/hud/hudsquadmsg.cpp
code/hud/hudsquadmsg.h
code/io/keycontrol.cpp
code/mission/missionparse.cpp
code/mission/missionparse.h
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/ship.h
fred2/fredview.cpp
fred2/ignoreordersdlg.cpp
fred2/management.cpp
fred2/missionsave.cpp
fred2/sexp_tree.cpp
fred2/shipeditordlg.cpp
qtfred/src/mission/Editor.cpp
qtfred/src/mission/dialogs/PlayerOrdersDialogModel.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.h
qtfred/src/mission/missionsave.cpp
qtfred/src/ui/dialogs/ShipEditorDialog.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

Previously, possible player orders were stored redundantly in three separate, fixed-size arrays: ``Comm_orders``, ``Sexp_comm_orders``, and ``Player_orders``.  This PR does away with these and creates a new ``Player_orders`` vector, allowing for a dynamic amount of player orders. In preparation for eventually changing up player orders in such a way that the old ID's are removed and not based on bitfields, thus allowing for more than 32 different ones, ships now store player order acceptance as sets of the index of the order in the Player_orders vector. 
This is needed to eventually facilitate LuaAI, a feature that allows a scripter to add AI logic based on Lua which can be added both by SEXP, as well as made available as a player order.
~Still needs testing in addition to a review:~ …

Clean up Player_orders

---

code/ai/aicode.cpp
code/model/model.h
code/model/modelread.cpp

By anchoring a dockpoint to a submodel, the dockpoint will move when the submodel moves.  Historically this has been done by inspecting the path associated with a dockpoint, but this method will not work if there is no path or no rotation mode specified.  Here is an alternate method that allows the submodel to be specified explicitly through a dockpoint property.

allow dockpoints to be anchored to submodels explicitly

---

code/io/timer.cpp

The `Timestamp_microseconds_at_mission_start` variable should not, in fact, be adjusted when the timer counter variables are adjusted.
Fixes #3946.

fix arrival delays and other mission time wonkiness

---

code/parse/sexp.cpp
code/scripting/api/objs/vecmath.cpp

1) Fix set-scanned and set-unscanned to take multiple arguments as designed.
2) Fix documentation on the "perturb" scripting functions.
Fixes #3951

some small fixes

---

code/cmdline/cmdline.cpp
code/cmdline/cmdline.h
code/network/multi_fstracker.cpp
code/network/psnet2.cpp

Add cmdline options to help deal with connectivity issues over IPv4/IPv6. This allows the user to set a preference for either IPv4 or IPv6 which will be used for DNS lookups. Both IPv4 and IPv6 still work normally however, allowing personal connection overrides and preventing a broken psnet setup.
Also now allows PXO data validation for mod ident to fall back to a different IP version if the first attempt times out.

add IP version preference troubleshooting options

---

code/gamesnd/eventmusic.cpp
freespace2/freespace.cpp

A few assorted fixes for timestamps:
1) The pre-player delay should be fast-forwarded by 1/4 second per frame regardless of time compression
2) If time compression is very slow, there could be a 0-millisecond change in timestamps, so don't adjust this
3) Properly handle a change in soundtrack that occurs during a mission, not just when the mission is parsed

some small timestamp fixes

---

code/model/modelanimation.cpp
code/model/modelanimation_segments.cpp

As discovered by MjnMixael, triggering an animation in instant mode in reverse can cause problems, notably with a serial segment as well. The fix is simple enough.

Fix reverse instant trigger edge case

---

code/math/ik_solver.cpp
code/math/ik_solver.h
code/math/vecmat.h
code/model/modelanimation.cpp
code/model/modelanimation.h
code/model/modelanimation_moveables.cpp
code/model/modelanimation_moveables.h
code/model/modelanimation_segments.cpp
code/model/modelanimation_segments.h
code/source_groups.cmake

This PR introduces an animation segment type used to combine multiple submodels into a chain which can be controlled by inverse kinematics.
Allows for each joint to have a specified rotation constraint, as well as to target a specific orientation with the end effector.
Implements the FABRIK algorithm with additions for constraints and end effector rotation.
The hinge constraint _could_ cause certain cases where FABRIK doesn't properly converge, but these'd need to be investigated in the wild when found.
As a side note: Apart from the outstanding translation module by Goober (for which animation support already exists), this is the final thing on my ToDo for animations. So unless someone has more feature requests, the overhaul can be considered basically complete with this PR.

Inverse Kinematics for Animations

---

code/mission/missionparse.cpp
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

#3963 notes that cargo icons do not save/work. I'm not sure why the code was not present to use cargo icons, but this PR adds it back in. If there was a deliberate decision to leave out that code, I'm happy to discuss/close. Tested and works as expected. Fixes #3963

Enable `Use Cargo Icon` for briefing icons

---

code/model/model.h
code/model/modelread.cpp
code/ship/ship.cpp

There are a few related improvements here:
1) Add a new function for iterating over the submodel hierarchy
2) Add a counterpart to the `subobj_num` field so that a submodel can refer to its ship_info subsystem
3) Update `ship_model_replicate_submodels` to replicate all movable submodels, even the ones that aren't associated with subsystems
Fixes #3967

replicate submodels that aren't associated with subsystems

---

fred2/fredrender.cpp
qtfred/src/mission/FredRenderer.cpp

The `fredhtl_render_subsystem_bounding_box` function only handled one level of submodel positioning, which worked for turrets but not more complicated submodel stacks like the Ma'at.  This properly handles all submodels in the hierarchy.
Fixes #3971.

use the whole submodel hierarchy in FRED

---

code/math/vecmat.cpp
code/model/modelanimation.cpp
code/model/modelanimation_moveables.cpp

1. Some turrets had wrong initial orientations in mission only. This is fixed by removing the errors from ``vm_closest_angle_to_matrix``.
2. Now sets the Can_move flag for all submodels that might be animated by an animation
3. Properly set canonical_prev_orientation for collisions and others
4. Fix moveables flickering when updating

Various Animation Fixes

---

fred2/management.cpp

The new animation system sets submodel initial positions on ship creation, but FRED was also indirectly setting them by calling the techroom method.  Initial positions will not work correctly if they are set twice.

fix initial positions of submodels in FRED

---

code/controlconfig/controlsconfig.cpp
code/controlconfig/controlsconfig.h
code/controlconfig/controlsconfigcommon.cpp
code/pilotfile/plr.cpp
code/scripting/api/objs/controls.cpp

Treating both bindings together will fail when a player has one binding inverted but the other uninverted.  This was complicated by the dual-binding method mysteriously delegating to the single-binding method in certain cases.  This change removes the dual-binding methods altogether and explicitly handles the bindings individually.  It also adds additional scripting VIRTVARs for all current use cases.

handle primary and secondary inversion explicitly and independently

---

code/model/modelanimation.cpp
code/ship/ship.cpp

When a ship is initialized from a template _and_ has a display name, previously the ship class name was not properly copied to the animation system for multi-hashing, turret lookup, and so far.
This remedies this _and_ adds robustness and performance by using the new pmi objnum to find the shipclass for turret lookup instead of a string search

Fix Animation edge case for turret lookup with template and display name

---

code/ai/aicode.cpp
code/asteroid/asteroid.cpp
code/debris/debris.cpp
code/model/model.h
code/model/model_flags.h
code/model/modelanimation.cpp
code/model/modelanimation_segments.cpp
code/model/modelcollide.cpp
code/model/modelread.cpp
code/object/collideshipship.cpp
code/object/objcollide.cpp
code/object/objcollide.h
code/object/object.cpp
code/ship/ship.cpp
code/ship/shipfx.cpp

Mostly renaming of fields and functions, and moving some modelread sections into functions.  This reorganization will put the code on a better footing for the model translation feature.  No model translation code is included yet, and there should be no change in functionality.

refactoring in preparation for model translation

---

code/hud/hud.cpp

Previously, the damage display gauge only showed the integrity for subsystem types. This was fine if there were a 1:1 match, with each type only having 1 subsystem. If there were more than one subsystem of a given type though, it would not display accurate information to the player.
Fixed Version
This PR sets the displayed subsystem integrity to that actual specific subsystem, not the aggregate. Tested and works as expected (screenshot attached) and fixes #3982.

Fix Damage Gauge Display

---

code/model/model.h

The POF format relies on some of the IDs being the values they are, so this change restores the original numbers.

regression fix for rotating submodels

---

code/network/multi_obj.cpp

So if your ping somehow gets up to ~500ms, and you try to shoot a primary shot or dumbfire missile, your shot might trigger an assert, because the code was previously letting in shots that were a little bit too old. So make sure that if the server is about to enter that frame index that the shot would have been mapped to, reject the shot.

Fix edge case rollback crash

---

code/camera/camera.cpp
code/camera/camera.h
code/math/vecmat.cpp
code/math/vecmat.h
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

A few fixes for the camera code...
1) When pointing the camera toward a target, take into account the host's orientation.  Use a game_settings.tbl flag to control this.
2) When using a submodel to host the camera, correctly calculate the submodel orientation.
Fixes #3889

point camera correctly when using set-camera-facing

---

code/weapon/weapons.cpp

This should allow the client to cull missiles with no lifetime left once again. 
Closes #3957 
Testing from FotG seems to confirmed that this fixes the issue.

Partially revert 3313 to fix missiles never dying

---

code/hud/hud.cpp
code/scripting/api/objs/object.cpp

It is very valuable for custom HUD gauges to be able to show/use the IFF color of any given object. Previous scripting solutions were limited and did not account for traitor status, varying team combinations (i.e. TvT multiplayer), and other cases.
This PR allows scripters to get the IFF color of a given object properly, as it uses the same method that retail HUD gauges use. It also allows HUD scripts to be updated to properly work in the aforementioned cases. For example, this will fix FotG's custom HUD gauges in multiplayer in TvT and Dogfight missions. 
Also, it turns out there was already a function `hud_get_iff_color` defined in `hud.h`. It was never used though, as `hud_set_iff_color` both got the color then set it. I've added the color getting to the `get` function and the setting …

Fix limitations of GetColor script function

---

code/model/modelanimation_moveables.cpp

This moveable was previously working in relative space, which is incorrect.
Moveables must operate in absolute space to be predictable when the movement gets interrupted before the old movement finishes.

Fix Axis Rotation Moveable

---

code/io/keycontrol.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h
code/network/multimsgs.cpp
code/object/collideshipweapon.cpp
code/object/collideweaponweapon.cpp
code/weapon/shockwave.cpp
code/weapon/weapon_flags.h
code/weapon/weapons.cpp

There is a bit of code that detonates a missile if it misses impacting on a subsystem.  On Nyctaeus's Arachnas model, missiles could reach the center point of the main beam turret submodel without actually hitting any part of the submodel.  The fail-safe code would set the missile to detonate in that case, but on low-FPS systems the weapon would be able to actually hit the turret before it detonated.  On high-FPS systems, there is a clean miss.
This reworks the code to delay the missile detonation until it reaches the other side of the submodel, so it has time to hit some other part of it.  It also reduces the detonation time from 1/100 of a second (which is more than one frame on 120 FPS systems) to 1/1000 of a second (which is always less than one frame).

fix missile detonation for computers with high FPS

---

code/camera/camera.cpp

As @Baezon figured out, when a host exists, `get_info` will return the orientation relative to the host.  When there is no host, `get_info` returns the absolute orientation.  In the latter case, `set_rotation_facing` does not need to do extra calculations to find the delta orientation.
Also remove a redundant `if` check.
Follow-up to #3989.

fix the camera flicker in the lab

---

code/math/ik_solver.cpp

Don't ask me how I didn't notice this in the tests, but IK has had a matrix multi order bug during matrix localization.
This fixes it, and this time I am sure that it's correct, both on paper and with tests...

Fix IK rotation localization

---

code/parse/sexp.cpp

1) Remove operator caching from `is-cargo-known-delay`, `cap-subsys-cargo-known-delay`, and `has-been-tagged-delay` so they can be used with `when-argument`
2) Note idiosyncrasies of `and-in-sequence` in SEXP help
3) Document logic for inverting known-true and known-false in `sexp_not`
Should fix #4013.

improve robustness of sexp operators

---

code/parse/sexp.cpp

A couple quality-of-life improvements for event logging:
1) Indent the SEXP operators according to their depth in the node tree
2) Add newlines between variables and containers

event logging tweaks

---

code/popup/popup.cpp
code/popup/popup.h
code/ui/ui.h

This PR extends the popup_input() function to allow users to set an arbitrary whitelist of non-alphanumeric characters (anything that isn't a-z or 0-9, and isn't a control character), and sets the default whitelist to include period ( . ), underscore( _ ), and minus( - ).
Affects the input boxes used for squadwars matchmaking code, controls preset naming, and the mainhall mission jump-to-mission  cheat.
Fixes #4005

Restrict allowable characters for preset names

---

code/controlconfig/controlsconfig.cpp
code/cutscene/movie.cpp
code/io/cursor.cpp
code/io/cursor.h
code/io/timer.cpp
code/io/timer.h
code/menuui/credits.cpp
code/menuui/mainhallmenu.cpp
code/menuui/optionsmenu.cpp
code/menuui/optionsmenumulti.cpp
code/mission/missionparse.cpp
code/missionui/missionbrief.cpp
code/missionui/missionbrief.h
code/missionui/missiondebrief.cpp
code/missionui/missionscreencommon.cpp
code/missionui/missionscreencommon.h
code/missionui/missionweaponchoice.cpp
code/missionui/redalert.cpp
code/network/multi_pxo.cpp
code/network/multiui.cpp
code/network/multiutil.cpp
code/network/stand_gui.cpp
code/popup/popupdead.cpp
code/ui/button.cpp
code/ui/ui.h
code/utils/id.h
fred2/fredstubs.cpp
freespace2/freespace.cpp
qtfred/src/fredstubs.cpp
test/src/test_stubs.cpp

This adds `UI_TIMESTAMP` which is a real-time timestamp not subject to time compression or pauses.  It is meant to be used in the UI and in other situations where the code needs the actual elapsed time.  It also uses the "strong typedef" pattern pioneered by `gamesnd_id` so that they cannot be mixed up with integers nor interchanged with standard timestamps.  (Doing the same thing with standard timestamps would be a good future upgrade.)
Various UI-related timing functions, including briefing, debriefing, and credits delays, as well as button and cursor delays, have been switched over to `UI_TIMESTAMP`.  This fixes #3955.
Additionally, now that timestamps no longer need to run during briefings, the standard timestamp can be kept paused from initialization until mission start.  This fixes …

another timestamp upgrade

---

code/scripting/api/objs/camera.cpp
code/scripting/api/objs/particle.cpp
code/scripting/api/objs/streaminganim.cpp
code/scripting/api/objs/subsystem.cpp

When returning objects, be sure to use `ade_set_object_with_breed`, per the documentation on that function.  This ensures that all relevant subclass information can be used (e.g. for ships, the `.Name` virtvar).
Also fix the return value of streaminganim's isValid() function.

a few scripting bugfixes

---

code/controlconfig/controlsconfig.cpp

Don't nullify axis_out[action] value when using mouse as joy

---

code/actions/types/ParticleEffectAction.cpp
code/actions/types/PlaySoundAction.cpp
code/camera/camera.cpp
code/model/model.h
code/model/modelread.cpp
code/model/modelrender.cpp
code/scripting/api/objs/mc_info.cpp
code/ship/ship.cpp
code/ship/shipfx.cpp
code/ship/shiphit.cpp

Consolidated these functions and replaced the `find_submodel_point_*` functions with their closest `world_find_` counterparts.  (One of those functions may not have actually worked correctly.)  Also use the correct coordinate logic when returning normals from collision info in scripting.
Related to #3985 although not yet a fix for it.

clean up model point/dir/normal/orient functions

---

code/scripting/api/libs/base.cpp

Allows scripters to use the functions `message_translate_tokens` and `sexp_replace_variable_names_with_values`. This is very useful with scripted HUD gauges and scripted messages. Also, fixes #4034.

Expand scripting string functions

---

code/model/model.h
code/model/modelread.cpp
code/scripting/api/objs/mc_info.cpp
code/scripting/api/objs/model.cpp
code/scripting/api/objs/model.h
code/scripting/api/objs/modelinstance.cpp
code/scripting/api/objs/modelinstance.h
code/scripting/api/objs/object.cpp
code/source_groups.cmake

Allow scripts to reference submodels, submodel instances, and model instances.  Currently just a few properties (like Orientation and Radius) can be accessed, but this can be easily expanded in the future.
Also add relevant functions to calculate real-world positions and orientations of rotated submodels.

add scripting support for submodels

---

code/graphics/opengl/gropengltexture.cpp

When switching to a texture as a render target, the code previously performed a check with the driver if the ID for the target texture was a valid framebuffer. This is sometimes a _very_ costly check, causing measureable and occasionally visible microstutter. The way this ID is found however, guarantees us one of two things: It's an ID returned directly from the driver from creating the frambuffer, in which case it's valid anyways, or it's 0 because the framebuffer has been cleared.
We can make use of this by changing the check to only check for the 0 case, since any non-zero number must have come from the driver and is valid, thus allowing us to omit the check to the driver, drastically reducing microstutter in cases where RTT is often used (like RTT HUD gauges, or other special drawing …

Improve costly RTT sanity check

---

code/mission/missionparse.cpp

Make sure the ship registry correctly records these ships as having exited.

fix an edge case for ships destroyed before mission

---

code/model/modelrender.cpp

It's legal for glowpoints to have a zero vector as a normal, apparently, so test for this.

prevent Assert with glowpoints

---

code/controlconfig/controlsconfigcommon.cpp

Set key to -1 and let CCB::take() do the actual binding later on instead of overwriting changes.
Should fix issue #4040

Fix issue #4040

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aicode.cpp

There were two bugs that kept this from working until now:
1) The destination goal point was calculated to take the ship right through the center of danger.  Flipping the vector now takes the ship away from danger as intended.
2) The original AI code did not turn the ship at all.  The new code turns the ship toward its goal point.
The fixed behavior is tied to the new `$fix keep-safe-distance:` flag.

fix the keep-safe-distance AI mode

---

code/popup/popup.cpp
fred2/fredstubs.cpp
freespace2/freespace.cpp
freespace2/freespace.h
qtfred/src/fredstubs.cpp
test/src/test_stubs.cpp

If time is already stopped when a popup is displayed, it should remain stopped when the popup is closed.

fix time resuming when popups are closed

---

code/model/modelanimation.cpp
code/model/modelanimation.h

Previously, using different capitalization for the same submodel in animation definition would cause unpredictable behaviour due to the animation system considering these to be separate submodels, while the rest of FSO would regard them as the same.
This change gets the animation system to also be case agnostic for coherent behaviour even with different capitalizations of submodel names.

Fixed incoherent case sensitivity for animation submodels

---

.github/workflows/build-release.yaml
.github/workflows/standalone-image-workflow.yaml

This PR makes changes to how our build-release workflow is published, along with one other change to the standalone workflow to prevent it from running if done on forks so as to facilitate experiments on forks without spamming up the docker host. (The standalone workflow usually fails anyway if on a fork, at least from my tests).
1. This uses the softprops/action-gh-release action to publish the .zip and .7z of both OS's to the Releases page
2. This makes the windows_zip job continue to run instead of fail-fast whenever it can't publish, allowing the other steps in its job matrix to run and thus allow all .zip and .7z windows packages to form (previously if one windows package failed, then whatever that wasn't zipped was left alone)
3. This stashes the windows .zip and .7z packages as an …

Changes to build-release.yaml

---

code/model/modelread.cpp

Chunk type 0 is EOF and lacks the following int indicating the total chunk size.

Dont try to read chunk size if chunk type is 0

---

qtfred/src/ui/widgets/sexp_tree.cpp

On Windows, there's currently a debug heap assertion failure when trying to use Edit Data.
This change seems to fix it.
I originally thought the issue was with Add Data >> Number/String (hence the branch name) but realized it was actually Edit Data.
I wonder if the issue is `QString`'s implementation of `toStdString()` itself.
Unrelated known issue: when Add Data >> Number is used and the text is left as "number" and the Events Editor is closed with OK, qtFRED doesn't automatically change the value to 0, but if you save/reload the mission, it's set to 0.

Fix qtFRED crash when using Edit Data

---

code/decals/decals.cpp
code/object/collideshipweapon.cpp

The orientation was broken since the engine rendered the decal box in
the direction of the hit normal which meant that the viewer was looking
at a flipped version of the decal texture.
This fixes that by flipping the direction of the decal before passing it
to the GPU.
This also fixes the orientation for weapon decals which previously did
not take the orientation of the weapon that just impacted into account.

Fix render orientation for decals

---

code/ai/aicode.cpp
code/ai/aigoals.cpp

If a support ship's repair goal is removed, abort the rearm.  There is extra cleanup that needs to be done for this goal only.

fix support ships breaking in in-mission jumps

---

code/playerman/playercontrol.cpp
code/ship/shipfx.cpp

1) Don't knock the player out of the warp if the sequence has already moved to stage two.  It breaks the sequence and the game will still end the mission anyway.
2) Remove the Volition code for calculating player speed.  It did not actually affect the speed, but it *did* affect the calculation of warp distance which often caused the player's ship to miss the portal.

two small but important warp fixes

---

.github/workflows/post-build-release.yaml
ci/post/main.py

This should now use the correct version string for both rc and release builds, which affects both Nebula publishing and the forum post title

Fixes the version string in main.py

---

code/model/modelread.cpp

Changing endianess of bsp data must be done before any other
bsp processing

swap bsp data before alignment

---

code/asteroid/asteroid.cpp
code/debris/debris.cpp
code/model/model.h
code/model/modelanimation.cpp
code/model/modelanimation.h
code/model/modelread.cpp
code/object/collideshipship.cpp
code/object/collideshipweapon.cpp
code/ship/shipfx.cpp
test/src/model/test_modelread.cpp
test/src/source_groups.cmake

With the previous animation overhaul, some problems with the collision code came to light.
This PR aims to fix most of the more problematic ones, including:
- Fixes Global -> Local coordinate transformation for nested submodels (prerequisite for latter points)
- Fixes Submodel collisions for nested submodels more than two layers deep
- Fixes Submodel collisions for nested submodels that have moving ancestors
- Fixes Collision physics calculation for submodels with triggered animations (fixes #3985)
- Laid groundwork to follow up to improve the collision physics calculation to more accurately represent submodels with moving ancestors in a future PR

Fix nested and animated submodel collisions

---

code/model/model.h
code/model/modelread.cpp
code/object/collideshipship.cpp

This is the followup for #4065 that redos collision speed and momentum transfer for moving submodels.
It turned out a lot simpler than originally thought, but now properly calculates collision speed for animated submodels, even with moving ancestors or (future) translating submodels. Additionally, steps are taken to drastically reduce the number of accidental tunneling through very fast moving (~100m/s) submodels.

Fix moving submodel collision speed calculation

---

code/model/modelread.cpp

Child subobjects can end up being much larger than detail0, or spill outside of it, resulting in the targeting brackets not actually appearing to contain the whole ship. This is especially common with newer MVPs ships which require chopping up into separate subobjects, which then require awkward workarounds like making sure the detail0 object is still a skeleton around the edge of the ship specifically to avoid this issue. The model header's bounding box includes that of all the children as well for exactly this purpose, so use that instead.

Targeting brackets should use the header's bounding box, not detail0's

---

code/model/model.h
code/model/modelread.cpp

Consider this approach tentative, but *apparently* model collide info does not necessarily fill `hit_normal` even when hits are registered. This happens in the case of a sphere hitting the 'edge' of a polygon (although I'm not convinced a hit normal cant be generated in this case, but this would require a deeper dive), which, at least in my tests, seems to happen a lot with maras and beams for whatever reason. 
Other parts of the code even explicitly check for edge hits and don't check normals.
https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/object/collideshipship.cpp#L336
And, at least for beams, this hit normal is passed directly to the relevant function.
https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/weapon/beam.cpp#L3689
Apparently before, it …

Remove new assert in `model_instance_local_to_global_dir`

---

code/model/modelread.cpp
code/object/collideshipship.cpp

#4067 introduced an issue in which collisions with already rotated turrets would fling about the ships.
This happens because the turrets (and certain other types of dumb rotations) did not properly update canonical_prev_orientation, which would cause their calculated momentum to assume that they rotated to their current position within one frame, making them much faster than they actually were.
In addition to fixing this by making submodel_canonicalize take care of updating canonical_prev_orient, turrets are also explicitly excluded from imparting momentum onto colliders. The reason for this is twofold:
1. Stemming from how momentum was calculated before, turrets were included with an implicit velocity of 0, thus previously not imparting momentum as well. Thus, to keep the same behaviour, …

Fix collisions with turrets causing physics bugs

---

code/graphics/software/VFNTFont.cpp
code/graphics/software/font.cpp
code/mission/missionlog.cpp
code/parse/parselo.cpp

`gr_get_string_size` takes a length parameter, but `split_str_once` was calling it with the position instead.  This led to incorrect results occasionally.  If the incorrect pixel width had the bad luck to be exactly equal to the remaining space, this would cause an infinite loop.  This fixes the bug and adds a bunch of safeguards to prevent a similar situation in the future.

fix off-by-one error in text splitting logic

---

fred2/eventeditor.cpp

PR #3342 would occasionally cause FRED to try to save a message that didn't exist.  Make sure the old saved index doesn't point past the end of the valid message list.
Fixes #3996.

fix message list crash

---

code/model/model.h
code/model/modelread.cpp
test/src/model/test_modelread.cpp

Fixes #4079.
The whole thing is still somewhat expensive, currently taking 2% of frametime for checking turret collision using these functions in very large missions. This is already a magnitude better than the previous version, and should fix most of the noticeable performance hiccups

Improve Performance of Global to Local functions

---

code/model/modelanimation.cpp
code/model/modelanimation.h

Fixes #4081.
The problem was that the initial animations did not set prev_orient correctly, which means that for the first frame, the physics of turrets set with initial type animation is very whacky. This caused the unintended behaviour, as #4065 changed the way collision detection on moving submodels worked in such a way that requires prev_orient to be correctly set.

Fix erroneous collision detection due to invalid canonical_prev_orient on inital-type animated turrets

---

code/localization/localize.cpp

Allow `XSTR` to be used by itself, without implying an `XSTR()` tag.

small XSTR qol improvement

---

code/popup/popupdead.cpp
code/popup/popupdead.h
freespace2/freespace.cpp

Bug #3672 was caused by the dead popup not being cleaned up properly when the player-dead state was left.  Closer examination revealed some possible holes in the cleanup logic - e.g. the game assumed that the mission would proceed to the debriefing but neglected the possibility that it would exit to the main hall.  This consolidates the two dead states and attempts to make the cleanup more robust.
Fixes #3672.

patch some holes in the mission cleanup

---

code/starfield/starfield.cpp

In FRED, deleting all suns and bitmaps should not delete the last remaining background.

patch a background bug in FRED

---

code/parse/sexp.cpp
code/parse/sexp.h

Profiling shows that free_sexp contributes to significant runtime consumption in mods with heavy use of sexps in scripts, especially in missions with lots of sexp nodes. This change removes the need for that looping, cutting about half of the runtime from those sexps from scripts. Given some testing in Blighted and Warmachine with no evident breakage of either scripts or conventional mission logic.

Remove unneeded search of whole sexp node array from free_sexp

---

code/model/modelanimation_moveables.cpp

In certain cases, moveables were not correctly updated and reset.
This simplifies how it's done and relies on the existing animation code, ensuring that the value used is always the canonical value.

Fix edge case wrongly updating moveable

---

code/model/modelanimation.cpp

Small issue with SEXP validation when using moveables:
Due to the way it matched moveables and case arbitration, only lowercase moveables were validated. This now properly lowercases all moveables internally and matches the lowercase version

Fix Moveable SEXP Matching

---

code/ship/ship.cpp
fred2/shipeditordlg.cpp
qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp

1) If a ship has its regular name change, clear the display name
2) When placing ships in FRED, truncate the ship name, if necessary, before creating the default name

fix a few bugs with display names

---

fred2/eventeditor.cpp
fred2/fred.cpp
fred2/fredview.cpp
fred2/fredview.h
fred2/missiongoalsdlg.cpp
fred2/sexp_tree.cpp
fred2/shipeditordlg.cpp
fred2/shipeditordlg.h
fred2/wing_editor.cpp
fred2/wing_editor.h

1) Fixes the ship and wing dialog resizing for both sexp help and arrival/departure cues
2) Restores the sexp help in the Mission Goals dialog, which had been broken since the mini-help-box was added

fix a bunch of FRED dialog problems

---

code/object/objcollide.cpp
code/object/object.cpp
code/object/object.h
code/scripting/api/objs/object.cpp
code/ship/shiphit.cpp
code/weapon/weapons.cpp
fred2/freddoc.cpp

It's theoretically possible for `parent_type` to get out of sync with the parent's type, particularly if the parent is destroyed.  Since the field is almost never used, it can be removed.
Should fix #4105.

remove Object.parent_type

---

code/playerman/playercontrol.cpp

I've been using `LUA_FULL_CONTROLS` in the updated mouse-as-a-joystick script, and it works well, but there's one last small bug that just was found that I'd like to fix. `LUA_FULL_CONTROLS` affects things that beyond just steering values, which has the unfortunate side-effect of also overriding non-steering controls such as cruise percent. It would be less intrusive to use the `LUA_STEERING_CONTROLS`. Unfortunately, `LUA_STEERING_CONTROLS` just sets everything to 0, which I think is a code issue bug that has been around since the LUA controls were added in 2010 here:
(https://github.com/scp-fs2open/fs2open.github.com/commit/2a69aaa23ba0def3dbfb9f566706e7130a33866f).
This PR fixes usage of `LUA_STEERING_CONTROLS`, and in testing everything works as expected (including fixing the cruise …

Fix LUA Steering Control Override

---

fred2/ship_select.cpp

prevent the ship select dialog from crashing if there are too many IFFs

---

code/graphics/software/VFNTFont.cpp
code/graphics/software/font.cpp

Make sure that zero-length strings still get the proper height.
Fixes #4122.  Follow-up to #4071.

Make sure that zero-length strings still get the proper height;  fixes missing whitespace in the credits

---

code/parse/parselo.cpp
code/parse/parselo.h
code/parse/sexp/LuaSEXP.cpp
code/parse/sexp/LuaSEXP.h

Two enhancements:
1) Allow the SEXP help description to take up multiple lines.  Since the parser did not originally use `stuff_string` with `F_MULTITEXT`, this required some creative parsing.
2) Generate the text for minimum and maximum number of arguments.

enhance help text for Lua sexps

---

code/menuui/readyroom.cpp
code/menuui/readyroom.h
code/playerman/managepilot.cpp
code/scripting/api/objs/player.cpp

This hook will be called when a campaign is started for the first time (whether in Player Select or in the campaign room), or is reset.

add campaign start hook

---

code/globalincs/linklist.h

This should allow collections which use the Volition linked list (for example `obj_used_list`) to be iterated using range-based `for` loops.

add a class encapsulation for Volition's linked list

---

code/ai/ai.h
code/ai/aibig.cpp
code/ai/aicode.cpp

Profiling found ai_new_maybe_reposition_attack_subsys accounting for around 13% of runtime in crowded missions. This adds a 1 second delay between checking new points, which takes it to 0% of runtime in those same missions. I have not been able to discern a visible change in ship behavior.

Add delay into ai_new_maybe_reposition_attack_subsys for performance 

---

code/hud/hud.cpp
code/hud/hudbrackets.cpp
code/hud/hudtarget.cpp

Several careful tweaks to improve handling of distance as measured on the HUD.
1) Use `Player_ai->current_target_distance` for rendered HUD gauges which display the distance, because the distance is calculated in `hud_update_frame` (which is called from `game_simulation_frame`) and is used for a couple of these gauges already.  This change makes it all consistent.
1b) Some gauges which depend on distance but do not actually display it (e.g. the lead indicator) still calculate their distance immediately before using it.  I didn't change these because a) the calculation is still correct, even if redundant, and b) there is a small possibility of `hud_update_frame` changing the target after the distance is calculated, so these gauges are guaranteed to have the correct calculation.
2) On …

make HUD target distance consistent

---

code/model/modelread.cpp

The check to not show `-destroyed` submodels is within `model_replicate_submodel_instance`, and that was only called for moveable submodels in the lab. This PR runs it for all submodels now. Tested and fix works as expected.

Fix destroyed submodels showing in Techroom

---

code/parse/sexp.cpp
code/scripting/api/objs/ship.cpp
code/ship/ship.cpp
code/ship/ship.h

the ship-is-visibile sexp is used heavily from inside lua in the popular radaricons script, and evaluating those sexps is unavoidably a heavy performance cost. This function can replace those sexp calls.

lua ship.checkVisibility mimicing sexp ship-is-visible

---

code/model/modelanimation.cpp
code/model/modelanimation.h

This flag allows to use looping animations that are supposed to loop forwards and then pause instead of the typical "trigger, wait, reverse"-animation in engine-internal triggers such as afterburners.

Add 'pause on reverse' Animation Flag

---

code/model/modelanimation.cpp
code/model/modelanimation.h

Fixes #4137.
The animations cache submodel numbers from the model file the first time any ship class animates their submodels. When this first animation was the techroom, where no objnum was present, the lookup would fail and cache an empty matrix, thus breaking the following animations. This PR adds safety to not cache bad values when no subsystem was found, and re-enables submodel lookup by ship_info name as fallback.

Fix techroom turret lookup and make animations more robust

---

code/weapon/weapons.cpp

Collide_remove_weapons being called in weapon_create to recover weapon slots is actively destructive to player experience and almost never recovers slots.  See #4098 for more on that. Instead, simply don't create a weapon in those cases.
Tested on the same scenario as originally prompted #4098 and encountered no player-visible issues.

Removed collide_remove_weapons from weapon_create

---

code/mission/mission_flags.h
code/object/objectdock.cpp
fred2/fred.rc
fred2/missionnotesdlg.cpp
fred2/missionnotesdlg.h
fred2/resource.h
qtfred/src/ui/dialogs/MissionSpecDialog.cpp
qtfred/ui/MissionSpecDialog.ui

This flag is not the sort of thing that should depend on the FREDder, and in any case it probably isn't needed.  So this removes it.

remove daisy-chained mission flag

---

code/ai/ai_flags.h
code/ai/ai_profiles.cpp
code/ai/aicode.cpp

Retail behavior is to aim directly at a target when gaining aspect locks, often making primaries ineffective in combat. If this flag is set then the AI ignores that case.

$AI ignores aspect lock for leading: AIP flag implemented

---

code/ai/aicode.cpp

Use a default value if we cannot directly access it.
Closes #4142 
Looking at the rest of the file, some of the checking is inconsistent, and as a follow up, a helper function (or series of helper functions) should probably be created which properly checks access to the `Weapon_info` array.

Check for valid index before accessing Weapon_info

---

code/parse/sexp.cpp

When the RGB values of the legacy `show-subtitle` were fixed (#2578) the `width` argument was inadvertently deleted, resulting in a mismatch for all subsequent arguments.  This fixes that.

fix show-subtitle again

---

code/mission/missionmessage.cpp

The FS1 behavior for converting wingmen messages to Command messages specifically applies to in-mission messages with multiple files corresponding to the possible senders.  There is no situation where a built-in message needs to be converted, and in fact built-in messages can't usually be substituted because most built-in messages are distinct.  This commit adds an extra check for that case.  It has the effect of "fixing" #4149 even though that isn't really a bug.

add an additional check to the convert-to-Command logic

---

code/graphics/post_processing.cpp
code/hud/hud.cpp
code/mission/missioncampaign.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h
code/parse/sexp.cpp
code/starfield/starfield.cpp
code/starfield/supernova.cpp
code/starfield/supernova.h
freespace2/freespace.cpp

A bit of cleanup, refactoring, and bugfixing...
1) The supernova code now uses enums to represent states, and those state transitions now all happen in `supernova_process` instead of being scattered around.
2) Some state transition bugs were fixed - e.g. the HUD is now disabled when the camera cuts to the external view, instead of when the camera stops moving; and the particles start and the simulation stops when the comments say they do.
3) There is now a game_settings.tbl flag to make the HUD countdown timer reach zero when the supernova hits, instead of reaching 5s.  This only affects the HUD display; actual timing is not changed.
4) Don't apply lightshafts if the supernova glare is in effect - partial fix for #4152.

refactor supernova code

---

code/hud/hud.cpp

...due to sudden changes in engine energy, which can affect `current_max_speed`. This makes 100% volume at the ship's tabled default max speed.

Fix cockpit engine sound volume changing unexpectedly

---

code/io/timer.cpp
code/io/timer.h
code/starfield/supernova.cpp

This adds a type-safe `TIMESTAMP`, similar to `UI_TIMESTAMP`.  Eventually all of the FSO codebase will be switched over to this new type.  In the meantime, just the supernova code is switched over.

upgrade supernova timestamps

---

code/actions/expression/ExpressionParser.h
code/actions/expression/nodes/AbstractExpression.h

`pstypes.h` overrides `memmove` by declaring a macro with that name. However, built-in Mac headers contain this: `_VSTD::memmove`, and the preprocessor replaces `memmove` with `memmove_if_trivial_else_error`, resulting in `_VSTD::memmove_if_trivial_else_error` that obviously doesn't exist. Reordering the includes to make sure `pstypes.h` is not loaded before the system includes fixes this issue.

Change include order to fix compilation of unit tests on Mac

---

code/ship/ship.cpp

Set the subsystem name pointers to nullptr so that we don't try to free random memory.  Also set the subsystem percentages to 0 for consistency.

prevent crashes in the event of a subsystem mismatch

---

.github/CODEOWNERS
.github/workflows/build-release.yaml
.github/workflows/post-build-release.yaml
ci/post/changelog.py
ci/post/forum.py
ci/post/github.py
ci/post/main.py

Auto triggers were failing because the `linux_result` and `windows_result` variables were expected by the .yaml to be bools but were in fact strings.  This fixes that assumption to be the correct type.
Changed checkout of current master HEAD to the passed release tag, thus allowing the script to be run on only the intended release data instead of accidentally including new merges after the release tag.
Fixes the Nebula and forum post version strings to correctly pull version string data from `version_override.cmake` and `version.cmake`, instead of trying to fudge it from the tag_name or incorrectly from the `version.cmake` alone.
Also Adds a `changelog.py` script to create a `change.log` file.  This grabs the titles of merged PR's since a given date passed as an argument of the form of …

Fix auto-trigger for post-release build workflow, Checkout passed release tag, Fix version string

---

code/parse/sexp.cpp
code/starfield/starfield.cpp
code/starfield/starfield.h

Page in the subspace stuff if the mission-set-subspace sexp is used.
Implements #4166.  Note that this will only preload the tunnel for sexps, not scripts.  If using scripts, just add a `(when (true) (mission-set-subspace 0))` as a mission event and it will trigger the preloader.  The preloader only checks for the use of the sexp operator, not whether it actually sets subspace or not.

add preload ability for mission-set-subspace

---

code/lab/renderer/lab_renderer.cpp

Couple of minor fixes here,
Firstly, envmap_name wasn't zero initialised, so strlen() would return =>1 even if no filename had been found, leading to an erroneous call to bm_load.
Secondly, I added a guard to check that bm_load returned a valid handle, so that environment maps are still generated if precalculated ones are missing.

Fix for #3629

---

code/def_files/data/effects/deferred-f.sdr

This is a change I've been playing with on my personal lighting experiments builds a lot and think is a big step up. I think it may make sense to have the 22.2 default weapon light sizes or brightness be different under this, as the result otherwise is generally dimmer lighting, but followup PRs will add controls for those defaults to lighting profiles. We could potentially have defaults tied to mod target version then, or something.

Switched light shader attenuation math to something that looks more real

---

code/camera/camera.cpp
code/camera/camera.h
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h
code/parse/sexp.cpp
freespace2/freespace.cpp

By specifying a base resolution in game_settings.tbl, subtitles can be scaled to the screen in the same way as HUD gauges.  This can be used to prevent subtitles from appearing smaller at larger resolutions.
Depends on and is a follow-up to https://github.com/scp-fs2open/fs2open.github.com/pull/4157.

add the ability for subtitles to be scaled correctly to the screen 

---

code/model/model.h
code/model/modelcollide.cpp
code/model/modelinterp.cpp
code/model/modeloctant.cpp
code/model/modelread.cpp
code/model/modelsinc.h
code/render/3d.h
code/render/3ddraw.cpp

These changes add a new chunk to the BSP data structure. TMAP2POLY uses unsigned integer instead of unsigned short to store vertex and normal indices, allowing up to `2^32 - 1` vertices to be used by a single sub-object. 
Also removes vestigal data `center` and `radius` that were unused or superfluous, resulting in a net profit in file-size savings.

Increase POF vertex limit

---

code/cmdline/cmdline.cpp
code/cmdline/cmdline.h
code/network/multi.cpp

Creates a mechanism for adding packet types to the debug log.  This is for debugging misaligned packets.  The last "good" packet is usually the culprit.

Create commandline option for logging data packets

---

code/hud/hud.cpp
code/parse/sexp.cpp

1) Fix part of the lookup logic in `hud_get_default_gauge_index`
2) Add back part of the lookup that was removed in #4003
3) Use custom checks with the `default_hud_gauges` list
4) Add a clarification comment to `default_hud_gauges`
Fixes #4171

various HUD gauge fixes

---

code/gamesnd/gamesnd.cpp
code/sound/ds.cpp
code/sound/ds.h
code/sound/rtvoice.cpp
code/sound/sound.cpp
code/sound/sound.h

Investigation and personal use cases have shown the limit cap of 15 to be unneeded and a hindrance at times, and the 128 channel cap is also at times a bit too low. This removes the first and makes the second dynamic based on system reported capabilities.

Disengage the sound limiters

---

code/network/multi.cpp

Upgrade packet dumping command line option to include the amount of data that has been processed from the packet so far.  Also, upgrade the `nprintf` that dumps unknown packet types to an `mprintf` because even power users very rarely use the debug filter.

Log data packets2

---

code/camera/camera.cpp
code/camera/camera.h
code/parse/sexp.cpp

Follow-up to #4158.  Allows use of the specified subtitle width and height in all cases, without stretching it to the screen's current aspect ratio.
~~In draft status until #4158 is merged.~~

add optional flag to not change subtitle aspect ratio

---

code/ai/aiturret.cpp
code/mission/mission_flags.h
code/mission/missionparse.cpp
code/object/object.cpp
code/object/object_flags.h

A work-around for the default behavior where turrets will ignore ships that have no-collide set.  This allows turrets to target such ships.  As requested by @MjnMixael and the bta team.
Needs testing, as I'm not in a position to build and test at the moment.

Basic Implementation for Attackable_if_no_collide

---

code/model/modelcollide.cpp
code/model/modelinterp.cpp
code/model/modeloctant.cpp
code/model/modelread.cpp
code/model/modelsinc.h
code/render/3ddraw.cpp

Adds the `SORTNORM2` chunk and merges the `BOUNDBOX` chunk into `TMAP2POLY` as part of version 2300 (more details [here](https://github.com/Baezon/pof-tools/issues/36#issuecomment-1101733254)). Technically, a 'breaking' change, but since it just introduced and there's no pofs in the wild with this version yet it should be ok.
Also removes several dead bsp parsing functions.

More Pof space optimizations

---

code/ai/aicode.cpp
code/ai/aigoals.cpp

My guess is that, in `ai_ship_destroy`, if the dead ship's goal object has already died in the same frame, the `goal_objnum` will be -1 when `ai_formation_object_recalculate_slotnums` is about to be called.

probably fix #4187

---

code/object/object.h

Turns out the `MAX_OBJECT_FLAG_NAMES` was not increased originally, so this PR increases it to match the new amount now that `ai-attackable-if-no-collide` flag was added.

Fix FRED accessibility of new flag `ai-attackable-if-no-collide` V2

---

code/parse/sexp.cpp

PR #3750 made `check_sexp_syntax()` less permissive of node trees containing `<argument>`, which causes problems given that FRED saves `modify-variable`'s second argument as a `SEXP_ATOM_NUMBER`, as now `check_sexp_syntax()` complains that `<argument>` isn't a valid number. This commit both makes the `SEXP_ATOM_NUMBER` check skip the number validation logic if the `SNF_SPECIAL_ARG_IN_NODE` flag is set, as well as removing the `SEXP_ATOM_STRING` type check from the later `SNF_SPECIAL_ARG_IN_NODE` check (for making sure it's inside an `-argument` SEXP).
This caused problems with no fewer than three missions in BP2: the dreamscape, Her Finest Hour, and UT2. After compiling a build with these changes, I was able to successfully load the dreamscape and the event that was previously generating …

Don't treat a bare <argument> as an error.

---

code/missionui/missionweaponchoice.cpp
code/ship/ship.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

The `stuff_int_list()` call converts the weapon names into the appropriate index into the `Weapon_info` array; however, in `weapon_do_post_parse()`, we call `weapon_sort_by_type()`, which reorders the array; this makes these indices potentially point to the wrong weapon. Additionally, there's no protection against someone `+remove`ing one of the weapons in the list in a later TBM.
This commit makes it so we instead store the names into a vector of strings, then convert them into indices after `weapon_sort_by_type()` has already been called. Additionally, `Player_weapon_precedence` is changed from a fixed-size array to a vector, since it's usually not as long as `MAX_WEAPON_TYPES`.
Fixes #4199.

Delay processing "$Player Weapon Precedence:" until after parsing.

---

code/mission/mission_flags.h
code/mission/missionparse.cpp
code/parse/sexp.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/ship_flags.h
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

This Ship flag (`Fail_sound_locked_primaries`) causes the game to call the firing fail sound (like when you're out of weapon energy) if the player tries to fire their primaries when they're under the effects of the `Primaries_locked` flag. 
Tested and worked fine.

Add a ship flag to allow the firing fail sound to play with locked primaries

---

code/hud/hud.cpp
code/hud/hud.h
code/hud/hudparse.cpp
code/hud/hudparse.h
code/scripting/api/objs/font.cpp
code/scripting/api/objs/hudgauge.cpp

These are useful for adapting scripts based on whether HUD gauges are scaled and whether they use different coordinates or fonts.

add some script functions for HUD gauge data

---

code/lighting/lighting.cpp
code/lighting/lighting.h
code/model/modelrender.cpp
code/model/modelrender.h
code/object/object.cpp
code/weapon/beam.cpp

`light_ignore_objnum` and `affected_objnum` support features that, as far as I can determine, can't work in deferred and don't even work in non-deferred lighting. Their continued presence in the code is a distraction.
Submitted in draft at the moment because my ability to actually test these changes has been very limited.

Remove light filtering data

---

code/ship/ship.cpp

Tabled `$Texture Replace` did not work on ships where the class is changed in the loadout or with the `change-ship-class` sexp. This was because the replacement textures only were loaded during mission parse, and the `change_ship_type` did not account for loading new textures from ship classes that were not in the initial mission parse. Part of the bug was also that the code that updates texture replacements was after the texture page-in section of `change_ship_type`.
This PR fixes that bug by properly loading the textures in when the ship class changes. It also moves the code to within the `ship_model_change` function (which is only used in the `change_ship_type` function) so that the texture loading happens correctly before texture page in. The updated code also fixes some other edge …

Fix Texture Replace and Team Colors with Ship Changes

---

code/ship/ship.cpp

`ship_set_default_weapons()` (which is called by `ship_create()`) was only setting `swp->primary_bank_capacity` for a bank if the default weapon for that bank was ballistic; if the ship was then equipped with an ammo-using primary and the `set-primary-ammo` SEXP was used on it, it would think the bank had a capacity of zero, resulting in 0 ammo.
This commit simply moves the assignment outside of the conditional, so that primary bank capacities are always recorded in the `ship_weapon` class.

Always record primary bank ammo capacity during ship creation.

---

code/weapon/beam.cpp

`beam_add_light_small()` and `beam_add_light_large()` duplicate a lot of logic, and in working on #4208 I found this to be an obstacle to making any changes to them and my attempts to work around that are significant enough to deserve individual scrutiny in my mind. I've moved what are to me logically discrete steps of that shared logic into functions, and eliminated some logically unreachable code as well.

Beam light cleanup

---

code/parse/sexp.cpp
code/scripting/api/objs/ship.cpp

Previously, using the `change-ship-class` sexp or scripting function did not update RTT cockpit gauges. This PR adds the cockpit code update functions to fix the issue. Tested and works as expected.

Fix RTT Cockpits Gauges with Change Ship Class

---

code/hud/hudbrackets.cpp
code/hud/hudbrackets.h

This is a relatively minor issue that ought not to bring everything to a screeching halt.
I'm not going to say this will fix (github pls) #4214 just yet. It's possible other engine code is doing something wonky that resulted in bad parameters that warrants a bit more investigation.

Early return instead of assert on 0 or less sized hud brackets

---

code/lighting/lighting_profiles.cpp
code/parse/parsehi.cpp
code/parse/parsehi.h
code/source_groups.cmake

This takes a little bit of tedium reduction I used in lighting profiles parsing and makes it more generally available.
I have done some work on applying this concept to all common table parsing constructs, but I would like to make use of this approach in other things long before I would ever get done doing that, so I'm PRing this as is with the intent of adding more capabilities as I actually need them.

Move of special parsing functions out of lighting_profiles into new file

---

code/weapon/weapons.cpp

Back in #104, I made an *attempt* at clearing the delayed SSM parsing data once it'd been validated; however, for some reason, I only cleared half of the variables, and I only used `.clear()` rather than `.clear()` followed by `.shrink_to_fit()` (which means the same amount of memory was still reserved for these variables that would never be used again). While making #4201 I happened to comes across the "swap with empty temporary" paradigm do to both at once, so I decided to apply it to this old thing, as well as clearing all four variables rather than just two. Additionally, since these mappings don't actually care about ordering, I made them `unordered_map`s while I was at it. It's probably not a significant memory savings, but since we'd never need to use that memory after parsing, I …

Actually clear delayed SSM parsing data when it's no longer needed.

---

code/parse/sexp.cpp

When FRED puts a `true` in the middle of a list of arguments, it wraps it in a nested list as `(true)`, because it's technically an operator; however, if someone writes a SEXP by hand, they could easily forget to do this, and in such cases, this causes `Locked_sexp_true` to be inserted into the middle of the list. If it's not the last element of the list, it will then have its `.rest` attribute set to the next node in the list. If this is a temporary SEXP (i.e. from Lua's `runSEXP()` function), this used to be a temporary problem, but PR #4088 changed the global search for any node with `.rest` set to the node being freed to require an explicit parent node. This means that `Locked_sexp_true.rest` remains set to a freed node, which can cause further issues. If such a malformed SEXP *isn't* …

Avoid setting .rest for Locked_sexp_true/false with malformed SEXPs.

---

code/parse/sexp.cpp

Properly report errors and warnings, and don't create duplicate variables.  Fixes #4170.

make variable list parsing a little more robust

---

code/ai/aicode.cpp
code/ai/aigoals.cpp
code/ai/aiturret.cpp
code/controlconfig/controlsconfig.cpp
code/object/collidedebrisship.cpp
code/object/collidedebrisweapon.cpp
code/object/collideshipship.cpp
code/object/collideshipweapon.cpp
code/object/collideweaponweapon.cpp
code/scripting/hook_api.h
code/scripting/scripting.cpp
code/scripting/scripting.h
code/ship/ship.cpp
code/weapon/beam.cpp
code/weapon/weapons.cpp
freespace2/freespace.cpp

For script hooks which use conditions, be more consistent about evaluating both objects involved, as well as evaluating the different types of objects.
Fixes #3874.

fix up conditions for script hooks

---

code/ship/ship.cpp

For some reason, ship flag parsing was still using a fixed-size array instead of a vector, limiting it to 20 flags parsed in a single entry. Since there wasn't really a reason to do that (it was basically parsing to a vector anyway, then resizing it down to the limit, then stuffing the C-strings into the array), I changed it to a vector.

Allow an unlimited number of ship flags to be parsed at once.

---

code/model/model.h
code/model/modelcollide.cpp
code/model/modelinterp.cpp
code/model/modeloctant.cpp
code/model/modelread.cpp
code/model/modelsinc.h

This is some much needed cleanup of the model code related to parsing some of the bsp data structure. There are some updates to macros, swapping out a function for some safe typecasting, and the addition of a new struct to make parsing TMAPPOLY less ugly. Also removed some magic numbers.

Model code cleanup #1

---

code/mission/missionparse.cpp
code/parse/sexp.cpp
code/parse/sexp.h
fred2/campaigntreeview.cpp

Followup to #4088.  A few calls of `free_sexp` (especially in `free_sexp2`) did not supply the calling node, which left inconsistent SEXP tree structures and caused a crash in TranscendE1M6.  This fixes the crash and fills in some of these places.

patch the freeing of SEXP nodes

---

code/missionui/missionshipchoice.cpp
code/model/model_flags.h
code/ship/ship.cpp

The statistics summary window in the ship loadout editor shows various aspects and stats of the selected ship. These can be toggled and customized through the ships table, but one line is actually autogenerated, `+Turrets`. This is unideal for certain ships, especially those which use turrets on ships in non-standard ways (for example having an AI controlled turret which shoots bombs). In these cases, the turrets are not actual turrets, and it is confusing for players seeing that there is a turret on the ship in the loadout editor. (I can give more detailed examples using FotG if needed).
This PR adds a subsystem flag which allows the modders to hide a turret subsystem so it is not counted in the auto generation of the `Turrets` summary line. (As a slight cleanup I also removed cleaned up …

Add Subsystem Flag to Hide Turrets from Ship Loadout Stats

---

code/missionui/missionweaponchoice.cpp

Theoretically, the list actually had precedence when a table entry had fewer banks than the model, which would fill the extra banks with the first applicable weapon in the precedence list... except the engine `Error`s before that can happen, so it didn't actually do that. When a mission's loadout doesn't include one or more of the weapons the ship thinks it should have (i.e. it's left to its default loadout and one or more of those are missing), the missing weapons are replaced from the `Player_weapon_precedence` list. However, it didn't actually check precedence: it just went through every weapon type in order, and picked the first applicable one that also happened to be on the `Player_weapon_precedence` list.
This commit makes it so that instead of iterating through every weapon ID, we …

Make the "$Player Weapon Precedence:" list actually give precedence.

---

code/menuui/readyroom.cpp
code/menuui/techmenu.cpp
code/scripting/api/objs/player.cpp

1) In commit 770fce8de5dc3ab4fd1db0e4d74724664dd60047, a flag was incorrectly ported from a bit to a flagset, which caused ships not in the tech db to not be removed.
2) Perhaps due to the pilot file upgrade, campaigns which had their tech databases reset would immediately load stale techroom data from the savefile.  This change writes the savefile after the reset so that subsequent reloads will load the correct data.

fix two bugs associated with custom tech databases

---

code/starfield/starfield.cpp

Follow-up bugfix for #4186. Suns are getting their positions and everything stored and retrieved correctly, but the math that positions them was never corrected like bg bitmaps are now. The default sun position must be corrected as well, since that is entirely internal.

Fix background sun positioning as well

---

code/mission/missionbriefcommon.cpp
code/mission/missionbriefcommon.h
fred2/briefingeditordlg.cpp
fred2/briefingeditordlg.h

1) Prevent the ship class from being changed if the icon image has a special closeup (like a jump node)
2) If the icon image is changed to a special closeup, automatically choose a ship class that doesn't have a custom icon
Fixes #3860

add some UX guards to the briefing editor icons

---

code/model/modelcollide.cpp
code/model/modelinterp.cpp
code/model/modeloctant.cpp
code/model/modelread.cpp

There were several dynamic arrays `new`'d but not `delete[]`ed, however in this case they were largely unecessary. Instead of copying the `model_tmap_vert_old`s into `model_tmap_vert`s and using those, the `model_tmap_vert_old`s can be used directly. Also do some updating of the easily-missed-because-it-doesn't-get-compiled-on-my-machine swap bsp functions for big endian.
Should fix #4185

Fix memory leak and use tmap verts directly

---

code/io/timer.cpp

The new timestamps should use the timestamp ticker, which accounts for pauses and time compression, not the standard timer, which measures absolute elapsed time.  This fixes the bug reported on Discord where the supernova timer did not pause when the game was paused.
Follow-up to #4156

use the proper time for the newly added timestamps

---

code/ship/ship.cpp

Assign locked-* cues to ship-created ships so that their arrival and departure cues are not -1.  Supersedes PR #4248.
Fixes #4251.

assign cues when a ship is ship-created

---

fred2/management.cpp
qtfred/src/mission/Editor.cpp

These were first noticed by @TheForce172 in PR #4241.  Instead manually editing the parse buffer, call the parsing functions to properly free the memory used by parsing the tables.  Also remove redundant calls to `ship_init`.

clean up some parse problems in FRED

---

code/camera/camera.cpp

When the `$Use host orientation for set-camera-facing` flag in game_settings.tbl is active, the camera will use the host's orientation as a basis for rotation.  However if there is no host, the camera unintentionally inherited its old stale orientation.  Instead the camera should base its new orientation on the identity matrix which is the expected behavior.

keep default identity orientation when host flag is active

---

code/hud/hudtarget.cpp

Normally, when the player cycles through targets using (for example) the hostile targeting key, the targets will be shown in order of distance.  In PR #4121, this was changed from bounding-box distance to center-distance, which has very little noticeable effect on the cycle except that it now agrees with the AI strategy for measuring distance.
However, when the player targets a hostile for the first time, or when the cycle resets after 1.5 seconds have passed, the first ship targeted will be the closest ship *or* the ship with the closest turret.  And furthermore, when the target cycle continues, the next ship targeted will be the next ship farther away.  There can be a dramatic difference between a turret, which may be very close, and the center of the ship, which may be very far away. …

partial revert of targeting distance ranking change

---

code/parse/sexp.cpp
code/parse/sexp_container.cpp

Follow up on PR #3862 to make two changes to the `clear-container` SEXP:
1. Fix SEXP help text
2. Allow for any number of arguments, rather than only one.

Fix clear-container SEXP

---

fred2/addmodifycontainerdlg.cpp

Turns out PR #4243 actually introduced a bug that appeared to implement the feature.  The previous implementation had the effect of intercepting all keypresses and routing them to the main window.  This fixes that bug by using `CDialog` instead of `CWnd`.  It also turns out that the `hWnd` window handle for some reason does not match the expected window, but fortunately, this implementation is only called in the correct window so the restriction is not needed.

revised disabling of Enter and Escape

---

code/object/collideshipship.cpp
code/ship/ship.cpp
code/ship/ship.h

Clients with bad pings can find themselves being thrown to the far corners of the map because multiple collisions can happen before an update can be received from the server, compounding the effects of collisions.  (And on the second collision, an interpolated ship can actually do the opposite of react properly to a collision impulse, especially if a brand new object update packet has just come in, making the subsequent collision even more powerful)
Client players are still affected by collisions on their local instance, but other ships will literally pass through each other until updated by the server (avoids other bugs with stationary ships).  A new timestamp controls the frequency of collisions with the player ship, so that the buggy secondary collisions do not happen.
Still needs to …

Limit all MP client collisions to prevent bugs

---

code/ai/aicode.cpp
code/ai/aiturret.cpp
code/object/objectsnd.cpp
code/scripting/api/objs/cockpit_display.cpp
code/scripting/doc_html.cpp

1) Remove the extra branch in `check_ok_to_fire` that was added in SVN revision 10392, or commit 0d54630e83419f53ede08056bac3b26928d059cb.  If there was an actual Coverity error, this does not fix it at the proper location.  More importantly, this breaks certain turret firing behavior.
2) Fix a couple of bounds checks.
3) Remove an incorrect stale comment.
This fixes the broken turret swarm weapons that were uncovered by the fixes in #2959.

miscellaneous fixes related to old Coverity fixes

---

fred2/bgbitmapdlg.cpp

Per Asteroth, and following PR #4258, sun banking is no longer meaningful and should be disabled.

disable sun bank controls

---

code/mission/missionparse.cpp
code/parse/sexp.cpp
code/scripting/api/libs/mission.cpp
code/starfield/starfield.cpp
code/starfield/starfield.h
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

Due to extra 'bank' shenanigans background bitmaps have a more complicated conversion, but suns don't have this so their conversion is simpler (and also incorrect if you try to do the banking stuff). One result of this now is that 'banking' a sun bitmap in FRED will have no apparent effect, but given that sun bitmaps could never actually be banked anyway (it only affected it's 2d position before), this isn't really a loss.

Correct sun position compensation math

---

fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

Container name nodes should never be arbitrary strings, and pasting over or add-pasting into SEXPs that expect them shouldn't be allowed.

Ensure Replace/Add String and (Add) Paste are disabled for container name nodes

---

code/cmdline/cmdline.cpp
code/network/multi_log.cpp
code/network/multi_options.cpp
code/osapi/dialogs.cpp

- report when multi.cfg is missing
- add game version, multi version, cmdline, and PXO status
to multi.log
- use non-interactive mode by default on standalone and
enable it as soon as possible

add improvements to aid in multi troubleshooting

---

code/mission/missionparse.cpp
fred2/missionsave.cpp
qtfred/src/mission/missionsave.cpp

As detailed in the LuaAI PR (#4198), the orders a ship is allowed to follow in mission are currently saved as a bitfield. This bitfield is only accurate if the orders are always within the same order however. And since LuaAI allows adding such orders with modular tables, this is now very brittle and prone to failure and to breaking missions if AI stuff is tweaked by modders.
Hence this PR removes the bitfield and replaces it with a flagset where the parse names of all allowed orders are explicitly listed

Replace +Orders Accepted: Bitfield with flag list

---

code/scripting/api/libs/ui.cpp

BTA added a script that listens for briefing stages. It works fine for regular briefings, but not for command briefings. Mjn realized that SCPUI (which we use for CBs, but not regular briefings) wasn't triggering the `$On Briefing Stage:` hooks. This adds a scripting function to trigger them.

Allow SCPUI to run `$On Briefing Stage:` hooks

---

code/ai/ai.h
code/ai/aicode.cpp

This mode was never actually implemented, even in retail, so there is no FIXME as such.  Tweak the code to reflect this.  Fixes #4270.

resolve FIXME for AIM_GET_BEHIND

---

code/hud/hudsquadmsg.cpp

In order to facilitate more player orders being added with LuaAI, the comms menu needs to support more than the ten entries available.
Fortunately, a system to effectively scroll in that menu already exists.
Unfortunately, it was broken except for one or two modes.
This fixes this by doing three things:
1. Make sure that ``First_menu_item``, the tracker for the current scroll position, is only reset on mode change (as it was before), and _not_ in any on-frame method
2. Make sure that the key-check method always takes ``First_menu_item`` into consideration for which button is selectable
3. Make sure that the key-check method always takes ``First_menu_item`` into consideration for which result was actually selected instead of relying on the callers to add this offset.
This now makes …

Fix HUD squad menu PageDown

---

fred2/briefingeditordlg.cpp
fred2/briefingeditordlg.h

Per #3860, don't disable any of the icon dropdowns, and don't change the ship class when the icon type is a special popup.

briefing icon behavior tweaks per request

---

code/mission/missionparse.cpp

#4282 introduced a regression where an empty orders accepted list would cause the ship to accept the default orders, instead of no orders as would be correct.
This fixes this.

Fix +Orders Accepted List: parse

---

code/mission/missionparse.cpp

Followup to #4310.
Evidently the fix has to be to _always_ add that flag, even with an empty list, and not never.

Fix Orders Accepted List properly

---

code/ship/ship.cpp

The ship creation code had an off-by-one error while checking the maximum length.  Fixes #4297.

fix NAME_LENGTH discrepancy

---

code/network/multi_pxo.cpp

Simple fix for string overflow in the PXO chat lobby, pending a large refactor moving to SCP_string.
Fixes #4285

use proper buffer size for PXO chat line

---

code/cmdline/cmdline.cpp

Instead of keeping the old variables around (except renamed to include "_deprecated") and manually checking them one at a time with a lot of duplicated code, use existing information to generate the messages automatically.
Got the idea from @EatThePath complaining about the code duplication, and realizing we already had the necessary information to do this automatically. Tested to make sure that the new code not only compiles, but also, given some deprecated flags, produces the same debug log output as the old code.

Handle deprecated cmdline flags programmatically.

---

code/hud/hudtargetbox.cpp
code/weapon/weapon.h
code/weapon/weapons.cpp

Done following a discussion in #Freespace a week or so ago. Allows a weapon to override a turrets name if it is the first weapon in a turret. Does not override a Subsystems Alt name if specified in ships.tbl

Allow Weapon To Override Turret Name

---

code/parse/sexp.cpp

Rename `is_for_op()` to `is_for_blank_op()` and move it to be near related functions.
Follow-up to PR #4296.

Fix is_for_op() to follow existing conventions

---

code/mission/missionparse.cpp

When parsing escort priority, FSO asserts that the escort flag is set, but this assertion is only valid in missions output by FRED; it's fairly trivial to use notepad to remove the flag without removing escort priority, thereby triggering the assertion. Furthermore, there doesn't actually seem to be a problem if a parse object has an escort priority without the escort flag; the engine won't actually use the priority until/unless the ship is manually added to the escort list, and then it doesn't matter that one is set.

Remove pointless assertion in mission parsing.

---

fred2/campaigntreewnd.cpp

In the FRED campaign editor, error checking for campaign branches did not correctly handle loop branches.  This avoids performing inapplicable error checking for loop branches, adds a new applicable check, and excludes loop branches from the count of regular branches.  Fixes error checking for the FS2 main campaign.

better error checking of campaign loop branches in FRED

---

code/io/timer.cpp
code/io/timer.h

Are we having fun yet?  A carbon copy of the new `ui_timestamp_elapsed_safe`

Add overload for timestamp_elapsed_safe

---

code/network/psnet2.cpp

Previously, debug builds would assert if a packet was not a psnet packet
type. Port scans and general traffic checks could trigger this for any
public server. So we should just log these events instead, taking into
account that some of this traffic could be malicious in nature.

log non-psnet packets for debugging

---

code/decals/decals.cpp
code/graphics/2d.cpp
code/graphics/light.cpp
code/graphics/post_processing.cpp
code/graphics/render.cpp
code/graphics/shadows.cpp
code/starfield/starfield.cpp

More work trying to make all of the newer graphics code play nice with stub graphics used by the standalone server. This is part one of the changes, which should address all of the weird graphics related crashes we've found so far while testing standalones.

fix a bunch of graphics functions to respect GR_STUB

---

code/cfile/cfile.cpp

Fennel is a lisp language implemented within lua. When embedded it loads .fnl files and compiles them to lua. Adding .fnl to the cfile scripts category reduces the amount of adjustment that needs to be made to the standard fennel compiler to make it work within freespace. Lua's standard module loading looks for the file extension and should have no chance of trying to load raw fennel files, which I have confirmed in testing.

Add Fennel script support to cfile.

---

code/mission/missiontraining.cpp
code/mod_table/mod_table.cpp
code/mod_table/mod_table.h

In Training missions, the game will check if keys used in directives are bound or unbound, and if unbound will display a message to the player to bind the key.
This is limited to only Training missions though, so this PR adds a `game_settings` option to allow modders to use that check in singleplayer mission types too, which is very useful for mods that rely on key presses in non-training missions. Also fixes #4340.

Add option to expand warning on unbound keys

---

code/scripting/api/libs/graphics.cpp

These will add insight if the errors reported by RedMadeJoe pop up again.  The root cause is in the script, but this will prevent FSO from choking.

add some extra safeguards to gr.drawString

---

code/network/multi_obj.cpp
code/network/multimsgs.cpp

Taylor, Wookiejedi, and I have all been going back and forth heavily testing these fixes.  On stationary targets, we have 100% accuracy.  On moving targets, we have one more test pending, but results are promising so far, even at high pings.  This improvement works best with Interpolation Overhaul 2, but is independent of it.

Fix rollback primary collisions

---

code/ai/ailua.cpp
code/hud/hudsquadmsg.cpp
code/hud/hudsquadmsg.h
code/mission/missionparse.cpp
code/network/multi.h
fred2/management.cpp
fred2/missionsave.cpp
qtfred/src/mission/Editor.cpp
qtfred/src/mission/missionsave.cpp

This allows for a nearly unlimited number of player orders as opposed to the 32 before.
Previously, orders were sometimes stored and passed as bitfields, and sometimes as indices into the player_orders array.
This PR tidies that up and replaces it to _always_ be an index into the player_orders array. 
As these bitfields were also sent to multi, replacing them with indices is a multi version bump.
As this is a deep rooted change, the following things need to be tested exhaustively before this can be merged:

De-Bitfield-y Player Orders

---

code/network/multi.h

Instead of having three separate multiplayer version bumps, just merge this the day that the three pr's are merged.  It makes things easier to handle if we need to bisect.  
@notimaginative 's idea.

Multi Bump for 22.2 release

---

code/ai/aicode.cpp
code/ai/aigoals.cpp
code/ai/aiturret.cpp
code/hud/hudsquadmsg.cpp
code/network/multi_obj.cpp
code/network/multimsgs.cpp
code/parse/sexp.cpp
code/scripting/api/objs/order.cpp
code/scripting/api/objs/ship.cpp
code/ship/ship.cpp
code/ship/ship.h
code/ship/ship_flags.h
code/ship/shiphit.cpp
fred2/fredview.cpp
fred2/shipgoalsdlg.cpp
qtfred/src/mission/Editor.cpp
qtfred/src/mission/dialogs/ShipGoalsDialogModel.cpp

Add indexing caches to ships and subsystems, moving both subsystem-to-index and index-to-subsystem lookup from O(n) to O(1).  These lookups appear in many places and often run for multiple ships, multiple times per frame.  This should improve performance by a small but measurable amount, as @EatThePath said:
> I faintly recall seeing that function lurking not too far down the list in performance profiles, though not high enough to really be my focus

Cached subsystem indexing

---

code/mission/missionmessage.cpp

Before setting the `MQF_CONVERT_TO_COMMAND` flag, check to make sure the conversion will succeed.
This should ensure proper behavior for any case where command-conversion is needed.  I've tested it with both a message that should not be converted and a message that should, and both behave as expected.
Follow-up to #4150 and #4078.  Fixes #4356.

additional checks for FS1 message conversion

---

code/network/multi_fstracker.cpp
code/pilotfile/pilotfile.cpp
code/pilotfile/pilotfile.h

Retail saved tracker stats to the local pilot file after read, however the newer pilot file code doesn't work the same way. This adds the ability to properly update the pilot file with multiplayer stats from the tracker during login.
NOTE: This will always overwrite multi stats in the pilot file with the stats from the tracker!

save PXO stats to local pilot file

---

code/gamesnd/eventmusic.cpp

Follow-up for #3879 particularly this commit 0dc3c914d920c11852000ff7a392f2a203e52579. Simply re-adds the various checks that the delay time had to go through before being set. This fixes a bug where music would not play on a mission where a mission without music was played previously. The logic causing that exact symptom gets kind of convoluted, but the basic cause is not checking the same conditions before setting the timestamp.
Unfortunately, I don't think this is the cause of a related bug where all music stops in a long play session. This one "fixes itself" after a single bugged music mission.

Small fix for music initialization

---

code/cfile/cfile.cpp

I couldn't 100% confirm that these two functions do not delete the file, but I didn't see any place where `cf_delete` was called. And if there's an assert protecting against it, then the behavior should not be relied upon, anyway.

Correct some Bad Documentation

---

code/asteroid/asteroid.cpp
code/object/collidedebrisship.cpp
code/object/collideshipship.cpp
code/object/collideshipweapon.cpp
code/scripting/global_hooks.cpp
code/scripting/global_hooks.h
code/scripting/hook_api.cpp
code/scripting/hook_api.h
code/scripting/scripting.cpp
code/scripting/scripting.h
code/ship/ship.cpp
code/ship/shiphit.cpp
code/source_groups.cmake
code/weapon/beam.cpp
fred2/management.cpp
freespace2/freespace.cpp
qtfred/src/mission/management.cpp

This takes a few of the existing hooks and converts them to the new style of hook definition which can include more extensive documentation and enumeration of supported hook variables.
This is an updated version of #3151 to work with the latest codebase.
NOTE: Before this can be integrated into the codebase, it needs an implementation for `bool script_state::IsActiveAction(int hookId)` which apparently only has support for old-style script hooks.

Convert some Lua hooks to the new style to add documentation

---

ci/post/main.py

There are two possible functions that can appear in `version_override.cmake`, so we need to make sure both are handled

Check either possibility for cmake set function

---

ci/post/main.py

`REVISION_STR_VERSION_PATTERN` is not currently matching against a string, it is matching against a number

Check string, not number in release version regex

---

code/hud/hudsquadmsg.cpp
code/hud/hudsquadmsg.h

#4306 changed the order that player orders appear in the hud menu.
While not breaking, this is certainly a nuisance to experienced players.
This PR restores the original display order.

Ensure legacy order for HUD commands

---

code/controlconfig/controlsconfigcommon.cpp

Mod-only controls were disabled in Controls6 as an attempt to de-clutter the controls listing for mods and vanilla that don't use them (or for that matter can't use them).
However, legacy mods (pre Controls Project) may make use of them, and might not add a binding for them in controlsconfigdefaults.tbl (which in post-Controls5 would enable them).  Furthermore, many of the mod-only controls also have hardcoded bindings, meaning usage of the ccfg.tbl to add a binding to them is less likely.
Of note, this PR does *not* remove the disabled flag from the Custom controls, even though they do have hardcoded bindings and do have a tab for them.  This is because they were default-disabled upon introduction.

re-enable mod-only controls that have a tab.

---

code/ship/ship.cpp

`p_objp` cannot be used if FRED is running, and this PR adds that check to the updated team color fixes from #4207.
Fixes #4374

Fix FRED Crash with Team Colors

---

code/parse/sexp_container.cpp
code/parse/sexp_container.h

Make these changes to the list modifier code:
1. Get rid of a ton of code duplication.
2. Detect/prevent concurrent container modification (see PR #4330).

Clean up list modifier code

---

code/CMakeLists.txt

Since bit.c is a third-party file, we can't modify it, so let's instead disable the warnings for it.
Follow-up to #4274.  Fixes #4366.

disable compilation warnings in BitOp

---

code/parse/sexp.cpp

There is no point in putting a define in an assert to make sure it's greater than zero.  Just put a comment or use a `static_assert` if you're especially paranoid.

Remove a pointless assert

---

code/menuui/techmenu.cpp
code/menuui/techmenu.h
code/ship/ship_flags.h
code/weapon/weapon_flags.h

The "default" tech database flags indicate whether entries are in the tech room by default, that is, when the table is originally parsed and the campaign is started.  Flags may be changed later, so that when the tech database is "reset to default" the flags can be returned to the known state as specified in the tables.
A bug was introduced back in commit c924e3997a (!) based on a misinterpretation of what "default" meant.  This fixes the bug and clarifies the flags.
Fixes #4390.

fix use of default tech database flags

---

code/ai/ai.h
code/ai/aicode.cpp
code/scripting/api/objs/ai_helper.cpp

Previously, rotation data was just written to the AI_ci, which, for rotation, is reset _and_ ignored.
Now fixes this, and properly resembles thrust (as described), regarding tabled damping and turntime values, as well as properly interacting with other AI functions setting the rotation.

Properly set rotation data from LuaAI

---

code/parse/sexp_container.cpp
fred2/sexp_tree.cpp
qtfred/src/ui/widgets/sexp_tree.cpp

Given concerns about complications from concurrent modification, I think it's best to prohibit the use of Replace Container Data with special argument lists. This includes the special argument handler SEXPs that don't support containers, such as `random-of` and `in-sequence`.
This restriction applies *only to argument lists*; the condition and actions SEXPs can still use Replace Container Data.
We can always revisit this decision later.

Disallow using Replace Container Data with special argument list

---

.github/workflows/post-build-release.yaml
ci/post/changelog.py

This adds an `echo` to print out the `github.event_name` of the calling workflow, so that the Auto Trigger can be debugged. (For some reason it hasn't been firing when called by Release.yaml)
Fixes Changelog.py going into an infinite loop due to not breaking out when page = last_page + 1, issue turned out to be due to how `for .. in ..` loops differ from C++'s `for` loops.
Also makes some improvements to the Changelog.py to be more user friendly as well as allow authentication to get around the REST API HTTP requests limits.

Changelog.py improvements and post-release-build.yaml debugging

---

code/mission/missionparse.cpp
code/mission/missionparse.h
code/network/multiutil.cpp
code/ship/ship.cpp
code/ship/ship.h

While it may seem counterintuitive, we have to keep the standalone bogus ship from being added to the ship object list so that we don't have to exclude it from all the places it could cause crashes or mysterious AI behaviors.  Both were being observed, and this should fix them.
I literally looked at every single place that the list is used, and most instances are potentially problematic, with other instances being benign, but none of them serving any practical use.

Fix the standalone ship being added to ship list

---

fred2/fredview.cpp
qtfred/src/mission/Editor.cpp

1) Restore original behavior where function would exit after one error check (for consistency)
2) Exclude player ships from the check for ships in a wing sharing the same orders

some tweaks to the FRED error checking

---

code/model/modelread.cpp

Since "No subsystems found" and "Not all subsystems have a record in ships.tbl" are different warnings, they should have different flags.  Follow-up to #4408.

split subsystem warning display checks

---

code/ai/aicode.cpp
code/math/vecmat.cpp

`bank_override` in `ai_turn_towards_vector` is a target angular position for banking in radians and it will do as much as it can to reach that position in the frame it is called. But all of the calls using the parameter with non-zero use... the ship's speed. Yes, 40, 80 whatever meters per second -> do what you can to bank by 40, 80 whatever radians this frame. In effect, this was only ever 0 banking, or bank as hard as possible. So this changes it so `bank_override` is instead a target velocity (expressed in % of max bank speed) and `vm_angular_move_forward_vec` is updated to instead aim for such a target velocity.
Not a bug fix per se, but this allows @BMagnu to use banking in turnTowardsPoint in LuaAI in a much more intuitive and useful way.

Update `ai_turn_towards_vector` to use a target vel for banking

---

code/cfile/cfile.cpp
code/cfile/cfilesystem.cpp

This allows for retail hud config presets to once again show up in the list, as they were previously excluded from the file cache. Additionally it fixes newly created presets that were unable to be found without a restart when a mod is specified.

Fix issues with loading of hud config presets

---

code/mission/missioncampaign.cpp
code/missionui/missionbrief.cpp

The "skip training" button and the "exit loop" button should both check whether the campaign is actually over before attempting to load the next mission.  The fix is simple - just use the same logic as in `mission_campaign_skip_to_next`.
Fixes #4412.

end the campaign properly when a mission is skipped

---

code/menuui/mainhallmenu.cpp
code/menuui/playermenu.cpp
code/menuui/playermenu.h

There are three popups of decreasing priority that can appear in the main hall screen: campaign not found, pilot upgraded, and player tip.  Only one of these should actually be displayed -- the first popup will take the player to a different screen, rendering subsequent popups useless; and the second popup is more important than the third popup.  This PR prioritizes the popups accordingly.
Yes, this uses `goto`.  It's a succinct and clear way of implementing the necessary logic.  It works better than both a one-iteration loop and a cascading if() block.
Fixes #4418.

only display one popup when the player gets to the main hall
