scp-fs2open/fs2open.github.com

- code/parse/sexp.cpp
This adds a hook into the for-* handlers to return the number of valid arguments.  Fixes a bug reported on Discord.
> make num-valid-arguments work for the for-* sexps

- code/network/chat_api.cpp
- detect server connection error messages before blindly
moving to user login (crash fix)
- detect read errors and fail accordingly (crash fix)
- allow server disconnect to run even if we aren't connected (cleanup & reset)
> address issues with error handling in chat_api

- code/ai/ai_profiles.cpp
- code/cmdline/cmdline.cpp
- code/controlconfig/controlsconfigcommon.cpp
- code/gamesnd/gamesnd.cpp
- code/graphics/software/FontManager.cpp
- code/io/mouse.cpp
- code/mission/missionmessage.cpp
- code/network/multi_obj.cpp
- code/network/psnet2.cpp
- code/ship/ship.cpp
Fixes #3407, and I used a regex search to find what I hope are all other examples.
> add missing newlines to several mprintf statements

- qtfred/src/main.cpp
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/dialogs/EventEditorDialog.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/util.cpp
Replacing some deprecated Qt function calls and initializations with their recommended alternatives to fix compile warnings.
Also fix a runtime warning.
> Fix some qtfred warnings

- code/lab/dialogs/render_options.cpp
- code/lab/renderer/lab_renderer.cpp
- code/lab/renderer/lab_renderer.h
- code/model/model.h
- code/model/modelrender.cpp
- code/ship/ship.cpp
- code/ship/ship_flags.h
> Add an option to switch off reflect maps in the lab

- qtfred/src/FredApplication.cpp
- qtfred/src/FredApplication.h
- qtfred/src/ui/FredView.cpp
Make Qtfred able to open/save files on windows. Also fix a crash on shutdown uncovered or introduced with the recent linux runtime fixes.
> Qtfred win fixes

- qtfred/src/CheckedDataListModel.h
Continuing work on the campaign editor, I've been making some changes to my original CheckedDataListModel.
> qtFred: improvements to my checked list

- code/hud/hudescort.cpp
- code/network/multi.cpp
- code/network/multi_ingame.cpp
- code/network/multi_kick.cpp
- code/network/multi_obj.cpp
- code/network/multi_options.cpp
- code/network/multi_pmsg.cpp
- code/network/multi_respawn.cpp
- code/network/multi_team.cpp
- code/network/multi_voice.cpp
- code/network/multimsgs.cpp
- code/network/multiteamselect.cpp
- code/network/multiui.cpp
- code/network/multiutil.cpp
- code/network/multiutil.h
Change find_player_id to find_player_index, since that is what it does.  It retrieves the index to the players[] array.
> Update Function Name and comment to describe what it actually is

- code/weapon/beam.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Also make explicit no mixing of beams/non-beams substitution, that's just going to be painful to attempt.
> Implement substitution for beams

- code/scripting/api/objs/object.cpp
Missed changing the argument type when I changed from int to enum.
> small followup fix for #3476

- code/ship/ship.cpp
The assumed location of a ship's "EngineSnd" is at its rearmost extent, which is fine for ships with engines, but not suitable for stationary objects such as space stations and comm nodes.  If the ship doesn't have an "engine" subsystem, place the persistent sound in the center.
> center the persistent sound by default

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/enums.cpp
Implements `common_maybe_play_cutscene` as a scripting function.  Partial fix for #3367.
> add a scripting function for playing cutscenes in the UI

- code/parse/sexp.cpp
> Add escape character for < and > in html output

- fred2/fred.rc
Finally got around to adding in the `Ctrl+Shift+S` shortcut for Save As in FRED. Tested and works as expected.
EDIT: Thanks @Goober5000 for the typo notice! :D
> Add Keyboard Shortcut for `Save As` in FRED

- code/hud/hudlock.cpp
> fix missiles locking during pause

- code/model/modelread.cpp
This adds additional version definitions so that features can be added which support both the aligned and non-aligned POF formats.
> add some more sophisticated POF version handling

- code/network/multi_pxo.cpp
- code/network/multi_pxo.h
(copied out of icculus.org version)
> support opening of web urls on PXO screens

- code/graphics/opengl/gropenglpostprocessing.cpp
- code/graphics/post_processing.cpp
- code/graphics/post_processing.h
- code/lab/dialogs/render_options.cpp
- code/lab/renderer/lab_renderer.h
***This is experimental work.***
Intended to address Issue #3375.
> Add in-game options menu options for lightshafts and bloom

- code/hud/hudescort.cpp
- code/hud/hudescort.h
- code/network/multi.cpp
- code/object/object.h
- code/parse/sexp.cpp
- freespace2/freespace.cpp
This should make the escort list code a little easier to deal with and be a bit more optimized.
- avoid rebuilding the list constantly
- add and remove ships more efficiently
- better handling of player ships in multi (fixes #1674)
> Refactor hud escort list to be less crazy

- code/ship/ship.cpp
> Initialize shield regen hit delay

- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/ai/aiturret.cpp
- code/asteroid/asteroid.cpp
- code/controlconfig/controlsconfig.cpp
- code/io/key.cpp
- code/io/mouse.cpp
- code/mission/missioncampaign.cpp
- code/mission/missionparse.cpp
- code/missionui/missionscreencommon.cpp
- code/object/collidedebrisship.cpp
- code/object/collidedebrisweapon.cpp
- code/object/collideshipship.cpp
- code/object/collideshipweapon.cpp
- code/object/collideweaponweapon.cpp
- code/object/object.cpp
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/scripting.cpp
- code/scripting/scripting.h
- code/ship/afterburner.cpp
- code/ship/ship.cpp
- code/ship/shiphit.cpp
- code/weapon/beam.cpp
- code/weapon/weapons.cpp
Don't even bother trying if no scripts are even registered to run on them.
> Be smarter about when we try to run scripting hooks

- code/scripting/api/objs/audio_stream.cpp
Just like `setVolume` for regular `sound` handles
> Add setVolume function for audio_stream objects

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/CommandBriefingDialogModel.cpp
- qtfred/src/mission/dialogs/CommandBriefingDialogModel.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/src/ui/dialogs/CommandBriefingDialog.cpp
- qtfred/src/ui/dialogs/CommandBriefingDialog.h
- qtfred/ui/CommandBriefingDialog.ui
- qtfred/ui/FredView.ui
Adds a fully functioning Command Briefing Dialog to qtFRED
> qtFRED Command Breifing

- code/mission/missionlog.cpp
- code/mission/missionparse.cpp
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/ship/ship.cpp
It's useful for *all* ship cleanup to be logged, not just big/huge ships.  And by extension, it's also useful for ship creation to be logged.
> improve logging of ship creation and cleanup

- code/ai/aibig.cpp
- code/ai/aiturret.cpp
Follow-up to #2634. Add target restriction checking to turrets and also AI attacking large ships.
> Add some more missile target restriction checking

- code/model/modelread.cpp
1) Make sure the `PM_FLAG_HAS_INTRINSIC_ROTATE` flag is only set after submodels pass validation and checking
2) Maintain compatibility with old models that used `$look_at` with the submodel number instead of name
> fixes to look_at and intrinsic rotation

- code/lab/dialogs/class_variables.cpp
Looks like a copy+paste error.
> fix lab variables

- freespace2/freespace.cpp
> use public API call for Lua garbage collector

- code/parse/sexp.cpp
Per request, add some more documentation to ai-ignore and ai-ignore-new (and ai-play-dead while we're at it).
Fixes #3612.
> add some SEXP documentation

- code/mission/missionparse.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shiphit.cpp
This occurs at the beginning of the ship death routine, similarly to OnDepartureStarted occurring at the beginning of the ship departure routine.
> add OnShipDeathStarted scripting hook

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipFlagsDialogModel.cpp
- qtfred/src/mission/dialogs/ShipFlagsDialogModel.h
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.h
- qtfred/src/ui/dialogs/ShipFlagsDialog.cpp
- qtfred/src/ui/dialogs/ShipFlagsDialog.h
- qtfred/src/ui/widgets/ShipFlagCheckbox.cpp
- qtfred/src/ui/widgets/ShipFlagCheckbox.h
- qtfred/ui/ShipFlagsDialog.ui
Ship Flags Dialog
https://user-images.githubusercontent.com/2040992/134794647-50e935c9-c44c-48f5-a9ef-87c79dadd4ad.png
> Split From #3674 Flags Dialog

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditorDialogModel.h
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.h
- qtfred/src/ui/widgets/ShipFlagCheckbox.cpp
- qtfred/src/ui/widgets/ShipFlagCheckbox.h
- qtfred/ui/ShipEditorDialog.ui
Ship editor bug-fixes including #3541
> Split From #3674 Ship Editor Bugfixes

- code/fireball/fireballs.cpp
- code/mod_table/mod_table.cpp
- code/model/modelrender.cpp
- code/nebula/neb.cpp
- code/nebula/neb.h
- code/particle/particle.cpp
- code/ship/shield.cpp
- code/weapon/beam.cpp
- code/weapon/shockwave.cpp
- code/weapon/trails.cpp
- code/weapon/weapons.cpp
Exposes the previously hardcoded factors for visibility falloff of various effects at distance in nebula fog.
> Expose nebula visibility factors

- code/ai/aibig.cpp
- code/ai/aicode.cpp
What it says on the tin, AI won't choose an optimum range based on a weapon which is currently locked.
> Ai use lock status for optimum range choice

- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/ship_flags.h
- code/ship/shipfx.cpp
> Add ship flag for toggling ship passive lightning

- .github/workflows/build-nightly.yaml
Reverts scp-fs2open/fs2open.github.com#3780
> Revert "Fix conditional in Build Nightly action"

- code/graphics/render.cpp
- code/graphics/render.h
- code/scripting/api/libs/graphics.cpp
This would allow scripters to draw rotated images to the screen by passing an optional angle parameter, similar to the way you can draw rotated rectangles.
Now without git fuckery. Apologies for not checking properly before creating the previous PR.
> Allow drawing rotated bitmaps

- code/model/modelanimation.cpp
#3732 missed some spots, and currently there are some reliable had crashes as a result. This safeties the ones I'm aware of.
> guard against trying to animate non-existent submodels in more places.

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/PlayerOrdersDialogModel.cpp
- qtfred/src/mission/dialogs/PlayerOrdersDialogModel.h
- qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
- qtfred/src/ui/dialogs/PlayerOrdersDialog.cpp
- qtfred/src/ui/dialogs/PlayerOrdersDialog.h
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.h
- qtfred/ui/PlayerOrdersDialog.ui
Adds the player orders dialog and adds bugfix for ship editor not enabling items on selecting second ship.
> QTFred Player Orders Dialog

- code/cfile/cfilesystem.cpp
Fixes new hud config files not being usable until after restart.
> add players directory to slow search

- code/model/modelread.cpp
Previous code allocated 4x bsp_data_size for alignment, whether it was
needed or not. Now it should allocate slightly more than 2x and only if
alignment is required.
> reduce memory required for bsp alignment

- code/def_files/data/effects/tonemapping-f.sdr
fixes immediate fatal crash described in #3821
> Removed consts being set from uniforms to fix #3821

- code/asteroid/asteroid.cpp
- code/debris/debris.cpp
- code/jumpnode/jumpnode.cpp
- code/menuui/techmenu.cpp
- code/missionui/missionbrief.cpp
- code/model/model.h
- code/model/modelread.cpp
- code/ship/ship.cpp
- code/starfield/starfield.cpp
- code/weapon/weapons.cpp
See title.  All references to `model_create_instance` have been updated to supply an object number or -1.
> update polymodel_instance to reference object

- code/network/multi_fstracker.cpp
- code/network/multi_fstracker.h
- code/network/multi_pxo.cpp
- code/network/multiutil.cpp
- code/network/ptrack.h
- code/network/valid.cpp
- code/network/valid.h
Adds ability to validate table and mission files in batches to reduce the number of network transfers, substantially decreasing the time needed to validate files.
> improve PXO data validation code

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/particle/effects/SphereShape.h
Also compute/convert from spherical coordinates in a way that's easier to understand.
Intended to address Issue #3840.
> Attempt to fix random selection of points inside/on spheres

- code/cfile/cfile.cpp
- code/network/multi_pxo.cpp
- add custom banners support for mods
- remove broken banner randomization code (from retail)
- remove banner hover outline if it's not really clickable
- randomly choose a new banner over time if user is in lobby long enough
> improve handling of PXO lobby banners:

- code/lab/wmcgui.h
- code/network/psnet2.cpp
- code/parse/parselo.cpp
- code/utils/Random.h
Deal with some warnings from clang and errors reported by valgrind.
> Fix warnings/errors from clang and valgrind

- code/ai/aigoals.cpp
This bit of code shouldn't run in FRED, but it wasn't a problem until recent changes made it so.
> fix a FRED crash caused by recent changes

- code/gamesnd/eventmusic.cpp
- code/hud/hud.cpp
- code/io/timer.cpp
- code/ship/shiphit.cpp
- code/weapon/weapons.cpp
I've started work on the timer reimplementation and found a few things that need cleaning up, plus one bug (incorrect initialization of an event music timestamp).  To minimize the mess I figured I'd submit them as an independent PR.
Related to #3854
> Timer preliminary cleanup

- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
Fix #3920 Actually save on save button rather than only on save as.
> 3920 qtFRED save only saves once

- code/model/modelanimation.cpp
Also simplifies the starting logic a whole lot by letting the animation internal state handle it as originally planned, and _then_ setting the animation state correctly instead of trying to handle it preemptively.
Fixes instant animations actually being instant.
> Properly calculate instant animations

- code/model/modelrender.cpp
- code/model/modelrender.h
- code/ship/ship.cpp
Fixes #1354, with some associated refactoring and cleanup. Probably still needs more testing and cleanup and definitely needs some more documentation,. I'm putting it up in draft in case there's any major issues with my approach here that need addressing too
> Fix first person glows

- code/cutscene/ffmpeg/FFMPEGDecoder.cpp
- code/cutscene/ffmpeg/internal.h
- code/sound/ffmpeg/FFmpegWaveFile.cpp
- code/sound/ffmpeg/FFmpegWaveFile.h
> update ffmpeg support for 5.0+ API changes

- code/lab/dialogs/actions.cpp
- code/model/modelanimation.cpp
- code/model/modelanimation.h
Some lab triggers didn't work before, notably all those that had explicit subtypes defined
> Fix lab animation triggers

- code/model/modelanimation.cpp
- code/model/modelanimation_moveables.cpp
- code/model/modelanimation_moveables.h
- code/model/modelanimation_segments.cpp
- code/model/modelanimation_segments.h
Allows for axis animation instead of just pitch bank heading for certain complex animations
> Add axis rotation Animation Segment

- code/model/modelanimation.cpp
- code/model/modelanimation.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
This adds better description to the new SEXPs, adds proper error checking for the entered animation triggers, and shows the FREDer the available triggers / names.
> Improve Animation SEXP usability

- code/starfield/starfield.cpp
No need to change the skybox if it isn't actually changing.
> when changing the skybox, check to see if it's the same as the current one

- code/model/modelanimation_moveables.cpp
> Fix Aix Rotation Moveable

- code/hud/hudtargetbox.cpp
- code/hud/hudtargetbox.h
- code/model/model.h
- code/model/modelread.cpp
- code/playerman/playercontrol.cpp
- code/scripting/api/objs/shipclass.cpp
- code/ship/ship.cpp
- code/ship/ship.h
1. Add custom scan times per subsystem
2. Add scanning time and range multipliers for player ships
Resolves #4027
> add some new scan features

- code/pilotfile/plr.cpp
* Directly reference t_plr instead of player* p
Should fix issue #4057
> Clean out player t_plr before use

- code/menuui/mainhallmenu.cpp
- code/menuui/playermenu.cpp
- freespace2/freespace.cpp
Tweak the help for the 'bastion' command and change 'dcf_fov' to 'fov'.  Also add a new 'mainhall' command that can be used in the main hall, not just the player select screen.  And for good measure, makes main hall names case-insensitive.
> some debug console updates

- code/mission/missionmessage.cpp
FS1 has a feature which will occasionally convert a wingman message to a Command message.  This adds a few more checks to that feature:
1) Make the command-conversion code and the alive-check code mutually exclusive;
2) If the filename is not a FS1-style persona, don't change either a) the filename, or b) the talking head
Fixes #3759.
> be a little more careful about converting wingman messages to Command messages

- code/controlconfig/controlsconfigcommon.cpp
> Added error handling to map accesses in contronconfigdefaults parsing

- code/scripting/api/libs/mission.cpp
Add mn.getMissileList(), similar to mn.getShipList().  See also #3660.
> add missile list iterator

- code/decals/decals.cpp
- code/decals/decals.h
- code/scripting/api/libs/tables.cpp
- code/scripting/api/objs/decaldefinition.cpp
- code/scripting/api/objs/decaldefinition.h
- code/scripting/api/objs/model.cpp
- code/source_groups.cmake
This extends the existing decal system so that decals can be created through scripting.
~~Testing reveals there may be some unexpected problems preventing decals from working.  This is in draft status until this is resolved.~~  Now that #4053 has been merged, this PR has been tested and is out of draft status.
> add scripting support for decals

- code/menuui/playermenu.cpp
Elaborate the most common error message.  Follow-up to #4074
> follow-up to 4074

- fred2/eventeditor.cpp
Events with background colors had their highlighting behavior disabled, because since an event has to be selected to add a color, users thought the color adding didn't work.  However it was pointed out in #4129 that users still would like to know which event is selected.  So this PR attempts to solve the problem by drawing a border over a selected event if that event has a background color.
> address highlighting for events with background colors

- code/pilotfile/plr.cpp
- code/scripting/hook_api.h
This hook will be called whenever a player is successfully loaded.
> add player loaded hook

- code/gamesnd/eventmusic.cpp
- code/gamesnd/eventmusic.h
- code/mission/missionparse.cpp
- code/missionui/missionscreencommon.cpp
- code/parse/sexp.cpp
- fred2/FictionViewerDlg.cpp
- fred2/briefingeditordlg.cpp
- fred2/debriefingeditordlg.cpp
- fred2/missionnotesdlg.cpp
- fred2/sexp_tree.cpp
- qtfred/src/mission/dialogs/FictionViewerDialogModel.cpp
- qtfred/src/ui/dialogs/MissionSpecDialog.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
This removes the limits on soundtracks and menu music.  Some design tweaks are thrown in as well.
> vectorize Soundtracks and Spooled_music

- ci/linux/clang_tidy.sh
- code/ai/aigoals.cpp
- code/globalincs/systemvars.cpp
- code/globalincs/systemvars.h
- code/globalincs/windebug.cpp
- code/hud/hudtarget.cpp
- code/mission/missionmessage.cpp
- code/mission/missiontraining.cpp
- code/parse/sexp.cpp
Turn `insertion_sort` into a templated function that uses assignment, so that it can be used with non-POD types.  Also make the sort do lazy-copying of elements and make a few other tweaks to the function.
> Insertion sort update

- code/camera/camera.cpp
- code/camera/camera.h
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/parse/sexp.cpp
What it says on the tin.  This allows more precise positioning of subtitles, and a future PR will add the ability to scale them according to screen resolution.
> add game_settings.tbl option to specify subtitle coords in pixels

- lib/prebuilt.cmake
Update prebuilt.cmake::PREBUILT_VERSION_NAME to latest (short) SHA-1
> Update PREBUILT_VERSION_NAME to latest (mac libs)

- code/mission/missionparse.cpp
- code/object/object.cpp
- code/parse/sexp.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
PR #4174 added this feature, this PR allows it to be useable with FRED.
> Fix FRED accessibility of new flag `ai-attackable-if-no-collide`

- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/VolumeEffect.cpp
- code/particle/effects/VolumeEffect.h
Adds a random spawn chance to particle effects. Implements #3587, with testing by requestor. Originally submitted in draft while testing was completed, now ready.
> Random chance of particle spawning

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.cpp
- qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/src/ui/dialogs/ReinforcementsEditorDialog.cpp
- qtfred/src/ui/dialogs/ReinforcementsEditorDialog.h
- qtfred/ui/ReinforcementsDialog.ui
Creates a working version of the reinforcements Dialog.
Still needs one more bug fixed before merging.
> Reinforcements Dialog

- code/lighting/lighting_profiles.cpp
I left a very reachable assert in the lighting profiles parsing. This cleans that up.
> Bad lpt line

- fred2/fred.rc
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
> Clearer Paste function names and saner defaults

- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
Requires the unrelated fix from PR #4018 to work properly.
> Implement Replace Data for Number and String in qtFRED

- fred2/addmodifycontainerdlg.cpp
- fred2/addmodifycontainerdlg.h
Add the functionality needed to get the "Save changes?" pop-up that PR #4243 added working correctly.
> Implement query_modified() for Add/Modify Container FRED dialog

- code/parse/sexp.cpp
Alt-names with hashes that were added by the `change-alt-name` sexp used to have their hashes truncated properly.  This most likely broke when hash truncation was moved from the HUD code to the "display name" code.  This PR truncates hashes in the same way as truncation elsewhere.
> fix assignment of alt-name when using the hash

- code/mission/missionmessage.cpp
- code/mission/missionparse.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/parse/sexp.cpp
- code/parse/sexp_container.cpp
- code/parse/sexp_container.h
- code/scripting/api/objs/message.cpp
- fred2/bgbitmapdlg.cpp
- fred2/briefingeditordlg.cpp
- fred2/campaigneditordlg.cpp
- fred2/campaigntreewnd.cpp
- fred2/cmdbrief.cpp
- fred2/debriefingeditordlg.cpp
- fred2/management.cpp
- fred2/management.h
- fred2/missiongoalsdlg.cpp
- fred2/missionnotesdlg.cpp
- fred2/missionsave.cpp
- fred2/orienteditor.cpp
- fred2/shipeditordlg.cpp
- fred2/voiceactingmanager.cpp
- fred2/waypointpathdlg.cpp
- fred2/wing_editor.cpp
- qtfred/src/mission/missionsave.cpp
- test/src/parse/test_replace.cpp
- test/src/source_groups.cmake
Also add some test cases for checking correct behavior.
> guard against off-by-one errors in replace_one and replace_all

- code/ai/aigoals.cpp
- code/ship/ship.h
In the process of looking through `num_waves` and `current_wave` for #4267, I found a couple of confusing bits of code.  This clarifies things.
> some wing wave cleanup

- code/scripting/api/libs/ui.cpp
This must have been coded as `ui:maybePlayCutscene` when it should be `ui.maybePlayCutscene`
> fix maybePlayCutscene arguments

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipTBLViewerModel.cpp
- qtfred/src/mission/dialogs/ShipTBLViewerModel.h
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.h
- qtfred/src/ui/dialogs/ShipTBLViewer.cpp
- qtfred/src/ui/dialogs/ShipTBLViewer.h
- qtfred/ui/ShipTBLViewer.ui
Adds TBL Viewer to the ship editor
No picture as it looks identical to the old one.
> Add TBL Viewer

- code/io/timer.cpp
- code/io/timer.h
- code/network/multi.cpp
- code/network/multi.h
- code/network/multi_fstracker.cpp
- code/network/multi_ingame.cpp
- code/network/multi_kick.cpp
- code/network/multi_observer.cpp
- code/network/multi_options.cpp
- code/network/multi_pmsg.cpp
- code/network/multi_pxo.cpp
- code/network/multi_respawn.cpp
- code/network/multi_voice.cpp
- code/network/multi_xfer.cpp
- code/network/multimsgs.cpp
- code/network/multiui.cpp
- code/network/multiutil.cpp
- code/object/collideshipship.cpp
- freespace2/freespace.cpp
A bit overkill for some of this but just covering the bases.
* fix issues with in-game join
* fix multi messaging and multi pause screen
* make sure maintenance stuff (pings, voice, file xfer, etc.) isn't
affected by pausing or time compression
* fix sync issues caused by options menu and screenshots
> address multiple timestamp issues with multi

- code/scripting/api/libs/hud.cpp
Add a scripting function to return the distance as seen on the HUD.
> add hu.getTargetDistance()

- fred2/fred.rc
- fred2/sexp_tree.cpp
> Fix FRED Add/Replace

- code/parse/sexp/LuaAISEXP.cpp
The feature was already largely implemented in #4198, this just finishes the parsing for it.
> Activate LuaAI custom message parsing

- code/ai/aiturret.cpp
- code/io/cursor.cpp
- code/io/timer.cpp
- code/io/timer.h
- code/ship/ship.cpp
Add `timestamp_since()` and modify a few places that use `timestamp_until()`.
> add timestamp_since

- code/io/timer.cpp
- code/io/timer.h
Add methods to compare timestamps, as well as methods to calculate deltas from existing timestamps.
Follow-up to #4286.
> timestamp comparisons

- code/hud/hudtargetbox.cpp
Small follow-up to #4313 based on review comments that were 2 minutes too late.
> minor cleanup of turret names

- .github/workflows/build-nightly.yaml
- .github/workflows/build-test.yaml
- .github/workflows/test-pull_request.yaml
- CMakeLists.txt
- ci/linux/configure_cmake.sh
- ci/linux/create_dist_pack.sh
- ci/linux/run_tests.sh
Add CI setup for Mac builds. Does not do release builds yet.
> Set up Mac builds on CI

- code/ship/shipfx.cpp
Due to both the AI code and the ship movement code calling warp departure logic, enabling `Framerate_independent_turning` caused ships with the no-departure-warp flag to depart twice.  Removing the call to `shipfx_actually_warpout` fixes this.
More fundamentally, this untangles and organizes the arrival and departure logic as it pertains to effects.  The actual arrival and departure code is moved to the `shipfx_actually_warpin` and `shipfx_actually_warpout functions`.  This simplifies `WarpEffect::warpEnd()` and allows `WarpEffect` and its subclasses to only concern themselves with the visual effects.
This also fixes a logging statement that could never actually be printed due to `delta_ms` being the wrong sign in the if() check.
Fixes the transport departure objective checks in Shrouding …
> clean up ship arrival and departure effects

- code/graphics/color.cpp
- code/graphics/color.h
- code/graphics/opengl/gropengldeferred.cpp
- code/lighting/lighting.cpp
- code/lighting/lighting.h
- code/lighting/lighting_profiles.cpp
- code/lighting/lighting_profiles.h
- code/object/object.cpp
- code/parse/parsehi.cpp
- code/parse/parsehi.h
- code/source_groups.cmake
- code/weapon/beam.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Configurable lighting data for weapons, both on a per-weapon basis and globally via lighting profiles. 
I will be doing a bit more testing to makes sure last minute changes or history rewriting didn't break anything, but this is now ready to review.
> Weapon lights

- code/network/multi_sexp.cpp
- code/network/multi_sexp.h
- code/parse/sexp.cpp
Addresses some multi sexp issues:
* try to handle incompatible sexp packets better
* fix operator name issue with debug messages
* enable the new show-subtitle-text options
> Multi sexp fixes

- code/mission/missionparse.cpp
- code/network/multi_ingame.cpp
- code/network/multi_interpolate.cpp
- code/network/multi_interpolate.h
- code/network/multi_obj.cpp
- code/network/multi_obj.h
- code/network/multi_respawn.cpp
- code/network/multi_time_manager.cpp
- code/network/multi_time_manager.h
- code/network/multimsgs.cpp
- code/object/collideshipship.cpp
- code/object/object.cpp
- code/object/object.h
- code/ship/ship.cpp
- code/source_groups.cmake
- freespace2/freespace.cpp
Base interpolation timing on Missiontime on remote instance vs. Mission time on the local instance.  
Based on the limited testing that I've done so far, it seems to fix the jerkiness that used to occur when the interpolation code basically guessed the timing on when packets were coming in.  It is also a cleaner and easier to read solution than the last one.
More testing required before merge, but it's in a good enough state to start being reviewed.
Closes #3042
> Interpolation Overhaul 2

- code/parse/sexp.cpp
> tweak strdup handling for argument vector

- code/hud/hudreticle.cpp
- code/localization/localize.cpp
Add entries requested by @Achille44.  Fixes #4259.
> add additional XSTR entries

- code/missionui/missionshipchoice.cpp
Attempt a simpler solution to Issue #4335 than PR #4396.
> Handle weapons-locked slots that aren't ship-locked in selection screens.

- code/lab/manager/lab_manager.cpp
- code/lab/renderer/lab_renderer.cpp
- code/lab/renderer/lab_renderer.h
Make sure that changing team colors only happens when there are team colors to change and only dump the envmap to disk if there actually is an envmap to dump.
Fixes #4415
> Two minor lab fixes

- code/ai/ai.h
- code/ai/aicode.cpp
- code/scripting/api/objs/ai_helper.cpp
Followup to #4406, properly fixing the rotation controls in a way that is both predictable and intuitive.
> Followup improvement for the LuaAI AI Control Helper

- code/scripting/api/libs/controls.cpp
Fixes #4173 
...Was it really that simple? 😩
> Flush the mouse state after toggling between Use_mouse_to_fly states

- code/scripting/api/objs/modelinstance.cpp
- code/scripting/api/objs/subsystem.cpp
The two `VIRTVAR`s for Orientation in subsystems and submodel instances do the same thing, but did not have the same code - in particular, the subsystem version did not update the subsystem angle and turret angle.  This syncs them up.
> sync Orientation virtvars

- code/scripting/api/objs/subsystem.cpp
This sent me on a small goose chase so let's clarify this.
> Small clarity edit to getTurretHeading() docs

- code/fireball/fireballs.cpp
- code/fireball/fireballs.h
- code/ship/ship.cpp
Fixes the only two gcc12 warnings by being more explicit
> Fix gcc12 warnings

- cmake/version.cmake
> Bump to 22.3

- fred2/fred.rc
- fred2/fredview.cpp
- fred2/fredview.h
- fred2/resource.h
> add x500 and x1000 movement speeds

- code/graphics/2d.cpp
- code/scripting/api/libs/graphics.cpp
- code/scripting/api/libs/graphics.h
- code/scripting/lua.cpp
- code/scripting/scripting.cpp
- code/scripting/scripting.h
There's no need to keep all this infrastructure to run every frame for a barely used situation.  This cleans it up a bit and does the position reset in the actual drawString function.
> clean up Lua frame handling a bit

- code/graphics/2d.cpp
Thanks to MjnMixael for catching this.
> Fix misspelled ID name for in-game options

- code/network/multi_interpolate.cpp
- code/network/multi_interpolate.h
- code/network/multi_obj.cpp
- code/network/multi_obj.h
- code/object/object.cpp
Has now been tested and is shown to improve collisions.  We are still having some issues with weapon-ship collisions which needs more investigation.
> Multi collision fix (ship-ship) collisions

- code/ai/ai.h
- code/ai/aigoals.cpp
- code/ai/aigoals.h
- code/autopilot/autopilot.cpp
- code/mission/missionparse.cpp
- code/parse/sexp.cpp
1) Move ai_goal definitions into aigoal.h
2) Add a proper `ai_goal_reset` function to clear goal fields to known initialized values
3) Add an optional distance to `ai-stay-near-ship`
> Ai goal refinement

- code/scripting/api/objs/ship.cpp
A simple copy of the same function on `ai_helper`, now usable on plain ships too.
> Script function for turnTowardsPoint

- code/scripting/api/objs/subsystem.cpp
> Script function for turret fov testing on positions

- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/shipclass.cpp
Give Lua access to a ship's scan time fields. Per FR #4546
> Lua scan time

- code/io/mouse.cpp
Implement correct display strings for scpui Mouse Option. Fixes #4527
> Mouse option strings

- code/scripting/api/objs/ai_helper.cpp
> Add turnTowardsOrientation

- code/lab/renderer/lab_cameras.cpp
And also lower zoom sensitivity, it's way too sensitive.
> Cap lab zoom distance

- code/cutscene/cutscenes.cpp
Allows adding additional cutscenes from a modular table. Resolves #3693
> Make cutscenes.tbl extendable with -csn.tbm

- fred2/eventeditor.cpp
- fred2/eventeditor.h
- fred2/fred.rc
- fred2/resource.h
- fred2/voiceactingmanager.cpp
- fred2/voiceactingmanager.h
Four new functions relating to synchronizing personas...
1) Copy personas from messages to ships
2) Copy personas from ships to messages
3) Clear personas from ships that don't send messages
4) Set head ANIs using personas in messages.tbl
> Voice acting manager enhancements

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/loop_brief.cpp
- code/scripting/api/objs/loop_brief.h
- code/source_groups.cmake
Should be everything required. Tested both accepting and denying a loop using these functions sends the player to the correct mission and sets the exit loop mission correctly as well.
> Scripting functions required for SCPUI conversion of Loop Brief.

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/redalert.cpp
- code/scripting/api/objs/redalert.h
- code/source_groups.cmake
Should be everything required. Tested both committing to a mission and replaying the previous mission using these functions and it seems to work as expected.
> Scripting functions required for SCPUI conversion of Red Alert

- code/scripting/api/libs/ui.cpp
These are useful in places beyond just Command Brief.
> Some User Interface API cleanup and generalization

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/debris/debris.cpp
- code/debris/debris.h
- code/io/timer.h
- code/object/object.cpp
- code/scripting/api/objs/debris.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
Mostly debris and asteroid timestamps, but also arc timestamps for ships.
> convert some timestamps to the new system

- code/menuui/mainhallmenu.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/scripting/api/libs/base.cpp
Add $Mod Title: and $Mod Version: to game_settings.tbl and display them on the mainhall similar to FSO version. Also add base Lua access (again just like FSO version) to those entries. Resolves #3417
> Add $Mod Title and $Mod Version options to game_settings.tbl

- code/scripting/scripting.cpp
- code/scripting/scripting.h
> defer adding new scripting hooks until after hook processing is done

- code/mission/missionparse.cpp
- code/ship/ship.cpp
- code/species_defs/species_defs.cpp
- code/species_defs/species_defs.h
For when you want to share a support ship between species. For BTA, but hey, maybe someone else wants to use species for organization like we do.
Closes #3352
> Allow assigning support ship per species

- code/missionui/missionshipchoice.cpp
Exactly what it says on the tin. For mission design trickery.
> Respect hashes in ship and wing names in the loadout screen

- code/scripting/api/objs/object.cpp
Surprised it hasn't been added before now.
> add Radius virtvar for objects

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/network/multi_interpolate.cpp
- code/network/multi_interpolate.h
This adds interpolation of matrices via axis angle calculations, and a way to calculate last orient from angular velocity.  The physics code is from @Baezon, with just a few edits.  We've tested and everything works as expected.
> Add interpolate matrices for multi

- code/math/vecmat.cpp
Follow-up to #4417. Even if the ship has reached its target position it may still need to bank and so should continue if non-zero.
> Small fix for banking using AI functions

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/scripting/api/objs/vecmath.cpp
Add script support for rotational interpolation of matrixes (orientations) and vectors.
> rotational interpolation

- code/scpui/elements/ScrollingTextElement.cpp
- code/scpui/elements/ScrollingTextElement.h
- code/scripting/api/libs/mission.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/briefing.cpp
- code/scripting/api/objs/briefing.h
- code/source_groups.cmake
This is everything required but the icon map itself, though it does include a placeholder API function for my own sanity and the sanity of the scripts until I can spend time getting it working.
> SCPUI API elements required for the Briefing

- code/scripting/scripting.cpp
- code/scripting/scripting.h
Basically just changing some parameter names.
> small hook refactor

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/fictionviewer.cpp
- code/scripting/api/objs/fictionviewer.h
- code/scripting/api/objs/loop_brief.cpp
- code/scripting/api/objs/loop_brief.h
- code/scripting/api/objs/redalert.cpp
- code/scripting/api/objs/redalert.h
Based on feedback from other PRs, this cleans up the API for these bits. Works as expected in testing.
> Cleanup Fiction, Red Alert, and Loop Brief

- code/actions/common.h
- code/actions/types/WaitAction.cpp
- code/autopilot/autopilot.cpp
- code/autopilot/autopilot.h
- code/controlconfig/controlsconfig.cpp
- code/hud/hudartillery.cpp
- code/hud/hudartillery.h
- code/io/joy-sdl.cpp
- code/io/joy.h
- code/io/timer.cpp
- code/io/timer.h
- code/object/objectsnd.cpp
- code/parse/sexp.cpp
More conversion of timestamps to the new system.  Follow-up to https://github.com/scp-fs2open/fs2open.github.com/pull/4569.
> more timestamp migration

- code/def_files/data/effects/deferred-f.sdr
- code/def_files/data/effects/deferred-v.sdr
- code/def_files/data/effects/lighting.sdr
- code/def_files/data/effects/main-f.sdr
- code/def_files/data/effects/main-g.sdr
- code/def_files/data/effects/main-v.sdr
- code/graphics/light.cpp
- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/util/uniform_structs.h
- code/lighting/lighting.cpp
- code/lighting/lighting.h
- code/lighting/lighting_profiles.cpp
- code/missionui/missionscreencommon.cpp
- code/model/modelrender.cpp
- code/object/object.cpp
- code/weapon/beam.cpp
@EatThePath has suggested some increases to light brightness necessary because of the improved shaders introduced by #4652 and #4653.
> Light power fix

- code/scripting/api/objs/ship.cpp
A script command to mirror the SEXP operator.
> add stopLoopingSubmodelAnimation

- code/model/modelanimation.cpp
> a couple of animation fixes

- code/ship/ship.cpp
If this is trivial and not needed feel free to dismiss, but this one-line PR simply fixes a warning that keeps showing up when building with VS.
> Fix VS Warning

- code/model/modelanimation_segments.cpp
- code/model/modelanimation_segments.h
Enhances the Translation Segment by Absolute positioning
> Add Absolute Translation

- code/source_groups.cmake
Small organizational thing. These go under objs not libs.
> These go here

- code/scripting/api/libs/mission.cpp
Add isInMission and changes getMissionTime to always return the mission time even outside of a mission
> Mission time

- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
This mirrors alter-ship-flag and are-ship-flags-set.
~~Currently in draft pending testing.~~  After testing (with valuable assistance from @wookieejedi) and some additional features including arbitrary arguments and a parse-object indexer, this is ready for review.
> add setFlag and getFlag for ships and parse objects

- code/scripting/lua.cpp
Just adding 1 missing include. Confirmed fix in testing.
> Fix multi lib

- code/osapi/dialogs.cpp
- code/osapi/outwnd.cpp
- code/scripting/api/libs/base.cpp
> Unify the two forms of default filters and consolidate the new lua category into scripting

- code/missionui/missionshipchoice.cpp
- code/missionui/missionshipchoice.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/shipwepselect.cpp
- code/scripting/api/objs/shipwepselect.h
- code/source_groups.cmake
Gives Lua access to the loadout wing slots. I had considerable trouble with this one due to lack of coding skill. Open to suggestions.
This is the first PR of several required to get ship and weapon select fully functional.
> Scpui ship select

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/shipwepselect.cpp
- code/scripting/api/objs/shipwepselect.h
Provides read-only access to the actual loadout used to setup the mission. A later PR will add the ability to write to these values.
> Lua API read-only access to the actual loadout

- code/scripting/api/libs/ui.cpp
API access to the ship and weapon loadout pools. Relies on #4694
> Scpui loadout pools

- code/missionui/missionscreencommon.h
- code/missionui/missionshipchoice.cpp
- code/network/multiui.cpp
- code/scripting/api/libs/ui.cpp
Converts `create_wings()` from an int to `commit_pressed_status` enum
> Handle errors from create_wings() in an API friendly way

- code/scripting/api/objs/shipclass.cpp
Fix getting bank capacity. Should take user data instead of an int and return an int instead of a float.
> take userdata and return int

- code/scripting/api/objs/shipclass.cpp
Fix bug where checking the last bank on the ship always returned false
> Only check for greater than, not equal to

- code/scripting/api/objs/shipclass.cpp
Fix comparing secondary bank index to num primary banks
> primary -> secondary

- code/scripting/api/objs/ship.cpp
> add WaypointSpeedCap

- code/missionui/missionscreencommon.cpp
- code/missionui/missionscreencommon.h
- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
Adds an API to render the 3D select for ships and weapons at arbitrary coordinates and at arbitrary size.
> Api to render the 3d selection effect

- code/scripting/api/libs/engine.cpp
Using lua dev mode can make for unweildly log files after a while, this lets the scripter start over if they want.
> Added an API function to allow clearing the log during play.

- code/cfile/cfile.cpp
- code/cfile/cfilesystem.cpp
- code/inetfile/inetgetfile.cpp
- fred2/freddoc.cpp
- consolidate old and new functions
- add missing location flags override from earlier fix
- add proper error handling where needed
> fix and clean up cf_create_default_path_string()

- code/mission/missionparse.cpp
> fix a last-minute error check

- code/anim/animplay.cpp
- code/bmpman/bmpman.cpp
- code/cmdline/cmdline.cpp
- code/gamesnd/gamesnd.cpp
- code/graphics/generic.cpp
- code/graphics/opengl/gropenglshader.cpp
- code/graphics/opengl/gropengltexture.cpp
- code/lighting/lighting_profiles.cpp
- code/model/modelread.cpp
- code/scripting/api/libs/base.cpp
This is a number of items that to me practically never have general log value and hide things that do have value. So, if anything shouldn't be hidden away like this, by all means say so
> Moved more things to debug filters, and associated cleanup

- code/iff_defs/iff_defs.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/wing.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/ship_flags.h
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
Add setFlag and getFlag for wings, just like for ships and parse objects.  Also some minor refactoring.  And fix `PARSEABLE_WING_FLAGS` which was a bit too low.
> add wing flags

- code/scripting/api/objs/techroom.cpp
> These were reversed

- code/object/collideshipship.cpp
Fix a typo in `collide_ship_ship`.  Also tweak some lines for clarity.
> collision fix

- code/cmdline/cmdline.cpp
- code/cmdline/cmdline.h
- code/fireball/fireballs.h
- code/fireball/warpineffect.cpp
Add warp flash to the list of flags the ingame options can modify (with scpui). Tested and working.
> add warp flash to ingame options

- code/scripting/api/objs/weaponclass.cpp
Adds a read-only virtvar to get the energy consumed of weaponclass
> Virtvar to access the energy a weapon consumes

- code/render/3dsetup.cpp
This bump should be sufficient to cover complex animation states. This fixes #4794
> Bump the MAX_INSTANCE_DEPTH constant to 32

- code/debris/debris.cpp
- code/debris/debris.h
- code/hud/hudtargetbox.cpp
- code/model/modelrender.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/enums.cpp
- code/scripting/api/objs/enums.h
- code/scripting/lua/LuaConvert.cpp
- code/scripting/lua/LuaConvert.h
This is a new Lua API function that allows creation of arbitrary debris pieces, whether chunks of a ship's hull or shards of shrapnel.  All of the parameters are optional, and a wide variety of situations are possible ranging from vaporized bits to static chunks to chunks propelled by an explosion.
> create debris using script functions

- code/graphics/shadows.cpp
> handle debris model instances correctly when shadows are enabled

- code/menuui/playermenu.cpp
- code/menuui/playermenu.h
- freespace2/freespace.cpp
Implements remapping of keys in tips.tbl. Closes #4648
> translate key tokens in tips

- code/globalincs/systemvars.cpp
- code/globalincs/systemvars.h
- code/mission/missionparse.cpp
- code/model/modelinterp.cpp
- code/model/modelrender.cpp
- code/model/modelrender.h
- code/parse/sexp.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/starfield/starfield.cpp
- code/starfield/starfield.h
- freespace2/freespace.cpp
- freespace2/freespace.h
Timestamp changes for texture animation, both on ships and on the skybox.
> upgrade texture animation code to use new timestamps

- freespace2/freespace.cpp
So a script can act on, or overwrite main camera data as it is about to be used.
> Add $On Camera Set Up hook

- code/physics/physics.cpp
- code/physics/physics.h
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
Add setDocked, setUndocked, and jettison.  All have been tested.
> add a few scripting dock functions

- code/menuui/playermenu.cpp
Vectorize tips to remove the limit of 40 and make the table extendable with -tip.tbm
> Modular tips

- code/mission/missionparse.cpp
- code/nebula/neb.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Makes nebula.tbl extendable with -neb.tbm. Closes #3581
> implement modular nebula.tbl

- code/scripting/api/libs/ui.cpp
Badge name instead of Rank would be preferred here.
> properly get badge name

- code/iff_defs/iff_defs.cpp
With unlimited IFFs, it'd be nice to be able to modify and organize them using modular table features, so this implements that functionality.
> Modular iff table

- code/scripting/api/objs/ship.cpp
> add numDocked and isDocked

- code/lab/renderer/lab_renderer.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/nebula/neb.cpp
- code/nebula/neb.h
- code/object/waypoint.cpp
- code/object/waypoint.h
- code/ship/ship.cpp
- code/ship/ship.h
- code/starfield/nebula.cpp
- code/starfield/nebula.h
- code/starfield/starfield.cpp
- fred2/bgbitmapdlg.cpp
- fred2/dumpstats.cpp
- fred2/freddoc.cpp
- fred2/fredrender.cpp
- fred2/fredrender.h
- fred2/management.cpp
- fred2/missionsave.cpp
- fred2/wing.cpp
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/EditorWing.cpp
- qtfred/src/mission/management.cpp
- qtfred/src/mission/missionsave.cpp
Gather all the mission initialization code into a common function for clarity and ease of expansion.  Previously, the various parsing routines contained initialization as well as parsing.  As a bonus, quite a few redundant initializations are streamlined.
~~This is in draft status pending testing.~~
> refactor mission initialization

- code/lab/manager/lab_manager.cpp
> fix lab CTD

- code/ai/ai.cpp
- code/ai/ai.h
- code/ai/aicode.cpp
- code/autopilot/autopilot.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/ship/ship.cpp
- fred2/management.cpp
- fred2/missionsave.cpp
- fred2/wing.cpp
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/missionsave.cpp
Remove `behavior`, `type`, and `wing`, which are either unused or redundant.
> clean up some obsolete fields

- code/asteroid/asteroid.h
- code/globalincs/globals.h
Increases limits as discussed in #SCP. I'm in no big hurry to get this committed, but submitting the PR to ensure the discussion is finished and a decision is made on the best numbers to use.
> increase object limits

- code/model/modelinterp.cpp
Fixes #4887.  Follow-up to #4704.
> use correct math for animated textures

- code/cmdline/cmdline.cpp
- code/globalincs/flagset.h
- code/hud/hudshield.cpp
- code/io/timer.cpp
- code/io/timer.h
- code/mission/missionparse.cpp
- code/network/multi.h
- code/network/multi_ingame.cpp
- code/network/multi_obj.cpp
- code/network/multi_team.cpp
- code/network/multi_time_manager.cpp
- code/network/multi_time_manager.h
- code/network/multimsgs.cpp
- code/network/multiui.cpp
- code/network/multiutil.cpp
- code/ship/ship.cpp
This has been a team effort with @notimaginative and @wookieejedi, working on this on and off for about 2 years.  Based on recent tests, this should fix all the final bugs.  This also makes in-game joining default on, which is what people expect these days, honestly.
Just waiting on some final tests to ensure everything is working.
> Fix in game joining 

- code/network/multiutil.cpp
Checking the wrong subsystem instance here, causing a crash.
> Make sure that we check the correct instance

- code/missionui/missionscreencommon.cpp
- code/mod_table/mod_table.cpp
Initialize overhead style in correct place and allow initialization of some colors so the overhead lines can be drawn with the correct color.
> Fix overhead style

- code/nebula/neb.cpp
> Check nebula and poof bitmaps at parse time

- code/ai/aigoals.cpp
- code/hud/hudsquadmsg.cpp
- code/mission/missionparse.cpp
- code/ship/ship.cpp
- code/ship/ship.h
Fixes #4899 by storing the wing leader's ship type in the wing struct and using that to look it up isntead of trying to look up a ship that might not be there.
> Add special ship info index

- code/ai/aicode.cpp
This is just a much simpler and cleaner version of the same check.
Closes #4530
> Move the assertion

- code/mission/missionparse.cpp
- code/ship/ship.cpp
This fixes both pre-mission and in-mission crashes regarding special_ship_ship_info_index
Also adds an adjustment to sssi when a ship in a wing dies.
> Adjust ssssssssssi in one more place

- code/object/objcollide.cpp
> Fix an oversight in collision code from recent changes

- code/model/modelanimation_segments.cpp
- code/model/modelanimation_segments.h
This helps for use cases where you want sounds to play after the animation has completed
> Add '+Don't Interrupt Playing Sounds'

- code/nebula/neblightning.cpp
- code/nebula/neblightning.h
Modular lightning table with better errors (proper warnings and errors instead of asserts) and a little general cleanup to use fewer casts; make the code more readable.
> Modular bolts

- code/scripting/api/libs/cfile.cpp
Also updates function description to be more accurate and document filter format for subfolder searches.
fixes #4939
> add proper support of subfolders to lua listFiles

- code/cfile/cfile.cpp
> use case-insensitive comparison of cfile pathtypes

- code/parse/sexp.cpp
Two situations in the event timestamp life cycle, chain delays and event status delays, require accommodation for the timestamp-plus-interval case described in `mission_process_event()`.  Commit 06fc8c73 applied the fix for chain delays; this applies the same fix to event status delays.
Follow-up to #4633.  Fixes #4951.
> fix event status evaluation for repeating events

- code/parse/sexp.cpp
- code/parse/sexp.h
Enhance set-primary-weapon and set-secondary-weapon to check the validity of the weapon bank and weapon type.
> add some additional weapon checks

- code/ship/ship.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Adds the ability to do autoaim on a per weapon basis in addition to per ship or globally from ai profiles.
> per weapon auto aim feature

- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
Add a SEXP to change the formation and formation scale on-the-fly.
> add changeable formation flying

- code/scripting/api/libs/mission.cpp
- code/ship/ship.cpp
- code/starfield/starfield.cpp
Also forgot to account for interaction with ship templates again.
> Fix edge case bugs with moveables in combination with special polymodels being animated

- code/ai/aicode.cpp
Whether a ship is a support ship or its target, and whether it is destroyed or vanished, its repair/rearm mode should be cleaned up in a consistent way.  This fixes a bug in Series Resurrecta where calling `ship-vanish` on a support ship put things into a broken state.
> clean up support ship mode in all cases

- code/scripting/api/objs/beam.cpp
Add a Team virtvar to beam objects in Lua.
> beam teams

- code/ai/aicode.cpp
> fix vintage copypasta bug

- code/scripting/global_hooks.cpp
> Fix OnBeamCollision Oversight

- ci/post/nebula.py
Also includes replacement of string literals with constants to reduce maintenance overhead in the event the name of a group changes.
> Fix failure to post Mac builds to forums

- code/scripting/api/libs/hud.cpp
A script function to tell if the comms menu is open
> add hu.isCommMenuOpen

- code/ai/ai_profiles.cpp
- code/mod_table/mod_table.cpp
- code/scripting/api/objs/enums.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Since these features were added before it was known the next version would be 23.0.
> Update 22.4 version references to 23.0

- code/model/modelrender.cpp
- code/model/modelrender.h
- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
Moves most of the renderTechModel and renderTechModel2 stuff into a single method in modelrender.cpp. Fixes #4628
> consolidation of tech rendering methods

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/briefing.cpp
Add some error checking here to prevent lua scripts from causing a CTD by access a goal outside the valid range.
> prevent access to goals outside the vector

- code/mission/missiongoals.cpp
Add a useful summary to the comment about event timestamps.
> comment tweak

- code/io/joy-sdl.cpp
> use correct joystick id type (instance -> device)

- code/io/joy-sdl.cpp
> swap loop order to fix joystick detection issue

- code/model/modelread.cpp
Add some checks during model load for submodel indexes that could be out of range due to a corrupt model.
> add some sanity checks for submodel indexes

- cmake/version.cmake
> bump version to 23.1.x

- code/asteroid/asteroid.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
Quick hook for when an asteroid has been created. Not overridable and has hv.Asteroid.
> On asteroid created hook

- code/missionui/missionpause.cpp
- code/missionui/missionpause.h
- code/scripting/api/libs/ui.cpp
Implements a few things required for SCPUI to properly handle the pause screen either from the PAUSE key or if FSO loses focus during a mission.
> funcs and virtvars for SCPUI pause screen

- code/ai/aicode.cpp
Makes ai.tbl modular with -aic.tbm. The real benefit is modifying previously parsed classes, but adding via tbm is also allowed. In that case a warning is printed to the log that it may affect ai autoscaling since autoscaling works with the ai class index position. However, the effects of that can be limited or removed with other existing table options, so it's really up to the modder on that.
> modular ai classes table

- code/autopilot/autopilot.cpp
It's a small table, but it's silly to force mods to define most parameters if they only want to change a single option. So let's make it modular, non-XMT to match how game_settings.tbl works.
> modular autopilot table

- code/parse/sexp/LuaSEXP.cpp
Adds "hudgauge" which lists OPF_ANY_HUD_GAUGE and returns a hudgauge handle. Also adds "event" which lists OPF_EVENT_NAME and returns an event handle.
> Add two additional Lua Sexp Parameters

- code/scripting/global_hooks.cpp
> Match documentation description to actual hook names.

- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
These small changes are required to get qtFRED building again
> missed items required to build qtfred

- code/ship/ship.cpp
- code/ship/ship.h
Adds per-bank autoaim setting as requested by Wookie. The highest autoaim fov out of mission-profile/ship/bank/weapon takes precedence.
> per bank autoaim

- code/cutscene/cutscenes.cpp
- code/cutscene/cutscenes.h
- code/scripting/api/objs/techroom.cpp
Works exactly like ship and weapon class custom data.
> Cutscene custom data

- code/osapi/osapi.cpp
- code/osapi/osapi.h
- code/scripting/api/libs/base.cpp
> Lua method to check if the game has focus

- code/scripting/api/objs/audio_stream.cpp
- code/sound/audiostr.cpp
- code/sound/audiostr.h
ADE_FUNC to get the duration of an audiostream.
> get audiostream duration in float seconds

- code/ai/aiturret.cpp
- code/parse/sexp.cpp
- code/parse/sexp.h
- code/ship/ship.cpp
- code/ship/ship.h
> Add `turret-fired-since` SEXP

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- freespace2/freespace.cpp
Quick flag to apply hud shudder (afterburner and engine wash) also to chase view. Does not override the command line toggle. Fixes #3563
> Flag to apply hud shudder to chase view

- code/scripting/api/objs/briefing.cpp
A couple more goal related virtvars I'll need for SCPUI
> Add virtvars for goal satisfaction and score

- code/options/Option.cpp
- code/options/Option.h
- code/options/OptionsManager.cpp
Documents the built-in Options API to the best of my knowledge based on reading the code and using it extensively for SCPUI. Some bits of it are unclear, but this should help to demystify most of it and fix #4492 .
> Document options files

- code/ship/ship.cpp
A few ship flags were missing from these lists.
> add some ship flags to the alter-ship-flag lists

- code/menuui/techmenu.cpp
> fix Techroom_modelnum references

- code/parse/sexp.cpp
The change in my previous code to do it the way goober wanted caused an off by one error. Lesson learned. Don't use goober's suggestions blindly.
> Always test review-suggested code for errors

- qtfred/src/mission/missionsave.cpp
> Use qtfred style warning instead of fred style

- code/missionui/missionbrief.cpp
Small change to capitalize the built-in icon names to match all other icons generally.
> these should be capitalized

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/medals.cpp
- code/scripting/api/objs/medals.h
- code/scripting/api/objs/player.cpp
- code/scripting/api/objs/rank.cpp
- code/scripting/api/objs/rank.h
- code/source_groups.cmake
Adds an API to give access to the Medals and Ranks vectors as well as adding access to the current player's medals and rank.
> Scpui API for medals access

- code/mission/missionmessage.cpp
- code/stats/scoring.cpp
- qtfred/src/main.cpp
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp
- qtfred/src/mission/management.cpp
- qtfred/src/mission/management.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/ui/BriefingEditorDialog.ui
Fix various compilation warnings and errors.
> fix qtfred compilation

- code/controlconfig/controlsconfig.cpp
- code/controlconfig/controlsconfig.h
- code/controlconfig/presets.cpp
- code/controlconfig/presets.h
- code/scpui/rocket_ui.cpp
- code/scpui/rocket_ui.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/control_config.cpp
- code/scripting/api/objs/control_config.h
- code/source_groups.cmake
All the changes required for API access to managing controls. I was able to replicate all the retail options and functionality from Lua. I also tested that the retail UIs work the same as they did before.
> Scpui API for Control Config

- code/hud/hudets.cpp
- code/hud/hudets.h
- code/network/multi_ingame.cpp
- code/network/multi_respawn.cpp
- code/network/multimsgs.cpp
- code/parse/sexp.cpp
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
Follow-up for #5292. A little more thorough on when changes to ETS values should change the max ship speed, including equalizing, multi packets and sexps.
> Ets max speed fixes

- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/gamehelp.cpp
- code/scripting/api/objs/gamehelp.h
- code/scripting/api/objs/medals.cpp
- code/scripting/api/objs/medals.h
- code/scripting/api/objs/missionhotkey.cpp
- code/scripting/api/objs/missionhotkey.h
- code/scripting/api/objs/missionlog.cpp
- code/scripting/api/objs/missionlog.h
- code/scripting/api/objs/player.cpp
- code/scripting/api/objs/rank.cpp
- code/scripting/api/objs/rank.h
Many of the recent scripting API enhancements are missing validity functions and validity checks, so this adds them.  There are also some documentation fixes and a >= vs. > bugfix.
> add validity checks

- code/network/multi_ingame.cpp
Follow-up for #5317, these got accidentally swapped.
> Bugfix accidental swap in ets changes

- code/mission/missionmessage.cpp
- code/mission/missionmessage.h
- code/mission/missionparse.cpp
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/message.cpp
- fred2/eventeditor.cpp
- fred2/messageeditordlg.cpp
- fred2/missionnotesdlg.cpp
- fred2/missionsave.cpp
- fred2/sexp_tree.cpp
- fred2/shipeditordlg.cpp
- freespace2/freespace.cpp
- qtfred/src/mission/missionsave.cpp
Makes messages.tbl extendable with -msg.tbm. Fixes #4626
Also vectorizes Personas to make the modularization a little easier.
> Modular messages table

- code/model/modelanimation.cpp
- code/model/modelanimation_moveables.cpp
- code/model/modelanimation_moveables.h
- code/model/modelanimation_segments.cpp
- code/model/modelanimation_segments.h
- code/parse/sexp.cpp
Closes  #5263.
In order to facilitate Translation Moveables, a Set Offset animation segment was added as well.
> Add a Translation Moveable

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/debris/debris.cpp
- code/debris/debris.h
- code/network/multi.h
- code/network/multimsgs.cpp
- code/network/multimsgs.h
- code/object/collidedebrisship.cpp
- code/object/collidedebrisweapon.cpp
- code/parse/sexp.cpp
- code/scripting/api/objs/asteroid.cpp
- code/ship/ship.cpp
- code/weapon/beam.cpp
- code/weapon/shockwave.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Part of #5278. With the relevant flags, debris and asteroids can be whacked around too.
> Whackable debris and asteroids

- code/missionui/missiondebrief.cpp
- code/missionui/missiondebrief.h
- code/scripting/api/libs/ui.cpp
The bulk of this PR changes the API descriptions to remove the warnings that it's experimental or testing. As of this commit, I consider the API finalized and ready for general use.
One small addition is that this PR also changes three debrief API methods from using a global to using a parameter to match the rest of the API. Should be no change in functionality.
> Finalize scpui api

- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
These messages add the context of the actual SEXPs causing the warnings to be displayed.  Motivated by Admiral Nelson's mod debugging work.
> enhance some SEXP warnings

- code/particle/util/ParticleProperties.cpp
Turns out Velocity Lifetime Curve was never initialized.
> Fixes CTD with New Particle Lifetime Curve

- fred2/eventeditor.cpp
- fred2/fred.rc
- fred2/messageeditordlg.cpp
- fred2/resource.h
- fred2/sexp_tree.cpp
- qtfred/src/mission/missionsave.cpp
- qtfred/src/ui/dialogs/EventEditorDialog.cpp
- qtfred/src/ui/dialogs/MissionSpecDialog.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
1. Disambiguate dialog IDs for the music player and the volumetric nebula dialogs
2. Fix compilation of qtFRED
3. Small refactor of Personas access to use STL functions where appropriate
> some FRED cleanup

- code/parse/sexp.cpp
Since `rand_sexp` also writes text into the sexp node for the seed value, its cache should be cleared too.  And since this is a pretty common operation, wrap it in a `clear_cache` function.
Follow-up to #5381.
> clear caches for both nodes in rand_sexp

- code/scripting/api/objs/LuaEnum.cpp
This just needs to be converted from base 1 to base 0.
> Lua Enum Hotfix

- code/parse/sexp.cpp
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
Add a Lua function to check whether a ship is a player ship.
> add ship:isPlayer()

- fred2/management.cpp
So things that require curves can actually find them.
> Ensure curves are initialized in FRED

- code/globalincs/globals.h
- code/globalincs/pstypes.h
- code/globalincs/systemvars.cpp
- code/globalincs/vmallocator.h
- code/mission/missionmessage.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/model/modelanimation.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/parse/sexp.cpp
- code/ship/ship.cpp
- fred2/freddoc.cpp
Refactor and clean up some of the code, and add some fixes and utility functions.  This covers the non-X-Wing part of #5277.
> some cleanup and refactoring

- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/def_files/ai_profiles.tbl
- code/ship/shiphit.cpp
Surprisingly not a thing until now! Adds a difficulty dependent buff to player damage.
> Add player damage inflicted factor

- code/nebula/neb.cpp
- code/render/batching.cpp
- code/render/batching.h
This why they can do 'gentle' fades into geometry, instead of clipping into them.
> Use volume particles for poofs

- code/cfile/cfilesystem.cpp
Allows for loose lz4 files to be indexed and used properly by cfile. Based on changes from @Shivansps.
> add support for loose lz4 compressed files

- code/hud/hudsquadmsg.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
> add hooks for comm menu opening and closing

- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
> Quick fix to qtfred loading on linux

- code/model/modelreplace.cpp
- code/model/modelreplace.h
Allows modifying subsystem definitions
> Virtual POFs: Modify Subsystems

- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
A couple quick flags to see if a ship or weapon class is player allowed.
> Flags to see if a ship or weapon class is player allowed

- code/scripting/api/objs/shipclass.cpp
What it says on the tin. Grants Lua access to the default countermeasure class assigned to the ship class.
> Lua access to default countermeasure class

- code/mod_table/mod_table.cpp
As requested by a comment on #4543.
> add game_settings.tbl option to enable HUD drop shadows by default

- code/asteroid/asteroid.cpp
Fix #5448 . Was a typo and a copy/paste error from testing to final PR.
> Fix typo and copy/paste error

- code/ai/aicode.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Update `+Failure Launch Delay Multiplier for AI:` and `+Successful Launch Delay Multiplier for AI:` to floats instead of integers, following Discussion on Discord here: [https://discord.com/channels/223511295431933953/771694956707315752/1115787819680538697](url)
> Update Some Newish CM Options to Floats

- code/model/modelread.cpp
1. Check that a path index is in range
2. Check that a path's parent submodel is the same as the dockpoint's parent submodel
> add some additional safety checks for dockpoint paths

- code/controlconfig/controlsconfigcommon.cpp
Similar vein to #5476.
Same symptom, different cause.
This time, it was dangling LuaFunctions in the controls code hooks
> Properly deinit io-lib LuaFunctions

- code/mission/missionmessage.cpp
Personae have a flag and a species bitfield. They're built up during parsing, but never explicitly zeroed out. This leads to ships occasionally getting an incorrect persona (especially common with support ships, which never have an explicit persona).
Additionally, this commit addresses an issue with the UES Aranyaka (and potentially other support ships belonging to species without a support persona). I'm honestly not sure why they were ever able to speak; however, with this change, they'll never be able to. As such, this commit introduces a "default support persona" to retain the desired behavior.
> Explicitly zero out persona bitfields

- code/io/joy-sdl.cpp
Occasionally, we're still getting strange configuration errors with joysticks and controllers.  This PR adds some more checks and debug messages which may help track it down.
> Add more error checking in joy-sdl.cpp.

- code/parse/sexp.cpp
allow-ship and allow-weapon work for the player team, not just the "Terran" team.
Also removes the gay slur from ai-evade-ship because really?
> Correct a few sexp descriptions

- code/ai/aigoals.cpp
As reported by Woutersmits, the GTT Nova did not dock with the GTD Hall in the first mission of Black Horizon.  Attempting to run a debug build caused a CTD.  Investigation showed that there was an invalid dockpoint triggering an Int3().  The dockpoint has been fixed, but to aid troubleshooting in the future, the Int3()'s in this function have been changed to more appropriate functions.
> remove Int3()'s in ai_mission_goal_achievable

- fred2/mainfrm.cpp
1. Fall back to the FREDzone help docs if the local files cannot be found
2. Tweak url_launch error message and add a return value
This consequently removes the ReleaseWarning which wasn't the friendliest or clearest way to tell the user about a missing help file.
> improve launching of FRED help

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-standalone.yaml
- .github/workflows/build-test.yaml
- .github/workflows/cache-master.yaml
- .github/workflows/post-build-release.yaml
- .github/workflows/test-pull_request.yaml
Revert #5547, per suggestion from @asarium, to try to fix #5571.  Reverting 5547 also implies reverting #5580.
> Revert 5547 and 5580

- code/scripting/api/objs/player.cpp
Not sure how this snuck in but this get arg parameter needs to be fixed or the call doesn't actually work.
> Fix Lua API Error with Player Stats

- cmake/util.cmake
CMake's copy_directory functions follow symlinks recursively as opposed to preserving them. For mac frameworks, which make use of symlinks for versioning, this causes the files to be duplicated multiple times in the copied framework. Using rsync instead, just for frameworks, will properly duplicate the framework while still avoiding the "file exists" error from cp.
> tweak directory copying for frameworks on macOS

- code/model/modelread.cpp
- code/object/collideshipship.cpp
- code/parse/sexp.cpp
Per a thread in the TBP forum, elaborate on these model warnings a bit.
Two other small code tweaks as well.
> tweak some model warning messages

- code/ai/aigoals.cpp
> tweak error message

- code/asteroid/asteroid.cpp
- code/camera/camera.cpp
- code/camera/camera.h
- code/graphics/matrix.cpp
- code/graphics/matrix.h
- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/shadows.cpp
- code/graphics/shadows.h
- code/hud/hud.cpp
- code/hud/hudshield.cpp
- code/hud/hudtargetbox.cpp
- code/hud/hudtargetbox.h
- code/io/keycontrol.cpp
- code/missionui/missionscreencommon.cpp
- code/missionui/missionshipchoice.cpp
- code/model/modelrender.cpp
- code/parse/sexp.cpp
- code/radar/radarorb.cpp
- code/render/3d.h
- code/render/3dinternal.h
- code/render/3dmath.cpp
- code/render/3dsetup.cpp
- code/scripting/api/objs/camera.cpp
- code/ship/ship.cpp
- code/starfield/starfield.cpp
- freespace2/freespace.cpp
> Allow an asymmetric FOV / Frustrum

- code/globalincs/version.cpp
- code/globalincs/version.h
- code/scripting/api/libs/base.cpp
- test/src/globalincs/test_version.cpp
Extracts the version parsing code from the Lua API.
Prerequisite for #5583
> Make version parsing available

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- freespace2/freespace.cpp
Adds the ability to specify an aspect ratio, or a range of aspect ratios, to be used by splash screens.
> aspect-ratio-specific splash screens

- code/cmdline/cmdline.cpp
- code/cmdline/cmdline.h
- code/graphics/opengl/gropengl.cpp
- code/graphics/vulkan/VulkanRenderer.cpp
- code/osapi/osapi.h
- freespace2/SDLGraphicsOperations.cpp
Also, ensure that FSO is on top when it starts.
Required for #5583.
> Allow to Capture Mouse in FSO window

- code/parse/sexp/LuaAISEXP.cpp
- code/parse/sexp/LuaSEXP.cpp
Adds waypoints `OPF_POINT` as an allowed LuaSEXP parameter type.
> Add waypoint as allowed lua sexp parameter type

- code/controlconfig/controlsconfig.cpp
- code/hud/hudsquadmsg.cpp
- code/hud/hudsquadmsg.h
- code/pilotfile/plr.cpp
Remove this function and associated items, since they are commented out and unused.
> remove hud_squadmsg_save_keys()

- code/ship/ship.cpp
- code/weapon/weapon_flags.h
- code/weapon/weapons.cpp
Adds a flag to set a weapon class to never be affected by countermeasures. Fixes #5265
> Weapon ignores countermeasures flag

- code/mission/missioncampaign.cpp
- code/playerman/managepilot.cpp
Only one of these was an actual memory leak.
Add comments to clarify.
Fixes #5691
> Revert one "Fix" and add comments

- .github/workflows/build-nightly.yaml
- .github/workflows/build-test.yaml
- .github/workflows/test-pull_request.yaml
Temporary fix for broken windows workflow. Hopefully a more permanent solution will be found soon and we can then remove this.
Reference: https://github.com/actions/runner-images/issues/8598
> add workaround for broken windows workflow

- code/mission/missionparse.cpp
- code/ship/ship.cpp
- code/ship/shipfx.cpp
- code/ship/shipfx.h
- code/species_defs/species_defs.cpp
- fred2/fred.rc
- fred2/missionsave.cpp
- fred2/resource.h
- fred2/warpparamsdlg.cpp
- fred2/warpparamsdlg.h
- qtfred/src/mission/missionsave.cpp
Per discussion with @Baezon, this is a more precise term.
> change "special warp physics" to "supercap warp physics"

- code/cfile/cfile.cpp
- code/cfile/cfile.h
- code/hud/hudconfig.cpp
- code/menuui/readyroom.cpp
- code/mission/missioncampaign.cpp
- code/mission/missioncampaign.h
- code/network/multi_data.cpp
- code/network/multiui.cpp
- code/starfield/nebula.cpp
- fred2/fredstubs.cpp
- freespace2/freespace.cpp
- freespace2/freespace.h
- qtfred/src/fredstubs.cpp
- test/src/test_stubs.cpp
Some streamlining and constifying of the readyroom popup list and associated functions.
Followup to #5462.
> additional cleanup from PR 5462

- code/menuui/techmenu.cpp
- code/menuui/techmenu.h
- code/scripting/api/objs/intelentry.cpp
- test/src/menuui/test_intel_parse.cpp
Works exactly like the custom data in ships, weapons, and cutscenes tables.
> Adds custom data for intel entries

- code/ai/aicode.cpp
- code/ui/slider2.cpp
This pr adds checks for the easily fixable divide by zero coverity issues that were uncovered by the most recent scan.
> New division by zero coverity issues

- code/scripting/api/objs/player.cpp
> Fix type mismatch

- code/lighting/lighting.cpp
- code/mission/missionparse.cpp
- code/model/modelrender.cpp
- code/parse/sexp.cpp
- code/scripting/api/libs/base.cpp
- code/scripting/api/libs/ui.cpp
Fix several coverity issues.  None of these is too bad, mostly just guarding against rare edge cases or future-proofing.
> Fix uninitialized scalars 2

- code/def_files/data/effects/main-f.sdr
> Account for Glow and Spec maps for alpha-multiplied ships

- code/ai/ailua.cpp
> how about an if/then/else that actually works?

- code/ai/aicode.cpp
- code/parse/sexp.cpp
Fix the two new coverity issues for this week.
> Coverity improper use of negative

- code/localization/localize.cpp
- code/missionui/missiondebrief.cpp
- code/network/multi_pinfo.cpp
- code/network/multi_pxo.cpp
- code/network/multiui.cpp
- code/network/multiui.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/rank.cpp
- code/stats/medals.cpp
- code/stats/scoring.cpp
- code/stats/scoring.h
Fixes #5592 by adding both a Rank Alt Name and a Rank Title, localized like other variables with $rtitle.
> Rank display name and title

- code/gamesnd/eventmusic.cpp
- code/parse/sexp.cpp
1. Update soundtrack message to make it easier for modders to track down missing files
2. Update sexp help for ai-stay-near-ship to show the right argument count
> two small tweaks

- code/ai/aibig.cpp
- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/ai/aiturret.cpp
- code/anim/packunpack.cpp
Replace many int3's with UNREACHABLE or ASSERTION as necessary.
> Get rid of remaining int3s in AI code

- code/asteroid/asteroid.cpp
- code/debris/debris.cpp
- code/object/collideshipship.cpp
Follow-up to #5771. Make sure these remain copies.
> Fix collision bug

- code/graphics/generic.cpp
- code/graphics/generic.h
- code/hud/hudmessage.cpp
Fixes #5710. Followup to #5656.
> Fix wingman headanis

- code/scripting/api/objs/ship_bank.cpp
Add the runtime burst counter and seed on ship banks to scripting api.
> Add lua burst values

- code/jumpnode/jumpnode.cpp
- code/jumpnode/jumpnode.h
- code/parse/sexp.cpp
- fred2/jumpnodedlg.cpp
- fred2/missionsave.cpp
- fred2/missionsave.h
- qtfred/src/mission/missionsave.cpp
- qtfred/src/mission/missionsave.h
See title.  A followup of sorts to #5464.
> add const where appropriate to the jump node API

- code/scripting/api/objs/LuaEnum.cpp
What it says on the tin. Takes the item name, finds it in the list, and yeets it into the void.
Also fix up some casts while I'm here.
> Add ability to remove an enum item from a list

- code/cmdline/cmdline.cpp
As requested on Discord.  I don't use this option myself, so I welcome any arguments why this should or shouldn't change categories.
> move -no_unfocused_pause

- code/sound/ffmpeg/FFmpegWaveFile.cpp
Should fix deprecation warnings when using ffmpeg 5.1 and above.
> fix deprecation warnings on newer ffmpeg versions

- code/scripting/api/objs/eye.cpp
Deprecate IsValid (wrong case) in favor of isValid for eyepoint stuff.
> Deprecate IsValid in favor of isValid

- code/hud/hudsquadmsg.cpp
- code/model/modelanimation.cpp
- code/model/modelread.cpp
- code/parse/sexp/sexp_lookup.cpp
- code/scripting/api/libs/ui.cpp
- code/ship/shipfx.cpp
- code/ship/shiphit.cpp
- freespace2/freespace.cpp
I'm not even listing the issue numbers as there were more than 5.  Also, if we switch to c++14 in the future, there would more that we could do in Lambda expressions.
> These std moves were suggested by Coverity as optimizations

- code/ai/aicode.cpp
- code/ai/aiturret.cpp
- code/hud/hudlock.cpp
- code/object/object.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/ship_flags.h
- code/weapon/weapon.h
- code/weapon/weapon_flags.h
- code/weapon/weapons.cpp
Rather than just repeated launch sounds, can make high rate rate weapons sound better. I really wanted to make this work for turrets but damn it's a pain in the ass, so just primaries/secondaries will have to do for now.
> Add Start/Loop/End sounds for weapons

- code/hud/hudtargetbox.cpp
> Do not translate these if setting is enabled

- code/radar/radar.cpp
- code/radar/radardradis.cpp
- code/radar/radardradis.h
- code/radar/radarorb.cpp
- code/radar/radarsetup.cpp
- code/radar/radarsetup.h
Also convert true/false variables to boolean.
> make radar timestamps type-safe

- ci/post/nebula.py
Missed this earlier. Updated to match changes made to the nebula script in the nightlybuild repo.
> update nebula script for Mac filename changes

- code/scripting/api/libs/graphics.cpp
- code/scripting/scripting.cpp
- code/scripting/scripting.h
Allows lua to check whether VR mode is active, either by explicit check through a function, or by using a hook condition.
> VR Lua interface

- code/weapon/beam.cpp
Yes, this will change behavior for mods using these options. But I hopefully should not need to mention how incredibly unintuitive and annoying it would be to have flags that are very explicit on what they do, only to just magically not work in certain situations, and magically require you to know to enable a completely different flag in a completely different file, otherwise.
EDIT: To clarify, with the new 'check hull' handling this will only early interrupt a beam that started unobscured and became obscured during its firing. 'check hull' as it is will prevent a beam from starting to fire if it is obscured.
> Make beams respect 'check hull' and 'can damage shooter' flags

- code/model/modelread.cpp
In consultation with @BMagnu, code that validates data in the POF file itself should happen in `read_model_file_no_subsys`, as virtual POFs rely on their source files having correct data.  I've added comments and slightly rearranged things to make this clearer, and also moved the new code from `read_and_process_model_file`.  Additionally, I fixed two bugs by changing `parent > pm->n_models` to `parent >= pm->n_models` and adding a newline to the `nprintf`.
> 5911 followup

- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Fix issue where FRED would wipe out custom strings on mission save if custom data was empty
> Fix custom string saving

- code/scripting/api/libs/options.cpp
These should get pushed to the INI file or player's in-game changes will get lost on game restart.
> Save these to the ini file

- code/ship/ship.cpp
As reported by Trivial Psychic, if the number of subsystems exceeds the max as the result of a modular table, the error message was very misleading.  This fixes the error message and also makes it report the correct number of parsed subsystems.
> fix ship subsystem parse warning

- code/stats/medals.cpp
Make sure all medal fields are properly assigned.  In particular, if a modular -mdl.tbm is parsed, don't overwrite information from the base medals.tbl.  Fixes a bug reported in Discord.
> ensure medal information is correctly assigned

- code/parse/sexp.cpp
Clarify message priorities, especially the conditions that allow High messages to be sent by Command.  Motivated by #5968.
> update sexp help for send-message

- ci/post/release.mako
A bit of wordsmithing and link updating for the release thread.
> edit the release template

- code/scripting/api/objs/ship.cpp
This improves the ability of Lua to check for ship arrival status:
1. Deprecates the `isWarpingIn` function, which can be misleading, and replaces it with the equivalent `isWarpingStage1`
2. Adds an `isWarpingStage2` function to fill a gap in functionality
3. Adds an `isArrivingWarp` function (complementing the existing `isDepartingWarp` function) to cover both stage 1 and stage 2
> cover all stages of ship warping in the Lua API

- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
Add `getShip()` to parsed ships and `getParsedShip()` to ships to allow the two APIs to connect to one another.
> connect ship and parsed ship in Lua API

- code/scripting/api/objs/ship.cpp
Another #6009 follow-up, this one from PR #5935.
> another isValid fix

- code/lab/renderer/lab_renderer.cpp
- code/math/bitarray.h
- code/mission/missionparse.cpp
- code/nebula/neb.cpp
- code/nebula/neb.h
- code/parse/sexp.cpp
- fred2/bgbitmapdlg.cpp
- fred2/dumpstats.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Change `Neb2_poof_flags` to use a bit string of unlimited length to allow for an arbitrary number of nebula poofs.
~~In draft pending testing.~~ Tested by Ice Cream Man.
> bitstring poofs

- code/menuui/techmenu.cpp
- code/missionui/missionbrief.cpp
- code/model/animation/modelanimation.cpp
- code/model/animation/modelanimation.h
- code/model/animation/modelanimation_driver.cpp
- code/model/model.h
- code/model/modelread.cpp
- code/model/modelrender.cpp
- code/ship/ship.cpp
- code/starfield/starfield.cpp
- code/weapon/weapons.cpp
This adds further animation driver options.
Notably, it allows three new things:
1. The usage of control input for animation drivers.
2. Animation drivers for cockpit animations (while allowing access to ship data)
3. Animation drivers for weapon animations (trivial to just tack ontop of this)
> Animation Drivers for Cockpits

- code/ai/aiturret.cpp
- code/graphics/opengl/gropenglopenxr.cpp
- code/iff_defs/iff_defs.cpp
- code/parse/sexp.cpp
- code/scripting/api/libs/ui.cpp
- code/ship/awacs.cpp
Some false positive annotations, some range checks, and commenting dead code.
> several coverity fixes

- code/network/multi.cpp
- code/network/multi.h
- code/network/multiui.cpp
- code/network/multiutil.cpp
- code/network/multiutil.h
Converts Active_games_head to an SCP_list to prepare for the SCPUI API.
> Make Active_games_head an SCP_list

- code/parse/sexp.cpp
> Push back instead of direct assignment

- code/scripting/api/objs/medals.cpp
- code/scripting/api/objs/medals.h
A couple scripting functions to help check if a medal is a Rank or a Badge in SCPUI. Also fix a static cast while I'm here.
> Code to check if a medal is rank or badge

- code/mission/missionhotkey.cpp
- code/mission/missionmessage.cpp
- code/object/objectsnd.cpp
- code/ship/awacs.cpp
- code/ship/ship.cpp
- code/weapon/trails.cpp
- code/weapon/trails.h
- code/weapon/weapons.cpp
Trail timestamps and a few top-level timestamps.  Also a few `static` and `constexpr` keywords for good measure.
> make several miscellaneous timestamps type-safe

- code/scripting/api/objs/object.cpp
Can be used in tandem with removeSoundByIndex() to effectively silence an object
> Lua method to get the number of object sounds

- code/parse/sexp.cpp
> Handle container data nodes correctly with eval_num()

- code/network/chat_api.cpp
- code/network/chat_api.h
- code/network/multi_pxo.cpp
- code/network/multi_pxo.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/multi_objects.cpp
- code/scripting/api/objs/multi_objects.h
- code/source_groups.cmake
This is the complete API for SCPUI Multi PXO and Multi PXO Help game states. Relies on #5830, so draft until that is merged.
> Scpui multi pxo api

- code/parse/sexp.cpp
Per Durandal, a few attributes of this SEXP can be documented a little better.
> improve set-support-ship description

- code/scripting/api/libs/options.cpp
Used for SCPUI's multi options menu
> Add lua function to validate a string as a valid IP

- code/scripting/api/libs/ui.cpp
I could hardcode them into SCPUI as well, but this is better.
> API to get the PXO urls

- fred2/fred.rc
- fred2/resource.h
- fred2/voiceactingmanager.cpp
- fred2/voiceactingmanager.h
This adds a new button to check if messages sent by `"<any wingman>"` have at least one ship with that persona.
> add a new check to the Voice Acting Manager

- code/ai/ai.h
- code/ai/aicode.cpp
- code/iff_defs/iff_defs.cpp
- code/iff_defs/iff_defs.h
- code/parse/sexp.cpp
What it says on the tin. AI won't rearm at all while its a bad time.
> Add bad-rearm-time sexp

- code/network/multiui.cpp
- code/network/multiui.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/multi_objects.cpp
- code/scripting/api/objs/multi_objects.h
Should be everything required to get this UI fully functioning. A few things had to move to the header and I broke out a few minor code blocks into methods that the API can use instead of duplicating code.
> Multi Join API

- code/scripting/api/objs/ship.cpp
Follow-up to #6034.  This slightly changes the function signature of `AddElectricArc` but it should be fine since it hasn't appeared in a stable release yet.
> more electrical arc API features

- code/mission/missionparse.cpp
This does two things:
1. Fix a bug in `mission_bring_in_support_ship` that assigns an incorrect parse object index to the support ship's ship registry entry.  Since `Arriving_support_ship` is not an item of `Parse_objects`, it should not have an index.
2. Adjust the in-game join checks at the bottom of `parse_create_object_sub` to more scrupulously account for index mismatches and bounds errors, with a specific exception for the arriving support ship.
> adjust ship registry checks to accommodate support ships

- code/network/multi_pause.cpp
- code/network/multi_pause.h
- code/scripting/api/libs/ui.cpp
Edit for clarification.. this PR does not need 6078. This is everything needed for Multi Pause with the exception of chat which is covered in 6078.
> API for the Multi Pause UI

- code/network/multi_dogfight.cpp
- code/network/multi_dogfight.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/multi_objects.cpp
- code/scripting/api/objs/multi_objects.h
Should be everything I need for the dogfight debrief UI
> Multi dogfight debrief API

- code/cutscene/ffmpeg/AudioDecoder.cpp
- code/cutscene/ffmpeg/FFMPEGDecoder.cpp
> fix deprecated/removed code in cutscene ffmpeg

- code/model/modelread.cpp
Use the correct upper bounds check for `model_get()`.
> model range fix

- code/cutscene/movie.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Update mod_table and movie files to include settings for the color and transparency of the subtitles.
Implements #6064
> Update Settings for movie subtitles #6064

- code/mod_table/mod_table.cpp
Allow optional strings in game_settings.tbl to recognise both spellings - color/colour.
> Accept "color" and "colour" in game_settings.tbl

- fred2/cmdbrief.cpp
> call set_modified() when cmd_brief data has changed

- code/missionui/missiondebrief.cpp
We don't need to build the buttons or retail UI if we're in API mode.
> Skip some more retail UI stuff with API

- code/playerman/player.h
- code/playerman/playercontrol.cpp
Fixes a bug with new unified scanning PR (#6000) and adds a bit of cleanup, including consistent brackets, whitespace cleanup, and removing vestigial function from the original PR.
> Follow-up to Unified Scanning

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipEditor/ShipPathsDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipPathsDialogModel.h
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.h
- qtfred/src/ui/dialogs/ShipEditor/ShipPathsDialog.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipPathsDialog.h
- qtfred/ui/ShipPathsDialog.ui
Not much to say on this one. It's pretty much just a copy paste of the FRED one.
> Arrival/Departure Paths Dialog

- code/ship/ship.cpp
Especially noticable in deferred rendering mode, but also present in normal mode, cockpits with transparency were broken.
This ensures a correct rendering order and processing of transparent stuff after the second deferred pass.
In addition, causes shadows for cockpits to not be cast from transparent tris.
fixes #5587
> Fix Transparent Cockpits

- code/asteroid/asteroid.cpp
- code/mission/missionparse.cpp
Update assertion message and mission saving check since older builds are not going to be able to read fields created with newer builds from #6021
> One more follow-up to #6021

- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/weapon/weapon.h
- code/weapon/weapons.cpp
- fred2/customstringsdlg.cpp
- fred2/customstringsdlg.h
Implements a request from #6117
> Custom Strings for ships and weapons

- code/parse/sexp.cpp
Exactly what it says on the tin:
* Clarify some ambiguous documentation
* Warn about non-obvious edge cases, especially around `<argument>`s
* Remove a couple "generic he"s
> Clarify some SEXP operator documentation

- code/controlconfig/controlsconfig.cpp
This lets FSO use the current preset as the default name for the "new" preset.  If there was no preset file, it reverts to the old behavior of using the pilot's callsign.  Tested and works as expected.
Fixes #3930
> Save current preset name and use as default when saving new preset name

- code/mission/missionmessage.h
- code/mission/missionparse.cpp
> Respect tabled delay for arrival and backup messages

- code/render/batching.cpp
- code/render/batching.h
I never PRed this apparently? Anyway, laser batching const cascade.
> Adds consts to parameters for a couple laser rendering functions.

- code/weapon/beam.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Sets up curve parameters to control the slash position and rotational position of type 5 beams over their lifetimes.
> Beam slash curves

- code/object/collideweaponweapon.cpp
- code/weapon/weapons.cpp
Previously the modder wouldn't be warned if a conditional impact couldn't find the specified armor type and set it to -1. This fixes that.
> Adds warning if cond-impact armor type not found.

- code/render/batching.cpp
- code/render/batching.h
> Adds const to a couple batching matrices.

- code/gamesnd/gamesnd.cpp
Although sound indexing is now done by name, mods which index by number (sc. a number that is treated as a name) expect the indexes to be in numeric order.  When multiple levels of -snd.tbm files add mixed retail-style and new-style sounds, this assumption can be violated due to named sounds being placed into indexes that later files expect to be available.
This PR refines the parsing so that sounds which use a numeric index can pre-empt existing named sounds that have been assigned to that index.  Since named sounds can go anywhere, they are just moved to the end of the list.  This allows the ranges 192-199 and 202-249 to be available for numeric indexes as expected under the old style.  MediaVPs named sounds which were previously parsed into those indexes are bumped to the next …
> improve sounds.tbl index ordering

- code/iff_defs/iff_defs.cpp
A bit of rearrangement to use a reference here, instead of a new map.  Follow-up to 6300
> Small optimization

- code/model/model.h
- code/ship/ship_flags.h
Fixes #6372 by more specifically setting the `MR_ATTACHED_MODEL` value and by correctly setting the `MR_NO_INSIGNIA`.
Tested and fixes the issue.
> Fixes Lab Rendering when Zooming

- fred2/voiceactingmanager.cpp
When actions in the Voice Acting Manager modify the mission, set the modified flag so that FRED will prompt to save the mission.  And since this requires tracking the number of modifications, enhance the dialog boxes to display this information to the user.
Fixes #6362.
> set the modified flag in the Voice Acting Manager

- code/scripting/api/objs/weaponclass.cpp
- code/weapon/weapons.cpp
Also fix a very minor parsing inconsistency
> Grant lua access to countermeasure parameters

- code/scripting/api/libs/hud.cpp
- code/scripting/api/libs/mission.cpp
- fred2/fredstubs.cpp
- freespace2/freespace.cpp
- freespace2/freespace.h
- qtfred/src/fredstubs.cpp
- test/src/test_stubs.cpp
1. add `hu.isOnHudDrawCalled()` and clarify documentation for `hu.HUDDrawn`
2. add `mn.isPrePlayerEntry()`
> add hud drawing and pre-player-entry checks

- code/ship/ship.cpp
A few addenda to PR #6364:
1. Use `std::swap` in the move constructor, since the fields are specifically being moved, not assigned
2. Fix off-by-one error when parsing firing patterns, and make the pattern count non-fatal
3. Standardize the setting of fire points since it's done in three different places, and in the case of `ship_set_default_weapons()`, `primary_firepoint_next_to_fire_index` was not reset to 0.  It might be useful to refactor this code into its own function.
4. Make the setting of `primary_firepoint_next_to_fire_index` consistent between forward and reverse cycling
5. Remove a couple redundant `.clear()` calls and fix a typo
> Cycle expansion followup

- code/parse/sexp.cpp
- code/parse/sexp.h
Add a simple SEXP operator for changing the range of the current nebula.  Also, slightly reorder the existing nebula operators.
> add nebula-set-range

- code/menuui/mainhallmenu.cpp
Tweak the mod string to display one or the other if both are not present.
> allow the mod title and version to be displayed independently

- code/ai/aigoals.h
- code/globalincs/pstypes.h
- code/globalincs/vmallocator.h
- code/iff_defs/iff_defs.cpp
- code/mission/missionparse.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/ship/ship.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
- tools/embedfile/embedfile.cpp
Small prerequisites to future PRs...
1. fix some usages of std::transform
2. change parse_string_flag_list to use a reference
3. add a variant of parse_string_flag_list that can use a SCP_set, and make a templated version of flag_def_list
> STL fixes and cleanup

- code/menuui/credits.cpp
- code/menuui/credits.h
- code/scripting/api/libs/ui.cpp
Similar to Substitute Music in other places, this allows the credits music to be changed if an optional music pack is present.
> add $Substitute Music: for credits.tbl

- code/graphics/color.cpp
- code/graphics/color.h
- code/object/object.cpp
Followup to #6474. Cleans up the logic flow some.
> Weapon light followup

- code/controlconfig/controlsconfigcommon.cpp
Fixes mislabeling of joystick hat names that appeared in #6371. Tested and confirms this fixes the issue.
> Fixes Joystick Hat Labeling

- code/io/joy.h
Follow-up to #6371 (and replaces #5960 since the goal of that PR was already taken care of with #6371 adding the procedural translation).
Overall tagging this as 25.0 since multiple folks have asking about bumping the limit. In draft status pending more testing.
> Update JOY_NUM_BUTTONS to 128

- code/graphics/render.cpp
- code/graphics/software/FSFont.cpp
- code/graphics/software/FSFont.h
- code/graphics/software/NVGFont.cpp
- code/graphics/software/VFNTFont.cpp
- code/graphics/software/VFNTFont.h
Fix another instance of an option getting optimized out of release builds.
> Fix font multiplier in release builds

- code/debris/debris.cpp
One line failsafe condition, to mitigate any possible crashes as reported on Discord: [](https://discord.com/channels/223511295431933953/223511391531827200/1329193470480482435)
> Add failsafe check for new texture replace fix

- code/parse/sexp.cpp
Clarify some sexp help descriptions.
> update sexp documentation

- code/globalincs/utility.h
- code/graphics/2d.cpp
- code/math/curve.cpp
- code/parse/sexp.cpp
- code/scripting/api/objs/ship.cpp
- code/utils/string_utils.cpp
- code/utils/string_utils.h
Useful functions for utility.h and string_utils.h.  Adapt existing code accordingly.
> add some utility functions

- code/hud/hudreticle.cpp
- code/hud/hudsquadmsg.cpp
- code/hud/hudtarget.cpp
Fix a few errors introduced by the big HUD code upgrade.
> Fix hud errors

- code/scripting/api/objs/hudgauge.cpp
Updates the get/set color functions as part of a hud gauge to match the gr library functions that can work with color objects in addition to rgb values.
> Match get/set colors for gauges to graphics

- code/hud/hudwingmanstatus.cpp
#6676 removed a section that it turns out needed. Tested and works as expected.
> Fix wingmen custom dot for starting ships

- code/mission/missioncampaign.cpp
- code/scripting/global_hooks.cpp
Adds the Mission hook variable to On Campaign Mission Accept
> Add mission name as hook variable

- code/ai/ai.h
- code/ai/aicode.cpp
- code/ai/aiturret.cpp
- code/lab/dialogs/lab_ui.cpp
- code/lab/dialogs/lab_ui.h
- code/lab/manager/lab_manager.cpp
- code/lab/manager/lab_manager.h
- code/ship/ship.cpp
- code/weapon/swarm.cpp
- code/weapon/swarm.h
- code/weapon/weapons.cpp
Adds the ability to fire turrets in the F3 Lab using multiple aiming settings based on the turret and allows changing the weapons on the turret. Please pay special attention in review to the changes in aiturret.cpp to make sure the in_lab paths to make sure I didn't change in-mission behavior. Basically the lab just needs to skip stuff and always fire the weapon.
While I was here I fixed a few things related to firing primary/secondary weapons to make those always fire as well, skipping some unnecessary checks when in the lab.
https://github.com/user-attachments/assets/ff2a8be6-3c5b-4505-9527-6f9d560f02ef
> Lab firing upgrades

- ci/post/changelog.py
> Update Changelog script to sort by labels

- code/parse/parselo.cpp
- code/scripting/api/objs/comm_order.cpp
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
1. fix a copy-paste error
2. fix a compiler warning
3. prevent negative array index when AI has no target
4. fix a bounds check
> A few fixes

- code/controlconfig/controlsconfig.cpp
- code/controlconfig/controlsconfig.h
- code/fireball/fireballs.cpp
- code/globalincs/utility.h
- code/hud/hudconfig.h
- code/hud/hudtargetbox.cpp
- code/lab/renderer/lab_renderer.h
- code/missionui/missiondebrief.cpp
- code/model/modelread.cpp
- code/parse/parselo.cpp
- code/parse/sexp/sexp_lookup.cpp
- code/pilotfile/csg_convert.cpp
- code/scripting/scripting.cpp
- code/tracing/FrameProfiler.cpp
- code/tracing/FrameProfiler.h
Address several issues flagged by Coverity. The changes are broken into multiple commits corresponding to different categories.
> Various more Coverity issues

- code/hud/hudets.cpp
> add an ETS comment

- code/hud/hudmessage.cpp
> fix hudmessage rand

- code/weapon/beam.cpp
- code/weapon/weapon.h
Closes #6476.
Works for Type 5 and Type 1 beams.
> Add "Move End Position by target velocity"

- code/hud/hudconfig.cpp
Don't flush mouse here or we can't drag the sliders.
> Fix hud config sliders

- qtfred/src/mission/dialogs/CustomWingNamesDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipTextureReplacementDialogModel.cpp
- qtfred/src/ui/dialogs/LoadoutDialog.cpp
- qtfred/src/ui/dialogs/ReinforcementsEditorDialog.cpp
Various cleanup associated with the `toStdString()` function in qtFRED.  Now that `lcase_equal` exists, it is no longer necessary to compare the C strings.  Additionally, QString has its own `isEmpty()` function.
> qtfred cleanup

- code/mission/missionmessage.cpp
- code/mission/missionmessage.h
- code/scripting/api/objs/message.cpp
Adds Custom Data to Personas for Event Horizon. Also fixes some minor things in the scripting api for Messages (NULL -> nullptr, SCP_vector_inbounds).
> Custom data for personas

- code/scripting/api/objs/font.cpp
Just a couple Lua functions to get a Font's `Auto Size` and `Can Scale` settings. Also change a bunch of NULL to nullptr in the same file.
> Get font scale options for Lua

- code/object/objcollide.cpp
Threading is fun.
So, what happened here is the following.
The worker threads update their queue lengths as follows:
```cpp
thread.result_length.fetch_add(1, std::memory_order_release); //W1
thread.queue_length.fetch_sub(1, std::memory_order_release); //W2
```
while the main thread checked these lengths as follows:
```cpp
if (thread.result_length.load(std::memory_order_acquire) > processed) { /* ... */ } //L1
else if (thread.queue_length.load(std::memory_order_acquire) == 0) { /* ... */ } //L2
```
Now, while neither write can be reordered, and neither read can be reordered due to the set memory order guarantees, the following _could_ happen for whatever timing reasons, and it in fact did happen sometimes:
1. L1 hits, and detects that no additional results have been produced
2. W1 hits, …
> Fix rare collisions being dropped in threaded FSO

- code/network/multi_interpolate.h
- code/network/multi_obj.cpp
Fix use of incorrect data macro
Fix packet size safety check
Fix sequence order issue with client data packet (Cyborg)
Cleanup code to address readability and maintenance issues
> cleanup and fix issues with multi client data

- code/mission/missionparse.h
- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/MissionCutscenesDialogModel.cpp
- qtfred/src/mission/dialogs/MissionCutscenesDialogModel.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/src/ui/dialogs/MissionCutscenesDialog.cpp
- qtfred/src/ui/dialogs/MissionCutscenesDialog.h
- qtfred/ui/FredView.ui
- qtfred/ui/MissionCutscenesDialog.ui
Fully implements the Mission Cutscenes dialog that was previously not ported from FRED to QtFRED.
> QtFRED Mission Cutscenes Dialog

- code/mission/missionparse.h
- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipEditor/ShipAltShipClassModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipAltShipClassModel.h
- qtfred/src/ui/dialogs/ShipEditor/ShipAltShipClass.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipAltShipClass.h
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.h
- qtfred/ui/ShipAltShipClass.ui
Not much to say on this one. It looks and functions like the old one.
Not fully tested due to the fact we haven't got a variables editor yet.
> QTFred: Alt Ships Class dialogs

- code/network/multiui.cpp
During maintenance of the active games list it's possible for the list to be cleared before a stale item is removed leading to a access violation. So we need to confirm the list isn't empty when attempting to erase the stale entry.
This also fixes a bug where the list entry index is incremented even when an entry is removed which can cause an improper selection index being used.
> fix memory access error with active games list

- code/missioneditor/common.cpp
- code/missioneditor/common.h
- code/source_groups.cmake
- fred2/management.cpp
- fred2/management.h
- fred2/voiceactingmanager.cpp
- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/VoiceActingManagerModel.cpp
- qtfred/src/mission/dialogs/VoiceActingManagerModel.h
- qtfred/src/ui/dialogs/VoiceActingManager.cpp
- qtfred/src/ui/dialogs/VoiceActingManager.h
- qtfred/ui/VoiceActingManager.ui
Revises and finishes the Voice Acting Manager. This will need way more testing in alpha and beta since big missions can throw a lot of wrenches in the works but it seems to be doing ok with my brief tests now.
NOTE: This formally adds the missioneditor folder and common.cpp to the Code project. The idea is that things common to any mission editor past, present, or future will live in that folder. I don't know if common.cpp will be the final final used but it's a place to start aggregating things that are common to editors. More organization can follow once we know what all we have.
Fixes #1694
> QtFRED Voice Acting Manager Dialog

- qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.cpp
- qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.h
- qtfred/src/ui/dialogs/ReinforcementsEditorDialog.cpp
- qtfred/src/ui/dialogs/ReinforcementsEditorDialog.h
- qtfred/ui/ReinforcementsDialog.ui
Refactors the reinforcements dialog into the new style and fixes some makes. Also makes the UI a bit clearer and easier to use.
Fixes #6976
> QtFRED Reinforcements Dialog

- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/mission/dialogs/ShieldSystemDialogModel.cpp
- qtfred/src/mission/dialogs/ShieldSystemDialogModel.h
- qtfred/src/ui/dialogs/ShieldSystemDialog.cpp
- qtfred/src/ui/dialogs/ShieldSystemDialog.h
- qtfred/ui/ShieldSystemDialog.ui
Refactors the shield sys dialog into the new code style.
Fixes #6977
> QtFRED Shield Sys Dialog

- code/nebula/volumetrics.h
- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
- qtfred/src/mission/dialogs/VolumetricNebulaDialogModel.cpp
- qtfred/src/mission/dialogs/VolumetricNebulaDialogModel.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/src/ui/dialogs/VolumetricNebulaDialog.cpp
- qtfred/src/ui/dialogs/VolumetricNebulaDialog.h
- qtfred/ui/FredView.ui
- qtfred/ui/VolumetricNebulaDialog.ui
Fully implements the dialog as it exists in FRED currently with very minimal enhancements.
Fixes #6981
> QtFRED Volumetric Nebula Dialog

- qtfred/ui/FredView.ui
Simply updates the .ui file to modernize the menu structure in QtFRED. Fixes #6985
> QtFRED Modernize Menus
