scp-fs2open/fs2open.github.com

code/globalincs/fsmemory.cpp, code/globalincs/fsmemory.h, code/globalincs/pstypes.h, code/osapi/outwnd_unix.cpp, code/parse/sexp.cpp, code/windows_stub/config.h, configure.ac, m4/ax_cxx_compile_stdcxx_11.m4
Also adds compile time checks for dangerous uses of memcpy/memmove/memset, i.e. on non POD classes/structs
=> Cpp11 support for GCC

code/parse/sexp.cpp
Allows *-argument SEXPs to short-circuit by allowing the *-of SEXPs to short-circuit with SEXP_KNOWN_FALSE. See Mantis 3136.
=> *-argument sexp short-circuiting

code/network/multi_pxo.cpp
time_t is 64bit on 64bit systems; casting a pointer to a larger type is
dangerous, but assigning to a larger type should be fine
=> Fix Coverity 1093484

code/ai/aigoals.cpp
Add an assertion to catch any callers that haven't correctly set
the target_name. Also fix a minor typo in the comments
=> Fix Coverity 1093565: Negative array index read

code/network/multiutil.cpp
A memory location at a negative offset from the beginning of the array will be read, resulting in incorrect values.
In multi_create_standalone_object(): Negative value used to index an array in a read operation
observer_create() will only fail in exceptional circumstances so a showing an error dialog should be acceptable
=> Fix for Coverity 1093555: Negative array index read

code/camera/camera.cpp
The field will contain an arbitrary value left over from earlier computations.
In subtitle::​subtitle(int, int, char const*, char const*, float, float, color const*, int, bool, bool, int, int, bool): A scalar field is not initialized by the constructor
=> Fix for Coverity 1237276: Uninitialized scalar field

code/network/multi_options.cpp
A memory location at a negative offset from the beginning of the array will be read, resulting in incorrect values.
In multi_options_process_packet(unsigned char *, header *): Negative value used to index an array in a read operation
=> Fix for Coverity 1093515: Negative array index read

code/mission/missionmessage.cpp
A memory location at a negative offset from the beginning of the array will be read, resulting in incorrect values.
In message_queue_process(): Negative value used to index an array in a read operation
=> Fix for Coverity 1093530: Negative array index read

code/globalincs/pstypes.h
Almost every compiled object on FreeBSD emits this warning right now.  I'm guessing HAVE_CXX11 is already defined either by our doing, or clang's, so always checking and defining it in pstypes.h is unnecessary if it's already defined.  If there's any suggestions for reformatting this, I'm open to them.
=> Fix for a 'HAVE_CXX11 already defined' warning

code/network/multi_voice.cpp
When used with 0xDEADBEAD, MULTI_VOICE_TOKEN_INDEX_RELEASED gets used in a case statement comparing it to token_status, which can't fit the number as an int. This was enough to fix compilation on FreeBSD with clang 3.4.1 which is pickier about narrowing and treats it as an error.  0xBEAD instead of 0xDEADBEAD should semantically get the point across but fit within the int, and doesn't change the size of the token_stream struct.
=> Fix for Mantis #3158: prevent narrowing that breaks compilation in stricter compilers 

code/hud/hudlock.cpp
Changes the "virtual frame" used for aspect locks to be 640x480 so as to correct different lock behavior due to both different aspect ratios and different resolutions. Applies a scaling factor to the drawing of the lock indicator on the HUD so that it traverses roughly the same portion of the screen regardless of resolution.
=> Fix Mantis 3140.

code/fred2/shipeditordlg.cpp
The old code operated under the assumption that all wingman personas would be at the start of the persona list. Since this assumption was neither checked for nor warned if violated anywhere else, I've made FRED work regardless of how they might be distributed throughout the Personas[] array.
Reported by TheHound.
=> Fix persona selection in FRED's ship editor.

code/gamesnd/gamesnd.cpp, code/parse/parselo.cpp, code/parse/parselo.h
As requested by jg18, this improves the sound.tbl parser to properly handle +nocreate. If the file name of an entry should not be changed you have to specify <same>.
=> Improve gamesnd modular parsing

code/parse/sexp.cpp
Can cause serious problems by accessing Sexp_nodes[-1].value. Caused chief1986 to segfault on OS X.
=> Fix typo in eval_not.

code/parse/sexp.cpp
This is very unlikely, but add an assertion anyway just in case someone
in future messes us keeping num_primary_banks & primary_bank_weapons in
sync.
=> Fix Coverity 1093714: Negative array index read

code/parse/sexp.cpp
I don't know if I was just tired when I wrote this originally or what, but there were two problems here; one, the for-loop condition was inverted (and since I made it a for-loop instead of a while-loop, I'm not sure why I didn't take out the "break" condition), so its contents would never actually evaluate. Two, the node matching random_argument wasn't being stored anywhere so even if the for-loop condition hadn't been wrong, it would've just used the last valid argument instead of the first argument every time. Fixes GitHub issue #84.
=> Fix random-multiple-of.

code/model/modelinterp.cpp
The div-by-zero won't be triggered by this code because the
secondaryteam is "none". Play it safe and protect the div anyway
=> Fix Coverity 1298268: Division by float zero

code/globalincs/vmallocator.h
The SCP_* variants are now all using inheritance or typedefs. Implementing this with a `using` template would be preferable but that's only supported in VS >= 2013.
=> Remove SCP_vm_allocator

code/model/modelinterp.cpp, code/model/modelrender.cpp
Copy particle min/max life values from modelinterp
Also avoid double->float conversion
=> Fix Coverity 1298255: Uninitialized scalar var

code/graphics/grbatch.cpp, code/model/modelinterp.cpp, code/weapon/trails.cpp
Also fixes 1298256, 1298254, 1298253
For vertex vars use default value-initialisation to zero the struct
http://en.cppreference.com/w/cpp/language/value_initialization
Note that parts of vertex don't seem used in relevant codepaths, e.g.
the colours. A zero init approach should be safer should code change in
future.
=> Fix Coverity 1298258: Uninitialized scalar var

code/ship/ship.cpp
This makes ship explosion shockwaves use the tabled damage type. The code was creating a new shockwave_create_info object, initializing it, and then only copying some of the attributes of the ship's "shockwave" shockwave_create_info member (not including damage type). It makes more sense to use copy-assignment and then specifically override the attributes that should be overridden.
=> Fix Mantis #3139.

code/globalincs/vmallocator.h, code/missionui/redalert.cpp, code/model/modelinterp.cpp, code/model/modelrender.cpp, code/object/objcollide.cpp, code/ship/ship.h
Also uses std::unordered_map on every platform now to fix warnings on Mac as the stdext hash maps are deprecated there.
This depends on #50 to be merged in order to cleanly compile on Linux.
=> Change SCP_hash_map to SCP_unordered_map

code/parse/lua.cpp
The `loop` variable wasn't specified in the `ade_get_args` call.
=> Fix scripting function ad.playMusic

code/fred2/asteroideditordlg.cpp, code/fred2/initialstatus.cpp
Change a couple instances of setting a DWORD_PTR to -1 by explicitly casting it to a DWORD_PTR.
As odd as this looks, Microsoft actually *expects* people to cast the item data, and at least one example on the MSDN itself uses -1.
=> Fix a couple FRED warnings.

code/freespace2/freespace.cpp
According to AMD and NV, these _should_ force their drivers into high-performance mode
=> Use high-performance GPU by default.

code/io/mouse.cpp, code/io/mouse.h, code/osapi/osapi.cpp
Adds support for the X and Y mousewheels, and X1 and X2 buttons. These currently take up the same mappings as joy buttons 4 through 9.
Of particular note is how the mousewheels reset to neutral, since the SDL API allows for values different from -1, 0, or 1, it's theoretically possible to end up thrashing from UP to DOWN between calls, for example.
In practice this might not be the case, and if so the mousewheel_motion function could be simplified and mousewheel_decay could be replaced by a simpler "mousewheel_x = 0"
=> Expands mouse functionality.

code/freespace2/freespace.cpp, code/graphics/2d.cpp, code/osapi/osapi.cpp
Instead of defaulting the resolution to 1024x768 FSO should now pick the desktop resolution as the initial video card configuration.
There is also a fix that disables defaulting to 800x600 when launching from a directory without the required interface art to trigger high resolutions.
=> [Antipodes] Pick a better default resolution

appveyor.yml
Apparently it's causing the nonsensical failures for builds of the 2013 project.
=> Remove AppVeyor logger.

code/cmdline/cmdline.cpp, code/io/joy-sdl.cpp, code/io/joy.h, code/io/joy_ff-sdl.cpp, code/osapi/osapi.cpp
The config value `CurrentJoystickGUID` will be read to determine what joystick is selected, if that value isn't present the old `CurrentJoystick` value will be read.
To let launchers know that this build uses SDL I added a new build flag, older launchers can still use `CurrentJoystick` to set the selected joystick but the GUID value will override the old config value.
This also adds support for removing and reconnecting a device while FSO is running which wasn't possible before.
=> [Antipodes] Make the joystick system use GUIDs to identify the joysticks

code/model/modelrender.cpp, code/model/modelrender.h, code/starfield/starfield.cpp
I noticed the Saturn rings in the Diaspora mission Shadow Walking were not being occluded by the planet's surface. My draw call sorting system was causing that issue. So, I wrote a simple fix to disable sorting when drawing skyboxes.
=> Eliminate sorting of draw calls for skyboxes for correctness.

code/freespace2/freespace.cpp, code/fs2netd/fs2netd_client.cpp, code/fs2netd/tcp_client.cpp, code/graphics/2d.cpp, code/inetfile/cftp.cpp, code/inetfile/chttpget.cpp, code/network/multi.cpp, code/network/multi_pause.cpp, code/network/stand_gui-unix.cpp, code/network/stand_gui.cpp, code/windows_stub/config.h, code/windows_stub/stubs.cpp
The `Sleep` WinAPI function was emulated on linux but we now have `os_sleep` so I replaced all remaining usages of `Sleep` with that function.
This also merges the latest changes from master into antipodes.
=> Replace Sleep with os_sleep

code/osapi/outwnd.cpp
I missed these differences between Unix and Windows when I unified the unix and windows outwnd variants.
This should restore the correct behavior for each platform.
=> Fix outwnd on Unix

projects/MSVC_2015/Fred2.vcxproj, projects/MSVC_2015/Freespace2.vcxproj
Apparently, VS2015 was still set to produce SSE2 release builds when the AVX config was selected
=> Sets AVX output for VS2015

code/Makefile.am, code/globalincs/pstypes.h, code/globalincs/vmallocator.h, code/globalincs/windebug.cpp, code/osapi/dialogs.cpp, code/osapi/dialogs.h, code/osapi/osapi.cpp, code/osapi/osapi.h, code/parse/scripting.cpp, code/windows_stub/stubs.cpp, projects/MSVC_2015/code.vcxproj, projects/MSVC_2015/code.vcxproj.filters
This unifies the way the engine handles warning and error dialog by using the functions supplied by SDL without having to use platform specific functions.
Tested on Linux and Windows (VS 2015).
=> Add unified dialog handling

projects/MSVC_2012/Freespace2.vcxproj, projects/MSVC_2013/Freespace2.vcxproj
I did a quick check on the other VS project files, excluding VC6, and it seemed that these were the only two that needed to be updated.
=> Resolves link errors when trying to build in MSVS 2012 and MSVS 2013.

code/ship/ship.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
This adds two weapons.tbl entries that allow a weapon to have a range of
possible fire delay times which results in random firing time. simulates
real life firing time error for the most part.
=> Add Max delay and Min Delay

code/object/collideshipweapon.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
This allows non-beam primary weapons to have attenuating damage.
$Damage Time:, Time at which damage attenuation starts. (when life left = damage time)
+Min Damage:, The minimum amount of damage that can ever be done assuming attenuation is taking place. Defaults to 0.0.
+Max Damage:, The maximum amount of damage that can ever be done assuming attenuation is taking place. Defaults to 0.0.
+Min Damage: and +Max Damage: cannot be used at the same time.
Test case:
Enemy: SF Mara
Weapon Velocity: 750 m/s
Lifetime: 4 seconds'
Max Range: 3000 meters
Damage time: 2 seconds, attenuation starts at 1500 meters
Damage: 25 -> 10 at max range
Shields removed entirely. ~13% damage taken by Mara at 1400 meters
~9% damage taken at 2000 meters.
~5% damage taken at 2900 meters. Single bolts were used each …
=> Weapon Damage Decay

code/menuui/barracks.cpp
Should resolve issues 1093431 and 1093432. These issues cannot cause crashes because the denominator is indirectly checked, but it's good to change to get coverity and other future diagnosing programs to stop yelling at us.
=> Resolve CID 1093435 & 1093437

code/network/multi_pxo.cpp
Should resolve issues 1093431 and 1093432. These issues cannot cause crashes because the denominator is indirectly checked, but it's good to change to get coverity and other future diagnosing programs to stop yelling at us.
=> Resolve CID 1093431 & 1093432

code/weapon/weapon.h, code/weapon/weapons.cpp
This flag prevents submunitions from being created if a parent weapon is
shot down.
Requested by IronBeer.
=> Create "don't spawn if shot" flag

code/stats/stats.cpp
Should resolve issues 1093428 and 1093429.  These issues cannot cause crashes because the denominator is indirectly checked, but it's good to change to get coverity and other future diagnosing programs to stop yelling at us.
=> Resolve CID 1093428 & 1093429

code/palman/palman.cpp
Pretty sure this is just a paranoid check.  If it's negative it should get changed to at least 2 in the following line.  Let me know if I have any misconceptions.
=> Resolve CID 1093395 - Unnecessary sanity check

code/network/stand_gui-unix.cpp
...when attempting to set a name that is too long.
Partial fix for issue #146.  This at least causes the standalone to exit completely when it has essentially crashed.
=> [fix/standalone_name_hang] Prevent the standalone from hanging

Makefile.am
New Makefile feature which runs the [cppcheck](http://cppcheck.sourceforge.net/) tool over the source code.
Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers and many other analysis tools it does not detect syntax errors in the code. Cppcheck primarily detects the types of bugs that the compilers normally do not detect. The goal is to detect only real errors in the code (i.e. have zero false positives).
Command line invocation is:
```
make cppcheck
```
=> Add 'make cppcheck' command line option.

code/ai/aicode.cpp, code/hud/hudlock.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h, code/weapon/weapon.h, code/weapon/weapons.cpp
This allows mission events or scripts to selectively disable secondary homing and lock acquisition, without completely locking secondaries.
=> Added a "no-secondary-lock-on" ship flag to disable secondary homing.

code/graphics/2d.h
The memory usage of the color struct can be optimised via reordering elements, which improves alignment and removes unnecessary padding bytes.
The attached patch reduces `sizeof(color)` from 28 bytes -> 24 bytes. 
That is a c.14% memory saving for any arrays which use the `color` struct.
=> Improve alignment of color struct

code/model/modelrender.cpp, code/model/modelrender.h
Add all struct members to constructor (esp thrust_scale which was read
uninitialised). Remove some var sets that the constructor now sets as
defaults. Also fixes 1298248
=> Fix Coverity 1298257: Uninitialized scalar var

code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp
See commit messages.
A part of the implementation of $box_offset and $offset (the added bsp_info variables) was actually accidentally committed a long time ago in r10135.
The problems in the box/sphere calculations were partly small regressions in the new rendering code and partly my own mistakes in the original code.
=> Fixes and enhancements for detail boxes and spheres

code/model/modelrender.cpp, code/model/modelrender.h
Reverts scp-fs2open/fs2open.github.com#113
This currently breaks compilation on VS platforms that are not VS2015
=> Revert "Fix Coverity 1298257: Uninitialized scalar var"

code/network/multi.cpp, code/network/psnet2.cpp
Vestigare's submitted patch for allowing multiple users behind a NAT to connect to a remote standalone.  See http://www.hard-light.net/forums/index.php?topic=88971.0 for more detail.  Just putting this out to hopefully get a little more review, I had the patch sitting on my desktop and it's been purged from the thread since, don't want it to disappear forever.
=> [fix/nat_multiplayer] Fix for multiple users behind a NAT

code/math/fvi.cpp, code/math/fvi.h
During the process of applying the 'const' and 'static' keywords to the math/fvi module, it was discovered that nine routines in that module were unused in the project.  Some of these appear to have never been used in the history of the project.  Others were used once, but have not been in use since 2010 (if I remember correctly).  Given their apparent lack of use, I am proposing their removal.
Although those nine routines are listed in one of the commit messages in this set, I have listed them here for convenience.
Removes the following unused routines ...
1. accurate_square_root()
2. fvi_point_dist_plane()
3. fvi_segment_plane()
4. fvi_sphere_perp_edge()
5. check_sphere_point()
6. fvi_check_sphere_sphere()
7. fvi_cull_polyface_sphere()
8. fvi_closest_point_on_line_segment()
9. …
=> math/fvi: apply const and static keywords

code/weapon/swarm.cpp
=> Passing value 2.0 to asin() leads to implementation-defined result

projects/MSVC_2010/code.vcxproj, projects/MSVC_2010/code.vcxproj.filters, projects/MSVC_2012/code.vcxproj, projects/MSVC_2012/code.vcxproj.filters, projects/MSVC_2013/code.vcxproj, projects/MSVC_2013/code.vcxproj.filters
Looks like a lot of changes but this is already mostly accomplished in master.  Fixes the file structures according to how the latest VS versions want the files to look like.  Proper line endings, etc.  'git diff -w' indicates a very clean set of functional changes, the rest is just whitespace.  These changes were mostly already made in master though, we may want to consider not merging this until master is merged into antipodes and then fixing the project files in antipodes to be a clean diff against master.
=> Add the osapi/dialog files to the other VS projects.

code/sound/audiostr.cpp, code/sound/audiostr.h, code/sound/ogg/ogg.cpp, code/sound/ogg/ogg.h
Previously audio streams used either MMIO (on windows) or the file system abstraction provided by SDL. With these changes every platform uses the file system abstraction provided by FSO.
This is a proposed fix for #225, it has been tested on windows and linux.
=> Use the CFILE system to handle audio IO

code/sound/audiostr.cpp, code/sound/rtvoice.cpp, code/windows_stub/config.h
As noted in #236, `NULL` was being compared with an integer value (`SDL_TimerID`) which caused issues on FreeBSD.
=> Don't compare NULL with integer

code/playerman/playercontrol.cpp
Allows any of pitch/yaw/bank to be freely bound to any axis.
=> Fixes Mantis #2436: Mouse controls ignore the axis binds.

code/math/floating.h, code/math/fvi.cpp, code/math/spline.cpp
3 minor refactors to the math code.
1. Rejiggerring the parentheses in macros fl_degrees and fl_radians() allows the compiler to precalculate the radians-to-degrees ratio so that a runtime division operation can be avoided.
2. Using a table to lookup factorials cuts down on the generated code.  In the previous implementation, the compiler (GCC 4.6.3) was both unrolling the loop and inlining the generated code.  The lookup table is only valid for 0! -> 12! as that was the valid range in the previous implementation.
3. Simplifies the solution to the quadratic equation in fvi.cpp by solving "A*x*x + 2*B*x + C = 0" instead of "A*x*x + B*x + C = 0".  This cuts down on the number of required multiplications.  (Commit message has the math to back it up).
=> Math refactoring

projects/MSVC_2013/Fred2.vcxproj
Edited in VS2013 which fixed the file's line endings to CRLF.  Logically only a one character deletion in the file.
=> Fix the output Fred SSE target name.

code/ui/slider2.cpp
in set_currentItem().  From FSCyborg's PR #221.
=> [fix/cid_1204285_divide_by_zero] Fix CID 1204285: Division by zero

code/cmdline/cmdline.cpp
This should match what was done in `SDLMain.c` with SDL 1.2.
This isn't hidden behind a `#ifdef APPLE_APP` to keep behavior consistent across platforms.
=> Proposed fix for #248

code/sound/ds.cpp, code/sound/openal.cpp
Fix the issue pointed out by Yarn where the OpenAL info for the default
device was being logged instead of the info for the selected
device. http://www.hard-light.net/forums/index.php?topic=90070.0.
=> Log OpenAL info for selected device.

code/ai/aiturret.cpp, code/model/model.h, code/parse/sexp.cpp, code/parse/sexp.h, code/ship/ship.cpp, code/weapon/swarm.cpp
This creates the foundation of turret ammo through the "turret use ammo" subsystem flag. Turret ammo works in the same manner as ship ammo, where the ammo is equal to bank capacity divided by the cargo size of the weapon. This was tested using the Blue Planet: War in Heaven mod.
Test case: UEFg Narayana turrets 19 through 21, all of which contain Apocalypse torpedos with a $Cargo Size: of 2.5, were changed to use ammo with a $SBank Capacity of 20, resulting in a total ammo capacity of 8 torpedos. The Narayana was ordered to attack a GTCv Diomedes; it fired 8 torpedos each from turrets 19 through 21 before stopping. The mission was left to proceed for an additional 2 minutes, in which time the Narayana did not fire any more torpedos. Note: The Apocalypse takes 20 seconds to fire each 4 …
=> Turret Ammo Implementation

code/globalincs/pstypes.h, code/globalincs/windebug.cpp, code/osapi/outwnd.h, code/windows_stub/stubs.cpp, fs2open.Doxyfile
These macros can be used to identify which parameters contain a `printf`-style format string. This allows to do static checking if a format string matches the supplied arguments.
Currently contains macros for GCC/clang using `__attribute__ ((format (printf, x, y)))` and SAL specifications for Visual Studio which are used when doing static code analysis.
=> Add format specifying macros

projects/MSVC_2015/Fred2.vcxproj, projects/MSVC_2015/Freespace2.vcxproj, projects/MSVC_2015/code.vcxproj, projects/MSVC_2015/libjpeg.vcxproj, projects/MSVC_2015/liblua.vcxproj, projects/MSVC_2015/libpng.vcxproj, projects/MSVC_2015/zlib.vcxproj
These are basically just the 2013 project files updated to use the `v140_xp` toolset, but this gives the MSVC_2015 folder the same improvements that the MSVC_2013 folder got in commit 66bddb9.
=> Update the VS 2015 project files.

code/parse/sexp.cpp
turret-set-primary-ammo and turret-set-secondary-ammo incorrectly had the descriptions for turret-get-primary-ammo and turret-get-secondary-ammo respectively.
=> Fix Turret Ammo Setter SEXP Descriptions

code/fred2/weaponeditordlg.cpp, code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/ship.h
Adds a get_max_ammo_count_for_turret_bank() function that the weapon editor can use for turrets instead of trying to hack the behavior into get_max_ammo_count_for_bank somehow. Adjusts weaponeditordlg.cpp to use it, and also fixes missionparse.cpp so that ammo values get correctly converted from a percentage to the number of actual missiles (but only when FRED isn't running).
=> Hopefully fix FRED and turret ammo.

code/ai/aiturret.cpp, code/weapon/swarm.cpp
A turret's current_primary_bank/current_secondary_bank is always
initialized to -1, this is set to 0 if it is still -1 when a turret
tries to fire. Ammo removal for swarm and corkscrew weapons is now done
using a single flag check instead of the original two.
=> Turret Ammo Fix: Default Bank and Ammo Removal location

code/asteroid/asteroid.cpp, code/lab/wmcgui.cpp, code/mission/missionbriefcommon.cpp, code/mission/missionparse.cpp, code/model/modelread.cpp, code/network/multi_ingame.cpp, code/network/multi_sexp.cpp, code/network/multimsgs.cpp, code/object/collideshipship.cpp, code/object/waypoint.cpp, code/parse/scripting.cpp, code/parse/sexp.cpp, code/pilotfile/csg_convert.cpp, code/pilotfile/plr_convert.cpp, code/ship/ship.cpp
Resolves a number of format string-related warnings reported by GCC 4.9, now properly exposed.
Some locations miss variables, some locations have too many variables. Some locations lack format string specifiers.
=> Resolve numerous format string issues

code/mission/missionparse.cpp, code/ship/ship.cpp
So it turns out it actually was the secondary code triggering the Assertion, because `ship_system->weapons.secondary_bank_weapons[]` was full of 0s. Subach HL-7 is weapon type 0, and obviously doesn't have a `cargo_size`. I see no reason to iterate through `MAX_SHIP_PRIMARY_BANKS`/`MAX_SHIP_SECONDARY_BANKS` if there aren't that many banks being used anyway.
=> Actually fix the `cargo_size` check for turrets.

code/parse/sexp.cpp
Somehow, this got missed during the creation of the pull request, and I guess nobody (not even me) actually tried using it since then.
=> Make beam-create actually call sexp_beam_floating_fire().

code/parse/sexp.cpp
If the subsystem was <none>, sexp_beam_floating_fire() wasn't consuming the node, resulting in it also being parsed as the X coordinate (making it always zero, because atoi("<none>") == 0).
=> Fix beam-create with targeting coordinates instead of a ship/subsystem.

code/cmdline/cmdline.cpp, code/freespace2/freespace.cpp, projects/Xcode4/Info.plist
*This is a PR to antipodes branch*
Resolves:
* Issue #248, and
* the lack of a working directory being set with SDL2-based middleware, which only affects fs2open when run from Finder (i.e. double clicking on .app bundle).
Specifically for the second resolved problem, with SDL1-based middleware `projects/Xcode4/SDLMain.m` used to set the working directory via `setupWorkingDirectory()`. This function is no longer present with SDL2. Accordingly, unless run from the Terminal a working directory is not set.
This leads to a number of problems on OS X with antipodes, not least of which is `cfile_init()` fails which leads to an early `exit(1)`.
Although we use `SDL_GetBasePath()` to set the working directory (not always strictly true), this limitation was already present on OS X with the …
=> Fix antipodes on OS X

code/mission/missiongoals.cpp
There's an undocumented feature whereby negative trigger counts are treated as infinite. However, since it doesn't use the bump_timestamp system of positive trigger counts, it'll behave more like an infinite repeat count (e.g. with "+Interval: 5" it will only check every 5 seconds instead of becoming active again after 5 seconds have passed). This just makes negative values set bump_timestamp and excludes them from resetting the timestamp if the event didn't trigger that frame (checking MEF_USING_TRIGGER_COUNT so that the other behavior is still possible if you set a negative repeat_count and don't specify a trigger_count).
(As an addendum, FRED makes it somewhat more difficult to use negative repeat and trigger counts because it doesn't allow typing non-digit characters; you can still …
=> Fix infinite trigger count not interacting correctly with "+Interval:"

code/hud/hudartillery.cpp, code/hud/hudartillery.h
Allows specifying a min/max for count, radius, and/or offset. To make them variable, instead of e.g. "+Count:", specify "+Min Count:", which adds a requirement for "+Max Count:". Each time the strike is activated, it will pick a different random count, and each projectile in the strike will have a different random radius and offset.
=> Allow SSM(/SSB) strikes to be more variable.

code/playerman/playercontrol.cpp
Instead of the mouse's axes being automatically bound to heading/pitch/throttle, it finds what the axes are bound to (by looking through `Axis_map_to[]`) and modifies the corresponding values.
This PR replaces the incorrect (now-reverted) commit da71e62.
=> Fix Mantis #2436.

.gitignore, code/freespace2/freespace.rc, projects/MSVC_2010/Freespace2.vcxproj, projects/MSVC_2010/code.vcxproj, projects/MSVC_2010/code.vcxproj.filters, projects/MSVC_2012/Freespace2.vcxproj, projects/MSVC_2012/code.vcxproj, projects/MSVC_2012/code.vcxproj.filters, projects/MSVC_2013/Freespace2.vcxproj, projects/MSVC_2013/code.vcxproj, projects/MSVC_2013/code.vcxproj.filters, projects/MSVC_2015/Freespace2.vcxproj, projects/MSVC_2015/code.vcxproj, projects/MSVC_2015/code.vcxproj.filters
These are only used for voice recognition on Windows. In addition, the gc.exe shouldn't be needed locally since it should be included with SAPI, which Visual Studio 2010 and later should already include.
I also tried to backport some of the changes from the 2013/2015 project files to the 2010/2012 project files, but lack of certain compiler flags made me tend to err on the conservative side in that regard.
Obviously, this PR will be obsoleted by the move to cmake, but I figure I might as well open it anyway since I did most of the work a while ago (just did the copy/paste job on the 2010/2012 projects for this PR).
=> Move the temporary grammar files into the build directory.

code/weapon/beam.cpp
This should allow 0-damage beams to be used to apply TAG effects.
On the flip side, it could have some unexpected consequences with existing mods that use 0-damage beams for anything (sudden appearance of impact sparks, for instance). Theoretically it could also cause problems if somebody had a 0-damage beam with TAG data that they were relying on not TAGing things for some reason, but that seems exceedingly unlikely.
There's also a minor cleanup commit that I noticed as I was poking around beam.cpp.
=> Remove do_damage check before calling hit functions in beam collisions.

code/bmpman/bmpman.cpp
The previous check was always false, replace with something that should
safely detect uint overflow.
This probably won't help the bmpman slots issue that WoD & JAD have seen... I mean if the slots were trying to overflow you'd probably get some sort of handle collision if the next handle is reset to one?
=> Fix Coverity 1093366: Operands don't affect result

code/playerman/playercontrol.cpp
Makes the joystick by far more responsive, as requested here: [Joystick turning lag] (http://www.hard-light.net/forums/index.php?topic=90306.msg1793490#msg1793490)
The polling method ended up getting a response time of twice of what was expected, since we couldn't find a good reason to keeping the polling method for modern hardware, it was decided to remove that altogether and have the joystick queried every frame for maximum responsiveness.
Ended up going with MageKing's idea of removing the NDEBUG block along with the polling, since it's no longer relevant.
=> Removes joystick polling. Joy axes are now queried every frame.

code/parse/lua.cpp
Previously, the `this != NULL` checks in the `isValid()` methods were covering most of these cases, but they were removed as part of PR #274 because clang was generating warnings because calling a method on a null pointer is undefined behavior (so the condition *should* be tautological). This performs the checks outside of `isValid()`, which should avoid (at least this variety of) undefined behavior while fixing the crashes that dereferencing null pointers was causing.
=> Add null pointer checks throughout lua.cpp.

code/parse/parselo.cpp
Also fixes saving missions in FRED, since it uses the same function.
=> Makes vsprintf() stop chopping off the last character. Fixes issue #298.

code/fred2/management.cpp
Avoids a constant stream of warnings when using "$Glowpoint overrides:".
=> Makes FRED call glowpoint_init().

code/ai/aiturret.cpp
Forgot to set `last_fired_turret` and its `last_fired_weapon_info_index`, causing CHA_ONTURRETFIRED to crash as soon as a swarm turret fired.
Oops.
=> Fix null pointer dereference with swarm turrets and "$On Turret Fired:".

code/parse/sexp.cpp
`ssm_create()` subtracts the start coordinates from the position of the target, and then normalizes that. Since call-ssm-strike was using the position of the target as the start coordinates, this was obviously resulting in normalizing a null vec3d, generating the spurious warning. This just makes call-ssm-strike use a point immediately behind the target's position (using the target's orientation) as the starting coordinate, thereby avoiding the warning.
=> Fixes call-ssm-strike resulting in a Warning about a null vec3d.

code/fred2/management.cpp
This would cause FRED to treat essentially unspecified pieces of memory as ship classes and then see if this nonsense class had the `SIF_DEFAULT_PLAYER_SHIP` flag set... and if so, put it in the default list of available ships. With a debug build (where the memory past the end of `Ship_info` is all identical for quite a ways), this could result in the default, empty mission saving as 60 megabytes.
=> Replaces a reference to MAX_SHIP_CLASSES with Ship_info.size().

.travis.yml
This should let Coverity run a scan via Travis whenever commits
are pushed to the "coverity_scan" branch.
Some hackery is required to avoid submitting too many builds to
Coverity. See travis-ci/travis-ci#1975 for details.
=> Integrate Coverity with Travis CI

code/missionui/missionshipchoice.cpp
Stops stripping newlines from ship descriptions, and resizes the text width according to Yarn's findings.
=> Fix Mantis #3144.

.travis.yml, ci/travis/before_install.sh, ci/travis/install.sh, ci/travis/script.sh
Now that all APT packages are supported we can switch to the container based infrastructure. It should be faster and provide more features for future usage (e.g. caching).
=> Travis CI: Switch to container infrastructure

code/io/joy-sdl.cpp, code/io/joy-unix.cpp, code/io/joy.h, code/osapi/osapi.cpp
Previously, when a joystick event happened that was related to axis movement, it would be ignored by the os_poll(). Button presses from joystick events were still processed, however.
This PR changes the axis polling system to be asynchronous of frame time, simplifying the joy_read functions to just read from a buffer instead of polling the joystick per frame. This should hopefully be the "fastestest" we can get with SDL when concerning analog inputs.
=> joy_asynch - Enables SDL's event handling for joystick axes

code/parse/lua.cpp
These are useful for things such as a mouse script that can be configured in-game.
=> Added Lua functions to read mouse/joystick sensitivity and deadzone

code/bmpman/bmpman.cpp
Useful in figuring out what's causing BMPMAN limits to be reached...
=> Add debug console command to log bmpman slot info

.gitignore, code/weapon/beam.cpp
Started a discussion about this here: http://www.hard-light.net/forums/index.php?topic=90329.msg1793720#msg1793720
The three people that replied seemed to like the idea of just never drawing it, but I could make it more complicated if people desire. ;)
=> Removes the beam flash impact from appearing when viewing from the hit object's cockpit

code/fred2/missionsave.cpp, code/mission/missionbriefcommon.h, code/mission/missionparse.cpp, code/missionui/missionbrief.cpp
see http://www.hard-light.net/forums/index.php?topic=90337.0
No FRED support - just add the appropriate text lines in the mission file using a text editor.  However, FRED will still load/save the mission file properly, preserving the mission background lines if they exist.
=> mjn.mixael's request for per-mission briefing backgrounds

code/windows_stub/stubs.cpp
The new version of `dump_stacktrace` uses abi::__cxa_demangle to determine the real name of a C++ function instead of printing the mangled name to the stacktrace.
=> Improve linux stacktraces

code/graphics/2d.cpp, code/graphics/gropengl.cpp, code/graphics/gropengl.h
When using the Linux AMD proprietary driver FSO gets stuck when trying to swap buffers when performing an abnormal shutdown (e.g. when exiting via a dialog). This skips the gr_flip calls when we are going to close as it doesn't matter anyway.
=> Workaround for freezing when exiting abnormally

code/weapon/beam.cpp
So in PR #294, I made 0-damage beams call the damage-applying code so they could be used to TAG things. The way I did this was I removed the `do_damage` check from the conditional before the switch block that handles beams damaging things.
This was a horrible mistake.
`do_damage` was set to 0 if a beam dealt `<= 0` damage, but before that, it would only be set to 1 if the damage timestamp had elapsed. Removing the `do_damage` check caused damaging beams to deal damage every frame, which obviously will cause a substantial damage increase (well, unless your framerate was so low that beams would deal less than their full damage anyway).
This commit restores the `do_damage` check, and simply avoids setting `do_damage` to 0 if the beam isn't a damaging one (the `<= 0` check is moved to …
=> Fix Mantis #3173.

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/parse/lua.cpp
A very simple refactor patch, which addresses a TODO comment in the code/documentation.
=> Refactor bm_set_render_target() return type to bool, thereby removing a TODO

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h
This is a simple refactor patch that says what it does on the label.
Wholly unrelated, it would be nice if we had unit tests for these sort of changes. But that issue is being tracked elsewhere.
=> Refactor bm_load_and_parse_eff() return type to bool, thereby removing a TODO

code/graphics/gropenglextension.cpp
While investigating issue #345, it was discovered that `popup()` is getting called during `gr_init()` (and since this is before `gamesnd_parse_soundstbl()` gets called, the eventual call to `gamesnd_play_iface()` results in reading invalid memory). Given that this is basically relying on a feature in the middle of the function initializing it, and given that both lines are preceded by `mprintf()` calls saying basically the same thing, it seems the best solution is to just remove the troublesome lines altogether.
=> Stop calling popup() during gr_init().

code/mission/missionparse.cpp
This includes Goober's change from PR #333.
Notes: the reason for the added (Game_mode & GM_IN_MISSION) check is to prevent all ship creation during mission load from triggering the hook, and only limit it to in-mission arrivals. This is likely the original reasoning for why the code was where it was.
=> Fixed the $On Ship Arrive hook code as per issue #334 and PR #333

code/parse/scripting.cpp
Should result in reduced BMPMAN slot usage with certain scripts as `bm_unload()` unloads the image data but holds on to the slot, while `bm_release()` releases the slot.
=> Make script_state::UnloadImages() call bm_release instead of bm_unload.

code/graphics/generic.cpp, code/mission/missionmessage.cpp
As headani's (both ANI & EFF) are streamed there's no need to have
the anim data in bmpman, the streaming code does that with only two
slots, rather than one slot per ani frame
Also fix a "leak" in the streaming code use of bmpman slots. i.e. each
time a message was played another slot would be used & not released
=> Reduce bmpslot usage by headz

code/fred2/FictionViewerDlg.cpp, code/fred2/FictionViewerDlg.h, code/fred2/missionsave.cpp, code/fred2/missionsave.h, code/mission/missionbriefcommon.h, code/mission/missionparse.cpp, code/missionui/fictionviewer.cpp, code/missionui/fictionviewer.h, code/missionui/missionbrief.cpp, code/missionui/missioncmdbrief.cpp, code/missionui/missioncmdbrief.h, code/missionui/missiondebrief.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/missionui/redalert.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/network/multiteamselect.cpp
This code expands on Goober's earlier code for per-mission briefing backgrounds to also allow the ship selection, weapon selection, debriefing, command briefing, and fiction viewer screens to use custom backgrounds. It also allows the fiction viewer UI to be explicitly specified in mission files and game_settings.tbl. Details on using these features are in this post: http://www.hard-light.net/forums/index.php?topic=90337.msg1795797#msg1795797
=> Per-mission UI backgrounds

code/parse/lua.cpp
If the input string is "/", then buf[-1] would get accessed and in rare cases also modified.
=> Fix possible out of bounds array access

code/fred2/missionsave.cpp, code/fred2/missionsave.h
Makes `save_mission_file()` and `autosave_mission_file()` delegate to a new `save_mission_internal()` function. Tested and works with both manual and automatic saves.
As an aside, this fixes a slight inconsistency between manual and automatic saving (which inspired this refactor in the first place): when the order of `save_fiction()` and `save_cutscenes()` was swapped (in r10886 a.k.a. d6e0a73), `autosave_mission_file()` wasn't also changed, so autosaves of missions with "#Cutscenes" sections can't actually be loaded.
=> Refactor mission saving to avoid duplicate code.

code/hud/hudsquadmsg.cpp, code/sound/phrases.xml, code/sound/voicerec.cpp
* Frees `cpAudio` pointer in `VOICEREC_deinit()`
* Validates that the ship/wing can actually take orders, and validates that it can take the specific order in question before trying to send it.
* Reports the confidence of the voice match if `DEBUG_ON` is set.
* Various commenting changes based on the patch.
Not included: using confidence to discard voice matches that fall below a certain confidence level. I haven't noticed a tendency towards spurious matches, and I didn't want to introduce this without additional data, especially when it might cause problems for people with different accents (and ESPECIALLY without a setting to tweak the threshold value, which the original patch did not have; it was hardcoded at 90%).
[Mantis link](http://scp.indiegames.us/mantis/view.php?id=2373)
=> Voice recognition cleanup based on Mantis #2373 patch.

code/fred2/FictionViewerDlg.cpp, code/fred2/missionsave.cpp, code/graphics/font.cpp, code/graphics/font.h, code/mission/missionparse.cpp, code/missionui/fictionviewer.cpp, code/missionui/fictionviewer.h, code/sound/audiostr.cpp, code/sound/audiostr.h
Per Battuta's request in HPC, this adds support for multiple fiction viewer stages per mission.  Only one stage will be displayed when the mission loads, but the associated conditional sexp will determine which of the several stages will be displayed.
FRED support consists of just loading and saving; the addition of sexp tree GUI support would require a bit more coding work.
Note that this PR rearranges the new fields for the fiction viewer that Yarn added in #353.  This was necessary because the required field $File must appear first so that the parser can determine the number of stages on the fly.
=> Fiction viewer conditional support

code/missionui/fictionviewer.cpp
=> cfclose() will hit an assertion if we try to close a null pointer

code/weapon/weapons.cpp
Battuta reported that leaving Min Damage or Max Damage undefined returns debug warnings.
This does fix the issue.
=> Fix debug warning in min max damage definition code

code/weapon/weapons.cpp
This moves the debug warnings so they only get checked if we actually set a value for min or max damage.
=> Additional debub warning move

code/parse/sexp.cpp
When you compare the usage of Error() throughout sexp.cpp, it's always used for more or less fatal errors.  But these background bitmap errors are recoverable and the mission can continue on.
=> made background sexp errors less fatal

code/menuui/techmenu.cpp
Because _some people_, and I am not naming any names, apparently write novels.
Which are awesome and should be represented in game without crashing.
=> Slightly increases the length limit for tech descriptions.

code/mission/missionbriefcommon.h
Addresses his comment here:
https://github.com/scp-fs2open/fs2open.github.com/commit/05d4e44c97100486fa68328fbfc89be68bed9a04#commitcomment-13593222
I did a regex search through the codebase and fortunately there are no other instances of 0 being the last argument instead of the middle one.
=> fix a memset typo identified by Echelon9

code/graphics/2d.cpp, code/graphics/gropengl.cpp
Adds a config file parameter that specifies the display where the main window is created. This was requested as part of Mantis 2826.
=> Add support for specifying the used display

code/network/multimsgs.cpp, code/parse/lua.cpp, code/weapon/weapons.cpp
The rest of the codebase uses &obj_used_list to mean "no homing target", and the inconsistency could cause all kinds of issues.
=> Stop comparing/setting homing_object to NULL.

code/weapon/weapons.cpp
"$Detonation Radius:" and "$Arm radius:" would both rely on `wp->homing_pos` being set if `wp->homing_object` was; however, during free flight time, `wp->homing_pos` remains uninitialized (a null vector). As a result, their `vm_vec_dist()` calls would be comparing with the distance from the mission origin (coordinates 0,0,0) instead of the actual location of whatever they were homing in on. In the case of detonation radius, this would result in instant detonation on launch if you fired within `det_radius` of the mission origin. In the case of arm radius, this would result in the weapon being armed during free flight if launched within the `arm_radius` of the origin (and yes, you could theoretically experience the effects of both of these bugs simultaneously).
Theoretically, this solution …
=> Check IS_VEC_NULL(&wp->homing_pos) for det_radius and arm_radius.

code/parse/sexp.cpp
Affected SEXPs include `turret-set-target-order`, `turret-set-direction-preference`, `turret-set-rate-of-fire`, `turret-set-optimum-range`, `ship-turret-target-order`, `turret-get-primary-ammo`, `turret-set-primary-ammo`, `turret-get-secondary-ammo`, and `turret-set-secondary-ammo`.
It's worth noting that while `turret-set-direction-preference`, `turret-set-rate-of-fire`, and `turret-set-optimum-range` were wrong, they were wrong in a way that wouldn't actually affect the outcome most of the time (thanks to the `if(turret == NULL)` checks simply skipping invalid subsystem names).
=> Fixes numerous SEXPs accessing the wrong nodes.

code/bmpman/bmpman.cpp
This was reported in #381. I'm pretty sure that the allocated memory is only used temporarily and cleaning it up at the end of the block doesn't cause any side effects.
=> Fix memory leak in bm_load_animation

code/mission/missionparse.cpp
A longstanding issue for capship command missions has been that hangars on player ships don't work. The reason for this was that the engine kept the player ship in the Arrival_List; according to the :V: comments, this was done to allow respawns in multiplayer.
I've amended the check so that the player ship gets treated correctly in singleplayer.
=> Allow ships to arrive from hangars on player ships

code/hud/hudsquadmsg.cpp
This reverts commit 2aa569c1e762413112717fde5405e3bb0b96d210.
As discussed in #386 hud_squadmsg_is_target_order_valid actually doesn't properly catch cases where the target_objnum may be -1.
=> Revert "Fix for Coverity 1093600: Negative array index read"

code/graphics/generic.cpp, code/mission/missionmessage.cpp
Tested with a mission that repeatedly plays command head animations running through valgrind. Confirmed that report in #381 has been removed.
=> Fix memory leaks in generic_anim_stream

code/freespace2/freespace.cpp
While working on #389, I noticed that `shipfx_eye_in_shadow()` is called 2n times, where n is the number of light sources in the mission.  Since this function is expensive, let's only call it n times.
=> small optimization of shadow checks

code/mission/missioncampaign.cpp
Related to #381 (memory leaked from early call of cs_read_missions)
=> Fix memory leaks in mission_campaign_load

code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/missionui/missionweaponchoice.cpp
The draw_model_rotating() and draw_model_icon() functions were receiving
the whole Weapon_Info array (Weapon_Info->variable) instead of a single weapon_info object (wip->variable in this case).
These have been replaced with proper pointer(s).
=> Fix Closeup_Pos and Closeup_Zoom

code/fred2/missionsave.cpp, code/fred2/voiceactingmanager.cpp, code/fs2netd/fs2netd_client.cpp, code/gamesnd/gamesnd.cpp, code/hud/hudshield.cpp, code/hud/hudtarget.cpp, code/mission/missioncampaign.cpp, code/pilotfile/csg_convert.cpp, code/pilotfile/pilotfile_convert.cpp, code/pilotfile/plr_convert.cpp, code/playerman/playercontrol.cpp
Speaking of const_cast, many of them are no longer needed now that there are more const-correct functions in the codebase.  Applying this PR brings the total number of const_casts down to 5.
=> remove obsolete const_casts

code/cfile/cfilesystem.cpp, code/graphics/gropengllight.cpp, code/network/multi_obj.cpp, code/network/psnet2.cpp, code/ship/shiphit.cpp, code/weapon/beam.cpp
My sources indicate that std::sort can often be substantially faster than qsort, since qsort invokes a function for every comparison whereas std::sort can inline the comparison.  Additionally, qsort makes no guarantees about performance, whereas std::sort is specified to have minimum n\*log(n) performance.  (In fairness, most implementations of qsort also have n\*log(n) performance, at least in the average case.  NB: qsort is not required to use the quicksort algorithm.)
Incidentally, @asarium may suspect that I'm biased against C++ due to conversations like #384, so hopefully this PR will serve as evidence otherwise. ;)
=> convert qsort to std::sort

code/graphics/2d.cpp, code/graphics/2d.h, code/menuui/mainhallmenu.cpp
As you might know, if sparky_hi_fs2.vp is missing, FSO changes the resolution to 640x480 if it was 1024x768 originally, and to 800x600 in other cases. However, this is incorrectly being done to *all* resolutions instead of just those that use high-resolution graphics (1024x600 and above). The effect of this is that low resolutions like 720x576 and even 640x480(!) are changed to 800x600 in this situation.
The changes in this pull request fix this problem.
=> Sparky hi fallback fix

code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/freespace2/freespace.cpp
Another one from #381, not very serious since the config presets are needed until game close anyway.
=> Fix memory leak from Control_config_presets

code/hud/hudmessage.cpp, code/hud/hudparse.cpp
Scales head animations to fit the talking head gauge's window. For more information, see the original Mantis report:
http://scp.indiegames.us/mantis/view.php?id=3122
=> Scalable head ANIs

code/sound/ds.cpp
Last fix for #381; stereo sounds converted to mono for 3D playback were leakin'
=> Fix memory leak in ds_load_buffer

code/graphics/2d.cpp, code/mission/missiongoals.cpp
While testing out Her Finest Hour for the BP:WiH rerelease, we found that under certain very common conditions event evaluation could spike to take up several hundred milliseconds. In order to find the cause, I added these profile points, I think they will come in handy for everyone.
=> Profiling support for mission events and scripts

code/freespace2/freespace.cpp
Thanks to Yarn for noticing this issue in #412.  When comparing the fiction viewer state with the other pre-mission states (GS_STATE_CMD_BRIEF, GS_STATE_RED_ALERT, etc.) in that same function, the fix becomes evident.
=> properly close the fiction viewer when returning to the main menu

code/ship/shipfx.cpp, code/ship/shipfx.h
It would have been sufficient to change one function's signature to remove the warning, but I thought I'd change all three `shipfx*in_shadow()` functions for consistency.
=> change these functions to return bool rather than int; fixes a minor warning

code/graphics/2d.h, code/graphics/gropengl.cpp, code/graphics/gropengldraw.cpp, code/graphics/gropengldraw.h, code/graphics/gropengltexture.cpp, code/graphics/gropengltnl.cpp, code/graphics/gropengltnl.h, code/graphics/grstub.cpp, code/io/keycontrol.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/model/modelinterp.cpp, code/render/3d.h, code/render/3ddraw.cpp, code/render/3dinternal.h, code/render/3dlaser.cpp, code/render/3dmath.cpp, code/render/3dsetup.cpp, code/starfield/starfield.cpp
After comments on #392, I decided to see about making `g3_set_view_matrix` (and other functions in 3d.h) const-correct.  This actually wasn't as bad as it could have been, owing mostly to the surprising fact that vertexes are often modified as they are drawn and so can't be const.  This isn't limited to clipping polygons, it also has to do with projecting and truncating lines.  Anyway, this diff is the result.
I did have to use `const_cast` in just a few places where the g3_ API calls the gr_ API.  Also, I removed two ugly instances of an `angles` struct being modified, used as a temporary variable for a calculation, then restored to its original value.
And yes, this PR adds `const` to the two parameters in `draw_model_icon` that I wanted to be const.
=> const-correctness inspired by #392, because why not be masochistic

code/graphics/gropengl.cpp, code/graphics/gropenglextension.cpp
Our present approach queries `glGetString()` with `GL_SHADING_LANGUAGE_VERSION_ARB`, which is not guaranteed to be present in future releases.
Refer OpenGL specifications: https://www.opengl.org/sdk/docs/man/html/glGetString.xhtml
Tested on the following OpenGL drivers:
* Mesa open source (Intel i965)
* Apple
=> Use the Core rather than older Extension form of GL_SHADING_LANGUAGE_VERSION

code/parse/sexp.cpp
We were declaring an array of `NUM_TURRET_ORDER_TYPES` `int`s, and then only specifying the first `oindex` of them; the `memcpy()` could've been changed to multiply by `oindex` instead, but it seemed cleaner to just reset `new_target_order` to -1 in all values and get rid of the redundant per-ship reset.
Discovered by triggering an `Int3()` in aiturret.cpp (line 1167 as of this writing) and finding uninitialized values in the `turret_targeting_order` array.
=> Fix ship-turret-target-order.

code/weapon/beam.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Directional Beam Glows, unlike conventional Muzzle Glows, are rendered to a project poly made of 4 vertices and oriented around the firing point.
Example of it in action: http://i.imgur.com/t0DMeHx.png
While not very noticeable initially, it is especially useful for AAA beams that have a very short life and need a bursty appearance.
This works using +Directional Glow: float, which sets a length value in meters for the glow, and the +Radius is used as the height.
=> Directional beam glows

code/sound/audiostr.cpp
There is a bug in the events editor that crashes FRED when the user tries to play a sound file whose file name has at least 28 characters and has the extension ".wav" or ".ogg". This is caused by the game trying to add another extension to the name, potentially resulting in a string that's longer than the maximum of 31 characters. The change in this PR fixes this bug (hopefully without breaking anything else).
=> Fix for crash in events editor

code/globalincs/globals.h
Because apparently, this is a thing we will need to have in Blue Planet.
Yes, I know it's better to remove the limit completely, which I am working on. But until that's finished, we need this to continue work.
=> Upped MAX_SHIP_CLASSES to 500

code/object/collideshipweapon.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
This deprecates +Min Damage and +Max Damage, as having two variables for what is effectively the same case and algorithm is not the most ideal situation.
Retested with current mods and retail to ensure compatibility, nothing to report on that front.
=> Deprecate +Min Damage and +Max Damage, add +Attenuation Damage:

code/lighting/lighting.cpp, code/lighting/lighting.h
Applies keywords such as 'const', 'static', ... to the lighting module.
Along the way it was discovered that two of the global variables in that module are no longer used (hence their proposed removal).
=> Lighting apply keywords

code/mission/missionmessage.cpp, code/mission/missionmessage.h
Currently, builtin messages can default to other messages from the same persona, or even other messages from other personas if they do not define a particular message. This is breaking the mood in mods where certain messages are excluded on purpose. This PR therefore introduces a persona flag to control this behaviour.
=> Adds Persona flag "$Allow substitution of missing messages:"

code/cmeasure/cmeasure.cpp, code/cmeasure/cmeasure.h, code/weapon/weapon.h, code/weapon/weapons.cpp
I've combined the commits into a single PR because they're changing the same areas of the code and will be simpler to merge together.
=> Add two small countermeasure features

code/ship/ship.cpp
The rearm code was checking the hull repair rate instead of the subsystem repair rate when rearming. This should be fixed now.
=> Fix support subsystem repair rate

code/mission/missioncampaign.cpp, code/mission/missioncampaign.h, code/parse/lua.cpp
The purpose of this function is to provide modders the capability to jump to a mission using LUA scripts. There is an optional argument for jumping to a hub mission, a good example is the JAD campaign map.
=> Add jumpToMission LUA function and a jump to hub function

code/weapon/weapon.h, code/weapon/weapons.cpp
Note that aspect missiles don't lose lock when their target dies, I'll
see about adding that later
=> Allow aspect missiles to die when have lost lock

code/fred2/eventeditor.cpp
The function can get called with an m_cur_msg of -1 if there are no messages defined by the mission; since this is apparently intended behavior (and causes no problems thanks to the immediately-following if-statement), may as well change this assertion.
=> Fix incorrect assertion in FRED's Event Editor when deleting a message.

code/hud/hudbrackets.cpp
The change in this PR fixes a bug where ship info displayed next to target brackets assume a font height of 9, resulting in text overlapping if the actual font height is greater than that. It also removes an assumption that the attacker blip has a size of 5x5, allowing larger or smaller blips to display properly and preventing larger blips from being overlapped by the target info.
=> Target bracket line height fix

code/ship/ship.cpp, code/weapon/weapons.cpp
If a modular table broke the weapons limit, it would warn about too many weapon classes, and then not actually skip the entry, because of the `if(!replace)` conditional around it, resulting in nonsensical parsing errors. Rather than just fix this error, it was suggested on IRC (by The_E) that these problems should instead cause immediate errors. Upon reflection, this makes more sense: if the mod exceeds the limits, there's little point in loading it anyway and having things be missing.
Hopefully, eventually, these limits will be removed altogether, but until then, exceeding them should not just be a dismissible warning.
=> Change warning from too many ship/weapon classes to an error.

configure.ac
That should let the compiler make a few more optimizations for the current system (release builds would probably need to override this to ensure that the executables run on other systems).
I did some profiling with the different versions:
Both times I ran the Icarus cutscene of Blue Planet 2. The graph doesn't really show any big difference but it's better to let the compiler use what it can.
=> Use -march=native for linux builds

code/parse/lua.cpp
After a lot of trial and error involving a simultaneously very-reproduceable and yet hard-to-track-down crash in the new Blue Planet release, I found that the problem is ultimately due to some inconsistencies in the Lua interface (ultimately leading to an uncaught negative index array access). This PR fixes the issue several times over. Firstly, looking up a wing by name no longer returns an invalid wing handle if the wing doesn't currently have any ships in the mission. Secondly, invalid wing handles can now be checked for with a new `isValid()` function. Thirdly, indexing an invalid wing handle will now produce an invalid ship handle instead of performing an out-of-bounds array access. Lastly, there's a cleanup commit (004fdae) to just fix a couple of other issues I happened to see …
=> Fix various issues with wings in the Lua interface

code/ship/ship.cpp
PR #445 was unfortunately incomplete; it fixed the time estimate for repairs, but not the actual repair part. I think I've identified which piece of code was preventing the actual repairs from working. This `repair_allocated > 0` conditional is actively preventing the `sip->sup_hull_repair_rate == 0.0f` branch from executing (so `repair_allocated` remains 0 and subsystems can't actually repair).
=> Fix support subsystem repair rate (for real this time).

code/ai/aiturret.cpp, code/freespace2/freespace.cpp, code/fs2netd/fs2netd_client.cpp, code/fs2netd/tcp_client.cpp, code/globalincs/pstypes.h, code/globalincs/toolchain.h, code/globalincs/toolchain/clang.h, code/globalincs/toolchain/doxygen.h, code/globalincs/toolchain/gcc.h, code/globalincs/toolchain/mingw.h, code/globalincs/toolchain/msvc.h, code/pilotfile/csg.cpp, code/pilotfile/plr.cpp, code/ship/ship.cpp, code/sound/rtvoice.cpp, code/weapon/shockwave.cpp
An attempt to abstract toolchain capabilities to make it easier to add support for new ones, as well as maintain existing ones.
I may be wrong, but from what I gathered, the following toolchains were supported: MSVC, GCC, Clang and MingW.  If others are desired, the infrastructure makes it fairly straight forward to add new ones.  The proposed new file toolchain.h includes the compiler specific header appropriate to the detected toolchain.
Thus far, I have only tested this on an x86-64 linux platform with GCC.
=> Abstract toolchain capabilities

code/hud/hudparse.cpp, code/hud/hudtargetbox.cpp, code/hud/hudtargetbox.h, code/hud/hudwingmanstatus.cpp, code/hud/hudwingmanstatus.h
This PR implements the HUD table features that Shivan Hunter requested in [this thread](http://www.hard-light.net/forums/index.php?topic=90978.0). Here are the new options:
* Wingman Status
* Fixed Header Position: If set to true, then the header text stays in its normal position, even if more than two wings are displayed. Should be placed after "Header Offsets:".
* Extra Target Data
* Dock Max Width: Sets the maximum width of the docking status. Should be placed after "Dock Offsets:".
* Order Max Width: Sets the maximum width of the current order. Should be placed after "Order Offsets:".
* The ETA line is never truncated, so there is no "Time Max Width:".
* Radar (2D and 3D)
* Radar Center Offsets: Sets the position of the center of the radar. Unlike many other parameters, this one takes …
=> Shivan Hunter's requested HUD table features

code/math/vecmat.cpp, code/math/vecmat.h
This is something the compiler is better equipped to decide.
=> Removing the _INLINE_VECMAT preprocessor define

code/bmpman/bmpman.cpp
As requested in https://github.com/scp-fs2open/fs2open.github.com/pull/449/files#r45241401
Note that I also included the ref_count >= 1 check.
=> Fixes to some bm_unlock and bm_unload calls

code/graphics/font.cpp, code/graphics/font.h, code/hud/hudescort.cpp, code/hud/hudescort.h, code/hud/hudparse.cpp
It allows the escort gauge to render with ship names right-aligned, as the name would suggest. Inability to retrieve the width from `gr_force_fit_string()` (requiring another `gr_get_string_size()` call) is slightly inefficient, but performance impact is probably negligible.
Requested by ShivanHunter.
=> Add "Right-Align Ship Names:" option to HudGaugeEscort.

code/fred2/bgbitmapdlg.cpp
This PR fixes a bug where the orientation spinners in the background editor sometimes increment and decrement by the wrong amount, particularly when working with larger numbers.
=> Fix for spinners in background editor

code/fred2/fredrender.cpp
This fixes the bug described in [Mantis 3096](http://scp.indiegames.us/mantis/view.php?id=3096) by doing these things:
* Applying the pi*(4/9) correction to the briefing view, as is already done to the main view
* Always using the FRED_DEFAULT_HTL_FOV value for the main view's FOV rather than a mix of FRED_DEFAULT_HTL_FOV and 0.5
=> Fix for Mantis 3096

code/network/multimsgs.cpp
The Assert in #482  will now be split into both tests, with hopefully some more helpful information to see what might have happened.  Will ultimately have to see this happen again in production to attempt to resolve the actual issue.  Reproduction steps would be ideal but we don't know how this instance occurred.
As I don't know how to actually hit this assert, making sure that the tokenization is correct for the given variable types before it is actually encountered is probably the most import part of this PR.  I believe the ints and chars should be %d and the unsigned bytes and shorts should be %u but some double checking on that would be appreciated.
=> Enhance an Assert to help track down how issue 187 could happen

code/model/model.h, code/ship/ship.cpp, code/ship/ship.h
Can either be set for individual subsystems via the "autorepair if disabled" flag, or set for an entire ship via the "repair disabled subsystems" flag. It will, by necessity, only have an effect if the ship's "$Subsystem Repair Rate:" is a positive number.
Some things that I'm considering adding:
- ~~[ ] A (per-subsystem-configurable?) delay before a disabled subsystem repairs itself, so that autorepair capability doesn't mean a ship can't be temporarily disarmed/disabled.~~
=> Adds the ability for subsystems to repair themselves when disabled.

code/model/model.h, code/model/modelread.cpp, code/model/modelrender.cpp, code/ship/ship.cpp
Removes the reliance on ship_model_start/stop for rendering models. Also fix a bunch of oversights involving blown off models in the polymodel_instance code.
=> Allow model rendering code to use polymodel_instance. 

code/math/fvi.cpp, code/math/vecmat.cpp, configure.ac
Should work on GCC, tested and works on Xcode's clang.  clang isn't reporting any more unused functions, so GCC on Linux probably won't either, and I've removed that hider in the configure.ac.  If any more show up, we can probably determine whether to remove or protect them in a similar manner.  We could also do the same for unused parameters, unused variables, etc, but I'll leave that for another audit.  Would fix the remaining issues in #292.
=> Wrap some unused functions in a diagnostic protection pragma

code/model/modelinterp.cpp
When explosions or sparks or electrical arcs or debris are created, the code will choose some random vertices on the detail[0] submodel.  However, for some reason, it doesn't use the entire range of RAND_MAX.  It divides by 2^5 first.  Since RAND_MAX is usually 32767, this results in a range of 0..1023.  And since most capships these days have more than 1024 vertices, explosions etc. will only be generated on the first 1024 vertices of the model.
I first noticed this problem with Scroll's GTCa Warlock, but The Dagger confirmed that it was a problem with another Inferno model.  A third large model did not have the problem, but its first 1024 vertices were distributed throughout the ship.
The division by 2^5 dates all the way back to the retail code.  I can only speculate that it was meant …
=> for model vertices, use the entire range of RAND_MAX, not the range divided by 32

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/freespace2/freespace.cpp, code/menuui/playermenu.cpp
That option will make performance tests much easier.
The option causes the initial pilot selection to immediately accept the current pilot without further user interaction.
For starting a mission `-start_mission` can be used which will immediately run a mission until it is complete. This works best with cutscenes because no user interaction is required.
When the end of the mission is reached the benchmark option will automatically quit the game and an external script can collect the framerate results generated by the profiling subsystem.
=> Add benchmark command line option

code/hud/hudshield.cpp
Calculates the alpha range using the actual number of shield segments instead of 4.
=> Fix a small glitch in shield icon alpha range

code/ship/ship.cpp
This should fix https://github.com/scp-fs2open/fs2open.github.com/issues/237 where ships assigned with with SIF2_NO_LIGHTING still have directional lighting applied.
=> Restore SIF2_NO_LIGHTING functionality for ship_render().

code/model/modelread.cpp, code/model/modelrender.cpp
Should fix https://github.com/scp-fs2open/fs2open.github.com/issues/489. Does a minor change to `model_set_instance` so we don't irrevocably alter `bsp_info::my_replacement` whenever `SSF_NO_DISAPPEAR` is on while still offering the same functionality; whatever `model_load()` reads in should be expected to be preserved.
=> Fixes missing destroyed submodels from the polymodel_instance rendering commit.

code/ai/aiturret.cpp, code/model/model.h, code/ship/ship.cpp, code/weapon/beam.cpp
This adds the "share fire direction" subsystem flag. Normally, each firing point on a turret will target a different spot  on a ship (unless they're firing at a subsystem or given firing coordinates), this flag prevents that from occurring, forcing a firing direction instead of a firing at a point.
<a href="http://imgur.com/AJvsJcz"><img src="http://i.imgur.com/AJvsJcz.png" title="source: imgur.com" /></a>
=> Share fire direction turret flag

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/graphics/gropengltexture.cpp
This should speed up load times by about half when scanning a model for transparent triangles. Not quite back to original load times, but it's a start.
=> Changed bitmap_lookup to use ubyte instead of floats.

code/ship/ship.cpp
This makes them behave more like ship flags and should bring them around towards how modders intuitively expect using a modular table to override a ship's allowed weapons to work.
Fixes [Mantis 3176](http://scp.indiegames.us/mantis/view.php?id=3176).
ALTERNATIVELY: If others aren't as convinced as I am that this behavior is the intuitive expectation, or somebody points towards released mods that would break, the logic can be reversed and `+noreplace` replaced with `+override` (like weapons.tbl uses for flags) instead.
=> Modular tables now clear allowed weapons if +noreplace isn't specified.

code/ai/aicode.cpp, code/fred2/fred.rc, code/fred2/missionsave.cpp, code/fred2/resource.h, code/fred2/shipflagsdlg.cpp, code/fred2/shipflagsdlg.h, code/mission/missionparse.cpp, code/mission/missionparse.h, code/ship/ship.cpp, code/ship/ship.h
Normally, ships whose weapons or engines subsystems are destroyed will self-destruct after 90 seconds if they are part of a wing (see ai_maybe_self_destruct).  This adds a ship flag to prevent that from happening.
=> add no-disabled-self-destruct ship flag

code/ai/aiturret.cpp
Coverity was complaining about what is arguably a bogus check at a particular point in `ship_get_global_turret_info()` so I moved it up to a more valid point and changed it to an assertion.
=> Fix for coverity 1343617

code/cmdline/cmdline.cpp
Given the number of unintended consequences that can result from use of this command-line flag, we should return to the pre- 137eb7e4d4cb0f9c153d15bbcce847347aa3d716 behavior of not including it in the exe_params[] array; anyone who knows what it does and why we don't advertise it can still use it for testing purposes, but it should prevent the typical user from turning it on without knowing exactly what can go wrong.
=> Stop exporting -no_fps_capping to the launcher.

code/globalincs/def_files.cpp, code/graphics/gropenglshader.cpp, code/graphics/gropengltnl.cpp
Fixes an issue with team glows still being displayed on certain texture formats that only have three color channels.
=> Only enable team glow colors if team color texture mask has an alpha channel.

code/ship/shield.cpp
Previously they'd always stop at 75% complete, and it's probably just
luck that it worked correctly for ````:v:````
(i.e. the change makes the calculation use the percent-complete ratio of the animation to determine the frame, not the elapsed runtime of the animation)
=> Allow shield hit animations to play to the end

ci/travis/before_script.sh
using `-march=native` causes some issues with the outdated GCC Travis CI is currently using. By using the generic architecture we can work around this issue.
=> Use generic architecture for Travis CI

code/hud/hudparse.cpp
This PR fixes a bug that prevents the new "Force Scaling Above" parameter from working properly under certain conditions. It also removes an erroneous plus sign that somehow found its way into #500.
(The first change mentioned here also addresses m!m's concern about `force_scaling_above_res` being changed from -1 to `INT_MAX` at one point in the code.)
=> Hud scale limit (part 2)

code/asteroid/asteroid.cpp, code/asteroid/asteroid.h, code/fred2/management.cpp, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/object/collideshipship.cpp, code/object/object.cpp, code/parse/lua.cpp, code/ship/ship.cpp, code/starfield/starfield.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
"Dumb rotation" is rotation of a submodel without having an associated subsystem.  The original implementation by Bobboau was quite hackish, involving a redundant traversal of the submodel hierarchy independent of all the rest of the submodel code.
This PR merges dumb-rotation into the rest of the code, so that neither the traversal nor the rotation calculations are duplicated.  It also introduces separate dumb-rotation data structures to hold the rotation information (which fills in for the absent subystems) so that the rotation doesn't have to be brute-forced each frame.  Finally, it uses Swifty's model_instance code so that it is not necessary to call ship_model_start and ship_model_stop whenever the game wants to interact with the submodels.
(Note that, since dumb-rotation doesn't …
=> Dumb rotation refactor

code/debris/debris.cpp, code/debris/debris.h, code/object/objcollide.cpp, code/ship/shiphit.cpp
Three problems related to recycled object slots:
- First (a5b705b), if piece of debris collided with a ship after its parent object got recycled and the slot used for something else, shiphit.cpp would still try to treat it as a ship instance and get the `debris_damage_type_idx` for that ship. If that instance number happened to be a valid ship, FSO would at least not crash; otherwise, out-of-bounds array access means undefined behavior. Could avoid with a signature check, but it seemed safer to just store the damage type on the debris itself.
- Second (37a98b8), objcollide.cpp would sometimes make checks on an weapon's parent without verifying that the parent was still occupying that object slot with a `parent_sig` check. Again, sometimes the instance number would be beyond `MAX_SHIPS` …
=> Fix object recycling errors

code/hud/hudlock.cpp, code/model/modelread.cpp
This fixes a bug where, when the skybox is changed after loading a new mission, it tries to delete its model instance which was already deleted in model_instance_free_all.  Setting the instance reference to -1 when the instance is freed fixes this.  (This is something that would typically be handled by the object_delete function, as it is for ship_delete, asteroid_delete, and weapon_delete, but there is no such equivalent for skyboxes.)
Since this is such a small PR, I decided to also include a stash where I restored a comment that was inadvertently deleted by Swifty's hud_lock variable scope fix PR.
=> one small bugfix, one small comment tweak

code/freespace2/freespace.cpp, code/io/timer.cpp, code/io/timer.h, code/menuui/credits.cpp
As noted by @MageKing17 in #522 there was another instance where `timestamp_inc` was used.
I realized that it would make more sense to pass milliseconds to `timestamp_inc` instead of the `fix` frametime in seconds so I changed the function to accept milliseconds and moved the code to convert fix to milliseconds into freespace.cpp.
=> Change timestamp integer handling again

code/globalincs/profiling.cpp, code/globalincs/systemvars.h, code/io/timer.cpp, code/io/timer.h
@MageKing17 discovered that the timer value can overflow because our code uses 32 bit integers while SDL supplied 64 bit integers.
=> Use the correct type for high resolution timers

code/asteroid/asteroid.cpp, code/model/model.h, code/model/modelread.cpp, code/model/modelrender.cpp, code/object/object.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/starfield/starfield.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
This is a renaming of the Dumb_rotation infrastructure, which is now called Intrinsic_rotation.  Intrinsic rotations are automatically applied to submodels without the need for an associated subsystem.  Dumb rotations are now a type of intrinsic rotation, and look_at rotations will be added in a future PR.  The same code will handle both; the only difference is in how the intrinsic rotation is calculated.  (In the case of dumb-rotation, it is calculated the same way as normal rotation; in the case of look-at, it will be calculated using submodel_look_at.)
This PR was created at @asarium's request in the comments on #530.
=> refactor of dumb_rotation to intrinsic_rotation

code/hud/hudparse.cpp
This fixes the bug described in http://www.hard-light.net/forums/index.php?topic=91498.0, which is caused by the check for negative values in $Force Scaling Above not happening in the correct part of the code.
=> $Scale Gauges fix

code/ai/aicode.cpp, code/ai/aiturret.cpp, code/asteroid/asteroid.cpp, code/camera/camera.cpp, code/debris/debris.cpp, code/model/model.h, code/model/modelcollide.cpp, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/model/modelrender.h, code/object/collideshipship.cpp, code/parse/lua.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/ship/shiphit.cpp
As @asarium commented in #530:
> An Assertion that checks if the model instance actually belongs to the model number could catch some programming errors here.
> 
> On seconds thought, `polymodel_instance` contains the model number of the referenced `polymodel` so the `model_num` parameter isn't needed at all.
=> modify function headers as suggested in PR #530

code/object/objcollide.cpp
Somewhat related to PR #528, this changes the branch that assumes constant velocity from checking for an absence of the `WIF_TURNS` flag to checking for the presence of the `PF_CONST_VEL` flag (because non-turning weapons can be given an acceleration time).
=> Don't assume non-turning weapons have a fixed velocity.

configure.ac
If a function is only used in an `Assert` then the CI build will fail for release builds.
=> Disable unused function warnings in release mode

code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilearchive.h
Inspired by the APNG cfile issue discovered today where it would have been useful to know where the CFILE pointers were leaked. This will 
1. improve the error message when we run out of cfile blocks
2. Print a list consisting of file name and line number which opened a cfile when ending the program and when we run out of cfile blocks.
Possible future expansion: A debug console command that shows which files are currently opened
=> Add source tracking for cfiles

code/fred2/fredstubs.cpp, code/freespace2/freespace.cpp, code/freespace2/freespace.h
Simplify the random number seeding; don't store the RNG seeds in variables since they aren't used elsewhere; don't seed the RNG for every mission in single player.  This bypasses a design weakness in the Visual Studio RNG implementation of rand and srand which causes the same sequence of random numbers to be repeatedly generated.
See this thread on HLP for background:
http://www.hard-light.net/forums/index.php?topic=91576.0
=> improve RNG seeding

projects/MSVC_2015/Fred2.vcxproj, projects/MSVC_2015/Freespace2.vcxproj, projects/MSVC_2015/code.vcxproj, projects/MSVC_2015/libjpeg.vcxproj, projects/MSVC_2015/liblua.vcxproj, projects/MSVC_2015/libpng.vcxproj, projects/MSVC_2015/zlib.vcxproj
Ref: https://randomascii.wordpress.com/2011/07/22/visual-c-debug-buildsfast-checks-cause-5x-slowdowns/
See http://www.hard-light.net/forums/index.php?topic=91557 for testing results
=> Set Basic Runtime Checks to Default

code/missionui/missionscreencommon.cpp
Instead of using the clipping plane, simply don't draw the grid below the scanline. Fixes issue #347.
=> Fix mission screen grid by changing the drawing of the lines.

code/missionui/missionscreencommon.cpp
Instead of using the clipping plane, simply don't draw the grid below the scanline. Fixes issue #347.
Backport of PR #556 to the 3.7.4 branch.
=> [3.7.4] Fix mission screen grid by changing the drawing of the lines.

code/model/modelread.cpp
This is a small change in the code, but it fixes a significant bug.
The rotation turn rate for regular rotating submodels, specified using the $rotate property in the POF, is calculated using the time, in seconds, to complete one rotation.  Unfortunately,  the $dumb_rotate property was originally coded to use the property as the actual turn rate.  Thus, a subsystem that takes 5 seconds to complete one rotation would be interpreted at rotating at 5 radians per second if converted to use dumb_rotate.  (This is about .8 rotations/second rather than .2 rotations/second.)
This led to strange mismatches in the turn rate, but this was probably not examined closely due to all the other problems with $dumb_rotate and $look_at.  Now that the $dumb_rotation refactor has been completed and will be in …
=> fix the $dumb_rotate turn rate calculation to align with regular $rotate

code/menuui/techmenu.cpp
This PR fixes a bug in the ship database where the ship is placed at the wrong location if all of the following are true:
- Shadows are enabled
- The aspect ratio is not 4:3
- The -stretch_menu flag isn't enabled
=> Fixed ship position in ship database

code/model/modelread.cpp
Avoids the assertions at model/modelread.cpp:3062
ASSERTION FAILED: "Polygon_models[num]->id == model_num" (etc)
=> Cleanup weapon_info when models are unloaded

code/model/modelread.cpp
Avoids the assertions at model/modelread.cpp:3062
ASSERTION FAILED: "Polygon_models[num]->id == model_num" (etc)
=> [3.7.4] Cleanup weapon_info when models are unloaded

code/controlconfig/controlsconfigcommon.cpp
Found by address sanitiser
My mistake from commit 253d8a7e >.>
````
=================================================================
==5464== ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x606000008080
#0 0x7f6c7fe2d9da in operator delete(void*) ??:?
#1 0x54c851 in control_config_common_close() /home/mememe/src/fs2open.github.com.niffiwan/code/controlconfig/controlsconfigcommon.cpp:620 (discriminator 3)
#2 0x423207 in game_shutdown() /home/mememe/src/fs2open.github.com.niffiwan/code/freespace2/freespace.cpp:7337
#3 0x422b0d in game_main(char*) /home/mememe/src/fs2open.github.com.niffiwan/code/freespace2/freespace.cpp:7080
#4 0x422f52 in main /home/mememe/src/fs2open.github.com.niffiwan/code/freespace2/freespace.cpp:7209
#5 0x7f6c7d24cec4 in …
```
=> Fix new[] vs delete mismatch

code/ai/aiturret.cpp, code/ship/ship.cpp
Essentially, what was happening was that the firing direction was getting unrotated with the shooter's orientation matrix in the model_instance_find_world_dir despite already being correctly oriented.
Additionally, the share fire direction flag is essentially useless without salvo mode as you don't get the visual effect so a check was added to automatically warn the modder/user and set the flag.
=> Remove redundant function and add check to add "salvo mode" if "share fire direction" is found

code/model/modelanim.cpp
Triggered animations (e.g. models with rotating afterburner flaps)
could trigger a memcpy on overlapping memory. This may not have caused
issues, but is undefined behaviour according to the spec
Also see #574
=> Fix issue with memcpy on overlapping memory

code/model/modelanim.cpp
Triggered animations (e.g. models with rotating afterburner flaps)
could trigger a memcpy on overlapping memory. This may not have caused
issues, but is undefined behaviour according to the spec
Also see #574
=> [3.7.4] Fix issue with memcpy on overlapping memory

code/menuui/barracks.cpp
This fixes a bug where pressing the tab key (as opposed to clicking the single and multi buttons) on the barracks screen doesn't really switch between single player and multiplayer, even though the screen appears to reflect the change.
=> Fix for tab key on barracks screen

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/osapi/osregistry.cpp
The new registry handling also breaks the settings for some people so I added a commandline option which selects which path is used.
This issue should be added to the "Known issues" section of the release post so users know how to fix this issue.
=> Make new registry configurable on commandline

code/controlconfig/controlsconfig.cpp
There was a bug in the controls code that meant trigger type controls
bound to a joystick hat could be triggered by unrelated mouse button
presses. i.e. bind "hat-back" to cycle secondary weapons and secondary
banks would change when you fired with left mouse button.
Root cause is left bitshifting by 32 or more, which is implementation
defined and at least on Linux/GCC resulted in the above behaviour.
=> Stop joystick hat binds being triggered spuriously

code/controlconfig/controlsconfig.cpp
There was a bug in the controls code that meant trigger type controls
bound to a joystick hat could be triggered by unrelated mouse button
presses. i.e. bind "hat-back" to cycle secondary weapons and secondary
banks would change when you fired with left mouse button.
Root cause is left bitshifting by 32 or more, which is implementation
defined and at least on Linux/GCC resulted in the above behaviour.
=> [3.7.4] Stop joystick hat binds being triggered spuriously

code/ship/ship.cpp
Otherwise, the `first_time` code never gets evaluated for template-based ships and you never get engine glows from species. Fixes issue #594.
=> Make ship templates default first_time to true, like ship classes.

code/ship/ship.cpp
Otherwise, the first_time code never gets evaluated for template-based ships and you never get engine glows from species. Fixes issue #594.
Backport of PR #596.
=> [3.7.4] Make ship templates default first_time to true, like ship classes.

code/asteroid/asteroid.cpp, code/camera/camera.cpp, code/globalincs/pstypes.h, code/graphics/gropengldraw.cpp, code/graphics/gropenglpostprocessing.cpp, code/graphics/shadows.cpp, code/hud/hudlock.cpp, code/hud/hudtarget.cpp, code/lab/lab.cpp, code/math/vecmat.cpp, code/mission/missionparse.cpp, code/model/modelinterp.cpp, code/model/modelread.cpp, code/network/multimsgs.cpp, code/parse/sexp.cpp, code/radar/radar.cpp, code/radar/radarorb.cpp, code/render/3ddraw.cpp, code/render/3dlaser.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/starfield/nebula.cpp, code/weapon/beam.cpp, code/weapon/swarm.cpp, code/weapon/weapons.cpp
These proposed changes are based on observations in the executable built for Ubuntu 15.04 using the GCC 5.2 compiler. Although I have not checked this against other compilers, I don't expect these proposed changes to have a negative impact with them.
When invoking the standard trig functions (sin, cos, tan, asin, acos, and atan), unless the single precision form (sinf, cosf, tanf, asinf, acosf, atanf) were explicitly used, the compiler would generate code to convert the parameter to a double precision float (using cvtss2sd), call the slower double precision version of the trig function and then convert the result back from double precision back to single precision (using cvtsd2ss).  This seemed like unnecessary overhead.
In the third patch (hud: Simplify HudGaugeLock ....), I happened to …
=> Minor trig cleanup

code/fred2/missionsave.cpp
Removed support for //-style comments from CFred_mission_save::parse_comments(). Added some minor clarifications.
=> Removed support for // comments in FRED

projects/MSVC_2013/code.vcxproj, projects/MSVC_2015/code.vcxproj
Recent update to VS 2015 Community Edition appears to have removed gc.exe for some reason; the safest thing to do would seem to be to go back to using the copy of it we were already keeping around for VS 2010 Express.
=> Make VS 2013 and 2015 use the copy of gc.exe like 2010 does.

projects/MSVC_2013/code.vcxproj, projects/MSVC_2015/code.vcxproj
Recent update to VS 2015 Community Edition appears to have removed gc.exe for some reason; the safest thing to do would seem to be to go back to using the copy of it we were already keeping around for VS 2010 Express.
Backport of PR #600.
=> [3.7.4] Make VS 2013 and 2015 use the copy of gc.exe like 2010 does.

code/ai/aicode.cpp
OBJ_RECALC_PAIRS unsets then sets the OF_COLLIDES flag, so when a ship
with "no collide" set on it warps out, the flag is essentially ignored
and the ship can collide during the warp sequence.
=> Prevent "no collide" objects from colliding during warp sequence

code/mission/missionmessage.cpp, code/mission/missionmessage.h
This fixes the regression that caused _all_ messages.tbl animation names to have a letter suffix appended, even if the base name referred to a valid animation file.
For more details, see this post: http://www.hard-light.net/forums/index.php?topic=91986.0
=> Fix for automatic message suffixes

code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/ship/ship.h
Allows the players ship to have a minimum speed set. If the ships speed
drops below this (per ship) value, the throttle is increased to the
minimum.
For ships that are gliding, their engines will be reactivated when the
ships overall velocity falls below the minimum speed.
Currently only sets a minimum Z speed, Y & X are ignored.
See #604
=> Add player minimum speed feature

code/mission/missionmessage.cpp, code/mission/missionmessage.h
This fixes the regression that caused _all_ messages.tbl animation names to have a letter suffix appended, even if the base name referred to a valid animation file.
For more details, see this post: http://www.hard-light.net/forums/index.php?topic=91986.0
=> [3.7.4] Fix for automatic message suffixes

code/ship/ship.cpp
Moves the `sip->draw_primary_models[bank_to_fire]` check so that it only contains the code related to `shipp->primary_rotate_ang[bank_to_fire]`, since that really does only matter if external models are present. The rest of the spinup code doesn't actually care about the model, though, so it seems odd (and unfair to modders) to not allow it to function just because the ship has external primary models disabled.
I also wrapped the spinup code in a basic check that `winfo_p->weapon_submodel_rotate_vel` is greater than zero because most weapons aren't going to have a spinup, so there's no need to perform the other calculations for them (it's probably a marginal savings at best, but since I was getting rid of the best-case savings of most ships not having external primary models enabled, I …
=> Move conditional so that weapon spinup happens without external models.

code/menuui/techmenu.cpp
This PR fixes a bug in the ship database where the ship is placed at the wrong location if all of the following are true:
- Shadows are enabled
- The aspect ratio is not 4:3
- The -stretch_menu flag isn't enabled
=> [3.7.4] Fixed ship position in ship database

code/cmdline/cmdline.cpp, code/inetfile/chttpget.cpp, code/mission/missionparse.cpp
GCC 6 warns about misleading indentation because it counts tabs as 8
spaces. The rest of the code uses tabs, these lines use 4 spaces.
Replace spaces with tabs.
Whitespace changes only.
=> Fix indentation warnings

configure.ac
Build was failing at least on Arch Linux, which installs Lua 5.1 pkg-config file as lua51.pc.
Changed formatting slightly, but that can be undone if you don't like it.
=> accept lua51 as pkg-config name for Lua

code/math/floating.h, code/network/multi_ping.cpp, code/network/multi_ping.h, code/network/multimsgs.cpp, code/network/multiui.cpp
Fix calculations of server ping in in-game server list. Minimize floating
point calculations, using double instead of float, avoid calling timer
twice when receiving pong, and capture pong time more precisely.
Note that fix is just a typedef for long. It is the return type of timer_get_fixed_seconds().
=> Fix ping calculations in server list.

code/mission/missionparse.cpp, code/parse/parselo.cpp
The warning in the parsing code has been replaced with a log message so if a file name is missing there will be some indication that something is probably wrong.
This also adds validation for the fiction viewer filename to make sure that a non-empty file name is specified in the mission.
=> Fix for #625

code/mission/missionparse.cpp, code/parse/parselo.cpp
The error in the parsing code has been replaced with a warning message so if a file name is missing there will be some indication that something is probably wrong.
This also adds validation for the fiction viewer filename to make sure that a non-empty file name is specified in the mission.
Backport of #629.
=> [3.7.4] Fix for #625

code/cutscene/movie.cpp, code/freespace2/freespace.cpp, code/io/cursor.cpp, code/io/cursor.h, code/missionui/missionpause.cpp, code/parse/lua.cpp, code/popup/popup.cpp, code/popup/popupdead.cpp
The `CursorManager` has a few issues because the transition from drawing the cursor ourself to letting it be drawn by the OS introduced some inconsistencies.
These changes should improve that behavior by no longer setting the cursor state every frame and instead doing that only when in the relevant code. This should also fix #436 which was broken before because the mouse state the script sets was overwritten immediately.
This also introduces a means to save a stack of mouse states. This can be used if some user interface requires mouse interaction but the previous state is not clear.
=> Improve CursorManager

code/Makefile.am
I'm quite sure that this is correct, but I'd still be reassured if some Linux users check that it doesn't break their build.
https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html
VPATH builds were broken because mongoose.h was not found.
Makefile.am stated that it should be found in ../mongoose, which is
incorrect for VPATH builds. The search path should be relative to the
source tree ( i.e. $(VPATH) ).
Example:
mkdir -p build/debug
cd build/debug
../../autogen.sh
../../configure --enable-debug
make
The search path would then be (relative to the source tree)
build/mongoose, not ./mongoose as it should.
Fix this by changing ../mongoose to ./$(VPATH)/../mongoose.
In the previous example, $(VPATH) is ../../../code, so the search path
is now correctly …
=> fix VPATH builds

code/Makefile.am
https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html
VPATH builds were broken because mongoose.h was not found.
Makefile.am stated that it should be found in ../mongoose, which is
incorrect for VPATH builds. The search path should be relative to the
source tree ( i.e. $(VPATH) ).
Example:
mkdir -p build/debug
cd build/debug
../../autogen.sh
../../configure --enable-debug
make
The search path would then be (relative to the source tree)
build/mongoose, not ./mongoose as it should.
Fix this by changing ../mongoose to ./($VPATH)/../mongoose.
In the previous example, $(VPATH) is ../../../code, so the search path
is now correctly ./../../../code/../mongoose.
For in-tree builds, the path was previously ../mongoose. It is now
.//../mongoose, which is equivalent.
Backport of …
=> [3.7.4] Fix VPATH builds

code/io/mouse.cpp, code/io/mouse.h, code/osapi/osapi.cpp
There was code for flipping the scroll values if the directions was reversed but that code was for a future version of SDL. That version has since been released but the code apparently was never really tested. I fixed the error while keeping the functionality intact.
Sorry about removing all the whitespace at the end of some lines. For some reason Atom thinks it's a good idea to enable that by default...
=> Fix compilation with SDL 2.0.4

code/globalincs/alphacolors.cpp, code/globalincs/alphacolors.h
Inserts "Orange" between "Bright Yellow" and "UI Light Green" and adds the default color tag "$o" to use it. (Prerequisite for using orange as a ping display color.)
Also added some comments to identify the RGB values by the corresponding color name, because as it turns out, they're awfully hard to read as-is.
This is intended to prepare the ground for a followup to PR #609, discussed [here](http://www.hard-light.net/forums/index.php?topic=89758.msg1820558#msg1820558). I guess this PR can stand by itself if somebody *really* wants to use the color orange in their briefings without having to define a custom color table...
=> Adds Color_orange and a corresponding color tag to colors.tbl.

code/globalincs/alphacolors.cpp
Accidentally forgot one array in PR #633, causing a crash if a color table is actually present.
Really should refactor this code again to get rid of this redundant array.
=> Fix color table parsing.

code/globalincs/pstypes.h, code/ship/ship.cpp
This was a bit of a doozy.
If the player's current target changes ship class with `change_ship_type()`, `Player_ai->targeted_subsys` will still be pointing to the old subsystem list; this could cause problems (specifically out-of-bounds array accesses) when trying to e.g. look up nonexistant submodels. Similar problems occur with any other AIs targeting a subsystem on the ship in question. In order to fix this, several changes were made.
Firstly, `change_ship_type()` will now go through every `Ai_info[]` object looking for ones targeting a subsystem of the ship changing classes, or with an `AI_GOAL_DESTROY_SUBSYSTEM` goal for the ship changing classes, and convert them all to the new subsystem (if there's a match) or remove the target/goal (if there isn't), reusing the existing subsystem …
=> Fix several problems with change_ship_type()

ci/travis/install.sh, ci/travis/script.sh
xcpretty does not show all errors so for some cases we still need the full build log. These changes will upload that build to pastebin if the build fails.
=> Upload the MacOSX build log to pastebin if the build fails

code/graphics/gropenglshader.cpp
OpenGL 2.1 spec doesn't support texture LOD lookups in the fragment shader unless we use GL_ARB_shader_texture_lod. Should allow PBR to work on Mac now.
=> Fix for the PBR shader compilation error on Mac

code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/gropengl.cpp, code/graphics/grstub.cpp
`gf_set_palette` was a no-op for all graphics APIs so I just removed it.
=> Remove unused graphics functions

code/graphics/generic.cpp, code/graphics/generic.h, code/mission/missionmessage.cpp, code/parse/lua.cpp, code/pngutils/pngutils.cpp, code/pngutils/pngutils.h
Main use case is headanis where only one is played at a time and
caching the frames merely increases memory use & fragmentation, leading
to malloc errors with heavy apng use
=> Allow apng's to not be cached

code/render/3dsetup.cpp
In this case, the original line "if (!Cmdline_nohtl || (s <= 0.0f))" was replaced by "if (s <= 0.0f)", which unfortunately is not the intended behaviour here.
=> Fixes a small issue in the nohtl removal commit. 

code/fireball/warpineffect.cpp, code/graphics/gropengldraw.cpp, code/model/modelrender.cpp
Adds TMAP_FLAG_EMISSIVE for the 2D warp effect, and ups the scaling applied to textures with that flag from 1.5 to 2.0 to better approximate the brightness beams used to have.
Also sets a glow texture for the 3D warp effect.
=> Make beams and warps bright again

code/globalincs/def_files.cpp
Colors blended into monochrome textures kind of looked dull when rendered in HDR. This was due to the state colors and vertex colors not being gamma corrected, thus being mangled in the tonemap pass. This should make lasers and other color blended effects look less dull when rendered in the HDR pass.
=> Fix gamma correction for colors sourced outside of textures

code/freespace2/freespace.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h
This should fix the "Application unresponsive" errors.
This is a resubmit of #510.
=> Ignore all OS events when loading a mission

code/osapi/osapi.cpp
This allows FSO to exit gracefully when receiving a SIGINT or SIGTERM
=> Quit game when receiving SDL_QUIT event

projects/Eclipse/Freespace2/.project, projects/MSVC_2010/code.vcxproj, projects/MSVC_2013/code.vcxproj, projects/MSVC_2015/code.vcxproj, projects/codeblocks/code/code.cbp
Removes references to monopub.h (removed in the AP merge) from the project files that still reference it
=> Bad reference removal

code/io/key.cpp, code/io/mouse.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h
SDL2 support multiple windows and differentiates the events for the
individual windows using the windowID field in the events. These changes
check if that window ID belongs to our main window and ignores any
events that don't belong to it. This allows to add another window
without screwing up the rest of FSO with its input.
=> Only process events that belong to the main window

code/graphics/gropengldraw.cpp
This check shouldn't have been in opengl_aabitmap_ex_internal in the first place but I thought it was needed to fix an earlier bug Axem reported. It looks like it ended up causing https://github.com/scp-fs2open/fs2open.github.com/issues/650.
=> Remove alpha channel check in opengl_aabitmap_ex_internal 

code/io/joy-sdl.cpp
The axis handler already checked if the right joystick was used but the
button and hat handlers didn't.
=> Only process events from the right joystick

code/io/joy_ff-sdl.cpp
So, this makes force feedback work. It's not an ideal solution (uses the first haptic device SDL sees rather than matching the currently-selected joystick), but it's better than not working at all, which is where we are until [SDL fixes this bug](https://bugzilla.libsdl.org/show_bug.cgi?id=3021). As @asarium noted on IRC, "I doubt many people have more than one haptic device so for most people it should work fine." For more detail, see the description for commit 19b5ee9 (and the previously-linked SDL bug).
The other commit fixes the docking effect, which I noticed was malformed while I was working on the other issue. With both of these commits, the force feedback code no longer generates any errors in my debug log, and I get force feedback in-game.
=> Fix a couple force feedback issues.

appveyor.yml
FSO hasn't been on 3.7.3 for a while, now.
=> Get rid of AppVeyor version number.

.gitignore
These are created by VS 2015 (as of update 2) and should be ignored like other local Visual Studio files. `*.VC.db` is a new format for the IntelliSense database (replacing `*.sdf` used by previous versions), and `*.VC.VC.opendb` is a lockfile indicating the database is in use.
=> Add *.VC.db and *.VC.VC.opendb to .gitignore file.

ci/travis/before_script.sh, code/bmpman/bm_internal.h, code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/globalincs/alphacolors.cpp, code/globalincs/mspdb_callstack.cpp, code/globalincs/profiling.cpp, code/globalincs/systemvars.h, code/graphics/2d.h, code/graphics/generic.cpp, code/graphics/gropenglbmpman.cpp, code/graphics/gropenglbmpman.h, code/graphics/gropengltexture.cpp, code/graphics/gropengltexture.h, code/graphics/grstub.cpp, code/hud/hud.cpp, code/jpgutils/jpgutils.cpp, code/lab/wmcgui.cpp, code/math/fvi.cpp, code/math/vecmat.cpp, code/osapi/osregistry.cpp, code/parse/parselo.cpp, code/pngutils/pngutils.cpp, code/pngutils/pngutils.h, code/sound/speech.cpp, code/sound/voicerec.cpp
The only major change is that all bpp variables in bmpman have been converted into ints. Before it was a mix of ubyte and int.
=> Fix Visual Studio warnings

code/ship/ship.cpp
If a modular ship table modifies a ship entry without specifying a `$Countermeasure type:` entry, and the species has a `$Countermeasure type:` entry, FSO would reset the ship's countermeasure type to match the species default, even if we weren't defining the class for the first time. This just adds a `first_time` check to the else branch to avoid that.
=> Make modular ship tables not reset to species countermeasures.

code/graphics/gropengl.cpp
The first sign of a problem creating the OpenGL context for FRED should not be failing an assertion when trying to call `sscanf()` on the OpenGL version. I added a check that will report an error much sooner (as soon as `SDL_GL_CreateContext()` fails), threw some OpenGL error-checking around the `glGetString(GL_VERSION)` call to be on the safe side, and slapped an `Assertion()` in there for good measure.
Also there was a `\n` missing from the `mprintf()` call if window creation failed.
These changes were made during the process of investigating #674.
=> Add some error checking to gropenl.cpp.

code/ship/ship.cpp
"If a or b else a" should never ever execute the "else a" branch; this appears to be an artifact left over from Wanderer's reorganization of the autoaim/convergence code in 7bb10d8, before which standard convergence and automatic convergence were handled in separate conditionals.
=> Remove redundant code branch in gun convergence code.

code/ship/ship.cpp
Originally, "share fire dir" forced the "salvo mode" flag. This
interfered with the "use multiple guns" flag. In order to avoid this, I
instead made "share fire dir" get unset if either "salvo mode" or "use multiple
guns" is not found, as those are the only two flags that, coupled with
"share fire dir", give the desired results.
=> Avoid setting flags when using the share fire direction flag

code/debris/debris.cpp, code/object/collideshipweapon.cpp, code/object/collideweaponweapon.cpp, code/parse/lua.cpp, code/stats/scoring.cpp, code/stats/scoring.h, code/weapon/weapon.h, code/weapon/weapons.cpp
These commits attempt to reduce the memory footprint of projectiles. The first changes `collisionInfo` from an `mc_info` object to a pointer to one. The second does some simplification of the code handling weapon/weapon collisions. The third simplifies weapon scoring and gets rid of scoring data from the `weapon` struct.
=> Various cleanup related to weapon objects.

code/model/modelread.cpp
bsp_info.outline_buffer was allocated but not freed when unloading the
model.
=> Fix memory leak in modelinterp.cpp

code/cfile/cfilesystem.cpp
The launcher passes the mod folders as relative paths using `/` as the
directory separator. That path is copied into the `cf_root` path and when
`cf_create_directory` tries to create the directory, `mkdir_recursive` can't
handle the `/` in the path and tries to create two path elements at once
which is not supported by `mkdir`.
These changes fix that by converting mod paths to the native format
(from the / format, so it's a No-op on Unix) before using it in
`cf_create_root()`.
=> Fix directory creation for nested mod folders.

code/graphics/gropenglpostprocessing.cpp
The FXAA documentation at http://developer.download.nvidia.com/assets/gamedev/files/sdk/11/FXAA_WhitePaper.pdf recommends that it be run after tonemapping; this is something we should do too.
=> Moves the FXAA pass to after the tonemapping step

fred2/fred.cpp
This allows to run the executable in a different directory. This is very
useful for debugging from within Visual Studio.
=> Use the current working directory for FRED

code/parse/lua.cpp
This fixes a bug reported by @The-E where there would be weird issues when using the message box script by @AxemP.
=> Fix off-by-one error in Lua font API

code/parse/lua.cpp
Adds the 'attacks' function to the 'team' lua type, which exposes the iff_x_attacks_y function to the lua engine.
=> Expose IFF to lua

code/inetfile/cftp.cpp
It looks like this was added to trunk (a0f31e6), synced with antipodes (4952b70), and then one of the antipodes merges (7e77b5a) wound up combining both additions.
=> Remove duplicate fclose() call (fix Coverity defect 1360951)

code/bmpman/bmpman.cpp
The Assertion which was triggered was carried over from the OpenGL code
but the stub code was using pretty much the same code so removing the
Assertion seems like the correct way to solve this.
Fix for issue #726.
=> Fix Assertion when running in standalone mode

code/fs2netd/tcp_client.cpp
"Unchecked return value from library". The function can't return an
error value so I added a ml_printf (which is used at another place for
error logging as well) to log the error.
=> Fix for Coverity 1093292

code/graphics/gropengl.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, fred2/fredview.cpp, fred2/management.cpp, fred2/management.h
The documentation says that the SDL OpenGL attributes need to be
initialized before a window is created. These changes implement that by
moving the actual SD_Window creation inside the OpenGL setup. FRED only
sets the native window handle to the correct HWND and gropengl uses
that.
=> Make sure that SDL OpenGL is initialized

code/network/multiui.cpp
The function returned the wrong value for same string which caused the
MSVC debug runtime to throw an error. This fixes that.
=> Fix sorting function multi_create_sort_func

code/hud/hudparse.cpp
Thanks to @AxemP for providing a test mod to fix this issue.
This shows that the hud parse code is flawed because instead of showing an error it skipped the invalid entry and continued with the next. I'll try to improve that a bit in a separate PR.
=> Fix parsing code error introduced by TTF merge

code/parse/lua.cpp
If a required argument is invalid, `ade_get_args()` returns 0, but it wasn't making sure `va_end(vl)` got called first, leading to potential memory corruption (probably not a huge issue in actual usage because most people try not to release scripts that throw errors).
=> Make sure va_end() gets called in ade_get_args() (fix Coverity 1360950)

code/graphics/gropengl.cpp, code/graphics/gropengl.h, code/graphics/gropengldraw.cpp
glLineWidth is no longer an effective way of setting the line width of
2D operations.
=> Fix for #765

code/graphics/gropengl.cpp
GLAD already parses the OpenGL version so that information can be used for our version check.
This is related to #753 but I don't think it will fix it.
=> Use the OpenGL version provided by GLAD

code/globalincs/memory/memory.cpp
Apparently MSVC 2013 allocates memory when locking a mutex which calls
our allocation hook when the tries to call our memory tracking function
which leads to a deadlock. Since there is no way of providing a memory
allocation function for std::mutex the best solution is to simply
disable the lock_guard for everything before MSVC 2015. That will
probably corrupt the memory tracking values at some point but it's
better than not being able to run FSO at all.
This fixes #768.
=> Fix for #768

code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/gropengl.cpp, code/graphics/gropengl.h, code/model/modelread.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, fred2/fredview.cpp, fred2/management.cpp, fred2/management.h, freespace2/CMakeLists.txt, freespace2/SDLGraphicsOperations.cpp, freespace2/SDLGraphicsOperations.h, freespace2/freespace.cpp
This allows to use a different method of creating and managing the
OpenGL context. This is needed by wxFRED where the OpenGL context is
created by wxWidgets. This will probably also fix #753 since it uses the
old wgl based method of creating an OpenGL context in FRED.
There are still a few SDL calls in gropengl.cpp but those are related to windowing instead of OpenGL. I'll fix that in another PR.
=> Add interface for creating an OpenGL context

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/osapi/dialogs.cpp
If the -noninteractive command line option is set then dialogs won't be
shown and the default action is taken. This should be useful for
the standalone server.
=> Add noninteractive mode

code/graphics/software/FSFont.cpp, code/graphics/software/FSFont.h, code/graphics/software/font.cpp
This also fixes the usage of an uninitialized variable that was reported by valgrind.
=> Improve font top and bottom offset handling

code/io/joy-sdl.cpp
When the hat switch code was fixed to restrict joysticks to 32 buttons again, it forgot to invalidate buttons between `numButtons()` and 32. This could lead to some assertions being failed when the joystick got asked for the status of a nonexistent button.
Also, `joy_down()` was comparing the hat's current position (a value from the `HatPosition` enum) to a 0-based index (such as `joy_down_count()` uses to index the relevant array), which was making hat switches not work with continuous controls.
=> Fix a couple button-related joystick issues.

cmake/toolchain-msvc.cmake, code/graphics/2d.h, code/graphics/software/font.cpp, code/windows_stub/config.h
Also removes `_cdecl` since it's not needed anymore and not compatible with other compilers.
=> Clean up CMake MSVC warning handling

Readme.md
Re-add visual badges that provide overview of build and code quality status via Travis and Coverity.
These existing previously and appear to have been omitted in the CMake transition.
=> Add badges to Readme

code/io/joy-sdl.cpp, code/io/joy.h
* There's now registers for both 4 position and 8 position hats for both timestamps and downcounts
* There's conversion code to allow an 8-position hat to act like a 4-position hat, which is needed by the FSO codebase which only uses 4-pos hats
* There's also conversion code to allow a 4-pos hat to act like an 8-position hat to some degree, This is currently "omitted" by the second commit, so if anybody needs it in the future you can just revert the commit.
=> More compatibility code for joystick hats.

code/ai/aiturret.cpp, code/ship/ship.cpp, code/ship/ship.h
Target priorities could previous only select based on very few flags, for the simple reason that very few were defined in the `ai_tgt_*_flags[]` arrays. This simply adds additional flags (even some that seem a little silly; I can't actually think of a reason to especially target "objects that are being rendered", but hey, maybe somebody will find a use for it in the future).
=> Greatly expand available flags for creating target priority groups.

code/osapi/osapi.cpp
Without the new line, this important warning line can get lost within the console messages e.g. on Linux.
e.g. now properly formatted
```
$ ./fs2_open_3_7_5_x64-DEBUG -window
FSO is running in legacy config mode. Please either update your launcher or copy the configuration and pilot files to '/home/usera/.local/share/HardLightProductions/FreeSpaceOpen/' for better future compatibility.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```
=> Improve legacy mode warning console message

code/io/joy-sdl.cpp
Kobrar reported that joystick events were not properly assigned to the
right Joystick instances because the GUIDs of the joysticks was the same
(that's another problem since the code assumes that they actually are
Globally Unique like the name says).
The fix was to simply use the instance ID for checking if two sticks are
the same which seems to work more reliably.
=> Fix wrong joystick event assignment

code/globalincs/flagset.h, code/weapon/beam.cpp
This allows to initialize a flagset instance from a {...} expression
without having to create an intermediary instance.
=> Add initializer_list support for flagset

code/io/joy-sdl.cpp, code/io/joy.h
This is related to #813. The new code now also uses the device ID if there are multiple joysticks with the same GUID. That's better than it was before but the device ID is not guaranteed to stay the same if the joystick is plugged into a different port so if that happens the code may break.
=> Refine joystick selection

code/io/joy-sdl.cpp
First commit makes joysticks work again if commit 8f034b08d4cab39829783fd3fa6aa4dbe1786e03 broke it for you.
Second commit makes force feedback work again... again. Commit f91c681ee1c75f4c22f323062bcd9554400a8073 didn't include any calls to the haptic subsystem; I just put them back.
=> Fix a couple joystick issues.

code/graphics/gropengldraw.cpp
When I created Cmdline_fb_thrusters, I hid the initialization for the distortion framebuffer behind a check for that flag. This was wrong, as the same FB is used to render framebuffer explosion effects, so this change makes sure that when either of those flags is set, the distortion framebuffer is correctly initialized.
=> Fixes issue with framebuffer initialization

code/parse/sexp.cpp
When PR #831 got rid of a warning in `sexp_event_delay_status()`, it did so by getting rid of the 64-bit temporary variable (in order to get rid of a warning in the non-`use_msecs` branch). However, that 64-bit variable was protecting against overflow when using numbers of milliseconds `>= 65535`, which are used by e.g. the Icarus cutscene mission from Blue Planet, leading to interesting (but wrong) behavior.
This restores usage of the `uint64_t` temporary variable by reverting that specific change, but then avoids the warning by moving that temporary variable to be inside the `use_msecs` branch; I get no warnings when compiling this version of sexp.cpp, and Icarus works again.
=> Fix overflow problem accidentally introduced to is-event-*-msecs-delay.

code/headtracking/freetrack.cpp
If `value` is empty, then attempting to access `value[value.length() - 1]` is equivalent to trying to access `value[-1]`, which is an out-of-bounds access (causing debug builds to complain and undefined behavior).
=> Add a check for an empty string to the freetrack loading code.

code/weapon/weapons.cpp
Starting with git 127976c (#851), FSO fails to start, displaying an
error. This is my attempt to fix it. FSO starts, but I do not know how
to check that the flags are parsed correctly.
Fixes #853
=> Fix weapon flag parsing

code/windows_stub/stubs.cpp
_mkdir was horribly broken. It was creating all directories in the given
path but failed to create the actually wanted last portion.
On Windows, _mkdir only creates the last portion.
Fix this by simply calling mkdir, which does the Right Thing (TM).
Fixes #855. Creating directories now actually works.
=> Fix _mkdir on non-Windows

code/CMakeLists.txt, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/cutscene/cutscenes.h, code/globalincs/vmallocator.h, code/pilotfile/BinaryFileHandler.cpp, code/pilotfile/BinaryFileHandler.h, code/pilotfile/FileHandler.h, code/pilotfile/JSONFileHandler.cpp, code/pilotfile/JSONFileHandler.h, code/pilotfile/csg.cpp, code/pilotfile/pilotfile.cpp, code/pilotfile/pilotfile.h, code/pilotfile/plr.cpp, code/source_groups.cmake, lib/CMakeLists.txt, lib/jansson/CMakeLists.txt
This is a new implementation of the JSON dumping which was already
proposed in #22 but this version tries to allow implementing both
reading and writing JSON files without having to change the existing
code too much. This is done by using an abstract class to hide the
differences between writing the JSON and binary files.
This is currently only capable of writing the files but not reading them
so if the option is enabled all changes to the pilot file are lost. I
will implement reading after this PR has been merged since I would like
to reduce the amount of changes that need to be reviewed.
=> Add option for writing pilot files in JSON format

code/def_files/deferred-f.sdr
Fix the error below by using float constants instead of integers.
```
Compiling new shader:
Deferred Lighting
Loading built-in default shader for: deferred-v.sdr
Loading built-in default shader for: deferred-f.sdr
Fragment shader failed to compile:
0:33(72): error: could not implicitly convert operands to arithmetic operator
0:33(71): error: operands to arithmetic operators must be numeric
0:33(9): error: operands to arithmetic operators must be numeric
0:33(9): error: operands to arithmetic operators must be numeric
0:33(9): error: operands to arithmetic operators must be numeric
0:33(2): error: `return' with wrong type error, in function `SpecularBlinnPhong' returning vec3
ERROR! Unable to create fragment shader!
Failed to compile deferred lighting shader!
```
=> Fix deferred lighting shader compilation

code/ai/aicode.cpp, code/hud/hudtarget.cpp, code/io/keycontrol.cpp, code/missionui/missionweaponchoice.cpp, code/network/multi_ingame.cpp, code/parse/sexp.cpp, code/ship/ship.cpp
See also my comments on #762.  The flag is almost entirely redundant, so this PR removes it in all instances where it's used in the ballistic primaries code.  There are one or two places where removing it was not a no-op, so I adjusted the rest of the code accordingly (most notably in the parsing validation when it checks that primary weapon cargo has been assigned).  I also added a few divide-by-zero checks and slightly tweaked the support ship rearm code.  The use of the SIF_BALLISTIC_PRIMARIES flag in the ingame_join code was replaced with a dummy value to avoid bumping the multiplayer packet version number.
=> remove the SIF_BALLISTIC_PRIMARIES flag

CMakeLists.txt, cmake/toolchain-msvc.cmake, cmake/util.cmake, code/sound/acm.cpp
This speeds up MSVC builds a bit (up to 1 minute when building a full release configuration). Other platforms have issues with precompiled headers so it's disabled by default for them.
=> Enable cotire by default for Visual Studio

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/io/cursor.cpp
This disables all mouse grabbing which is useful for debugging when SDL gets interrupted without giving up control of the mouse. That usually leads to problems since you can't interact with the debugger window anymore.
=> Add -nograb commandline option

code/controlconfig/controlsconfig.cpp
Avoid potential uint overflow if joystick returns a range greater than
the maximum expected range. I guess this could also be fixed by
limiting raw to rng-1 (?)
=> Fix coverity 1361824

code/graphics/2d.cpp, code/graphics/gropengl.cpp, code/headtracking/trackir.cpp, code/io/key.cpp, code/io/mouse.cpp, code/osapi/dialogs.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, fred2/fredview.cpp, fred2/missionsave.cpp, freespace2/SDLGraphicsOperations.cpp, freespace2/SDLGraphicsOperations.h, freespace2/freespace.cpp
This separates OpenGL context creation from window creation and also allows to implement multiple viewports in the future. This is a continuation of the previous PR where I added the OpenGL context abstraction.
=> Add interface for viewport management

code/graphics/gropengl.cpp
Fixes #879.
@SamuelCho Could you check if this change fixes the crash you encountered?
=> Use the APIENTRY calling convention for the debug callback

code/headtracking/freetrack.cpp, code/playerman/playercontrol.cpp
Also adds code for detecting if the FreeTrack client is actually
reporting valid values. I only tested it with FaceTrackNoIR so it may
not work for other head trackers.
=> Fix issue with head tracking and freelook interaction

code/mission/missionparse.cpp
This fixes an Int3 in the ai code where it couldn't find a ship that was
destroyed before a mission. This was found through a mission bug in
FreeSpace Blue "Slaying Ravana" where the "Somtus" is marked as
destroyed before mission but then the AI is given orders which target
that ship.
=> Mark ship destroyed before a mission as exited

code/weapon/weapons.cpp
It was setting the `Pierce_shields` flag based on whether or not the `Beam` flag was set, rather than based on whether or not "beam" was explicitly provided; as such, a TBM entry for a non-piercing beam that contained a "$Flags:" entry but didn't re-set "no pierce shields" could spontaneously regain piercing status (explicitly setting "beam" again will re-add piercing, but this should match previous behavior).
=> Fix minor problem with the logic for parsing the beam flag.

code/parse/parselo.h, code/weapon/weapons.cpp
Putting an assertion in here was the wrong thing to do, as "no pierce shields" is very definitely "in use".
=> Fix for parsing the no pierce flag

code/windows_stub/config.h
The code was using the 32-bit types while being compiled under 64-bit
because a header was missing. I fixed this issue by using fixed width
integer types.
=> Fix WAV parsing on UNIX

code/starfield/starfield.cpp
The previous code generated a lot of OpenGL function calls because every
star was rendered using a separate NanoVG frame. This fixes that by
using the path renderer directly which removes most of the
inefficiencies.
Fixes #898.
=> Fix performance regression in star rendering code

code/model/modelrender.cpp, code/render/3d.h, code/render/3ddraw.cpp
Nipping this in the bud before someone submits an issue report. I'm sure some people noticed jumpnodes were rendering in red. This gets them back to normal.
=> Fixed jumpnode colors following OGL Core changes

code/osapi/outwnd.cpp, code/windows_stub/config.h
Opening the log file failed when the data path did not exists, e.g.
during the user's first run. Create it before trying to open the log
file.
Also, include `<direct.h>` in windows_stubs/config.h since the equivalent
stubs for Unix are also declared there.
=> Create data path for log file

code/pilotfile/BinaryFileHandler.cpp
startSectionWrite would push unnamed sections on _sectionOffsets, but
endSectionWrite was not removing them, leading to _sectionOffsets
containing tens of unnamed sections when parsing the HUD config.
Pop the unnamed sections in endSectionWrite.
This was causing interesting issues such as a crash when starting a mission because of an invalid radar range as well as all controls being unassigned.
=> Fix writing binary pilot files.

code/model/modelinterp.cpp, code/pilotfile/plr.cpp, code/radar/radarsetup.cpp
Add missing new line to BSP Parse timing.
Log value of HUD_config.rp_dist when it is not valid.
I'm hitting this one with rp_dist=-1, I'll try to debug it later.
=> Small imporvements to debug messages

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/globalincs/profiling.cpp, code/globalincs/systemvars.h, code/model/modelrender.cpp, code/object/objcollide.cpp, code/object/object.cpp, code/render/batching.cpp, freespace2/freespace.cpp
This output is compatible with the Chromium tracing viewer which
provides a very nice visual overview of what FSO does in a frame.
Here is an example of how it looks like: ![chrometracing](https://cloud.githubusercontent.com/assets/1013983/18053370/536d2b0a-6dff-11e6-996c-7560baad73e6.png)
The files are written to a directory called "tracing" where each frame is written into a separate file. Here is an example file that you can use directly in the trace viewer: [frame_354.txt](https://github.com/scp-fs2open/fs2open.github.com/files/442507/frame_354.txt) (You have to change the extension to json).
You can also view these files without Chromium since the [Trace-viewer](https://github.com/catapult-project/catapult/blob/master/tracing/README.md) can also be used as a standalone script.
=> Add support for outputting profiling data as JSON

code/menuui/techmenu.cpp
`tech_render_anim` did not check whether there were any intel/weapon
entries before trying to read from`Current_list`, which means that it
read at `Current_list[-1]`, which is a Bad Thing (TM).
Do not try to render an anim if there is no entry.
=> Fix crash/Error in techmenu with 0 intel entries.

fred2/fredview.cpp
This is not technically correct since the FRED code is not able to
create an OpenGL Core context but since FRED is Windows only it's not a
problem because those drivers usually support the Core profile features
in the Compatibility profile.
=> Fix OpenGL context creation for FRED

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/render/3ddraw.cpp
There seem to be a few graphics functions that aren't used anymore but still exist in the interface definition. This fixes the crash by removing the `gr_sphere_htl` call and also removes those unused functions.
=> Fix FRED crash when rendering waypoints

code/def_files/main-f.sdr, code/graphics/material.cpp
Following my conversation of wanting to keep targetbox lighting enabled by default but encountering some unusually salient pushback, I've decided to go another route to solve our black PBR model in targetbox issue. Unlit models, in addition to their constant diffuse, will have their specular color added with a view-dependant Fresnel factor that varies based off of their gloss. The result is a sort of rim effect that still goes well with the unlit aesthetic while conveying the view dependent nature of a specular map.
Here is a lit Zeus rendered with PBR textures:
And here it is using the unlit specular effect:
=> Better handling of specular maps when using unlit rendering

code/cmdline/cmdline.cpp
This was causing my (yet unpublished) tests to fail because the mod list
was just being appended to instead of being reset for each test.
It would be nice if there was a simple way to reset all global state. This is probably not the only state which is leaking between tests. Running each test in a new process would be ideal, but I don't know if that is (a) even possible and (b) fast enough.  A quick browse of the Google Test docs did not reveal any sensible way to do this.
=> Remove old cmdline parms before parsing new ones.

code/cutscene/mveplayer.cpp, code/cutscene/oggplayer.cpp, code/globalincs/profiling.cpp, code/io/timer.cpp, code/io/timer.h, code/menuui/credits.cpp, code/network/multi_obj.cpp, freespace2/freespace.cpp
Currently the timer system uses `SDL_GetTick()` for keeping track of frametimes but that uses millisecond precision. `timer_get_fixed_seconds` converts that into a `fix` (aka 1/65536 of a second) which means that ~6 bits of information are completely useless. These changes always use the high precision timer which allows to get timer values with microsecond precision and that allows to use the remaining 6 bits of information in the `fix`.
I wanted to fix the timer issues at high framerates with this but it doesn't seem like that has changed with these changes. I decided to submit this anyway because it should improve the frametime computation a bit.
=> Always use high resolution timers

code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengltnl.cpp
This was something I planned on doing before the OpenGL Core migration but I got sidetracked. The way materials decide what shader a draw call was left in an overly complicated state and wasn't very clear. I simplified it so that a material just needs an override of the get_shader_flags() if a shader type of a derived material class needs a flag for its particular case.
=> Refactored material handling of shaders

ci/travis/script.sh
@rtoijala mentioned this option and I thought it would be a good idea to use it when running the tests on the CI servers,
=> Shuffle the order in which unit tests are executed

code/def_files/effect-f.sdr, code/def_files/fxaa-f.sdr, code/def_files/ls-f.sdr, code/def_files/main-f.sdr, code/def_files/passthrough-f.sdr, code/def_files/shield-impact-f.sdr
texture2D has been deprecated for some time and Mac also doesn't support
it anymore. The 1.50 GLSL specification says that texture is the correct
function for texel lookup so I used that.
=> Replace texture2D with texture in shaders

code/parse/parselo.cpp, fred2/management.cpp
Fixes #933.
This also uses `size_t` for keeping track of he size of the memory.
=> Make sure that the parse strings are c strings

code/ai/aigoals.cpp, code/ai/aigoals.h, code/parse/sexp.cpp, code/ship/ship.cpp, fred2/management.cpp, fred2/shipgoalsdlg.cpp
A few things I noticed while working on ai-chase-ship-class, split out into a separate PR.  Some code is reordered, some is cleaned up; nothing too extensive.  The most notable changes are a) the modification of the Ai_goal_text function to work on the AI_GOAL_X #define directly rather than unnecessarily calculate the bit; b) changing the HUD text of "fly to ship" to "rendezvous with" plus the ship name; c) adding a Warning in ai_update_goal_references; and d) changing ship_name to target_name in ship_return_orders for clarity
=> minor tweaks and adjustments to AI goal code

code/CMakeLists.txt, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/opengl/gropenglshader.cpp, lib/CMakeLists.txt, lib/md5/CMakeLists.txt, lib/md5/md5.cpp, lib/md5/md5.h
This uses the program binary support included in OpenGL 4.1 to build a
cache of compiled shaders. It does this by computing the MD5 of the
source code of the shaders and using that hash to generate unique file names. That
should make sure that a change to a shader is automatically reflected in
the shader cache.
Currently the shader files are written to a mod specific directory. If that's a problem then I could try figuring out how to write them into the root directory but that would probably involve hacking the cfile system and I would like to avoid that.
Also, in my test runs I found that we use 167 (!!) shaders. It might be a good idea to somehow reduce that.
=> Add shader caching

code/parse/parselo.cpp, test/src/parse/test_parselo.cpp, test/test_data/parselo/data/tables/test.tbl, test/test_data/parselo/parse_pausing/data/tables/test2.tbl
As far as I can tell this issue has been present for a very long time,
maybe even since retail. It was only uncovered since the recent changes
initialized the mission text by default which corrupted the table text
that was currently being parsed.
This also adds a unit test that validated that pausing works correctly.
=> Don't initialize mission text when it's not used

code/menuui/mainhallmenu.cpp
cmission.main_hall defaults to an empty string, so calling main_hall_init() with an empty string is neither unsurprising nor uncommon. Since it's not actually caused by bad data, the warning can be considered actively harmful by training users that sometimes FSO just gives you a pointless warning.
=> Remove pointless main_hall_init() warning about an empty string.

code/ship/ship.cpp
`Ignore_List` (the list of flags used to determine if a ship is an invalid target) was originally a statically-initialized bitfield stored in an `int`; the new bitset flags code added a `set_default_ignore_list()` function to provide the default values, but then forgot to call it anywhere. As a result, "hidden-from-sensors" (and the other, less-likely-to-be-noticed flags) was having no effect on the player's ability to target anything. This adds a call to `set_default_ignore_list()` to `ship_init()` so that the original functionality is restored.
=> Actually initialize Ignore_List.

code/graphics/2d.cpp, code/io/cursor.cpp, freespace2/freespace.cpp
There are a few issues with cursors in standalone mode since we don't have video support there. These changes should take care of that and make sure that the standalone server works again.
@chief1983 Please test this to check if it resolves #941.
=> Fix cursor handling in standalone server

code/parse/sexp.cpp
This is another issue introduced by converting `f2i` to a function. The parameter in the current version gets truncated to a `fix` (aka `std::int32_t`) which is not enough to hold the values. The new version "fixes" that by moving the conversion into the SEXP code which is not a perfect solution.
An alternative would be to use a templated `f2i` function but that would reduce the type-safety of the function since then it could be used with any integer type without causing a warning.
=> Fix integer overflow in mission-time-msecs SEXP

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/material.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/menuui/credits.cpp
This fixes #914. I tested it and it seems to be working fine and it fixes the bitmap alpha blending.
There are a few additional changes that I made while searching for the cause of the bug which may be helpful for future debugging to I also included it here.
=> Always use alpha blending for interface materials

code/hud/hudmessage.cpp, code/hud/hudmessage.h, code/hud/hudparse.cpp
This fixes #865, which was caused by the gauge still using 0x8000 as its default X-position even after support for that magic number was removed.
This also adds the "Center Text On Gauge X-Position:" option for the Fixed Messages gauge, which defaults to false if a position is specified and true otherwise, matching previous behavior.
=> Fix for Fixed Messages gauge position

code/graphics/2d.cpp, code/graphics/generic.cpp, code/parse/lua.cpp
This now uses the same material properties that `gr_bitmap` already uses and fixes the alpha blending mode for interface materials.
=> Fix lua drawImage rendering

test/src/menuui/test_intel_parse.cpp, test/test_data/menuui/intel_parse/missing_end_multi_text/data/tables/species.tbl, test/test_data/menuui/intel_parse/wrong_order/data/tables/species.tbl
Since 16d5f88 and c9f9e1b there is no longer the danger of reading old data from `Mission_text`, so the test `missing_end_multi_text` can now be uncommented.
Also, add a unit test to check that intel entry data must be in the correct order for parsing to succeed.
=> Species tbl test improvements

code/def_files/main-f.sdr
This caused problems with the Mac GLSL compiler on my machine. Other compilers prob didn't catch this since it was unused and likely optimized out.
=> Remove unused varying envReflect from main fragment shader.

code/ai/aicode.cpp
This used to be a check against a copy of the flags field that was initialized to 0 when there was no enemy_sip, so we need to check if enemy_sip exists here
=> Fixes a little nuance that was missed during the ship flag conversion

code/globalincs/profiling.cpp, code/globalincs/systemvars.h, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropenglquery.cpp, code/graphics/opengl/gropenglquery.h, code/io/timer.cpp, code/io/timer.h, code/mission/missiongoals.cpp, code/model/modelrender.cpp, code/object/objcollide.cpp, code/object/object.cpp, code/object/objectsort.cpp, code/particle/particle.cpp, code/render/batching.cpp, code/source_groups.cmake, code/tracing/tracing.cpp, code/tracing/tracing.h, code/weapon/trails.cpp, freespace2/freespace.cpp
This adds support for profiling the time the GPU takes for executing a set of commands. The OpenGL renderer uses query objects with timestamp queries to implement this and those values are then written in the same format the CPU times are already being written. The chrome trace viewer always threw an error when I tried to combine the two data sets so I choose to write the two data sets to two different files which can be opened separately.
=> Add GPU time tracing to JSON output

code/graphics/opengl/gropengltnl.cpp
This was missed in the OpenGL core changes. The new code should behave
like the code in 3.7.4.
=> Readd team color glows

code/ship/ship.cpp
`previous_primary_bank` was only getting set if the ship had a ballistic weapon or if secondary banks were changed, so `previous_secondary_bank` wasn't getting set at all. I fixed the second problem my simply using the correct variables, and the first problem by consolidating the ballistic and non-ballistic code so that there was less code redundancy (without that redundancy, it's unlikely the mistake would've been made in the first place); I figured this was a better solution than just copying the code to set `previous_primary_bank` into the non-ballistic codepath.
=> Fix previous_primary_bank and previous_secondary_bank.

code/cutscene/player/OpenGLVideoPresenter.cpp
The FFmpeg merge removed the behavior of displaying videos only on the center monitor of multimonitor setups. This PR restores this behavior.
=> Display videos only on the center monitor

code/hud/hudmessage.cpp
Init center_text in ctor, safety/defensive measure only since is
currently correctly set via init function in all code paths
=> Fix Coverity 1363382

code/sound/ffmpeg/FFmpegAudioReader.cpp, code/sound/ffmpeg/FFmpegAudioReader.h, code/sound/ffmpeg/WaveFile.cpp, code/sound/ffmpeg/WaveFile.h
ADPCM playback was broken by #991 when an older FFmpeg version (< 3.1)
was used. The newer version has a better API for handling decoders that
return multiple frames of data per packet which I already used. However,
I didn't bother implementing that for the older API since I haven't seen
a decoder that actually returned multiple frames per packet but ADPCM is
such a decoder. This fixes that by implementing the correct behavior
with the old API.
=> Fix ADPCM playback with older FFmpeg versions

code/missionui/missionweaponchoice.cpp, code/ship/ship.cpp, code/ship/ship.h
Designed to work around issues with gunpoints on animated subsystems,
and those gunpoints being in the "triggered" position, and thus there's
lines pointing to empty space in the weapon loadout screen.
Use this to specify an alternate model that has the gunpoints in the
"correct" position.
(finally implemented alternate solution to #627)
=> Add alternate pof for use in techroom

code/sound/sound.cpp
@niffiwan discovered that some retail sounds trigger the newly
introduced so the warning needs to be suppressed for those few files.
See #1005 for the full discussion.
=> Suppress 3D sound warning for retail sounds

code/object/collideshipship.cpp, code/osapi/dialogs.cpp
I'm not entirely sure if this is the correct way to do the computation
but I see no other way of fixing it but since the zero vector is a valid
value for the relative velocity this seems to be the most sensible
solution.
Also, related to this I found out that FSO causes a lot of NaN errors at
runtime which may need to be investigated at some point to make sure
they don't cause issues like this bug.
=> Fix computation that causes NaN errors

code/sound/audiostr.cpp
This fixes an issue where the event music cuts off after ~ 3 seconds
because the fields tracking how much data has been read so far were not
reset. I also fixed the calculation of how much data may be read since
that was slightly broken by the new audio stream reading code.
=> Reset AudioStream data when beginning playback

code/ship/ship.cpp, code/weapon/weapons.cpp
Axem reported a few issues with $Substitute: relating to secondary dual fire and primary linking as well as thruster glows.
Made it so that substitution weapons get paged in alongside the base weapon.
Ensure dual/linked fire is in sequence.
=> Fixes for $Substitute

freespace2/freespace.cpp
This will make sure that an exception doesn't just silently crash the
game (if the dialog can be shown at that point). This caused some issues
in the past so I thought it would be a good idea. I also added a check
for a preprocessor define to disable exception catching completely which
should make it possible to use a debugger to debug uncaught exceptions.
=> Show an error dialog when an exception is thrown in main

code/menuui/credits.cpp, code/parse/parselo.cpp, code/parse/parselo.h
This just checks if the end of the file has been reached so existing
tables without the #end will still work (I'm looking at you
FSPort...).
=> Fix reading credits table without #end

code/graphics/material.cpp, code/graphics/opengl/gropengltnl.cpp
A hiccup in the transition to OpenGL Core. Sorry for the inconvenience. Should fix https://github.com/scp-fs2open/fs2open.github.com/issues/995
=> Fixed reflectance maps and ambient/cavity maps not being used

code/cutscene/ffmpeg/AudioDecoder.cpp, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/player.cpp, code/libs/ffmpeg/FFmpeg.cpp
There were some issues with the timing of the video frames which are fixed by these changes. This also improved the error handling when reading the cutscene since some existing cutscenes cause errors for some unknown reason.
This fixes #1028.
=> Fix a few cutscene playback issues

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/cutscene/Decoder.h, code/cutscene/player.cpp, code/cutscene/player/OpenGLVideoPresenter.cpp, code/cutscene/player/OpenGLVideoPresenter.h
This makes two changes to how the cutscenes are rendered. First, it makes the rendering code more robust against external changes so that the other graphics functions can be used while rendering the cutscene. This allows to render text over a cutscene that is being played.
Second, this adds an option which uses that capability to render some debug information about the played cutscene to the screen when a command line option is set.
These changes are also necessary for allowing to render movie files outside of the cutscene player which can be used in the future to allow H.264 encoded cbanims.
=> Add option for showing video debug informations

code/bmpman/bmpman.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/paths/nanovg/nanovg_gl.h, code/ship/ship.cpp
I needed to disable backface culling but I don't think it actually
matters.
Fixes #1038.
=> Fix TTF rendering on cockpit displays

code/hud/hudtargetbox.cpp
This fixes #960. The flagsets patch negated the flyable logic but this
one spot was missed when negating the conditions.
=> Fix wrong negation in HudGaugeExtraTargetData

code/libs/ffmpeg/FFmpegHeaders.h, code/sound/ffmpeg/FFmpegAudioReader.cpp
This adds compatibility with earlier versions of FFmpeg. A part of these changes were provided by @chief1983.
=> Add compatibility code for older FFmpeg versions

code/parse/sexp.cpp
This fixes issue #1050.  When subsystem flags were converted to enums, this function inadvertently swapped lock/free flags.
=> fix reversal of toggle caused by flag -> enum conversion

code/math/floating.h, code/math/vecmat.cpp, code/math/vecmat.h
I happened to notice that with the x86 GCC compiler (not tested with other compilers) that using fl_abs() (which evaluates to fabsf) can be used to generate tighter code.
As fabsf() is a function well known to the compiler, GCC is able to optimize it such that the sign bit in a float is unconditionally cleared in a single SSE instruction (and no function call).
Although I would expect that this would generate slightly more efficient code, I have not benchmarked that. I have however done a size check and found that the text section is smaller by about half a page (peanuts in the grand scheme of things).
=> Absolute values

code/graphics/opengl/gropengldraw.cpp, code/graphics/software/NVGFont.cpp
Since Windows line endings include this character it needs to be ignored
since the text rendering would display it as an unknown character
otherwise.
This was reported by @AxemP.
=> Ignore Carriage return characters when rendering strings

cmake/toolchain-gcc.cmake
Enable compiler and linker garbage collection to eliminate dead
code from the final image.
Signed-off-by: Peter Mitsis <peter.mitsis@gmail.com>
=> cmake, gcc: Enable garbage collection

code/scripting/lua.cpp
This'll get things going, but it's an impartial fix in the sense that existing scripts the use the old VM_EXTERNAL_CAMERA_LOCKED state are effectively outdated.
=> Fixes issue #965 by making the VM_INTERNAL view state ignore the camera lock bit

code/parse/sexp.cpp
When this functionality was added in commit 0662cb6959177723c4dd218872f006eeeb3365d0 it made an explicit check to see if the node was -1, and if so (meaning the node is not present), defaulted the value to true; a month later commit 57c4855e25c3410f39fdbb07ef346b9b1298fe71 "simplified" this to a single `is_sexp_true()` call, which returns false if the node isn't present... but the documentation still claimed that the default value was true.
Ten years later, and Axem wanted to know why his submodel wasn't being fixed by the `repair-subsystem` SEXP. I don't know if this is the first time in ten years anybody's wanted to use `repair-subsystem` on a destroyable submodel, or if everyone was just assuming it worked as intended and never noticing it didn't; regardless, while the "simple" …
=> Make repair-subsystem/set-subsystem-strength fix submodels by default.

code/render/batching.cpp
primative_batch_buffer:desired_buffer_size was not properly initialized with the vc120 (Visual Studio 2013) toolset during debugging. Default constructors proved insufficient, and std:map::operator[] seems to ignore them anyway. This fix gets around that by explicitly clearing desired_buffer)size from within batching_init_buffer()
=> Fixes issue #1097:

code/scripting/api/enums.cpp, code/scripting/api/enums.h, code/scripting/lua.cpp
Previous fixed used a logical NOT (!) instead of a bitwise NOT (~), derp!
In addition, the LE_VM_INTERNAL state now ignores VM_CENTERING, so it won't go false if the camera is returning to center.
Adds scripting support for VM_CAMERA_LOCKED and VM_CENTERING. VM_EXTERNAL_CAMERA_LOCKED is now a soft-state that is equal to (VM_EXTERNAL && VM_CAMERA_LOCKED)
=> Actually Fixes Issue 965.

code/def_files/fxaa-f.sdr, code/def_files/fxaa-v.sdr, code/def_files/main-v.sdr, code/graphics/opengl/gropenglpostprocessing.cpp
GL_EXT_gpu_shader4 is part of the GLSL 1.50 language standard so the
FXAA shader doesn't need to check against that. I also added a
conditional define for FXAA_GATHER4_ALPHA if the GLSL version supports
it which is the case when it's >= 4.00.
The other issue was a minor change from inout to out where Mesa
complained that the target variable might not have been initialized.
=> Fix a few Mesa warnings in the shader code

code/weapon/beam.cpp, code/weapon/weapons.cpp
Previously beams would not set the Destroyed by weapon flag, which means spawn weapons shot by beams would spawn regardless of whether "don't spawn if shot" was set on the weapon. This has been fixed according to Axem.
=> Fix Don't Spawn If Shot

code/ai/aicode.cpp, code/controlconfig/controlsconfigcommon.cpp, code/globalincs/alphacolors.cpp, code/localization/localize.cpp, code/mission/missionmessage.cpp, code/particle/ParticleManager.cpp
Before, if any parsing call failed it would throw an exception which
would have been propagated to the exception handler in main() which
terminates the program. This should fix that.
=> Add catch clauses everywhere where parselo is used

code/mission/missionparse.cpp
When this line was [converted by the bitset flags PR](https://github.com/scp-fs2open/fs2open.github.com/commit/770fce8de5dc3ab4fd1db0e4d74724664dd60047#diff-88098ad7c34083a6bd8b42e955eeca45R3493), it was accidentally changed from setting the flag to reading the flag, making it a do-nothing line and causing the flag to be cleared on mission load.
[Corresponding Mantis issue.](http://scp.indiegames.us/mantis/view.php?id=3187)
=> Fix for Mantis 3187.

code/io/joy-sdl.cpp
Before, they were assuming any joystick had at least 1 hat; this way, they now treat it similarly to buttons. If requesting the status of a button the joystick doesn't have, they return 0. If the joystick doesn't have a hat, querying a hat position will likewise now also return 0. This code will obviously need changed when we get around to proper (e.g. multiple) hat support.
=> Make joy_down_time() and joy_down_count() check current->numHats().

code/network/multi_log.cpp
Remove extra \n that was added in ml_string().
=> Fix double newlines in multi.log caused by ml_string()

code/ship/ship.cpp
Swaps the order of the scripting call block and the cycle-to-next-bank-if-out-of-ammo block so that e.g. "$On Weapon Fired:" scripts for a specific weapon type (which checks the currently-selected bank) will work properly when firing the last missile in the bank. Fixes issue #1091.
=> Make ship_fire_secondary() call into the scripting engine earlier.

code/def_files/main-f.sdr
The previous usages were always true since we require a more recent GLSL
version now.
=> Remove unnecessary __VERSION__ usages in shaders

code/weapon/beam.cpp
It was using the object pointer of the User before which is not correct
since the object pointer of the beam is needed.
=> Fix scripting hook object parameter

cmake/toolchain-msvc.cmake, lib/jansson/CMakeLists.txt, lib/libjpeg/CMakeLists.txt, lib/libpng/CMakeLists.txt, lib/lua/CMakeLists.txt, lib/md5/CMakeLists.txt, lib/mongoose/CMakeLists.txt, lib/zlib/CMakeLists.txt
This is a feature for developers that is not needed in FastDebug builds.
This should speed up these builds a bit since iterator debugging causes
quite a performance penalty.
=> Disable iterator debugging for FastDebug

code/graphics/material.cpp
I've realized that we weren't setting the proper color factors when we render additive materials. I reverted the interface material setting function to switch between additive and alpha blending since the core problem has been fixed. This should address https://github.com/scp-fs2open/fs2open.github.com/issues/961 while also fixing https://github.com/scp-fs2open/fs2open.github.com/issues/1074.
=> Blending fixes for interface materials.

code/bmpman/bmpman.cpp
bm_has_alpha_channel() checks true_bpp for bmps. true_bpp is 0 for animations. That's because they're created with bm_create, not bm_load or bm_load_animation. Suffice to say, that causes problems when the material setting functions wants to figure out if a bitmap needs to be alpha or additively blended. Made a simple  change to bm_create that should address this. Hopefully this should fix the waifus in https://github.com/scp-fs2open/fs2open.github.com/issues/1074
=> Fix for incorrect alpha channel detection for animations.

code/graphics/2d.cpp
This should better match up behavior of the old opengl_setup_render_states() function.
=> Use user defined alpha regardless of if blend filter is on.

lib/lua/CMakeLists.txt
This fixes the warning that `tmpnam` shouldn't be used anymore.
This fixes one of the warnings mentioned in #1103.
=> Use the correct Lua defines for Linux and Mac

ci/travis/before_script.sh, cmake/util.cmake, lib/jansson/CMakeLists.txt, lib/libjpeg/CMakeLists.txt, lib/libpng/CMakeLists.txt, lib/lua/CMakeLists.txt, lib/md5/CMakeLists.txt, lib/mongoose/CMakeLists.txt, lib/zlib/CMakeLists.txt
This should suppress the warnings that made the Linux nightly builds fail for the past few days.
This also changes the Travis configuration so that it always builds the included libraries which matches what the nightly build does. This should reduce the likelihood that the CI builds pass but the nightly builds fail.
=> Fix warnings in nightly builds

code/mission/missionparse.cpp, fred2/missionsave.cpp
The "no collide" parse object flag needs to be written as "no_collide" in the flags list, and the "no-disabled-self-destruct" flag needs to be parsed
=> Fix for #1115

code/weapon/beam.cpp
Makes beams inherit their firing ship's collision group if "$Weapons inherit parent collision group:" is enabled, and adds a collision group check to beam/ship collisions (and only beam/ship collisions, since collision groups are only currently checked for ship/ship and ship/weapon collisions).
This shouldn't break any existing mods, since usage of collision groups is surprisingly rare, and so is usage of weapons inheriting their parent's collision groups, and this change should only affect mods that do both at the same time; from a (very quick, non-representative) survey of modders, it's entirely possible that the mod requesting this change is the only one that does so (theoretically, there could be a mod out there that uses scripting to explicitly set the collision group of a beam …
=> Add collision group support to beams.

code/scripting/scripting.cpp, code/scripting/scripting.h
This fixes #1127.
The old-style hooks make the code a bit ugly but removing those while keeping backwards compatibility is a bit more involved so I'll do that in a separate PR.
=> Clean up Lua function references before destroying the Lua state

code/pngutils/pngutils.cpp
This prints the error and warning messages to the log. It could be possible to convert them into warning and error dialogs but that may break existing mods the distribute broken png files.
=> Use libpng callbacks for reporting errors and memory allocation

code/model/modelrender.cpp, code/model/modelrender.h
Instead, this uses a lambda function which is better since it doesn't
require storing any global pointers.
=> Remove usage of a static global variable in draw_list

cmake/toolchain-clang.cmake
This warning isn't caused by our code at the moment so there is no
reason to keep them disabled.
=> Reenable the deprecated warnings of GCC and Clang

code/def_files/main-f.sdr, code/graphics/opengl/gropengllight.cpp
Restores the old ambient light behavior from the OpenGL compatibility code that was replaced with the OpenGL Core code. Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/1135.
=> Restore original OGL compatibility ambient light behavior.

code/parse/sexp.cpp, code/scripting/scripting.cpp
This also fixes a small inefficiency in sexp_script_eval.
This fixes #1139.
=> Fix off-by-one error in script_state::EvalString

code/graphics/2d.cpp, code/graphics/2d.h
When the function was rewritten as part of the TrueType PR, its logic was also unintentionally changed so that it expected timestamps in milliseconds when everything calling it provides "fix"es, which represent 65536ths of a second.
Fixes #1142.
=> Fix gr_print_timestamp() to actually display timestamps properly.

code/graphics/opengl/gropenglbmpman.cpp
It looks like this conditional needed to be removed entirely when we removed code that checked for certain OpenGL extensions. This prevented render targets for environment cube maps from being generated. 
Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/900
=> Removed unnecessary conditional when making render targets.

code/osapi/dialogs.cpp
LuaError, Error & Warning use RETURN for Exit
LuaError & Warning use ESCAPE for Continue
=> Make shortcuts for Warning/Errors consistent

Readme.md
Provides fixes to improve the documentation within README.md:
* CMake-based means of compiling a debug build
* Add AppVeyor continuous integration build status
As an improvement to documentation, am hoping this PR qualifies to merge during the feature freeze.
=> Fixes to better document README.md

code/graphics/2d.cpp
This fixes #1141, where the cursor bitmap that's supposed to appear when the user is entering text is missing.
=> Make gr_bitmap obey clip offsets as it did before the OpenGL Core merge

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/osapi/DebugWindow.cpp, code/osapi/DebugWindow.h, code/osapi/outwnd.cpp, code/osapi/outwnd.h, code/parse/parselo.h, code/source_groups.cmake, fred2/fredview.cpp, fred2/management.cpp, fred2/management.h, freespace2/freespace.cpp, test/src/util/FSTestFixture.cpp
This allows to show the debug output in a second window in real time.
This system could be expanded further to allow more interactivity but
the current status is good enough.
This is a cross-platform reimplementation of a system that was removed when antipodes was merged.
=> Reimplement debug window

code/io/joy-sdl.cpp
The logic for joy_down was missing a safety check, which could cause an assertion in Joystick::getHatDownTime if a joystick without a hat (or no joystick at all?) was attached. Was reported by Bryan See here: http://www.hard-light.net/forums/index.php?topic=93045.msg1839250#new
=> Fixes an assertion due to insufficient amount of hats

code/cmdline/cmdline.cpp, code/debugconsole/console.cpp, code/parse/sexp.cpp, code/scripting/scripting.cpp, fred2/fredstubs.cpp, freespace2/freespace.cpp, test/src/test_stubs.cpp
Currently there are multiple locations in the code where the version is
constructed by printing the individual numbers together. This is mostly
sufficient but it hides information such as the commit hash or the build
name (e.g. RC1). These changes unify that behavior by always using the
version string generated by CMake.
=> Unify version string handling

code/cmdline/cmdline.cpp, code/graphics/2d.h, code/osapi/DebugWindow.cpp, code/osapi/osapi.h, freespace2/SDLGraphicsOperations.cpp
This makes the debug window resizable and also reduces the default size
to ~80% of the used display. This also makes sure that the main window
has input focus after the debug window was created.
=> Fix a few minor issues with the new debug window

lib/zlib/adler32.c, lib/zlib/compress.c, lib/zlib/crc32.c, lib/zlib/deflate.c, lib/zlib/deflate.h, lib/zlib/gzguts.h, lib/zlib/infback.c, lib/zlib/inffast.c, lib/zlib/inflate.c, lib/zlib/inflate.h, lib/zlib/inftrees.c, lib/zlib/trees.c, lib/zlib/uncompr.c, lib/zlib/zconf.h, lib/zlib/zlib.h, lib/zlib/zutil.c, lib/zlib/zutil.h
Fixes a warning in inflate.c on latest clang.  See issue #1103.
=> libupgrade/zlib_1_2_11: Update bundled zlib version to 1.2.11.

code/object/objectsort.cpp
This fixes #653.
@AxemP Could you check if this is the desired behavior? In my tests the effects looks good now but just to be sure.
If this works then it's probably among one of the most time-intensive one-line fixes I have done...
=> Fix double rendering of effect ships

code/bmpman/bmpman.cpp, code/graphics/2d.cpp, code/hud/hudconfig.cpp, code/menuui/mainhallmenu.cpp, code/menuui/readyroom.cpp, code/menuui/techmenu.cpp, code/mission/missiontraining.cpp, code/missionui/missionbrief.cpp, code/popup/popup.cpp, code/popup/popup.h, code/stats/medals.cpp
These commits prevent FSO from crashing when running with the data from the FS2 Demo. Some of these bugs could theoretically be encountered outside the demo, although it's unlikely. This PR makes no attempt to stop demo data from generating warnings; only errors or assertions.
Only commit I'm really iffy on is 559b07da63e52237d5ce66052bc2b07cec8164fa, but I never liked the hi-res interface art check anyway.
=> Improves FSO's compatibility with the FS2 Demo data

code/hud/hudobserver.cpp, code/ship/ship.cpp
In ship::clear(), @The-E removed
`memset(&weapons, 0, sizeof(ship_weapon));`
but did not replace it with the corresponding
`weapons = ship_weapon();`
This fixes that.  Additionally, this PR removes the need for one of the uses of `ship::clear()` by tweaking `hud_observer_init`.  Originally, the code used memcpy, but if the assignment operator works for `ai_info`, it should be suitable for `ship` too.
Edit:
Link to PR #806
=> some riffs on PR #806

code/ship/ship.cpp, code/ship/ship.h
* Looks like a shallow copy wasn't enough for PR #1163 , so this fix creates ship_weapons::clear() which is called by ship_weapons's constructor and by ship::clear().
=> Harmony to 1163's malady

code/ship/ship.cpp
`secondary_animation_position` wasn't being set by the `ship_weapon` constructor, which could cause potential issues with whatever uninitialized data it wound up being set to (like, say, being unable to fire any weapons in the second secondary bank until you've cycled through it once). Since it depended on uninitialized data, the behavior could even change between 32-bit and 64-bit builds (and Release/Debug, of course).
While I was at it, I also noticed some variables were getting set twice; in one instance (`primary_animation_done_time`), it was even being set to the *wrong* value the second time (according to the pre-flagset code that used `memset()` on it and then overrode some values that shouldn't have been zero). Not sure what problems that could've caused; possibly some issues with …
=> Add missing variable to ship_weapon constructor.

code/missionui/redalert.cpp, code/object/deadobjectdock.cpp, code/object/deadobjectdock.h, code/object/object.h, code/object/objectdock.cpp, code/object/objectdock.h, code/ship/ship.cpp, code/ship/ship.h
First fix is when a deleted carried ship (one that has the "red-alert-carry" flag) is docked with another ship in the red-alert mission at start. Before the fix, if a carried ship was deleted, any docked object to the ship would not be properly undocked and would cause an access violation to the NULL location.
Second fix is when a deleted carried ship is on the escort list. Before the fix, it wouldn't be removed from the escort list.
=> Fixes two crashes in red-alert missions, cleans up and refactors some of the docking code

code/graphics/2d.cpp, code/graphics/grbatch.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropenglstate.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/paths/NVGRenderer.cpp, code/model/modelinterp.cpp, code/model/modelread.cpp
These are now unneeded since we check for OpenGL 3.2 and GLSL 1.50 support when starting the engine. After that, these conditions were always true which means that they weren't needed anymore.
=> Remove some unneeded OpenGL version checks

code/scripting/scripting.cpp
Use after free; use the copied string for the Warning
=> Fix Coverity 1370830

code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropenglstate.cpp, code/graphics/opengl/gropenglstate.h, code/graphics/opengl/gropengltexture.cpp, code/graphics/opengl/gropengltnl.cpp, code/render/batching.cpp, code/scripting/scripting.cpp
The root issue of #976 was that the code that reset the depth buffer of
the scene framebuffer was actually setting the depth buffer of the bloom
framebuffer since that didn't get reset properly. To fix this I
introduced a system in our GL_state which keeps track of a stack of
"bound" framebuffers which allows us to return to the previous
framebuffer with a simple function call.
I also added support for GL_KHR_debug since that help me while debugging
which texture was in use. In the future I'll probably extend that to
other areas of the OpenGL code as needed.
This fixes #976.
=> Fix wrong usage of cockpit depth buffer

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp
It wasn't used anywhere and has been superseded by the material system.
It would also interfere with a possible texture array usage.
=> Remove tcache_set from rendering API

code/graphics/opengl/gropengl.cpp
Apparently OpenGL contexts aren't supposed to expose the KHR variant so
this version should work better if the extension is supported.
=> Fix crash when using glObjectLabel

code/graphics/opengl/gropenglpostprocessing.cpp
The framebuffer stack operations were at the wrong locations which
caused problems since the wrong buffers were used for rendering.
=> Fix post processing framebuffer binding

fred2/fred.cpp
The default key is probably not valid anymore since we don't use the
registry virtualization anymore.
This fixes #940.
=> Set the registry key for FRED

code/weapon/weapons.cpp
The flagset changes misplaced the post-parsing flag processing so that
it was only executed if a special flag was found. That was not the case
previously and this restores that behavior. I also simplified the code a
bit while I was at it.
This fixes #1191.
=> Restore original flag parsing behavior

code/graphics/opengl/gropengltexture.cpp
Since the cubemap loading code explicitly states that it doesn't support
resizing it's only logical to skip that if the bitmap that is currently
being loaded is a cube map.
This fixes #611.
=> Disable resizing for cubemaps

code/def_files/main-f.sdr
This fixes #651.
@SamuelCho Please take a look at the changes I made. They fix the issue and IMO they make sense but there may be a good reason for making these numbers go negativ.
=> Make sure that team glow colors don't go negativ

code/cfile/cfilesystem.cpp, test/src/cfile/cfile.cpp, test/src/menuui/test_intel_parse.cpp, test/src/parse/test_parselo.cpp, test/src/scripting/ScriptingTestFixture.cpp, test/src/scripting/api/base.cpp, test/src/scripting/api/bitops.cpp, test/src/scripting/api/enums.cpp, test/src/source_groups.cmake, test/src/util/FSTestFixture.cpp, test/src/util/FSTestFixture.h
Since Unix is case sensitive this should make sure that case errors are
cought early in mod development. This is an `Error` and not a `Warning`
since a mod with such a folder structure would never work under Unix and
as such it's justified to break mods that currently use this.
This fixes #1182.
=> Show error message when a data directory uses the wrong case

code/lab/lab.cpp
If the object number is set for the render info the renderer uses the
instance information of that object to render the model. That is not
correct for the lab since the instance data is handled by the lab code
in that case.
This fixes #643.
=> Remove object instance from lab render info

code/object/object.cpp
If there was only one object and that got deleted the code that keeps
track of the highest object index would cause a negativ array index. I
added a check to make sure that the index was positive but that still
means that Highest_object_index will be negativ after that function
returns. I looked at the usages of the value and that value seems to be
fine with that code so I think this should be safe.
=> Fix negative array index

code/nebula/neb.cpp, code/nebula/neblightning.cpp
The HDR changes made the nebula bitmaps a lot less visible. This fixes
that by boosting the color of the bitmaps when they are rendered.
I choose 3 since that gives a similar look to 3.7.4 but that can be
further tweaked if desired.
I also added two debug scopes to help track down where that stuff was
actually rendered.
This fixes #712.
=> Boost the color of nebula bitmaps to make them visible again

code/cfile/cfile.cpp
Fix for log printing creating directory lines for directories that already exist.  Numerous "Creating new directory..." lines were appearing in my log, and it seems like checking to see if the directory already exists before creating it would make sense.
I could be wrong, but I assume that this code has already ensured that the path is a folder and not a filename, and that any relevant assert was not done deeper inside the logic that I'm now bypassing.  If I'm wrong on that it can be added here instead with a simple enough addition, but I wanted to keep it as simple as possible.  That check might not also be as cross-platform as just checking for existence so I wanted to avoid that for that reason too.
I have confirmed in testing that both the create statements for existing directories …
=> Stops debug log printing "Creating new directory"

code/math/vecmat.cpp, code/math/vecmat.h, code/render/3ddraw.cpp
Previous version only checked if the two vectors were equal, which only half-way works for normalized vectors.
Two normalized vectors are indeed parallel if they are equal to each other, but they are also parallel if one is the negative scalar of the other (v2 = vm_vec_scale(v1, -1))
New method checks if the crossprod of the two is the zero vector. If using SSE2 optimizations, this should be only 2 ops. I commented in the function definition an alternative method should SSE2 be unavailable. The Best Fix (TM) would be to have a compile-time check for SSE2 optimizations and choose the appropriate version.
=> Fix minor bug with parallel vector testing

code/object/objectshield.cpp, code/ship/ship.cpp
**The first fix: Allow transferring energy from shields to work properly at full shields.**
A conditional originally added to `shield_add_strength()` to make shields not recharge beyond the recharge limit forgot to check that the amount shields are changing by was positive (unlike a couple other conditionals added/modified around the same time), so a call to `shield_add_strength()` with a negative delta (e.g. when transferring energy from shields to weapons) when the current shield strength is at or above the recharge limit (i.e. full strength when a recharge limit isn't specified) would immediately return without doing anything. This would, of course, result in no change to shield strength... so if you had full shields and had drained your weapon batteries dry, you could get free energy …
=> Fix two bugs with transferring energy to/from shields/weapons.

code/cfile/cfilesystem.cpp, test/src/cfile/cfile.cpp
Previously, if a mod used an upper case "Data" folder (which is the case
for the Diaspora development files) the file enumeration would fail on
case sensitive platforms (e.g. Linux) since FSO searched for a path with
a lower case "data". These changes make it so that FSO looks for all
instances of the path type name regeardless of case. Since the real path
was also needed elsewhere I added a new cf_file field which stores the
actual path which can then be used by fopen operations.
This fixes #1182.
=> Search for path types regardless of case

code/graphics/opengl/ShaderProgram.cpp, code/graphics/opengl/ShaderProgram.h, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengl.h, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltexture.cpp
The texture labels make it easier to debug which texture is currently
bound when tracing with APItrace.
I also surrounded the definition of `opengl_set_object_label` with preprocessor directives so that it only appears in debug builds or if a special preprocessor directive is enabled. This should help reduce the overhead of this feature in release builds.
=> Assign OpenGL labels to more objects

code/ai/aicode.cpp
As per discussion for PR #1171, only without the bad rebase.
=> Changes the "Object rotated too far" assertion to a log message

fred2/weaponeditordlg.cpp
This fixes the improper rounding in the weapons dialog, which can cause missile counts to decrease progressively if the dialog is repeatedly opened and closed. (Rounding is necessary because mission files store missile counts as integral percentages rather than the actual numbers of missiles.)
More information can be found in this thread:
http://www.hard-light.net/forums/index.php?topic=93161.new
=> Fix for rounding errors in weapons dialog

code/lab/lab.cpp
Related to #1205.
Instead of being greeted by the rear end of a ship, players will now get this as the default orientation.
The reason for the additional matrix rotation by angles is because matrix transforms are not commutative. That is to say, composing a matrix out of the angles P= -0.6, B = 0.0, and H = 4.0 is NOT the same transform as composing it as P= -0.6, B = 0.0, and H = 0.0 and rotating it around the H axis by 4.0 radians.
=> Change Initial Orientation in the Lab

code/pngutils/pngutils.cpp
PNGs can have 16 bits per channel but we always tell libpng to reduce
that to 8 bits per channel. However, we do not tell the caller of
png_read_header that this will happen so instead of 32-bits per pixel,
we tell bmpman that the image has 64 bits per pixel which causes some
issues.
The specific issue I fixed was the system map of BtA where the jump
nodes used a 16-bit PNG which broke the alpha blending of those bitmaps
since bmpan though that the image had no alpha channel.
=> Return correct bits-per-pixel data for 16-bit PNGs

code/parse/sexp.cpp
If the logger happens to encounter a sexp_node with a short-circuited value, the node may not actually be an operator node.  This PR makes a second attempt to select the operator if the first attempt comes up invalid.
=> make sure we find the correct operator for logging in short-circuited sexps

freespace2/SDLGraphicsOperations.cpp
This fixes #1051 by explicity telling SDL to create the window in the
display corner instead of centering the window. This has caused some
problems because the window borders aren't visible anymore in this case
which lead to some confusion.
@Goober5000 Please test if this fixes your issue since I don't have a system where this bug happens.
=> Create main window at 0,0 if its the same size as the display

code/ai/aicode.cpp
When converting an Assertion to a Warning or log print, remember to invert the Assertion's condition to get correct behaviour. Fix for #1217.
=> Removes log spam

code/math/vecmat.cpp
Fixes a subtle problem with vm_test_parallel() wherein a relative error
was accidentally converted into an absolute error.
Instead of comparing the result of the cross product to the zero vector,
the two calculated components of the cross product are compared against
each other. This permits vectors whose cross product is a large number
but whose cross product partials are within relative error of each other
to be treated as parallel.
For example, the following two vectors may now be considered as parallel
whereas before they were not:
v1 = (1000004.0, 1.0, 1.0)
v2 = (1000000.0, 1.0, 1.0)
The relative difference between them is sufficiently small according to
vm_vec_equal() for them to be considered equal, but their cross product
would have elements whose magnitudes would be near 4.0 …
=> vecmat: Fix vm_test_parallel()

code/cmdline/cmdline.cpp
Because apparently that isn't happening right now.
=> Export the -no_emissive_light flag to the Launcher

fred2/missionsave.cpp
Currently, when saving a retail-compatible mission, FRED sets +Red Alert: based on whether the Full Nebula option is enabled rather than the Red Alert option. This PR fixes this behavior.
=> Fix for improper setting of +Red Alert:

cmake/platform-darwin.cmake, code/cmdline/cmdline.cpp, freespace2/freespace.cpp
fix/967: Define APPLE_APP to fix some issues introduced on Mac in the CMake conversion (may have other effects we aren't yet aware of).
Specifically fixes being able to double click the app in the finder (issue #967), as opposed to having to launch through the finder.  Before this returned an error, now it will run as expected, with the last saved command line settings.
Also unifies a three-part ifdef into a two part by using our standard DIR_SEPARATOR.
GetCurrentDirectory and SetCurrentDirectory had to be replaced with more standard equivalents as they don't seem to be part of any current Mac framework, if they ever were.
The target_compile_definitions line is paired alongside the EXE_GUI_TYPE set because if the Mac build is ever supported in a non-bundled fashion, those two lines would …
=> Fix for #967 - Enable APPLE_APP in Mac CMake project

code/starfield/starfield.cpp
The code wrongly used return instead of continue. This caused a second
sun to disappear if the bitmap of the first sun wasn't drawn.
This fixes [Mantis 3188](http://scp.indiegames.us/mantis/view.php?id=3188).
=> Fix wrong control flow in stars_draw_sun

code/object/object.cpp
This regression was introduced with the new model draw list which separates
collecting the drawing information and actually drawing the objects.
Previously, the scripting hook was always executed and the override
condition was used to determine if the normal rendering should happen.
Since 3.7.4, the scripting code is only executed if the condition was
overridden by Lua and if that override is active then the model isn't
rendered at all.
This executes the scripting hook in all cases and then checks if the
scripting system specified if rendering of that object should be
skipped. This introduces some slight changes in behavior since, when the
scripting hook is executed, the object isn't actually being rendered but
instead it's added to the draw list. IMO, that is not a major issue for
any …
=> Fix "On Object Render" behavior regression

freespace2/freespace.cpp
In large mods this caused memory issues since we reached the 32-bit
memory limit when loading all models of a large mod (e.g. Blue Planet).
I fixed that by explicitly unloading the loaded model once the code is
done with it.
This fixes [Mantis 3177](http://scp.indiegames.us/mantis/view.php?id=3177).
=> Unload models after loading them for -pofspew

code/ship/ship.cpp
Most of the game considers a ship bank's max missile count to be the bank's capacity divided by the missile's cargo size, rounded to the nearest integer. So, for example, the GTF Ares' first missile bank, which has a capacity of 90, can hold 23 Rockeyes, which have a cargo size of 4 (90 / 4 = 22.5, rounded to 23).
The `get_max_ammo_count_for_bank` function, however, doesn't do the rounding, so in the scenario above, it thinks the Ares' first missile bank can hold only 22 Rockeyes (90 / 4 = 22.5, truncated to 22). (This function is used by FRED to obtain max missile counts, and is also used by the game to determine how many missiles a support ship can load into a bank during a red-alert mission.)
This PR fixes this discrepancy by adjusting the `get_max_ammo_count_for_bank` function to …
=> Change get_max_ammo_count_for_bank to return "correct" max missile count

code/missionui/missioncmdbrief.cpp, code/missionui/missiondebrief.cpp, code/missionui/redalert.cpp
This happened in BtA where a script changed the font after rendering its
UI. Since the briefing code didn't account for that, the word wrapping
code used the wrong font for calculating how long a line would be which
made the display look wrong.
=> Fix briefing word wrapping when a script changes the font

code/io/timer.cpp
If FSO runs for a very long time (5 hours to be exact) then the SDL
performance counter reaches a value so hight that rescaling it to
microseconds causes an overflow which is bad.
This fixes that by implementing the rescaling by computing the factor in
the timer initialization code and then multiplying the SDL time with
that. This uses the same principle as the changes done by @TheMatthew in #1082.
According to the tests done by @chief1983, this fixes #1237.
=> Fix standalone timer overflow

code/hud/hud.cpp, code/hud/hud.h
Previously, the hud gauge was hidden if the player ship had taken no
damage. However, this made it impossible to see if subsystems have been
damaged.
These changes make sure that the subsystem values are shown even if the
hull integrity is at 100%. This is done by first collecting all the
necessary information about each line in the gauge and then, if that list
is non-empty, rendering it. This is necessary since the gauge code can't
decide if anything will be visible before looking at the entire
subsystem list.
There is a minor behavior change with how popups are handled.
Previously, the code would return if the HUD gauge was a popup and its
strength was at 100%. However, I think that this was dead code anyway
since that condition could never be true at that point because the code
would …
=> Render all damage elements of the damage HUD gauge

code/playerman/managepilot.cpp
This fixes a bug whereby creating a pilot in the barracks screen (not the initial pilot selection screen) would effectively clone the variable vector from whatever pilot was selected beforehand.
=> Clear the player's variable vector in init_new_pilot() if reset is true.

code/hud/hudtargetbox.cpp
A piece of debris spawned from a ship will say what class of ship it came from. If that ship has an alternate class name defined in FRED, that's used instead. If the ship class table entry specifies an "$Alt name:", however, that isn't used, which could potentially be confusing. This fixes that oversight.
=> Make debris from a ship use the ship class's alt name, if specified.

code/particle/particle.cpp
The new particle system didn't load the particleexp01 anim as a generic fire animation. This caused calls to create PARTICLE_FIRE particles to fail silently.
Fixes #1245.
=> Load the Fire particle animations

code/parse/sexp.cpp
So that it behaves as expected when used in an event without a when conditional.
Fixes #1256
=> Make script-eval return SEXP_TRUE 

freespace2/freespace.cpp
Otherwise the Simulation hook would be called without a Player variable
which breaks some scripts.
=> Set the Player scripting variable for the whole frame

code/parse/sexp.cpp
As per discussion for #1256, script-eval-string should also return SEXP_TRUE, if only for consistency's sake.
=> Like script-eval, script-eval-string should also return SEXP_TRUE

CMakeLists.txt, cmake/util.cmake, code/CMakeLists.txt, code/jpgutils/jpgutils.cpp, code/prefix_header.h, code/source_groups.cmake
Cotire (the CMake module we use for handling precompiled headers) can
auotmaically generate a prefix header by examining the includes of the
project. However, if a system include changes, the prefix header may
change as well which triggers a complete project rebuild. To avoid this
and to add the ability to customize the prefix header, I added a
manually maintaned header which will be used by all platforms and which
will only change if that file is manually changed.
=> Use a manually maintained prefix header for cotire

code/hud/hud.cpp, code/hud/hudshield.cpp, code/render/3ddraw.cpp
I also added a few graphics debug scopes since I needed those for
tracking down which code renders the shield icons.
This fixes #1261.
=> Render correct number of vertices for shield icon

cmake/toolchain-clang.cmake, cmake/toolchain-gcc.cmake
The C++ standard allows to have no return in a function but in most
cases that is not the desired behavior. There are currently no instances
of this warning in our code but I encountered this error while
developing something else.
=> Enable GCC and Clang warning for missing return

code/lab/lab.cpp, code/menuui/techmenu.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/model/modelrender.cpp, code/model/modelrender.h, code/ship/ship.cpp
This applies table-based texture replacement settings in the lab, techroom and the weapon/ship select screens.
Fixes #1264
=> Make table-based texture replacement work

cmake/toolchain-msvc.cmake
One of the nightly builds failed to compile with an error saying that it
had run out of heap space. This adds the suggested flag which should
hopefully fix this issue.
=> Allocate more memory for the Visual Studio compiler

freespace2/SDLGraphicsOperations.cpp, freespace2/resources.cmake, freespace2/resources/win/default.manifest
This sets the dpiAware flag which should improve the compatibility with
High-DPI displays. It also sets a few values for specfying what Windows
versions we support and it also enabled the nicer dialog boxes which
makes the error and warning dialogs look a bit nicer.
=> Add a Windows executable manifest to FreeSpace2

code/def_files/deferred-f.sdr, code/def_files/main-f.sdr
This pull request should address a lot of the concerns expressed in this thread (http://www.hard-light.net/forums/index.php?topic=93151.0) about the physically-based specular lighting model. Namely, this changes it so that we don't use Fresnel reflectivity when using legacy specular data. This preserves the darker specular colors, preventing legacy specular data from looking really flat at grazing angles when Fresnel reflections become really prominent. 
I also tidied up the model shader a bit, removing a bunch of unused or unnecessary variables.
I also discovered a bug in the deferred lighting shader, where it was using specular light source color as the specular material instead of using the specular material from the g-buffer.
=> Adjustable fresnel term in lighting model. Model shader cleanup. Deferred lighting shader fix.

freespace2/SDLGraphicsOperations.cpp
I added the "allow high DPI windows" SDL-flag while investigating #998
but since that flag isn't used on Windows we can safely remove it again
without causing issues.
=> Fix rendering on high DPI displays on Mac

code/hud/hudshield.cpp
The generated shields did not respect the display offset specified in
the table so they were drawn out of the clipping bounds of the gauge
which meant that they were not visible. This fixes that by respecting
the specified display offset when rendering the shield icons.
=> Fix generated shields rendering in cockpits

code/object/object.h, code/scripting/api/objs/object.cpp
I found this issue while debugging the JAD gauntlet where a script calls
getSignature() on an invalid object. However, object_h does not see the
object as invalid even though its signature is 0 which is defined to be
an invalid sigature. This should fix that by making sure that
object_h::isValid returns false if the saved signature is not valid.
=> Adjust object_h validity check to avoid assertion failure

code/ship/ship.cpp
I just encountered this assertion while debugging another issue. As far
as I can tell, this can happen if the ship dies the same frame that
change_ship_class is called. Since a negative hull_strength value is a
valid value this assert is invalid. The CLAMP should ensure that the
following code still behaves as expected.
=> Remove unneded assert in change_ship_class

.gitignore, code/missionui/missionweaponchoice.cpp, code/missionui/missionweaponchoice.h, code/osapi/dialogs.cpp, code/weapon/weapons.cpp, test/src/source_groups.cmake, test/src/util/test_util.h, test/src/weapon/weapons.cpp, test/test_data/weapon/data/tables/weapons.tbl, test/test_data/weapon/description_line_too_long/data/tables/test-wep.tbm, test/test_data/weapon/description_too_many_lines/data/tables/test-wep.tbm
If the description of a weapon is too long it would currently cause a
very unhelpful assertion message. This fixes that by checking the length
of the lines when parsing the weapon description. I removed the
assertions since the string is just cut of if it is too long so that
fixes the actual assertion.
I also added two unit tests for making sure that too long descriptions
cause warnings.
=> Fix assertion failure in weapon choice screen 

code/hud/hudtarget.cpp
Since the rendering code always accesses all four frames it must be
ensured that they are all present. Currently, there is a bmpman
assertion about an invalid handle if the animation does not have enough
frames. This fixes that by warning about that and then resetting the
bitmap handle to -1 so that the rendering code doesn't try to use the
handle.
=> Require that the energy bar animation has 4 frames

code/radar/radardradis.cpp
The DRADIS has two icon types, one where the color is scaled with the
IFF color and once which isn't. Due to a regression, both icons were
previously scaled with the IFF color which made the icons look bad. This
fixes that.
=> Restore color icon behavior in DRADIS HUD gauge

.travis.yml, ci/travis/before_script.sh, cmake/toolchain-clang.cmake, cmake/toolchain-gcc.cmake, code/scripting/ade.h, code/scripting/api/libs/hud.cpp, code/scripting/api/libs/testing.cpp, code/scripting/api/objs/hudgauge.cpp, code/scripting/api/objs/hudgauge.h, code/scripting/api/objs/particle.cpp, code/scripting/api/objs/particle.h
As described in #1278, the current scripting system has issues with
handling non-trivial C++ types. Since fixing that deficiency is too much
work, especially since we are in a feature freeze, I decided to simply
enforce the usage of trivial types for scripting handles. Fortunately,
only two handles used non-trivial types so it was relatively easy to fix
those instances by dynamically allocating those and only storing the
pointers in the lua memory.
This fixes a bug in JAD-XA where the game would crash at the last boss.
Also, I noticed that the HudGauge handle used a copy of the hud gauge
rather than a pointer to the actual instance so I'm pretty sure that any
scripting changes to a custom HUD gauge simply didn't work before.
=> Disallow to use non-trivial types as scripting handles

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropenglpostprocessing.h, freespace2/freespace.cpp
This introduces code to explicitly restore the z-buffer binding to the
previous value instead of relying on the lightshaft code to restore it.
I'm not sure why the code to reset the depth buffer was in the position
it was previously in. The way it was, it looked like some kind of hack 
but I have no idea why it would be put there in the first place. @SamuelCho Maybe you could take a look at this? I tested the lightshaft effect with and without my changes and I couldn't find any difference.
=> Fix depth test of lasers when using a cockpit ... again

code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/io/key.cpp
Previously, the key text would use the localized key name which made it
hard for scripts to consistently handle key presses across different
languages. This changes that interface so that it always returns the
english name of the key.
This was reported in the [BtA bug report thread](http://www.hard-light.net/forums/index.php?topic=92701.msg1843838#msg1843838).
=> Always use the english key name in the scripting interface

fred2/missionsave.cpp
The briefing icon lables previously just wrote the label string to the
mission files without surrounding it with an XSTR which made is
impossible to translate them. I fixed that by using the right function
call when saving the value.
This fixes Mantis 3193.
=> Output briefing icon lables as XSTRs

code/graphics/material.cpp
Fixes the derp set_color method in the material class (https://github.com/scp-fs2open/fs2open.github.com/issues/1289)
=> Fixed color struct to vec4 color conversion in material class.

code/osapi/outwnd.cpp
Due to some initialization order issues the original header string
wasn't printed to the log anymore. This fixes that by initializing
outwnd_inited before doing the initial outwnd_print.
=> Fix log header printing

code/ship/ship.cpp
These were pointed out by Spoon on the forums; given that these are just spewing warning dialogues but not applying any corrective measures (which leads me to believe that these Warnings are strictly informative, nothing more), downgrading them to log print should be fine.
=> Remove a couple of annoying warnings in ship flag parsing

code/parse/sexp.cpp, code/parse/sexp.h
I'm pretty sure that this is a bug since the documentation of
std::string::copy says that it doesn't append a 0 byte so our code would
need to do it manually. Instead, the code appended the 0 byte to the
input buffer which also conflicts with const-correctness (the function
was used on a lua-string buffer which should be const outside Lua).
=> Correctly terminate Sexp_variable text with a null byte

code/ship/shield.cpp
This ensures that the conditional statement that allows shields to be rendered as decals uses the correct logic with the detail level values.
This is a "fix" for #1294
=> Correct shield decal selection logic

code/graphics/opengl/gropenglpostprocessing.cpp
Immediately clearing the z-buffer is definitely not a good way of
saving it for later use. This fixes the lightshaft rendering (which was
broken by my fix in #1282) by removing the depth buffer clear from the
z-buffer restore function. The z-Buffer is cleared anyway before
rendering into it so it shouldn't make a difference.
=> Fix lightshaft rendering with cockpits

code/def_files/main-f.sdr
Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/1293
=> Fix for intense glare when rendering a model in a render target with no lighting.

code/graphics/opengl/gropengldraw.cpp, code/lab/lab.cpp, code/lab/wmcgui.cpp
The updated values for the distortion map were rendered too close to the
edge of the screen so they were clipped which meant that there was no
distortion data available. This fixes that by moving the rendered
primitives farther away from the edge. I'm not sure why this worked in
3.7.4, maybe the fixed function rendering used some slightly different
matrix.
I also don't know why this wouldn't work consistently across GPU vendors
but maybe the rasterization rules vary a bit across drivers.
This fixes #1307.
=> Fix OpenGL distortion map update

code/graphics/opengl/gropenglshader.cpp
Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/969. glBindFragDataLocation needs to be called before a shader program is linked, not after. Apple likes following the Core spec to the letter.
=> Reorder fragment shader destination binds to fix Mac deferred lighting.

code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp
This also promotes medium and high severity OpenGL messages to the
general logging category to help troubleshooting in the future.
=> Fix OpenGL errors when framebuffer effects are disabled

code/def_files/main-f.sdr, code/def_files/main-g.sdr, code/def_files/main-v.sdr, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropenglstate.cpp, code/graphics/opengl/gropenglstate.h, code/graphics/opengl/gropengltnl.cpp
The current shaders compute the clip values in the vertex shader and
then discard fragments if those values say that the fragment is clipped.
I don't know why this was done but, as far as I can tell, this behavior
can be fully replaced by using the built-in OpenGL clip-plane feature
which should also reduce the amount of fragment shader invocations. This
won't affect performance too much since we rarely use clip planes but it
seems like the correct thing to do.
=> Use built-in OpenGL clip plane instead of custom variant

code/graphics/opengl/gropengldraw.cpp, code/parse/sexp.cpp, code/starfield/starfield.cpp, code/starfield/starfield.h, code/tracing/categories.cpp, code/tracing/categories.h, freespace2/freespace.cpp, scripts/performance_graph.py
This should make sure that the environment map is only redrawn if
necessary. In my case that should improve frame times by around 1ms for
the normal case when the environment map doesn't need to be redrawn.
This only affects missions which use SEXPs to change the background but since that is more and more common with new releases this should improve framerates a bit.
=> Improve handling of environment map redrawing

code/bmpman/bmpman.cpp, code/gamesnd/gamesnd.cpp, code/mission/missionload.cpp, code/model/modelcollide.cpp, code/model/modelinterp.cpp, code/model/modeloctant.cpp, code/model/modelread.cpp, code/ship/ship.cpp, code/sound/sound.cpp, code/tracing/categories.cpp, code/tracing/categories.h, code/weapon/weapons.cpp, freespace2/freespace.cpp, freespace2/levelpaging.cpp
This makes it easier to determine what takes the most time while loading
the mission (loading models) and how we could optimize that load time
(optimize model loading).
This is not a bug fix but it also shouldn't cause any regressions since
there are no actual code changes so this could be merged before the
release of 3.8.
=> Add tracing scopes to the mission load code

code/cfile/cfilearchive.cpp, code/libs/ffmpeg/FFmpegContext.cpp
Invalid values previously corrupted the internal position counter which
caused crashes on some platforms because the position counter would
overflow in the next read operation. I added some assertions to track
the position counter corruption and it's probably a good idea to leave
them in to catch possible future errors early.
The actual fix was to just ensure that the seek position it always valid
for the file.
This fixes #1059.
=> Validate seek offsets in cfseek

.editorconfig, code/def_files/passthrough-v.sdr, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropenglshader.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h
This adds support for using clipping planes with the passthrough shader
by passing through the clip equation of the specified plane and then
using gl_ClipDistance for using the built-in clipping capabilities.
This fixes ##1326.
=> Apply clipping planes to passthrough shader

code/hud/hudshield.cpp
See #1329, this makes the rear shields slightly further away from the
front, so that the model clip area matches the area where the shields
are drawn.
=> Tweak autodraw shield bar positions

cmake/platformChecks.cmake, cmake/platformChecks.h.in, code/scripting/ade.h, code/scripting/lua/LuaTable.cpp, code/scripting/lua/LuaTable.h
FSO doesn't build from source on OpenBSD anymore. This patch corrects the only significant problem: the iterator in LuaTable.h/cpp known as _L clashes with a #define in OpenBSD's standard headers (ctypes.h to be specific). The new name proposed here is simply taken from the type.
One other problem still prevents building on OpenBSD at this time: an assert in code/scripting/ade.h that calls std::is_trivially_copyable, available in libstdc++ >= 5 (where OpenBSD has 4.9 in ports/packages). OpenBSD on i386/amd64 will probably use clang/libc++ in the future, so this issue will go away anyhow. For the record, the following diff on top of this PR fixes the build on OpenBSD 6.1-current at this time:
```diff
diff --git a/code/scripting/ade.h b/code/scripting/ade.h
index 8478ea3ea..04cf920ef 100644 …
```
=> Fix the build on OpenBSD

code/stats/stats.cpp
The problem was caused by an oversight in 07107ce9b208d6dc8c5a2efcb9122b8180908103 (namely, that changing some strings from being passed directly to string-formatting to being passed as arguments to a "%s" format-specifier meant that "%%" was no longer needed to get a plain "%" out the other side).
Fixes [Mantis 3196](http://scp.indiegames.us/mantis/view.php?id=3196).
=> Get rid of duplicate percent signs in the statistics screen.

.travis.yml, appveyor.yml
While searching for the cause of the rate-limiting of our BinTray
organization, I revoked the API key used by the CI servers in case the
key got compromised somehow. These are the updated keys which should
allow us to upload nightly builds again.
@chief1983 and I are working on a nightly solution which does not
require BinTray but until that works we need these updated keys.
=> Update BinTray API keys

.travis.yml, appveyor.yml, ci/travis/nightly_deploy.sh
Since BinTray may be unreliable as our nightly host @chief1983 and I
decided that it would be best to return hosting to our dedicated FTP
servers. These changes implement that together with a pending pull
request for the nightly script.
=> Upload nightly builds to FTP instead of BinTray

cmake/platform-solaris.cmake, code/globalincs/pstypes.h, code/globalincs/version.cpp, code/globalincs/version.h, code/mod_table/mod_table.cpp
I have actually produced a fully functioning build on OpenIndiana (the fork of OpenSolaris), and have compiled on a Solaris 11.3 VM with these changes.  I am open to suggestions for alternative names for the version->gameversion rename, but the rename itself is required because version is a defined enum in math.h in the Solaris system headers, which resulted in a symbol conflict on Solaris distros since this was committed nearly two years ago.  The other fixes just enhance the existing platform file to fix library linking, and address a missing line from when a series of IFDEFs were modified without addressing the Solaris case (probably since no one was available to test it on Solaris at the time).
=> Fix several issues blocking a Solaris compile

appveyor.yml
I encrypted those values using my user instead of our SirKnightly
account which meant that the values failed to decrypt. These new values
were encrypted using the SirKnightly user which should allow Appveyor to
upload the nightly builds to our FTP servers.
=> Fix encrypted login data for appveyor FTP upload

code/weapon/weapons.cpp
The weapon state value of the weapon was updated after the particle
source was created so the source was always invalid which caused an
assertion.
=> Fix assertion when applying particle effect to laser

code/anim/animplay.cpp, code/bmpman/bmpman.cpp
This was noted by FrikgFeek. When loading an ani that had its header corrupted, it's very easy for invalid data to get written to rather important fields; this adds a small check that should at least catch a few of these.
=> Adds a small sanity check after reading an ani header

code/menuui/optionsmenu.cpp
fa60c666bcef7f2d560d718e8741bfccb5a85c4d tried to fix an issue reported
by Coverity which was an intentional "issue". This restores the original
behavior which will cause a new coverity issue which can be ignored.
This fixes Mantis 3195.
=> Revert bad fix for Coverity issue

code/cmdline/cmdline.cpp
`os_init_cmdline()` contains the legacy-mode codepath in a conditional, but then doesn't put the non-legacy mode code in an `else` branch, resulting in cmdline_fso.cfg getting processed twice, leading to e.g. every mod getting loaded twice (which can cause all kinds of issues). This just wraps the non-legacy code in an `else` branch so that FSO running in legacy mode won't do both.
=> Stop parsing cmdline_fso.cfg twice in legacy mode.

code/hud/hudreticle.cpp
The code works perfectly fine without it and it causes issues with a
release campaign so there is no reason to keep it.
=> Remove unneded Int3 in hudreticle.cpp

code/stats/scoring.cpp
There's a bit of debug code that checks to make sure all ranks are in ascending point order; if this check fails, FSO calls `Int3()` instead of trying to describe the problem. I've changed it to a Warning that actually explains the problem, so the modder can fix it.
Is a conversion to a Warning the correct response here? It shouldn't be an Assertion instead (it's not a coding mistake, since it results from bad data), but making it an Error seemed like a bad idea (Release builds would go from silently ignoring it to crashing outright). Nonetheless, making it a Warning means that people could continue past it, and certain code expects all point values to be in ascending order. I don't think any of them will actually crash if they aren't, but it could result in things like a forced promotion …
=> Avoid Int3() when finding a rank with an out-of-order points value.

code/ship/ship.cpp
SND_MISSILE_START_LOAD and SND_BALLISTIC_START_LOAD (indices 33 and 200, respectively) could never actually play due to a logic error (they checked that a variable was true and the loop was on the last bank, when those conditions being met earlier in the function set that same variable to false). As far as I can tell, this broke back in 2006 with commit f300716e9381b4f6187ba3f3a09243c78708f579.
=> Allow rearm start sound effects to actually play.

code/ship/ship.cpp
The gun convergence code would detect if the target was within the minimum distance and move the predicted target point farther away if so, but wouldn't also alter the `dist_to_aim` variable to match; since `predicted_target_pos` is used by the autoaim code while `dist_to_aim` is what automatic convergence uses, this meant automatic convergence didn't respect the minimum distance at all.
Looks like this was broken in 7bb10d8408de60ccb69d88e342679a94cc4b3226.
=> Allow "+Minimum Distance:" to actually work with automatic convergence.

code/menuui/techmenu.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionweaponchoice.cpp, code/model/modelrender.h
The OpenGL headers should never be included by code outside of the OpenGL implementation.
=> Remove include of OpenGL header in non-OpenGL code

code/weapon/shockwave.cpp
After someone tripped an assertion in the shockwave code which provided no details, I found some... questionable vector-related code. I changed all the code I could find that looped through the vector with iterator-based code, converted most `Assert`s into `Assertion`s for more informative debugging, and added a couple `Assertion`s to check previously-unchecked assumptions (which theoretically should never be tripped, but we'll see). A test build with the vector fixes resulted in the assertion no longer tripping so I'm fairly sure the improper erasure of the vector was causing problems (leftover data from a previous mission with a model number that no longer made sense because the model was unloaded).
=> Cleaning up the shockwave code's use of vectors and assertions.

code/headtracking/trackirpublic.h
This should make it possible to have both DLL version installed at the
same time without causing conflicts.
Combined with the new DLL, this will finally fix #974.
=> Use TrackIR DLL with 64 suffix when compiling a 64-bit build

code/graphics/generic.cpp
Prior to APNG support, a regular non-animated PNG could be used as a still-frame command briefing animation. This started causing a crash when APNG support was added because any PNGs sent through `generic_anim_stream()` would get `ga->type` set to `BM_TYPE_PNG`, then sent through the APNG code... which would determine that they weren't APNGs, throw an `ApngException`, and `generic_anim_stream()` would return -1... except that `BM_TYPE_PNG` would still be set, so that when it later came time to render the still frame in `generic_frame_render()`, it would be sent through `generic_anim_render_variable_frame_delay()`... which expected a fully-formed APNG, tried to dereference `ga->png.anim`, and crashed.
This commit is a simple fix to reset `ga->type` to `BM_TYPE_NONE` if APNG processing …
=> Reset generic animation type to BM_TYPE_NONE if APNG processing fails.

code/ai/aigoals.cpp
This just popped up in Artemis: When a ship is removed from play using ship-vanish, any AI goals still referencing that ship become instant death for debug builds due to a leftover bit of Volition-vintage sanity checking. Said checking is actually unnecessary; the code can handle this case gracefully (and actually does so in release), ships that have vanished without a trace are treated the same as ships that haven't arrived yet. Downgrading the Int3() to a log print (Because, after all, this could result in unintended behaviour) seems the correct course of action.
=> Handle ships removed from play via ship-vanish correctly in ai goal processing

code/lighting/lighting.cpp, code/weapon/weapons.cpp
While replaying Sesquipedalian's mission "The Fourth Vial", I discovered that all of the beam sections were being removed from the subspace rift beams.  I tracked this down to an unintended side-effect of the `weapon_clean_entries()` function added by Taylor in 2007 (!) in SVN revision 4019.  Invisible beam sections are initialized with no filename, but removed beam sections are also re-initialized with no filename and then culled later on.  This PR adds a check in the cleanup function to whitelist invisible beam sections while still allowing removed beam sections to be culled.
I also added a Warning for beams that (through either improper table entry creation or overzealous beam section removal) end up with 0 sections.  Although issue #1366 makes this of limited utility at present. …
=> Invisible beam section fix

code/scripting/api/objs/weapon.cpp
`l_weapon.Team` was using `Num_teams` which only changes value from 1 to 2 in response to whether or not the current game is a multiplayer session. Changing it use `Num_iffs` makes it coherent with the `l_Team` Indexer.
=> Make l_weapon use IFFs in Team var

fred2/initialstatus.cpp
This also fixes a slight behavior change for when multiple selected ships had inconsistent values.
=> Fix inverted "Has shields" flag in initial status dialog

code/tracing/categories.cpp
Cutscene audio decoding was accidentally named "FFmpeg decode video", causing some minor problems in the profiling code (because the same name is used for actual video decoding, resulting in an assertion firing).
=> Fix duplicate tracing/profiling category.

code/parse/sexp.cpp
`sexp_manipulate_colgroup()` was using logical NOT when it should've been using bitwise NOT, meaning that removing any collision group would remove *all* collision groups.
=> Fix removing a collision group via SEXP.

code/hud/hudtarget.cpp
This assertion could apparently be hit if a ship was vanished (e.g. with `ship-vanish`) in the middle of talking. Rather than making the vanishing code aware of (and responsible for) `Message_shipnum`, it seemed simpler to just make `hud_show_message_sender()` clear the invalid shipnum itself.
=> Avoid faulty assumption in message bracket code.

code/menuui/credits.cpp, code/scripting/lua.cpp
* Credits roll now grabs the LUA copyright info from liblua, instead of being hardcoded
* Credits roll now has LUA version info as well
=> Adds LUA versioning and copyright info to the scripting.html output

code/graphics/opengl/gropengldraw.cpp
At least on NVidia drivers, the medium-severity warning "Framebuffer unsupported. Framebuffer object Scene framebuffer is unsupported because the depth and stencil attachments are mismatched." would get repeatedly output to the debug log. @SamuelCho suggested this change, which gets rid of the warnings and doesn't appear to have introduced any graphical glitches.
Fixes #1382.
=> Get rid of OpenGL warnings about the framebuffer being unsupported.

code/parse/parselo.cpp
While looking into the issue described in [this thread](http://www.hard-light.net/forums/index.php?topic=93624.0), I noticed that an Error message in `mark_int_list` incorrectly says `stuff_int_list`.  Then I saw that the invalid `lookup_type` value isn't printed in the error messages, so I thought that would be good to add.
=> Small improvement in error messages in stuff_int_list and mark_int_list

code/parse/sexp.cpp
There is an old bug, dating back to FS1 retail (!) where the `targeted` sexp wasn't always reliable.  Sometimes it would fire immediately rather than waiting for the specified time duration.
Just now I figured out why.  There is a special `Players_target`, `Players_targeted_subsys`, and `Players_target_timestamp` set of variables that are updated every frame for the benefit of this sexp.  Unfortunately, the `sexp_targeted` function used `Player_ai->target_objnum` and `Player_ai->targeted_subsys` instead of the former two variables.  This made it possible for the sexp to fire during the single frame when `Player_ai->target_objnum` and `Player_ai->targeted_subsys` held the new value but `Players_target_timestamp` held the old value.
This bug also affected `sexp_node_targeted` so I fixed it …
=> fix an old Volition bug in the targeted sexp

code/parse/parselo.cpp, code/parse/parselo.h, code/scripting/api/objs/graphics.cpp
This was reported by @AxemP who wanted to have leading tabs in a text
line. However, `split_str` removed those characters by default since it
ignores leading whitespace. To fix that unexpected behavior of
gr.drawString I added a new paramter to `split_str` which disabled
whitespace removal and enabled that flag for the scripting function.
That should not be a problem for existing scripts since the expected
behavior would be that leading whitespace remains in place and since we
have not received any bug reports about missing white space I'm going to
assume that no one has used the function like this before removed those
characters by default since it ignores leading whitespace. To fix that
unexpected behavior of gr.drawString I added a new paramter to `split_str`
which disabled whitespace …
=> Ignore leading whitespace for gr.drawString

code/graphics/software/NVGFont.cpp, code/graphics/software/font.cpp
Instead, this will now cause a Warning when the issue is detected while
parsing the table and an Error when it still occurs at runtime.
=> Fix Assertion when default Volition font could not be found

qtfred/source_groups.cmake, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/EditorViewport.cpp, qtfred/src/mission/dialogs/AbstractDialogModel.h, qtfred/src/mission/dialogs/EventEditorDialogModel.cpp, qtfred/src/mission/dialogs/EventEditorDialogModel.h, qtfred/src/mission/dialogs/WaypointEditorDialogModel.cpp, qtfred/src/mission/dialogs/WaypointEditorDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/EventEditorDialog.cpp, qtfred/src/ui/dialogs/WaypointEditorDialog.cpp, qtfred/src/ui/dialogs/WaypointEditorDialog.h, qtfred/src/ui/widgets/ColorComboBox.cpp, qtfred/src/ui/widgets/ColorComboBox.h, qtfred/src/ui/widgets/renderwidget.cpp, qtfred/ui/FredView.ui, qtfred/ui/WaypointEditorDialog.ui
This adds the first fully functioning editor window to qtFRED. The system uses a Model-View system to separate the GUI view from the underlying data model. Updating the view is done through a signal which is emitted by the model when it changes and the view can change the model using normal function calls.
This is how I would like to build all the editor dialogs so this is the time and place to discuss possible alternatives.
=> Add waypoint editor

fred2/sexp_tree.cpp
This is a follow-up to issue #1381.  Whereas that was a fix, this is just a cleanup.  Instead of exhaustively performing a manual check of all possible sexp operators that use variable names as an argument, just check to see if the OPF_ type is `OPF_VARIABLE_NAME`.  This was already calculated a few lines earlier in the function.
This PR also changes the `op` variable in this function to `op_index`, to make it clear that it is not `op_const`.
=> Use the already-determined sexp argument type

lib/prebuilt.cmake
This became necessary since the BinTray hosting fails some times which should hopefully be fixed by moving the hosting to GitHub.
=> Use GitHub prebuilt URL

ci/travis/nightly_deploy.sh
This fixes the failures of the nightly builds which failed to upload because indiegames does not accept FTP connections anymore.
=> Compile curl with SSH support for nightly deploy

code/anim/animplay.cpp, code/anim/animplay.h, code/graphics/generic.cpp, code/mission/missionmessage.cpp
Two commits here. The first removes a condition from `message_mission_free_avi()` that didn't seem to serve a useful purpose. The second is the real meat of the PR and so I'll copy its description here:
When streaming an ANI file, first `anim_load()` is called, then `init_anim_instance()`. The latter increments the animation's `instance_count`. If `anim_free()` is called on an animation that still has instances, it refuses to free the animation. `generic_anim_unload()` first called `anim_free()`, then `free_anim_instance()`.
The fact that ANI files would ever unload at all seems to be because some code would unload twice. I can only assume that, combined with the fact that the bug only applies to ANI files, explains how this bug went undetected since November of 2009 (commit …
=> Fix unloading streaming ANI files.

code/tracing/FrameProfiler.cpp, code/tracing/FrameProfiler.h
The old code is not able to handle multi-threaded events so this change
simply filters out all the events that originated from another thread.
This fixes an Assertion caused by an invalid event.
=> Discard non-main thread events for the frame profiler

fred2/orienteditor.cpp
This could happen if the user enabled "Point to" and selected "Object"
without having an object selected. This can only happen when there is
only one object in the mission so it's only a minor bug but still
something worth fixing.
=> Fix invalid indexing in object orientation editor

code/graphics/opengl/gropengldraw.cpp, code/graphics/software/FSFont.cpp, code/graphics/software/FSFont.h, code/graphics/software/NVGFont.cpp, code/graphics/software/NVGFont.h, code/graphics/software/font.cpp
This fixes weird misplaced special characters since the TTF strings
weren't rendered at the right position. This should fix that.
This fixes an issue reported [on the forums](http://www.hard-light.net/forums/index.php?topic=93685.msg1850724) by Novachen.
=> Correctly apply scaling to TTF rendered strings

fred2/orienteditor.cpp
From issue #1400, the `IS_VEC_NULL` macro should be used because comparing floating points to zero is not accurate in all situations.
=> use IS_VEC_NULL for floating point safety, plus a few minor touchups

code/parse/sexp.cpp
This does a few things:
1) Adds the ability to specify a plain old string as the debug message, instead of requiring it to be an in-mission message (it looks like Karajorma tried to do this but used the wrong method)
2) Makes the sexp description a little more clear
3) Removes the "(optional)" descriptor for the second argument because it isn't actually optional
Also, I removed an extra period in one of the other sexp descriptions.
=> minor enhancements to the debug sexp

code/def_files/main-f.sdr
This reapplies the fix from https://github.com/scp-fs2open/fs2open.github.com/commit/8e0304a5, which got overwritten at some point.
=> Fix bug in normal map rendering

code/mission/missionparse.cpp
The hook wasn't firing correctly for each ship of an arriving wing, apparently ever since my previous fix in 81d18573.
=> Fixed $On Ship Arrive hooks not firing on wing arrivals

.travis.yml, appveyor.yml, ci/appveyor/build.ps1, ci/appveyor/test.ps1, ci/travis/check_release.sh, ci/travis/ftp_deploy.sh, ci/travis/release.sh
Any branch starting with "test/" will cause test builds to be compiled
and uploaded to fs2downloads. This will only work for the main
repository since the secure variables for the FTP credentials only work
for that repository.
Once this is merged I will add a short explanation to our wiki so that other
people can also use this functionality. Since this only works for the main
repository it shouldn't cause any bandwidth or storage issues since only a
few people have push access to the main repository.
=> Add support for building test builds on the CI servers

code/mission/missionparse.cpp, code/ship/ship.cpp
In the bitset flags PR #775, the `no-collide` ship flag was mistakenly changed to `no_collide`.  (This was probably because the equivalent ships.tbl flag was `no_collide`.)  As a result, this flag is not recognized in missions created with older versions of FRED, as noted in #1425.
I added code to check both variants of flag in both ship parsing and mission parsing.  This should not only fix the regression bug but also guard against typos in ships.tbl.
=> for backwards compatibility, check both no-collide and no_collide

code/missionui/missionweaponchoice.cpp
When loading the mask file fails, correctly report which file we were trying to load.
=> Fix error message for failure to load mask file in weaponloadout

code/io/joy_ff-sdl.cpp
`SDL_HapticStopAll` stops all effects, including the spring effect so the
joystick goes limp after one mission (`joy_ff_stop_effects` gets called at
the end of each mission).
This restarts the spring effect which should fix that issue.
This fixes #1417.
=> Restart spring effect after stopping all FF effects

code/io/joy_ff-sdl.cpp
This was suggested by taylor on the forums and should match the previous
values more closely.
=> Lower Afterburner force feedback effect strength to previous levels

code/ai/aicode.cpp, code/network/multimsgs.cpp
I noticed that there was one line in #922 where two flags were checked using the comma operator.  This is incorrect as the comma operator evaluates both expressions but only returns the value of the rightmost expression, resulting in only one flag being checked.  This PR fixes the Assert by copying the same condition as another Assert elsewhere in the file.
This PR is actually a no-op because the problematic code is commented out, but one never knows when it might be used again.
=> fix typo in AI flag conversion

code/asteroid/asteroid.cpp
If the asteroid split rules were used and the asteroid speed happened to be 0 (for example if the field has an average speed of 0), the code would try to normalize a null vector. Now, a random vector is chosen in those cases.
=> Fix for a null vector normalization

code/osapi/dialogs.cpp
It serves no purpose there since it's a message specifically designed to
be seen by modders and most times the stack trace doesn't even contain
useful information since there are no debug symbols present.
=> Remove stack trace from warning dialogs

cmake/cpufeatures.cpp, cmake/toolchain-msvc.cmake
Also adds AVX2 autodetection so that AVX2-capable processors will generate AVX2 projects by default. To my surprise, there is actually a noticeable performance increase between AVX and AVX2 builds.
With the help of @TRBlount (he runs at a higher resolution than I do), I generated this graph showing the FPS differences (running Icarus as the benchmark):
The speedup appears to be related to models loading faster the first time they appear.
=> Add AVX2 to the list of supported MSVC compiler optimizations.

code/def_files/post-f.sdr, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropenglpostprocessing.h, code/parse/sexp.cpp, code/scripting/api/objs/graphics.cpp
FotG needs a tint shader for a feature; basically toggle screen tinting
when a key is pressed as a visual indicator of which mode your ship is
in. Was previously done in a custom shader.
=> Add colour-configurable tint shader

code/anim/packunpack.cpp, code/graphics/opengl/gropengltexture.cpp, code/graphics/software/FontManager.cpp
Currently, the graphics code does some color remapping on 8
bit-per-pixel textures since those textures use special 4-bit pixel
values. These changes move that conversion out of the graphics code and
into the image loading/font bitmap creation code.
The reason this is needed is because this conversion breaks 8-bit
textures that try to use the full range of colors. I need to do exactly
that for moving the cutscene renderer to our generic rendering interface
which I can't do at the moment since the existing color conversion
corrupts the video data.
I have tested this with retail data and could not find any visual
changes after applying these changes.
=> Move 4 bit color conversion out of graphics code

code/weapon/beam.cpp
`beam_pause_sounds()` "pauses" looping beam sounds by setting their volume to 0; `beam_unpause_sounds()` "unpaused" by calling `beam_recalc_sounds()`, which only set the volume correctly when -no_3d_sound is set; 3D sound updates the sound's position without changing its volume. This PR just makes `beam_unpause_sounds()` perform the inverse operation of `beam_pause_sounds()` if 3D sounds are enabled.
=> Actually unpause 3D beam sounds correctly.

code/object/object.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Adds a new "+Pulse Interval:" countermeasure field that enables the new behavior; all countermeasures that don't have this field defined still use the old behavior of the global frame counter.
This changes countermeasure logic quite a bit, but I attempted to mitigate performance implications by re-using an existing traversal of the object list in order to build the list of active countermeasures each frame. If any countermeasures are actively pulsing in a frame, the object list is traversed again, looking for homing weapons. Each homing weapon then goes through the active countermeasure list and checks to see if it got decoyed. Most of this central logic is unchanged from the old behavior, although no longer separated into two functions, and it should be more efficient since it's using a …
=> Allow countermeasures to pulse at regular intervals instead of globally.

code/weapon/weapons.cpp
If we rely on uninitialized values, we're likely to wind up with countermeasures that are only ever active for a single frame.
=> Explicitly initialize cmeasure_timer_interval to 0.

ci/travis/before_script.sh
The previous command simply created a tar with a tar.gz ending which is
wrong. This fixes that.
=> Actually compress the source archive

code/io/joy_ff-sdl.cpp
This adds an `fs2_open.ini` option for specifying the global scale of the effect strengths. This uses the global gain feature of SDL2 so if that is not supported then the config option will have no effect and a release warning will be displayed.
=> Add config option for setting the FF strength

code/globalincs/version.cpp, code/globalincs/version.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, test/src/globalincs/test_version.cpp, test/src/mod/test_mod_table.cpp, test/src/source_groups.cmake, test/test_data/mod/correct_targetted_version/data/tables/test-mod.tbm, test/test_data/mod/future_targetted_version/data/tables/test-mod.tbm, test/test_data/mod/mod_support_test/data/tables/test-mod.tbm
This adds a small system for letting a mod specify which version of FSO
was designed for. That would allow us to introduce code which would
normally break backwards-compatibility by putting it in an if block
which checks if the mod supports the FSO version which ontroduced the
behavioral change.
There is currently no code which uses the new functions yet so I added a
few tests to verify that the options do what they are designed to do.
This fixes #1389.
=> Add mod table setting for specifying targetted FSO version

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp, code/parse/sexp.cpp, code/scripting/api/objs/graphics.cpp, code/ship/ship.cpp, code/ship/ship.h
The previous system used naked pointers which probably worked fine but
this should give us some extra memory-leak security.
@MageKing17 `ship_info::clone` is only used by the ship template feature.
Is my assumption correct that this will always be called before the HUD is
parsed? If not then the previous code is invalid and needs to be fixed. Otherwise
this is a simple cleanup PR which does not need to be in 3.8.
=> Use unique_ptr for storing HUD gauge pointers

code/bmpman/bmpman.cpp
The code would have displayed the warning but didn't actually set the
flag to let the rest of the code know.
=> Fix bug in texture array detection code

code/menuui/readyroom.cpp
When switching to a previously completed campaign, the game will currently attempt to make further progress due to the existing campaign savefile, which is obviously not possible.  This PR deletes the old campaign savefile (which is retail behavior) and sets the next mission to the first in the campaign.  This way, the player can start the campaign afresh.  Pilot stats are not modified.
This PR fixes Mantis #3174.
=> toss out the campaign savefile if we are restarting a previously finished campaign

code/bmpman/bmpman.cpp
The code did not use the right method for calculating the required size
of the memory. This was never noticed before because the old OpenGL
texture loading code only used 16-bit textures for interface data but
the new code uses 32-bit textures which exhausted the available memory.
This was found and reported by @chief1983.
=> Fix memory allocation in tga loading code

code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropenglstate.cpp, code/graphics/opengl/gropenglstate.h, code/graphics/opengl/gropengltexture.cpp, code/graphics/opengl/gropengltnl.cpp
This introduces a new function in the OpenGL state tracker which
combines setting the active texture unit and enabling a texture. The
reason this is a good idea is that this new function can filter out
unneeded calls to glActiveTexture if the texture is already enabled on
that specific unit. This happens very often when rendering several
submodels of a model which share their textures.
This is unlikely to yield significant performance improvements but
avoiding unneded OpenGL calls is always a good idea.
=> Avoid redundant glActiveTexture calls

code/parse/sexp.cpp, code/parse/sexp.h
Surprised nobody else has added this yet.  From the help text for this sexp:
> Checks whether the specified ships are currently docked.  This sexp is different from has-docked-delay, which will return true if the ships have docked at any point in the past.  The has-docked-delay sexp checks the mission log, whereas the is-docked sexp examines the actual dockpoints.
=> add is-docked sexp

code/graphics/opengl/gropengltnl.cpp
I changed those lines in another PR and forgot to revert these before I
submitted it. This will fix the OpenGL errors that appeared when shadows
were enabled.
=> Readd accidentally removed OpenGL calls

code/parse/sexp.cpp
When the OPF_NUMBER and OPF_POSITIVE behaviors were made more robust, it exposed a latent bug in the play-sound sexps.  These had OPF_POSITIVE where they should have had OPF_NUMBER.  With this fix, sounds can now play from all coordinates, positive or negative.
=> fix negative coordinates in play-sound-from-x

code/parse/sexp.cpp
There is a bug where, when displaying an error message with a sexp node that contains a variable, the code will trigger an Assertion in the process of printing the error message.  This is because it tries to transcode the sexp variable from name to index, when that has already been done further up the pipeline.  This fixes that by adding a quick test to see if the expected variable name is an integer.
=> fix Assertion in sexp error reporting

code/parse/sexp.cpp, code/parse/sexp.h, fred2/sexp_tree.cpp
Add `string-concatenate-block` and deprecate `string-concatenate`.  The new sexp is a better design since the destination variable appears first in the argument list and the sexp allows an unlimited number of concatenations (subject to length limits).  The old sexp was cumbersome for doing more than one concatenation at a time.
=> add string-concatenate-block sexp

code/parse/sexp.cpp, code/weapon/emp.cpp
Back when I added the "same emp time for capships" flag in SVN r9540, I neglected to multiply the EMP time by 1000, as the EMP disruption time for fighters is specified in seconds but the time for capships is specified in milliseconds.  So, using this flag would cause capships to suffer EMP disruption for almost no time at all.
This PR fixes that, and also extends the explosion-effect sexp to specify this parameter.  And I also cleaned up the fireball section by calling eval_num(n) just once instead of several times.
=> make "same emp time for capships" actually work

code/mission/missionlog.cpp, code/parse/sexp.cpp, fred2/sexp_tree.cpp
The `time-docked` and `time-undocked` sexps will cause FSO to freeze unless you know what you're doing, so this PR fixes some gotcha areas.  Inspired by The E's rant on Discord which, while not correct about `OPF_POSITIVE`, did indicate some areas for improvement.
1) Set the default "number of times docked" argument to 1 when the sexp is created in FRED, same as with the `has-[un]docked-delay` sexps
2) Catch any <= 0 counts when the sexp is called in FRED and set them to 1.  (This was done for other sexps which used `mission_log_get_time_indexed`, but was not done for `time-[un]docked` for some reason.)
3) Add an Assertion to `mission_log_get_time_indexed` as a last resort to guard against invalid counts.
Also, I merged `sexp_time_docked` and `sexp_time_undocked` since the functions were …
=> several fixes to time-docked and time-undocked

code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h, code/graphics/render.cpp, code/graphics/render.h
Since this code is the same for all possible graphics backends it can be
moved outside the OpenGL implementation to simplify that code.
=> Move immediate mode rendering into generic graphics code

code/stats/medals.cpp
As requested by Admiral Nelson here:
http://www.hard-light.net/forums/index.php?topic=93704.0
Already tested by him, and it works.
=> add field for setting the hotspot index of the exit button in the medals screen

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h, code/render/3d.h, code/render/3dsetup.cpp, code/ship/shipfx.cpp, code/ship/shipfx.h
The function implementations were empty anyway and the code that called
them wasn't used anymore.
=> Remove graphics functions for explicit clipping planes

code/graphics/opengl/gropenglpostprocessing.cpp
If a 32-bit color shadow framebuffer is not supported this will first
try to fall back to 16-bit and if that still doesn't work it will
disable shadows completely. This should fix the rendering artifacts
reported on the forums here:
http://www.hard-light.net/forums/index.php?topic=93867.msg1854164#msg1854164
The 16-bit rendering may look a bit worse but it's better than nothing.
=> Add proper fallback path for unsupported shadow framebuffer

code/graphics/opengl/gropengltexture.cpp
The PCX loader requires this or else the data isn't loaded correctly.
This matches what the code did before the texture array merge but it
only does it for PCX textures now since the other formats handle 32 and
24 bits per pixel correctly.
This fixes #1472.
=> Only use 16 bit-per-pixel for PCX data loading

code/graphics/opengl/gropengl.cpp, code/pngutils/pngutils.cpp, code/pngutils/pngutils.h
This was requested by @AxemP for improving the usability of FSO
screenshots. This will remove the need to convert the TGA files to PNG
before uploading them to an online image hoster.
=> Use PNG instead of TGA for saving screenshots

code/graphics/matrix.cpp, code/graphics/opengl/gropengltnl.cpp
This restores the behavior from before the matrix system changes. The
observed behavior is more or less the desired behavior sinde setting the
2D projection matrix resets the model matrix stack but it happens to
work with the previous movie code since the 2D matrix is not set if no
perspective projection matrix was set before. This would need to be
fixed if the movie player should ever work within a mission but for now
this will fix the reported bug.
=> Restore 2D matrix setting behavior

code/graphics/matrix.cpp
This fixes a CTD when FRED is started since the graphics function
pointers are not valid at that point which causes a null pointer
dereference when starting FRED. This fixes that by checking if the
graphics system has been initialized before calling that function.
This fixes #1483.
=> Ensure that viewport setting calls are valid

code/network/multimsgs.cpp, code/ship/ship.cpp, code/ship/ship.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Shield impact sounds now re-use the shield quadrant calculated by the collision code instead of naively recalculating based on global hitpos, allowing the hull impact sound to play if the shot pierces shields or was fired from within the shield mesh, and simplifying the relevant calculations in the process.
=> Make shield impact sounds more intuitive.

code/ship/ship.cpp
The code probably tried to check if the sound is available but since the
sounds vector is not long enough if the sound is not specified in the
table it would cause an out-of-bounds failure if the sound was missing
from the table. Furthermore, the current code would only have worked if
the sound was preloaded since the id is -1 until the sound is loaded for
the first time.
=> Fix out-of-range vector access in ballistic sound code

code/gamesnd/eventmusic.cpp
The condition of an assertion doesn't exist in a release build, and assertions should never be used for bad data anyway.
(Technically a regression caused by commit c28989e1218117805cdcac02d56002f7f334a01a, although an `Int3()` on bad data isn't any better, but at least it did the skipping in release builds properly.)
=> Fix misused assertion in music table parsing code.

code/graphics/opengl/gropengltexture.cpp
The function previously used `glFramebufferTexture3D` which caused issues
on the Mesa drivers and probably also with other drivers. This fixes
that by using `glFramebufferTextureLayer` which is the right function for
this use case.
=> Fix OpenGL function usage in opengl_make_render_target

code/radar/radardradis.cpp, code/radar/radarsetup.h
DRADIS blips were originally intended to have decaying alpha. After some changes related to materials, they no longer used the alpha and the original functionality was not in line with what the designer wanted.
The blips now decay in alpha based on the time since they were last swept by the DRADIS.
=> Make DRADIS blips use decaying alpha

code/particle/ParticleSource.cpp, code/particle/ParticleSource.h, code/particle/effects/BeamPiercingEffect.cpp, code/particle/effects/GenericShapeEffect.h, code/particle/effects/ParticleEmitterEffect.cpp, code/weapon/beam.cpp
The particle sources of the beams were missing multiple properties
(direction and impact normals) and the generic shape effect didn't have
any way of controlling how long the source was active. This fixes that
by introducing an effect timing field similar to the single particle
effect.
=> Fix several oversights and bugs in the particle effect code

code/graphics/opengl/gropengltnl.cpp
The texture array changes introduced the default material which is
similar to the passthrough shader but allows to use texture arrays. The
vertex shader is the same as for the passthrough shader so that shader
also supports clipping planes.
=> Fix Assertion failure when rendering clip planes using default material

code/bmpman/bm_internal.h, code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/graphics/2d.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
`bm_init()` now dynamically allocates the `bm_bitmaps` array, and `MAX_BITMAPS` can be changed by the mod table.
After the question was raised as to the possibility of making the BMPMAN limit be a mod table entry (as a way to make Wings of Dawn no longer require custom builds with an increased limit), it was pointed out that the mod table gets parsed before BMPMAN is initialized, which led to me trying out allocating the array at runtime. I've tested it and it *seems* to work.
=> Allow BMPMAN slot limit to be defined by mod table.

code/gamesnd/eventmusic.cpp
For some reason, commit 8b43ed823c39ec6f489450883ccac4ee81e5559f moved the consumption of the "#Soundtrack End" token out of `parse_soundtrack()`, when if a soundtrack needs to be skipped (e.g. because it's in a .tbm, flagged with +nocreate, and the original doesn't exist), it will skip straight past "#Soundtrack End" to reach the next "#Soundtrack Start". It also changed how music tables are parsed so that they'll skip any junk data that happens to be between sections, which is atypical of how tables are parsed. This commit changes both of these things: "Soundtrack End" is once again consumed near the end of `parse_soundtrack()`, and the while loop uses `check_for_string()` instead of skipping to the start of a section.
(For reference, the original [Mantis …
=> Fix music table parsing when a soundtrack needs to be skipped.

code/lab/wmcgui.cpp
The labviewer window background got its width and height mixed up in 6dbd7c34, this fixes that
=> Fix window drawing in the F3 lab

code/scripting/scripting.cpp
This adds empty lines to the beginning of the Lua source passed to the
interpreter so that the interpreter sees the lines in the source as they
appear in the table.
This might slow down parsing a bit since `get_line_num` is quite slow but
it should not be noticable in most instances since the script tables
tend to be quite short.
This fixes #1469.
=> Fix error line reported by Lua Errors

code/graphics/2d.h, code/model/modelinterp.cpp
In previous versions of FSO the GPU data of a model was stored in
various different layouts depending on what data was required for
rendering that model. Since the transform batching code was added to the
model loading code this wasn't the case anymore since all data had to
use the same vertex stride even if the data wasn't used.
This made these changes possible where a standard C-struct is now used
for managing the layout of the data in GPU memory. This makes the code
easier to read and also easier to extend in the future since all layout
data is available in the struct.
=> Use a C-struct for managing GPU model data layout

code/network/multi_sexp.cpp, code/parse/sexp.cpp, code/parse/sexp.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h
I split this from #1331 to make reviewing these two changesets easier.
These changes convert all usages of const char* to SCP_string in the
static SEXP arrays so that the dynamic SEXP system can use SCP_strings
instead of having to allocate the strings and then somehow figure out
which strings must be freed at the end of the program.
This also converts the SEXP arrays to vectors so that new SEXP operators
can be added at runtime later.
=> Use SCP_strings and SCP_vectors in SEXP code

freespace2/freespace.cpp
In-mission events (SEXP chains that are used for directives and all mission logic) can sometimes call "training SEXPs", which depend on special variables set in the `game_do_training_checks()` function. However, this function was called near the end of `game_frame()`, well after `mission_eval_goals()` (which processes all mission events). This means that most training SEXPs wouldn't actually evaluate as true until the frame after whatever condition they were checking became fulfilled. This, combined with PR #1388 making the `targeted` SEXP actually use the appropriate variables (`Players_target` and `Players_targeted_subsys`), means that Diaspora's very first training mission's very first instruction (after launching from the launch tube, anyway) could not be completed, because the …
=> Move game_do_training_checks() to be right before goal processing.

cmake/fred_rc.h.in, cmake/generateHeaders.cmake, code/graphics/opengl/gropengl.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/network/stand_gui.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, code/osapi/osregistry.cpp, code/osapi/osregistry.h, fred2/fred.rc, freespace2/freespace.cpp
FSO now allows the window title to be specified via game_settings.tbl, some never-used function arguments were pruned at the same time, and fred.rc now receives version information (for the About dialogue and the title bar) from a cmake-generated header, so the version numbers get filled in properly. Speaking of FRED's About dialogue, it now displays the copyright symbol properly.
=> Window title overhaul.

fred2/fredview.cpp, fred2/mainfrm.cpp
Now that BMPMAN dynamically allocates the `bm_bitmaps` array, and deallocates it in `bm_close()`, which is explicitly called by `gr_close()`, FRED generates an exception on close because of trying to release bitmap handles after `bm_bitmaps` has been deallocated and set to null. This is because `gr_close()` is called by `CFREDView::OnDestroy()`, but the mission textures aren't fully paged out until `CMainFrame::OnClose()` (well, technically, `CMainFrame::OnClose()` calls `CFrameWnd::OnClose()`, which calls `CWinApp::CloseAllDocuments()`, which calls `CDocManager::CloseAllDocuments()`, which calls `CDocTemplate::CloseAllDocuments()`, which calls `CDocument::OnCloseDocument()`, which calls `CFREDDoc::DeleteContents()`, which calls `CFREDDoc::editor_init_mission()`, which calls …
=> Avoid exception when closing FRED related to bm_release().

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/io/keycontrol.cpp, freespace2/freespace.cpp
Can be enabled with the "-bmpmanusage" command-line option, toggled via the debug console, or toggled via a debug/cheat key combo (`+B).
I wrote this while I was working on #1502, and it makes an interesting diagnostic tool (although the fact that framerate isn't displayed during menus means, since it uses the same function, you also can't monitor BMPMAN usage during menus, which limits its utility somewhat). ~~I *may* do some experiments with calling `game_show_frametime()` outside of missions, but otherwise~~ this PR is complete.
=> Add in-game BMPMAN usage display.

code/ai/aicode.cpp, code/cfile/cfilesystem.cpp, code/globalincs/toolchain/clang.h, code/globalincs/toolchain/doxygen.h, code/globalincs/toolchain/gcc.h, code/globalincs/toolchain/mingw.h, code/globalincs/toolchain/msvc.h, code/graphics/generic.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/paths/nanovg/stb_image.h, code/hud/hudartillery.cpp, code/inetfile/cftp.cpp, code/menuui/credits.cpp, code/mission/missionhotkey.cpp, code/model/modelrender.cpp, code/network/multi_pxo.cpp, code/parse/sexp.cpp, code/scripting/ade.cpp, code/scripting/api/objs/order.cpp, code/scripting/scripting.cpp, code/stats/medals.cpp, freespace2/freespace.cpp
The two new warning types are switch-case fallthrough detection and `sprintf` truncation warnings. I fixed the first type by adding the fallthrough attribute where appropriate. Since `[[fallthrough]]` is a C++17 feature I added detection for other versions of the same attribute.
The second type was fixed by looking at the return value of `snprintf` and if the return value indicated a truncation then a null byte was written at the end of the buffer.
This fixes #1375.
=> Fix new warnings generated by GCC 7

code/cmdline/cmdline.cpp, code/graphics/2d.cpp, code/graphics/2d.h, code/io/joy-sdl.cpp, code/io/joy.h, code/sound/openal.cpp, code/sound/openal.h, code/sound/speech.cpp, code/sound/speech.h
This will output the flags data in a better format than the current
binary format. For determining if the JSON output should be used this
uses an optional parameter for -get_flags. The command line parsing does
not cause an error if a parameter is specified for an option that does
not support them. This way, the launcher can just pass "json_v1" to the
option and an old build will just silently ignore it and use the binary
format.
=> Add support for printing command line flags in JSON output

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/graphics/render.cpp, code/menuui/mainhallmenu.cpp, code/menuui/trainingmenu.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/pcxutils/pcxutils.cpp, code/pcxutils/pcxutils.h, code/stats/medals.cpp, code/ui/window.cpp
This is a bugfix for an issue introduced in 72a797f73219f709a4617480bdf53c86c721491f which broke 8 bits-per-pixel alpha bitmap reading.
This fixes #1516.
=> Fix PCX alpha color correction

cmake/AppRun.in
The previous version used `PATH` instead of `LD_LIBRARY_PATH` which may have
caused some issues if the system is configured in a way that depends on
the value of `LD_LIBRARY_PATH`. It also broke launchers that tried to fix
library issues by changing `LD_LIBRARY_PATH`.
=> Fix LD_LIBRARY_PATH value in AppImage runs

code/sound/sound.cpp
This was an issue since a lot of mods used wrong sounds and after the
FFmpeg changes the code would display a warning for those sounds by
default. This will restore the old behavior of printing the warning to
the log where it is easier to ignore if the mod does not explicitly
support 3.8.0.
=> Only display 3D sound warnings for mods with 3.8.0 support

code/graphics/opengl/gropengl.cpp
If the previous rendering operation left the color mask in any other
state than completely enabled then the clear will only affect the
enabled channels. This makes sure that all channels are enabled before
doing the clear.
This fixes an issue reported on the forums:
https://www.hard-light.net/forums/index.php?topic=94200.msg1859118#msg1859118
=> Enable all color channels before doing a clear

code/graphics/opengl/gropengldeferred.cpp
This fixes another issue reported by Trivial Psychic on the forums.
=> Fix usage of wrong buffer handles in opengl_draw_sphere()

code/parse/parselo.cpp, code/parse/parselo.h, code/parse/sexp.cpp, fred2/management.cpp, fred2/missionsave.cpp
This was an issue since UTF-8 encoded text can contain -128 as part of
an encoding sequence which causes a lot of issues for the parsing code.
I could not find any indication why the original code didn't use null
bytes from the start and I also couldn't find any code that would break
because of this. If anyone knows why this was done like this please let
me know.
=> Replace the special EOF char value with a standard null byte

code/bmpman/bmpman.cpp, code/jpgutils/jpgutils.cpp
The new OpenGL texture data handling code uses different bits-per-pixel values than before which caused a crash when using a JPEG image as the mission load screen. The JPEg decompression code only supports decompressing to 24-bits per pixel but the new code requested 32 bits-per-pixel. `bm_lock` uses either the supplied bpp value (32 in the new code or 16 in the old code) or the true bpp value of the bitmap, whichever is higher. This meant that the new code always tried to lock JPEGs with 32 bits per pixel instead of the supported 24 bits per pixel which caused a crash when the decompression code tried to write out of the bounds of the supplied buffer.
This fixes that issue by always forcing the bpp value to 24 (which is similar to how PNGs are handled).
=> Fix crash when using JPEGs as interface bitmaps

code/fs2netd/tcp_socket.cpp
PLEASE DO NOT MERGE WITHOUT A DECISION BETWEEN PROPOSAL 1 OR 2
This is my second attempt at preventing the SIGPIPE standalone crash on all supported *nix platforms.  I recently discovered that jg18's proposal did not work on Solaris based platforms as they don't currently support MSG_NOSIGNAL or SO_NOSIGPIPE.  After a lot of searching I came up with a couple of proposals.  This one is mostly copied from https://github.com/kroki/XProbes/blob/1447f3d93b6dbf273919af15e59f35cca58fcc23/src/libxprobes.c#L156 and revolves around managing the SIGPIPE restoration differently than the first proposal.  Other proposals involving sigaction() I decided against because of thread concerns.  It may not be an issue today, but the solutions weren't any simpler so I figured I would just stick with a thread …
=> Fix for #470: Proposal 2

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, freespace2/freespace.cpp
always_preload_snd: Is there ever a good reason not to preload mission sounds at this point?
I am not aware of a reason this really needs to be an option at this point.  Seems like a good candidate for pruning to me.
=> Always Preload Game Sounds

code/cutscene/Decoder.cpp, code/cutscene/Decoder.h, code/cutscene/VideoPresenter.cpp, code/cutscene/VideoPresenter.h, code/cutscene/ffmpeg/FFMPEGDecoder.cpp, code/cutscene/ffmpeg/FFMPEGDecoder.h, code/cutscene/ffmpeg/SubtitleDecoder.cpp, code/cutscene/ffmpeg/SubtitleDecoder.h, code/cutscene/ffmpeg/internal.cpp, code/cutscene/ffmpeg/internal.h, code/cutscene/movie.cpp, code/cutscene/player.cpp, code/cutscene/player.h, code/graphics/opengl/gropengltexture.cpp, code/graphics/render.cpp, code/localization/localize.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/source_groups.cmake
This adds support for displaying subtitles embedded in movie files. This
supports files with multiple subtitle streams where each stream contains
the subtitles for one language. When the movie file is opened, the
stream for the currently active language will be used and displayed.
This resolves one of the points mentioned in #1522.
This also depends on PR #1484.
=> Add localized subtitle support to the video player

code/scripting/api/libs/base.cpp, code/scripting/api/libs/mission.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h, freespace2/freespace.cpp
This allows to use the XSTR mechanism in script to make translating
script text possible. This is compatible with the existing XSTR format
so automatic tstrings.tbl generator tools should work fine with this.
This also adds a scripting hook for the mission load screen since that
was requested in #1522.
This resolves points 2 and 4 of #1522.
=> Add support for translating strings in scripts

code/def_files/main-f.sdr, code/def_files/main-g.sdr, code/def_files/main-v.sdr, code/graphics/opengl/gropengltnl.cpp, code/graphics/opengl/gropengltnl.h
This changes the batched transform code so that instead of using `discard`
in the fragment shader it uses the built-in clipping capabilities of
OpenGL for removing invisible sub models. This improves performance in
GPU-limited scenes by ~1ms if shadows are enabled.
=> Use built-in OpenGL clipping planes for model transforms

code/sound/speech.cpp, code/sound/speech.h
The previous code could only handle ASCII data correctly but this new
code is also able to handle UTF-8 data correctly by using the Windows
API function `MultiByteToWideChar`. Since the conversion only happens in
Windows-only code this is not a portability issue.
This fixes an issue reported on the forums where non-ASCII text was not
spoken correctly by the TTS system.
=> Convert speech text properly to wide string

code/sound/ffmpeg/WaveFile.cpp
`SOUND ==> Could not open wave file 2ndRDeath.ogg for streaming. Reason: File not found.`
is much more helpful than
`ASSERTION: "file_path && strlen(file_path)" at cfile.cpp:831`
=> Log a proper error message if WaveFile::Open tries to load a missing file

freespace2/freespace.cpp
Fix for #1541.  Tested to work when run via wxLauncher, Finder, open, and terminal after entering my FS2 data directory.  Please inspect for string and any necessary const adjustments, as again, this definitely isn't my daily language, and the gist of the code was basically from the internet.
=> Only change directory on MacOS when parent process path is /sbin/launchd.

code/graphics/opengl/gropengldeferred.cpp
This should be the correct way to set the combined depth/stencil buffer.
This has not been tested yet since I do not have a GPU which causes
these issues.
This fixes #1555.
=> Use correct attachment for depth/stencil buffer
