scp-fs2open/fs2open.github.com

code/hud/hudconfig.cpp
The first issue is that if a gauge isn't found it will fail to parse any remaining gauges in the file. The second issue is that when saving the preset the game uses translated strings for the gauge name but when loading the preset it uses untranslated strings.
This should address both issues while keeping the original purpose of the changes as well as not breaking existing presets or requiring any mod changes.
Ref: http://scp.indiegames.us/mantis/view.php?id=3099
=> fix parsing issues with hud color presets

.github/workflows/post-build-release.yaml
Auto-trigger in the Post-Build-Release workflow wasn't firing because the workflow inherited its caller's `github.event_name` of `push` instead of the expected `workflow_call`.  This changes it so that either event type will fire the auto-trigger in case github decides to change things.
=> Autotrigger on either workflow_call or push event.

code/mission/missioncampaign.cpp
Certain campaign-related functions would run even when the game was not in campaign mode (e.g. when playing in the tech room).  Normally these would be benign, but with a new pilot or with a skipped mission, the current campaign mission would be -1 and a crash would occur.
Should fully fix #4412.
=> more fixes for the skip-training-mission crash

code/parse/sexp.cpp, code/starfield/starfield.cpp
The previous way to clear a skybox was to set it to "default", and if the mission had no skybox then it would be cleared.  The skybox code can correctly handle the lack of a skybox, but if you pass an empty string to the skybox preloader it fails with a file not found error.  This fixes the preloader, and also adds "none" as an explicit no-skybox parameter.
=> fix clearing a skybox model when it isn't the mission default

code/ship/ship.cpp
Updates the `show-ship` function to account for team colors. Also, cleans up the function a bit. Tested and works as expected. Fixes #4435
=> Fixes Team Colors not working with `show-ship`

code/ai/aigoals.cpp
This goal was missed in `ai_remove_goal_sexp_sub`, so add handling for it.  Also make the error message clearer in case another goal is missed in the future.
~~In draft status until it can be tested by Durandal.~~  Tested and verified.
=> fix crash when removing form-on-wing

code/parse/sexp.cpp
Another bug discovered by Durandal.  The message sender was a variable containing an invalid value, and the game crashed.  This handles it more gracefully.
Tested and verified.
=> better handling of invalid message sources

code/io/keycontrol.cpp
Tests with standalone multiplayer builds revealed that the server would seg fault if a player tried to switch secondaries if the ship did not have secondaries. Tests with standalones showed this fixed the bug. Thanks to @chief1983 for the bug IDing and the fix code.
=> Fix Seg Fault on Standalones with Safer Check for Secondaries

code/mission/missioncampaign.cpp
As noted in #4412, it's possible for `Campaign.current_mission` to be -1 even in campaign mode.  This explictly checks for that.
=> even more fixes for the skip-training-mission crash

code/ship/ship.cpp
Okay so previously, if a target goal was not valid the code was
`strcpy(outbuf, XSTR("no orders", 495)); `
but then it was changed to
`outbuf += XSTR("no orders", 495);`
So it would instead append the "no orders" instead of properly replace the whole string. Looks just like a copy and paster oversight, since all the other text appends the name of the target with the order.
This PR correctly replaces, rather than appends that text. Fixes #4345
=> Fix AI Goal Display Strings

code/osapi/outwnd.cpp
Small refactoring of the debug filter, needed as a prerequisite for #4448.
=> set up debug_filter.cfg to have default filters that can be turned off

code/osapi/outwnd.cpp, code/scripting/api/LuaPromise.cpp, code/scripting/api/libs/async.cpp, code/scripting/api/libs/mission.cpp
Log when the context is created, completes, and is aborted.  Adds insight for the situation described in #4432.
=> add some logging to waitAsync

code/hud/hud.cpp, code/hud/hudbrackets.cpp, code/hud/hudlock.cpp, code/hud/hudtarget.cpp, code/playerman/playercontrol.cpp
A comprehensive fix for the `target_is_dying` variable.
Retail expected this variable to be set to -1 when the player target had died, but that assignment was only on the player struct reset.  So this adds an assignment when it's been determined that there is no current valid target.  I also added comments and made sure the logic was consistent on all the checks.  There is a little bit of redundancy on the checks, but honestly that's probably better in c++.  But there is more than one way to fix this, so I'm open if anyone feels strongly that it should be done another way.
Closes #4393
=> A comprehensive fix for the `player.target_is_dying` variable.

code/menuui/optionsmenu.cpp, code/missionui/missiondebrief.cpp, code/missionui/missiondebrief.h
If the player exits the game from the options menu while at the debriefing screen after completing a mission during a campaign, then auto-accept the mission outcome.
Has not yet been scrutinized/tested.
Should fix Issue #4309.
=> Auto-accept completed campaign mission before exiting game from debriefing screen

code/mission/missionparse.cpp, code/parse/sexp.cpp, code/parse/sexp.h, fred2/campaigntreewnd.cpp, fred2/fredview.cpp, qtfred/src/mission/Editor.cpp
Sync the "mission save" and "error reporting" versions of the SEXP variable string.  Also use `stuff_sexp_text_string` to print the "bad node" token rather than `Sexp_nodes[bad_node].text`, so that a human-readable token is displayed instead of a magic number like 26.
Related to #4226, as the generated error message is formatted differently enough to be confusing.
=> refine SEXP error reporting

code/pilotfile/csg.cpp, code/pilotfile/pilotfile.h, code/pilotfile/plr.cpp
Should fix #3321. Tested with the provided save files and the defective value was clamped as expected. 
Also tried forcing a few wrong values by manually editing a JSON pilot file and playing it in the RC, which saved the wrong values to the campaign file, and then loaded the same pilot/campaign in my dev build, resulting in the values being corrected.
=> Clamp values to their correct ranges when loading and saving pilot and campaign files

code/hud/hudreticle.cpp
And make an assertion more explicit, just in case.
Fixes a crash for observers with certain ship table setups.
=> Prevent a crash by exiting here

code/model/modelread.cpp
Gun objects must be an immediate child of their base object. Also replace the confusing `parent` `physical_parent` naming scheme that is literally only used right here.
Fixes #4204
=> Warn on mismatched turret objects

code/inetfile/cftp.cpp, code/inetfile/chttpget.cpp, code/network/chat_api.cpp, code/network/psnet2.cpp, code/network/psnet2.h
Fixes network connectivity issues on macOS due to a mismatch of struct sizes, which macOS appears to be rather particular about. Successfully tested on macOS, Linux, and Windows.
=> address issues causing network connectivity failures on macOS

freespace2/freespace.cpp
Move `snd_aav_init` to `game_level_close` so that it is always called when the mission exits, not just in the `GS_STATE_GAME_PLAY` state.
Fixes #4468.
=> reset the adjusted volume when the mission closes

code/missionui/redalert.cpp
This range check is to ensure that the ship's hull is in a valid range, so it should therefore check that the hull is less than the max strength, not less than the current strength.  This was inadvertently changed in 593be42e66 and a04e83ab01, but retail behavior is to set the exact hull from the previous mission.
Tested for both regular ships and delayed-arrival ships.  Fixes #4472.
=> use proper bounds check when bashing hull in red-alert

code/network/psnet2.cpp
"addr" is optional and allowed to be null, so we've got to check it before zeroing.
=> fix memset() on nullptr in psnet_get_addr()

fred2/fred.rc, fred2/sexp_tree.cpp
Makes these changes in FRED's Events Editor:
1. Ensures the keyboard shortcuts for Paste/Add-Paste won't trigger a crash if the clipboard is empty.
2. Remove "Delete" from UI as a keyboard shortcut for "Delete Item". It never worked, and as explained in the related issue, it shouldn't be made to.
Intended as a very limited partial fix for Issue #4405 until someone can do a proper rewrite of `sexp_tree::right_clicked()`.
=> Provide a limited partial fix for FRED keyboard shortcuts

fred2/orienteditor.cpp, fred2/orienteditor.h
Due to rounding and conversion approximations, it was possible for FRED to think the position and/or angle was modified when no such modification had occurred.  This could result in erroneous updates.  In the case of angles this could result in a group of ships being assigned the wrong orientation.
Follow-up to #2614.
=> fix erroneous position/angle modification

code/ai/aicode.cpp, code/hud/hudtarget.cpp, code/network/multi_ingame.cpp
An assert in `obj_team` is triggered very rarely, and we have yet to get a minidump or catch it in a debugger.  So I went through all the instances of `obj_team` and I tried to add checks or asserts that incoming objects were in fact what they should be (mostly ships).
There was one specific instance where already existing assertions should have been run before checking the object's team, on a code path having to do with friendly fire, which I hope is the cause.  Since I had to change that logic around, the indentations change and this PR looks a lot larger than it is.
In draft as it waits for testing, to make sure I didn't go too strict on the assertions.
=> Do our best to avoid invalid types in obj_team

code/network/multi_obj.cpp
Move this nprintf over because we only remove the data if it exceeds the max amount, not if everything fits. 
This improves clarity a lot in a difficult section of code.
=> Fix an nprintf being in the wrong logic branch

code/math/vecmat.cpp
An oversight from #4417. This will prevent ships from spinning themselves out of control under certain circumstances. That fact that ships are even *trying* to spin themselves out of control uncapped or otherwise is due to this dubious, but retail logic https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/ai/aicode.cpp#L1300. I am confident this part could be re-written to something more sensical and less framerate sensitive, but that's technically a separate issue. It does at least seem to be behave like it did before the aforementioned PR.
=> Cap bank velocity in AI turning

code/ai/aicode.cpp, code/parse/sexp.cpp, code/physics/physics.cpp, code/physics/physics.h
Two things: split `ai_control_info_check` into `ai_control_info_flags_upkeep`, which keeps track of the flags and sets or resets them accordingly and `ai_control_info_apply` which then uses those flags and sets the directional values. `ai_control_info_flags_upkeep` is then made unconditional, even if the AI mode dictates it should not act on maneuver overrides, keep track of the flags and ensure they set and reset properly. Additionally, `player-not-use-ai` completely resets maneuvers, preventing any accidental 'leakage' of its flags. Also makes clear that `PF_NO_DAMP` is only used for maneuvers. 
This is possibly, but not certainly, related to #2157
=> Fix some bugs with maneuvers

code/io/timer.cpp, code/io/timer.h, code/scripting/api/libs/time_lib.cpp, code/scripting/api/objs/movie_player.cpp, code/scripting/api/objs/time_obj.cpp
The movie player code was missing some important functionality, in particular:
1) There was only one timing method to get real-time elapsed time, which was not suitable for pausing or time compression
2) There was an improper cast for the FPS property, causing a script error
3) The `getSeconds` method lost precision during casting
This patches those deficiencies.
=> some fixes for playing movies via script

code/parse/sexp.cpp
Enforce the restriction that using `validate-argument` and `invalidate-argument` with container arguments isn't supported.
However, `validate-all-arguments` and `invalidate-all-arguments` apply to container arguments as well.
These constraints are listed in the [containers forum thread](https://www.hard-light.net/forums/index.php?topic=98209.msg1914261#msg1914261) (see Feature 6), which is currently the only documentation for containers.
=> Fix type checking and FRED help for containers in special argument lists

code/gamesnd/eventmusic.cpp, code/mission/missionmessage.cpp, code/missionui/missiondebrief.cpp
When the code checks for the existence of an audio file, be sure to check all relevant extensions.
This fixes #4495.  Tested with both ST:R personas as well as the Vasudan persona.
=> check all possible extensions for audio files

code/ai/aicode.cpp
The previous version of the fix only included ships because it was believed to be the object that a ship used to be guarding.  Now it's clear that this is an object that the ship is currently targeting *after* guarding something.
So remove the UNREACHABLE and manually check the valid object types with an assert.  Then only continue with the function if it is the right target type.
=> Include more valid object types in this check

code/scripting/lua/LuaFunction.cpp, code/scripting/lua/LuaReference.cpp, code/scripting/lua/LuaReference.h, code/scripting/lua/LuaValue.cpp, code/scripting/lua/LuaValue.h
Fixes #4287.
Until now, when we pushed values to the Lua stack from C, we _never_ checked that the stack allocated by the lua interpreter had space available, let alone reserve new space.
This PR now adds checks on each push to the stack. While this might slightly degrade performance, it is a necessary check.
To avoid unnecessary checks, there is infrastructure in place to pre-reserve multiple stack spaces and pass the information about guaranteed sufficient stack pre-allocation to the value push, enabling omission of the check in these instances.
=> Ensure sufficient stack size for Lua values

code/parse/sexp.cpp
Absent ships or wings should simply be skipped instead of stopping.
=> Bugfix for not present ships in `clear-goals`

freespace2/freespace.cpp
We must do sexp_shutdown() before we clear the scripting state. Otherwise FSO will try to destroy the LuaFunction references still held by the SEXP system, which will cause a crash as the lua state (and thus its function registry) is a nullptr / not allocated anymore by that point.
=> Ensure that SEXP shudown is before script shutdown

freespace2/freespace.cpp
When `mission_campaign_clear()` is called, all persistent SEXP nodes (those used by the campaign) are marked as non-persistent.  When `sexp_shutdown()` was moved in #4503, this caused `Sexp_nodes` to be nullptr when the campaign was cleared, which caused a crash.  This adds checks to prevent the crash.
=> prevent a crash on game exit

code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/sexp_lookup.cpp
SEXP categories will not support more than 256 SEXPs; this is why the CHANGE2 category had to be created when CHANGE got full.  Unfortunately, dynamic SEXPs will count toward this limit, so mysterious errors will occur for the ones whose category indexes roll over.  The problem is not easily fixable, but at least the engine can detect the situation, warn about it, and refrain from adding any problematic SEXPs.
Since too many *total* SEXPs would cause a similar problem, this adds a warning for that case too.
=> prevent too many dynamic SEXPs from breaking the SEXP system

code/scripting/scripting.h
fixes #4504. Hopefully. I'll freely admit my understanding of this area of the engine is spotty, but debug monitoring of the stack allocation showed this to be a source of leaks and the crashing missions are stable now as far as I've tested. More testing of script-eval-num and script-eval-bool heavy missions may be warranted.
=> Clean up the lua stack after EvalStringWithReturn's function creation

code/ai/aicode.cpp
This assert catches any weapon's parent object type, which can include OBJ_GHOST, which is a dead player.  OBJ_GHOST is being encountered in this function using BPC when the player dies via beam weapon and (likely) when the players weapon are hitting an enemy ship at the same time.  Because the player ship can damage an enemy after it is dead, allow for that in this function.
Fixes #4522
=> Add OBJ_GHOST to this assert and add comments

Changelog.md
This is an *incomplete* changelog for 22.2.0, made by reading each commit up to RC5, reading their PRs, reading linked issues, and writing down my understanding of the effective changes. 
I added a new "feature" to the changelog itself: Collapsible subsections, by topic.
I skipped fixes for issues that were added during the 22.2.0 development cycle, as well as CI/build related commits (with the exception of the Mac related ones).  
This is in draft form, since I still need to write up changes from the post RC5 commits, and also because there are changes yet to be committed. 
Reminders for before merging:
=> Preliminary Changelog for 22.2.0

code/object/objectsnd.cpp, code/object/objectsnd.h, code/scripting/api/objs/enums.cpp, code/ship/ship.cpp
Previously the persistent object sound management code would attenuate all script-assigned sounds by engine strength, and would not play them at all if the engine was off.  This fixes the code to only apply that logic if the sound is in fact and engine sound.
There is also a small amount of refactoring.
=> only attenuate a persistent sound by engine strength if it's an engine sound

code/hud/hudparse.cpp, fred2/sexp_tree.cpp
FRED needs to work with any HUD gauge in the table, so don't prune any based on resolution.  Fixes #4517.
This also improves checking for duplicate names in the FRED gauge list.
=> don't prune HUD gauges by resolution in FRED

code/ship/ship.cpp
Other types are possible here because multi deletes the ghost object, at least, that is what I understood from the code and comments two years ago, when I first started looking at respawn bugs.  So it is much better to just ensure that the object is a ship, instead of checking against what it shouldn't be before checking the distance.
Related, but not guaranteed to fix part of #4509.
=> Only check that *ships* have left the mission

code/ai/aiturret.cpp, code/model/model_flags.h, code/model/modelread.cpp, code/ship/ship.cpp, code/weapon/beam.cpp
Add `$Turret Barrel FOV:` option for turrets in ships.tbl, as requested by CP5670.
=> add ships.tbl override for turret fov

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/network/multi_options.cpp
Previosuly, the default object update speed setting for new players was `High`. Many mods, such as Fate of the Galaxy, do multiplayer tests where we have to ensure players are using the highest object update speed, which is LAN. This extra step is cumbersome and prone to players' forgetfulness.
This PR allows mods to set the default multiplayer object update speed for new pilots to mitigate this issue. Tested and works as expected.
EDIT: Closes #4497.
=> Allow Mods to specific default multi update speeds

code/ai/ai.h, code/ai/aicode.cpp, code/object/object.cpp, code/object/object.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
`Ai_flag_names[]`, `Object_flag_names[]`, and `Ship_flag_names[]` all had an associated `#define` containing their length that had to manually be incremented whenever new flag names were added to the list. This commit instead makes the number of flags in the list be computed by simple `sizeof` division, so now adding a new entry just requires adding the entry, rather than remembering to bump a `#define`. Tested in FRED to make sure populating `OPF_SHIP_FLAG` entries still works.
=> Automatically calculate length of flag name lists.

code/ai/aiturret.cpp, code/asteroid/asteroid.cpp, code/hud/hudtargetbox.cpp, code/math/floating.h, code/math/vecmat.cpp, code/math/vecmat.h, code/mission/missionbriefcommon.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/nebula/neblightning.cpp, code/parse/sexp.cpp, code/physics/physics.cpp, code/radar/radarorb.cpp, code/scripting/api/libs/mission.cpp
In #4443, `fl_near_zero` was set to use default epsilon values in the `IS_VEC_NULL` check. In this comparison, epsilon is the wrong threshold because it used to have a much smaller threshold. The fix restores the previous definitions of `IS_VEC_NULL` and `IS_VEC_NULL_SQ_SAFE` by exposing the epsilon value as an optional parameter (similar to how `IS_NEAR_ZERO` used to work. This PR also restores `IS_VEC_NULL_SQ_SAFE` where it was replaced by `IS_VEC_NULL.`
Fixes #4534.
=> Fix False Null MOI warnings

code/graphics/shadows.cpp, code/graphics/shadows.h, code/menuui/techmenu.cpp, code/missionui/missionbrief.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionweaponchoice.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp
Some mods can contain models for which having shadows in the techroom / mission select screen is a problem. This allows to bulk-disable rendering of shadows for some of these categories, such as shadows for weapon selection during the mission briefing.
=> Add options to selectively disable shadows

code/scripting/api/objs/subsystem.cpp
It is possible for a script to call the `fireWeapon` subsystem function passing `wnum` as any integer. 
Down the line, `wnum` ends up passed to `ai_turret::get_turret_weapon_wip`, and could trigger either of those asserts:  
```C++
Assert(weapon_num < MAX_SHIP_WEAPONS);
Assert(weapon_num >= 0);
```
This PR prevents that by giving an error and returning early.
=> Prevent subsystem `fireWeapon` scripting function from triggering an assert

code/scripting/scripting.cpp
#4231 changed the WeaponClass hook in such a way, that if a Weapon Class was required, but the condition itself was called _with no weapon at all_, it'd still evaluate.
This breaks certain mods, such as JAD, which rely upon ``$On Ship Collision:`` with a Weapon class condition to catch and process hits of certain weapons on ships.
=> Fix WeaponClass Script Condition

code/cmdline/cmdline.cpp, code/graphics/shadows.cpp, code/graphics/shadows.h, code/mod_table/mod_table.cpp
This PR allows mods to set a default `Shadow_detail` level in `game_settings.tbl`. ATM, if the `enable_shadows` flag is set then the game will use the `Medium` level.
It is very useful for mods to be able to specify a default level. For example, with FotG we have noticed that if the `High` shadows level looks far, far better then the default of `Medium`, with getting no noticeable FSP difference on our testers range of dedicated graphics cards. Yes, using `shadow_quality` flag will work, but that's a tedious extra step, especially for our testers who are new to FSO. Plus, using a `shadow_qualilty` that overrides if `enable_shadows` is set or not is rather unintuitive for our players.
A boolean check is used because it's far easier to set and check in the mod table code, especially for …
=> Allows default shadow quality to be per mod

code/model/modelread.cpp
As part of the cleanup in preparation for model translation, there was a bit of code review that was actually incorrect.  The calculation of the current step needs to be rounded down, because the step isn't actually complete until it fully reaches the next number.  Rounding the step causes the submodel to jump around in all sorts of weird ways.
Follow-up to #4443.
=> fix stepped rotation

code/mission/missionparse.cpp
Add On Loadout Parse hook that runs during mission parse but before loadouts are created. Resolves #4361
=> Add hook just before loadout parsing

code/scripting/api/objs/ship.cpp
Implements #3070 . Allows getting and setting the ship's persona by index. Tested reading and writing with messages after writing and works as expected. Also testing writing an index that does not exist in messages.tbl. FSO does the same thing with that as it does if it gets an invalid persona from the mission file; it chooses a random persona instead.
=> Implement ability to get and set a ship's persona index

code/network/multi_obj.cpp
This makes servers update player ships more often, even when they are not front and center in front of the player.  This hopefully will cut down on some of the player jitteriness.  Because client player ships have extra latency in a server-based system, they should have been prioritized when the system was changed over between FS1 and FS2.
Testing has occurred, and it is definitely not making anything worse, although our multiplayer testing base is not as scientific these days.
=> Prioritize players in object update

code/mod_table/mod_table.cpp
`$Shadow Quality Default:` allows mods to specify what the default shadow quality should be, given that `-enable_shadows` flag is used. If a mod used this game settings option but the player did not use the `-enable_shadows` flag, then a parsing error would show up.
This PR fixes that bug by reordering two lines. Tested and fix works as expected.
=> Fix setting of `$Shadow Quality Default:`

code/hud/hudparse.cpp
Rather than try to put a sentinel value in *ship_idx if it's null, I've just left it null and put checks everywhere it's used. Nothing ever gets written through *ship_idx so this should have the same behaviour.
=> Fix dangling pointer in hudparse.cpp

code/parse/sexp.cpp
If you define a variable inside a block, its lifetime is confined to that block. So oswpt needs to be lifted into the parent block.
=> Fix dangling pointer in sexp.cpp

code/model/modelanimation.cpp, code/model/modelanimation.h, code/scripting/api/objs/ship.cpp
This enables scripting to change the speed multiplier of any animation. If it is not yet running, the speed change will also affect the animation once it is started.
=> Allow changing Animation Instance speed

code/asteroid/asteroid.cpp, code/debris/debris.cpp, code/scripting/global_hooks.cpp, code/scripting/global_hooks.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp, code/weapon/weapons.cpp
Splits the existing On Death hook into independent hooks for each relevant type.  Adds On Ship Death, On Missile Death, etc.  Also adds On Missile Death Started to complement On Ship Death Started.
Partial fix for #4394; the remainder of the fix will need to be done in the MediaVPs.
=> add new hooks for each object type

code/hud/hudparse.cpp
These options for controlling the locking animation are toggled by `$Reticle Style:` but were otherwise not available to HUD gauges.
=> add missing hud_gauges.tbl options

code/gamesnd/gamesnd.cpp
Follow-up to #3743.  A sound that was originally parsed as empty, but then re-parsed as non-empty, would still have the `GAME_SND_NOT_VALID` flag from the original attempt.  This fixes that by clearing the flag each time the filename is read.
This also slightly moves the `gs->pitch_range` assignment so both functions are consistent.
=> fix overriding of originally-empty sounds

code/scripting/api/objs/ship.cpp
A simple copy of the same function on `ai_helper`, now usable on plain ships too.
=> Script function for `turnTowardsOrientation`

.github/workflows/build-nightly.yaml, .github/workflows/build-test.yaml, .github/workflows/test-pull_request.yaml
Looks like the base GH Actions image got updated (newer Python?) and it now fails to install the older version of py7zr.
=> Fix Mac builds by overriding py7zr version

code/ai/ai.h, code/ai/aicode.cpp, code/scripting/api/libs/mission.cpp
The `test_line_of_sight` can currently provide the closest intersecting distance, but it would be very useful, especially for AI scripting, if this function could also return the signature of the intersecting object. This PR adds that functionality.
Tested and works as expected. Happy to discuss strategies for changing implementation, too. The extra, third return value for object signature was added to `getLineOfSightFirstIntersect` function because that function already returns 2 values. Thus, it will remain compatible with older scripts which only save the first 2 returned values.
=> Allow `test_line_of_sight` to return intersecting object signature

code/ai/aibig.cpp, code/ai/aicode.cpp, code/hud/hudconfig.cpp, code/math/floating.h, code/math/vecmat.h, code/model/modelread.cpp, code/physics/physics.cpp, code/ship/ship.cpp
Floating-point comparisons are tricky beasts.  See this article for a good summary of the issues involved:
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
This PR improves support somewhat, although there are obviously situations in the code (such as comparisons to 0) that should still be addressed.  This PR makes the following improvements:
1) Tightens the threshold on `IS_VEC_NULL` and `IS_VEC_NULL_SQ_SAFE` from 1e-16 and 1e-36 to FLT_EPSILON
2) Tightens the threshold for parsing `turn_time` in POFs
3) Restores the previous implementation of `fl_equal`
4) Adds a dedicated `IS_MOI_VEC_NULL` for moment of inertia values
5) Improves documentation
Follow-up to #4535 and #4443.
=> floating-point followup

code/scripting/api/libs/ui.cpp, code/scripting/api/objs/fictionviewer.cpp
Protects `Fiction_viewer_active_stage` if it reads a stage of -1 (it would have thrown a vector access error because the index is out of range). Also, given a lot of other scripting functions have additional built in error checks, I just added those to the fiction viewer functions.
=> Some extra safety checks for fiction viewer scripts

code/scripting/api/libs/ui.cpp
Fix issue that was missed. This should be ADE_FUNC instead of ADE_VIRTVAR to reflect the generalized functionality
=> This should be func not virtvar

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp, code/iff_defs/iff_defs.cpp, code/iff_defs/iff_defs.h
The original implementation of `ai_good_time_to_rearm` did not revert to being a "bad" time to rearm when the time was up.  This fixes that and adds an AI profiles flag to toggle it.
Also converts `ai_rearm_timestamp` to use the new TIMESTAMP type.
=> fix good-rearm-time bug

code/model/modelread.cpp
While a form of 'backwards compatibility' by including some features but not others might seem helpful, having new features 'interleaved' through the versions *greatly* complicates version checking (note how the check went from 5 comparisons to 1), is practically not very useful, and this situation will worsen with every feature added this way. New features should be placed in the newest version, like most other software.
=> Associate only a single pof version to submodel translation

code/network/multi_pxo.cpp
For help with troubleshooting, list what game/mod PXO identifies this instance is running in the chat lobby stream.
=> prepend PXO game identity to chat lobby window

code/network/chat_api.cpp
A MOTD missing (422) message is non-fatal and should be handled the same as a MOTD end (376) message to prevent the chat connection process from hanging.
=> handle irc motd error to prevent connection hang

code/hud/hud.cpp, code/localization/localize.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/weapon/emp.cpp
EMP is the only text warning that does not use an entry in the strings table (and thus it's the only text warning gauge that mods cannot change and/or translate). This PR adds a string entry for it to allow mods to translate and change the string like all other HUD gauge text warnings.
Also, EMP flash has a hard coded color and strength factor for the flash, whereas generic pain and shield pain have a configurable flash strength factor (shield pain flash is based on shield color, while generic pain is based on damage dealt). This PR also allows modders to change the strength intensity and color following previously established methods.
This PR also fixes a case of "Launch" that fell through the cracks. The function is supplied the translated string, but within the function it does not …
=> Allow mods to change Emp flash color, intensity, and string

code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/hud/hud.cpp, code/hud/hud.h, code/hud/hudets.cpp, code/hud/hudreticle.cpp, code/io/keycontrol.cpp, code/scripting/api/objs/control_info.cpp
This PR adds a new control (By default Alt+L, but it will be unset for existing pilots) which lets the player enable or disable Drop Shadows on the HUD, affecting Text, the main targeting reticle and the background of the ETS gauges. 
<details><summary><b>Click here to see comparison screenshots</b></summary>
Low contrast, no shadows
High contrast, no shadows
Low contrast, with shadows
High contrast, with shadows
</details>
Related: #3712. I'm not sure if we could consider that it closes that FR. IMO there are other possible ways to improve HUD contrast that would be nice to have: 
* Allow HUD elements to be fully opaque (currently even with alpha at 255, they'll be slightly transparent due to how `aabitmap`s work
* Use outlines instead of shadows (This would probably require a specific …
=> Add optional Drop Shadows to HUD

code/parse/sexp.cpp, code/scripting/api/libs/mission.cpp, fred2/fredstubs.cpp, freespace2/freespace.cpp, freespace2/freespace.h, qtfred/src/fredstubs.cpp, test/src/test_stubs.cpp
Allow the variables controlling ship shudder to be independently set using scripting.  Also add new flags to apply the shudder without decay and apply the shudder regardless of camera.
Also change the shudder timestamp to the new style.
=> enhanced control for the global ship shudder

code/globalincs/vmallocator.h, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelreplace.cpp, code/model/modelreplace.h, code/network/multi.cpp, code/parse/parselo.cpp, code/parse/parselo.h, code/ship/ship.cpp, code/source_groups.cmake, fred2/management.cpp, freespace2/freespace.cpp, qtfred/src/mission/management.cpp
This PR adds the basic framework to handle table-defined virtual POFs. These allow modular manipulation and combination of models during FSO runtime.
Right now, only the very basic features (copying submodel model data, renaming submodels, moving submodels, editing some POF header data) are supported, basically only allowing some dynamic kitbashing.
Due to the already large size of the PR, the following planned features will be deferred to a later PR:
- Replacing Submodels
- Processing more than just model data when copying / replacing
- Allow to manipulate turret data
- Allow to manipulate weapon fire point data
- Allow to manipulate glowpoint data
- Allow to manipulate dockbay paths and data
- Allow copying / replacement of said data individually, without needing to copy parent …
=> Virtual / Modular POFs

code/model/modelread.cpp
Profiling shows this taking about 10% of the total time in loading BP's Icarus mission, and the result isn't even read any more!
=> Remove unused and costly checksum during model read

code/ai/ai.h, code/ai/aigoals.cpp, code/ai/aigoals.h, code/ai/ailua.cpp, code/ai/ailua.h, code/globalincs/systemvars.h, code/hud/hudsquadmsg.cpp, code/parse/sexp/DynamicSEXP.h, code/parse/sexp/EngineSEXP.cpp, code/parse/sexp/EngineSEXP.h, code/parse/sexp/LuaAISEXP.cpp, code/parse/sexp/LuaAISEXP.h, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/LuaSEXP.h, code/scripting/api/objs/luaaisexp.cpp
Previously, LuaAI could only use _one_ singular target parameter that had to conform to the OSWPT type.
Now, LuaAI can take any number (including repetitive) of arguments, with the restrictions that all non-target-parameter arguments will be nil if called as a player order, and that they cannot be used within target validation for player orders.
=> Enable LuaAI to use more arguments

code/cfile/cfile.cpp, code/cfile/cfile.h, code/model/modelread.cpp
This function stuffs a string from a file into a buffer and requires that the length of the string be strictly less than the size of the buffer it was going in, so that it could forcibly add a 0 after the end of the string and still fit in the buffer. This is a little more conservative than necessary, since it prevents properly null terminated strings of length, say, 32 from fitting in a 32 buffer, because it wants to add another at the end, and even more problematic if the file is trying to 4 byte align and has padded the string up to 32. 
Having a string equal to the size of the buffer is only a problem if it contains no terminator at all, which an assertion has been added for, and in which case it will simply overwrite the last character, otherwise, it is safe simply to add the …
=> Fix cfread string's handling of null terminated strings

code/cutscene/player.cpp
The Video Player keeps a thread for decoding. When you tell the player to close, all of its data is deallocated, and the decoding thread is closed. While deallocating the data is secured against deleting it multiple times, closing the thread is not. We should check if the thread is still joinable before we just blindly call join on it to prevent crashes. If it's not joinable, we can pretty much just ignore it at that state
=> Prevent closed thread from Video Player from re-closing

code/CMakeLists.txt, code/model/modelanimation.cpp, code/model/modelanimation.h, code/model/modelanimation_moveables.cpp, code/model/modelanimation_moveables.h, code/model/modelanimation_segments.cpp, code/model/modelanimation_segments.h, code/model/modelreplace.cpp, code/model/modelreplace.h, lib/CMakeLists.txt, lib/optional/CMakeLists.txt, lib/optional/COPYING, lib/optional/README.md, lib/optional/include/tl/optional.hpp
In a few chunks of code, namely modular POFs and animations, optionals were needed.
These used more or less janky reimplementations of similar functionality.
This now replaces these jury-rigged solutions with a proper, std compliant reimplementation of optional for C++11.
Similar reimplementations of C++17 STL types for C++11 already exist for other types like std::variant or std::any
=> Implement a proper std::optional alternative

code/scripting/api/objs/weaponclass.cpp, code/weapon/weapon.h
Since Tech model files are not required for weapons, this version exits early and returns false if Tech model does not exist. I partially implemented falling back to the regular POF file if it exists and tech model doesn't, but since in weapons the regular POF file do not have closeup_pos or closeup_zoom defined, it wasn't as good. Thought it was better to stick with just the tech model, which does get those properties defined, as that's what the method is called in the first place.
Resolves #4353
=> Implement renderTechModel() and renderTechModel2() for weapons

code/pilotfile/pilotfile.cpp
If a new pilot manages to gain a rank during the first mission and then decides to replay that mission, the check to reset the rank was accidentally demoting the pilot by two ranks instead of one. Inverting the check and just iterating through the ranks table until the fitting rank can be found fixes this.
This fixes #4614
=> Fix issue with new pilots getting demoted too fast

code/camera/camera.cpp
For subtitles drawn using the `$Show-subtitle base resolution:` feature, text near the side of the screen would get clipped off mysteriously:
The clipping corresponded precisely to the edge of a 4:3 boundary:
This led me to discover that `gr_screen.clip_right_unscaled` was still set for a 4:3 box, rather than a 16:10 box as was expected.  Explicitly setting the clip boundary when setting the screen scale fixes the issue:
For any graphics coders in the know, is this actually the proper fix?
=> fix subtitle clipping

code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
Adds a new game_settings.tbl option: `$Lead indicator behavior`, which can be set to `default`, `multiple` or `average`. 
Also adds a new flag to weapons.tbl: `don't merge lead indicators`
When `$Lead indicator behavior` is set to `default` (or unset), lead indicators act just like in retail, meaning when you link them, only the indicator for the one with the farthest range will be drawn.
When set to `multiple`, a lead indicator is drawn for all primary weapons in range when you have them linked.  
When set to `average`, a single lead indicator is drawn in the average of the position where each of them would usually be drawn.  
Invalid selections will revert to default and give a warning.
When Weapon flag `don't merge lead indicators` is set for a homing secondary, its lead indicator will …
=> New options for lead indicators

code/mission/missiontraining.cpp
Properly check if mission is singleplayer for the `Always_warn_player_about_unbound_keys` game option.
=> Fix conditional for `Always_warn_player_about_unbound_keys`

code/missionui/missiondebrief.cpp
The null terminator was written past the end of the string buffer, which intruded on the next field in the struct.  Fixing this fixes #4635.  Also adjust the string concatenation a couple lines up because it could also write past the end of the buffer.
=> properly account for string sizes in debrief_choose_voice

code/hud/hud.cpp
Discussion starts here: https://discord.com/channels/223511295431933953/722747742996267068/1018264927699476571
=> Allow Autotarget to get new target when current target is deathrolling

code/parse/sexp.cpp, code/parse/sexp.h
This adds SEXPs to simplify angle and direction testing.
One, ``angle-vectors`` simply allows for calculation of an angle between two vectors.
The other, ``angle-facing-object`` returns the angle between the fvec of a ship and the direction from a ship to a target object. This massively simplifies "is ship facing object sufficiently"-checks.
=> Add Angle SEXPs

code/scripting/scripting.cpp
Like #4559 before it for weapons, this fixes the script conditions for ships.  The problem was the same: the script condition would evaluate to true if none of the objects under consideration were ships.  The fix is the same as well.  I checked all the other script condition categories, so no similar bugs should pop up in the future.
Fixes #4637.
=> fix script conditions for ships

code/ship/ship.cpp
Previously, placing a ship that had a long class name might create a default name that was too long and thus trigger a buffer overflow assert.
Such behavior was confusing if someone was just placing things in FRED and not sure at all what happened or how to fix it.
This PR replaces the assert with code to auto truncate the ship class part of the name to ensure that the default name will fit into the designated size.
=> Auto Truncate default ship names

code/parse/sexp.cpp
It's not necessary here to assert on the correct variable type, as having the wrong type here won't cause the code to break.  More importantly, the error will have been flagged before this point anyway, and this code is used for formatting the SEXP to be displayed in an error message.  It's not helpful to pre-empt an error message with an assert.
=> remove two unnecessary asserts

code/menuui/credits.cpp, code/menuui/credits.h, code/menuui/readyroom.cpp, code/menuui/readyroom.h, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/scripting/api/libs/mission.cpp, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/techroom.cpp, code/scripting/api/objs/techroom.h, code/source_groups.cmake
This adds an ScpUi API for access to the many tech room related bits including the simulator room, cutscenes viewer, and credits screen. I think I covered everything. Anything missed will be in a later PR.
Some files, notably readyroom.cpp and credits.cpp needed some slight rearranging because the mission list and credits data are not created/parsed until that UI is actually loaded. The restructure allows for the API to call those methods and then access the data without loading the rest of the retail UI elements. While a larger restructure could have made the files more efficient overall, I felt this was the best way to accomplish what was needed while keeping the impact to the affected files as minimal as possible. That said, I'm open to instruction how this could be improved if …
=> Scripting functions required for SCPUI conversion of all four Tech Room UIs

code/scripting/api/libs/ui.cpp, code/scripting/api/objs/cmd_brief.cpp, code/scripting/api/objs/cmd_brief.h
The API previously had incorrect documentation, and was using a copy of the cmd_briefing object for the lua data, instead of a reference to the object. This is troublesome, since that implies that no changes can be propagated to and from FSO and can cause hard-to-find bugs if there is ever any API method that can modify the object
=> Fix the cmd_briefing scripting API

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/deferred-v.sdr, code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr, code/graphics/decal_draw_list.cpp, code/graphics/light.cpp, code/graphics/light.h, code/graphics/opengl/gropengldeferred.cpp, code/graphics/uniforms.cpp, code/graphics/util/uniform_structs.h, code/lab/dialogs/render_options.cpp, code/lab/renderer/lab_renderer.h, code/lighting/lighting.cpp, code/lighting/lighting.h, code/lighting/lighting_profiles.cpp, code/lighting/lighting_profiles.h, code/menuui/techmenu.cpp, code/missionui/missionbrief.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/missionui/missionweaponchoice.cpp, code/model/modelinterp.cpp, code/model/modelrender.cpp, code/scripting/api/objs/shipclass.cpp, code/starfield/starfield.cpp
as discussed in https://www.hard-light.net/forums/index.php?topic=98195.0 this PR replaces the command line args that scale lighting with whole-light controls, with controls in the lighting profiles to globally tune light types taking over for mods.
Effectively feature complete now but submitted in draft as there's a lot of cleanup and documentation I need to do still.
Includes changes from #4208, will have a history cleanup once that's merged in.
=> Crossing the specular rubicon

code/ai/aicode.cpp, code/ship/ship.cpp, code/ship/ship.h
According to EatThePath's frame profiling, this one ship name lookup takes 2% of the frame time.  It can be easily optimized by making use of the ship registry.
=> improve huge_fire_info lookup

code/cmdline/cmdline.cpp, freespace2/freespace.cpp
Reseeds the rng every mission load, if not in MP.
~~In draft because I'm having compiler difficulties and haven't been able to test any.~~
Now tested and appears functional. Doesn't result in noticeable repeatability in chaotic cutscenes, the ultimate goal, but that's expected as this is only one small piece of the puzzle.
=> Implemented a command line flag that forces a fixed RNG seed,

code/menuui/readyroom.cpp
Small oversight in the new UI code, wrong function was being called when building the list of campaign missions in the simulator.
=> Fix retail UI crash when campaign missions are selected in simulator

code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/deferred-v.sdr, code/def_files/data/effects/lighting.sdr, code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr, code/graphics/light.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/util/uniform_structs.h, code/lighting/lighting.cpp, code/lighting/lighting.h, code/model/modelrender.cpp, code/object/object.cpp, code/weapon/beam.cpp
This was made in collaboration with @EatThePath, and focuses on improving the look of beams, weapons and warp lighting
This should be merged in after #4652 as it relies upon some of the changes made there.
Based off research by epic games, [Real Shading in Unreal Engine 4](https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf), the tube and point light lighting calculations have been modified. 
Firstly, the point-source approximation used by beams/tube lights has been changed. Instead of choosing the nearest point of the tube light to the shaded fragment, the eye direction and surface normal are taken into account. This improves the look of the reflections of beams (especially on curved surfaces)
Secondly, all beam and point lights now have a …
=> Improved beam, blob and warp lighting

code/hud/hud.cpp, code/hud/hud.h, code/mission/missiontraining.cpp, code/parse/sexp.cpp, code/parse/sexp.h, code/scripting/api/libs/hud.cpp, code/scripting/api/objs/hudgauge.cpp, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
add `getDirectiveLines` and `setPosition` script functions properly error if trying to set a HUD gauge name
remove the unneeded `Directive_frames_loaded` variable improve accuracy of SEXP help for HUD gauge operators
=> several minor HUD enhancements

code/model/modelanimation_segments.cpp, code/model/modelanimation_segments.h
Previously, all animation sounds were played as 2D sounds.
Now, if they're properly attached to a parent submodel providing position (and they're on an actual object-model as opposed to stuff like skyboxes or cockpits without a position), the sound will play as a proper 3D sound
=> Fix Animation 3D Sound

code/weapon/weapons.cpp
Courtesy of Lafiel, this code fixes special flags such as those related to `spawn`. (Bug arose in #4620).
Tested and fixes the problem and works as expected.
=> Fix smart spawn flag

freespace2/freespace.cpp
When debugging, don't adjust the timestamp by the exact difference, since that would make the frametime 0 and cause div-0 errors.  Instead pretend that the previous frame was a reasonable duration.  Also, perform the timestamp check separately from the frametime check, since they are not always consistent.
=> better adjustment of timestamp delta

.github/workflows/build-release.yaml, .github/workflows/post-build-release.yaml
Adds release CI config for Mac. Note: this only adds enough to build and upload Mac artifacts to the Github release, but it doesn't change anything in the Python scripts that upload to Nebula and forums. That'd be a separate PR, also I'm not familiar with all that code so far.
=> Add release CI config for Mac

code/starfield/starfield.cpp
Two small fixes to follow up the lighting PRs
1) Change the mprintf to a Warning, both to be consistent with other deprecation warnings and to notify modders that they might need to accommodate the new lighting system
2) Parse any leftover data so that legacy tables don't cause FSO to choke on parsing
=> lighting followup

code/model/modelanimation.cpp, code/model/modelanimation.h
This is a rather specific flag for a certain but common type of animation, namely seamlessly looping animations which have an initial startup from a different rest state to their seamless loop.
This flag acts as a loop + reset on startup flag combination which, instead of skipping back to the end, skips back to the part where the seamless loop begins, both in forwards and backwards direction. Once the loop is stopped, the animation will run until the next loop would begin, and then play the startup sequence in reverse.
=> Flag for seamless animations with startup period

code/cmdline/cmdline.cpp, code/hud/hudparse.cpp, code/hud/hudtargetbox.cpp, code/hud/hudtargetbox.h
Allow different types of cargo scans, including the -dualscanline behavior, to be specified in the HUD gauges table.  Right now the options are "default" and "dualscanlines".
=> add -dualscanlines as a HUD config option

code/hud/hudparse.cpp
Because of idiosyncrasies of `required_string_one_of`, use a different technique.
Follow-up to #4671.
=> fix cargo scan type parsing

code/scripting/api/objs/ship.cpp
Previously the scripting function `giveOrder` capped goals at priority 100, but the max is 200. This PR fixes that.
=> Update max priority for scripting AIgoals

code/parse/sexp_container.cpp
Allow a map container's data for existing keys to be modified when the map container is used in the special argument list.
Adding or removing keys is still prohibited in this situation due to concurrent modification.
=> Allow modifying map container data when the map is an argument

code/scripting/api/libs/ui.cpp
Changes these two methods to allow the API to specify whether to go straight to the next (or current) mission briefing. This allows implementation of the debriefing ESC popup menu as well as skipping to the next mission. The latter requires closing out the debriefing with one of these two options so that we avoid an assert upon entering the next debriefing.
Also removes the return value because it was meaningless.
=> Allow API to optionally not start the next mission.

code/object/object.cpp, code/scripting/api/libs/graphics.cpp, code/scripting/api/libs/graphics.h
Scripts that render models in the On Object Render hook were effectively doing immediate renders in the middle of queued renders.  This caused some data, such as model orientation, to 'leak' between renders.  It might also have something to do with why the bug in #4637 had the particular graphical side effects that it did.
Anyway, changing the immediate renders to queued renders fixes the leaky orientations, and is probably a good upgrade for other reasons as well.
=> use queued rendering instead of immediate rendering for scripts

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/osapi/dialogs.cpp, code/osapi/outwnd.cpp, code/scripting/api/libs/base.cpp
Adds new default 'lua' filter category for all lua errors and output and -luadev flag that currently only makes lua errors non-fatal.
=> -luadev flag and lua log filter

code/mission/missionbriefcommon.cpp, code/mission/missionbriefcommon.h, code/missionui/missionbrief.cpp, code/missionui/missionbrief.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/briefing.cpp
Creates an API that allows drawing the currently loaded mission's briefing icon map and ability to manipulate what stage it is on.
Note that because of how retail rendered the cut-to-stage static, rendering of that has been removed from the API to be handled by the scripts so that it can be properly sized dynamically.
Also note that clicking on the icons of the map rendered through the API is not currently possible. That will take further investigation to sort out and allow. There are several bits of code that are commented out, but kept to make that later PR easier.
=> Scpui api briefing map

code/parse/sexp.cpp, code/scripting/api/objs/model.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/subsystem.cpp, code/ship/ship.cpp
1) Add the "no-thrusters" ship flag to the list of flag that can be used by alter-ship-flag or the ship's setFlag function
2) Add a `FireRateMultiplier` virtvar to control the firing rate of turrets (fulfills #4300)
3) Add a `setGlowPointBankActive` function to do the same thing as `activate-glow-point-bank`/`deactivate-glow-point-bank`
~~In draft status pending tests.~~
=> a few more script enhancements

code/mission/missiongoals.cpp, code/mission/missiongoals.h, code/mission/missiontraining.cpp, code/network/multimsgs.cpp, code/parse/sexp.cpp
This change covers just the timestamps associated with goals and events, for better review and isolation purposes.
Follow-up to #4569.
=> convert event-related timestamps to new system

code/graphics/uniforms.cpp
Big shader PR #4652 made models always receive image based lighting (bar command line options) - even those without specular maps. However, the associated shader_flags logic wasn't updated. this meant that ships without specular maps would render environment lighting with uninitialized data describing its orientation. This resulted in flickering as the data would differ frame-to-frame. 
This PR moves the logic outside of the "if has specular map" conditional, making sure the data is initialised if environment map rendering is happening
=> Fix lighting flickering on specmap-less models

code/globalincs/safe_strings.h, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelreplace.cpp, code/model/modelreplace.h, code/sound/speech.cpp, code/sound/voicerec.cpp
Previously, all loads for modular pofs were continually repeated. This changes this to cache models loaded from disk.
Since such a cache implies that the base models loaded from disk are immutable and reusable, some access had to be refactored. This consists mostly of macroifying the change_submodule_number (and name) functions, so that they provide methods for both in-place editing (when they need to operate on the current, mutable base model) as well as for editing an rvalue temporary copy of the data from the cache to be put moved into the current virtual pof with minimal code repetition. The templates in the macro may look scary, but all they do is allow any kind of map-like for providing the replacement arguments over just one variety of SCP_map.
This PR is a requirement for the …
=> Adds a cache for modular POFs

code/graphics/opengl/gropengldeferred.cpp, code/lighting/lighting.cpp, code/lighting/lighting.h, code/lighting/lighting_profiles.cpp, code/lighting/lighting_profiles.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp, code/ship/ship.h, freespace2/freespace.cpp
The first followup to #3445.
This removes the two different functions for external ship model and cockpit rendering, and instead fuses them into one function.
Apart from the evidently higher maintainability, this has a few advantages:
1. Due to the shipmodel now being in the deferred cockpit pass, ship model and cockpit can shadow one another
2. The external ship model is now also rendered deferred at no additional cost.
3. The external ship model is rendered, like the cockpit, with a 0,0,0 view matrix which avoids the stuttering issues observed for close models like show ship / cockpit when far from the origin.
4. It allows for finer control over the relation between cockpit and show ship model as well as their render settings
=> Merge Show Ship and Cockpit Renderpasses

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aibig.cpp
When fightercraft are ordered to attack big ships (if they pass some very modest conditions) they will enter this submode, which has them do nothing but turn in place for a second or two. I have no idea what the intention of this was, and it frustrates modders attempts to understand wtf the AI is doing, in addition to looking bizarre. This submode is used in other contexts, which this flag does not touch.
=> Flag to turn off continuous turn when attacking

code/lighting/lighting_profiles.cpp, code/lighting/lighting_profiles.h
The new lighting controls in the lab were implemented poorly, this makes them accurate to what is actually in the tables and prevents some potential side effects in the old handling.
=> Moved lab access to light multipliers to cleaner path

code/scripting/scripting.cpp
This fixes the newline count used to make the parsed Lua code align with the source file.
=> fix off-by-one error in Lua line numbering

code/object/collideshipship.cpp, code/object/object.cpp
Collisions with immobile objects... are fundamentally broken, obviously as a physics concept it is nonsensical, and if the non-immobile object has enough mass it can just burrow straight through immobile objects. I'm not going to tackle that right now, but we can at least make sure things don't blow up too badly when it happens. Physics impacts will currently update the speed of an immobile object, but it still won't move, giving it 'phantom' speed, which causes 'phantom collisions' and screws up a bunch of stuff. Rather than hunt all that down, I think its best to just always re-affirm every frame that immobile objects have 0 velocity, just in case it comes from weird places.
Position modification is much rarer, so I did go in and explicitly add checks for the few times the physics tries …
=> Make sure immobile objects always have 0 velocity

code/cfile/cfilesystem.cpp, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h
Implements #4113. In summary:
Conventional wisdom is that anything put in the fs2/data folder will override mod data but this is actually false, a file there will be shadowed or overridden by anything in mod files. It's possible that loose files in fs2/data override VP files, I haven't verified that for sure, but not all mods are distributed as such.
Clearly a community need/desire for something that overrides mod data exist, or there'd be no reason for that misconception to arise. So, this PR creates that capability.
This is implemented as effectively a 'built in' mod directory, named "load_last". Anything placed in fs2/load_last/data will be loaded after/above all roots in fs2/, though the appdata roots will still take priory.
=> created new "load_last" universal mod directory

code/network/multi_interpolate.cpp, code/network/multi_interpolate.h, code/network/multi_obj.cpp, code/network/multi_obj.h, code/network/multi_time_manager.h, code/object/object.cpp
The ship record for player ships is not always accurate.  This corrects entries in the ship record as valid packets are received, removing data recorded from guesses while interpolating ship info.
Also, remove a case where null vectors were being passed to the physics engine.
Waiting on some final testing.
Could not have finished this if not for @wookieejedi who has been performing testing and linting until I get a regular setup again.
=> Add corrections in multi ship record

code/scripting/lua/LuaTable.cpp, code/scripting/lua/LuaTable.h, code/scripting/lua/LuaThread.cpp, code/scripting/lua/LuaThread.h, test/src/scripting/lua/Thread.cpp
If we open a thread with async.run, we lose complete control over it.
This means, that when closing the scripting state, we don't actually take the thread with us.
To prevent the C++ side of things to try to push the thread off of the lua state way after the state is already dead, we remember all threads, and once the state gets destroyed, we forcibly push every thread handle off the stack. This has twofold effects: One, the C-Side of the handle gets invalidated, causing the destruction of the Thread object to not try to modify the lua stack, and two, cause the thread to be properly garbage collected on the lua side of things during deallocation.
As a sidenote, there is no built in way to stop threads in lua. They are an object like any other, and will be GC'd once they have no references …
=> Prevent dangling threads from crashing FSO on close

code/ship/ship.cpp
Using the `Cloak` or `Decloak` effect with 0 duration is a commonly accepted way to make a ship invisible/visible, however there is still a single frame of 'half-cloaked', due to the way it is handled. Firstly, only bother setting an animated effect if the effect actually has a duration (which also avoids division by 0 problems), and secondly use `>=` instead of `>` so we can take 'visibility' effect on the same frame.
=> Minor fix for 0 duration animated effects

code/ai/aiturret.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/model/model_flags.h, code/ship/ship.cpp
Most turrets can lead just fine without this, but in use cases where the firepoint is far from the center of the turret's "body" (an extra long barrel, for example) this can cause the turret to not aim correctly.  
This PR adds a ship flag that can be added to turret subsystems to enable it for them directly, as well as a game settings option to enable it for all turrets. 
Resolves #4288
=> Allow turrets to use their firepoints for target-leading calculations

code/missionui/missionshipchoice.cpp, code/missionui/missionshipchoice.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/shipwepselect.cpp
Changes isDisabled to return the value that was always intended; if the ship slot is used in the mission or not. Fix some documentation while I'm in there. Also changes #Loadout_Wings to always return MAX_STARTING_WINGS because Wss_slots can apparently store more wings than that, but they shouldn't ever be used.
=> isDisabled returns if the ship is used in the mission

code/missionui/missionscreencommon.h, code/missionui/missionshipchoice.cpp, code/missionui/missionshipchoice.h, code/missionui/missionweaponchoice.h, code/network/multiteamselect.cpp, code/scripting/api/libs/ui.cpp
Changes `commit_pressed()` from a void to an int and introduces return values based on the built-in errors. Also adds an API_Access parameter to suppress popups if true so that scpui can handle them with it's own dialog prompts.
Also adds resetSelect() which resets Wss_slots, Ss_pool, and Wl_pool to the mission's default loadout.
Tests of both are working as intended to both scpui Commit presses and retail Commit presses.
=> Reset loadout to default and handle commit mission error returns

code/missionui/missionshipchoice.cpp, code/scripting/api/libs/ui.cpp
Instead of always returning 3, this now checks that a wing has a ship actually used in the mission and will return 0-3 properly. Also makes sure to clear `in_mission` in all the slots when appropriate so that the count is, indeed, accurate.
=> return the actual number of starting wings

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aigoals.cpp
Play-dead orders set a special case of the ai mode (`AIM_PLAY_DEAD`), which had special handling to return early in the AI frame function. Remove-order does not change the ai mode though, and thus even when a play-dead order was removed the `AIM_PLAY_DEAD` remained, which would continually trigger an early out in AI frame, which in turn would make turrets not fire on ships, even when the play-dead order was removed. No other orders had this early return, which is why remove order works for them.
This PR accounts for that special handling case. There also seemed to be an extra cleanup line for rearm and repair, so this was added right after that step.
=> Fix Remove-Order not working for Play Dead Orders

code/decals/decals.cpp
For some reason, decals appear upside-down unless the uvec is flipped.
This screenshot shows a test mission with the fix applied.
=> flip decals right-side up

code/model/modelanimation.cpp, code/model/modelanimation.h, code/model/modelanimation_moveables.cpp, code/model/modelanimation_segments.cpp, code/model/modelanimation_segments.h
When fixing +Absolute in a previous PR, I was unknowingly removing a bug that has found use in some indev mods.
This adds a +Local mode, which works as the old, broken +Absolute.
+Relative is a movement in relative space. (i.e., 0,0,0 will be no change)
+Local is a movement to absolute coordinates local to this single animation. (i.e., 0,0,0 will be the state at the beginning of the animation)
+Absolute is a movement to absolute coordinates within the FoR of the parent, considering all other active animations. (i,e. 0,0,0 will be the actual absolute 0 coordinate of the parent FoR)
=> Add local coordinate relations to allow restoring old absolute behaviour

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp
Currently, if an AI ship is emerging from a bay path, the AI will stop following that path after only 10 seconds (and some distance away from the starting point). This results in AI breaking off a path early if a bay arrival path is long and/or uses a slow bay arrive multipliers. For bays that require the ship to follow the exact path this results in AI that then run into the parent ship and each other.
This PR adds a flag which disables that 10 second timeout. Also, in my tests having a flag to disable works best, as opposed to setting a max time (which is hard to calculate with varying ship speeds and varying bay path lengths).
PR is tested and works as expected.
=> Add AI flag to support ai bay arrivals > 10 seconds

code/scripting/api/libs/ui.cpp
Adds a Lua method to save the current loadout so that scpui can navigate between briefing game states and not lose the loadout
=> API to save the current loadout to the player file

code/controlconfig/controlsconfig.cpp, code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/parse/sexp.cpp, fred2/fredstubs.cpp, freespace2/freespace.cpp, freespace2/freespace.h, qtfred/src/fredstubs.cpp, test/src/test_stubs.cpp
This requires splitting the `used` field into digital and analog components.  The digital field stores the last-used timestamp, whereas the analog field stores the last value.
=> upgrade controls code to use type-safe timestamps

code/missionui/missionweaponchoice.cpp, code/missionui/missionweaponchoice.h, code/scripting/api/objs/shipclass.cpp
Moves overhead ship rendering to `draw_3d_overhead_view()` with two minor changes. First it changes using `&Eye_Matrix` to `&vmd_identity_matrix` which matches how `draw_model_rotating()` works. This allows this method to run successfully before any other model is drawn. It also changes some of the hardcoded coordinates in the line drawing to math that should return almost exactly the same value as was there previously. This allows the API to more freely customize where and how this is drawn.
Finally it adds an API to be able to call this drawing method.
=> Move rendering of the 3d overhead to it's own method and create an api

code/scripting/api/objs/object.cpp
Looks like no mods use this script method, so this change should be safe.
=> removeSoundByIndex should be 1-based

code/pngutils/pngutils.cpp, code/pngutils/pngutils.h, code/scpui/RocketRenderingInterface.cpp
This PR adds PNG decoding from base64 strings, as well as adds "file path" handling to librockets image backend, which allows to catch ``data:image/png;base64,``-prefixed png's and properly decode them.
=> Enable PNG blobs in LibRocket

code/object/objectsort.cpp, code/parse/sexp.cpp, code/scripting/api/objs/ship.cpp, code/ship/ship.cpp, code/ship/ship.h
In addition to type-safety, this now adjusts ship effects properly for time compression and pausing.
Follow-up to #4716
=> make animated ship effects use the new timestamps

code/mission/missionbriefcommon.cpp
Fixes issue in scpui where the briefing grid icon positions would not scale to fit the new coordinates.
=> Fix one missed resize mode

code/mission/missionparse.cpp, code/mission/missionparse.h, code/parse/parselo.h, code/parse/sexp.cpp, code/scripting/api/objs/parse_object.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/wing.cpp
Virtual variables corresponding to the same fields as in `set-arrival-info` and `set-departure-info`.  Some refactoring as well.
~~In draft status pending tests and rebase.~~
=> add arrival and departure info for wings, ships, and parse objects

code/menuui/credits.cpp
Starting the music should happen in `credits_init`, not whenever someone needs to know the file name.
=> get the credits music without starting it

code/menuui/credits.cpp, code/scripting/api/libs/ui.cpp
Sets the credits music default earlier so that SCPUI doesn't get nil data if no table explicitly sets the music.
=> Correctly set credits default even for scpui access

code/mission/missionparse.cpp, freespace2/freespace.cpp
Since the debug pause check needs to use UI timestamps, and since UI timestamps must keep track of time regardless of time compression, pausing, or mission status, move the updating and checking to `game_do_state_common`.
Also fix a type conversion warning.
=> fix updating of ui_timestamps

code/object/object.cpp, code/object/object.h, code/parse/sexp.cpp
The `flag_list` field is left over from before the type-safe refactor.  It was used to specify either the `flags` or `flags2` bitfield.
=> remove obsolete field

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp, code/hud/hudparse.h, code/scripting/api/libs/hud.cpp, code/ship/ship.cpp, code/ship/ship.h
Makes cockpits toggle-able in mission and adds a new HUD gauge option to make a gauge render only when cockpits are active, only when cockpits are not active, or render for both (default). Also adds a Lua method to be able to toggle the cockpits.
=> Toggle cockpit

code/scripting/api/objs/weaponclass.cpp
This fixes an issue where if renderTechModel was used it would load the tech model into `wip->model_num` causing the weapon in-game to subsequently not load in the desired low detail or bullet POF and instead use the tech model.
=> Use a local int for model storage in renderTechModel

code/scripting/api/objs/model.cpp
Guard against the indexer being invalid, e.g. if the model isn't loaded yet.
=> model.Submodels fix

code/hud/hudtargetbox.cpp
Looks like there was a misunderstanding originally. Team colors were only applied to wireframe style target views, which doesn't make sense. This moves settings of target view team colors up to apply to all target view styles when a ship is targeted.
Fixes #3883
=> apply team colors to all target view styles

code/scripting/ade.cpp, code/scripting/api/libs/base.cpp
There was code that could interpret any Lua type as an argument for printing, so I adapted it to be used in `ba.print()`, `ba.warning()`, and `ba.error()`.  Also `ba.println()` seemed like a useful thing to add.
Viewing the diff without whitespace changes should cut down on clutter.
With this PR, the following test script...
```
ba.println(5)
local t = { 1, 2 }
ba.println(t)
ba.println("x")
```
...produces the following output...
```
5.000000
Table w/ no metatable
x
```
=> enhance ba.print and add ba.println

freespace2/freespace.cpp
Fix for recent updates to cockpit rendering check, which was false if the player was the only ship in a mission. `instance >0` was used but it is supposed to be `instance >= 0` (The object index is valid if larger or equal to 0, while the signature is only valid equal or larger to 1.) Tested and fix works as expected.
=> 1 Line fix for player view render check

code/menuui/techmenu.cpp, code/missionui/missionbrief.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/model/model.h, code/model/modelread.cpp
Currently `$POF file Techroom:` is only used in the weapons loadout screen (despite having techroom in the name). This PR expands the use of the `$POF file Techroom:` to shiploadout select and the actual techroom.
If it is desired, I can put it behind a game settings flag, but IMO it would make the most sense for modders to have this just work as the actual name implies.
=> Update `$POF file Techroom:` Usage

code/hud/hudsquadmsg.cpp, code/mission/missionparse.cpp
The script functions should make the ships/wings arrive even if they are reinforcement, so this PR fixes that.  Also, this PR adds some additional verification of the `num_uses` of reinforcements, especially when the player calls for a wing that is already present but has more uses remaining.
=> fix makeShipArrive and makeWingArrive for reinforcements

code/asteroid/asteroid.cpp, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/hud/hud.cpp, code/hud/hud.h, code/hud/hudbrackets.cpp, code/hud/hudparse.cpp, code/hud/hudtarget.cpp
Adds a way to enable extra target info from hud_gauges.tbl. Does not deprecate the commandline but the table setting, if parsed, will take precedence
=> enable target info in hud_gauges.tbl

code/network/multi.cpp
Client update packets are sent from the server to client to update the health and threats on the hud.  Currently, there is a one-size fits all interval of 333 ms.  Very noticeable, especially at high pings (missile damage could show up half a second after impact, for instance). This was discovered while doing code analysis for the ETS refactor.
So if we've set a higher update rate in the multi options menu, allow for shorter interval times.
=> Add an update interval for client update packets

code/cmdline/cmdline.cpp, code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp
Adds a way to enable the support rearm timer from hud_gauges.tbl. Does not deprecate the commandline but the table setting, if parsed, will take precedence
=> Enable hud rearm timer in hud_gauges.tbl

code/scripting/api/objs/shipclass.cpp
Mostly copies of the same fields on `physics_info`, but on the ship class, so you know what the base values were if you're messing with the physics values.
=> Add a bunch of movement stats to ship class script api

code/hud/hudparse.cpp, code/hud/hudtargetbox.cpp, code/hud/hudtargetbox.h
This allows setting a wireframe color override globally for the HUD target monitor. Additionally it allows setting the target monitor style and wireframe color per gauge. Priority is in order of gauge > global > default. Still allows changing of the gauge style with the keyboard shortcut but could be paired with $Lock Wireframe Mode: to give HUDs their own unique target monitor style.
=> Additional Target Monitor features

code/hud/hud.cpp
Gauges that are set to render if the cockpit is inactive should also render in chase view, even if the current ship has a cockpit and cockpits are enabled.
=> cockpitinactive gauges should render in chase view

code/scripting/api/objs/player.cpp
Allow scripts to write to the current player's mission specific stats. Resolves #4686
=> Allow writing to player mission specific stats

code/graphics/2d.cpp
This took _way_ too long to find.
With SCPUI on the horizon, we'll soon see TC's that don't need to ship with all retail graphics or replacements for these. While that already works in large parts, the game currently assumes we cannot support high resolutions when it cannot find some arbitrary high res retail file. This amends this check, so that it still triggers when retail is available, but only without the sparky_hi_fs2.vp package, so that we fall back to low res mode.
But in case that the low res file is also not available, assume that we are using SCPUI and do not want to do any falling back.
=> Allow High Resolution Mode for SCPUI-only installations

code/globalincs/safe_strings.cpp, code/globalincs/safe_strings.h, code/model/model.h, code/model/modelread.cpp, code/model/modelreplace.cpp, code/model/modelreplace.h
The first big set of features for Virtual / Modular POFs (#4590)
Adds:
1. Copying Turrets
2. Copying Glowpoints
3. Copying Engines
4. Copying Special-Point Subsystems
5. Automatic handling of attached Glowpoints and Turrets when a Submodel Tree is copied
While not the proposed solution, this implements #3935
=> Modular POF Features

code/scripting/lua/LuaConvert.cpp, code/scripting/lua/LuaConvert.h
The `ade_odata_is_userdata_type` function didn't clean up its stack properly, as it left type information there for error reporting.  But there are other reasons to check userdata types besides error reporting, so this adds a flag to clean up in most situations.
Fix courtesy of @BMagnu.
=> clean up stack when checking type

code/globalincs/systemvars.cpp, code/globalincs/systemvars.h, code/graphics/material.cpp, code/graphics/opengl/gropengltnl.cpp
As best I can tell these variables are remains of an older version of the lab or old implementations of command line flags, and are currently only ever a single value. To clean up, I removed them and the remaining checks on them.
=> These old vars did something once, but not anymore

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, fred2/eventeditor.cpp
Implements the ability to define a custom list of Head Anis in game_settings.tbl and uses that to populate the list in the FRED Events Editor. Fixes #3875
=> Allow adding custom head anis to the list in FRED

code/asteroid/asteroid.cpp, code/asteroid/asteroid.h, code/mission/missionparse.cpp, fred2/asteroideditordlg.cpp, fred2/fredview.cpp, fred2/management.cpp, fred2/missionsave.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp, qtfred/src/mission/missionsave.cpp
Some refactoring with asteroid fields:
1. Moves asteroid throwing targets into the Asteroid_field struct, in anticipation of potentially multiple fields in the future
2. Moves some initialization code into `asteroid_level_init`
3. Calls `asteroid_level_init` when a mission is cleared
4. Loads asteroid targets as part of the asteroid field update/init logic.  This fixes a FRED bug reported in Discord where asteroid targets stay in the dialog when a new mission is loaded
5. Remove `Default_asteroid_throwing_behavior` flag as it is equivalent to checking that the target list is empty
=> asteroid field fix/refactor

code/weapon/weapons.cpp
Use the proper attacking function here, as traitors need to be able to attack each other in dogfight mode.
=> Allow multilock between traitors

code/missionui/missionshipchoice.cpp
This makes `ss_reset_selected_ship() `mirror its sister function `wl_maybe_reset_selected_weapon_class()`. Removes an erroneous int3() which prevented checking the ship pool for a valid ship class if none was found in the loadout slots. Returns instead of breaks when a valid value is found. Finally, it allows the game to continue with a value of -1.
Research and testing shows that the Ship Select UI will handle a -1 correctly by not loading an animation or ship data. In other cases where a value is needed, error checking already exists there. That said, in the retail UI it seems to be impossible to force a value of -1 due to other error checking in the mission files themselves during load. (IE: You cannot have a ship without a player ship and having a player ship forces the pool to have …
=> remove misplaced int3() and allow the game to continue with -1

code/ai/ai.h, code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aicode.cpp, code/ai/aiturret.cpp
This adds an AI profiles flag that filters autoscaling so that only the index and number of autoscaled classes are considered, not the index and number of all AI classes.
Fixes #4516.
=> take non-autoscaling AI classes into account when autoscaling

fred2/fredview.cpp, fred2/mainfrm.cpp, fred2/mainfrm.h, fred2/management.cpp
Turns out this list already looks up objects by name with the exception of waypoints and jump nodes. So this modifies how we create the list slightly by adding a counter and doing checks against the counter total instead of `ship_info.size()` This allows to be able to not list white space in order to keep indices. This also moves where we set the expected index of waypoints and jump nodes to after the counter is complete. It changes them from `ship_info.size() + N` to counter total + N.
I spent a few hours FREDing on this build and didn't run into any bugs, but it is probably worth giving this PR just a little extra scrutiny to be sure. The FRED code isn't the most readable.
Fixes #3633
=> Dont add whitespace for no_fred ships in the main list

code/gamesnd/gamesnd.cpp, code/species_defs/species_defs.cpp, code/species_defs/species_defs.h
Adds ability to borrow flyby sounds to species_defs.tbl and cleans out some old species flyby checking code that was no longer used.
Fixes #4520
=> allow borrowing flyby sounds from a previously parsed species

code/missionui/missionbrief.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/missionui/missionshipchoice.cpp, code/missionui/missionshipchoice.h, code/missionui/missionweaponchoice.cpp, code/missionui/missionweaponchoice.h, code/scripting/api/libs/ui.cpp
Partial fix for #4821. Stops SCPUI from being able to even get into functions that only handle retail UI elements.
=> Further limit what built-in UI elements can be setup when using SCPUI

code/scripting/api/objs/ship.cpp, code/scripting/api/objs/subsystem.cpp
Previously, setting `Target` for either would have been ignored entirely.
=> Clearable Ship/Subsystem Targets via script

code/io/timer.cpp, code/io/timer.h
Fix the comparison and add documentation to the compare functions.
Thanks to @JohnAFernandez for noticing the bug.
=> fix timestamp_in_between functions

code/scpui/RocketRenderingInterface.cpp, code/scripting/api/libs/graphics.cpp, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/texture.cpp, code/scripting/api/objs/texture.h
This allows to directly use a texture object for image sources in librocket over having to render on screen over librocket or to have to pass it as a blob, which is especially useful for rendering continually updating textures with librocket.
To make sure we don't run into problems with passing ownership and stuff, I had to redo the lock_count system for lua textures. This is a good thing anyways IMO, since we would have leaked textures which are created in lua, used / locked somewhere else, and then went out of scope in lua as it is now, whereas this new way will properly reference count them.
=> libRocket Texture Passthrough

code/hud/hudescort.cpp
If a player is dead and their ship has not yet respawned, don't try to add them to the escort list.
=> Make sure that the escort list only lists valid targets on multi

code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/lighting.sdr, code/def_files/data/effects/main-f.sdr
While working on shader culling, @EatThePath noticed some issues with rough dielectric surfaces being too shiny at sharp angles. Through a process of elimination he narrowed it down to the geometry term using the wrong equation for surface roughness. 
While fixing, I also noticed the `area_normalisation` term that stops wide beams from being too bright wasn't actually in use, so that's been applied to deferred lighting.
To prevent further mistakes, there's some minor cleanup to make it more clear what we're doing. (This also gets rid of a sqrt() call, so hopefully there's some optimisation there)
=> Minor lighting shader fixes

code/parse/sexp.cpp
This ensures that when using beam-fire SEXPs the turrets will properly increment `turret_next_fire_pos` and cycle through its fire points. `beam_fire()` does not handle this, and it must be handled by the caller.
=> Small fix for `turret_next_fire_pos` in beam-fire

code/scripting/api/objs/subsystem.cpp
This way, singlepart turrets can be directed to fire in a given direction, instead of purely straight out from the turret normal.
=> Allow overriding `gvec` in `fireWeapon` on subsystems

code/graphics/uniforms.cpp
Fixes a regression from #4838. Leaving default gloss uninitialized for unlit models led to a flickering issue in some cases, such as loadout screens.
=> always set the default gloss uniform since it is now always used

code/scripting/api/objs/subsystem.cpp, code/ship/ship.h
`getModelFlag` following the  same general API as `get/setFlag` on ships.
=> Add `isMultipart` and `getModelFlag` functions on subsystems

code/mission/missionparse.cpp, code/parse/sexp.cpp
When the top-level operator of a SEXP is not found, flag the error instead of crashing.  This is helpful for missions that contain unsupported scripted SEXPs.
=> improve SEXP syntax checking

code/network/multi_fstracker.cpp, code/network/multimsgs.cpp, code/parse/sexp.cpp, code/pilotfile/csg.cpp, code/pilotfile/csg_convert.cpp, code/stats/medals.cpp, code/stats/medals.h, code/stats/scoring.cpp, code/stats/scoring.h, fred2/management.cpp, fred2/sexp_tree.cpp, freespace2/freespace.cpp, qtfred/src/mission/management.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Makes medals.tbl extendable with -mdl.tbm. Ended up being a bigger PR than expected because it fixes a number of related issues to make it easier to deal with modular medals including better handling of kill count badge promotion to remove requiring badges be tabled in order of kill count, better handling of finding the Rank medal, adding the ability to specify a mask value for each medal, and entirely removing `Num_medals` in favor of `Medals.size()`.
=> Modular medals

code/libs/discord/discord.cpp, code/libs/discord/discord.h, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, freespace2/freespace.cpp
Sets up discord presence to allow toggling. Adds a game_settings.tbl flag to enable or disable it (Could be command line, but leaning in to the load_last directory instead). Also adds a constructed built-in option to toggle it during a game instance if the active mod is using SCPUI. The built-in option toggle will override the game_settings.tbl flag.
Partially implements #4113
=> Optional discord presence

code/decals/decals.cpp
Prevent warnings from being displayed due to decals not being loaded.
=> fix decal debug warnings in FRED

code/mission/missionparse.cpp
Parse objects have their path masks temporarily set to -1, since during parsing the mask represents an index, not a bitfield.
Fixes #4873.
=> use correct path masks for parse objects

code/lab/renderer/lab_renderer.cpp, code/mission/missionparse.cpp, code/nebula/neb.cpp, code/nebula/neb.h
#4856 broke the new nebula poof parsing by zero'ing the list and then immediately setting all the bits before the parse happened. This resulted in Neb2_poof_flags == -1 before it even starts trying to set bits from the list of poof names. This PR removes that and moves the bit setting to it's own method and then calls that method during mission parsing. Also makes sure the Lab is aware of the new poof parsing option.
=> Fix poof name parsing and fix lab not knowing about the new parsing

code/ai/ai_profiles.h
Previous limit lasted from 2005-11-21 until now (from commit b33caf6f45).  We'll see how long this one lasts.
=> bump MAX_AI_PROFILES

code/parse/sexp.cpp
Adds `SEXP_CHECK_INVALID_SOUND_ENVIRONMENT` and `SEXP_CHECK_INVALID_SOUND_ENVIRONMENT_OPTION` to `sexp_recoverable_error()`. Neither causes a fatal problem, and the former can be spuriously triggered if EFX is disabled.
=> Make sound environment SEXP errors recoverable.

code/missionui/missiondebrief.cpp
Quick addition to replace keybinds in debriefings at the same time that the code already replaces variables and containers. Fixes #3241
=> replace keybinds in debriefing

code/mission/mission_flags.h, code/mission/missionparse.cpp, code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/ship/ship_flags.h, fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Prevents the player from performing a cargo or subsystem scan.  Can be toggled using alter-ship-flag.
Also adds some missing logic for Fail_sound_locked_primary, Fail_sound_locked_secondary, and Aspect_immune.
=> add cannot-perform-scan flag

code/scripting/api/libs/bitops.cpp, code/scripting/api/libs/graphics.cpp, code/scripting/api/libs/mission.cpp, code/scripting/api/libs/testing.cpp, code/scripting/api/objs/enums.cpp, code/scripting/api/objs/enums.h, code/scripting/api/objs/object.cpp, code/scripting/api/objs/option.cpp, code/scripting/api/objs/order.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/ship_registry_entry.cpp
This PR refactors the lua enum system away from arbitrary indices to it being a proper enum. At the same time, it facilitates explicit bitfield values to allow for bitfield enums without the double-usage of indices as was the case previously.
This fixes a number of bugs associated with lua enums:
1. Bitfield enums now no longer test as equal to other unrelated enums.
2. Bitfield enums now display their proper name instead of an arbitrary unrelated one.
3. Combined bitfield enums now properly display which combination of enums they are.
=> Refactor Lua Enums

code/ai/aigoals.cpp
The `special ship` field stores the index in the wing's `ship_index` array.  It does not store the shipnum itself.
Discovered in the course of coding #4889.
=> fix wing leader check

code/ai/aicode.cpp, code/ai/aiturret.cpp, code/model/modelread.cpp, code/network/multi.cpp, code/network/multi.h, code/network/multi_turret_manager.cpp, code/network/multi_turret_manager.h, code/network/multimsgs.cpp, code/network/multimsgs.h, code/network/multiutil.cpp, code/network/multiutil.h, code/ship/ship.cpp, code/ship/ship.h, code/source_groups.cmake, freespace2/freespace.cpp
This allows clients to user server data to move turrets according to the timing and target data on the server.  Uses a small packet to do so.
=> Enable client turrets to track targets

fred2/campaigneditordlg.cpp, fred2/eventeditor.cpp, fred2/missiongoalsdlg.cpp
This properly updates event and goal signatures when events are moved around.  Fixes Mantis bugs 1005, 1961, and 2998.
=> fix swapping of things in FRED

code/scripting/lua.cpp
In my recent enum refactor, I may have forgotten to assign the bitfield enums to the actually globally set ones, causing Asserts when globally accessed enums were used.
=> Fix Enum assignments

cmake/platform-win32.cmake, code/bmpman/bmpman.cpp, code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilesystem.cpp, code/cfile/cfilesystem.h, code/def_files/data/scripts/cfile_require.lua, code/graphics/generic.cpp, code/graphics/software/FontManager.cpp, code/localization/localize.cpp, code/localization/localize.h, code/pilotfile/csg_convert.cpp, code/pilotfile/plr_convert.cpp, code/sound/ffmpeg/FFmpegWaveFile.cpp, fred2/campaigneditordlg.cpp, test/src/cfile/cfile.cpp
Allow indexing of files in subfolders of known cfile path types as if the files in those subfolders were directly part of the known path. Essentially a cosmetic change allowing mod makers to organize their files in a better way without requiring any direct content changes or special code handling to take advantage of the feature.
=> add support for subfolders to cfile

code/def_files/data/effects/deferred-f.sdr
Area_normalisation term in deferred shader was not getting set properly for cone lights, which caused things like ship headlights to not work properly.
Tested and fixes issue as expected. Thanks to Qaz and EatThePath for pointing out how to fix it!
=> Fix Flashlights

code/io/timer.cpp, code/io/timer.h, code/model/modelrender.cpp
For all POFs that use animated textures, if no starting timestamp is specified, assume animation started at the beginning of the mission.  This fixes a bug reported in Starfox: Event Horizon where weapon POF animated textures stopped animating after the texture timestamp upgrade.
=> by default, start texture animation at the beginning of a mission

code/cfile/cfilesystem.cpp, code/menuui/readyroom.cpp, code/mission/missioncampaign.cpp, code/mission/missioncampaign.h, code/mission/missionparse.cpp, code/mission/missionparse.h, code/pilotfile/csg.cpp, code/scripting/api/objs/player.cpp, fred2/campaigneditordlg.cpp, fred2/campaigneditordlg.h, fred2/campaignfilelistbox.cpp, fred2/campaignfilelistbox.h, fred2/campaigntreeview.cpp, fred2/campaigntreewnd.cpp
Load campaigns using the full path provided by the user, not just from the configured mod paths.
Also tweaks initialization based on the campaign having already been cleared in `mission_campaign_clear()`.
=> fix campaign loading in FRED

fred2/fred.rc, fred2/voiceactingmanager.cpp
A quick feature to print Message Names as part of script generation. This is useful for Lua sexps that send messages on behalf of ships where the code won't be able to find the Sender from a send-message SEXP. In the case of BtA's specific message-alt SEXPs, the "sender" is always built-in to the message name itself.
=> allow getting message names in script generation

code/mission/missionparse.cpp
This was accidentally introduced in #4878.
=> fix a copy+paste error

code/ship/ship.cpp
PR #4908 had a small bug that caused a crash in FRED.  The code in question is only needed and only relevant when changing ship classes in-mission.
=> fix crash when changing ship classes in FRED

code/scripting/api/objs/control_binding.cpp
We shouldn't be checking that the `cci_h` is valid by seeing if it is greater than -1 because by that point it never will be.  Instead, we should be checking that the incoming id is valid and setting to the invalid state if it is not.
=> Fix a warning

code/mission/missionhotkey.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
Adds a game settings table flag to always hide hidden hotkey ships. Fixes #3290
=> option to always hide hidden hotkey ships

code/ship/shiphit.cpp, code/weapon/weapon.h, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
I've returned to this project after a year of not working on it. Got most of the changes from last time added, along with warnings for missing flags or bad values. The core principle is still the same:
-Vampirism flag enables the ability to regain health by dealing hull damage to a ship.
-"$Vampiric Healing Factor:" is the multiplier by which the final hull damage dealt is multiplied by. This value now cannot go below 0.
This now DOES work with shockwaves and beams and primaries and secondaries.
=> Setting up Vampirism again... again

cmake-variants.yaml
When using visual studio code to build the game, the cmake extension provides a list of build flavors to choose from but can't pick up on the SCP's custom defined builds and only uses a default list. This file is read by it to get around it.
If keeping it in the root is undesirable it could be shifted to a `.vscode/` location instead.
=> Add yaml file defining build options for vscode cmake tools users.

code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/main-g.sdr, code/def_files/data/effects/main-v.sdr, code/globalincs/systemvars.cpp, code/globalincs/systemvars.h, code/graphics/uniforms.cpp, code/graphics/util/uniform_structs.h
effectively a followup to #4823, working along similar lines but hitting a few things that were a tad less evident on my last sweep.
After this there are several elements of the model data shader uniform that are unused. Altering shader uniforms is something that can easily go wrong, and I'm not quite done with them yet, so for the moment I've marked all the dead ones' names to make them stick out and intend to do a followup very soon.
=> More old dead shader override code that isn't hooked to anything anymore

code/mission/missionhotkey.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
1. Since Discord is both a common noun and a proper noun, capitalize it here to clarify what it refers to.
2. Capitalize the first letter of the Hotkey internal variable to follow the global variable convention.  And might as well clarify, while we're at it, that it hides hidden ships, not all ships.
=> style tweaks for recently added options

code/weapon/weapon_flags.h, code/weapon/weapons.cpp, fred2/shipeditordlg.cpp, fred2/shipeditordlg.h, fred2/weaponeditordlg.cpp, fred2/weaponeditordlg.h
The new `no_fred` flag prevents weapons from being listed in the dropdown lists in the weapon dialog.  Also this fixes `no_fred` ships to not appear either: previously they were hidden in the main window dropdown but still appeared in the ship editor.
In order to vastly simplify the dropdown list code, the weapon dialog was refactored to use arrays of variables rather than one hardcoded variable per bank.
Implements #3643.
=> add no_fred flag for weapons, and patch no_fred for ships

code/object/collideshipweapon.cpp
`warning C4305: 'argument': truncation from 'double' to 'float'`
=> fix two warnings

code/scripting/api/objs/texture.cpp
Fixes #4935.
#4822 introduced proper refcounting for lua-held textures. Unfortunately, it failed to account for the creation of invalid textures, which caused a failed attempt at refcounting invalid textures, causing an Assert.
This now adds a check, that only texture objects which are actually valid will be refcounted.
=> Fix RefCounting on invalid textures

code/ai/aicode.cpp, code/ai/aigoals.cpp, code/ship/ship.cpp
In the submodel reorganization in commit 575c050da44c213c4ef127588880f24101ca480f, subobject movement was moved out of the AI pipeline, which inadvertently removed the play-dead check that prevents subsystem movement.  This broke a few missions such as Scroll's 'Thor's Hammer'.  This PR restores the check.
Fixes #4933.
=> don't process turrets or subsystems when playing dead

code/popup/popup.cpp, code/popup/popupdead.cpp, code/scripting/global_hooks.cpp
This is a follow-up to #4806, allowing SCPUI to take full control of all popups in the game, including those on-death.
=> Enhance OnDialogX Hooks to encompass Death Popups

fred2/campaigneditordlg.cpp, fred2/campaigneditordlg.h, fred2/eventeditor.cpp, fred2/eventeditor.h, fred2/missiongoalsdlg.cpp, fred2/missiongoalsdlg.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
FREDders expect events (and goals and campaign links) to land where you drag them.  So when dragging items earlier in the list, insert them before the item they are dropped on.
=> make sexp_tree dragging more user-friendly

code/ai/ai.h, code/ai/aicode.cpp
PR #4516 did not cover all of the autoscaled AI class attributes, since a few of them were labeled differently.  This adds checks to grab the correct autoscale index for the remaining cases:
```
$Afterburner Use Factor:
$Shockwave Evade Chances Per Second:
$Get Away Chance:
$Secondary Range Multiplier:
```
Fortunately, Sushi's investigation was pretty thorough.  Between these remaining cases and @EatThePath's autoscaling review, this PR should cover the complete set of autoscaling situations.
Fixes #4922.
=> fix the rest of the autoscaled attributes

code/ai/aigoals.cpp
Some subsystems will not have submodel instances, so make sure their velocities are not reset.  Fixes a crash in FotG.
=> fix crash on mission load

code/parse/sexp.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
If a variable can't be found, fail gracefully instead of Asserting.  These changes will allow the mission to be saved and/or loaded, and will also allow the user to open the Event Editor and replace the nonexistent variable.  This fixes the crash/assertion failure in #3849, as well as the case where the variable is edited in the mission file.
=> guard against unknown variables

code/model/model.h, code/model/modelread.cpp, code/model/modelrender.cpp
Adds option to glowpoint overrides table to define the light intensity for the glowpoint. Defaults to the previous hardcoded value of 1.0f.
=> Allow setting glowpoint light intensity

code/ship/ship.cpp
The logic designed to match Epsilon and Epsilon#clone would be tripped up by Pi and Pisces.  Tweak the string matching to handle this.
Fixes a bug reported on the forums: https://www.hard-light.net/forums/index.php?topic=98576.0
=> fix wing name matching

code/ship/ship.cpp
This would otherwise cause a crash when a cockpitless model gets loaded, leaves cockpit_model_instance at 0, and then tries to clear the cockpit instance 0 again once the ship gets cleaned.
=> Properly init cockpit_model_instance to -1

code/ship/ship.cpp, code/weapon/weapons.cpp
Ran into this in BtA. For the purposes of +remove, `@Shipname` is not the same as `Shipname` which is different from all other parsing. This PR resolves that by moving the code that removes the @ from the name to directly after the name parsing so that the @ symbol is truly completely ignored by the code as documented in the Wiki.
=> move @ removal up

code/ship/ship.cpp
Make sure custom_data is properly cleared or carried over when shipclass info is reset or cloned/moved
=> Fix custom data when using tbms

code/weapon/weapons.cpp
I missed pushing a local commit to the per-weapon autoaim feature. This bit of parsing ensures the correct values later in the code.
=> do correct math at parse

code/stats/scoring.cpp
Cleans up traitor.tbl parsing by making `$Num Stages` and `$Formula` optional entries. Both entries' values are required to be something specific and in the case of Num Stages would assert if anything else was in the table. So, this sets the values and skips straight to parsing `$Multi Text` so that the retail table still parses properly.
Kept the old parsing as comments in case traitor.tbl is expanded upon sometime in the future.
=> clean traitor.tbl parsing

code/model/modelread.cpp
Fixes case where the code tries to set the color ptr for DAMAGE lightning type instead of SHIP (passive) which would be nullptr here.
=> Only set the colors for passive lightning

code/scripting/api/libs/tables.cpp, code/scripting/api/objs/fireballclass.cpp, code/scripting/api/objs/wing.cpp, code/scripting/api/objs/wingformation.cpp, code/scripting/api/objs/wingformation.h, code/source_groups.cmake
A rework of #4980, adding a wing formation type and a way to access them via `tb.WingFormations`.
Also fixes some flaws in the fireball class, which the wing formation class is based on.
=> exposes wing formation via scripting

code/globalincs/memory/memory.h, code/globalincs/systemvars.h, code/mission/missionmessage.cpp
Use a vector for storing the message queue so it can be whatever size the mission needs.
As part of this, add `free` and `vm_free` deleters to be usable with `unique_ptr` and enhance `insertion_sort` to be usable with vectors.
Fixes ~~#4959~~ and #4968.
=> make message queue dynamic

code/nebula/neb.cpp, code/weapon/weapons.cpp
For poofs and laser bitmaps specifically. Notably, this fixes apngs when used for these purposes, as otherwise those apngs are valid static bitmaps, and would not be usable as an animation.
=> Ensure effect animations load before static bitmaps

code/ship/ship.cpp
This function can be called when `shipp` is null, so check for that.
Fixes #4991.
=> fix crash in ship_close_cockpit_displays

code/ship/shipfx.cpp
Fixes issue where passive arcs would stop checking for additional valid arcs if any were skipped due to a destroyed subsystem.
=> fix passive arc iteration

code/mission/missionparse.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Empty subcategories are now OP_SUBCATEGORY_NONE, not -1.  Fixes #4994.
Also fixes a cast warning in missionparse.cpp.
=> fix subcategory comparison

code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/EngineSEXP.cpp, code/parse/sexp/EngineSEXP.h, code/parse/sexp/LuaAISEXP.cpp, code/parse/sexp/sexp_lookup.cpp, fred2/management.cpp, freespace2/freespace.cpp, qtfred/src/main.cpp, qtfred/src/mission/management.cpp, qtfred/src/mission/management.h
Several items here:
1. Patches several category and subcategory validation checks (comparisons to -1 rather than _NONE) that were missed in #4965.
2. Adds sanity checks to both built-in operators and scripted sexps to ensure categories and subcategories are consistent.
3. Deconflicts several built-in sexps that had inconsistent categories.
The inconsistent operators were:
* script-eval-string
* set-wing-formation
* get-ets-value
* turret-get-primary-ammo
* turret-get-secondary-ammo
* get-fov
Follow-up to #4965 and #4995.
=> subcategory fixes and followup

code/scripting/api/libs/base.cpp
Much like a previous instance (fixed in #3281, although the function in question was later removed), `std::isdigit()` without a locale argument prevents MSVC 2017 from compiling FSO.
=> Add missing locale argument to `std::isdigit()` calls.

freespace2/freespace.cpp
Introduced by #4960, causes On State Start to not properly execute when overridden.
=> Fix Hook Refactor Bug

code/ai/aicode.cpp, code/ship/ship.cpp
Follow-up to #4934. Fixes #4998 and restores behavior from before #3713 . A little unfortunate, maybe, but designers can still lock player turrets if they don't want them to do anything.
=> Allow player turrets to fire despite play dead

code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/sexp_lookup.cpp, code/parse/sexp/sexp_lookup.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
Adds the ability to specify a custom enumeration for dynamic lua sexps. Internally the sexp argument type starts at the end of the type enum list and is incremented from there. That is used to find the correct list of enumerations in the `Dynamic_enums` vector. This fixes #3381 .
Currently this is only done inline, meaning if you have the same enum list more than once it will need to be specified for each sexp. There is a path forward from here to specify enums earlier in the sexps.tbl and then reference those for each sexp which will be cleaner. But I felt that would be better as a follow-up enhancement to this feature since this PR has enough spaghetti.
=> Dynamic sexp enum

code/autopilot/autopilot.h
Initialize NavPoint values any time a NavPoint object is created, not just when the `clear()` function is run.
=> initialize NavPoint properly

code/scripting/api/objs/shipclass.cpp
Fixes #4660 by copying the same method used in the retail tech room UI. Setup a model instance that removes -destroyed subobjects and use that for rendering.
=> Do not include -destroyed subobjects in renderTechModel

code/network/multi_interpolate.cpp
These were never set to the correct variables, which is to say the incoming parameters.  Based on the comment also never being edited, I am guessing this is a copy paste mistake.  The effect of the wrong variables being placed there is that player ships were likely more easy to hit in PvP modes.  This makes sense, as my original expectation for the effectiveness of this function would be more subtle effect on PvP accuracy.
This is also the reason why #5003 is failing its checks.
=> Use the correct variables in this function

.github/workflows/post-build-release.yaml, ci/post/forum.py
This modified the check as `text` has been changed in the Requests API. In order to make the code compatible with the JSON result, we check `resp.status_code` instead.
=> Change check of POST response result

code/cfile/cfile.cpp, code/scripting/api/libs/cfile.cpp
- fix crash bug when path only contains dir separators
- fix error handling when no path is specified in write mode
- clarify function documentation
Fixes #5028
=> address issues related to cf.openFile() error handling

code/scripting/global_hooks.cpp, code/scripting/global_hooks.h, freespace2/freespace.cpp
when parsing a script table that includes hooks for a different application (i.e. FRED scripts in FSO or vice versa), only print something to the log instead of erroring out
this fixes #5026
=> Fix issue with FSO-only scripts in FRED

code/ship/ship.cpp
Probably an oversight from when these are split into being stored on the ship object itself.
=> Update regen rates and autoaim fov on ship class change

code/hud/hudtarget.cpp
These checks risked causing a crash or memory access violation if they were ever encountered with an invalid target when `auto_advance` is true.
=> patch some crash vulnerabilities in hud_target_live_turret

code/hud/hudlock.cpp, code/ship/awacs.cpp
Since `hud_lock_acquire_uncaged_target` assumes every item is a ship, it probably intended to iterate over `Ship_obj_list`, not `obj_used_list`.
=> patch hud-lock iteration for objects that aren't ships

code/ship/ship.cpp
Follow-up to #4908. Not all ships have parse objects! (And if you don't, fairly sure that also means you don't have a wing either.)
=> Fix a crash in `change_ship_type`

code/ai/aibig.cpp, code/ai/aicode.cpp, code/ai/aigoals.cpp, code/ai/aiturret.cpp, code/asteroid/asteroid.cpp, code/autopilot/autopilot.cpp, code/gamesnd/eventmusic.cpp, code/hud/hud.cpp, code/hud/hudescort.cpp, code/hud/hudsquadmsg.cpp, code/hud/hudtarget.cpp, code/hud/hudwingmanstatus.cpp, code/mission/missionhotkey.cpp, code/mission/missionparse.cpp, code/missionui/redalert.cpp, code/network/multi_ingame.cpp, code/network/multi_respawn.cpp, code/network/multi_team.cpp, code/network/multimsgs.cpp, code/network/multiutil.cpp, code/parse/sexp.cpp, code/playerman/playercontrol.cpp, code/scripting/api/objs/oswpt.cpp, code/ship/awacs.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/weapon/emp.cpp, code/weapon/weapons.cpp, freespace2/freespace.cpp
When iterating through `Ship_obj_list`, check the `Should_be_dead` flag before using the object.  This fixes #4990 and adds defense-in-depth checks to guard against similar errors elsewhere.
I considered moving the `Ship_obj_list` removal from `obj_delete` to `ship_cleanup`, but decided it would be prudent to avoid fundamental changes to lifecycle management.
=> add should-be-dead checks for all ship iterations

code/parse/sexp.cpp, fred2/wing.cpp, qtfred/src/mission/EditorWing.cpp
Fixes #5045 by correctly initializing wing arrival and departure cues.  Follow-up to #4856.  Also adds a bit more SEXP error checking.
=> fix wing cues and add some more error checks

code/scripting/scripting.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Controls6 (PR #4133) changed `textify_scancode()` to be more l10n-aware, and added `textify_scancode_universal()` to continue serving the function of providing the values expected by scripts. Except there was one `textify_scancode()` call in the scripting system that wasn't changed, and it also wasn't used in FRED (for providing values for the `OPF_KEYPRESS` argument type, as used with `key-pressed`). This commit fixes both of these oversights, which *should* mean that all instances where a script or mission file needs to reference a keypress now use the same strings as before controls6.
=> Use `textify_scancode_universal()` in more places.

code/ship/ship.cpp
If there's an unchecked parse object access, blighted will find it.
For real though, I double checked the rest of the function there's no other unchecked accesses.
=> Check for parse object before team color change

code/cfile/cfilesystem.cpp
.vpc is identical to existing .vp except that it is allowed to contain compressed files. This allows builds and tooling to know that although the archive itself is retail compatible, it's content may require special handling.
Simply rename your existing .vp to .vpc to indicate that it may use compressed files. Existing tools can be updated to be able to handle the compressed content within.
Although not recommended, the same archive can exist as both .vp and .vpc for maximum compatibility. Both archives will be indexed but the content of the .vpc will have priority.
=> add support for .vpc extension on VP archives

code/ship/shipfx.cpp
Apply team coloring to half-exploded ship halves as they are split.
=> Ensure 'split ships' are team colored

code/io/joy-sdl.cpp
If using the new options system, we need to evaluate all 4 joysticks, not just joy0.
=> Make sure all 4 in-game joystick options get evaluated

code/ai/aicode.cpp, code/ai/aiturret.cpp, code/asteroid/asteroid.cpp, code/hud/hudtarget.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/weapon/emp.cpp, code/weapon/weapons.cpp
Follow-up to #5050 and #5040, along the same lines.  Also uses `Missile_obj_list` and `Asteroid_obj_list` instead of `obj_used_list` where appropriate.
~~In draft status until #5050 is merged, as it depends on that.~~
=> add should-be-dead checks for missile and asteroid iterations

code/object/object.h, code/scripting/api/libs/mission.cpp, code/scripting/api/objs/object.cpp
When iterating through various object collections, check for the should-be-dead flag to avoid returning objects that are on the verge of being deleted.
Separately, this adds the `isExpiring` function to check for should-be-dead objects.
This PR also makes object iteration consistent across all object types, both to reduce code duplication and to ensure that the length and iteration are done using the same algorithm.  Furthermore, if the number of should-be-dead objects is nonzero, the Lua array count for that frame will be different from the internal array count for that frame.
Fixes #5034.
In draft status pending tests.
=> more robust object iteration

code/mission/missiongoals.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/parse/sexp.cpp
To avoid changing behavior of existing mods, simulate the retail behavior unless the bugfix is explicitly activated.  The buggy retail behavior is to evaluate a chained event, not skip it, if the event is repeating, regardless of whether the repeat timestamp has elapsed.
"Fixes" #5005.
=> restore retail behavior of chaining to repeating events

code/scripting/api/libs/mission.cpp, freespace2/freespace.cpp
Fixes #4755 ~~by making sure the timer is not ever paused during a mainhall game state. We can't rely on UI-specific code to restart the timer after mission load if SCPUI is being used, so it should be done whenever the mainhall is entered probably. I didn't do a deep dive into the timer functions, so maybe there's a more appropriate fix elsewhere.~~
-by adding the ability to run `game_level_close()` from the scripting interface.
=> SCPUI needs to be able run game_close_level

fred2/orienteditor.cpp
Fixes #4564 by limiting input to `INT_MAX` whenever we're converting the string to a float. qtFRED limits input while typing, so this fix isn't needed there.
=> Disallow overly large input in FRED Orientation Editor

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Fixes #3100 and Mantis 2107 by doing a quick check for dogfight weapons for each ship in the loadout if the mission is a dogfight mission. If not at least one weapon for each ship type then show a warning.
=> Warn dogfight weapons

code/missionui/missionbrief.cpp
Fixes #5083 by making sure that we set the frametime counter for highlight icons and also reset them between stages.
=> fix api brief map not rendering icon highlight arrows

code/parse/sexp.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Also slightly enhances the debug log print to include the Operator name to make it easier to figure out which sexp is missing help text.
=> Add missing help for ship-untag sexp

code/asteroid/asteroid.cpp, code/mission/missionparse.cpp
PR #5058 made `count_incident_asteroids()` use `Asteroid_obj_list` instead of `obj_used_list`; a perfectly sensible change in and of itself. However, PR #4827 had previously made `asteroid_obj_list_init()` only be called if FRED wasn't running (presumably because of the iteration through `Asteroid_objs` to clear flags, which is wasted effort in FRED). The problem is that without `list_init()` being called on `Asteroid_obj_list`, its `prev` and `next` were `nullptr` instead of linking back to itself, which means the beginning of the list and the end of the list were no longer considered the same (the iterator's `begin()` calls `GET_FIRST(head)`, which is effectively `head->next`, while `end()` calls `END_OF_LIST(head)`, which is effectively just `head`). This meant that iterating over …
=> Avoid calling `asteroid_add_target()` in FRED.

code/parse/sexp.cpp
When checking sexp text strings, make sure to account for usages of `<argument>`
fixes #5099
=> Fix regression in sexp argument saving

code/mission/missionparse.cpp, fred2/initialstatus.cpp
"None" is a valid team color setting so we don't need to warn in the log and then set team color to "none". Also fixes a small bug where FRED would never show "None" as selected in the Initial Status dialog box.
=> fix team color parsing

fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Asteroids is a 0 based index so we need to subtract one here to prevent skipping the first debris item in the list
=> don't skip first debris item

code/anim/animplay.cpp, code/anim/packunpack.cpp, code/anim/packunpack.h, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/generic.cpp
As discussed in #5064, there is a piece of legacy code in the graphics initialization code that references a "screen signature". Back in the olden days, this value was used to track whether or not certain data needed to be reinitialized in response to changes in the graphics environment; this is no longer a concern with our current render backend.
Closes #5064
=> Remove the screen signature

code/render/batching.cpp
This addresses behaviour described in #5112. Profiling reveals that we are spending a lot of time per frame updating the buffers we use for batched rendering, even if the batches are nominally "empty" and thus wouldn't be rendered. This shows for example in cases where a lot of trails are spawned; even once all those trails have expired, the buffers created for them are still opened and updated, which involves a round trip through the GPU driver and PCIe bus, with all the overhead that implies. 
The change here removes the buffer update in those cases, meaning that while batch rendering itself might still be slow in extreme cases (see #5112 for an example mod and mission), it will no longer incur a _permanent_ performance penalty.
This is part of an ongoing effort to improve the …
=> do not update the gl buffer for a batch if the batch is empty

code/parse/sexp.cpp
I should verify during each loop that we have a sexp parameter to evaluate or it could trigger an assert.
Also when the sexps were consolidated I missed removing this return so that asteroid fields could be deleted with num 0.
=> make sure we have an argument

code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp
* Expand upon some comments for clarity on assumptions and optimizations
* Define the CCF_NONE flag for posterity
Should resolve #5113 
I've confirmed a quick build test, but haven't tested on Debug or Release.
=> Fix and expand upon debug safety catcher for ccfg.tbl flag reading.

ci/post/release.mako
1. Change the "previous release" thread to 22.2
2. Change http to https
3. Link to the github Bug Triage page rather than the Mantis filter
=> update the .mako file for release posts

code/asteroid/asteroid.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/weapon/shockwave.cpp, code/weapon/weapons.cpp
In the same way that navbuoys aren't blasted by explosions, no-collide objects shouldn't be blasted either.
Fixes #5068.
=> don't blast no-collide objects

code/asteroid/asteroid.cpp, code/parse/sexp.cpp
If types aren't specified then the sexp logic ends early. This is another thing that I missed when making requested changes to the original PR. If the sexp logic ends early then fields cannot be removed by simply specifying 0 for the number of asteroids. So move these checks into the asteroid.cpp function that runs after asteroids have already been cleared but before new ones are created.
=> Move these checks into asteroid.cpp

code/weapon/weapon.h, code/weapon/weapons.cpp
`spawn_type` (or `spawn_wep_index` as I've renamed it) is at first an index into the raw parsed weapon names used in the flag, to be filled with the actual weapon info index later during parsing, but if the weapon cannot then be found at that time, that index into `Spawn_names` is kept as is and used as a weapon index resulting in odd scenarios where it will spawn random other weapons if any of the syntax was mispelled.
=> Improve handling of failure to find spawn weapons

code/object/objcollide.cpp, code/object/objcollide.h, code/parse/sexp.cpp, code/scripting/api/libs/mission.cpp
Whether a weapon has `PF_CONST_VEL` or `PF_BALLISTIC` depends on whether there is gravity *at the moment*, not just when it was fired.
=> Better account for runtime gravity changes

freespace2/freespace.cpp
This is another case of a bug introduced by a bugfix, in this case #3885.  The original bug inadvertently made sun glare work in most cases where it was supposed to.
This commit removes the check for lightshafts when drawing the sun glare.  Since sun glare can be drawn regardless of whether lightshafts are enabled, the only thing that matters is to check that the view is not shadowed.
Fixes #5089
=> fix sunglares when lightshafts are disabled

.github/workflows/build-release.yaml
Essentially, when a reusable (called) workflow is used, as in our Post Release Builds action, secrets must be explicitly included from the caller workflow via `secrets: inherit`.
=> Inherit secrets when publishing Release builds

code/weapon/weapons.cpp
Fixes #3156 by warning during parse if a beam has a damage factor != 0 and any armor, shield, subsystem factor != 1.0 while beam damage factors are disabled in game_settings.tbl.
=> Warn if beams have damage factors while damage factors are disabled

code/menuui/playermenu.cpp
1. Be consistent about the check for `Player` being null, as the `Player` variable may be used later in the function without a null check
2. Return early if there are no tips to show, so as to prevent a crash
3. Use `Random::next` rather than `frand_range`
4. Use `SCP_string` to avoid string overflow
Fixes a crash discovered in Star Fox: Event Horizon
=> patch player tips

code/ship/ship.cpp
Adds a simple check to make sure we have at least two linkable weapons. If not, then skip linking. Fixes #5124
=> Check if we have at least two linkable weapons

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/scpui/RocketRenderingInterface.cpp
By default SCPUI/librocket follows FSO's trend of substituting `2_animname.ext` for `animname.ext` if the game's resolution is larger than a certain amount. SCPUI can correctly scale animations dynamically so this behavior isn't required anymore. 
The substitution can be a problem in the case of naming conflicts with upstream files. A local mod may have a hires cb_default but the game hands over the retail 2_cb_default instead. That is not ideal. However, there may still be situations (retail/mediavps) where it would be preferred to get the hires filename in place of the normal one. So this PR allows a quick toggle to enable or disable the behavior for SCPUI.
=> Allow way to prevent scpui loading hires animations

code/ship/ship.cpp
Fixing a 9 year old bug with a single line change. If we're not showing primary weapon models then we don't need to look up any of its information at all, including where to fire from. Fixes #3112
=> If we're not drawing weapon models then skip all this

code/weapon/trails.cpp
There's an early out in trail rendering that just seems pointless and weird to me, having trails on the player go unrendered in a very narrow set of view modes. So, I deleted it.
=> Removed unhelpful optimization from trail rendering

code/hud/hudsquadmsg.cpp, code/hud/hudsquadmsg.h, code/ship/ship.cpp, code/ship/ship.h
As requested by Wookie, this PR does a few things to verify some order-sending things. 
First it checks that at least one ship in a wing can depart before marking the order as allowed on the Comms Board. 
Second it enhances `ship_get_random_ship_in_wing()` to be able to check if a ship can actually perform an order. If it can't, then don't select the ship. This prevents ships that can't perform a "wing" or "all ships" order from acknowledging the order as if they can.
=> some validity checks to order sending

code/ai/aicode.cpp
Meant to address #5150 , but does not resolve it. This function is a red flag in terms of possible sources for a -1 `current_secondary_bank`, lots of values initialized to -1 and then possibly written to it later. But without a test case its difficult to know what set up of weapons and priorities would actually cause that to happen, so best we can do is at least assert this function didn't mangle it, and to put back whatever was there.
=> better safety for `ai_select_secondary_weapon`

code/ai/aicode.cpp
Fixes #5150 by bailing early if there are no valid weapon choices to choose from. Prevents `swp->current_secondary_bank` from getting set to -1 and then never set since there's no options for the ai to set it to.
This can happen in the case of the mod using ai range awareness and the ai not having any targets in range. In this specific case `get_available_secondary_weapons()` correctly returns a value of 0.
=> Don't try to choose a secondary if there are no choices

code/ai/aicode.cpp
When using/finding a second priority weapon, only assign if you actually found something. Fixes #5155
=> Dont assign a possibly -1 priority2_index

code/ai/aiturret.cpp, code/scripting/hook_conditions.cpp, code/scripting/hook_conditions.h, code/ship/ship.cpp, code/weapon/beam.cpp
Supercedes #5086.
Fixes #5080.
This is the IMO proper way of fixing the bug in question.
With this change, the hook behaves as it is documented.
Previously, if a weapon class was specified, the hook would only fire if the selected weapon matches the weapon class. Now, the hook will fire if any fired weapon will match the weapon class.
At the same time, the hook will, as before, only fire once per gun trigger, keeping scripts working as intended with no change.
=> Fix WeaponUsedConditions

code/ai/aibig.cpp, code/ai/aicode.cpp
Turns out #5156 / #5153 / #5151, i.e. not setting `current_secondary_bank` to -1, was a load-bearing bug, because of course it is. This is in practice how the AI knows that none of its secondaries are valid and to not fire, as there are plenty of checks for `current_bank >= 0` when it comes time to fire. I think this was more a happy coincidence than truly intentional though, so this PR simply has the secondary choosing code return whether or not a valid secondary has been found (and so can differentiate 'stayed on the same bank because this is a good weapon to fire' and 'stayed on the same bank because all my options were bad') mimicking the previous behavior of setting to -1 without actually setting to an invalid index. 
Fixes #5166
It doesn't appear to be related to 'smart secondary …
=> Fix inadvertent AI usage of invalid weapons

code/scripting/api/libs/ui.cpp
We should clear the credits string before rebuilding it to prevent it appending over and over upon itself if run multiple times during a play session.
=> Clear credits before rebuilding

code/scripting/api/objs/order.cpp
Turns out setting a waypoint order then trying to get to target of that order in the same frame triggers a crash in the scripting API for ship orders (`order.cpp` line 295). This was due to invalid lookups which lacked safety checks.
This PR adds those safety checks. Now, if this situation is encountered, it leaves `objnum` at -1 and thus returns an object for which `isValid` is false.
Fix is tested and works as expected. Also fixes #5172. Thanks @BMagnu for the additional assistance!
=> Adds safety checks to scripting orders with waypoints

code/parse/sexp/EngineSEXP.cpp, code/parse/sexp/EngineSEXP.h, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/LuaSEXP.h, code/parse/sexp/sexp_lookup.cpp, code/parse/sexp/sexp_lookup.h
1. Allow categories, not just subcategories, to be added by scripted SEXPs.
2. Allow subcategories in different categories to have the same name.
=> more category updates

code/ai/aiturret.cpp, code/parse/sexp.cpp, code/parse/sexp.h, code/ship/ship.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
Really just a FREDing QoL thing, but this implements opf_turret_type to for turret-protect-ship and turret-unprotect-ship since they can only accept these 4 types anyway. But also makes it easier to enhance in the future if additional turret types are defined.
=> Implement opf_turret_type

fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
An idea came up during a BtA team FREDing session to make node comments in the event editor more visible by including them in the help text box. This PR implements the feature. For root "Event" nodes it will display any comments instead of being blank. For Messages and Sexps any comments will be appended to the message text or sexp help.
qtFRED does not yet have support for node comments, so the base code is added where it should be, but commented out until Goober finishes porting the feature.
=> Make sexp node comments more visible at a glance

code/localization/localize.cpp, code/mission/missionparse.cpp, code/mission/missionparse.h, code/parse/parselo.h, fred2/freddoc.cpp, fred2/missionsave.cpp, freespace2/freespace.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/missionsave.cpp
This finally enables the `$Version:` field in FreeSpace missions, which has been present ever since the beginning of FS1's development but has never been used for its intended purpose.  This field now stores the version of FSO that is required to run the mission.  If the version of the engine is not sufficient to run the version of the mission, then a) the mission is hidden from the mission listing, or b) a friendly notification is displayed if the mission is loaded anyway (for example, through a campaign).  Furthermore, FRED will notify the user if the mission's version is migrated from any version other than the legacy 0.10.
It will be the responsibility of coders who modify the mission format to also update the `MISSION_VERSION` constant with the appropriate major/minor/build/revision …
=> add versioning support to missions

code/mission/missionparse.cpp, code/mission/missionparse.h, fred2/dumpstats.cpp, fred2/management.cpp, fred2/missionnotesdlg.cpp, fred2/missionsave.cpp
Change author from a char array to a basic string.
This particular string is never used outside of FRED and SCPUI, both of which handle it internally as CString and SCP_string, we're just truncating it to pass it around internally. The FRED field allows unlimited input and SCPUI can handle long strings in a more modern way (can wrap, auto-overflow, etc). So let's just keep it as a string and remove the limit entirely.
=> increase mission author name length limit

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, freespace2/freespace.cpp
As requested by @wookieejedi . This allows to specify a list of splash screen bitmaps in game_settings.tbl and then one will be chosen at random to display on game init. If the vector is empty then it defaults to pre_load/2_pre_load as is the current behavior.
=> choose random splash image

code/model/model.h, code/model/modelread.cpp, code/ship/ship.cpp
Adds a boolean to glowpoint overrides that allows forcing the bank to default as off. Useful for glowpoints that cast light, making sure they are off in the tech room, ship/weapon select and other places.
=> Override to set glowpoint bank to default off

code/menuui/mainhallmenu.cpp
Removes some older mainhall shortcuts from debug that have outlived their usefulness and get in the way of newer features like mainhall cheats.
=> Remove some old debug key checks in mainhall

code/scripting/api/libs/graphics.cpp
I realize this one is inherently risky because if someone uses it at the wrong time, fun things could happen. However, as SCPUI becomes more fully featured I have run into issues regarding having too many models loaded and giving the scripts a way to cleanup after themselves seems like a good idea.
For example; if 3D ship and weapon selection is enabled then the current SCPUI scripts will, during the first mission load of an instance of FSO, load and render every player allowed ship and weapon to a texture, saving each to a png blob for use in ship and weapon selection. In practice it works well, but lower end computers ran into out of memory errors.
I instead moved that whole function to On Game Init which solves the out of memory during a mission load for those computers (because FSO …
=> Lua method to free all loaded models

code/cheats_table/cheats_table.cpp
Removes the requirement for cheats to have a +Message entry and puts some checks in place so that we only try to send a message if the message has length and we're actually in a mission. (Without the latter, the game will assert and these cheats are triggerable anywhere in the game!)
With this in place you can define cheats and use the On Cheat hook to do any kind of cheat just about anywhere in the game very easily.
=> Remove message requirement for custom cheats

code/parse/sexp.cpp, code/parse/sexp.h, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Adds the sexp to check the current armor of a ship or ship's subsystem. Fixes #2854
=> has-armor-type sexp

code/weapon/emp.cpp, code/weapon/emp.h
Follow-up to #5138.  Tweak the function header to be more compatible with different build environments; some don't like the `= ""` for some reason.
=> build compatibility fix

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp
Due to being connected to rendering, player thruster starts and stops wouldn't play in the cockpit, were played at the wrong location in 3d space and loops wouldn't play at all due to lacking `OS_PLAY_ON_PLAYER`. This inconsistent behavior is fixed and splits out sounds into their own function, and additionally a flag is added in order to hear player thrusters at all, similar to turret sounds which I think makes sense.
=> Fix thruster sounds and add flag for player thruster sounds

code/scripting/api/libs/audio.cpp
Allows pausing and unpausing weapon sounds. Meant to be used with SCPUI to mimic how FSO will pause music and weapons when changing game states during a mission.
=> Expose pausing weapon sounds

code/ai/ai_profiles.cpp
This PR fixes #3456 by allowing `gameplay_profiles.tbl` to be an alias of `ai_profiles.tbl` . There is precedent for this with `intel.tbl` <-> `species.tbl` and this works PR exactly the same way.
=> Allow gameplay_profiles.tbl to be an alias of ai_profiles.tbl

code/localization/localize.cpp, code/network/multi_pinfo.cpp, code/network/multi_pxo.cpp, code/network/multiui.cpp, code/pilotfile/pilotfile.cpp, code/pilotfile/pilotfile.h, code/playerman/managepilot.cpp, code/stats/medals.cpp, code/stats/scoring.cpp, code/stats/scoring.h, freespace2/freespace.cpp
Free Ranks from their retail shackles. Vectorizes Ranks and adds bounds checks to places where it's accessed. Removes the limit of 10 and assumptions that ranks will match retail's 10. UI elements that display rank will check if the player rank > than the current max. If so, display the max without changing player rank. Adds modular -rnk.tbm parsing with +nocreate support. 
Disallows Ranks to have equal values and will automatically increment one of them by 1 point if detected and log the change. Will then auto sort ranks after all parsing is done if Ranks is not ordered by point values or Rank equality is detected. Will warn if auto sorting is done and log the changes.
=> Modular rank table

code/missionui/fictionviewer.cpp, code/missionui/fictionviewer.h, code/scripting/api/objs/fictionviewer.cpp
Implements true fiction viewer localization. If language setting is not English then it will try to find the fiction viewer file with the language extension applied. If the file specified is `somefile.txt` then it will search for `somefile-gr.txt`, for example, if the language setting is German. If that file is not found then it will default to the base filename `somefile.txt`.
Also updates the scpui virtvar with the same code.
Fixes #1836 for real this time
=> fictionviewer localization

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/localization/localize.cpp
While you can set the language in Knossos, it (currently) only allows for the four built-in languages. This will accept any string and checks it against the language settings in the strings.tbl. Will set the language first by commandline. If that doesn't get a valid language it will fall back to past behavior and check the INI file/registry.
Set it like so `-language German`
This is the first step towards creating an SCPUI in-game language option (that would require a restart).
=> enable commandline language setting

code/mission/missionparse.cpp, code/mission/missionparse.h, code/parse/sexp.cpp, code/scripting/api/objs/object.cpp, code/scripting/api/objs/parse_object.cpp
Add collision groups to parse objects so they can be set before arrival via script.
=> make collision_group_id accessible to parse objects

code/graphics/2d.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/scripting/api/libs/engine.cpp, code/scripting/doc_html.cpp, code/scripting/global_hooks.cpp, code/scripting/global_hooks.h, code/scripting/hook_api.cpp, code/scripting/hook_api.h, code/scripting/scripting.cpp, code/scripting/scripting.h, code/scripting/scripting_doc.h, fred2/management.cpp, freespace2/freespace.cpp, qtfred/src/mission/management.cpp
Adds the ability to deprecate scripting hooks and does so with the OnDeath and the OnSplashScreen hooks.
Fixes #4742 and closes #3171.
This PR approaches hook deprecation with two stages:
There is a warn-type deprecate that will warn but run the hook if the target version is below the deprecation version, and error out if the target version is the same or above the deprecation version.
Secondly, there is an error-type deprecate that will always hard-error if a user attempts to use it for situations (like the OnSplashScreen override) where function of the hook / override cannot be feasibly enabled, even in a limited fashion for mods targeting older versions.
In addition, these override-modes can be set differently for the actual hook and its override, if applicable.
=> Add option to deprecate hooks

code/popup/popup.cpp, code/scripting/global_hooks.cpp
Adds the keypress as a string to the On Dialog Init hook variables. Fixes #5048 .
Death popups don't seem to have a keyboard shortcut so it remains nil in that case.
=> Pass shortcut key character to Lua as a hook variable

code/globalincs/version.cpp, code/globalincs/version.h, code/mission/missionparse.cpp, fred2/freddoc.cpp, fred2/missionsave.cpp, freespace2/freespace.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/missionsave.cpp
Since older builds of FRED parse the mission version as a float, the version can contain a maximum of one decimal point.  These changes allow FRED and FSO to disregard the build number when loading, saving, or comparing versions.
There is also a small fix to qtfred's saving of the author field.
Follow-up to #5152.
=> mission version numbers should be major.minor

code/debris/debris.cpp, code/mission/missionparse.cpp, code/model/model.h, code/model/modelinterp.cpp, code/scripting/api/objs/model.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/starfield/supernova.cpp, code/weapon/beam.cpp
`GetVertex` allows for retrieval of specific vertices or random ones, and with `NumVertices()` a scripter could even do some advanced 'model parsing' type operations if they were feeling spicy, but random retrieval was my main goal.
Additionally, cleans up `submodel_get_two_random_points_better` a bit, there's no real reason for this function to get two points at a time, even if that's a common case, resulting in awkward scenarios where callers need to declare useless temporaries when they only need one. Instead it should return a single vertex, and you can call it more than once if you need more (and for what it's worth, the Shivan Comm Node *does* have a collision tree).
=> Add `GetVertex()` and `NumVertices()` script functions and clean up random submodel point retrieval a bit

fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp
Prevent the Windows error beep from sounding by capturing key characters sent to the window.
On a related note, change Asserts to returns so that FRED catches invalid child nodes when getting default argument values.  This prevents FRED from crashing if an invalid operator is entered manually.
=> deblongify fred

code/ship/shipfx.cpp
This allows, for instance, scripts to make a ship do the warp out effect but without actually removing it from the mission. Should make imjump scripts and sexps much simpler and cleaner.
=> On warp complete hook

code/menuui/credits.cpp, code/menuui/credits.h, code/scripting/api/libs/ui.cpp
If we're building the credits string for SCPUI or other API access, then we aren't concerned with the retail credits UI string length limit, so skip the line splitting and return the whole string unaltered.
=> Prevent line splitting if building credits for SCPUI

fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
In PR #5202, a bunch of `Assert(child >= 0);` statements were replaced with `if (child < 0) return nullptr;`, except the first one kept the assertion's condition (inverting the logic). This fixes this accidental inversion.
=> Fix negative child check inversion.

code/nebula/neb.cpp, code/nebula/neb.h, fred2/bgbitmapdlg.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
Removes MAX_NEB2_BITMAPS which was previously just 10; a limit I hit just but modularizing the MediaVPs nebula.tbl which only adds three bitmaps to retail's 8. Instead of simply raising the limit this PR vectorizes the bitmap list. Bitmaps are only ever referenced by name (unlike poofs which use flags) so it makes sense to just make this a quick vector of strings.
Sneaks in one small QoL parsing feature to check for end of file in a modular table so that -neb.tbms which don't specify poofs won't require two #end lines.
=> Remove nebula bitmap limit

code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ship/shiphit.cpp
Poor Nuke was clearly aware of the risk of accidentally applying player damage difficulty scaling more than once, but alas, that's what's happened.
The code is really pointlessly confusing (which may have contributed to the bug being written), so I've tried to give it a good makeover and comment more. 
The main issue is that shockwaves and area blasts will erroneously always report as having hit the shield, usually not a big deal, it checks the shield is empty, so in essence all of the damage overflows to the hull anyway. However, damage difficulty scaling *is* applied to the damage before being passed to the hull damage calculation, where it gets applied *again*, squaring the scale factor and possibly greatly changing the damage in effect. So, unless the backwards compatible flag is …
=> Fix some issues with damage application

code/parse/sexp.cpp, code/parse/sexp.h, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/sexp_lookup.cpp
Adds ability to pre-define Lua Sexp Enums like the following example.
> #Lua Enums
> 
> $Name: Factions
>   +Enum: Galactic Terran Alliance
>   +Enum: Parliamentary Vasudan Navy
>   +Enum: Regulus Syndicate
> 
> #End
This changes inline Enum parsing to check for a previously existing Enum list and will use that if the name matches. However, if +Enum is then specified a new Enum list will be created with the original as a base and the new entries added.
Fixes #2246
=> add pre-parse enums support

code/debris/debris.cpp, code/model/model.h, code/model/modelcollide.cpp, code/object/collideshipweapon.cpp, code/weapon/beam.cpp
Adds `MC_COLLIDE_ALL`, which will accrue all hits including those against backfacing polies into a vector. Since this makes `mc_info` not trivially memcopyable anymore, they're replaced with typical deep copy assignments.
This flag is not yet used, but will be for a feature in development by @BMagnu
=> Add collision flag for colliding with all polies

code/ai/aibig.cpp, code/ai/aicode.cpp, code/ai/aiturret.cpp, code/asteroid/asteroid.cpp, code/debris/debris.cpp, code/hud/hudtarget.cpp, code/model/model.h, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/object/objcollide.cpp, code/scripting/api/objs/object.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/weapon/beam.cpp, fred2/fredrender.cpp, qtfred/src/mission/EditorViewport.cpp
This initializes `mc_info` to the correct values when it is constructed, removing the need for `mc_info_init`.
This PR also fixes a group of incorrectly inverted assignments in beam.cpp.
Follow-up to #5212.
=> add initializers to mc_info

code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/sexp_lookup.cpp
Review of #5036 suggested to me that we should be checked for duplicate enum items here, too.
=> Check duplicate enum items

code/object/objectsnd.cpp
Presumably for almost-certainly-now-irrelevant performance reasons, object sounds are not updated every frame, but with maneuvering thruster sound loops or fast weapons even 100ms can be noticeable, so I think we can afford to drop it down some more.
=> Increase sound update rate

code/mission/missionlog.cpp, code/mission/missionlog.h
Reorganizes how the mission log scrollback is initialized and drawn. Instead of separate linked lists for timestamp and entries, this uses a single vector for each line. The vector entry holds all the required information required for drawing, including text, color, etc. This will make SCPUI access much easier in a follow-up PR.
Tested viewing the scrollback with a small log (no scrolling required), a large log, and with as many different entry types as I could reasonably come up with. Each type of log entry seems to work exactly as it did before.
=> Refactor mission log scrollback

code/localization/localize.cpp
Changes built-in strings from an array to an unordered map very similar to translated strings. The main advantage here is places like Custom Controls being able to define an arbitrary xstr ID instead of having to find one that's unused or can be replaced from within the current limitation of 1672 strings.
This solves one of the barriers mentioned in #4523
=> Mapify builtin strings

code/localization/localize.cpp, code/mission/missionlog.cpp, code/parse/sexp.cpp, code/parse/sexp.h
Both #5210 and #5157 contained memory leaks caused by calling vm_strdup but not freeing the strings.  This fixes those and a few other things:
1. keep localization text types consistent
2. be more scrupulous about checking for the existence of entries in localization maps
3. use some SCP_string and const reference optimizations in `get_dynamic_enum_position`
=> 5210 and 5157 followup

code/ai/aicode.cpp
Many values in `ai.tbl` can be inserted as overrides for their equivalent `Ai_profiles.tbl` values. (They are all optional and if not set for an AI class, the values in AI Profiles will be used.)
This is particularly useful for making very specific AI classes that still follow the main AI profiles table with easy to change values.
This PR adds `$firing requires exact los:` as an optional override to set in `ai.tbl`. This particular override is very useful, since it can be set to off by default in the `ai_profiles.tbl` for performance, but then set to on for some select AI classes within `ai.tbl`, and those AI classes can be easily changed on the fly in a mission.
=> Add `line of sight` as optional AI override

code/starfield/starfield.cpp
Fixes an issue since fs1 where the apparent brightness of stars would fluctuate wildly based on how quick the camera was moving since their brightness is not adjusted at all, yet each star is given many pixels spread over its 'trail' across the sky. I wasn't sure why square root of the length looked good, but as pointed out by qazwsxal, it approximated gamma correction, so the typical 2.2 value is used instead to better match it.
Now stars look... completely normal, regardless of whether your camera is moving or not!
Before: 
https://user-images.githubusercontent.com/17305613/221725872-b09cc9cc-4b7e-48e1-af5d-19a28c7b41b5.mp4
After:
https://user-images.githubusercontent.com/17305613/221725894-4cf1fcdb-0a2c-4a8b-bcc5-c27e98cea151.mp4
=> Fix retail star look by applying gamma correction

code/scripting/global_hooks.cpp
Small oversight from #4960. This used to be "User"
=> Fix On Beam Fired hook variable name

code/menuui/techmenu.cpp
Sets up the techroom to render the weapon tech model (if it exists), if no weapon tech anim is specified. Fixes #3099 and Mantis 2762
=> Use weapon tech model if no anim

code/gamehelp/gameplayhelp.cpp, code/gamehelp/gameplayhelp.h
Refactors the in-mission gameplay help with SPCUI in mind. Instead of defining text strings at the same time as drawing them, it now inits all the help text into a vector of help sections first. On frame it will draw the current section. Special handling is in place to deal with some minor unique retail UI cases (like function keys).
With this in place, Lua can be granted access to the vector of help text much easier in a later PR so that the UI can be replicated in SCPUI.
=> Refactor gameplay help

code/mission/missionmessage.cpp, code/mission/missionmessage.h, fred2/shipeditordlg.cpp, qtfred/src/ui/dialogs/ShipEditorDialog.cpp
Implements features from #5020:
1. Personas can now be assigned to multiple species
2. Personas can be excluded from automatic assignment if the game picks a random persona
Also removes the obsolete `PERSONA_FLAG_VASUDAN` and turns the `substitute_missing_messages` field into a proper flag to match the others.
Additionally, this fixes the addition of the -Vas suffix on the wingmen personas in FRED, which had been broken since the species_defs upgrade.
=> Persona species enhancements

code/ship/shiphit.cpp
Follow-up to #5084. This got missed when things were re-arranged, damage scaling applies only to the hull and shields, not to subsystems. Fixes #5228
=> Fix damage scaling oversight

code/ai/aicode.cpp
Fixes #4484 . Looks pretty silly on fighter AI with all the flags enabled, but otherwise works as expected, making them consistent with the player using the same flags.
=> Update some movement flags to work for AI too

code/controlconfig/controlsconfigcommon.cpp, code/io/joy-sdl.cpp, code/lab/renderer/lab_renderer.cpp, code/localization/localize.cpp, code/missionui/missionshipchoice.cpp, code/playerman/playercontrol.cpp
Add some entries for "or" and "None", mostly in the controls code.  Note that there is already an XSTR entry for "none", but it does not have the right capitalization.  Also note that "None" is localized in `textify_scancode` but not `textify_scancode_universal`.
This also makes "Nothing" cargo use appropriate localization.
Fixes #5227.
=> add some XSTR entries

code/mission/missionlog.cpp
Changes the mission log scrollback to use subsystem names (display names if they're available) instead of model subobject names. This makes the scrollback names match what the HUD displays. Fixes #5187
=> Use subsystem names instead of model names

code/model/modelrender.cpp
Follow-up to #88. The 'thruster length' this is being compared to is in the local frame so compare to the thruster normal in the local frame as well. Ensures the 'flicker' is consistent regardless of the orientation of the ship, only the direction of the thruster and the direction of thrust, as intended.
=> Small fix for thruster flicker

code/graphics/2d.h
When profiling, you want to have GL debug information available on release builds. This gives you a better idea where there's bits with poor performance.
Without:
With:
=> Enable debug scope on release builds

code/missionui/missionbrief.cpp, code/missionui/missionbrief.h, code/model/modelrender.cpp, code/model/modelrender.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/shipclass.cpp, code/scripting/api/objs/weaponclass.cpp
This PR does three main things. First it adds an ADE_FUNC to check the mouse position against briefing icon positions. Returns the relevant icon information if the mouse if over one and also causes that icon to switch to the "highlight" frame. Second, it changes up the unified `render_tech_model()` function to allow for rendering an arbitrary POF in the same style and with pretty much the same arguments. This is necessary to handle unique briefing icon closeup cases such as "asteroid" and "unknown". Third it adds the ADE_FUNC `renderBriefingModel` which takes a POF instead of a ship or weapon class.
With this in place, SCPUI can recreate retail's ability to hover and click on briefing icons.
=> SCPUI methods required for handling closeup briefing icon stuff

code/model/model_flags.h, code/model/modelread.cpp
Even in zookeeper's original commit this flag was vestigal, and thruster movement on moving engine subsystems was done unconditionally!
https://github.com/scp-fs2open/fs2open.github.com/commit/bcf9fd90bef5c1f5229cc561d9d543ef89e81f4d
=> Remove `Attach_thrusters` submodel flag

code/asteroid/asteroid.cpp
Chucked asteroids are always large. Therefore use their speed, not the speed of the 1st parsed/small asteroid. Should not affect retail because it uses the same speed for all three asteroids
=> use large asteroids speed when chucking asteroids

code/ship/ship.cpp, code/ship/ship.h, code/weapon/weapon.h, code/weapon/weapons.cpp, freespace2/freespace.cpp
Works very similarly to the recoil multipliers, only affecting camera shudder instead of physical recoil. Both the ship and the weapon can have multipliers allowing them to behave differently than their mass x velocity might suggest.
=> Add shudder multipliers

code/parse/sexp.cpp
Hotfix to fix incorrect error display meant for LuaSEXPs from displaying for normal sexps.
=> Check the op const, not the op dummy

code/model/modelread.cpp
This bit of code to override turret rotation axes will erroneously trigger on subobjects that are children turret gun objects, and messing up the turret. So instead defer the checks until after parsing, and based on the actual base/gun pairs for each turret, instead of guessing based on the name. 
It's a little cruder than I'd like but the logic and sequencing is a bit fragile. Moreover, unless I'm mistaken I believe this operation is entirely skipped for virtual pofs with turrets added after the fact, @BMagnu may know more.
=> Adjust movement sanity checks to account for more situations

code/hud/hudparse.cpp
Looks like the last time this list was updated was in commit 2cded900317a850b8dcc9f9bc173f2f127bab7ab, and other gauges have been added since then.  So let's update the list.
~~In draft pending tests.~~ Tested and works.
=> add missing HUD gauges

code/model/modelread.cpp
If a submodel doesn't have a parent, set `parent_sm` to nullptr instead of an invalid value.
Follow-up to #5240.
=> fix submodel sanity check

code/parse/sexp.cpp
This fixes some issues with how Lua SEXPs with subsystem or dockpoint parameters will work in sexp.cpp error checking. I got lucky in my earlier tests in that my specific set of test sexps passed the checks by just happening to have the right parameters in the right places to match existing built-in sexps.
My earlier code was a copy/paste from sexp_tree.cpp to here, assuming it worked the same but of course it's just slightly different. Here the code is running down the entire node tree instead of just a specific sexp, so we have to compensate for that. Instead of returning the index to the parent parameter within the single node, I need to get the index of the parent parameter within the entire sexp list. A matter of simple math. But also since in this case sexp node names count in the …
=> fixup error checking in regards to sexps using dynamic parameters

qtfred/src/mission/missionsave.cpp, qtfred/ui/BriefingEditorDialog.ui
These patches fix compilation of QTFred. I have tested them on Debian Linux 12 Bookworm amd64.
Linux 6.1.0-5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1 (2023-02-15) x86_64 GNU/Linux
g++/gcc (Debian 12.2.0-14) 12.2.0
=> Fixes for Missionsave.cpp and BriefingEditorDialog.ui

code/mission/missionlog.cpp
The more specific `sub_name` (which `ship_subsys_get_name` retrieves) is copied from `alt_sub_name`, so this should be equivalent, and doesn't rely on the ship still being around.
=> Fix a bug in mission log with subsys names

code/weapon/corkscrew.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Closes #5272. Adds the ability to set the angle on the corkscrew the weapons starts on. Either random, or a specific angle, for now.
=> Add some parameters for corkscrew starting angle

code/hud/hudmessage.h, code/mission/missionlog.cpp, code/mission/missionlog.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/missionlog.cpp, code/scripting/api/objs/missionlog.h, code/source_groups.cmake
API access to the elements required for the mission log UI.
EDIT: I should add that this also slightly changes how log entry flags are done. The flags are used only for Goal True or Goal Failed and all they functionally do is tell the game whether or not to draw a little circle next to the log entry filled with either red or green. In the past this was saved to the log entry action item (there are multiple actions (bits of colored text) per log entry. It makes little sense to have to parse all of those for each action since it applies to the entire entry no matter what. So now we save the flags to the parent "objective" item only and look there.
=> Scpui Mission Log

code/def_files/data/effects/main-f.sdr
Noticed an issue with gamma correction being overzealously applied to the emissive channel, resulting in envmap shines being too dim, likely introduced by #5055 . 
The emissive channel is a bit weird, as multiples sources are added together during g-buffer creation, this means it's better to convert everything to linear colour space when you're reading from the textures rather than waiting until the end.
=> FIX: Incorrect gamma calculations in shaders.

code/graphics/opengl/gropengltexture.cpp
Exposes texture filtering among the graphics options in the Options Manager. I'm not 100% sure if this one would require a game restart, but for now, it does because that's safer.
=> Expose texture filtering as a built-in option

code/lab/manager/lab_manager.cpp
There's a gui button for this too, but the hotkey is still listed in the ui text and it's a bit more convenient for doing large batches of these, so I put it back in.
=> restored the keyboard hotkey for envmap export.

code/io/timer.cpp, code/io/timer.h, freespace2/freespace.cpp
EDIT: reverts scp-fs2open/fs2open.github.com#5266
Alas async and mission time are not acting reliably after this commit. Seems like removing the `if (start_frame)` check fixes things, but of course that's not the proper fix since that just restores the old behavior. ~~I've tried tracking things down and updating places where I think things should go, but no luck so far. It looks like Goober is pretty busy with RL ATM too, so I'm going to post this revert PR to fix the bug in the interim.~~
From Goober on Discord:
```This will need a proper investigation but I don't know how much time I'll have in the next few days to look at it. I think 5287 is thinking along the right lines but is not actually the correct fix. I'd say that leaving the missiontime and time compression bugs in the nightly …
```
=> Revert "synchronize simulation timestamps across the entire frame"

code/mission/missionhotkey.cpp, code/mission/missionhotkey.h, code/scripting/api/libs/ui.cpp
Toggle caused the list to load different each time it was called. This enforces the same behavior every time.
=> Force expand wings instead of toggle for scpui

code/mission/missionmessage.cpp, code/mission/missionmessage.h, code/mission/missionparse.cpp
Historically, there's been a hardcoded 25% chance for Command to announce an enemy wing arrival. This is problematic for mods without Command, like BTA.
=> Dehardcode Command arrival message chance

code/ai/aiturret.cpp, code/scripting/api/objs/subsystem.cpp
Just like ship primary weapons (and indeed using the basically the same code/logic), if multiple weapons of the same launch_snd are played at the same time, only play it once, otherwise you'll get ugly audio artifacts.
=> No overlapping turret sounds

code/ai/aicode.cpp, code/weapon/weapons.cpp
If a team explicitly attacks itself, then the same-team checks should not apply.  Fixes a bug reported by SilverAngelX on Discord.
=> fix IFF logic for teams that attack themselves

code/mission/missionparse.cpp
Command should not be considered if the mission explicitly prevents Command from sending builtin messages.
Follow-up to #5290.
=> additional constraint on Command arrival messages

code/weapon/beam.cpp
Type5 fighter beams are for several purposes not treated as 'having a target', the beam aims for straight forward regardless. For this purpose `usable_target` is used, and should also apply to the offset scaling, otherwise discrepancies will appear like the random offset scaling widly changing the beam's accuracy based on the distance to the target despite in this case always 'aiming' for a spot directly ahead at a fixed distance.
=> Small fix for type5 fighter beams

code/weapon/weapons.cpp
Fix for an annoying case I ran into, beam weapon behaved oddly because I forgot to add the "beam" flag. These flags are dumb. If they specified any $Beaminfo, it's a beam full-stop.
=> $Beaminfo implies "beam" flag!

code/ai/aicode.cpp, code/hud/hudets.cpp, code/hud/hudreticle.cpp, code/hud/hudtargetbox.cpp, code/mission/missionparse.cpp, code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/ship/ship.h
The ship's `current_max_speed` stores the max speed given the ship's ETS settings and it's what most things will read from, while every frame its own physics `phys_info.max_vel.xyz.z` is updated to that value. This indirection is harmful because it basically prevents any modification of a ship's max velocity through scripting through its physics values. Instead the `current_max_speed` should be removed, and `phys_info.max_vel.xyz.z` should be modified and acted upon directly, they store the exact same value (which was also enforced every frame).
Other changes in hudets.cpp meant to facilitate script access is that max speed should only be adjusted when the engine energy is actually adjusted, prior the speed was set based on engine energy every frame, even on ships without ETS.
=> Adjustments to max vel changes from ETS

code/hud/hudsquadmsg.cpp, code/mission/missionmessage.cpp
Fixes the issue identified in #5299 and another that BTA noticed with support ships and the new auto-assignment configuration.
=> Message filter follow up

code/ship/shiphit.cpp
This moves `LOG_SELF_DESTRUCTED` to the same place that `LOG_SHIP_DESTROYED` is recorded.  This allows self-destruction to be correctly recorded when a ship is self-destructed via script, as well as when it is auto-repaired with a negative hull multiplier, or when ships are killed off in in-game joining.
=> move self-destruct mission logging to ship_hit_kill

code/ship/ship.cpp, code/weapon/beam.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Although $LaunchSnd will attempt to play in 2d when appropriate, given that it is expected to be used in both 3d (others shooting) and 2d (you shooting) contexts, in practice modders are forced to make them 3d, and are unable to make use of nice stereo for their weapons. This adds $CockpitLaunchSnd, a separate sound only for the player, so the modder can use an appropriate dedicated 2d sound.
As always, diff is a bit cleaner with 'hide whitespace changes'.
=> Add $CockpitLaunchSnd

code/ship/ship.cpp
Allows to table sort of derived ships.
Behaves pretty much identical to templates (which should be preferred), but allows to use ships that may be present in a parent mod or are already tabled as templateless ships to be used as such.
=> Add +Use Ship as Template

code/model/model.h, code/model/modelread.cpp, code/model/modelreplace.cpp, code/model/modelreplace.h
Followup to #4590 and #4713.
Adds copying of dock points, paths, and weapon banks, pretty much completing, as far as I can tell the features for actually modifying pofs, save for anything that modifies the BSP tree.
Potential future upgrades at this point are (sub)model rotation (modifies BSP tree), replacing or removing things from a model, building models from individual vertices (modifies BSP tree) and Lua integration. However, as any of these are a rather substantial amount of work, I don't intend to implement them in the near future unless someone has actual need for it.
=> Modular POF Features 2

code/scripting/api/objs/subsystem.cpp
There can be cases where the subsystem cache is invalid, so just call the proper function here.
=> Fix Subsystem Serialization

code/mission/missionhotkey.cpp, code/mission/missionhotkey.h, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/enums.cpp, code/scripting/api/objs/enums.h, code/scripting/api/objs/missionhotkey.cpp
Here's a suggested followup to #5249.  This converts the hotkey type to an enum for improved type safety.  It also adds the corresponding Lua enums and adjusts the Type virtvar to return them.
=> convert hotkey types to enum

code/mission/missionparse.cpp, code/parse/parselo.cpp, code/parse/parselo.h
When parsing a list of numbers, such as in the $uvec or $fvec of models, a bug was reported where whitespace before the comma caused the number parsing to fail.  This change checks for a comma after whitespace instead of checking for a comma as the very next character.
=> check for whitespace between token and comma

code/mission/missionlog.cpp, code/mission/missionlog.h, code/scripting/api/libs/ui.cpp
Originally I had set this to just use the screen width for message lines, assuming no line could be more than that and lines would never be split for SCPUI. In hindsight, that was dumb and of course lower resolutions would run into problems. So this makes line splitting an explicit choice.
=> Explicitely do not split lines when making the message log

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Just like briefings and debriefs do, this way the user can just delete the field for the same effect.
=> Flush empty cbrief voice filenames to "None"

code/asteroid/asteroid.cpp, code/missionui/missionbrief.cpp
Implements part of #5255.
This allows for an asteroid table to be functionally empty, not requiring any asteroids to be set up.
Evidently, this will disallow the usage of asteroid fields, but some TC's may not need any, so allow these to set up without asteroids.
=> Allow 0-Asteroid setups

code/scripting/api/libs/async.cpp
What this does is basically providing an async.run that is able to run _and await_ an async with a built-in On Frame executor, but in a way that blocks _all other engine code_.
This makes it useful for things that need multiple frames, but the engine is in an unstable state where there simply are not multiple frames to be had until other things happen.
Two examples quickly become apparent for when this occurs:
1. Imagine you want to add animated transitions between game states. If you hook into a game state change, you simply never get a frame, so any attempt at starting an async will end up happening simultaneously to the stuff in the next game state. This new function will allow to start and run an async that yields and draws multiple frames _during_ the state change of FSO.
2. Say you …
=> "On Frame but actually Wait before you continue"-Executor

code/scripting/api/objs/player.cpp, code/scripting/api/objs/rank.cpp
Follow-up to #5280:
1. Make the Rank virtvar actually return a rank object, to be consistent with other Lua API methods
2. Add a RankIndex virtvar to replicate the previous functionality
3. Make RankIndex return the expected 1-based index for Lua
This is a breaking change to the API, but since the original API is less than a month old, the impact should be small.
=> tweak rank handling in Lua

ci/linux/upload_dist_package.sh
We should post nightlies even if one mirror fails since it'll still be available on the other mirrors.
Unfortunately, the failed mirror will still be referenced in the forum post and Knossos will still try to download the nightly from the failed mirror but that's preferable to having no nightly at all. Forum users will just have to try both links and Knossos will try both mirrors anyway.
Due to the current server migration of scp.indiegames.us, the upload will fail but the download link will still work since it currently just redirects to the mirror (datacorder).
=> Mark the nightly upload step as succesful as long as at least one mirror got the file

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/particle/particle.cpp, code/particle/particle.h
Still leaves room for more in-depth options later, but for now just a global flag. Also removes `particle_index` dunno wtf 'dynamic array usage' is about but it was used before for a janky random 90 degree rotation (which was also broken a few years ago)
=> Randomize particle rotation

code/ai/ailua.cpp, code/ai/ailua.h, code/hud/hudsquadmsg.cpp, code/parse/sexp/LuaAISEXP.cpp
This is the pendant to +Target Restriction: which can disable certain Lua AI orders for invalid targets, in that it disables giving Lua AI orders to certain ships.
Since this _should_ be done using objecttypes, this is more for context-sensitive AI orders that need finer control (such as orders that are only valid for the player's wingmates, or orders like formation flying which only make sense when given to a full wing and not just one ship)
=> Make restriction which ships accept Lua player orders configurable

code/model/modelanimation.cpp, code/model/modelanimation.h
Should fix #5248.
Implements proper wrapping for animation time instead of just capping in certain situations.
=> Add proper time wrapping for Animations

code/render/batching.cpp, code/render/batching.h, code/weapon/trails.cpp
Building large trails is an annoyingly costly process in terms of frame times. This makes it a very little bit cheaper. Not a big enough optimization to have very visible effects, but one I think is worth doing.
=> Optimizing the trail renderer by avoidng repeated batch_find calls

code/io/timer.cpp, code/io/timer.h, fred2/fredrender.cpp, freespace2/freespace.cpp, qtfred/src/mission/EditorViewport.cpp
Prior to the timer upgrade, all simulation timestamps shared identical timer and timestamp values for the duration of the frame, since they were only updated within the `game_set_frametime` function.  Since the timer upgrade depends on the system clock, timestamps evaluated near the end of the frame will be very slightly later than timestamps evaluated near the beginning of the frame.  It is desirable to keep them all in sync.
This PR tweaks the timestamp system to take a snapshot at the beginning of the frame, then use that snapshot for the entire duration of the frame.  This only affects simulation timestamps; real-time timestamps still use the live timer.
This is a redo of PR #5266, with some small additional tweaks.
Update: this now fixes the bug discovered in #5287.
=> synchronize simulation timestamps across the entire frame

code/math/curve.cpp, code/math/curve.h, code/parse/parselo.cpp, code/parse/parselo.h, code/particle/particle.cpp, code/particle/particle.h, code/particle/util/ParticleProperties.cpp, code/particle/util/ParticleProperties.h, code/source_groups.cmake, freespace2/freespace.cpp
Essentially, allows for modders to define arbitrary functions, using piece-wise components, made from polynomial, circular or previously defined functions. We can then apply those functions to map values in a wide-variety of domains and applications. For simplicity of the initial commit, just two applications are added here, particle +Size over lifetime and particle +Velocity scalar over lifetime.
```
$Name: test1
$KeyFrames:
(0, 1): Polynomial, 2, true
(1, 0): Constant
$Name: test2
$KeyFrames:
(0, 0): Circular
(0.5, 1): EaseInQuad    ; a built-in curve
(1, 0): Constant
```
Closes #3045
=> Add arbitrary curves support

code/hud/hudsquadmsg.cpp
If no ship in a wing can depart then the order *should* be disabled, but what it was actually doing was completely overwriting the allowance status of the order based on simply if any ships *could* depart, clobbering a correctly disallowed depart order via 'allowed orders'.
=> Fix for disallowed depart orders

code/debris/debris.cpp, code/debris/debris.h, code/model/model.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/shipfx.cpp
Just like ship density, allows for a ship class specific multiplier for debris mass and MOI, including subsystem debris-specific density.
Address the last point of #5278
=> Add debris density

code/ai/ai.h, code/ai/ai_flags.h, code/ai/ai_profiles.cpp, code/ai/aibig.cpp, code/ai/aicode.cpp, code/ai/aigoals.cpp, code/parse/sexp.cpp
Allows modders to more or less force AI to afterburn as hard as possible, either by simply adding or short-cutting existing afterburning behavior. Not as a matter of difficulty or anything, but mission choreography. They still should afterburn intelligently though, this only makes them hustle to get near their goal, and they won't burn so hard they can't properly complete their goal, whether it's attacking or defending or whatever, their behavior once they get here is basically unchanged.
~~Additionally, this removes some superfluous checks for having afterburners or whether they are locked, `afterburner_start()` already checks both of these so they just muck up the code.~~ Since it makes different decisions based on the status of the afterburners they are not superfluous >.>
Closes #5303
=> Add an Ai goal flag to afterburn hard

code/network/multi_respawn.cpp, code/object/objcollide.cpp, code/object/objcollide.h
Take into account the collision flag and collision groups when spawning a ship.  Should fix #5357.
Also clean up the code a bit, including setting a few `int`s to `bool`s and adding a missing axis case.
=> improve spawn collision checking

code/model/modelanimation.cpp
Skips an animation if it has a bad type instead of crashing later.
=> Fix CTD on bad legacy animation data

code/scpui/rocket_ui.cpp
Simple PR that slightly reorganizes the keymapping list and maps some of the other keys that were originally left off. Without this, librocket/scpui cannot detect those keypresses.
=> Organize and map additional keys to librocket

fred2/orienteditor.cpp, fred2/orienteditor.h
1. When the "object" radio button is selected, the "point to" check box will also be selected
2. When an object is selected from the object list, the "object" radio button and "point to" check box will also be selected
Fixes #5356.
=> FRED object editor QOL improvements

code/scripting/api/libs/graphics.cpp, code/scripting/api/libs/hud.cpp, code/scripting/api/objs/object.cpp, code/scripting/api/objs/team.cpp
I'm not sure if this is the best way to do this or even worth the possible annoyance for scripts. However, since the Lua API has full color support I was curious what it would take to convert past methods to get and set using the proper color object rather than raw rgb(sometimes a) values. Turns out there were only a handful of places.
Take it or leave it. Doesn't change underlying functionality, just unifies color handling across the API and deprecates the old methods.
=> Deprecate old versions in favor of versions that use color objects

code/hud/hudets.cpp, code/hud/hudets.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp
Follow up for #5137 and #5292. This engine strength check thus needs to be added to all instances where `max_vel.xyz.z` is updated, so a function was created and added in respective locations. Fixes #5367.
=> Fix max Z speed when using ETS and engine damage tracking

code/cfile/cfilesystem.cpp
If any files considered critical (like a table or mission) might be shadowed then give a proper warning. The line in the debug log is also changed to say "A critical file being indexed..." for these instances so that they are easier to track down.
=> warn when a critical file might be be shadowed

code/hud/hudartillery.cpp, code/hud/hudartillery.h
Extensible modular table handling for -ssm.tbm files was not very robust due to quite a few assumptions left over from straight .tbl parsing.  Ostensibly optional fields were required, non-overridden fields were reset to defaults, etc.  This improves XMT parsing and adds sensible defaults for SSM fields.
=> improve XMT handling of ssm.tbl

code/model/modelrender.cpp
Follow-up for #5344, which exposes a reliance on a valid `pmi`! The 3d ship select doesn't have one, maybe we can get one I dunno, but skip this if there is no `pmi`, the submodel probably isn't moving anyway.
Fixes #5371
=> Ensure pmi for moveable submodel glow points in 3d ship select

code/ai/aicode.cpp
Even if the afterburn hard flag allows afterburning the maximum afterburner speed may be limited by other members of the same wing, especially without the 'free afterburner use' flag (which it does not require). So if afterburning hard ignore all the wing speed limiting stuff.
=> Afterburning hard ignores wings

code/particle/ParticleSource.cpp, code/particle/ParticleSource.h, code/particle/ParticleSourceWrapper.cpp, code/particle/ParticleSourceWrapper.h, code/particle/effects/GenericShapeEffect.h, code/particle/effects/VolumeEffect.cpp, code/weapon/beam.cpp, code/weapon/beam.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Adds a new `SourceOriginType` for particle sources corresponding to the entire length of a beam. All the special beam handling definitely... *chafes* a little with the framework, but I'm confident that if beams are to be done in the framework this is the best way to do it. Key here is that when asked for the origin's position, it gives random positions along its length, allowing all the existing shape and volume effects to otherwise work the same. 
The random distribution along its length is also biased towards the start of the beam, linearly decaying to 0 at its maximum range. This is done so that the distribution of particles essentially matches the opacity of the beam graphic itself, which also linearly decays to 0 towards its end.
Closes #3050
=> Add beam particles

code/missionui/missionbrief.cpp
When I made FSO not crash with demo data in PR #1156, I avoided calling `brief_maybe_blit_scene_cut()` if `Fade_anim` didn't load, when I should've made it do what the icculus port does in demo mode: pretend the animation finished immediately.
With this commit, the first mission of the demo correctly advances past the first briefing stage.
=> Actually handle a missing `Fade_anim` properly.

code/parse/sexp.cpp
The `rand` SEXP stores the result of its first call in the "low" node. Prior to PR #2402, this worked fine, but after that, the value is cached when first evaluated, meaning that subsequent calls to the `rand` SEXP will always return the lowest value in the range, not whatever number was rolled the first time.
This commit makes it so that writing the rolled value to the node's `text` attribute is immediately followed by deleting the no-longer cached value, so that the SEXP continues to work as intended.
=> Fix the `rand` SEXP's use of cached values.

code/particle/effects/ParticleEmitterEffect.cpp, code/particle/effects/ParticleEmitterEffect.h, code/particle/particle.cpp, code/particle/particle.h, code/ship/ship.cpp, code/ship/shipfx.cpp, code/weapon/weapons.cpp
#5328 added a very useful culling for particles created by specific particle effects (ie weapons, now beams), though in an effort to simplify the culling process, that PR removed the necessary culling of default smoke on ships. This PR restores the culling of default smoke while also keeping the new culling of particle specific effects. Tested and works as expected, including fixing the slowdowns caused by the aforementioned removal of smoke effect culls. Thanks to @Baezon for all his discussion and help with this.
=> Update recent particle optimizations to fix edge case slowdowns

code/graphics/software/font.cpp
Finding a bitmap font while in unicode mode is a recoverable error. So this changes up the parsing to make that work. If we find a bitmap font, silently ignore it but warn if Extra Warn is enabled.
Fonts.tbl already errors if not enough fonts were loaded after all font parsing has completed.
=> Warn instead of error for bitmap fonts in unicode

cmake/toolchain-apple-clang.cmake, cmake/toolchain-clang.cmake, cmake/toolchain-gcc.cmake, code/fireball/fireballs.cpp, code/fireball/warpineffect.cpp, code/gamesnd/eventmusic.cpp, code/globalincs/systemvars.cpp, code/graphics/2d.cpp, code/graphics/opengl/gropengltexture.cpp, code/graphics/post_processing.cpp, code/io/mouse.cpp, code/jpgutils/jpgutils.cpp, code/mission/missionbriefcommon.cpp, code/mod_table/mod_table.cpp, code/nebula/neb.cpp, code/sound/sound.cpp, code/weapon/shockwave.cpp, freespace2/freespace.cpp
Per GCC optimisation guide, which applies equally well to clang:
* -funroll-loops should not be used unless directed by profiling. The compiler will already unroll loops when it's a good idea.
* clang and gcc now have -Og optimisation levels designed to enable debugging with good performance.
(second attempt at PR #4562)
=> Modernise CFLAGS on Mac/Linux

code/def_files/data/effects/main-f.sdr
#5055 changed the way SDR->HDR conversion was handled for textures.
This was incorrect for some cases, causing #5282.
#5282 however did not fully fix the issues but only fix them for handling of envmaps (and in the process likely incorrectly appyling SDR->HDR conversions in the SDR-only non-deferred pipeline, but I have not validated this).
This PR properly fixes the SDR->HDR conversion for all textures simply by reverting to how the old shader deals with the conversion, just with the new style of conditionals in the shader. This fixes some models being way too dark models with high specularity and low-light glowmaps.
=> Fix HDR conversions in main shader

code/object/collideshipweapon.cpp
A weapon can exceed its own `max_vel` via inherited velocity, and otherwise screw up this collision extrapolation.
=> Collision fix for weapons with lots of inherited velocity

code/parse/parselo.cpp
In retail, number parsing picked up immediately at the character after the number parsed, so parsing `0.50` as an int would yield 0, and then the next available characters would be `.50`.  Even though parsing has been tightened up and made stricter, we can still "fail gracefully" by simulating the old behavior.  And when failing gracefully, the message can be a warning.
=> make number parsing a little more forgiving

code/model/modelanimation.cpp
Fixes a crash when something tries to actively start an animation on an already no-longer existing ship.
=> Add additional checks for Animation List handling of nonexistent polymodel instances

code/ai/aicode.cpp, code/ai/aigoals.cpp
Summary:
Fighters and bombers object types can be edited to accept docking or undocking orders. Undocking presented two bugs:
1. Undock never had the path properly reset to -1 when done (dock does). This lead to fighters or bombers never being able to properly attack large ships after undocking due to a conditional if check regarding paths in `ai_big_chase()` (specifically line 1338 in in `aibig.cpp`). This PR properly resets the path when undocking of a fighter is complete. (Recall undocking is completely seperate then bay arrivals or departures). This bug was likely not noticed before now because Fighters and bombers cannot normally undock, only re-arm, that has to be edited in the objecttables, so in retail it was never noticed. Also, re-arm has it's own path and orders, so that case …
=> Fix two undocking bugs for small ships

code/model/modelreplace.cpp
The `type_flags` on a model's dockpoints are determined by the dockpoint name.  If the name changes, the flags should be updated accordingly.
This fixes a bug in Scroll where a dockpoint that was imported and renamed to start with the word "cargo" was not compatible with cargo docking as expected.
=> update type_flags when dock name changes

code/globalincs/adjustment.cpp, code/globalincs/adjustment.h, code/graphics/light.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/opengl/gropenglpostprocessing.cpp, code/lab/dialogs/lab_ui.cpp, code/lab/dialogs/lab_ui_helpers.cpp, code/lab/manager/lab_manager.cpp, code/lab/renderer/lab_renderer.cpp, code/lab/renderer/lab_renderer.h, code/lighting/lighting.cpp, code/lighting/lighting_profiles.cpp, code/lighting/lighting_profiles.h, code/object/object.cpp, code/source_groups.cmake, code/weapon/beam.cpp, freespace2/freespace.cpp
This is some general cleanup before I work on the flexible lighting profiles feature. The big change count is a bit deceptive, most of this is code that's already been reviewed and is just being moved.
@BMagnu some time back suggested the lighting profiles 'adjustment' code could be repurposed, so before I do significant changes to the lighting profiles code that entwines them more I'm pulling them apart here. 
Reworking the lighting profiles to a namespace comes from discussion with @TRBlount about other projects that suggested this was a good best practice to adopt rather than lots of class static members, so I'm doing that now before I start adding in new state to profiles.
And in the process I applied clang-format too, as was generally my intent with this code to begin with but it …
=> lighting profile code reorg

code/mission/missionparse.cpp, code/mission/missionparse.h, code/missionui/missiondebrief.cpp, code/parse/sexp.cpp, code/parse/sexp.h, code/stats/scoring.cpp, code/stats/scoring.h, fred2/management.cpp, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/mission/management.cpp, qtfred/src/mission/management.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
Adds a new Traitor Overrides feature as discussed with WookieJedi. This allows much more fine-tuned control of the traitor debrief than persona system allows.
You define a traitor debrief in traitor.tbl under the new `#traitor overrides` section. Each debrief gets a unique Name identifier. You set the text, audio file, and recommendation text for each one. A new sexp is used in FRED to define which traitor override debrief to use.
The traitor override pointer defaults to nullptr. If it remains nullptr then the old persona setup is used. Otherwise the debrief will use the override.
=> Traitor overrides feature

qtfred/src/main.cpp, qtfred/src/mission/Editor.cpp
The `stars_post_level_init()` change in #5403 exposed a bug where qtFRED would sometimes try to render the mission before all setup had been completed, causing a crash because `Show_iffs` was zero-length.  This was due to the mission being created in the middle of initialization, instead of after initialization was complete.  This fix moves `createNewMission()` to main.cpp, after initialization has finished, and in parallel with the command-line option to load a mission.
=> fix qtFRED initialization

code/parse/sexp.cpp
Related to #5267, and again concerned with the original check for event delay:
```
if ( (fix) Mission_events[i].timestamp + delay >= Missiontime )
return SEXP_FALSE;
```
For events that were never evaluated at all, their timestamp remained 0.  Thus the function did not return and the status of the event (which by definition was incomplete) was always checked.
After the timestamp refactoring, this comparison always returned SEXP_FALSE for these events.  The correct behavior is to bypass invalid timestamps so that the status of the event is always checked.
This fixes the behavior of `is-event-false-delay` in debriefings.
=> fix evaluation of event status for some events

code/globalincs/systemvars.cpp, code/globalincs/vmallocator.h, code/math/curve.cpp, code/model/modelreplace.cpp, code/nebula/neb.cpp, code/parse/sexp.cpp, code/parse/sexp/LuaSEXP.cpp, code/parse/sexp/sexp_lookup.cpp, code/scripting/hook_conditions.cpp, code/scripting/lua.cpp, code/starfield/starfield.cpp, code/stats/scoring.cpp, fred2/eventeditor.cpp, fred2/missiongoalsdlg.cpp, fred2/musicplayerdlg.cpp, qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp, qtfred/src/ui/dialogs/EventEditorDialog.cpp
The `SCP_string_lcase_equal_to()()` and `SCP_string_lcase_less_than()()` functors are rather unwieldy to use in non-functor situations, so this adds conventional function equivalents.
=> add lcase_equal and lcase_lessthan

code/lighting/lighting_profiles.cpp
fixes some issues with the named profiles features
=> call reset() on new profiles to ensure properly set default values.

qtfred/src/main.cpp, qtfred/src/mission/management.cpp, qtfred/src/mission/management.h, qtfred/src/ui/widgets/sexp_tree.cpp
There was a missing function call in qtFRED's initialization, which prevented custom HUD gauges from being loaded.  This adds that.  Additionally, this updates the deduplication code in `get_listing_opf_custom_hud_gauge` to match its counterpart in FRED.
Fixes #5422.
=> patch qtFRED's handling of hud gauges

code/asteroid/asteroid.cpp, code/asteroid/asteroid.h, code/io/keycontrol.cpp, code/mission/missionparse.cpp, code/parse/sexp.cpp, fred2/asteroideditordlg.cpp, fred2/asteroideditordlg.h, fred2/fred.rc, fred2/missionsave.cpp, fred2/resource.h, qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp, qtfred/src/mission/dialogs/AsteroidEditorDialogModel.h, qtfred/src/mission/missionsave.cpp, qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp, qtfred/src/ui/dialogs/AsteroidEditorDialog.h, qtfred/ui/AsteroidEditorDialog.ui
Per discussion with WookieJedi, this fixes/enhances asteroid field spawning and wrapping for certain fields.
Basically fields with "enhanced checks" do not use range to limit the player view cone when wrapping asteroids and **do** use the view cone to check if an asteroid should be spawned (where retail does not have that check at all).
The core issue is that for small fields the existing checks for wrapping asteroids from one side to the other weren't stringent enough causing asteroids to visibly pop into and out of existence. This PR fixes that issue by adding an optional parameter for asteroid fields for "enhanced checks" that makes sure the asteroid is not within view of the player when it might be wrapped as well as when an asteroid might be created.
This shouldn't be a general …
=> Fix asteroid wrapping

code/ai/aigoals.cpp
Using Replace Container Data as the "waypoint path" argument in `ai-waypoints` and `ai-waypoints-once` currently works in FRED but triggers a crash ('Int3()') in game. This change fixes that.
Should fix Issue #5109.
=> Allow using container data with ai-waypoints* SEXPs

code/mission/missionparse.cpp
This fixes a regression where missions which relied on all poofs on by default would now have none. In this position used to be the same check that turned on all 6 poofs. As always, if a nebula is actually specified, this will get completely overwritten.
=> All poofs on by default

code/lighting/lighting_profiles.cpp
The default lighting profile name was getting cleared by `.reset()` which meant the list in FRED, for mods that only had the default profile, to call it "", an empty string. On mission save, this would not match `default_lighting_profile` name comparison and cause the mission to save out the line `$Lighting Profile: ` and that would then cause a warning on mission parse that FSO couldn't find lighting profile `""`.
This fixes that by making sure the default profile has the correct name.
=> Default profile name needs to be added after reset()

code/weapon/trails.cpp, code/weapon/trails.h, code/weapon/weapons.cpp
A trail with sufficiently simple parameters (no num faded sections, no spread, no alpha decay exponent) on an object with constant velocity is equivalent to a single rectangle with with only linear changes happening between points, so we can optimize for that case. Those are a lot of caveats, but this is still a significant portion of the use cases, especially for things like primary weapon trails, and allows us to avoid going over every single segment of a long straight trail and instead do the entire thing in a single pass.
Before
After
=> Optimize for 'simple' trails

code/lab/renderer/lab_renderer.cpp, qtfred/src/mission/management.cpp
1. Patch the string skipping behavior for backgrounds in the lab.  Not all the strings were accounted for in each section, which would occasionally cause some sections to be incorrectly skipped; and one of the strings was wrong.  Also tidy up the assignment of `ltp_name`.
2. Since `curves_init()` was added to FRED, add it to qtFRED too.  Also sort the list of #include statements in that file.
Followup to #5380 and #5408.  Also fixes a bug mentioned in Discord where background bitmaps were not being loaded in the lab.
=> Fixes for lab backgrounds and curve initialization

code/autopilot/autopilot.cpp, code/object/objcollide.cpp, code/object/objcollide.h, code/parse/sexp.cpp, code/scripting/api/objs/object.cpp
1. Add a function to retime *only* the collision pairs involving a specific object.  This is useful when only one object has moved, since only collisions involving that object are affected.
2. Use this function when objects are moved for autopilot, via sexp, and via script.
Previously collision pairs were not retimed when objects were moved via script, leading to bugs.  This fixes that.
=> some refinements for retiming of object collision pairs

code/def_files/data/effects/batched-f.sdr, code/def_files/data/effects/batched-v.sdr, code/graphics/2d.h, code/graphics/opengl/gropengltnl.cpp, code/math/vecmat.cpp, code/math/vecmat.h, code/render/batching.cpp, code/render/batching.h, code/weapon/trails.cpp
Since retail, lasers with head radius != tail radius (or any trapezoidally shaped bitmap) would not have their UVs correctly interpolated across their bitmap, each triangle unaware of its existence as part of the trapezoid, creating a 'kink' across the diagonal. At the modest price of widening the texcoord vertex attribute to a vec4, we can include a correction parameter that correctly scales and interpolates the texture.
I added it for single segment trails too, because that optimization actually makes the 'kinkiness' very obvious >.>
=> Make lasers less kinky

code/cmdline/cmdline.cpp, code/model/modelread.cpp
This fixes the INF_Antaeus.pof crash of Inferno: Alliance due to unknown data found on the model BSP Data chain.
Explanation: 
While parsing the bsp data, the alignment code reads every chunk of the chain one by one, on this particular model on one of the chains at the final 8 bytes there is invalid data that looks like corrupted or trash data, this has an invalid chunk type and a negative chunk size, causing the bsp_pointer to go out of bounds.
Fix:
A check is added to make sure the chunk size value is not negative or has a value that may cause the bsp pointer to go over the max bsp_size.
A troubleshoot flag is also added to disable this process.
=> Validate chunk size to avoid align crash and add align skip flag

code/ai/aibig.cpp
Follow-up to #4087. Gotta actually write to this value, so we don't go towards zero every other time.
Fixes #5453
=> Fix AI subsys reposition oversight

code/cmdline/cmdline.cpp, code/graphics/2d.cpp, code/mod_table/mod_table.cpp
Follow-Up to #5445.
It seems to cause crashes since gr_capability isn't available that early, so defer the shadow capability check to gr_init.
=> Fix check for shadows

code/localization/localize.cpp, fred2/campaigneditordlg.cpp, fred2/management.cpp, fred2/management.h, fred2/missionnotesdlg.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp, qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
Kitsune discovered that special characters, notably semicolons, were not properly handled in the Mission Specs editor.  This adds appropriate handling of special characters for fields in that editor, similar fields in the campaign editor, and the corresponding places in qtFRED.  This also makes error messages more descriptive for campaign load failures.
=> handle special characters in additional places in FRED

code/mission/missionparse.cpp, fred2/bgbitmapdlg.cpp
In certain cases, angles would be rounded to 360, where the expected range is 0-359.  The range was guarded properly for skyboxes but not for bitmaps and suns.  This fixes that.  Additionally, since suns do not bank, the angle conversion now sets the bank to 0.
Fixes #5390.
=> fix angle conversions in FRED

code/hud/hudbrackets.cpp, code/hud/hudtargetbox.cpp, code/jumpnode/jumpnode.cpp, code/jumpnode/jumpnode.h, code/mission/missionparse.cpp, code/parse/sexp.cpp, fred2/jumpnodedlg.cpp, fred2/jumpnodedlg.h, fred2/missionsave.cpp, fred2/sexp_tree.cpp, qtfred/src/mission/missionsave.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
1. Deprecate the old set-jumpnode-name sexp now that there is a set-jumpnode-display-name
2. Make the display name design consistent with ships and weapons; in particular add a `HasDisplayName()` function and automatically generate the display name for hash-truncated names
3. Keep the display name in sync when the name is changed in the FRED dialog
4. Fix the overriding of hash-truncated names with display names on the HUD
5. Fix the incorrect setting of the alphacolor flag when using FRED
6. Fix array out-of-bounds access when no object is selected
Follow-up to #5401.
=> refinements of jump node features

code/model/modelrender.cpp
PR adds extra validity check within `model_render_glowpoints` function. Other places in code that use `bank->submodel_parent` check for validity before looking up `pmi->submodel`, but this check was missing from this section (which caused a CTD in a mission restart due to `bank->submodel_parent` being -1).
=> Fix crash that can occur due to invalid glow point bank

code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/opengl/gropengldeferred.h, code/graphics/vulkan/vulkan_stubs.cpp, code/object/objectsort.cpp, code/ship/ship.cpp
Fixes #5466.
Basically, decals are an effect which need to happen _before_ deferred lighting is calculated, but _after_ MSAA resolve has happened as they need to read from the g-buffer.
This PR pulls out MSAA resolve from the deferred_end method and makes it its own method, so that there is a window between MSAA resolve and deferred lighting where these types of effects can be rendered.
=> Decouple MSAA from deferred_end

code/mission/missionparse.cpp, fred2/freddoc.cpp, fred2/freddoc.h, fred2/missionsave.cpp, fred2/missionsave.h
Issue #5459 notes that mission files that are too long will crash the FRED campaign editor, but this is an artificial restriction.  The only need for a string buffer here is to enforce the correct mission extension, so use a SCP_string for this, and add checks for whether string manipulation is in fact necessary.  (In most cases it isn't.)
Fixes #5459.
=> allow getting of mission info even for files with long names

code/mission/missioncampaign.cpp, code/pilotfile/csg.cpp
Campaign-persistent containers were getting clobbered by red alert containers and also weren't always being cleared alongside campaign-persistent variables.
Fixes Issue #5458.
=> Fix issues with campaign-persistent containers

code/weapon/swarm.cpp
It appears that `(turret->turret_enemy_objnum < 0)` is an expected and allowed condition, so just assert that the objnum does not exceed MAX_OBJECTS.
Fixes #5470.
=> fix Assertion in turret_swarm_set_up_info

code/bmpman/bmpman.cpp
This is a bit tricky because both animated and non-animated PNGs use the same extension.  So for PNGs we need to defer the filename length check until we know for sure that it is an animated image.
Fixes #5387.
~~In draft pending testing.~~  Tested by @Baezon
=> tweak filename length check for PNGs

code/parse/parselo.cpp
In at least two instances, `split_str_once()` can be called with width values derived from mod-supplied values that can be 0 or less (specifically, two hud gauges: if `+Messages:` has a `Max Width:` that's too small, or `+Directives:` has a `Max Line Width:` of 0 or less). Since user-supplied code shouldn't be tripping assertions, I looked into adding security around the calling sites when I realized that the assertion wasn't actually protecting against anything; the function would run just fine with a negative pixel width, it would just break with every whitespace. Since both calling sites that could trip the assertion already treat getting `src` back as output as an "I can't split this" error condition, it's perfectly fine (and skips iterating through the string) to just `return src` if …
=> Remove `max_pixel_w > 0` assertion from `split_str_once()`.

code/scripting/lua/LuaThread.cpp
Followup to #4701.
While that last PR apparently properly cleared the thread handle, it added three more handles: A function, a table, and a userdata.
In _some_ cases, it seems that during teardown these also didn't get properly cleared along with the thread, so this PR also manually detaches the LuaHandle from the C++ side, so that deallocation does not cause a crash on exit.
=> Clear C++ Handles to LuaThread-stuff more aggressively

code/ai/aicode.cpp
Fix the instructor check for whether a ship should circle or not.  Follow-up to #5353.  Fixes #5478.
=> fix instructor check

code/hud/hudescort.cpp
Secondarily, display callsigns in the escort list, if one is given.
(I named the branch before deciding it wasn't actually a cleanup; oh well.)
=> Avoid displaying hidden ship names in the escort list.

code/playerman/player.h, code/playerman/playercontrol.cpp, code/ship/shiphit.cpp
Several related fixes:
1. Copy the actual ship name, not the display name, to `killer_parent_name` for two reasons:
a. Since `killer_parent_name` is used to look up the ship, it must be the actual ship name, not the display name.
b. Copying the display name can cause a buffer overflow because display names can be longer than 31 characters.
2. The display name functionality is moved to the more appropriate location in `player_generate_death_message()`.
3. Remove `player_get_killer_weapon_name()` which only served as a proxy check for whether the weapon index was used or not.
4. Use `ship_registry_get()` rather than `ship_name_lookup()`.
5. Add comments to clarify the use of `killer_parent_name`.
Fixes a bug reported in Discord.
=> fix some bugs revealed by ships with long display names

code/sound/voicerec.cpp
If you pause the game, say something into the microphone, then unpause, it can abruptly perform an action based on voice recognition; this is probably counter to player expectations. This adds a `gameseq_get_state() != GS_STATE_GAME_PAUSED` check to the existing conditional.
=> Ignore voice recognition events while game is paused.

code/menuui/readyroom.cpp
If the "Campaign Room only available in full version" popup is shown, it tries to reset `Active_campaign_index`, except that if a pilot is loaded with a missing campaign file, `Active_campaign_index` is -1. This causes an out-of-bounds array access, so let's present an alternate popup in this case (either one to select whatever the first campaign file found is, or the generic `popup_game_feature_not_in_demo()` if no campaign files are found).
Fixes #5484.
=> When playing the demo, don't try to reset if no campaign is active.

code/bmpman/bm_internal.h, code/bmpman/bmpman.cpp, code/hud/hud.cpp, code/hud/hudescort.cpp, code/hud/hudets.cpp, code/hud/hudlock.cpp, code/hud/hudreticle.cpp, code/hud/hudshield.cpp, code/hud/hudtarget.cpp, code/hud/hudtargetbox.cpp, code/hud/hudwingmanstatus.cpp, code/mission/missiontraining.cpp, code/radar/radar.cpp, code/radar/radarorb.cpp
While *most* HUD gauges will check the validity of their bitmaps before rendering, a random smattering do not. This PR ensures *every* HUD render is gated behind a check for its bitmap and converts any `== -1` to `< 0` (as in debug uninitialized memory is often that giant ass negative int) and prevents any horrible bmpman assertions from rearing their ugly head.
It should be noted *all* invalid/missing bitmaps were already warned about before this point.
=> Improved hud gauge loading safety

code/sound/voicerec.cpp
These #include lines are needed for the changes introduced in #5492.  Not sure why they weren't picked up by CI, or why they work in some compilers but not others.
=> add missing #includes to fix compilation

code/render/batching.cpp, code/ship/ship.cpp, code/weapon/trails.cpp, code/weapon/weapons.cpp
Based on [this question by Kitsune on discord](https://discord.com/channels/223511295431933953/223511363807346691/1130507954873958501), I did some digging and it turns out if a trail bitmap is missing, the engine never warns about it; we silently swallow this on release builds and assert unhelpfully on debug and fastdbg. we shouldn't do that.
=> Add a warning for cases when we couldn't load a trail bitmap

code/autopilot/autopilot.cpp, code/object/objcollide.cpp, code/object/objcollide.h, code/object/object_flags.h, code/parse/sexp.cpp, code/scripting/api/objs/object.cpp, code/tracing/categories.cpp, code/tracing/categories.h
Follow-up to #5487 
#5442 adds invalidation of collision check timings on ships who've had their position or orientation changed via script, which prevents any erroneous collision behavior, but since this involves going through all the collision pairs, if done too much like say, on dozens of ships every frame (not that I would ever do such a thing >.>) the cost can add up.
Instead of adding extra script bells and whistles to skip this step in 5487, the cost of fixing this invalidation can be greatly improved. Instead of immediately retiming all or even some pairs, any operations will instead set a global flag, then once per frame directly before collision go through all the pairs to retime them, *and* cull any invalid pairs.
Simply going through the pairs is often the bigger cost than the …
=> Improve performance of collision retiming

code/fireball/fireballs.h, code/scripting/api/libs/mission.cpp
When fireballs were made dynamic in 609ed4ed94, the `MAX_FIREBALLS` #define lost any relationship to the fireball collection.  This removes it and also correctly specifies the size of the fireball collection.
This fixes a CTD when accessing items in `mn.Fireballs` via script.
=> fix Lua API access to Fireballs array

code/mission/missiontraining.cpp
In f350e06851d71694db8d20e9c8536f46379ff6a7, two Int3()s were added to `message_translate_tokens()`, to check for possible out-of-bounds errors. However, in c70fdc3a52dc732c34fd954f2934b864db73f198, just a couple months later, the code being protected by those bounds checks were put into `else` branches, meaning the `Int3()`s became redundant. This wouldn't actually cause any problems unless somebody passed a string with two `$`s at least 40 characters apart to `message_translate_tokens()`. Cue #4876, which started calling `message_translate_tokens()` on debriefing stages and recommendations, which can contain color tags. This still wouldn't cause problems as long as the color tags are in pairs within close proximity (`translate_key()` would say "that's not the name of a scan code" and …
=> Remove `Int3()`s from `message_translate_tokens()`.

code/ai/aicode.cpp
When only one AI class performs autoscaling, the math formulas which use autoscaling will become meaningless (e.g. in `ai_maybe_launch_cmeasure()`) or will cause divide-by-zero errors (e.g. in `ai_manage_shield()`).  And autoscaling is not very useful outside of the specific ways that Volition used it.  So this adds some warnings and disables single-occurrence autoscaling.
Fixes #5474.  ~~In draft status pending testing.~~
=> prevent AI autoscaling for only a single autoscaled class

code/cmeasure/cmeasure.cpp
Single segment trail optimization relies on the fact that the object has a constant velocity, so when countermeasures go and *change* that velocity after creating the weapon (and telling the trail a *wrong velocity* beforehand), it gets ugly. `CONST_VEL` doesn't mean what it used to these days... but I'm confident this sort of thing is extremely rare.
=> Fix for countermeasures with a single segment trail

code/weapon/trails.cpp, code/weapon/weapons.cpp
Laser trails come from their visual center, rather than their actual position which is at their tail, however this is done when the trail is maintained every frame in `trail_set_segment` rather than when it is created, which is when all the single segment handling happens and so it 'misses that memo'.
1. Make sure this is done for trails even when created, even if it's going to be affirmed in set_segment anyway. Makes that bit clearer in general. This would be sufficient to fix the problem...
2. But also remove the early out for single segments in `trail_set_segment`, this was done since it 'theoretically' shouldn't need any maintaining what with a constant velocity and all, but let's do it anyway just to make sure the trail doesn't get 'disconnected' by any other means as well.
3. Clamp …
=> Some more fixes for laser single segment trails

fred2/missionsave.cpp, fred2/missionsave.h, qtfred/src/mission/missionsave.cpp, qtfred/src/mission/missionsave.h
When using the mission importer, missions were being corrupted for very subtle reasons: due to some code reordering in prior commits, `raw_ptr` would be initialized to `Parse_text_raw` before `Parse_text_raw` itself was initialized.  This assignment was done in the `CFred_mission_save` constructor and the ordering dependency is not obvious.  Since this is a highly fragile situation and has the potential to affect any use of `parse_comments()` in FRED, it's better to explicitly assign `raw_ptr` when it is needed, and just initialize it to nullptr in the constructor.
This also sets the version number to the legacy version (0.10) when the mission is saved in the retail format.
=> fix mission corruption in FRED

code/parse/parselo.cpp, code/parse/parselo.h, code/parse/sexp.cpp, fred2/freddoc.cpp
This is a cleanup and upgrade of the SEXP parsing mechanism that makes the whole thing a lot more robust.  Error handling has been upgraded, several cases that previously caused a crash will fail gracefully, and some cases that previously caused an error can now be recovered with a straightforward "Attempt to load the mission failed".  The case that caused parsing to fail on Black Horizon mission 7, "Alone in the Void" -- a message name that started with an `@` character -- now works successfully.  The code has also been refactored and cleaned up a bit.
=> SEXP parsing cleanup and fixes

code/scripting/api/objs/shipwepselect.cpp
Prevents a vector out of range CTD if a script tries to set the amount of a weapon slot when the currently loaded weapon is invalid.
=> Fix: Prevent loadout related CTD

code/starfield/starfield.cpp
Fixes #5538 by implementing better formula for frame calculation. The previous formula would always result in at least a 1 frame increase in the animation for every mission frame drawn unless the framerate of the animation was >= the current game's framerate.
This newer formula calculates the ms an animation frame should be drawn for. If timestamp >= that amount of time is when we go to the next frame. Otherwise we draw the current frame again.
=> Fix animated background bitmaps rendering with incorrect framerate

code/model/modelread.cpp
In #4702 this log line was changed to the 'Model' category, which made it hidden by default.  This was missed in review but should be restored as it is a fairly important line.
Fixes #5507.
=> add model filename back into debug log

code/mission/missioncampaign.h, fred2/campaigneditordlg.cpp, fred2/campaigneditordlg.h, fred2/campaigntreewnd.cpp, fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
1. When saving a campaign, the save directory should be the one that the campaign was just loaded from.  If prompting the user, this should be the default save directory.  This fixes a bug where campaigns were saved to %APPDATA% instead of where the FREDder might expect.  This has been a bug ever since the migration of the game files from FreeSpace2 to %APPDATA%.
2. When saving a campaign, save only the external mission flags, not the working flags that are maintained during gameplay but have no meaning in the saved file.
=> fix a couple bugs in the campaign editor

cmake/util.cmake
Copying a file with cp on top of another one is not allowed by default so switching the command to use the CMake provided one will fix the issue and will also unify the commands for all platforms.
The directory support is necessary for Mac where the SDL library is actually a directory.
=> Fix "File exists" error

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-standalone.yaml, .github/workflows/build-test.yaml, .github/workflows/cache-master.yaml, .github/workflows/test-pull_request.yaml
The install step in the CI pipeline is no longer needed after this change and has been removed.
=> Update build image with curl and jq preinstalled

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/parse/sexp.cpp
The hud-set-coords SEXP has always used exact pixels, without regard for the current screen resolution.  This adds a similar scaling mechanism as is used for show-subtitle.
Fixes #5525.
=> add screen resolution scaling for hud-set-coords

code/ship/shiphit.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp
For mods which want primary weapons to 'detonate', setting the detonation range is not reliable because, due to rounding imprecision, either the range (which detonates) or the lifetime (which does not) may happen first.  So this adds a flag to always detonate a weapon when its lifetime expires.  Secondary weapons have this flag by default, but primary weapons can add this flag in the $Flags list.  Additionally, if the detonation range and the predicted range due to lifetime are equal, the flag is added automatically.
Resolves #5521.
=> 'detonate on expiration' weapon flag

code/ai/aigoals.cpp, code/parse/sexp.cpp
Three fixes:
1. In commit fa0878b6b3 for PR #5338, the optional distance parameter was inadvertently changed to a bool.  This fixes the parameter.
2. The distance parameter was previously parsed using `atoi` which works for number literals, so change to `eval_num` to allow sexp return values.
3. Make `eval_num` consistent with `eval_sexp` in the sense that evaluating an empty list is valid and returns false or 0.
Also takes advantage of the fact that `is_sexp_true` works for empty lists to streamline optional arguments in `ai_add_goal_sub_sexp`.
=> ai-stay-near-ship fixes

code/globalincs/flagset.h, code/weapon/weapons.cpp
When weapon flags are parsed in a modular table and override the previous set of flags, certain flags must be kept to preserve the behavior of the weapon.  The previous `preset_wi_flags` technique only worked if all such flags (homing, has-display-name, even whether the weapon turns) were set in the same modular table.  If a modular table overrode the flags but didn't specify those lines over again, mysterious and subtle bugs would occur.
This modifies the flag parsing to explicitly preserve all appropriate flags from the existing weapon entry, which fixes the bug.  It also allows all of the flags to be specified in one place, rather than scattering `preset_wi_flags` assignments throughout `parse_weapon`.  And this also adds quite a few flags to the flag list that were not handled at all …
=> fix flags in modular weapon entries being cleared

code/graphics/generic.cpp, code/graphics/generic.h, code/scripting/api/libs/graphics.cpp, code/scripting/api/libs/graphics.h, code/scripting/api/objs/streaminganim.cpp
1. Since other functions in the scripting API remove extensions before loading the files, and since the internal functions expect them to be removed, the streaming anim API should handle that too.
2. Make streaming animations obey the current scripting resize mode.
3. Make streaming animations obey the passed alpha value.
=> some streaming animation fixes

code/weapon/weapons.cpp
Since `std::unordered_map.insert` does nothing if a key already exists, use bracket notation.  Fixes #5515.
=> assign weapon particle effects properly

code/cutscene/movie.cpp, code/mod_table/mod_table.cpp
The default movie subtitle font is font01.vf, but mods with custom font tables might not use this font.  So this changes the handling slightly so that the movie player will use whatever the first available font is.
Follow-up to #1523.  Fixes a sometimes spurious warning in mod initialization.
=> fix $Movie subtitle font: for custom fonts

code/sound/ffmpeg/FFmpegWaveFile.cpp
~~Currently, menu music will trim the extension and look for both OGG and WAV files, but event music will use the exact extension specified.  This behavior dates all the way back to commit f969eb52a2 from 2010.  There doesn't seem to be an obvious reason for this, and it leads to a bug in FSPort where in some cases music will not play during a mission, in situations where the table uses .wav but the music pack provides .ogg.  So, let's make event music extension-agnostic.~~
Currently, menu music will trim the extension and look for both OGG and WAV files, but event music will use the exact extension specified.  This is intended but could lead to unexpected results in mods, so display a warning for the modder.
=> handle extension mismatch in event music

fred2/fred.cpp
The crash in #5514 appears to be caused by some of the graphics code not being in the expected state for the synchronization.  Looking at the code in `render_frame()`, a `gr_flip()` happens after one frame ends and before the next frame begins.  That implies that this `gr_flip()` should not be here, as it is in the middle of a frame.  For additional evidence, `gr_flip()` modifies the "uniform buffer manager" state, and that is part of the stack trace preceding the crash.  Removing this `gr_flip()` fixes the crash.
The strange thing is that this code *doesn't run at all* while the campaign editor is active.  I verified this by adding a MessageBox in place of `gr_flip()`; the MessageBox doesn't display until the campaign editor is exited.  And yet, FRED crashes with `gr_flip()` present and …
=> fix crash in campaign editor

code/gamesnd/eventmusic.cpp, code/sound/ffmpeg/FFmpegWaveFile.cpp
Since event music soundtracks use the exact file extension specified (see #5567), the validity check should also use the exact file extension specified.
Also, move the validity check to after parsing has completed because extensions may be overridden.
=> fix validity check for soundtracks

code/def_files/data/effects/deferred-f.sdr, code/def_files/data/effects/deferred-v.sdr
What I _think_ happened here is that the Nvidia compiler saw the calculation of ``lightPosition`` in the vertex shader (which turns out to be a dynamically uniform expression) as optimizable, but somehow messed up how its passed as a parameter to the fragment shader. If this calculation is moved to the fragment shader, which should be performance-equivalent since it's a dynamically uniform expression, the issue goes away.
Fixes #5430
=> Fix issues with newer Nvidia driver

code/object/objectsnd.cpp, code/object/objectsnd.h
When a non-looping persistent sound expires, `obj_snd_stop()` actually does need to be called.  Even though the sound is no longer playing, the `Num_obj_sounds_playing` tally needs to be decremented, otherwise it will eventually exceed its limit and prevent any additional persistent sounds from playing.  And it turns out `obj_snd_stop()` returns gracefully for sounds that aren't playing.
Follow-up to #3510.  Fixes a bug that appears to have been around since retail.
=> fix persistent sounds not clearing their tally

code/gamesnd/eventmusic.cpp
There is a built-in delay for the event music to start playing, but this delay gets stepped on if `change-soundtrack` is called when the mission first starts.  So don't set the delay unless it has already elapsed at least once before.
=> fix soundtrack timestamp when change-soundtrack is called immediately

code/gamesnd/eventmusic.cpp, code/gamesnd/eventmusic.h, code/mission/missionparse.cpp, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/scripting/api/libs/ui.cpp
This adds several fixes to make the event and menu music more robust:
1. The game will now run with zero soundtracks.  All accesses into a potentially empty vector should now have checks.
2. Soundtracks and menu music are now checked for validity before being played (not just when importing a FSM mission).
3. The parsing validity checks and the in-game event music now check for skippable patterns using the same function.
4. Zero measures and zero samples-per-measure now cause the game to skip a pattern.  Negative values now trigger a warning.
5. Omitting some or all of the `$Name:` lines for a soundtrack will not cause an assert.
Fixes #5576.  Follow-up to #5572.
=> additional music checks

code/scripting/api/objs/shipwepselect.cpp
I truly have no idea how this ever worked. Single character change is required to make this properly functional. We need the weapon index here, not the bank index.
=> Fix Being unable to set loadout amounts

code/hud/hudreticle.cpp
The gauge assumes that all firepoints will always have weapons, but it's possible for a ship to have less than the maximum number of weapons.
=> fix crash in firepoint gauge

code/hud/hudreticle.cpp, code/io/keycontrol.cpp, code/weapon/weapon.h
The firing point gauge did not work as advertised; this fixes it.  Unselected weapons are dimmed, selected weapons are normal, and firing weapons are bright.
=> fix the logic for lighting up firing points

code/object/collideweaponweapon.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/shiphit.cpp, code/weapon/shockwave.cpp, code/weapon/weapons.cpp
For certain calculations involving armor, the `GetDamage` function needs to know if the damage is being applied by a beam so it can apply the calculations with the proper frametime.  The parameter was not provided in all cases, so this fixes that.
Follow-up to #1609.
=> supply parameter for is_beam in all armor checks

code/starfield/starfield.cpp
This fixes the formula (Which has been incorrect for quite some time) used to get the next frame of an animation used in a starfield and extends a previous change to apply to all bitmap animation types.
=> Update starfield animation handling

code/graphics/render.cpp, code/graphics/render.h, code/hud/hud.cpp, code/hud/hud.h, code/hud/hudconfig.cpp, code/mission/missionbriefcommon.cpp, code/mission/missionbriefcommon.h, code/mission/missionparse.cpp, code/missionui/missionbrief.cpp, fred2/briefingeditordlg.cpp, fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
This extends the handling of scaling to all briefing icon types and uses the standard method of saving briefing icon info as the old method did not account for all cases.
=> Follow-up for briefing icon scaling

code/ship/ship.cpp, code/weapon/trails.cpp, code/weapon/trails.h
If new contrails are defined in a modular tbm, certain fields may not be initialized correctly (namely `a_decay_exponent` and `texture_stretch`, which must be 1), since they are typically only initialized on the ship's first definition, so I've added an explicit trail info initializer. Ship contrails are the only one with this issue, since they are the only circumstance of an unknown, variable amount of trail_infos.
=> Fix for modular table contrail initialization

code/scripting/api/libs/ui.cpp
SCPUI loads the campaign file from the player file after leaving the Barracks and in a few other cases. Normally this is fine, but if the player recently changed campaigns, the player save file will be out of date. So this one-line change forces saving the player file whenever the campaign is changed in SCPUI.
=> Save player after changing campaign in scpui

code/missionui/missionweaponchoice.h, code/scripting/api/libs/ui.cpp
Fixes a bug where `ui.ShipWepSelect.resetSelect` would slowly deplete the available weapon pool until no weapons are available.
=> Actually reset the weapon pool with SCPUI

code/mission/missionmessage.cpp
The `Random::next(low, high)` function returns a value in [low, high].  This location should use the single-argument version, `Random::next(int modulus)`, which returns a value in [0, modulus-1].
=> fix random selection of message candidates

code/parse/parselo.cpp, code/parse/parselo.h, code/parse/sexp.cpp
As reported by Colt, there was a crash in the in-mission jump sequence in Shepherds where the mission previously worked.  The proximate cause was a handwritten SEXP called via script that omitted whitespace before an opening parenthesis.  This was incorrectly recognized by the upgraded SEXP parser as an invalid SEXP.  Unfortunately, a separate bug in `get_line_num()` caused a crash when the parser tried to display a warning, because the function tried to calculate the line number of a SEXP that did not come from a parsed file.
This commit fixes the parser to recognize opening parentheses even when no whitespace precedes them, moves the output to the 'unexpected end of sexp' warnings will they will now be seen, and fixes `get_line_num()` to work when there is no parsed text.
Follow-up to …
=> fix crash in unusually formatted handwritten SEXP

code/missionui/redalert.cpp
Two fixes for red alert missions:
1. Since any ship in the wing can be stored, not just the wing leader, the "prospective name" check should check for all possible names in each wave
2. If a wing wasn't actually stored, the red alert code should not reset the wing's wave number to 0
Follow-up to #4457.
=> improve checks for red-alert status

code/parse/sexp.cpp, code/scripting/api/objs/parse_object.cpp, code/scripting/api/objs/ship.cpp
The `collides` and `no_collide` flags are equivalent, but opposite.  So when sexps or scripts get or set those flags, allow each to be used as an anti-synonym (not exactly an antonym) for the other.
=> sync setting and getting of collides and no_collide

code/scripting/api/objs/player.cpp, code/scripting/api/objs/player.h
I think when I originally tested this I used the return value to verify that it was working. Turns out that wasn't a good enough test because the scoring_struct_h explicitly makes a copy of the player stats, probably to prevent manipulation. However, in the case of storing and reloading mission stats (for checkpoints), we need to actually apply the stats to the player's stats and not the copied stats.
So I've added a way to get the player from the scoring stats and in the case of setting the mission stats, apply them directly so that it actually.. ya know.. works.
=> Fix setting mission stats

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-standalone.yaml, .github/workflows/build-test.yaml, .github/workflows/cache-master.yaml, .github/workflows/test-pull_request.yaml, ci/linux/configure_cmake.sh
Statically link to libstdc++ for CI/CD builds in an attempt to avoid compatibility issues without relying on a crippled or out-of-date build image.
Also returns #5547 as we should no longer have to remove it as a workaround.
=> use static libstdc++

code/scripting/api/objs/weapon.cpp
1. Allow setting the homing subsystem if the homing object has already been set
2. Use the `weapon_set_tracking_info` function if setting both object and subsystem, as it handles several important homing things
=> some fixes for setting HomingSubsystem in script

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-test.yaml, ci/linux/create_dist_pack.sh
- handle double archiving of macOS builds so they'll work properly with Knossos
- fix issue where only a single configuration was included in the package (Release or FastDebug, not both)
=> fix macOS build packaging issues

code/hud/hudescort.cpp
In #5477, I made the escort list respect hidden names by copying the behavior from `message_queue_process()`, which already checked those flags; however, this resulted in some dramatic behavioral changes for mods using callsigns for escort ships, so making the "replace ship name with callsign" part of the code optional, and disabled by default, should result in minimal changes for existing mods while still fixing the bug of the escort list not hiding ship names properly, and still allowing mods to show callsigns in the escort list if they *do* want that.
Tagging this as "regression" because it's not *strictly* a bug, but affects backwards-compatibility nonetheless. Making this a draft because I don't want to change this again without some proper feedback along the lines of: should it …
=> Make the escort list show ship names as well as callsigns.

code/weapon/weapons.cpp
Add some extra logic implied by the `Begun_detonation` flag.  Missiles that are homing can have their targets, headings, speeds, and lifetimes changed for various reasons.  If a missile has begun detonation, particularly if it is in "detonation limbo" because it is flying across a bowl-shaped turret, we don't want to change any of that.  The "detonation limbo" weapon lifetime is only accurate if all of those values remain constant.
Follow up to #4006.
=> fix weapon detonation

code/gamehelp/gameplayhelp.cpp
Gameplay Help only inits once, so once Help_Text is populated we shouldn't clear it or we get an out of bounds vector crash upon the second time entering Gameplay Help UI.
=> Do not clear Help Text

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-test.yaml
Use GNU tar instead of the default bsdtar. This works around some weird corruption bug triggered by the combination of the GitHub runner-VM, the llvm linker, and bsdtar.
Adjust intermediate filenames such that they don't get uploaded to indiegames by mistake.
Unpack builds as a single step instead of two.
=> tweak mac build packaging

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-test.yaml
And this kids, is why you don't test locally on a system with a bunch of shell aliases and helpers in use.
=> fix bad extraction command in mac distribution zip

code/ai/aibig.cpp
The target world pos should use `model_local_to_global_point` since it could be at the end of whoever knows how many subobjects parented together.
=> Fix for improved subsys attack pathing

code/ship/shiphit.cpp
I'm not exactly 100% sure what causes this specific situation, but looking at the function, it seems that getting a null object as the other hit object is allowed.
This fixes the damage carry check, and since not carrying the damage will happen with all non-shockwaves, it'll also happen with null objects. The check in L 958 is safe btw, since weapon_info_index is guaranteed to be -1 for a null other_obj (in fact, checks further up in the function already rely on that)
=> Fix null dereference when a subsystem is hit for damage by a null object

code/mission/missionparse.cpp, code/parse/sexp.cpp, code/scripting/api/objs/oswpt.cpp, code/ship/ship.h
The Star Fox barrel roll effect is achieved using a script which spawns a new ship.  The script sets no-collide on this spawned ship, but it also tries to set the ship flag for all future ships -- and future ships require a parse object, which doesn't exist for a created ship.  This patches the FALLTHROUGH in the sexp code to account for that possibility.
Separately, there are other ways a parse object pointer could become null through unusual code states, so this adds an INVALID status and several additional checks to defend against this crash in other circumstances.
=> fix barrel roll crash in Star Fox: Event Horizon

code/missionui/redalert.cpp, code/missionui/redalert.h, code/pilotfile/csg.cpp, code/pilotfile/pilotfile.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h, freespace2/freespace.cpp
If consecutive red-alert missions have different numbers of ships in a wing, then calculating the number of waves will not be correct.  This necessitates the addition of wing status to the stored data for red-alert sequences.
Not only must wing data be stored in `Red_alert_wing_status`, but also in the CSG file.  This necessitates a version bump.  Fortunately, the current design of CSG files allows extra data to be added to a section without breaking old builds, since the CSG loader will just skip over the unrecognized data.
This also renames `red_alert_wingman_status` to `red_alert_ship_status` since it's not limited to wingmen, as well as fixing the omission of exited ships if they are in the player's wing but don't have the red-alert-carry flag.
Fixes #5637.  Follow-up to #4457 and …
=> add wing status to red-alert system

code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/ship.h
There is a bit of code in missionparse that sets the parse object because in-game joining needs it.  This is unrelated to ship status, so the status shouldn't be changed.  This fixes the bug and adds a comment to clarify the situation, as well as some warnings to help track down incorrect joining states.
Fixes #5661.  Follow-up to #5658 (where the regression was introduced) and #4836 (which fixed in-game joining).
Also adds a ship registry entry for support ships, since in testing that issue was (correctly) flagged by the warnings.
=> remove incorrect setting of ship status

code/menuui/techmenu.cpp, code/missionui/missionbrief.cpp
Use the same method for texture replacement in briefing popups that is already used in the tech room.
Also don't render shadows when the jump node is displayed, since it's not being lit anyway.
I recommend reviewing this PR while ignoring whitespace changes, to make the briefing popup section clearer.
=> fix replacement textures in briefing popup

code/hud/hud.cpp, code/mission/missionparse.cpp, code/mission/missionparse.h, code/parse/sexp.cpp, code/parse/sexp.h, code/scripting/api/libs/mission.cpp
BtA has a couple missions with "time skips". In order to help sell the illusion we dreamt up this sexp that simply pads out the HUD timer with N seconds. It's entirely an illusion. Does not affect actual mission time or the mission log in any way.
Also adds a virtvar to get/set the same value.
=> Set timer padding sexp

code/mission/mission_flags.h, code/parse/sexp.cpp, code/starfield/starfield.cpp, code/starfield/starfield.h, fred2/fred.rc, fred2/missionnotesdlg.cpp, fred2/missionnotesdlg.h, fred2/resource.h, qtfred/src/ui/dialogs/MissionSpecDialog.cpp, qtfred/ui/MissionSpecDialog.ui
Adds a mission flag to preload the subspace tunnel. Allows for missions with scripts that call the effect to make sure it's preloaded without having to do some hacky sexp just to get that feature to work.
FRED support tested and working. qtFRED not so much because qtFRED currently CTD's just after startup on the SCP master branch, but I'm fairly certain it's implemented properly.
=> Preload subspace tunnel flag

code/scripting/api/libs/graphics.cpp
Some scripts under development will benefit from access to the `particle::kill_all()` function.
=> add gr.killAllParticles

code/popup/popupdead.cpp, code/scripting/global_hooks.cpp
Adds the death message that is normally drawn to the screen as an HV of the death popup hook so that SCPUI can #dothingswithit
=> Add death message as a dialog HV

code/scripting/api/libs/mission.cpp
Lua API access to check if a support ship can be called in by the player.
=> Lua access to Support Ship availability

code/scripting/api/objs/shipclass.cpp, code/scripting/api/objs/weaponclass.cpp
These can be used to set whether a ship or weapon is allowed in loadouts, without necessarily waiting for the mission to be accepted.
Tested by IceCreamMan.  Needed for both Event Horizon and Scroll.
=> add AllowedInCampaign virtvar

code/parse/sexp.cpp, code/scripting/api/objs/beam.cpp, code/scripting/api/objs/subsystem.cpp, code/scripting/api/objs/weaponclass.cpp, code/scripting/global_hooks.cpp, code/scripting/global_hooks.h, code/weapon/beam.cpp
1. Add a `vanish()` function for beam objects, to be consistent with other object types
2. Add a `BeamFree` virtvar, analogous to `TurretLocked`
3. Add timestamp variants of TurretLocked and BeamFree to be consistent with sexps
4. Add `BeamLife`, `BeamWarmup`, and `BeamWarmdown` virtvars so scripts can access table properties
5. Add "On Beam Death", "On Beam Warmup", and "On Beam Warmdown" hooks
6. Clarify some existing documentation and patch a couple things
=> additional beam-related features for Lua

code/def_files/data/tables/objecttypes.tbl, code/fireball/fireballs.cpp, code/fireball/fireballs.h, code/ship/ship.cpp, code/ship/ship.h
The retail warp range multiplier can yield ridiculous results, like an Elysium warp being audible over 9000 meters away.  So allow the multiplier to be set via ship type.
=> allow modification of warp audible range via objecttypes.tbl

code/graphics/generic.cpp, code/graphics/generic.h, code/hud/hud.cpp, code/hud/hud.h, code/hud/hudbrackets.cpp, code/hud/hudbrackets.h, code/hud/hudconfig.cpp, code/hud/hudlock.cpp, code/hud/hudlock.h, code/hud/hudmessage.cpp, code/hud/hudshield.cpp, code/hud/hudtarget.cpp, code/hud/hudtarget.h, code/hud/hudtargetbox.cpp, code/mission/missiontraining.cpp, code/render/3dmath.cpp, freespace2/freespace.cpp
This PR fixes wildly inconsistent HUD slewing behaviour in FSO.
Some gauges just didn't slew at all, some slewed incorrectly, while some were allowed to slew even if they must not slew ever.
This also removes the effect of HUD_offset_x/y, as that seems to be partly redundant with HUD_nose_x/y, and causes HUD gauges to never be anywhere near correct as soon as its nonzero. However, as there may have been plans for it, it's just commented out instead of removed outright.
Prerequisite for #5583.
=> Fix HUD slewing

freespace2/resources/win/default.manifest
This fixes #4588.
At least it does so on Win10, previous versions may still behave differently.
Required for #5583.
=> Fix hiDPI Windows Scaling

code/scripting/api/libs/ui.cpp
Exposes the URL launching method from multi_pxo to Lua for SCPUI. It would be handy to be able to link to a mod's forum or other related links directly from the game, much like how modern games do the same.
=> Lua method to launch arbitrary url

code/parse/sexp/LuaSEXP.cpp
Just a quick parsing change to allow Lua SEXPs to not specify a subcategory and in that case they get `OP_SUBCATEGORY_NONE` without trying to add a new category. This allows placing sexps near `do-nothing` or `debug` in the change category or to place them in places like `Training` category without a subcategory.
=> Allow Lua SEXPs to not specify a subcategory

code/scripting/api/libs/base.cpp
A quick method to get the current mod's root folder name. Will be useful for SCPUI's data saving features.
=> LUA get mod root

code/ai/aigoals.cpp
Change `ai_mission_goal_achievable` to use the ship registry instead of looking up the target repeatedly.
=> refactor ai_mission_goal_achievable

code/ai/aicode.cpp, code/hud/hudets.cpp, code/object/object.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h
This flag ignores engine status when determining whether and how a ship can maneuver.  Implements #5503.
=> add a maneuver-despite-engines flag

fred2/management.cpp, qtfred/src/mission/Editor.cpp
Simply removes the newline characters from the default mission Notes and Description. SCPUI can be set to actually display these values but requires additional code to remove the newlines because they mess with the default SCPUI mission grid view. It's minor to deal with, but I'm also thinking it's pretty minor to just remove them by default.
=> Remove new lines from default generated mission fields

code/def_files/data/scripts/dkjson.lua, code/menuui/credits.cpp, code/scripting/lua.cpp, code/source_groups.cmake
Adds dkjson, as used by a large number of community scripts, as a default script bundled with FSO. The convenience of always knowing that json functions are available cannot be understated. The main thing I'm unsure of is license compatibility.
Notably, this script creates no globals of any kind. It must be used by first requiring it with `require('dkjson')`.
=> Add dkjson as a default lua file

code/mission/missionparse.h
I was gonna vectorize `Cargo_names` but it's ugly. So I'm taking the path of least resistance and just doubling the size of the array. According to the comments here, it should be OK and some brief testing showed no noticeable errors.
I thought about going all the way to 64, but I liked a nice round number instead.
=> Double the allowed cargo from 30 to 60

code/ship/shiphit.cpp
If a ship is in the process of dying, it shouldn't be killed or self-destructed again.  This fixes a bug noticed by RedMageJoe during the Derelict playthrough.
(This situation is distinct from a ship being hit while in the middle of its death roll.  That shortens the death roll but does not try to kill the ship again.)
=> don't kill/self-destruct ship if it's already dying

code/io/keycontrol.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h
Remove a whole bunch of ad-hoc code piled on top of the retail weapon cycling behavior, then replace it with a robust algorithm that takes all relevant attributes into account.
Fixes #5529.
=> rewrite primary weapon cycling

code/physics/physics.cpp, code/physics/physics.h, code/ship/ship.cpp, code/ship/ship.h, code/ship/shipfx.cpp, code/ship/shipfx.h, fred2/fred.cpp, fred2/fred.rc, fred2/fredrender.cpp, fred2/fredrender.h, fred2/fredview.cpp, fred2/fredview.h, fred2/resource.h, qtfred/src/mission/EditorViewport.h, qtfred/src/mission/FredRenderer.cpp, qtfred/src/ui/FredView.cpp, qtfred/ui/FredView.ui
This adds the ability to calculate the arrival distance of a ship using the default warp effect.  There is a new option (in both FRED and qtFRED) to display a gray wireframe outline of the ship projected forward to its final location.
Credit to @Baezon for figuring out the math involved.
=> add support for predicting arrival warp distance

code/scripting/api/libs/mission.cpp
The `mn.createWeapon()` function takes an optional group ID for weapons that share lighting, but the internal `weapon_create_group_id()` function was never exposed to the API.  This adds that.
=> add mn.generateWeaponGroupId()

code/scripting/global_hooks.cpp, code/scripting/global_hooks.h, freespace2/freespace.cpp
I needed to reliably run a script for SCPUI after all game init methods have been completed but before the game actually moves on to the Intro and other game states. On Splash Screen worked but is deprecated, so this adds a new hook just before the intro that allows me to do what I need.
=> Intro about to play hook

code/model/modelread.cpp, code/model/modelsinc.h
Modelread.cpp supports POF versions as low as 1900, but early model versions were not loaded properly because they relied on preprocessor directives rather than version checks.  This changes the POF loading to correctly check version numbers and chunk IDs.
Fixes crashes when attempting to load a FS1 model.
=> POF version fix

code/mission/missionmessage.cpp, code/mission/missionmessage.h
This PR introduces a few enhancements to the dynamic message system:
* Message filters can look at a ship's IFF.
* A dynamic message can be filtered based on the presence of other ships in the mission, and can do so with a range check. Alongside an IFF filter, this can be used to play different versions of a message when the speaker is "in battle" or not.
* The tiebreaker system can be further customized, for cases where two messages have filters but the author wants one to beat the other. (Maybe one of your pilots has a special arrival message for HoL ships, and another for enemy bombers. Currently, when this pilot announces HoL bombers, they'll pick one of those two at random. This feature lets you pick one message or the other.)
* Lastly, as a QoL enhancement, when a message is …
=> More message filters

code/def_files/data/effects/deferred-f.sdr, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/matrix.cpp, code/graphics/matrix.h, code/graphics/opengl/gropengldeferred.cpp, code/graphics/util/uniform_structs.h, code/ship/ship.cpp
This gets rid of dark, unshaded spheres in the cockpit close to the camera by doing two things:
1. Unify all near-z distances used in cockpit rendering to one common value, and make that a proper variable instead of hardcoding it everywhere.
2. Properly pass that to the deferred lighting shader instead of having a magic constant for closest allowed shading distance in there.
=> Fix near z planes for the cockpit rendering

code/mission/missioncampaign.cpp, code/playerman/managepilot.cpp
Fixes coverity 1093679 and 1093680 by freeing if an early return is reached.
=> Fix two small memory leaks

code/network/chat_api.cpp
Before this change if the wrong endianness was used, the c style cast that was used here would lead to the argument being passed to getsockopt to lack the actual information it needed.
Fixes coverity 1093482
=> Change underlying type to avoid endianness problem

code/io/keycontrol.cpp, freespace2/freespace.cpp
Guarantee that this block will not divide by zero and accidentally crash while debugging. 
For coverity 1107324.
Also add a clarifying comment for another false positive coverity issue.  (turns out modulo division is slow)
=> Avoid edge case divide by zero

code/parse/sexp.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
What it says on the tin.  Implements #5531.
Also reorders two arguments on the popup menu to be consistent with other sexps.
=> enhance set-armor-type to work with generic subsystems

code/ship/shipfx.cpp
Fixes #3098. The `shipfx_eye_in_shadow` function did a collision check for cockpits, bit did not previously take into account of the viewpoint had a non-forward orientation (IE the player was using free-look). This PR sets the collide check to take that into account with a 1 line fix. Tested with multiple FotG cockpits and fixes the issue.
=> Fix glare shining through cockpits in free-look

code/io/keycontrol.cpp
Normally the disabled/disarmed flags are only set if the destroyed subsystem is actually an engine or turret.  This should be done for cheats as well, otherwise, for example, destroying any subsystem on a non-engined ship will cause it to become disabled.
=> fix incorrect setting of disabled/disarmed flags when cheating

code/object/collideweaponweapon.cpp
`max_lifetime - lifeleft` is not necessarily an accurate way to gauge how long a weapon has existed, partly because it can be messed with and fall at variable rates, but also (in the case which exposed this bug) because scripts can set it to arbitrary values, causing this code to make the weapon invulnerable longer (or shorter) than it should. `Missiontime - creation_time` is preferred for this reason, and all other code which needs to know how long a weapon has existed uses that.
This is fairly niche and the script could easily work around it so I don't consider it a priority for the stable.
=> Bugfix missile time for 'aspect invulnerability time'

code/hud/hud.cpp, code/hud/hud.h, code/hud/hudparse.cpp
Implements #5472 with a simple boolean flag for the damage gauge. If true then all damage values will always be drawn.
A note on hud.cpp line 2024: Changing the value here from 1000.0f to 1.0f prevents the subsystem damage text from flashing at mission start if Always Display is true but still ensures that the text flashes without the feature if the damage is less than 1.0f where 1.0f == 100% hull integrity.
Fixes #5472
=> Add feature to always display the damage gauge

code/ship/ship.cpp
I have looked at making this fail more gracefully, but the system is quite entangled. The `ship_info` has already allocated these `model_subsytem`s and they are implicitly trusted by the very subsystem itself, as well as any other ship classes which use the same model, which will *also* lean on those same `model_subsystem`s. Failing to find the model entry fails to set up a lot of data which rapidly escalates into memory errors. Consider this PR a request for help on how to make this gracefully fail as much as an advocacy to make it an error.
I have seen this surprise users at least a dozen times now. It introduces bizarre bugs and behaviors which users have difficulty reconciling with the nature of the warning, and, in the most recent case, *earlier instances of this issue on different …
=> Make invalid model_subsystem model_nums a hard error

code/scripting/api/libs/graphics.cpp
Since `gr_string` can accept a length parameter, there's no need to copy each line before it is drawn.
Related to #5495 but not one of the two options mentioned.
=> small speedup to drawString

code/gamehelp/gameplayhelp.cpp, code/hud/hudmessage.cpp, code/io/keycontrol.cpp, code/mission/missionhotkey.cpp, code/mission/missionmessage.cpp, code/mission/missionmessage.h, code/missionui/missionpause.cpp, code/network/multi_pause.cpp, code/scripting/api/libs/audio.cpp, code/scripting/api/libs/ui.cpp, code/sound/ds.cpp, code/sound/ds.h, code/sound/sound.cpp, code/sound/sound.h, freespace2/freespace.cpp
Not sure if this ever worked in retail, but it should in 2023. This adds sound methods to pause and resume sound handles which are then used in mission message to pause and resume voices. I've added the appropriate pause/resume methods to all areas expected (essentially all the same places where weapons and audiostreams (music) are paused as well).
=> Pause and Resume voices

code/mod_table/mod_table.cpp, code/mod_table/mod_table.h, code/ship/ship.cpp
Subsystem hitpoints are calculated as a percentage of the ship's hull strength as they are parsed.  If a modular table modifies the ship's hull strength, the subsystems are not modified at the same time.  This can lead to unreasonably large or small subsystem hitpoint values, as recently seen in the 1.3.0 version of Cardinal Spear.
This PR adds an option to defer hitpoint calculation until after parsing so that the subsystem is a percentage of the correct hull strength.  Since this may affect the balance of existing mods, it is off by default unless the build targets 24.0 or later.
This also removes the long-unused `hull_percentage_of_hits` check and adds several log statements for significant options in game_settings.tbl.
=> add "Calculate subsystem hitpoints after parsing" option

code/graphics/2d.h, code/graphics/material.cpp, code/graphics/material.h, code/math/vecmat.cpp, code/math/vecmat.h, code/model/model.h, code/model/modelinterp.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/model/modelrender.h, code/model/modelreplace.cpp, code/model/modelsinc.h, code/render/3d.h, code/render/3ddraw.cpp, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/model.cpp, code/ship/ship.cpp, code/ship/ship.h
See title.  There were some cascade effects, but the changes are mostly contained to the model code.  The calls to `gr_render_model` and `g3_render_primitives` use `const_cast` because constifying that API would require a whole other PR.
=> add const where appropriate to the modelrender API

code/object/objectsnd.cpp, code/object/objectsnd.h
This fixes a small warning on mac compilers that OS_USED was previously defined in the SDK.
=> Fix Redefined Macro Warning

code/ship/ship.cpp, code/weapon/weapon_flags.h, code/weapon/weapons.cpp, fred2/management.cpp, qtfred/src/mission/Editor.cpp
Adds the weapon equivalent to "default player ship" flag. This flag defines what weapons are default in the player loadout in FRED/qtFRED. Fixes #5552
=> Add default player weapon flag

code/gamesnd/eventmusic.cpp
The fix in #5578 assumed that a previously playing soundtrack would properly set the timestamp, but if no soundtrack was previously played at all, this wouldn't happen.  So if we deliberately don't play a soundtrack, be sure to set the timestamp as if `event_music_do_frame()` had been called.
Fixes #5705.
=> fix change-soundtrack after <No Music>

.gitignore
This would be pretty helpful to me, as for some reason on my Mac, vscode does not automatically know how to build FSO and I have to create a preset to build it.  But every time I do, it gets added to the changes I have to uncheck when making commits.  LMK if this change is undesired for any reason as I could live with the inconvenience, if necessary.
=> Add CMakePresets.json to gitignore

code/missionui/missionweaponchoice.cpp
If a wing has fewer than four ships, clicking the apply-to-all button will cause a vector subscript out of range error.  This fixes it.
=> fix a crash in the apply-loadout-to-wing routine

code/weapon/weapons.cpp
The code has always checked a per-weapon-class value called `lock_fov` when comparing the dot product of a ship to its target to see if it can lock on to it, however the weapon table hasn't ever included a way to set this value; it's always the default value of 0.85. This just adds "+Lock FOV:" entries to aspect/javelin homing missile parsing after "+Seeker Strength:", which will set `lock_fov` as long as the supplied input is between 0 and 360 degrees.
(Note to self: don't forget to update the wiki whenever this gets merged.)
=> Make `lock_fov` settable for aspect/javelin missiles.

code/missionui/missionweaponchoice.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
This PR adds an option to always ensure the viewed weapon is one that can actually be on the selected ship when first clicking on the weapon loadout.
If you go to the loadout in the briefing and view the weapons on your ship, then go and change your ship class and go back to the weapon loadout screen, you will see that the weapon shown in the window on the right side is from your very first viewing before you changed your ship class. Displaying a weapon not allowed on a ship by default can be confusing to players, especially on mods like FotG where most ships have unique weapons.
The player can still of course click on a non-allowed weapon to view it, but with this PR the player will be initially shown a selected weapon that is allowed on the ship when opening the loadout editor.
Tested …
=> Add Game Option to refresh selected weapon in loadout

code/mission/missionparse.cpp
Occasionally, FRED can save a mission with a wing's ships out of order; this can happen if ships are deleted and FRED finds a free index in the middle of the ship list.  This can cause benign but confusing mismatches in the ship registry, the hotkey list, and other places -- and it's also possible some mismatches may not be so benign, e.g. in multiplayer.  Anyway, it's better for the ships to appear in the order the wing expects them, so this adds a routine to swap them around if necessary.
Due to a change in indentation, I recommend viewing the diff while hiding whitespace changes.
=> handle parse objects that are out of order

code/hud/hudtarget.cpp, code/render/3dmath.cpp, fred2/fredrender.cpp, qtfred/src/mission/FredRenderer.cpp
Follow-up to #5656. In that PR, in determining the direction to point for the HUD target triangle, the calculation uses the `screen` position of the projected point, but `g3_project_vertex` early returns and leaves `screen` uninitialized if the point is behind the camera. However, VR requires the screen position and not the old `world` position (the point transformed into the camera space).
This PR still sets the `PF_OVERFLOW` flag, but projects the point regardless (and flips it because everything would be backwards). This way it can still give a meaningful result, while alerting any callers it's behind the camera. All callers properly check for this flag in all relevant behavior, or have been updated to do so to ensure behavior is unchanged.
Tagging @BMagnu to hopefully ensure this …
=> Bugfix HUD target direction triangle

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-test.yaml, .github/workflows/test-pull_request.yaml
Now that a fix should be in place with the 20231023.1.0 runner image it should be safe to revert the previous workaround.
=> revert workaround for the windows runner breakage

code/particle/particle.cpp
If a particle has an `attached_objnum` then `pos` is *relative* to that object, so keep in mind when calculating distance from camera for culling.
=> Fix for particle culling

.github/workflows/build-release.yaml
This should fix the point release workflow by adding a the reference branch (the branch that initiates the workflow) to checkout.  In my tests, regular releases do still seem to pull master, and the new point releases pull the separate branches.
=> Fix Point Release workflow by adding reference branch

code/scripting/api/libs/ui.cpp
Mimics optionsmenu.cpp line 1045 that saves both files on options close. This ensures that SCPUI options are properly respected throughout the rest of the game.
=> Allow SCPUI saving current player data to file

code/ai/ailua.cpp, code/tgautils/tgautils.cpp
Fix two small coverity memory leak issues.  (de ja vu, I know)
EDIT:  Yes, the tga code is not currently used, but on the off-chance that it ever were used again, I'd rather it not have a memory leak.
=> Fix resource leaks

code/menuui/mainhallmenu.cpp, code/menuui/mainhallmenu.h, code/scripting/api/libs/ui.cpp
For being able to force it enabled on first run to help players know where to click.
=> Provide Lua a way to toggle the mainhall help overlay

code/ai/aigoals.cpp, code/ai/aiturret.cpp, code/fireball/fireballs.cpp, code/hud/hudtarget.cpp, code/mission/missionmessage.cpp, code/missionui/missionbrief.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp, code/weapon/beam.cpp, fred2/briefingeditordlg.cpp
A mission in Mantle caused an invalid vector access when checking whether to vaporize a ship whose ship type was -1.  Turns out having "no type" is actually allowed, so I audited all `class_type` accesses throughout the code for potential -1 accesses.  Most were properly checked but a few were not.  A few others needed to be tweaked.
(I suspect this is something that would be on the Coverity list if it isn't already.)
=> make sure class_type exists when used

code/mission/missionparse.cpp
For missions which use the Persona Index method, make sure the mod doesn't load a persona index that is out of range for the personas it knows about.
=> check for out-of-range persona

code/menuui/optionsmenumulti.cpp, code/object/waypoint.cpp
Clobbering global data is bad.  So make sure we check for negative indexes in these three places.
To make the code more resilient, I've also removed an int3 and replaced with an assertion.  It was really not a major issue to have that function not find a player: it's enough to just ignore the user action.
=> Fix negative array index writes

code/controlconfig/controlsconfig.cpp, code/network/multi_obj.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp
This handles all new (and one old) variable cannot be negative issues.  Based on the severity, I've either added just an Assert or added a full check.
This includes an actual edge case bug, where a garbage timestamp might get set when no countermeasure is set, keeping the player from firing a countermeasure if a countermeasure is added to their ship.
=> Fix coverity variable cannot be negative issues

code/ai/aicode.cpp, code/parse/sexp.cpp, code/parse/sexp.h
Adds `force-rearm` and `abort-rearm` sexps. Notably, the docking code and rearm code are not quite as tangled as I had thought they would be. They could still use a bit of a refactor to separate them but I've avoided that here, opting for minimal changes to the codebase. With one small change to aicode.cpp, we can essentially tell a ship to rearm itself which is what the `force-rearm` sexp actually does here.
`abort-rearm` simply runs the abort code and will work for any rearm type, whether forced or not.
Fixes #5269
EDIT: I should note that if the ship that is force rearming itself has the appropriate persona message, then they will be played. I left off customizing that to keep the sexp focused. In most cases, the ship force rearming itself will not have rearm persona messages defined …
=> Force rearm sexp

code/ai/aibig.cpp, code/hud/hudets.cpp, code/ship/ship.cpp, code/ship/ship.h
The ship's maximum velocity is updated when the ship's engine strength changes, but `ship_get_subsystem_strength` always reports 15% when below 15%, causing the code to erroneously believe the engine strength isn't changing (when it is probably auto-repairing). Repairing under this threshold wouldn't cause the max velocity to change, but it is supposed to prevent ETS changes from ignoring the whole engine damage bit, so use the actual engine strength to determine when to apply 'damaged' engine velocities.
=> Fix for ets changes when engines are <15%

code/localization/localize.cpp
While I was adding strings to the engine, it became obvious that there's no good way to have the engine output a list of a strings and string IDs from the engine because they are only handled when the code is running through a section with an XSTR call. Over the years SCP has added several new strings and IDs as well as allowing a few tables like controlconfigdefaults.tbl and sexps.tbl to define "built-in" strings. This made it tough to find what IDs are available to use. So my best idea was to add an `nprintf` (XSTR debug filter) for XSTRs that simply outputs to the log each string and string ID that XSTR handles as it handles them.
This is still not a fool proof way, but it's much simpler and more reliable than searching the code for 'XSTR' function references because some of those …
=> xstr debug filter

code/ai/ailua.cpp, code/mission/missionparse.cpp, code/mission/missionparse.h, code/missionui/missionweaponchoice.h, fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
1. The player can target other object types besides ships, so when creating an `object_ship_wing_point_team`, make sure it is a ship
2. A few recent mission features require a version bump, but not all missions use these features; so do a "soft bump" where the mission version is updated only if necessary
3. Remove an unneeded #include by adding a `struct team_data` declaration (see #5599)
=> some polishing of recent changes

.github/workflows/weekly-coverity-scan.yaml
Since we removed travis ci, coverity has been unused for six years.  This allows us to automatically submit a linux build to coverity scanning once a week.
=> Add a weekly coverity workflow

code/ai/aibig.cpp
Follow-up for #5634. Changing this to `model_local_to_global_point` fixes the case where the subsystem is a submodel... but breaks when the subsystem is a special point. Use the function that already exists to determine between these cases instead.
=> Fix subsys positions in `ai_new_maybe_reposition_attack_subsys`... again

code/ai/aibig.cpp
This keeps us from using a pointer to a variable that went out of scope. Coverity  1523195
=> Change the scope of this pointer

code/cfile/cfile.cpp, code/model/modelrender.cpp, code/starfield/nebula.cpp
This handles the remaining coverity issues that popped up on the October 30th scan.
This going to need an eye from a graphics coder if possible.  The code is not safely relying on pmi being not null, but I'm not sure if I fixed that correctly.
=> Handle oct30 covscan issues

code/scripting/api/libs/audio.cpp, code/scripting/api/objs/sound.cpp, code/sound/ds.cpp, code/sound/sound.cpp, code/sound/sound.h
This PR upgrades the LUA Sound Handle methods to add the newer pause/resume methods. It also allows for specifying using either the Effects volume multiplier or the Voice volume multiplier where appropriate. 
(Note that music handling is not added here because music should still be done with AudioStream as well as the fact that there's no sound_handle methods that take the master music volume into account. They generally assume either voice or effects.)
Relies on PR #5636 and set as draft until that is merged.
=> Upgrade Lua Sound Handling methods

code/missionui/missionscreencommon.cpp, code/mod_table/mod_table.cpp, code/mod_table/mod_table.h
SCPUI rolls it's own, much more robust, loadout saving and restoration system. It turns out there are rare cases where the built-in loadout system can conflict with it, so this exposes a toggle to disable the internal one entirely.
Note: this does not disable direct loadout restore which is still used when a player restarts a mission immediately.
=> Mod setting to disable FSO's internal loadout restoration

code/ai/aicode.cpp
Fix #5759 by making sure the code is only run once on undock and add extra check to make sure that the ending code is only run if doing a force repair.
=> Fix #5759 Sticky Support Ship

code/hud/hudmessage.cpp, code/hud/hudmessage.h, code/mission/missionlog.cpp, code/mission/missionlog.h, code/scripting/api/objs/missionlog.cpp
Simply saves the current timer padding when a log entry is created. Provides a way for SCPUI to get the padded time instead of the regular time.
This takes the padded timer feature a little further than I originally intended but it ended up being confusing to have the mission clock say 25+ minutes while messages and events were still happening at -7 minutes. So this provides SCPUI a way to keep the illusion alive if a mod wants to.
I thought about making it default behavior and adding it to the retail UI as well, but that seemed a step too far. Open to discussion on that, though. Regular time is still useful for development and testing purposes because that's the real game clock.
=> Provide a way to account for timer padding in the mission log

code/mission/missionmessage.cpp, code/mission/missionmessage.h, code/parse/sexp.cpp
In a few places where the game checks for the command sender, it should check for #Command as well, as long as the mission flag to override #Command is present.
Additionally, while the mission's command sender was originally intended to be a ship, it has been used to specify an alternative to #Command as well.  But this caused problems when the "override #Command" mission flag was active, as it transformed a hashed source into a non-hashed source.  So this commit adds a check to treat the source as hashed, if necessary, if a replacement has occurred.
Fixes #5749.
=> Command fixes and tweaks

fred2/fred.rc, fred2/resource.h, fred2/voiceactingmanager.cpp
One of the Voice Acting Manager dialog's strings is now too long for the .rc file and is truncated at 256 characters.  Fortunately this can be worked around by setting it at runtime.
=> fix a FRED compilation warning

code/hud/hud.h
Followup to #5656.
Removes now unused and undefined variables that just had a stray declaration left.
=> Removed unused variables in HUD code

code/ai/aiturret.cpp, code/hud/hudtarget.cpp, code/hud/hudtargetbox.cpp, code/ship/ship.h, code/weapon/weapons.cpp
Add `const` to the `eval_enemy_obj_struct` struct so its values aren't inadvertently overwritten.  Handle a bit of const-correctness propagation.  Also add default member initialization to the struct.
=> protect eval_enemy_obj_struct input values

code/asteroid/asteroid.cpp, code/debris/debris.cpp, code/model/model.h, code/object/collideshipship.cpp, code/weapon/flak.h
Add `const` to the `mc_info` struct so its values aren't inadvertently overwritten.  Tweak some of the collision code to prevent overwrites.
Also remove the `flak_muzzle_flash` declaration since that function no longer exists.
=> protect model_collide input values

fred2/freddoc.cpp
Some patches for mission imports:
1. Check that the path isn't empty (the user didn't select "This PC") before continuing
2. Count successful imports
3. Avoid treating an import as a newly saved single mission unless the import was successful
=> FRED import fixes

code/ai/aiturret.cpp, code/cheats_table/cheats_table.cpp, code/hud/hudartillery.cpp, code/menuui/fishtank.cpp, code/nebula/neblightning.cpp, code/network/multi_pxo.cpp, code/network/multiui.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/weapon/beam.cpp, code/weapon/emp.cpp, freespace2/freespace.cpp
Some of the `frand_range` calls were used for integer calculations, so we can use `Random::next` now.
This also reduces the number of C-style casts in the codebase.
=> convert some instances of frand_range to Random::next

code/menuui/mainhallmenu.cpp, code/menuui/mainhallmenu.h, code/scripting/api/libs/ui.cpp
Mainhall is the only place where retail UI and SCPUI mix (using dialogs) and there are times when I need it to not process keypresses.. notably when taking user input in the form of typing. The existing enable/disable input methods do not override this behavior so this adds a simple bool to toggle it.
=> Mainhall ignore input

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/grstub.cpp, code/graphics/opengl/gropengl.cpp, code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropengldraw.h, code/graphics/opengl/gropengltexture.cpp, code/graphics/vulkan/vulkan_stubs.cpp, code/io/mouse.cpp, freespace2/SDLGraphicsOperations.cpp, freespace2/freespace.cpp
This allows FSO to render the actual game at a different resolution from the window, by routing all rendering through an additional framebuffer (only if the option is actually used, for performance reasons).
I.e. -res 1920x1080 -window_res 1000x1000 will render the game and UI at 1080p, but the window will be 1000 by 1000 pixels large, with the image stretched to fit.
There are mainly two uses for this:
1. It allows a modder to test HUD / Mainhall / UI-setup for high resolutions or strange aspect ratios, even if the modder has no screen that could actually support that resolution.
2. In VR, users will regularly run FSO at resolutions higher than their displays, as the VR image is sent to the HMD before the downscaling. Without this, they'd also need a screen to support this to allow for …
=> Add command line option for window resolution
