code/ship/ship.cpp, code/ship/ship.h, code/weapon/weapon.h, code/weapon/weapons.cpp
This code adds recoil via a weapon flag as well as a ship and weapon recoil modifier for those who want to change how recoil affects their ships.
=> Recoil related code

code/hud/hudshield.cpp
I wonder if fixing some multiplayer bugs will result in people actually playing multiplayer so we can get some feedback to fix more multiplayer bugs.
=> Fix mantis 2971.

code/ai/aigoals.cpp
I have no idea why this didn't cause any issues earlier...
=> Fix usage of negative index

code/hud/hudsquadmsg.cpp, code/ship/ship.cpp
hud_squadmsg_is_target_order_valid already checks if ainfo->target_objnum is less than zero so that check is not needed
=> Fix for Coverity 1093600: Negative array index read

code/io/keycontrol.cpp
dynamic weapon point firing causes a crash when used on a fighter with more than 6 firing points
=> From LotF: Fix for Mantis 3134

code/lighting/lighting.cpp, code/missionui/missionshipchoice.cpp, code/model/modelrender.cpp
Fixes bugs reported by Niffwan in https://github.com/scp-fs2open/fs2open.github.com/pull/88.
=> Fixed ship select bracket rendering and lighting on transparent geometry.

code/graphics/gropengltnl.cpp
=> Fix Coverity 1298261 Missing break in switch

code/fred2/management.cpp, code/jumpnode/jumpnode.cpp, code/jumpnode/jumpnode.h, code/mission/missionparse.cpp
This introduces a move constructor for CJumpNode to handle freeing resources.
=> Fix for Coverity 1093690: Resource leak

projects/MSVC_2010/Fred2.vcxproj, projects/MSVC_2010/Freespace2.vcxproj, projects/MSVC_2010/code.vcxproj, projects/MSVC_2010/code.vcxproj.filters
Makes all the changes necessary for AP to compile on MSVC 2010
=> Adjustments to the MSVC2010 project files for AP

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h, code/graphics/gropengltnl.cpp
=> Retval of bm_has_alpha_channel(int handle) should be a bool 

code/bmpman/bmpman.cpp, code/bmpman/bmpman.h
=> Retval of bm_page_out(int handle) should be a bool 

code/bmpman/bm_internal.h, code/bmpman/bmpman.cpp, code/bmpman/bmpman.h
=> Retval of bm_get_size (int handle) should be a size_t

code/menuui/mainhallmenu.cpp
PR fixes issue #197 as count is declared as an unsigned int.
=> Update format string specifier to unsigned int (mainhallmenu.cpp)

code/object/objectsort.cpp
=> Resolve order of precedence compiler warning.

code/model/modelrender.cpp
=> Avoid shadowed declaration of previous local 'gpoi'

code/mission/missionparse.cpp
Proposed refactor of #Cutscenes in mission files, per wiki documentation.
Before merging, see discussion here: http://scp.indiegames.us/mantis/view.php?id=3137
=> Fix Mantis 3137

code/ai/ai.h, code/ai/aicode.cpp, code/ai/aigoals.cpp, code/asteroid/asteroid.cpp, code/asteroid/asteroid.h, code/freespace2/freespace.cpp, code/hud/hudbrackets.cpp, code/hud/hudbrackets.h, code/object/object.cpp
PR contains a set of related, but independent janitorial-style code clean ups.
This patch had been sitting on my hard drive as an out-of-tree SVN change for some time.
None should change features or functionality, and each commit can be reviewed standalone as testing ensure the build would compile between each commit.
=> Janitorial changes

configure.ac
=> [fix/badmerge_configure] Fix a bad merge in configure.ac

code/math/floating.h, code/math/fvi.cpp, code/math/spline.cpp, code/playerman/playercontrol.cpp, projects/MSVC_2013/Fred2.vcxproj
Merges master and especially the fix for the Fred2 SSE Release filenames.
=> Antipodes /merge ce69e71

code/ship/ship.cpp
=> Add correct argument to printf format string.

code/ai/aiturret.cpp
=> Resolve Coverity-reported incorrect for() loops.

code/starfield/starfield.cpp
=> Correct Warning() in parse_startbl

code/ship/ship.cpp
Should've checked more than just that FRED was working... d'oh.
=> Fix cargo size check for primary weapons I screwed up in PR 269.

code/cfile/cfile.cpp, code/cfile/cfile.h
Simple addition of Doxygen documentation.
=> Document cfile_init() function.

code/ai/aiturret.cpp, code/freespace2/freespace.cpp, code/object/collidedebrisship.cpp, code/object/collidedebrisweapon.cpp, code/object/collideweaponweapon.cpp, code/object/object.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp
Add RemHookVars() calls as appropriate, and some related cleanup.
=> Cleanup hook variable removal

code/fred2/messageeditordlg.cpp, code/parse/sexp.cpp
A few asserts, a comment correction, and a removal of an Int3()
=> various assertions to improve the sexp code

code/parse/sexp.cpp
This bug was found by, of all people, woutersmits, while FREDding his happynewyear campaign.  See http://www.hard-light.net/forums/index.php?topic=90069.0 for discussion.  The crash was triggered by the use of ( validate-all-arguments ) as the entire sexp tree for one of his mission events.
This was a two-part fix.  The first part was to ensure that every *-argument sexp (of which validate-all-arguments is but one) is actually used within a when-argument or every-time-argument tree.  More specifically, every sexp operation that expects an argument handler should first check that the arg_handler node actually exists.
The second part was to partially revert one of Taylor's old commits:
Revision: 3644
Author: taylor
Date: Tuesday, October 24, 2006 9:17:24 AM
Message:
various bits of cleanup …
=> fix an obscure edge-case sexp crash

code/parse/parselo.cpp
The previous version didn't use the c-library which would cause incompatibilities with formats that assume all format specifiers to be supported.
=> Fix SCP_string version of vsprintf

code/ai/aiturret.cpp
Probably worth noting that a previous version of this patch was posted on the forums by Axem. That version only worked with beam turrets and used "Weapon" instead of "Beam" which, in hindsight, could only lead to horrible confusion because the two classes are completely unrelated in both FSO and the Lua interface.
Any existing scripts that don't check `hv.Weapon:isValid()` before trying to use it may cause problems when a beam turret fires, but since a script that doesn't make that check is technically wrong (and a quick glance through scripting tutorials shows liberal usage of `:isValid()` checks), I'm less concerned with that than I might otherwise be.
=> Add CHA_ONTURRETFIRED support to beam and swarm turrets.

code/ship/ship.cpp
=> Fix gcc warning in ship/ship.cpp

code/hud/hudbrackets.cpp
Now it actually sets the bounds.
=> Fix gr.drawSubsystemTargetingBrackets

.travis.yml, ci/travis/before_install.sh, ci/travis/before_script.sh, ci/travis/install.sh, ci/travis/script.sh
Requires enabling the multi-os feature of travis CI
=> Add CI support for MacOSX

code/graphics/generic.cpp
EFF streaming was implemented in 48e0517e (svn r9109)
=> Remove obsolete comments

code/model/modelread.cpp
Simple change for better debug logging.
=> the model filename is useful to have in the debug message

code/freespace2/freespace.cpp, code/graphics/2d.cpp, code/io/cursor.cpp
This is currently based on the #319.
=> Fix cursor initialization

code/bmpman/bmpman.cpp, code/graphics/generic.cpp
Remove redundant Assert from bm_load_animation
Replace magic numbers in EFF streaming animations
=> Minor bmpman/generic anim cleanup

code/cfile/cfile.cpp, code/cmdline/cmdline.cpp, code/freespace2/freespace.cpp, code/model/modelread.cpp, code/network/multi.cpp, code/osapi/dialogs.cpp, code/osapi/dialogs.h, code/osapi/osapi.cpp, code/osapi/osapi.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/sound/openal.cpp, code/sound/voicerec.cpp, code/windows_stub/config.h, code/windows_stub/stubs.cpp
Also moved SCP_MessageBox into os::dialogs namespace
=> Replace Win32 MessageBox with os::dialogs version

code/inetfile/cftp.cpp, code/network/chat_api.cpp, code/network/psnet2.cpp, code/sound/acm.cpp, code/windows_stub/config.h, code/windows_stub/stubs.cpp
Now uses SDL functions. Also fixes usage of windows-only struct.
=> Remove usage of HMMIO

code/hud/hudartillery.cpp
This is PR #323, redux, without the bizarre merge that git threw in at the end.  As a bonus, git cherry-pick allowed me to edit the final commit message. :)
=> Sound index tweak2

code/ai/aibig.cpp, code/ai/aicode.cpp, code/gamesnd/eventmusic.cpp, code/mission/missionbriefcommon.cpp, code/network/multiutil.cpp, configure.ac
The unknown pragmas have been fixed by wrapping them in a visual studio ifdef
=> Re-enable two gcc warnings

code/parse/sexp.cpp
In 9ec10dd I thought I was fixing a memory leak, but the actual scenario was that the freeing was just delayed until later. This removes the freeing added by 9ec10dd and changes the `free()` calls into `vm_free()` calls.
=> Fix double-free with for-counter (introduced by myself).

code/parse/lua.cpp
This hopefully completes what PR #355 intended to do. Mistake pointed out by Echelon9.
=> Make the array bounds check actually work

code/weapon/shockwave.cpp, code/weapon/weapons.cpp
As discovered by Aesaar, CIWS doesn't actually work. This fixes that.
=> Fixes the logic surrounding the ciws flag

ci/travis/before_script.sh, code/cfile/cfilesystem.cpp, code/cmdline/cmdline.cpp, code/gamehelp/contexthelp.cpp, code/globalincs/version.cpp, code/model/modelread.cpp, code/network/stand_gui-unix.cpp, code/stats/scoring.cpp, configure.ac
This should prevent merging PRs that introduce warnings.
=> Travis CI: Make warnings fatal errors

code/weapon/weapons.cpp
I missed a branch when doing the first check.
=> Fix Coverity 1093606 for real this time

code/globalincs/pstypes.h, code/globalincs/windebug.cpp, code/parse/sexp.cpp, code/windows_stub/stubs.cpp
Creates a new variant of Warning that is not #ifdefed out on release to make the debug sexp work as its description implies
=> Fix the debug sexp

code/weapon/weapons.cpp
Broken by 88e7c83. Not sure how I missed that when reviewing the PR, but there you go. Fixes issue #396.
=> Restore local SSM behavior.

code/camera/camera.cpp
=> Fix memory leak in cam_create/cam_close

.travis.yml
i.e. they should be building debug, not release, see #387
=> Fix coverity_scan builds

coverity/modeling.cpp
This is just record keeping, I've already uploaded the new modeling file to Coverity & it's marked 14 issues as fixed. See #387
=> Model Assert/Assertion as Coverity killpaths

code/mission/missionparse.cpp
Also convert Assert to Assertion to provide more info
(aka wanted to test fix A tonight, ended up finding & fixing B instead!)
=> Guard against negative array index reads

code/ship/shipfx.cpp
Instead of changing how the mc_info struct is used throughout the code, I think it would be better if we just polished or clarified the trouble spots.  Reasons are stated in my comments on that ticket.
=> Alternative suggested PR to #384

code/cmdline/cmdline.cpp
Enable shadows with -enable_shadows
-shadow_quality should still work
=> Disable shadows by default

code/graphics/gropengl.cpp, code/graphics/gropengltnl.h
Set of individually small refactors to and around `gr_opengl_init()`.
=> Small tweaks to gr_opengl_init()

code/model/modelread.cpp
This seems to be a data error rather than a coding error. Also provide
the user with more info to assist with tracking down the source of the
problem.
See http://www.hard-light.net/forums/index.php?topic=90860 for more info.
=> Change Assert to Error

code/network/multimsgs.h
This will make sure that compiler changes that affect the size of a type are noticed early.
=> Check the size of data in multi packets

code/mission/missionmessage.cpp
Emergency fix needed here. Defaulting is not a good idea here, apparently.
=> small error correction

code/parse/sexp.cpp
Improve sexp help for two sexps, prompted by the discussion on HLP starting here:
http://www.hard-light.net/forums/index.php?topic=90982.msg1804415#msg1804415
=> improve sexp help regarding bitmasks on ship-arrival-info and ship-departure-info

code/parse/parselo.cpp
`matches_version_specific_tag()` now uses the previously-FRED-only `scan_fso_version_string()` function, meaning it now supports version-specific comments with as few numbers as `;;FSO 3;;` to as many numbers as `;;FSO 3.7.3.20151106;;`, instead of you being required to supply exactly 3 numbers.
=> Improve consistency/flexibility of version-specific comments.

code/globalincs/version.cpp, code/globalincs/version.h, code/mod_table/mod_table.cpp, code/network/multi_update.cpp
This allows a modder to specify a minimum FSO version that is needed
for the mod.
=> Add "$Minimum version" to game settings table

code/cmeasure/cmeasure.cpp, code/cmeasure/cmeasure.h
Thanks to Goober5000 for noticing this
=> CMEASURE_DETONATE_DISTANCE should be a float

code/freespace2/freespace.cpp
Horizontal faces on cubemap were oriented incorrectly.
<a href="http://imgur.com/2qUTYFY"><img src="http://i.imgur.com/2qUTYFY.png" title="source: imgur.com" /></a>
=> Fix Mantis 0003014

code/cmdline/cmdline.cpp
Replacement for pull request #402.
Same functionality, but now support folders that differ only in lower-/uppercase.
The implementation is made much more complex by that requirement.
=> Unix modlist

code/gamesnd/gamesnd.cpp
Thanks to Maverick_BB110CB's detective work on this thread:
http://www.hard-light.net/forums/index.php?topic=91030.0
=> retail sounds 36 and 37 should actually be converted to 3D

code/graphics/gropengltnl.cpp, code/math/vecmat.cpp, code/math/vecmat.h
Thanks to MageKing for noticing them
=> Addressing a few small issues with PR 468

configure.ac
Pretty self-explanatory, I have had a local change on one of my machines to enable this, and thought adding it as a toggle and getting it out of my local changes would be helpful.  Will make my life easier anyway.
=> AddressSanitizer toggle flag for configure.ac

code/hud/hudlock.cpp, code/hud/hudlock.h
Eliminates unnecessary globals and conflicts of scope as raised by Goober. Also tries to address the issue that Yarn pointed out in issue https://github.com/scp-fs2open/fs2open.github.com/issues/456.
=> My attempt to fix the HUD lock scoping issues raised by issue #456.

code/cfile/cfile.cpp, code/cmdline/cmdline.cpp, code/freespace2/freespace.cpp, code/model/modelread.cpp, code/network/multi.cpp, code/osapi/dialogs.cpp, code/osapi/dialogs.h, code/parse/sexp.cpp, code/ship/ship.cpp, code/sound/openal.cpp, code/sound/voicerec.cpp
`dialogs.h` undefined MessageBox on Windows because it was causing issues but this broke compilation of FRED. So instead I renamed the function.
=> Fix compilation errors in FRED

code/graphics/gropengl.cpp
force_s3tc_enable needs to be set before SDL_InitSubSystem.
=> Fix s3tc texture loading

code/weapon/weapons.cpp
This should fix the issue reported in http://www.hard-light.net/forums/index.php?topic=91465.0
=> Fixed $Acceleration Time not working right on non-homing secondaries

code/bmpman/bmpman.cpp, code/globalincs/version.cpp, code/globalincs/vmallocator.h
Reports how many bmpman slots are used, with subtotals for each image
type and EFFs broken down by sub-type
=> Add debug console command: bm_used

code/fred2/fredrender.cpp
Sorry about that everybody: http://www.hard-light.net/forums/index.php?topic=90759.0
=> Fixes ships in FRED only rendering wireframe instead of both wireframe and model when selected.

code/menuui/mainhallmenu.cpp, code/menuui/optionsmenumulti.cpp, code/network/multi.cpp, code/network/multi.h, code/network/multi_voice.cpp, code/network/multilag.cpp, code/network/multimsgs.cpp, code/network/multimsgs.h, code/network/multiui.cpp, code/network/multiutil.cpp, code/network/multiutil.h, code/network/psnet2.cpp, code/network/psnet2.h, code/pilotfile/plr.cpp
Remove support for the IPX protocol. The IPX selector button in the multi
options menu is now hidden, and the TCP button is disabled since there is no other option.
=> Remove IPX support.

code/osapi/osregistry.cpp, code/osapi/osregistry.h
=> Fix Windows Registry configuration

code/model/modelread.cpp
Backporting issue #560 to the fs2_open_3_7_4 branch.
=> fix the $dumb_rotate turn rate calculation to align with regular $rotate

code/ship/ship.cpp
Despite what the original report claims, the ship.cpp change described in it actually works.
=> Fix for Mantis 3170

code/ship/ship.cpp
Backport of PR #566 to 3.7.4 branch.
=> [3.7.4] Fix for Mantis 3170

code/cfile/cfile.cpp, code/cfile/cfilearchive.h
Various minor clean ups to cfile.cpp
=> Cfile cleanup

code/cfile/cfile.cpp
=> Fix crash in cfile.cpp

code/model/modelread.cpp
Per issue #573, this restores the original configuration of the $dumb_rotate property, and also adds synonyms to make the turn rate or turn time explicit.  I made it easier with a useful `prop_string` function that allows multiple possible property values.
I still need to run a few tests on some POFs, so don't merge this yet, but I don't expect any problems.
=> use $rotate, $rotate_rate, and $rotate_time, and their $dumb_ equivalents, with proper backwards compatibility

code/model/modelread.cpp
=> [3.7.4] Backport/issue 580

code/controlconfig/controlsconfigcommon.cpp
Found by address sanitiser
Backport 575
=> [3.7.4] Fix new[] vs delete mismatch

code/parse/lua.cpp
Just expose the existing instant flag from the animation handling code
=> Add instant flag to lua triggered anims

code/windows_stub/config.h
=> [3.7.4] Fix compiling debug build on linux with glibc 2.23 (#1)

code/playerman/playercontrol.cpp
I don't remember why I was reading this function, but I noticed that the `can_warp` and `warp_failed` variables didn't actually seem to be serving any purpose, and there was some redundant code in the `PCM_WARPOUT_STAGE*` case they were "used" in.
=> Clean up read_player_controls() somewhat.

code/network/multiui.cpp, code/network/multiui.h, code/network/multiutil.cpp
Update ping color value ranges to be more realistic. Also add orange as a
ping value text color.
=> Fix text color of ping values in server list.

code/ship/ship.cpp
Allows support for as many subsystems as available memory allows by replacing the `Ship_subsystems[]` pointer array with a pointer vector. It still just contains pointers to dynamically-allocated subsystem arrays (allocated in blocks of `NUM_SHIP_SUBSYSTEMS_PER_SET`), so this should behave almost identically to the current code.
Used a test build to verify that a mission that was exceeding the old subsystem limit generated no such errors with these changes.
=> Remove subsystem limit.

code/nebula/neb.cpp
Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/657
=> Fixed nebula missions from breaking scene render targets following the nohtl removal.

code/io/joy-sdl.cpp, code/io/key.cpp, code/io/mouse.cpp, code/osapi/osapi.cpp, code/osapi/osapi.h, code/sound/voicerec.cpp
This is currently only used by the default event handlers but it could also be exposed to the scripting API or an external GUI framework.
This is a resubmit of #164.
=> Add API for registering custom event handler

code/graphics/generic.cpp
Choose that if a system is too slow to compose & render apngs fast
enough, play the anim until the last frame anyway, potentially messing
up time sync between frames, but at least don't have looped anims
stuttering as they skip back to the 1st frame from some non-end frame.
Most modern-ish systems won't see this issue unless there's lots of
apngs playing at the same time...
=> End apngs by frame count as well as time

code/fred2/fred.cpp
Literally a copy-paste of the code added by PR #119 from freespace.cpp to fred.cpp.
=> Make FRED use high-performance GPU by default.

code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/graphics/gropengldraw.cpp, code/model/modelrender.cpp
=> Adds a commandline switch analoguous to framebuffer shockwaves to enable the distortion effect for thrusters

code/graphics/gropenglpostprocessing.cpp
Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/688
=> Make sure we can write to the alpha channel before doing the FXAA luminance prepass

code/sound/fsspeech.cpp, code/sound/speech.cpp
I added some debugging statements to the speech code when I couldn't get my speech to work.  Found out it was a case sensitivity issue I plan to file a ticket for, but having these statements in place might help speed up future debugging.  Need to be sure to update the debug_filter wiki page when merged.
=> Speech Debugging

code/osapi/osapi.cpp, fred2/fredview.cpp, fred2/management.cpp, fred2/management.h
Maybe this will help tracking down that FRED OpenGL issue
=> Clean up FRED init a bit

code/osapi/osregistry.cpp
=> Make config key check case-insensitive

code/controlconfig/controlsconfig.cpp, code/controlconfig/controlsconfig.h, code/controlconfig/controlsconfigcommon.cpp, code/io/joy-sdl.cpp, code/io/joy.h, code/io/keycontrol.cpp, code/menuui/optionsmenu.cpp, code/parse/lua.cpp, code/pilotfile/csg.cpp, code/pilotfile/plr.cpp, code/playerman/managepilot.cpp, freespace2/freespace.cpp
This API allows to handle events from multiple joysticks but currently
only the events from the configured joystick are used.
=> Add improved joystick API

code/menuui/readyroom.cpp, code/parse/lua.cpp
This fixes one of the bugs reported in #732.
=> Fix some font scripting bugs reported by Axem

.travis.yml, coverity/modeling.cpp
Update modeling file to deal with SDL2.0 changes
Should fix #740
=> Fix coverity scan triggered from travis

code/network/multiteamselect.cpp
Someone (and I am assuming this is vintage Volition) forgot that there's a difference between objects and parse objects.
=> Fixes a mismatched flag type error in multiteamselect.

code/cmdline/cmdline.cpp, freespace2/freespace.cpp
-shadow_quality imply -enable_shadows.
=> Fixed actual_main to correctly return 0 on success and made

code/radar/radarsetup.cpp
Fixes a flag mismatch error as explained in #762.
=> SIF_STEALTH and SF2_STEALTH are different things, I'm afraid

code/controlconfig/controlsconfig.cpp
=> Fix logic error in controlsconfig.cpp

code/hud/hudparse.cpp
Previously the code simply skipped the invalid tokens and silently
ignored them. This is frustrating for modders and also let #758 slip
into the code base which would not have happened otherwise.
=> Detect HUD gauges parse error and print a warning

code/graphics/gropenglstate.cpp
This fixes a crash reported by @Karajorma.
=> Fix Assert caused by invalid comparision

cmake/platform-win32.cmake, freespace2/freespace.cpp
Now this also works when there are more than 4GB or RAM in the system.
=> Fix Windows memory statistics

code/globalincs/flagset.h, code/iff_defs/iff_defs.cpp, code/mission/missionparse.cpp, code/parse/parselo.h
Fixes an issue in flagsets where the sanity check for flagset::set was inverted.
=> Bugfix for flagsets

code/graphics/gropenglpostprocessing.cpp
Fixes the overly bright glare from lightshafts after the PBR and HDR commit. Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/649
=> Reorder lightshafts in the post process pipeline. 

code/playerman/playercontrol.cpp
Major credit to m|m for finding the bug and spotting the errant line that reset the chase angles.
=> Fixes an issue where the regular padlock view was disabled.

code/globalincs/flagset.h, code/ship/awacs.cpp, test/src/globalincs/test_flagset.cpp, test/src/source_groups.cmake
This uses the , operator for combining the flag values.
=> Add support for indexing flagset with multiple flags

code/object/objcollide.cpp, code/object/objectsnd.cpp, code/object/waypoint.cpp, code/osapi/osregistry.cpp, code/osapi/outwnd.cpp, code/parse/parselo.cpp, code/parse/parselo.h, code/parse/scripting.cpp, code/parse/sexp.cpp, test/src/parse/test_parselo.cpp, test/src/source_groups.cmake
Also added a bunch of tests for function where I significantly changed the code.
=> And another batch of warning fixes

code/headtracking/freetrack.cpp, code/playerman/playercontrol.cpp
Reverts scp-fs2open/fs2open.github.com#839
=> Revert "Fix FreeTrack and headtracking"

cmake/toolchain-gcc.cmake
@chief1983 mentioned that the `-fsanitize` flag is not set correctly. This should fix that.
=> Fix -fsanitize flag setting

code/cmdline/cmdline.cpp
=> Remove leftovers of -debug_window cmdline arg

code/ship/ship.cpp
Restore primitive sensors to Ship_flag_names[]
=> Fix Coverity 1361854

code/parse/scripting.cpp
It's a small miracle that it worked but these changes should fix the
issue.
=> Fix stack overflow reported by ASan

code/ai/ai_profiles.h, fred2/AltShipClassDlg.cpp, fred2/asteroideditordlg.cpp, fred2/briefingeditordlg.cpp, fred2/campaigneditordlg.cpp, fred2/campaigntreeview.cpp, fred2/dumpstats.cpp, fred2/eventeditor.cpp, fred2/fred.cpp, fred2/fred.h, fred2/freddoc.cpp, fred2/initialships.cpp, fred2/initialstatus.cpp, fred2/management.cpp, fred2/management.h, fred2/missiongoalsdlg.cpp, fred2/missionnotesdlg.cpp, fred2/missionsave.cpp, fred2/modifyvariabledlg.cpp, fred2/orienteditor.cpp, fred2/playerstarteditor.cpp, fred2/sexp_tree.cpp, fred2/shipeditordlg.cpp, fred2/shipgoalsdlg.cpp, fred2/voiceactingmanager.cpp, fred2/wing_editor.cpp
This should fix all remaining 64-bit warnings with Visual Studio.
=> Fix 64-bit warnings in FRED2

appveyor.yml, ci/appveyor/before_build.ps1, ci/appveyor/build.ps1, code/graphics/2d.h, code/graphics/gropenglstate.cpp, code/graphics/gropengltnl.cpp, code/graphics/gropengltnl.h, code/graphics/grstub.cpp, code/model/modelinterp.cpp, code/model/modelrender.cpp, code/render/batching.cpp, code/render/batching.h
Nightly builds are still compiled as 32-bit build though.
=> Use 64 bit build for appveyor

code/cutscene/mveplayer.cpp, code/cutscene/oggplayer.cpp, code/graphics/gropengl.cpp, code/graphics/gropengl.h, code/graphics/gropengldraw.cpp, code/graphics/gropengllight.cpp, code/graphics/gropengllight.h, code/graphics/gropenglpostprocessing.cpp, code/graphics/gropenglshader.cpp, code/graphics/gropenglstate.cpp, code/graphics/gropengltexture.cpp, code/graphics/gropengltnl.cpp, code/graphics/gropengltnl.h, code/lab/lab.cpp, code/lighting/lighting.cpp, code/model/modelread.cpp, code/model/modelrender.cpp, code/object/object.cpp, code/ship/ship.cpp, code/weapon/beam.cpp
Since OpenGL Core is required now that function would always return true
so it can be removed.
=> Remove is_minimum_GLSL_version()

code/graphics/gropenglshader.cpp, code/graphics/gropenglshader.h
Removes fixed arrays and replaces them with vectors.
=> Improve shader value handling

code/cutscene/mveplayer.cpp, code/cutscene/oggplayer.cpp, code/graphics/grinternal.h, code/graphics/gropengl.cpp, code/graphics/gropengldraw.cpp, code/graphics/gropengllight.cpp, code/graphics/gropenglpostprocessing.cpp, code/graphics/gropenglstate.cpp, code/graphics/gropenglstate.h, code/graphics/gropengltexture.cpp, code/graphics/gropengltnl.cpp, code/graphics/material.cpp, code/graphics/material.h, code/graphics/paths/NVGRenderer.cpp, code/graphics/shadows.cpp, code/hud/hudtarget.cpp, code/model/modelrender.cpp, code/object/objectsort.cpp, code/render/3ddraw.cpp, code/starfield/nebula.cpp
Did some cleaning. Removed a bunch of fixed function state tracking code that was left behind following the OpenGL Core migration.
=> OpenGL state tracking cleanup

code/def_files/bloom-comp-f.sdr, code/def_files/post-f.sdr, code/graphics/gropenglpostprocessing.cpp, code/graphics/gropenglshader.cpp
Removed unneeded bloom compositing code in the main post processing shader. Cleaned up the bloom compositing shader. Fixes https://github.com/scp-fs2open/fs2open.github.com/issues/889
=> Fixed bloom intensity weirdness when set it's set to 0.

code/parse/parselo.cpp
This should fix #933.
Thanks to @rtoijala for noticing this issue from the previous PR.
=> Make sure that Mission_text is always initialized

code/graphics/2d.cpp, code/graphics/2d.h, code/graphics/opengl/gropenglshader.cpp, code/graphics/opengl/gropengltexture.cpp, code/graphics/opengl/gropengltnl.cpp, code/graphics/paths/NVGRenderer.cpp, code/graphics/shadows.cpp, code/model/modelrender.cpp, code/object/objectsort.cpp, code/render/batching.cpp, freespace2/freespace.cpp
I improved the debug scope macro so it doesn't need a variable name anymore and also added a few new debug groups.
=> Some graphics debug group improvments

fred2/shipgoalsdlg.cpp
Fix two bugs uncovered during testing of PRs #931 and #939.
=> Ai chase ship class followup

freespace2/freespace.cpp
This solves one issues reported by @chief1983 in #941.
=> Don't initialize graphics operations in standalone mode

code/ai/ai_profiles.cpp, code/asteroid/asteroid.cpp, code/cfile/cfile.cpp, code/controlconfig/controlsconfig.cpp, code/controlconfig/controlsconfigcommon.cpp, code/gamehelp/contexthelp.cpp, code/gamesnd/gamesnd.cpp, code/hud/hud.cpp, code/hud/hudparse.cpp, code/hud/hudreticle.cpp, code/hud/hudshield.cpp, code/hud/hudtarget.cpp, code/lab/wmcgui.cpp, code/lighting/lighting.cpp, code/menuui/mainhallmenu.cpp, code/mission/missionparse.cpp, code/model/modelinterp.cpp, code/model/modelrender.cpp, code/object/objcollide.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/starfield/starfield.cpp, code/weapon/weapons.cpp, fred2/bgbitmapdlg.cpp, fred2/dumpstats.cpp, fred2/sexp_tree.cpp
None of these should be functional changes, but give them a look over in case I missed something.
=> Some miscelleaneous cleanup commits.

code/object/objectsort.cpp
Should fix https://github.com/scp-fs2open/fs2open.github.com/issues/945
=> Make sure we tell the batcher to render in FRED.

freespace2/CMakeLists.txt, scripts/performance_check.sh, scripts/performance_graph.py
This script allows to compare the performance of a branch to master by
running both versions and generating a graph of frametimes for both
versions.
=> Add script for doing automated performance test

code/graphics/opengl/gropengldraw.cpp, code/graphics/opengl/gropenglpostprocessing.cpp, freespace2/freespace.cpp
Post processing takes a lot of GPU time so I added some more tracing scopes to determine which part actually takes the most time.
=> Add more tracing scopes to post processing code

cmake/finder/FindSpeech.cmake, code/network/multilag.cpp, code/network/multilag.h, code/windows_stub/config.h
This does not mean that MinGW can compile FSO yet, these are just a few
fixes that are needed.
=> Fix a few issues with MinGW

code/parse/lua.cpp
This was requested by @AxemP.
The implementation is a bit more complicated than simply retrieving the value since that is only updated when the weapon is fired. Instead, the function calculates what the current value should be based on the code from the function that updates the value when the weapon is fired.
Setting the value is disabled since the extra processing code could alter the calculation a script does so that after setting the value, reading it again would return a different value.
=> Add lua option for accessing the FOF cooldown

ci/travis/before_script.sh, ci/travis/check_release.sh, ci/travis/release.sh
=> Fix nightly AppImages

cmake/util.cmake
The previous version simply ignored that configuration but these changes
should fix that.
=> Fix boost for FastDebug

code/graphics/opengl/gropenglshader.cpp
This was reported by Coverity.
=> Fix parameter oder for shader hashes

cmake/cross_compile/mingw64.cmake, cmake/platform-win32.cmake, code/def_files/def_files-win32.cpp, code/headtracking/freetrack.cpp, code/osapi/osregistry.cpp, code/sound/ogg/ogg.cpp, code/sound/voicerec.h, code/tracing/tracing.cpp, freespace2/freespace.cpp
This makes it possible to compile windows builds on Linux.
=> Cross compilation fixes

code/model/model.h, code/model/modelinterp.cpp, code/model/modeloctant.cpp, code/model/modelread.cpp
This was probably missed in removal of -nohtl
Also "fixes" Coverity 1363380
=> Cleanup some non-HTL code

code/sound/ffmpeg/WaveFile.cpp
=> Fix Coverity 1363662

code/parse/sexp.cpp
This is definitely a bad thing, as a few flags were never getting set correctly. Thanks to @asarium for the detective work.
=> Fixes a few instances of using the wrong overload for sexp_deal_with_ship_flag

code/sound/ffmpeg/WaveFile.cpp
This fixes #1029. Special thanks to @AxemP for providing a test mod for
reproducing the bug.
There are also some minor formatting changes which I could remove again if required.
=> Remove extension from a filename passed to WaveFile::Open

code/scripting/lua.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Requested by Axem.
Allows a weapon to be paged in via script so if a weapon has special qualities through scripting, say, upgrades given a player state, the weapons can be paged in and rendered correctly.
=> Add isWeaponUsed scripting function

code/scripting/lua.cpp
isWeaponUsed description was wrong.
=> Fix isWeaponUsed Description

code/bmpman/bmpman.cpp, code/pngutils/pngutils.cpp
=> Fix mprintf format strings in apng code

code/ai/aicode.cpp, code/hud/hudets.cpp, code/hud/hudshield.cpp, code/object/object.cpp, code/object/objectshield.cpp, code/object/objectshield.h, code/parse/sexp.cpp, code/ship/shield.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp
Fix unlimited transfer of energy to shields (energy lost)
Fix thresholds in ai balance shields, rearm timer & call4help
Fix scaling in shield pain flash
Fix variable number of shield segments in shield pain flash
Lastly includes formatting tidy-up in shield pain flash
=> Fix issues with $Max Shield Recharge

code/cfile/cfile.cpp
Adds .tbl, .tbm, .xml and .csv to the list of supported /config file types.
=> More file types for data/config

code/weapon/weapons.cpp
Move check for -1 to before we use weapon_index as an array index :)
Also fixes coverity 1365315; which seems like a redundant issue...
=> Fix Coverity 1365316

cmake/toolchain-gcc.cmake
There are a few issues I found with this option which should probably be
fixed.
=> Add option for enabling -fsanitize=undefined

fred2/management.cpp
=> Initialize ffmpeg when starting FRED

code/ship/ship.cpp
This fixes Mantis 3182.
http://scp.indiegames.us/mantis/view.php?id=3182
=> Don't do autorepair if we're already dead

code/scripting/api/libs/testing.cpp, code/scripting/api/libs/testing.h
Also fixed an unresolved external error.
=> Fix definition of scripting testing library

code/graphics/2d.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h, freespace2/freespace.cpp
This changes some functionality but it shouldn't cause too many issues
since the previous functionality was kind of a hack anyway.
This also adds a simulation conditional hook that has only been
available through global hooks before.
=> Remove global hook system and emulate it with conditional hooks

code/math/vecmat.cpp
`vm_vector_2_matrix` was improperly guarded against bad parameters. In the
case I encountered the `uvec` was the negative of `fvec` which produced a
null vector when the cross product of the two vector was constructed.
These changes should fix that bug by ignoring the `uvec` parameter. Since
`vm_vector_2_matrix` and `vm_vector_2_matrix_norm` are basically the same, I
converted the former into an alias of the latter and only fixed that
code.
=> Fix null vector normalization in ship select screen

code/math/vecmat.cpp, code/math/vecmat.h
*Enforce if-else block style within vecmat.cpp.
Related to PR #1158
=> Doxy vm_vector_2_matrix functions.

code/math/vecmat.cpp
This probably caused a lot of issues throughout the code. I fixed the
autoaim issue that happened in the capship command mission by JSRNerdo.
=> Use the correct pointer in vm_vector_2_matrix

code/nebula/neb.cpp, code/particle/particle.cpp, code/ship/shield.cpp, code/starfield/starfield.cpp, code/tracing/categories.cpp, code/tracing/categories.h, code/weapon/beam.cpp, code/weapon/trails.cpp
Several of the substeps of render_frame have not been instrumented yet, this PR changes that.
=> Adds more trace scopes

code/osapi/osapi.cpp
Now it will also check if the old config location exists and if it
doesn't then the new config mode will be used by default. This should
fix #858.
This solution doesn't work too well on windows since the registry system isn't initialized yet when `os_is_legacy_mode` is first called so I just assume that the old config exists. Most Windows users use a launcher which should handle that transition automatically so this shouldn't be a huge issue.
=> Improve logic for determining legacy mode

test/src/source_groups.cmake
For some reason these weren't included in the PR that was supposed to
contain them.
=> Actually add CFile to the unit test project

code/gamesequence/gamesequence.cpp, code/gamesequence/gamesequence.h, code/scripting/lua/LuaFunction.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h
This fixes #1241.
I also included some cleanup here since I noticed some things that were not used anymore.
=> Copy all relevant values in the LuaFunction copy-constructor

Readme.md
This is a quick and simple PR to add a note at the beginning of the readme about submodule updates, and fixes a minor typo.
=> minor readme updates

lib/FFmpeg.cmake
2.7 is the last version we can support with our current code so we
should check for that.
=> Add a sensible version constraint for FFmpeg

freespace2/resources.cmake, freespace2/resources/mac/Info.plist.in
=> Use the correct variables in MacOSX Info.plist

code/parse/sexp.h
This should clear up some confusion about what the functions do since
their behavior is not obvious from looking at the code.
=> Add documentation for CAR and CDR

code/graphics/paths/nanovg/CHANGES.txt, code/graphics/paths/nanovg/nanovg.c, code/graphics/paths/nanovg/stb_image.h
=> Fix or suppress warnings in stb_image

code/lab/lab.cpp, code/lab/wmcgui.cpp, code/lab/wmcgui.h, code/ship/ship.h, code/weapon/weapon.h
During the bitset flags conversion, the flag viewers in the F3 lab were disabled. This restores their functionality.
=> Restore the flag viewers

code/graphics/opengl/gropengl.cpp
This should make it clearer what went wrong.
=> Extend display device initialization error

code/osapi/dialogs.cpp
=> Readd warning dialog counting

code/osapi/osapi.cpp
=> Remove abort call from debug_int3

qtfred/source_groups.cmake, qtfred/src/ui/BriefingEditorDialog.cpp, qtfred/src/ui/BriefingEditorDialog.h, qtfred/ui/BriefingEditorDialog.ui
This adds a UI for the Briefing Editor.
=> Add Briefing Editor Dialog

code/weapon/shockwave.cpp
If framebuffer shockwaves were enabled and a 3D shockwave was created, FSO would use a hardcoded reference to the second slot of the `Shockwave_info` vector to generate the framebuffer shockwave for it. This only makes sense if and only if:
- the 3D shockwave command-line flag is also enabled
- the default 3D shockwave and default 2D shockwave are both present and loaded
- its the first mission of the session (because after that any shockwave not in the 0th index got unloaded)
I've changed the code so that which index the default 2D shockwave got loaded into gets tracked and used instead of a hardcoded index... and if both default shockwaves are loaded, the first two `Shockwave_info` indices are both kept between missions instead of just the first. This should allow framebuffer shockwaves …
=> Fix combining 3D shockwaves with framebuffer shockwaves.

fred2/sexp_tree.cpp
This fixes the handling of default operators in the case of modify-variable, where the behavior had diverged slightly from retail as described in #1331.  (See [the original code](https://pastebin.com/41sKyBWt) which this new PR more closely resembles.)
This PR has two main effects:
1) simplify the checking for sexps that use variable names: as @asarium pointed out, the `OPF_VARIABLE_NAME` is sufficient and there is no need to check sexp identifiers and argument numbers
2) properly check the type of the second argument of `modify-variable`, according to the type of the first argument (which is the actual variable name)
=> Fix handling of arguments for sexps that use variables

code/weapon/shockwave.cpp
=> Fix "Error: Can't open model file <shockwave.pof>" on second mission load

code/parse/sexp.cpp
This is a follow-up to issue #1256.  It skips the positive/negative number reconciliation entirely if there is no parent node for the sexp.  It also cleans up the `find_argnum` function to work more intuitively and adds sanity checks to match `find_parent_operator`.
=> Better handling of positive/negative discrepancy as well as finding sexp node arguments

code/globalincs/pstypes.h, qtfred/source_groups.cmake, qtfred/src/mission/EditorViewport.cpp, qtfred/src/mission/dialogs/ObjectOrientEditorDialogModel.cpp, qtfred/src/mission/dialogs/ObjectOrientEditorDialogModel.h, qtfred/src/mission/object.cpp, qtfred/src/mission/object.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/ObjectOrientEditorDialog.cpp, qtfred/src/ui/dialogs/ObjectOrientEditorDialog.h, qtfred/ui/FredView.ui, qtfred/ui/ObjectOrientationDialog.ui
This adds another small editor to qtFRED. I also found a minor bug in the old FRED code which caused a negative indexation of an array but apparently that isn't a problem in the usual use cases. I fixed that issue for qtFRED.
=> Add object orientation editor

code/mission/missionparse.h, qtfred/source_groups.cmake, qtfred/src/mission/Editor.h, qtfred/src/mission/dialogs/CustomWingNamesDialogModel.cpp, qtfred/src/mission/dialogs/CustomWingNamesDialogModel.h, qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp, qtfred/src/mission/dialogs/MissionSpecDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/CustomWingNamesDialog.cpp, qtfred/src/ui/dialogs/CustomWingNamesDialog.h, qtfred/src/ui/dialogs/MissionSpecDialog.cpp, qtfred/src/ui/dialogs/MissionSpecDialog.h, qtfred/ui/CustomWingNamesDialog.ui, qtfred/ui/FredView.ui, qtfred/ui/MissionSpecDialog.ui
This adds functioning dialogs for:
* Mission Specs Editor
* Custom Wing Names Editor
The Sound Environment Editor is being delayed as the Sound Environment system does not actually work.
Ready to merge.
=> Add Mission Specs Editor

qtfred/source_groups.cmake, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/EditorViewport.cpp, qtfred/src/mission/EditorViewport.h, qtfred/src/mission/EditorWing.cpp, qtfred/src/mission/IDialogProvider.h, qtfred/src/mission/dialogs/FormWingDialogModel.cpp, qtfred/src/mission/dialogs/FormWingDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/FormWingDialog.cpp, qtfred/src/ui/dialogs/FormWingDialog.h, qtfred/ui/FormWingDialog.ui
This adds the code for making the form and disband wing actions work from the GUI. This is the first instance where the mission code uses the dialog interface to open a custom dialog. The view/model separation works nicely here since the mission code only has to interact with the model without having any direct interaction with the GUI code.
=> Add form and disband wing actions

ci/appveyor/build.ps1, ci/travis/release.sh
This package will include the externals which are not present in the
default GitHub export.
=> Build a compressed package of the source as part of a release

qtfred/source_groups.cmake, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/EditorViewport.h, qtfred/src/mission/dialogs/SelectionDialogModel.cpp, qtfred/src/mission/dialogs/SelectionDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/SelectionDialog.cpp, qtfred/src/ui/dialogs/SelectionDialog.h, qtfred/ui/FredView.ui, qtfred/ui/SelectionDialog.ui
This adds the ship selection dialog and connects it to the correct action in the main view.
=> Add ship selection dialog

.travis.yml
I have no idea why this doesn't work anymore. I didn't even touch that
line when I added the test build stuff...
=> Fix Travis CI nightly deploy

cmake/version.cmake
I'll write a short wiki article about how to do version bumps in the future since there was some confusion about how to do that.
EDIT: Nevermind, I already did that: https://github.com/scp-fs2open/fs2open.github.com/wiki/CMake#setting-the-project-version
=> Bump development version after final release

ci/travis/before_script.sh, ci/travis/release.sh
The previous version included the make files which increased the size of
the package.
=> Build Unix source package before configuring

qtfred/source_groups.cmake, qtfred/src/FredApplication.h, qtfred/src/main.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/mission/Editor.h, qtfred/src/mission/EditorViewport.cpp, qtfred/src/mission/EditorViewport.h, qtfred/src/mission/FredRenderer.cpp, qtfred/src/mission/management.cpp, qtfred/src/mission/management.h, qtfred/src/mission/object.cpp, qtfred/src/mission/object.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/AboutDialog.cpp, qtfred/src/ui/dialogs/AboutDialog.h, qtfred/src/ui/dialogs/WaypointEditorDialog.cpp, qtfred/src/ui/widgets/renderwidget.cpp, qtfred/ui/AboutDialog.ui, qtfred/ui/FredView.ui, qtfred/ui/WaypointEditorDialog.ui
This covers almost all menu actions that don't require a dialog.
=> Add most of the remaining menu action implementations

code/localization/localize.cpp
Since 4500 strings are not enough for some mods there was a request for
removing that limit. I chose to use an unordered map for storing the
entries since the indices are not guaranteed to be sequential.
This fixes [Mantis 3199](http://scp.indiegames.us/mantis/view.php?id=3199).
=> Remove limit for tstring table entries

code/parse/sexp.cpp, code/parse/sexp.h, code/sound/audiostr.cpp, code/sound/audiostr.h
What it says on the tin.
Any reviewers should pay particular attention to `sexp_or`, `sexp_and`, and `sexp_and_in_sequence`.  I double-checked my changes carefully, but extra eyes are always helpful.
=> change is_sexp_true return type from int to bool

code/osapi/DebugWindow.cpp, code/osapi/DebugWindow.h
This adds support for changing the view offset via the arrow and Page Up/Down keys. It also allows to scroll to the begin with "Home" and to the end with "End".
=> Add scrolling support to new debug window

code/weapon/beam.cpp
There were some issues with positioning and size of directional glows as well as jitter during the startup/cooldown sequence.
=> Fix directional glow issues

code/cfile/cfile.cpp, code/cfile/cfile.h, fred2/mainfrm.cpp
This will allow to put the FRED docs somewhere else instead of into the
root directory of a TC.
=> Search for fred docs using cfile

code/menuui/snazzyui.cpp, code/missionui/missionshipchoice.cpp
I added these while investigating another issue which was fixed by the NanoVG rendering changes but these may still be useful.
=> Add a few graphics debug scropes to the ship selection

code/graphics/material.cpp, code/parse/parselo.cpp, fred2/fredrender.cpp
This fixes the crashing issue and the tooltip issue reported by Trivial Psychic on the forums: https://www.hard-light.net/forums/index.php?topic=94271.0
=> Fix some FRED issues

code/libs/ffmpeg/FFmpeg.cpp
I had to debug some ffmpeg library issues and added these additional log
statements. They may be useful in the future.
=> Add additional logging output for FFmpeg library version

code/parse/sexp/LuaSEXP.cpp
This was requested by @AxemP on the forums.
=> Pass ship variables as actual handles to scripts

code/parse/sexp/LuaSEXP.cpp, code/scripting/api/libs/mission.cpp, code/scripting/lua/LuaValue.cpp
These changes make sure that this situation is detected properly and an
informative error message is shown.
=> Fix game crash when a lua SEXP is not initialized properly

code/parse/sexp/LuaSEXP.cpp
This was requested by Axem on Discord.
=> Add support for passing various parameter types to Lua SEXPs

code/gamesnd/eventmusic.cpp, code/gamesnd/eventmusic.h, code/playerman/managepilot.cpp, code/sound/sound.cpp, code/sound/sound.h
previously newly created pilots inherited the volumes from the last
pilot
=> set default volumes on pilot create

code/globalincs/systemvars.h, code/graphics/light.cpp, code/graphics/opengl/gropengldeferred.cpp, code/graphics/shadows.cpp, code/lighting/lighting.cpp, code/lighting/lighting.h, code/model/modelrender.cpp, code/model/modelrender.h
=> Make sure directional lights are always rendered

code/weapon/beam.cpp
=> Consistent beam damage per frame regardless of time acceleration

code/graphics/2d.h, code/graphics/line_draw_list.cpp, code/graphics/line_draw_list.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/paths/NanoVGRenderer.cpp, code/hud/hudbrackets.cpp, code/hud/hudbrackets.h, code/hud/hudtargetbox.cpp, code/missionui/missionshipchoice.cpp, code/missionui/missionweaponchoice.cpp, code/scripting/api/objs/graphics.cpp, code/source_groups.cmake, code/tracing/categories.cpp, code/tracing/categories.h
The previous version used NanoVG which caused quite a serious FPS drop.
This adds a buffer batching class which groups line drawing operations
together and submits them to the GPU with a single draw call.
=> Add a mechanism for batching line draw calls

code/def_files/data/effects/batched-f.sdr, code/def_files/data/effects/decal-f.sdr, code/def_files/data/effects/default-material-f.sdr, code/def_files/data/effects/effect-particle-f.sdr, code/def_files/data/effects/gamma.sdr, code/def_files/data/effects/main-f.sdr, code/def_files/data/effects/passthrough-f.sdr, code/def_files/data/effects/shield-impact-f.sdr, code/def_files/data/effects/tonemapping-f.sdr, code/source_groups.cmake
This moves the constant definition and functions for converting from and
to linear color space into a single file that is included in all other
files.
=> Move gamma correction into common header

code/model/modelrender.cpp
The rendering material used by the model render list was reused by
multiple draw call submissions so a non-transparent mesh would reset the
fog value set before which would break meshes submitted after that.
There are still some issues with how the fog is rendered which causes
differences between how opaque and transparent meshes are drawn but I
will fix that in another pull request.
This fixes #1645.
=> Avoid reusing model material instance when setting fog

code/model/modelanim.cpp
Replace this assert with a proper exit path + debug log print.
This fixes #1623
=> Fix for 1623

qtfred/source_groups.cmake, qtfred/src/main.cpp, qtfred/src/mission/Editor.cpp, qtfred/src/ui/util/menu.cpp, qtfred/src/ui/util/menu.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
This adds displaying the correct context menu for the qtFRED SEXP tree
widget. The actions are not implemented yet.
=> Add SEXP tree context menu building

qtfred/source_groups.cmake, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/BackgroundEditorDialog.cpp, qtfred/src/ui/dialogs/BackgroundEditorDialog.h, qtfred/src/ui/dialogs/ShieldSystemDialog.cpp, qtfred/src/ui/dialogs/ShieldSystemDialog.h, qtfred/src/ui/dialogs/VoiceActingManager.cpp, qtfred/src/ui/dialogs/VoiceActingManager.h, qtfred/ui/BackgroundEditor.ui, qtfred/ui/FredView.ui, qtfred/ui/ShieldSystemDialog.ui, qtfred/ui/VoiceActingManager.ui
Add .ui files and stub dialog .h/.cpp files for Background Editor, Shield System Dialog, and Voice Acting Manager to qtFRED.
=> Add GUIs for background, shield system, and voice acting editors to qtFRED

qtfred/source_groups.cmake, qtfred/src/mission/dialogs/FictionViewerDialogModel.cpp, qtfred/src/mission/dialogs/FictionViewerDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/FictionViewerDialog.cpp, qtfred/src/ui/dialogs/FictionViewerDialog.h, qtfred/ui/FictionViewerDialog.ui, qtfred/ui/FredView.ui
EDIT: This adds the fiction viewer dialog to qtFRED.
=> Add fiction viewer dialog to qtFRED

qtfred/README.md, qtfred/src/mission/dialogs/AbstractDialogModel.h
=> Update qtFRED readme and add some documentation

code/osapi/outwnd.cpp
The crash was caused by a static initialization order problem where the
static initializer of the FRED app was called before the initializer of
the outwnd filter vector.
This fixes that by initializing the vector as soon as necessary through
the use of a function with a static variable.
=> Fix crash on FRED startup in debug mode

cmake/platformChecks.cmake, cmake/platformChecks.h.in, cmake/toolchain-gcc.cmake, code/cfile/cfile.cpp, code/default_files.cmake, code/fs2netd/tcp_socket.cpp, code/globalincs/toolchain/mingw.h, code/globalincs/toolchain/msvc.h, code/headtracking/freetrack.cpp, code/inetfile/cftp.cpp, code/network/multi_sexp.h, code/network/multilag.cpp, code/network/psnet2.cpp, code/network/stand_gui.cpp, code/osapi/osregistry.cpp, code/osapi/outwnd.cpp, code/source_groups.cmake, code/utils/strings.h, code/utils/unicode.h, code/windows_stub/config.h, freespace2/freespace.cpp
This fixes various issues I found while trying to compile FSO in a cross
compilation setup using MinGW. This is a prerequisite for merging Tea-CI
support.
=> Fix various issues detected by MinGW

code/parse/parselo.cpp, code/parse/parselo.h, qtfred/source_groups.cmake, qtfred/src/mission/missionsave.cpp, qtfred/src/mission/missionsave.h, qtfred/src/mission/util.cpp, qtfred/src/mission/util.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h
This is pretty much an exact copy of the mission save code of FRED2. I
removed the campaign save code for now since it requires some
interactions with the campaign editor which does not exist yet.
This fixes #1697.
=> Port mission save code to qtFRED

code/parse/sexp.cpp
I also added a new `Error` in `sexp_transfer_cargo` to make it consistent with `sexp_exchange_cargo`.
=> Converted all Int3() calls in sexp.cpp into Warnings, Errors and Asserts

qtfred/src/main.cpp
=> Enable log output for qtFRED

code/graphics/opengl/gropenglshader.cpp
This automatically removes old shader cache files from the mod directory
when FSO is started. Those old files are likely to not be used anymore
so this will reduce the amount of disk space FSO uses for the shader
cache.
=> Purge old shader cache files from file system

code/ship/ship.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
This adds a probability based weapon failure system. By default, it simply cancels firing the weapon, otherwise it can substitute a weapon specified by the modder.
=> Add $Failure Rate:

code/ai/aicode.cpp
Change this warning to a log print. This is only an issue when it's an issue, and most of the time it's not
=> Remove "not enough points in path" warning

lib/prebuilt.cmake
This has been a problem for nighty and release builds which should be
fixed by this.
=> Retry prebuilt library download if it fails

code/ship/ship.cpp
The Assert did no cover all possible input values which caused some
isues for me. This fixes that.
=> Fix assert in ship_cleanup

code/ai/ai.h, code/ai/aibig.cpp, code/ai/aicode.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/shiphit.cpp, code/weapon/swarm.cpp, code/weapon/swarm.h, code/weapon/weapons.cpp
Continuing some side work wherein routines in aicode.cpp with unused parameters have those parameter removed.  Where applicable, the 'static' keyword has been added to those routines and the 'const' keyword may have been added in some instances.
=> Unused parameter removal from aicode.cpp module

code/mission/missionparse.cpp, code/parse/parselo.cpp, code/parse/parselo.h, code/scripting/ade_api.h, code/scripting/api/libs/cfile.cpp, code/scripting/api/libs/parse.cpp, code/scripting/api/libs/parse.h, code/scripting/lua.cpp, code/source_groups.cmake, fred2/management.cpp, fred2/missionsave.cpp, fred2/missionsave.h, qtfred/src/mission/Editor.cpp, qtfred/src/mission/management.cpp, qtfred/src/mission/missionsave.cpp, qtfred/src/mission/missionsave.h
This allows scripts to use the same parsing functions which are also
used by the engine for parsing tables.
=> Add scripting API for accessing parsing system

code/weapon/weapons.cpp
New to using git especially collaboratively so don't hesitate to tell me if I'm doing this wrong.
=> Corrected faulty lifetime randomization for weapons in weapons.cpp

code/globalincs/pstypes.h, qtfred/source_groups.cmake, qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp, qtfred/src/mission/dialogs/AsteroidEditorDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp, qtfred/src/ui/dialogs/AsteroidEditorDialog.h, qtfred/ui/AsteroidEditorDialog.ui, qtfred/ui/FredView.ui
As it says on the tin; a mostly-direct port of the fred code to qtfred
=> qtfred asteroid editor

code/math/vecmat.cpp, code/render/3ddraw.cpp
This also adds a check to that function to swap the values around should that not be the case
=> vm_vec_random_cone needs to be called with the smaller angle first.

code/hud/hudparse.cpp, code/hud/hudreticle.cpp, code/hud/hudreticle.h, code/ship/ship.cpp, code/ship/ship.h
Optionally play a sound when autoaim becomes active, and another sound
when autoaim becomes inactive
Credit to zookeeper - I'm just pushing this into master!
I should also note that this is a feature that FotG wants
=> add feature: change reticle when autoaim is active

code/def_files/data/effects/main-f.sdr
So we need to convert everything into it when we do the thing.
Thanks to frikgfeek for pointing me in the right direction for this fix
=> The team color process is only valid for srgb color space

code/cutscene/ffmpeg/FFMPEGDecoder.cpp
This changes the FFmpeg code to not use av_seek_frame anymore if looping
is not required. This fixes an issue when playing MVE movies since that
format does not support seeking.
This fixes #1828.
=> Disable movie looping for MVE cutscenes

code/parse/sexp.cpp
The special value DIRECTIVE_WING_ZERO (defined to be -999) is used to
signify to the directives system that an is-destroyed SEXP was found
which specified an empty wing. However, if a second is-destroyed-delay
SEXP is present in the same directive then the count of the parameters
is added to -999 which makes means that the directives system then
displays it on the HUD as a negative number.
This fixes that by resetting the counter to 0 if a second SEXP
encounters the special value which fixes the issue in the supplied test
mission. There are probably other edge cases when using multiple
is-destroyed SEXPs in a directive so I added a warning to the SEXP help
which lets the mission designer know that it is preferable to specify
multiple parameters instead of using multiple is-destroyed …
=> Handle DIRECTIVE_WING_ZERO in is-destroyed SEXPs correctly

code/particle/particle.cpp, code/particle/particle.h, code/scripting/api/objs/particle.cpp
This introduces support for keeping particles around forever and letting
them be controlled by a Lua script.
=> Add support for looping particles

ci/travis/release.sh
I think I used that for debugging some things but now it's causing
issues.
=> Remove release build uploading to transfer.sh

code/scpui/rocket_ui.cpp
Since libRocket requires unicode mode this doesn't change anything but
it fixes an error when a mod uses TrueType fonts without unicode mode.
=> Disable libRocket unless unicode mode is active

code/mission/missionparse.cpp
In FRED, if all docked ships had their arrival cue set to false, none of them would be loaded
in the mission because there was no dock leader to bring in the entire group.  This PR fixes that
by choosing an arbitrary ship (the biggest ship according to ship_class_compare) to be the
dock leader.  This consequently fixes issue #1877 because the wing is able to find its ship.
=> always choose a dock leader in FRED

code/graphics/opengl/gropenglpostprocessing.cpp, code/graphics/opengl/gropengltnl.cpp
This appears to be a leftover from the development of the shadow
rendering code. The shadow FBO was allocated twice but only one was
used. This removed the unused code and also ports the improved error
handling of that code over to the actual shadow FBO creation code.
=> Remove duplicate shadow FBO creation

code/menuui/barracks.cpp, code/osapi/dialogs.cpp, code/playerman/managepilot.cpp, code/scpui/RocketFileInterface.cpp, code/scpui/RocketFileInterface.h, code/scpui/RocketSystemInterface.cpp, code/scpui/RocketSystemInterface.h, code/scripting/api/libs/base.cpp, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/player.cpp, code/scripting/api/objs/player.h, code/scripting/api/objs/shipclass.cpp, freespace2/freespace.cpp
This mostly adds the scripting features required for accessing the
various internal variables required for the barracks screen.
This depends on the changes from #1817 since that allows using FSO handle types with hook variables.
=> Add scripting features for barracks libRocket UI

ci/travis/release.sh
There are still some unresolved issues and the file size is pretty large
due to some issues with how the AppImage is built.
=> Disable Linux qtFRED building again

ci/travis/before_script.sh, ci/travis/release.sh
I removed too much code when disabling qtFRED deployment...
=> Fix linux release building

code/parse/sexp.cpp
=> Fix set-ets-values sexp documentation bug

code/hud/hudsquadmsg.cpp, code/hud/hudsquadmsg.h, fred2/ignoreordersdlg.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp
That way we get rid of "Message too long" if we use Unicode. Also it is more healthy approach to use strings.
=> Switch communication messages to use SCP_string

code/missionui/missionshipchoice.cpp
=> Play simulated speech if mission is launched while briefing is paused

code/lab/lab.cpp, code/lab/wmcgui.cpp, code/lab/wmcgui.h
Uses the up/down keys.
Addresses the second part of #1710.
=>  Add arrow key scrolling to the lab

code/autopilot/autopilot.cpp, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/debris/debris.cpp, code/mission/missionparse.cpp, code/model/modelcollide.cpp, code/model/modelread.cpp, code/object/objcollide.cpp, code/object/objcollide.h, code/object/object.cpp, code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/starfield/supernova.cpp, code/weapon/beam.cpp, freespace2/freespace.cpp
The new system has been tested pretty thoroughly so I think it is time
to remove this option.
=> Remove -old_collision command line option

code/parse/sexp.cpp
The code already only recomputed collisions if we moved a ship or a wing, but this further optimizes things so that only ships or wings that can collide will cause a recomputation.
=> only recompute collision pairs if we moved a colliding object

code/parse/sexp.cpp, code/ship/ship.cpp, code/ship/ship.h
Previously, these two SEXPs could only be used in single-player; now they can be used in multiplayer.  (This now allows Admiral MS's ship save/load script to work in multiplayer too.)
Inspired by Parias's patch included in the [FSPort Co-Op Mod Beta](https://www.hard-light.net/forums/index.php?topic=88385.0) though with some modifications.
=> multi capability for destroy-instantly and destroy-subsys-instantly

code/ship/afterburner.h, code/ship/shield.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/shipfx.cpp, code/ship/shipfx.h, code/sound/ds.cpp, code/sound/ds.h, code/sound/sound.cpp, code/starfield/nebula.h, code/starfield/starfield.cpp, code/stats/stats.cpp, code/weapon/emp.cpp, code/weapon/emp.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Removes unused code in directories starting with Letters S to Z, as described in #1955 .
Pretty much analogue to #1952
=> Remove unused Code S to Z

code/nebula/neb.cpp, code/nebula/neb.h, code/nebula/neblightning.cpp, code/nebula/neblightning.h, code/object/collidedebrisweapon.cpp, code/object/collideshipship.cpp, code/object/objcollide.cpp, code/object/object.cpp, code/object/objectdock.h, code/object/objectshield.cpp, code/object/objectshield.h, code/object/objectsnd.cpp, code/object/objectsnd.h, code/pcxutils/pcxutils.cpp, code/pcxutils/pcxutils.h, code/physics/physics.cpp, code/physics/physics.h, code/playerman/player.h, code/playerman/playercontrol.cpp, code/radar/radardradis.h, code/radar/radarorb.cpp, code/radar/radarorb.h, code/radar/radarsetup.h, code/render/3d.h, code/render/3dclipper.cpp, code/render/3ddraw.cpp, code/render/3dinternal.h, code/render/3dsetup.cpp, code/render/batching.cpp, code/render/batching.h
Removes unused code in directories starting with Letters O to R, as described in #1955 .
Pretty much analogue to #1952
=> remove unused functions O to R

code/ship/ship.cpp, code/ship/shipfx.cpp, code/ship/shipfx.h
I'm doing a bit of refactoring of the warp code for issue #1835 and I think it would be good to get this enum out of the way as a separate PR first.
=> create WarpDirection enum

code/ai/aicode.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h
Adds 'On Waypoints Done' hook variable for scripting system.
=> Add 'On Waypoints Done' Hook

code/parse/sexp.cpp
now that all troys have been removed from all subsystems, this word can be changed
=> spelling fix

lib/lua/CMakeLists.txt, lib/lua/lua.natvis
This should make debugging issues with Lua easier by providing a better
view on how the Lua state looks like.
=> Add natvis file for Lua

ci/travis/ftp_deploy.sh
This hopefully finishes up fixing the CI to be able to upload Travis builds again.
=> Make sure to use a path that contains the new curl binary

code/mission/missionparse.cpp, qtfred/src/mission/Editor.cpp
Minor miss from 9332311b57c4614245a492d2debc93e291c8d992
Also has trivial comment fix
=> Allow qtFred to open missions again

code/ai/aicode.cpp
Also adds/enhances some handy nprintf debug statements.
Fixes #2040
=> Don't link if ship has 'no primary linking' flag

code/ship/shipfx.cpp
Thanks to @SamuelCho for telling me what to put where to provide the final step to fix this bug. This PR fixes #2046 (for good it seems!).
=> Fix blown_off bug for good

code/scripting/api/libs/testing.cpp
This should fix a problem with the MVPs.
=> Move deprecation of createParticle to the next version

code/io/keycontrol.cpp
Have FSO check for subspace and start the loop up again when subspace is being used.
=> Fix 1433 Take two

code/cmdline/cmdline.cpp
Make -get_flags imply -parse_cmdline_only, per asarium's comment. This should fix #1221.
=> fix issue #1221

code/windows_stub/stubs.cpp
Use m!m's suggestion to fix issue #1138
=> fix FreeBSD warning in stubs.cpp

.github/workflows/pr-workflow.yaml, ci/travis/valgrind.supp
This currently only does the GCC Linux compilation but it's a good start
to check out how this works and if it will work for us.
=> Add GitHub Actions workflow for pull requests

.github/workflows/pr-workflow.yaml, ci/travis/valgrind.supp
This adds more Linux configurations for testing different compilers.
=> Add more GitHub actions configurations

code/scripting/api/libs/base.cpp, code/scripting/api/objs/vecmath.cpp, code/scripting/api/objs/vecmath.h
This should add scripting functionality equivalent to `vm_vector_2_matrix`.  I'm not really a scripting guru so this was made by copying and adapting other functions as appropriate.
=> create matrixes from vectors

code/parse/sexp.cpp
Enhances play-sound-from-file, etc. to allow more than one audio stream to be played at the same time, provided all stream are referenced by audio handles contained in variables.
=> allow multiple simultaneous sexp-controlled audio streams

.gitattributes, .github/workflows/pr-workflow.yaml, cmake/toolchain-msvc.cmake, code/network/multimsgs.h
This will test compilation and tests on Windows as compiled by Visual
Studio and MinGW.
=> Add Windows Checks for GitHub Actions

code/weapon/weapons.cpp
Fix the rearm rate by not depending on flags that haven't been set yet....
=> Set Ballistic Primaries ream increment no matter what

code/missionui/missionweaponchoice.cpp
Fixes 3D weapon selection not working when an animation is already specified.
=> Fixes 3D Weapon Selection Bug

code/io/keycontrol.cpp, code/ship/shipfx.cpp
Preventing a nullptr deep within shipfx_warpin_start()
=> Bring Pirates of the FSO Back by

code/sound/audiostr.cpp
=> avoid full stream reset when looping music

code/ai/aigoals.cpp, code/scripting/scripting.cpp, code/scripting/scripting.h
Adds 'On Goals Cleared' hook variable for scripting system. Previosly there was no scripting or sexp method to determine if a ship had all of it's goals cleared.
=> Add `On Goals Cleared` Scripting Hook

.gitattributes
Making everything auto globally is causing more problems than it might be trying to solve.  This seemed to rectify the problem on the nightly build repo.
=> Fix Line Ending Tomfoolery

code/parse/sexp.cpp
There was a small but serious bug in PR #2063 that would cause a crash.  This fixes it.
=> fix set-object-facing for wings not present

code/model/modelanim.cpp
This patch was posted in 2011 but never applied.  Here's a PR to remedy that.
Mantis ticket:
http://scp.indiegames.us/mantis/view.php?id=2542
Original thread:
http://www.hard-light.net/forums/index.php?topic=79068.0
=> apply fix for model_anim_get_time_type (Mantis 2542)

fred2/briefingeditordlg.cpp
Already tested to make sure the icons now load correctly! 
Fixes the following:
1. Creating an icon from a jumpnode
2. Creating an icon from a waypoint
3. Jumpnode would become a navbouy icon unless there was more than one jumpnode icon in the mission.
It looks like the main reason why this was happening is that they left this line in:
iconp->ship_class = (int)std::distance(Ship_info.cbegin(), it);
I'm not sure which portion of this line is buggy, although my guess is std::distance should not be used with Ship_info.Begin().
After looking at the uses for iconp->ship_class, its value is never read, so just removing the section that was trying to set it should be a sufficient solution.  Also, the icon type is written to biconp, and iconp is not altered for any of the other ship types in this …
=> Fix Crashes In Briefing Screen

.clang-tidy, code/scripting/api/libs/mission.cpp, code/scripting/api/objs/parse_object.cpp, code/scripting/api/objs/parse_object.h, code/source_groups.cmake
=> Add Lua access to not yet arrived ships

code/globalincs/pstypes.h, code/globalincs/toolchain/msvc.h, freespace2/freespace.cpp
Some small changes:
a) Fix admonishment about commenting Assert and fix spelling
b) rename VerifyEx to Verification to be similar to Assertion
c) remove old pre-2005 MSVC code
d) update `COUNT_ESTIMATE` to provide a more accurate loading bar, per discussion in Discord
=> Minor cleanup to Verify and loading bar

code/network/multi_obj.cpp
I'll just leave this here....
Before: https://youtu.be/dsdS6d1q93A?t=25
After: https://youtu.be/P8sdYKtmjO8?t=36
Does this by refactoring how the timing is calculated.  It also removes the Next Arrival Time Array, which does not actually do a good job of calculating it, anyway.  We can now rely on the other oo_arrive_time arrays exclusively by subtracting from current time.
There are further improvements not included in this pull request which require a multiplayer version bump, which is forthcoming.
=> Better Timing For Interpolation Calc

code/scripting/api/objs/ship.cpp
Reverts scp-fs2open/fs2open.github.com#2236 per Mage's justification.
=> Revert "Adds Scripting Support for the Ship Flag `gun convergence`"

code/hud/hudtargetbox.cpp
Also cleaned up the code slightly, the factor variable was only used
when missile_view was false
fixes #2261
=> make small bombs appear smaller in hud targetbox

code/model/modelread.cpp
swap_bsp_data() and swap_sldc_data() use those.
=> Fix build on big-endian architectures

code/def_files/data/effects/rocketui-f.sdr
=> Fix compilation error in shader

cmake/AppRun.in, code/cmdline/cmdline.cpp, code/cmdline/cmdline.h, code/osapi/dialogs.cpp, code/osapi/outwnd.cpp, code/osapi/outwnd.h
This will make it easier to get logs from FSO running in a docker
container since logging to stdout is the easiest solution there.
Also includes some other changes that will make this work better in
Docker containers.
=> Add option for logging to stdout

code/scripting/ade.cpp
This will provide a proper error message when such a function is called
that will mention the name of the function and that it is deprecated and
cannot be used anymore in the targetted engine version.
=> Improve error message for deprecated functions

fred2/fred.rc, fred2/mainfrm.cpp
I originally wanted to embed the version string in fred.rc, but after combing the documentation and stackoverflow for over an hour, I'm no closer to solving it that way.  Instead, I coded a quick hack to modify the title as part of window initialization.
This fixes #2281.
=> Fred2 version small fix

code/graphics/opengl/gropengltexture.cpp, code/graphics/opengl/gropengltnl.cpp, code/ship/ship.cpp, code/ship/ship.h
This looks like it was for a feature that was never implemented.  In any case we have the cloaking post-processing effect now.
=> remove CLOAKMAP

code/gamesnd/eventmusic.cpp
=> Reset the current soundtrack during mission shutdown

code/ship/ship.cpp, code/weapon/weapons.cpp
This adds the `+remove` tag to both ships and weapons, allowing modular tables to remove a previously parsed entry.  There's also a bit of cleanup and some Int3() removal.
~~Marking as draft because I still need to add the "blacklist" feature to prevent later-parsed TBMs from re-adding the removed entries.~~  Blacklist added.
=> Xmt remove feature

code/scripting/scripting.cpp
This fixes the latest issue identified by @tomimaki on #2316.
=> fix yet another issue uncovered by vectorization

code/mission/missionparse.cpp
If ships have less than their full allocation of weapons, the code is supposed to compact the array so that these weapons all appear at the beginning.  This is done for small ships (fighters and bombers), but was not done for capital ships.  There was also a lot of code duplication with small ships getting extra error checking than capital ships.  This commit removes the duplicate code, makes the error checking more robust, and incidentally fixes the weapon array compacting for capital ships.
This fixes the third of three issues in #2316.
=> simplify and fix the subsystem weapon loading code

code/mission/missionparse.cpp
This is a follow-up to #2318.  In the subsystem code, there is some pilot-specific logic that should only run for the Pilot subsystem.
Fixes #2333.
=> fix loading of capship custom weapons

.clang-format, code/graphics/2d.cpp, code/graphics/2d.h, code/hud/hudmessage.cpp, code/mission/missionmessage.cpp, code/scripting/ade.cpp, code/scripting/ade.h, code/scripting/hook_api.cpp, code/scripting/hook_api.h, code/scripting/scripting.cpp, code/scripting/scripting.h, code/ship/shipfx.cpp, code/source_groups.cmake, code/utils/tuples.h, freespace2/freespace.cpp, test/src/scripting/lua/Util.cpp
This moves towards defining the hooks in the code module that executes
them. Also provides the API necessary for better documentation of hooks.
This only covers a few hooks as a test and demonstration of the new API.
If no issues are found with this it can be extended in the future.
=> Add extended scripting hook system

code/math/vecmat.cpp, code/math/vecmat.h, code/missionui/missionscreencommon.cpp, code/ship/ship.cpp, code/ship/shipfx.cpp, code/starfield/starfield.cpp
Quick pull request to add angles to the empty vectors and identity matrix party.  I wanted to do it in the the multi branch, but I realized it was better to keep changes like this out of the way of multi getting done.
=> Add an angles version of zero vector and identity matrix

code/lab/lab.cpp
This enables cubemap generation and adds the ability to switch between SMAA modes in the F3 lab.
=> Small F3 lab fixes

code/ai/aicode.cpp
Originally requested in https://github.com/scp-fs2open/fs2open.github.com/pull/2328#discussion_r415157575, but subsequent progress on that PR may mean the branch may not touch aicode.cpp at all, so it seemed preferable to pare that cleanup out to a separate PR.
=> Set_primary_weapon_linkage cleanup as requested by Goober5000

code/cmdline/cmdline.cpp, code/graphics/opengl/gropenglpostprocessing.cpp
Make sure the SMAA presets are actually passed to the shader stages and that the SMAA shader is recompiled at runtime if the preset changes.
=> Fix bug in SMAA application

code/graphics/opengl/gropenglpostprocessing.cpp
Clean up the aa shader loading/unloading code to handle cases where we switch between FXAA and SMAA correctly
=> A followup to the recent SMAA fixes

code/mission/missionparse.cpp
This PR adds a scripting hook which triggers when a ship begins it's departure process. It has one variable that is the ship. I have tested and it works as expected. This new hook is very useful for triggering events whenever a ship needs an alteration to it's departure methods. 
The following two examples show the utility of this hook (note these are Fate of the Galaxy specific). As a first example, we require ships to warp out along a certain vector. This hook allows us to evaluate when the ship is beginning that departure and then we can use scripting to affect it's behavior to achieve the desired warp effect (such as break the ship's warp, order the ship to instead follow a waypoint path, and then jump out).  A second example is that we require certain ships to close their s-foils …
=> Add `On Departure Started` Hook

code/parse/parselo.cpp, code/parse/parselo.h, code/ship/ship.cpp, code/weapon/weapons.cpp
Minor edits from an obsolete branch that are still useful in cleaning up the code.
=> some code tweaks from an old branch

.clang-tidy, code/cfile/cfile.cpp, code/osapi/dialogs.cpp, code/parse/parselo.cpp, code/scripting/api/libs/engine.cpp, code/scripting/api/libs/engine.h, code/scripting/lua.cpp, code/scripting/lua/LuaFunction.cpp, code/scripting/lua/LuaFunction.h, code/scripting/scripting.cpp, code/scripting/scripting.h, code/source_groups.cmake, fred2/management.cpp, freespace2/freespace.cpp, qtfred/src/mission/management.cpp
This adds the capability to have a Lua script that does not need to use
our table syntax at all but instead defines the hooks by calling API
functions. This also makes it possible to add hook functions at runtime
if the script requires that.
=> Add capability to have a pure lua script

.github/workflows/pr-workflow.yaml
This allows building QtFred on Windows which was the last thing missing
to achieve parity with Appveyor.
=> Install Qt in GitHub actions

code/model/modelrender.cpp
Fixes an issue with some ships having thrusters render through their hull.
=> Temporary fix for thrusters rendering through ship geometry

code/menuui/readyroom.cpp, code/menuui/readyroom.h, code/mission/missioncampaign.cpp, code/mission/missioncampaign.h, code/scripting/api/libs/engine.cpp, code/scripting/api/libs/ui.cpp, code/scripting/lua/LuaTable.cpp
This makes the necessary campaign room API available to the scripting
API so that it can be implemented using libRocket. Also adds an
engine.sleep function which I needed for making my Lua debugger work
reliably.
=> Make the campaign room API available to scripting

code/parse/sexp.cpp
This PR upgrades the function, and the sexps that use it, to take advantage of the new sexp caching.  It also makes `script_eval_multi` more robust in the face of players who might be respawning.
=> upgrade get_player_from_ship_node

code/ship/ship.cpp
=> match strings.tbl

code/parse/sexp.cpp
Another - hopefully bite-size - sexp upgrade stage.  This takes the objective SEXPs (those which are primarily concerned with the mission log) and upgrades them to use the ship registry.
=> upgrade the objective sexps

lib/antlr4-cpp-runtime/CHANGES, lib/antlr4-cpp-runtime/runtime/CMakeLists.txt
This will remove the installation rules for Antlr since they are not
relevant for us.
=> Fix Antlr installation step

code/parse/sexp.cpp
There's another chunk of objective sexps farther down in sexp.cpp, so this PR addresses those.
=> upgrade the objective sexps 2

code/weapon/weapons.cpp
As the title says. 
Should resolve #2409
=> Extend weaponspew to handle burst weapons and beam weapons

code/parse/sexp.cpp
1) combine hits-left and sim-hits-left
2) combine is_ship_stealthy and is_friendly_stealth_invisible
3) combine various energy recharge percent sexps
4) fix a spelling mistake
=> small sexp upgrades

lib/antlr4-cpp-runtime/CHANGES, lib/antlr4-cpp-runtime/runtime/CMakeLists.txt, lib/antlr4.cmake
=> Completely remove santlr4_shared target

code/parse/sexp.cpp
This combines the alt-name and callsign sexps, as well as the ship-class and ship-type sexps.
=> combine and upgrade more sexps

code/parse/sexp.cpp
This merges and upgrades the add/remove/clear goal sexps.
=> combine goal sexps

code/parse/sexp.cpp
This PR upgrades and consolidates the sexp_time_* sexps.
=> merge and upgrade the time sexps

code/parse/sexp.cpp
Fix the waypoints-done-delay sexp to work for both ships and wings.
Also, fix the set-object-speed sexp (which is deprecated anyhow) to work for all ships in a wing, not just the wing leader.
This fixes #2478.
=> fix some sexps

code/parse/sexp.cpp
* Merge primary and secondary weapons depleted
* Upgrade the nav/autopilot sexps
=> some more sexp upgrades

code/parse/sexp.cpp
Upgrade the time-docked sexp, which was missed in the batch of time-x sexps.
Upgrade several sexps which check cargo.
=> upgrade time-docked and various cargo sexps

.github/workflows/pr-workflow.yaml
Seems like there is a bug in aqtinstall in the newest version. 0.8 was
the last version to work correctly.
=> Fix GitHub actions Qt install

code/parse/sexp.cpp
upgrade and merge the various ammo sexps
=> Ammo sexps

code/parse/sexp.cpp
primary/secondary weapon selected, energy percent, shields-left
=> upgrade weapon_selected and related sexps

code/parse/sexp.cpp
last-order-time, set-player-orders, ship-vanish, shield-quad-low
=> upgrade misc sexps

code/menuui/mainhallmenu.cpp
The cause of the #2512 bug was using the new main hall to look up sounds from the old main hall, which would crash in several cases.  The lookup was performed when testing whether or not to truncate a door sound when changing screens or states.  Dan Wentz requested that "glowy" sounds not be truncated, so this preserves that check.  Rather than test the indexes of the door regions, this tests the indexes of the sounds in sounds.tbl.
Right now the retail sound indexes are hard-coded, but it would be easy to make this configurable from mainhall.tbl if modders wanted that ability.
This fixes #2512.
=> better handling of non-truncated hotspot sounds

code/network/multi_sexp.cpp, code/network/multi_sexp.h, code/parse/sexp.cpp
This upgrades the remaining sexps and removes the temporary API stuff.  It was originally the branch containing all the PRs that have been merged over the past few weeks; it should be pruned down to bite-size now.
=> giant refactor of sexps to use caching for ships and wings

code/mission/missionparse.cpp
Volition's arrival code used eager evaluation of arrival cues even before the mission was finished parsing.  With the new sexp optimization code, this can fail because the sexps can depend on ships which are not even parsed yet and thus are not in the ship registry.  So I moved the arrival_delay initialization and added some comprehensive comments explaining what is going on.
This fixes some arrival cue weirdness reported in FSPort and probably unreported in other mods.
=> fix arrival delay handling

code/parse/sexp.cpp
When ships vanish, they are in the EXITED state but their `exited_index` is -1 *and* their `shipp` pointer is null.  So I patched all applicable sexps to take this into account.
This fixes #2527.
=> handle vanished ships for sexps that check exited_index

code/parse/sexp.cpp
Follow-up to #2529.  Fixes #2545.
=> fix copy-paste mistake

code/parse/sexp.cpp
=> fix the special-warpout-name sexp

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Bit of cleanup to increase mission compatibility.
=> lazily write the flag list to prevent empty flag lists

code/parse/sexp.cpp
Fix a problem with the new handling of `<argument>` that popped up in Blue Planet, and also fix some error printing.
=> Fix numeric arguments

code/missionui/missiondebrief.cpp, code/stats/scoring.cpp, code/stats/scoring.h
Upon further consideration, the text is what depends on the persona, so just iterate on that.
=> traitor table addendum

code/network/gtrack.cpp, code/network/multi.cpp, code/network/multi_fstracker.cpp, code/network/multi_options.cpp, code/network/multimsgs.cpp, code/network/multimsgs.h, code/network/multiui.cpp, code/network/multiutil.cpp
Fix issues related to getting and setting info with the PXO game tracker. Some are retail bugs, and the rest are just problems with reintegration of PXO code.
=> Clean up PXO client-side game tracker

code/network/multi_fstracker.cpp, code/network/multi_pxo.cpp, code/network/ptrack.cpp, code/network/ptrack.h
Leaving as draft until it's confirmed to work 100%
=> fix various issues with PXO stats

code/hud/hudets.cpp, code/hud/hudets.h, code/missionui/missiondebrief.cpp, code/ship/ship.cpp, freespace2/freespace.cpp
Where it belongs.
#2582 
Also changes it to a bool, because bool makes more sense.  Already tested.
=> Move unsetting of Wep Cheat to Gamestate code

code/hud/hudparse.cpp, code/menuui/techmenu.cpp, code/menuui/techmenu.h, code/parse/sexp.cpp, code/pilotfile/csg.cpp, code/scripting/api/libs/mission.cpp, code/scripting/api/libs/tables.cpp, code/scripting/api/objs/event.cpp, code/scripting/api/objs/intelentry.cpp, code/scripting/api/objs/intelentry.h, code/scripting/api/objs/model.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/shipclass.cpp, code/scripting/api/objs/shiptype.cpp, code/scripting/api/objs/species.cpp, code/scripting/api/objs/team.cpp, code/scripting/api/objs/weaponclass.cpp, code/scripting/api/objs/wing.cpp, code/scripting/scripting.cpp, code/ship/ship.cpp, code/source_groups.cmake, code/weapon/weapons.cpp
1) Upgrade the pilot file code to correctly save flags whether entries are added *or* removed
2) Make the tech-db/tech-db-multi ship flag handling consistent
3) Add scripting support for intel entries
4) Add scripting support for adding and removing entries from the tech room
5) Minor cleanup
=> cleanup of tech room, and scripting stuff

code/math/vecmat.cpp, code/math/vecmat.h, code/scripting/api/libs/base.cpp, code/scripting/api/objs/controls.cpp, code/scripting/api/objs/model.cpp, code/scripting/api/objs/sexpvar.cpp, code/scripting/api/objs/vecmath.cpp
Several new scripting functions and features related to a script I'm working on.  All new scripting functions have been tested and are working.
This PR is feature-complete, but I want to ask about the `YAxisInverted` function before moving it out of draft status.  What I would like to do is make an `AxisInverted[n]` virtual variable (or indexer?) that accepts any joystick axis and allows testing or setting each axis.  What's the best way to do that?  Or would it be better to add separate `XAxisInverted` and `ZAxisInverted` virtual variables instead?
=> Additional scripting enhancements

code/hud/hudlock.cpp, code/hud/hudlock.h, code/hud/hudtarget.cpp, code/network/multi.h, code/object/object.cpp, code/ship/ship.cpp, code/ship/ship.h, code/ship/ship_flags.h, code/weapon/weapon.h, code/weapon/weapons.cpp
The long awaited multilock feature is finally here! The documentation will be added to the wiki ASAP but one final review for this should be done before merging. This will handle the comments from #1441.
=> Merge Multilock

code/network/multi_obj.cpp, code/network/multi_obj.h, code/object/object.cpp, code/playerman/playercontrol.cpp, code/ship/ship.cpp, code/weapon/weapons.cpp
Multiplayer Compatibility Portion Of Multilock.
Please get the reviews in now so we can get this merged.
*The reason it's in draft is to be extra careful and I would able to test after addressing feedback but before it's merged.*
=> Multilock Patch

code/scripting/api/libs/base.cpp, code/scripting/api/libs/graphics.cpp, code/scripting/api/objs/streaminganim.cpp
add `ba.rand32()` and `ba.rand32f()`, and `gr.clear()`
enhance `streaminganim:process()`
fix `streaminganim:timeLeft()`
=> add several more scripting functions

code/hud/hudlock.cpp, code/ship/ship.cpp
=> Fix for #2616

code/globalincs/globals.h
Rather than having all discussion of this be in discord, forgotten by the next time it comes up, here's a PR.
I've reviewed the code that this touches to the best of my ability and it looks good, and it plays fine as far as I've tested it. 
Implements #2274
=> increased weapon type limit from 300 to 500, matching ship class limit

code/menuui/playermenu.cpp, code/scripting/api/libs/mission.cpp
Also fixes a bug in the function that is used by the libRocket pilot
selection UI.
=> Add Lua function for checking for a red alert mission

code/def_files/data/effects/rocketui-f.sdr, code/def_files/data/effects/rocketui-v.sdr, code/graphics/material.cpp, code/graphics/material.h, code/graphics/opengl/gropengltnl.cpp, code/graphics/util/uniform_structs.h, code/scpui/RocketRenderingInterface.cpp, code/scpui/RocketRenderingInterface.h, code/scpui/elements/AnimationElement.h, code/scpui/elements/ScrollingTextElement.cpp, code/scpui/elements/ScrollingTextElement.h, code/scpui/rocket_ui.cpp, code/source_groups.cmake
This emulates the "scrolling text" effect that is present in briefings.
It is not exactly the same since it just goes pixel wise and not by
character but it looks good enough.
=> Add scrolling text element for libRocket

code/missionui/missionbrief.cpp, code/missionui/missionbrief.h, code/missionui/missionscreencommon.cpp, code/missionui/missionscreencommon.h, code/scripting/api/libs/async.cpp, code/scripting/api/libs/base.cpp, code/scripting/api/libs/ui.cpp, code/scripting/api/objs/audio_stream.cpp, code/scripting/api/objs/player.cpp, code/scripting/api/objs/player.h
This covers the various APIs needed for getting the last parts of the
new command briefing UI to work.
=> Add more scripting APIs for the command briefing

code/mission/missionparse.cpp
With very long mods, this error message can overflow the buffer.  So I changed it to a SCP_string.
=> use SCP_string instead of fixed buffer

code/lab/lab.cpp, code/menuui/techmenu.cpp, code/menuui/techmenu.h, code/parse/sexp.cpp, code/pilotfile/csg.cpp, code/pilotfile/csg_convert.cpp, code/scripting/api/libs/tables.cpp, code/scripting/api/objs/intelentry.cpp, fred2/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.cpp, test/src/menuui/test_intel_parse.cpp
1) Make Intel_info a vector instead of a fixed-size array
2) Make intel descriptions SCP_string so they can be any length
=> make Intel stuff dynamic

code/hud/hudlock.cpp
=> Set ai_info lock variable if the player has any lock slots firing

fred2/fred.cpp, fred2/fred.rc, fred2/fredview.cpp, fred2/fredview.h, fred2/initialstatus.cpp, fred2/resource.h, qtfred/src/mission/EditorViewport.cpp, qtfred/src/mission/EditorViewport.h
1) Clarify some help text for menu options
2) Reorder some menu options
3) Add a checkbox for jettisoning ships that are undocked in FRED
4) Add a menu option for cloning ships (so that they don't have to be dragged out of their positions)
=> Some fred enhancements

code/parse/sexp.cpp, code/parse/sexp.h, fred2/sexp_tree.cpp, fred2/sexp_tree.h, qtfred/src/ui/widgets/sexp_tree.cpp, qtfred/src/ui/widgets/sexp_tree.h
This builds on the previous for-ship-class and for-ship-type sexps.
=> add for-ship-team and for-ship-species sexps

code/menuui/mainhallmenu.cpp, code/menuui/mainhallmenu.h
This adds full modular table support to mainhall.tbl, allowing subsequent tables to override previous main halls, and enabling use of the +nocreate option.
=> add the ability to override main halls with modular tables

code/gamesnd/gamesnd.cpp
=> make sound lookup case-insensitive

code/debris/debris.cpp, code/object/collideshipship.cpp, code/ship/ship.cpp, code/ship/ship.h
Sounds for debris collision and explosion.
=> add more debris sounds

qtfred/source_groups.cmake, qtfred/src/mission/Editor.h, qtfred/src/mission/EditorWing.cpp, qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp, qtfred/src/mission/dialogs/ShipEditorDialogModel.h, qtfred/src/ui/FredView.cpp, qtfred/src/ui/FredView.h, qtfred/src/ui/dialogs/ShipEditorDialog.cpp, qtfred/src/ui/dialogs/ShipEditorDialog.h, qtfred/ui/ShipEditorDialog.ui
Add ShipEditor to QtFred
The Main editor window is feature complete dialogs will be added later.
Could to with thoroughtesting to make sure it matches the old fred in every scenario.
=> Add ShipEditor to QtFred

code/ai/aibig.cpp, code/hud/hudartillery.cpp, code/math/vecmat.cpp, code/math/vecmat.h, code/nebula/neblightning.cpp, code/scripting/api/libs/base.cpp, code/scripting/api/objs/vecmath.cpp, code/weapon/beam.cpp, code/weapon/weapons.cpp
createRandomVector
perturb (for vectors)
perturb (for matrixes)
randomInCircle
randomInSphere
=> add some vector scripting functions

code/menuui/playermenu.cpp
fixes following cmdline options:
-connect
-startgame
-almission
=> properly set multi flag when using last multi pilot

code/ship/ship.cpp, fred2/wing_editor.cpp
=> make wing formation parsing a little more robust

code/graphics/software/font.cpp, code/localization/localize.cpp, code/localization/localize.h
Reverts scp-fs2open/fs2open.github.com#2706
Will fix #2721
=> Revert "Change special_char_indexes to a vector"

code/lab/lab.cpp
=> fix a lab CTD

code/object/collidedebrisship.cpp, code/object/collidedebrisweapon.cpp, code/object/collideshipship.cpp, code/object/collideshipweapon.cpp, code/object/collideweaponweapon.cpp, code/weapon/beam.cpp, code/weapon/beam.h
Also slightly optimizes some of the hooks because the adding/removing of hook variables should be guarded by the same if() block that controls execution.
=> add Hitpos as a hook variable for all collision hooks

fred2/FictionViewerDlg.cpp
Rampage noticed that the dialog would save a fiction viewer entry in some cases even if there was no story file.  This makes the handling a bit more robust.
=> clean up fiction viewer dialog a bit

code/parse/sexp.cpp
=> Call send_ship before destroying it to avoid a crash.

code/scripting/api/libs/tables.cpp, code/scripting/api/objs/shiptype.cpp, code/ship/ship.cpp
Add ShipTypes as a collection to complement ShipClasses.
Also check the correct init variable.
=> add tb.ShipTypes

code/bmpman/bmpman.cpp, code/cfile/cfile.cpp, code/cfile/cfile.h, code/cfile/cfilearchive.h, code/cfile/cfilesystem.cpp, code/graphics/generic.cpp, code/scripting/api/objs/file.cpp, code/sound/ffmpeg/FFmpegWaveFile.cpp, test/src/scripting/ScriptingTestFixture.cpp
The getPath() function would crash if the id was -1.  Also, there was no function for getting the file name.
=> fix getPath() and add getName()

code/network/psnet2.cpp
This was apparently broken the entire time in the IPv6 code and we all missed it.
=> Fix memory error which broke reliable sockets

code/parse/sexp.cpp
Update SEXP help regarding variable types, and also add them to the SEXP syntax checker.
Fixes #2758.
=> polish some SEXPs

code/weapon/beam.cpp, code/weapon/beam.h, code/weapon/weapon.h, code/weapon/weapons.cpp
Also some parse safety for the shrink table values.
=> Add beam 'growth' in addition to shrinkage

code/weapon/beam.cpp, code/weapon/beam.h
=> Put beam->finished_growing into beam->flags

.github/workflows/pr-workflow.yaml, cmake/platformChecks.cmake, code/math/vecmat.cpp, code/missionui/missiondebrief.cpp, code/network/multi_voice.cpp, code/network/multiteamselect.cpp, code/utils/strings.h, code/weapon/beam.cpp, code/weapon/beam.h
This fixes some warnings reported by GCC 10 and enables that compiler to
be used by our CI pipelines.
This fixes #2773.
=> Fix GCC-10 warnings

code/mission/missionparse.cpp, code/ship/ship.cpp, code/ship/ship.h, fred2/wing_editor.cpp
Fix wing name generation, when using hash symbols, to use the new display name method.
=> fix display names for wings

code/missionui/missionweaponchoice.cpp
Phantom Hoover noticed this bug in Vassago's Dirge.  For ships with no allowed weapons list (like Shivan ships) weapon culling would cause a crash.
=> fix bug in ships with no allowed weapons list

code/parse/parselo.cpp
If a message string contained a word that was too long, on its own, for the available screen real estate, the function wouldn't split the string at all.  The new behavior is to split the string even if the split location is suboptimal, since it's better to have as much of the message visible as possible.
Quoting from the code:
```
// only update the line break if:
// a) we don't have a line break yet;
// b) we're still within the required real estate
// (basically we want the latest line break that doesn't go off the edge of the screen,
// but if the *first* line break is off the end of the screen, we want that)
```
=> improve message string splitting for outlier cases

code/weapon/weapons.cpp
I forgot the acceleration time conditional that had also been passed by that point, erroneously exempting it from `Use_additive_weapon_velocity`. (conditional was getting a bit long so i just put it into a variable)
=> Fix to the fix to initial missile physics set-up

code/parse/parselo.cpp, code/weapon/weapon.h, code/weapon/weapons.cpp
Adds `$Spawn Interval` for weapons, doing their spawn event every time that amount of time passes, plus `$Spawn Chance`  for some randomization and `$Spawn Effect` since it can look a bit weird just spawning them naked.
~~This... probably breaks multi. As with type 5 beams, I'm more than willing to wait, but I'm not really sure what it's doing or what its implications for multi would be. I've commented the multi-relevant sections.~~ Multi issues worked out, due to assistance from Cyborg and taylor.
=> Allow for continuously spawning weapons

code/network/multi_obj.cpp
Feeding the wrong index to the rollback struct is a bad idea....  That's late night coding for you.
=> Should fix some crahes and inaccuracies at high pings

code/pilotfile/plr.cpp
This addresses two pilot file issues:
1. Total data loss if a pilot has any medals in multi stats
2. Partial data loss in active pilot when entering the barracks
=> Fix pilot file data loss

code/cutscene/movie.cpp, code/missionui/fictionviewer.cpp, code/missionui/missioncmdbrief.cpp, code/missionui/redalert.cpp, code/network/multi.h, code/network/multi_endgame.cpp, code/network/multimsgs.cpp, code/network/multiteamselect.cpp, code/network/multiteamselect.h, code/network/multiui.cpp, code/popup/popup.cpp, code/popup/popupdead.cpp, freespace2/freespace.cpp
Attempt to fix any states that cause multi to time out or that are poorly handled in multi.
=> Fix multi screen timeouts

freespace2/freespace.cpp
This should fix any number of weird multi issues when exiting a mission without actually having gone into full game play state.
=> Close out mission when returning to multi screens

code/ship/ship.cpp, code/ship/ship.h, code/ship/shipcontrails.cpp, code/weapon/corkscrew.cpp, code/weapon/trails.cpp, code/weapon/trails.h, code/weapon/weapons.cpp
Causes trail points to drift away from each other making a very nice visual effect :)
=> Add trail 'spread'

code/mission/missionmessage.cpp
This resolves #2887, even though that issue is really a case of bad data.
=> don't access invalid memory if the shipnum is -1

code/weapon/weapons.cpp
General Battuta's summary:
> BLAST BUT NO SHOCK (SHOCK SPEED 0): Double damage to hull, regular damage to subsystems
> BLAST AND SHOCK: Double damage to hull, double damage to subsystems
=> adjust weapon calculations based on Discord analysis

code/network/multiutil.cpp
Fixes Mantis 1892
http://scp.indiegames.us/mantis/view.php?id=1892
=> Update host pointer on standalone after host switch

code/hud/hudets.cpp, code/hud/hudets.h, code/ship/ship.cpp, code/ship/ship.h
=> Add ships.tbl flags to tune most aspects of ETS behaviour

fred2/fredview.cpp, qtfred/src/mission/EditorViewport.cpp
Yes, it really was that simple to fix #2283 .
Currently attempting to install qt in order to test the fix on qtFRED.
=> Fix fred control crash

ci/github/dist_functions.sh
The glob pattern was not correct. This should fix the nightly build
again.
=> Fix upload glob

code/model/modelanim.cpp, code/scripting/api/objs/subsystem.cpp
Found a null pointer CTD in modelanim that slipped through initial testing.  Also added some defense-in-depth null checks to scripting.
=> additional null checks

code/network/multimsgs.cpp
=> Prevent Fire_turret from using null values

code/ai/aicode.cpp, code/ai/aiinternal.h, code/ai/aiturret.cpp, code/model/model.h, code/model/modelread.cpp, code/network/multi_obj.h, code/scripting/api/objs/subsystem.cpp
1) modify and prune some turret function definitions
2) clean up KeldorKatarn's submodel orientation parsing
=> some refactor and cleanup

.github/workflows/build-nightly.yaml, .github/workflows/build-release.yaml, .github/workflows/build-test.yaml, ci/linux/create_dist_pack.sh
This fixes a bug in the release pipeline where uploading the debug symbols failed the release build.
=> Fix release debug file name

code/model/modelread.cpp
Add back the copying of model instance information to submodels in other LODs.  This was inadvertently removed in commit 88c1d8a02a9062c394262aca3888e2debb15c22a.
This fixes #3063.
=> fix model_update_instance to handle LODs

code/asteroid/asteroid.cpp, code/debris/debris.cpp, code/object/collideshipship.cpp
=> Update Comments for #548

code/object/objcollide.cpp
Firstly, makes explicit the implicit assertion here that (for non-turning weapons) that a weapon's max vel is the same as its current vel, by making them all current vel because weapons can accelerate now so that assertion isn't always true and it's what it should have been using anyway.
Secondly, no solution to the quadratic equation of _'when a weapon and object will cross paths'_ *usually* means the weapon always outpaces the object, but can also mean the ship always outpaces the weapon, in which case we should not cull. So poll `c` to see if we're negative and always inside the ship's potential movement.
=> Fix collision culling for slow/accelerating weapons

code/cmdline/cmdline.cpp
Yeah, we shouldn't be sending anyone to Mantis anymore.
=> Send them to Github instead of Mantis

code/scripting/api/objs/ship_bank.cpp
The previous pr was supposed to fix what ammo capacity the ship was reloaded to, but instead it was changing how much ammo was in the magazine.
=> Switch the correct ammo variable.

fred2/missionsave.cpp, qtfred/src/mission/missionsave.cpp
Somehow during the annotation merge the save got borked.  This fixes mission saving.
=> mission save bugfix

code/network/stand_gui.cpp
Quick fix to a portion of the code trying to use a vector index in the standalone gui.
=> Make sure to pull from the bounds of the vector.

code/math/vecmat.cpp, code/math/vecmat.h, code/scripting/api/objs/vecmath.cpp
Another function ported from vecmat to vecmath.
=> add useful function

code/hud/hudconfig.cpp
Problem was caused by negative array index write in this section of code.  It looked like this was impossible because either I have a specific gauge selected or all of them selected right?  Not unless I start moving the sliders around *before* I select a gauge!!
=> Actually fix radar range turning to -1 after hud gauge config

code/parse/sexp.cpp, fred2/sexp_tree.cpp
Moves messages to the more suitable default of normal.  Also adds clarifying documentation.
As requested by @MjnMixael
=> Make "Normal" the default option for Messages

code/parse/sexp.cpp
This was mentioned on Discord and it was evident that clarification was needed.
=> add clarification

code/globalincs/vmallocator.h, code/ship/ship.cpp, code/ship/ship.h
Does what it says on the tin.  Fixes #3221.
~~This is in draft status because I haven't tested it yet.~~  Tested and works.
=> make the ship lookup case insensitive

code/scripting/api/objs/object.cpp
=> add SimHitpointsLeft

code/ai/aiturret.cpp, code/ship/ship.cpp
I really need to stop forgetting to initialize things. Also that should've been strictly greater than, no point in doing that if it's 0.
=> Bugfix to turret_inaccuracy

code/scripting/api/objs/debris.cpp, code/scripting/api/objs/fireball.cpp, code/scripting/api/objs/ship.cpp, code/scripting/api/objs/weapon.cpp
This allows scripting to delete certain objects, akin to ship-vanish in sexp.
=> Add vanish Lua function to some objects

code/ship/ship.cpp, code/weapon/weapons.cpp
"I really should stop forgetting to initialize things" -Me, like yesterday
=> Properly initialize trail texture stretch

code/parse/sexp.cpp, code/parse/sexp.h, fred2/messageeditordlg.cpp
Like the C equivalent, these SEXPs allow one action to be taken, or one value to be returned, based on a numeric expression.
=> add switch and functional-switch operators

code/weapon/weapon.h, code/weapon/weapons.cpp
Implements #3236.
Code is pretty much copied from how the fireball type is inferred for SSM's
=> Added flag to select the warp effect type of LSSM's

code/mission/missionmessage.cpp, code/mission/missionmessage.h, code/scripting/api/libs/tables.cpp
Implements #3165.
I decided to rename the list in question to uppercase to make it conform to other global variable names.
=> Add scripting API for accessing registered Simulated Speech Overrides

code/scripting/api/objs/player.cpp
Implements #3158 
Used code similar to the commit button functionality of the campaign selection dialog
=> Lua add campaign switch function

code/asteroid/asteroid.cpp, code/hud/hudparse.cpp, code/iff_defs/iff_defs.cpp, code/mission/missioncampaign.cpp, code/mission/missionparse.cpp, code/parse/parselo.cpp, code/parse/parselo.h, code/ship/ship.cpp, code/weapon/weapons.cpp
Consolidate all the functions which parse lists of data.  They're almost the same except for the data itself, so use templates.  As for the templated function which handles the list, boost the robustness by adding additional checking and error messages.
This completes the fix for #3265.
~~In draft form until I finish testing.~~  Should be ready now, but it would be better if #3269 were merged first because there are some changes that very slightly overlap.
=> rewrite stuffing of lists

code/mission/missiongoals.cpp, code/mission/missiongoals.h, code/mission/missiontraining.cpp, code/network/multimsgs.cpp
This allows multiplayer clients to hear the directive completion sound at the right time and to also see when a directive has been failed.
=> Play directive completion sounds for clients

freespace2/freespace.cpp
=> Add FSO_KEEP_STDOUT env var to skip the AttachConsole() call
