scp-fs2open/fs2open.github.com

- code/cfile/cfilesystem.cpp
- code/network/psnet2.cpp
- code/utils/HeapAllocator.cpp
1. use `SIZE_T_ARG` instead of `"%lu"`; should fix format warning in #5780
2. since `HeapAllocator::checkRangesMerged()` has no effect unless running in debug, `#ifdef` out the function; should fix CI warning in #5778
> a few build fixes

- code/scripting/global_hooks.cpp
The documentation was incorrectly listed as `object` when it should be `gamestate`
> Fix documentation error in On State Start

- code/object/collideshipweapon.cpp
- code/object/collideweaponweapon.cpp
- code/weapon/beam.cpp
- code/weapon/shockwave.cpp
- code/weapon/shockwave.h
- code/weapon/weapon.h
- code/weapon/weapons.cpp
For #5365, adds laser length radius and alpha over time, damage over time, beam alpha over time, homing turn rate over time and shockwave radius over time.
Also removes vestigal `max_lifetime` from weapons.
> Moar curves

- code/menuui/mainhallmenu.cpp
- code/menuui/mainhallmenu.h
BtA is modernizing the UI experience. PilotSelect is becoming a title screen that includes player selection among other options. As part of this, we're removing the Barracks. Players that want to switch pilots must return to the title screen.
In order to make this seamless I want a way to force the ESC keypress during the mainhall not always be "quit game", but instead return to the game title screen.
Unless #4533 is going to be completed soon, this small table feature allows customizing the last non-customizable aspect of each mainhall with a custom script action, similar the "Script" option for door clicks.
> Custom lua action for mainhall esc keypress

- code/controlconfig/controlsconfigcommon.cpp
- code/localization/localize.cpp
These controls, added by SCP were never given XSTRs for localization. This PR adds them.
Follow-up to #5627
> Add built-in xstrs for SCP-added custom controls

- code/ai/aicode.cpp
- code/ai/aiturret.cpp
- code/object/object.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
In many calls to `ship_get_subsystem_strength`, the caller doesn't care about the actual number, just whether the subsystem type is destroyed.  So this adds an optimization to check specifically for that.  In the case of `SUBSYSTEM_ENGINE`, this avoids an iteration over every subsystem on the ship which, for a ship with many turrets, can be significant.
> optimization for checking whether subsystems are blown

- code/globalincs/flagset.h
- code/ship/ship.cpp
- code/ship/ship.h
Here's some low-hanging fruit for reducing the memory footprint of `ship_info`.  This turns the maneuvering thrusters array into a vector, refactors the names a bit, fixes thruster activation when `-nosound` is active, reduces the number of calls to `ship_get_thruster_status`, adds some const-correctness, and converts the timestamps to the new system.
> rcs thruster refactor

- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/messageeditordlg.cpp
Move some special-arg helper functions to sexp.h, as requested by jg18.  While we're at it, also refactor the names and add documentation.
> refactor argument functions

- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
1. Use the `optional_string_fred`/`fout` pattern so the FRED comment parser can follow along with the mission file
2. Since the #Custom Data section is optional and requires a version bump, don't output the section header if the section is empty
> FRED missionsave updates

- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
Replace Container Data is currently not disallowed for the `for-*` SEXPs. This PR fixes that.
Should fix Issue #5783.
> Disallow Replace Container Data for all special argument SEXPs

- code/mission/missioncampaign.cpp
- code/mission/missiongoals.cpp
- code/mission/missiongoals.h
- code/mission/missiontraining.cpp
- code/parse/sexp.cpp
- code/parse/sexp.h
In the course of investigating #5725, I made a few minor code enhancements:
1. convert event status to enum
2. split off the event currency functionality from `Sexp_useful_number`, for clarity
3. move where `Sexp_useful_number` (now `Assume_event_is_current`) is set, to increase its visibility and group it with more appropriate code
4. fix `sexp_event_delay_status` to properly set `Assume_event_is_current` in all return paths
> Event currency tweaks

- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
This should be >= else we can't ever get the first item in the list
> Fix incorrect out of bounds check

- code/parse/sexp/LuaSEXP.cpp
Because it's not actually a problem if scripters are building enum lists On Game Init, which is intended to be allowed.
> Downgrade this warning to a log print

- cmake/toolchain-clang.cmake
- cmake/toolchain-gcc.cmake
Currently, the optimization flag is hard-coded to -O2 (for release) and -Og (for debug). It would be better to leave the choice of optimization to the user. See downstream bug: https://bugs.gentoo.org/887671
This PR implements changes that detect if a user-set -O* flag exists. If so, use them. Otherwise, use the previously hard-coded values.
> Don't ignore user-set -O* flags

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
Previously, there was no way to limit the velocity at which asteroids/debris randomly rotated. There was a way to set maximum speed, thus this PR follows that convention and adds a way to cap the rotational velocity scaling. This PR allows modders to set caps per type, including setting the value to 0 for no rotation.
A single scaling value was used b/c it was the most straightforward value to se via table and it was the employed the least code changes. Asteroids pick a random normalized vector for their rotation when spawning, and then that value is scaled by a random multiplier.
> Allow Modders to Set Rotational Scaling Multiplier for Asteroids/Debris

- code/hud/hudparse.cpp
- code/mission/missiontraining.cpp
- code/mission/missiontraining.h
It's bothered my design sensibilities for a long time that Directives and Directive Help Text are both aligned left. There have even been instances where someone reported they didn't understand a directive in BtA that turned out to be helper text for the directive above.
So to help with clarity this PR adds a way to offset only help text lines to help make things a little more obvious.
> Add way to offset directive help text only

- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
Follow-up to #5755. Before, `allowRelative` was always off, and disabled carrying over many possibly valuable bits of information from a particle's source downstream to the particle effect, why should we withhold it? Well what it means by "allow relative" is that by setting an `attached_objnum` we are implying that the particle's velocity and position are *relative* to that object, and it turns out that all weapon effects, inflight effect, homed flight effect, etc use `SourceOriginType::OBJECT` which enables that behavior if we unconditionally 'allow relative'.
None of the particle info math is built to take this into account, so for now, it needs to remain always off. There is other useful data here, so this does not disable as much as it once did, but the key 'relative motion' aspect is …
> Revert removal of allowRelative in `applyToParticleInfo`

- code/parse/sexp.cpp
- code/parse/sexp.h
- code/parse/sexp/LuaSEXP.cpp
- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
This feature adds, hopefully, the final level of arbitrary do-whatever-you-want-ness to lua sexps. The existing `child_enum` parameter type takes whatever the parent parameter's text is and looks for a Lua Enum list with that name. It was originally intended to be able to have the parent be a Lua Enum list of Lua Enum lists. But I realized it can be whatever you want, currently. The parent could a `ship` type and then the game would look for a Lua Enum list with the name of the ship. That's handy, but it's a one-off. You can only have one list with that name.
With this upgrade a `child_enum` can optionally specify a list name suffix. So if the parent parameter is a ship, the child_enum can specify to look for a Lua Enum list that's `shipname + suffix`.
This also downgrades an Error to a …
> Add child enum suffix option

- code/menuui/mainhallmenu.cpp
This PR moves the valid campaign check to when the player clicks on Ready Room rather than at Mainhall Init. This offers a few advantages. First it allows getting into the game and not getting immediately greeted with a warning in some cases. Players can set options, view the tech room, etc.. all without having a valid campaign selected. Second, developers can do development on a mod without having a campaign file created yet. This still allows them to play single missions and everything. Mainhalls already default to using mainhall 0 if the campaign is invalid. Essentially this PR serves to lower the friction of the initial in-game experience.
I couldn't find any obvious problems in my testing. As best I can tell, all the appropriate places where this matters also have their own checks in …
> Move no campaign warning to on Ready Room click

- fred2/briefingeditordlg.cpp
Prevent "Disable grid rendering" from being stuck on.  Fixes a bug reported by Kitsune.
> small briefing bugfix

- code/ai/ai_profiles.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shiphit.cpp
This option was misleadingly named when originally introduced, so give it a more sensible name.  The old name is still accepted for backwards compatibility.
> rename Vaporize Percent Chance

- code/parse/sexp.cpp
Transfer-cargo is a convenience sexp to copy the cargo string from one ship to another and set the source ship cargo string to "nothing". I find it odd that this is limited to only ships that are docked as a mod could have ships that teleport cargo or other sci-fi tropes. Or a mission could need to transfer cargo between two props without docking them. Really, there's lots of possibilities and reasons to do this with ships that aren't docked together. If a FREDer does want to be sure to only transfer cargo between two docked ships, there is the is-docked sexp!
Notably the sexp description does not say it must be between two docked ships, so this PR simply removes that check and let's FREDers run wild with imagination. I can't think of a way this would affect previous uses of this sexp …
> Remove is-docked check for transfer-cargo sexp

- fred2/playerstarteditor.cpp
We need to call `UpdateData()` in the `OnOK()` function and in several other places so that the member variables are populated with the most recent input from the UI.  This prevents certain input (such as Player Entry Delay changes) from being lost by being overwritten with stale stored values.
This fixes a bug reported by Kitsune where the Player Entry Delay box did not work properly.  It also fixes the random checkbox issue from #5494.
Many thanks to Kitsune for assistance with testing.
> fix loadout dialog updating in FRED

- code/weapon/weapons.cpp
Follow-up to #5753. Gotta recalculate the ubyte alpha here from the float 0-1 so don't forget the 255.0
> Fix for lasers with head on bitmaps

- code/localization/localize.cpp
- code/missionui/missionshipchoice.cpp
Add XSTRs to the strings in `ship_select_blit_info()`. Fixes #5823
> Localize strings in ship_select_blit_info

- code/globalincs/systemvars.cpp
- code/globalincs/systemvars.h
- code/graphics/light.cpp
- code/graphics/light.h
- code/mission/missiontraining.cpp
- code/mission/missiontraining.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- freespace2/freespace.cpp
Convert additional timestamps to use the new timestamp system.  This covers all timestamps referred to in freespace.cpp.  For purposes of organization, the fade-in/fade-out timestamps have been moved to light.h|cpp and the training timestamps have been moved to missiontraining.h|cpp.
There are also several related code enhancements:
1. `FadeType` has been converted from `enum` to `enum class`
2. Initialization of the various training variables has been added to `training_mission_init` (previously they had never been reset between missions)
3. Validity checks have been added to the relevant locations for these timestamps
> upgrade timestamps referenced in freespace.cpp

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/ship/shipcontrails.cpp
One of the features requested in #5378 (specifically the one requested in #5274), this adds a new "$Contrails use absolute speed:" option to game_settings.tbl, which makes the `ct_below_limit()` function check `objp->phys_info.speed` instead of `objp->phys_info.fspeed`. This allows contrails to appear when moving in a direction other than forwards.
> Implement direction-blind contrails option.

- code/graphics/software/font.cpp
- code/localization/localize.cpp
- code/localization/localize.h
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Adds the ability to select the game's language from the in-game options menu with SCPUI. Right now this requires the game to be restarted because many xstr strings are initialized on game_init and not when they are actually displayed/needed. This could be changed in the future.
This also adds a feature to strings.tbl to assign an XSTR to the language name itself.
This also adds a feature to game_settings.tbl to prevent FSO from initializing the three additional built-in languages. This allows mods who don't support those languages to remove them from the SCPUI language selector.
> Scpui language selector

- code/globalincs/vmallocator.h
- code/localization/localize.cpp
This language check should have verified the index is in bounds for the vector, so this PR fixes that. 
It also adds a method and an overload to do the inbounds check a little more clearly where needed in the future.
> Verify this is in bounds and add vector_inbound macro

- code/scripting/api/objs/cockpit_display.cpp
- code/scripting/api/objs/cockpit_display.h
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
- code/ship/shipfx.cpp
- code/ship/shipfx.h
For collections that we want to make dynamic, we should not store pointers in data structures because these pointers will be invalidated if the collection is resized.  This PR takes care of all `ship_info` pointers stored in data structures in the codebase.
Since `WarpEffect` stored pointers to objects and ships (and warp params, which is already dynamic), this PR handles those as well.  There are, of course, more places where ship and object pointers are stored that will eventually need to be handled.
> avoid storing ship_info pointers in data structures

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-standalone.yaml
- .github/workflows/build-test.yaml
- .github/workflows/cache-master.yaml
- .github/workflows/test-pull_request.yaml
- CMakeLists.txt
- ci/linux/configure_cmake.sh
- code/bmpman/bmpman.cpp
- code/controlconfig/controlsconfigcommon.cpp
- code/cutscene/cutscenes.cpp
- code/globalincs/pstypes.h
- code/globalincs/toolchain/clang.h
- code/globalincs/toolchain/gcc.h
- code/globalincs/toolchain/mingw.h
- code/globalincs/toolchain/msvc.h
- code/hud/hudparse.cpp
- code/hud/hudtargetbox.cpp
- code/io/joy-sdl.cpp
- code/io/key.cpp
- code/mission/missionlog.cpp
- code/model/modelrender.cpp
- code/network/multi_lua.cpp
- code/object/collideshipship.cpp
- code/object/objectshield.cpp
- code/parse/sexp/EngineSEXP.cpp
- code/parse/sexp/EngineSEXP.h
- code/scripting/hook_api.cpp
- code/scripting/util/LuaValueDeserializer.cpp
- code/ship/shipfx.cpp
This advances the versions for Clang to 16 and GCC to 13 along with fixing any warnings these new versions are detecting now.
The new image versions also include Vulkan so the additional workflow step for installing that is not necessary anymore.
> Update PR build image and compilers

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
- .github/workflows/cache-master.yaml
- .github/workflows/test-pull_request.yaml
The previous version of the image accidentally removed the /tmp directory which broke things in the GitHub actions.
Initially, an update for the upload/download actions was tried which had no effect but keeping these updated is probably a good idea.
> Update container image to fix artifact uploads

- code/network/multi_pxo.cpp
- code/network/multi_pxo.h
This PR prepares multi_pxo for SCPUI's API by converting the three main linked lists (channels, players, chat) to vectors. It moves some defines to the header for the API to eventually use as well.
This turned out to be kind of a booger because all three lists were implemented slightly differently and converting from a linked list to a vector for FSO's built-in UI isn't always straightforward. That said, tests showed each list rendering correctly. Channels were clickable (and joinable). Players are also clickable and the Player Info button worked as expected. Chat no longer has a limit of 60 messages. Sending, receiving, and scrolling all seem to be working.
> Vectorize multi pxo

- code/hud/hud.cpp
- code/scripting/api/libs/hud.cpp
- code/ship/ship.cpp
- code/ship/ship.h
Just adds a portion of the ship's acceleration to the camera, probably quite dependent on the size of the cockpit model so it's a multiplier the modder can fiddle with to their content along with a scripted toggle. Also normalizes naming of `cockpitActive` and `disableCockpits`
> Add cockpit 'sway'

- code/mission/missioncampaign.cpp
- code/missionui/missiondebrief.cpp
Back in 2008 (in commit 2c45dbbb5f77404e4d1833369cd2f40594731a81), some retail code incrementing `Player->failures_this_session` was removed, seemingly by accident. A month later, a bug related to this was fixed (in commit 28a408deee3496b8f6d81768778c3ff1f2397515) in a different way. Since this fix is rendered redundant by the restoration of the original behavior, I've removed it and put back in the old behavior. This is only "mostly-retail" because the retail code didn't check `Game_mode & GM_CAMPAIGN_MODE`.
This restores the old behavior of allowing a player to skip a mission without having to die (and see the death popup, which doesn't happen in some missions that show a debriefing if the player dies). Since the logic is so straightforward (and other "mission failed" checks in the …
> Restore (mostly-)retail debrief failure counting behavior.

- code/physics/physics.cpp
These few lines of code were what many coverity issues were pointing at.  After looking at the surrounding functions and figuring out what these variables are for, I've determined that nothing is guaranteeing that Tai and Taf are greater than 0.  The only reason why we probably haven't seen issues related to this is that use of the Ai and Af are *currently* gated behind Tai and Taf being > 0 (depending on the variable).  So, that if we ever wanted to expand the avd_movement class, we might run into those values being garbage.  So, we should should ensure that these Ai and Af are set to zero (no acceleration) when no acceleration time is passed to these functions.
In draft until I can run a test.  I do this a lot, but I'm a lot closer to being able to run these kinds of tests than I have …
> Add safety to crusty old physics code (coverity issue)

- code/scripting/api/objs/movie_player.cpp
Make sure the return value is actually a float so that the float format can process it.
Follow up to #5831.  Fixes a crash for invalid movies.
> fix Lua API arguments

- code/osapi/osapi.cpp
These variables are only ever used in the scope of `os_get_legacy_user_dir()`, so they can be scoped rather than global.  This should fix a Coverity issue on the `DCF(low_mem` debug console function.
> change two global variables to be scoped

- code/localization/localize.cpp
Fixes #5857 
The Options Builder will return the default value of `0` even if the new ini setting is not present. We can't set the default value to -1 because that's invalid for the API. So instead let's just avoid the in-game option entirely if the mod.tbl setting is false.
> Only use- in-game language if the mod table option is enabled

- code/gamesnd/eventmusic.cpp
Ever since retail, the code has assumed that a soundtrack would always have arrival music.  This removes that requirement.  If arrival music is missing, it will just be skipped.
Tested by @skdKitsune.
> allow nonexistence of arrival overlays

- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
Calling `query_node_argument_type()` on a node with no parent is a valid use case, so return the proper argument type.  Fixes a crash discovered by Applemush.
> fix query_node_argument_type()

- fred2/addvariabledlg.cpp
- fred2/asteroideditordlg.cpp
- fred2/bgbitmapdlg.cpp
- fred2/briefingeditordlg.cpp
- fred2/cmdbrief.cpp
- fred2/debriefingeditordlg.cpp
- fred2/eventeditor.cpp
- fred2/messageeditordlg.cpp
- fred2/messageeditordlg.h
- fred2/missioncutscenesdlg.cpp
- fred2/missioncutscenesdlg.h
- fred2/missiongoalsdlg.cpp
- fred2/missiongoalsdlg.h
- fred2/missionnotesdlg.cpp
- fred2/orienteditor.cpp
- fred2/playerstarteditor.cpp
- fred2/shipeditordlg.cpp
- fred2/shipspecialhitpoints.cpp
- fred2/shipspecialhitpoints.h
- fred2/wing_editor.cpp
FRED has an autosave feature but it wasn't invoked in too many places.  This adds autosaving whenever a major dialog is closed, unless it was closed by hitting Cancel.  NB: Autosave is not yet implemented in qtFRED.
Also, `addvariabledlg` incorrectly referred to `OnOk` instead of `OnOK` and `CMessageEditorDlg` incorrectly referred to `OnOK` instead of `OnOk`, so this fixes those and distinguishes `OnOk` by renaming it `OnButtonOk` to be consistent with the event editor and other dialogs.
> add more autosaving in FRED

- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/opengl/gropengldeferred.h
Profiling on a RX 5500 XT showed extremely high costs for dynamic light submission, likely related to #787. This PR rearranges buffer construction and submission, and profiling in Icarus on that machine has shown framerates improve by a factor of at least 2 in most busy frames, and up to 6 or more in some sections, without any visual side effects I have detected.
This is accomplished by submitting the matrix uniforms in a single block rather than preparing them one by one for each light. To also reduce repeated bind call, deferred lighting now sorts lights into three sub-lists based on what mesh will need to be drawn for them. This sorting process does not prove expensive in subsequent profiling runs.
~~In draft because I want to make sure I'm happy with the state of the code, comments …
> Deferred light mesh submission optimizations

- code/graphics/2d.cpp
- code/mod_table/mod_table.cpp
Moves the Discord option to a real category and force dropdown selector for the Display Selection option because the display names can be too long for a button option.
> Change the discord option category to "game"

- code/parse/parselo.cpp
- code/parse/parselo.h
- code/scripting/api/libs/graphics.cpp
in draft due to lack of testing and likely need to relocate the code.
Implements the ideas in #5495 and should address #5601, testing pending.
~~The optimizations are implemented in the `gr.drawString()` api function directly rather than applying to `split_str()`. This was done for initially testing the algorithm, as there are around 20 call sites for `split_str()` I wanted to keep the change confined to one targeted area, and I didn't want to think through all the arcane-ass c string contortions in there to find what I could and couldn't cut out.
I think this should definitely go in `split_str()` and see wider testing if the initial testing pans out, though.
I also think that many call sites means it needs to wait for stable before going in, it's just too much potential for chaos at this …
> LuaDrawstring optimization

- code/mission/missioncampaign.cpp
- code/mission/missioncampaign.h
- code/mission/missiongoals.cpp
- code/parse/sexp.cpp
- code/parse/sexp.h
Adds a SEXP that specifically checks for whether a player has skipped a mission.  This can be used to set tech room entries, allowed ships/weapons, and other campaign data that would otherwise break if a player skipped a mission.
This only applies to the the failed-five-times popup.  For this to work with the `skipmemymissionyo` cheat, it would be necessary to load every intervening mission and check the events.  That being said, `skipmemymissionyo` already automatically allows all ships and weapons, so there is much less, if any, need for this SEXP in that case.
This has been tested with a simple two-mission campaign and works for allowed ships/weapons, tech room, and scripts.  ~~It is in draft status pending the resolution of #5506 and #4634~~.
> implement on-mission-skip SEXP

- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/hud/hudbrackets.cpp
- code/mission/missionparse.cpp
- code/mission/missiontraining.cpp
- code/missionui/redalert.cpp
- code/network/multiteamselect.cpp
- code/network/multiutil.cpp
- code/object/waypoint.cpp
- code/object/waypoint.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- code/parse/sexp/LuaSEXP.cpp
- code/playerman/playercontrol.cpp
- code/scripting/api/objs/oswpt.cpp
- code/scripting/api/objs/ship_registry_entry.cpp
- code/ship/ship.cpp
- code/ship/ship.h
This refactors the ship registry and the OSWPT struct to store data as indexes rather than pointers.  This is a prerequisite for making these collections dynamic in the future.  See also #5800.
~~In draft pending tests.~~ Tested and self-reviewed; ready for peer review.
> replace pointers with indexes in ship registry and oswpt

- fred2/briefingeditordlg.cpp
Volition used a bit of juggling when deleting the briefing editor pointer.  Turns out this actually prevents a crash in certain situations, so let's put it back.
Follow-up to #5866.
> juggling fix

- code/mission/missionlog.cpp
This limit has not been bumped since the original public source release.  The final mission in Shepherds has been experiencing mysterious bugs which were finally tracked down to the mission log overflowing its limit and discarding log entries.  Ideally the mission log should be made dynamic and the pruning mechanisms removed, but for the 24.0 release, it suffices to bump the limit.
Colt tested a build with the bumped limit and it fixed all of the mysterious bugs in the affected mission.
> bump missionlog limit

- code/menuui/playermenu.cpp
- code/menuui/playermenu.h
Ever notice that the selected player resets when trying to switch between Single and Multiplayer modes on the player select screen?  Well, this should keep that from happening by first checking if we're initializing or just switching modes in `player_select_init_player_stuff()`.
Tested.  It will correctly load the correct player, whether the mode has been switched or not and whether there are many players on the list or not.
This is very much a "Hide Whitespace Changes" kind of PR.
> QOL: Don't reset the position in the player list if we switch modes

- code/localization/localize.cpp
- freespace2/freespace.cpp
Adds screenshake and unfocused pause toggles to the Options Builder for SCPUI
NOTE: This takes PR #5865 into account already for the XSTR ids.. but it's a PITA to manage that XSTR line with multiple PRs in the pipeline. Will handle any merge conflicts as merges happen.
> More scpui options

- qtfred/ui/FredView.ui
Not sure how this option became false, but it should be true in order for the checkable menu option to be set up properly.
> fix crash in QtFRED

- code/def_files/data/tables/objecttypes.tbl
The name of this table flag was changed for parsing, so we need to update the internal tables to match to avoid log warnings that mods can't fix
> Make internal table file match updated parsing preference

- code/parse/sexp.cpp
The requirement for delayed event status checks to be strictly greater than the event fired timestamp (see commit eed50619ca / PR #5267) means that `is-event-true-delay 0` will not work in debriefings if the event becomes true and the debriefing SEXPs are evaluated on the exact same timestamp.  Normally this is not a problem, but one important exception is the `end-mission` operator which instantly sends the player to debriefing.
This timestamp behavior is working as designed and should be consistent as long as the `end-mission` operator has been around (I've verified it as far back as 3.7.4).  But it does lead to inconvenient situations where the event that called `end-mission` cannot be evaluated by the debriefing.  This makes it slightly more complicated to plan debriefing stages based …
> tweak event status evaluation when the game is not in-mission

- .github/workflows/weekly-coverity-scan.yaml
This fixes the weekly coverity workflow by ny using container images and switching to Checkout V1.
Also removes Vulkan SDK install, since it seems to be taken care of by the new containers or is disabled.
> Fix Coverity WorkFlow

- code/scripting/lua/LuaFunction.cpp
- code/scripting/lua/LuaTable.cpp
2 line typo fix `refere` -> `refer`
> Fix typo in lua error prints

- code/ai/aicode.cpp
- code/ai/aiinternal.h
- code/ai/aiturret.cpp
- code/camera/camera.cpp
- code/model/model.h
- code/model/model_flags.h
- code/model/modelread.cpp
- code/scripting/api/objs/subsystem.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/weapon/beam.cpp
1. make `check_ok_to_fire` return a boolean (like `check_los`)
2. make `check_ok_to_fire` and `check_los` both use a position argument since we don't need the whole turret
3. remove the redundant position prediction code from `ship_get_global_turret_gun_info` (since that needs to be a "pure" function) while making sure "share fire direction" still works
4. skip calculation of the vector in `ship_get_global_turret_gun_info` if we don't need it
5. move the position prediction code out of `aifft_rotate_turret` and into its own function
6. prune some gun position calculation calls since in most cases one will suffice
7. fix position "jitter" with weapon subsystem damage in missions that use gravity
8. `model_rotate_gun` now uses a nullptr position for a reset instead of an extra boolean …
> untangle turret code a bit

- code/scripting/lua/LuaUtil.cpp
After getting the main state from the Lua registry, this function had two Lua thread values on its Lua stack but we only removed one which lead to a value being left on the stack.
Why did this not blow up before? Because undefined behavior.
The only place where this was called was when creating a Lua reference value where luaL_ref is called in the same expression (see UniqueLuaReference::create). The evaluation order of the parameters for the make_shared call is not defined by the standard and for some reason all major compilers (except clang) choose to execute the luaL_ref call before the getMainThread call.
For those compilers, everything is fine. We have some extra values on the Lua stack but that gets cleaned up after the API function finishes.
However, clang first evaluates the …
> Fix unbalanced stack when retrieving Lua main thread

- code/hud/hud.cpp
- code/hud/hud.h
- freespace2/freespace.cpp
Use a single canonical `frametime` value for all HUD rendering, in both `hud_render_preprocess` and `hud_render_all`.  Previously, certain functions called through `hud_render_preprocess` were using the full frametime, rather than the half frametime needed for VR when the HUD is rendered twice.
Fixes #5882.  ~~In draft pending confirmation of the fix from a user with a VR setup.~~ Fix confirmed by @Kerbrer.
> additional HUD fixes for VR

- code/object/object.h
Although they may not seem so offensive, I distinctly remember finding these descriptions phenomenally unhelpful and confusing when I was first starting because it didn't actually use FSO example types.
> Improve description of `type` and `instance`

- code/parse/sexp.cpp
Operators that specify OPF_POSITIVE should be guaranteed to get positive numbers.  This code was previously disabled for performance reasons, but following the contract of the SEXP system is more important.  A future PR will improve the performance of the functions used here.
Also, the `num-players` operator takes no arguments, so fix that.
> restore number hack sign checking in all builds

- code/localization/localize.cpp
- code/menuui/barracks.cpp
- code/menuui/mainhallmenu.cpp
- code/menuui/readyroom.cpp
- code/mission/missioncampaign.cpp
- code/mission/missioncampaign.h
- code/parse/parselo.cpp
- code/parse/parselo.h
- fred2/campaigneditordlg.cpp
- freespace2/freespace.cpp
This improves campaign load error handling in several ways.  The code now makes a better distinction between load failures that occurred because the file was missing, vs ones that occurred because of some actual error such as a parsing failure or savefile incompatibility.  The error when the player clicks on the campaign room has been updated to reflect this.
Also, the fallback behavior has been changed.  If the player's current campaign cannot be found, the code now automatically falls back to the mod's default campaign or the first campaign in the campaign list.  To avoid problems, this only happens when the game is started for the first time or when the player chooses a new pilot; in all other cases there is no fallback from the current campaign, whether or not it can be found.  (This …
> campaign error message improvement

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
Apple Silicon Macs require that all code is signed in order to run. Our builds are partially signed due to the SDL framework already being signed, so it is seen as broken. To fix that we need to codesign all the rest of the necessary files with an ad-hoc signature in order to allow the builds to work properly.
> codesign Mac builds to prevent broken app message

- code/parse/sexp.cpp
- code/parse/sexp.h
This is a new method of ensuring that OPF_POSITIVE numbers are positive.  It works for all numeric arguments, including variables and literals, and caches the status of the node to avoid lookups for every negative number on every frame.  Tested on both operator and non-operator cases.
Follow-up to #5915.  ~~In draft until that is merged.~~
> upgrade the OPF_POSITIVE number hack

- code/scripting/api/libs/ui.cpp
I discovered that the way SCPUI reads in pilot info on the pilot select screen can, in some cases, cause the campaign file data to be reset and then saved on game shutdown.
Basically SCPUI reads in pilots to decide if they are a single player or multiplayer pilot. Depending on the order of operations, this causes `Player` to be set to something valid while the relevant campaign data is reset (because reading a save file always resets the data first). If the player then shuts down the game, the player file is saved and the campaign csg file is overwritten with reset data because `Player` is not nullptr.
I toyed with several ideas to avoid the player file saving in freespace.cpp line 6860/61 in these cases including a scripting hook or a global check. In the end I decided the simplest way …
> Fix SCPUI overwriting campaign data

- code/def_files/data/effects/msaa-f.sdr
Some OpenGL drivers, apparently mostly Apple's, don't just ignore redeclarations of built in variables (as Linux & Windows drivers for AMD and Nvidia seem to), but actively error out.
So, remove the redeclaration, and MSAA will work again on macs and possibly other drivers that might have had this behaviour.
> Fix MSAA for some graphics drivers

- code/controlconfig/controlsconfig.h
- freespace2/freespace.cpp
This keeps observers from accidentally crashing the game by using the proper get eyepoint function when using chase view.  Observers will simply use their natural eyepoint instead of trying to be chase their non-existent ship.  Chase view will still be available on targeted ships.
Fixes #5875 
Btw, this is one of those "hide the whitespace" PR's.
> Fix: Keep Chase view from crashing in multi

- code/io/mouse.cpp
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
- freespace2/freespace.cpp
Adds code to print player options to the log at game start and when the options game state is closed. Fixes #5900.
Has the additional benefit of not only printing most of the ini file data, but also any retail options as well. Once #5895 is merged there is a small bit of additional code here that can be uncommented to only print in-game options if they are active while also still always printing built-in retail options.
This also fixes an incorrect xstr setting for the mouse input option title in OptionsManager.
> Print option settings to the log

- code/weapon/beam.cpp
A small oversight in #5837 - beam jitter is not done when targeting coordinates.
> fix crash in fire-beam-at-coordinates

- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
- code/scripting/hook_api.h
- code/scripting/scripting.cpp
- code/scripting/scripting.h
- fred2/management.cpp
- freespace2/freespace.cpp
- qtfred/src/mission/management.cpp
This PR fixes a crash in the initialization sequence and makes a few defense-in-depth improvements to address related risks.
PR #5379 introduced a bug that everyone, including me, missed the first time around:
> It's worth noting this moves `game_title_screen_close()` above the script hooks for On Game Init and On Splash Screen. This is so that anything that runs on Game Init that might draw to the screen won't have the splash screen fade-out rendered directly afterwards.
Now, script initialization occurs through several functions called in sequence.  During this sequence, the script system is not completely initialized, and therefore `os_poll()` cannot be called lest it invoke other scripting hooks.  Unfortunately, `game_title_screen_close()` calls `os_poll()`, so it needs to be moved …
> fix splash crash and add supplemental script hook

- code/mod_table/mod_table.cpp
Discord option never needs a restart, so this should always return true.
> Fix discord option needing restart

- code/cutscene/cutscenes.cpp
- code/cutscene/cutscenes.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/techroom.cpp
- code/scripting/api/objs/techroom.h
Cleanup & formalize cutscene Lua API. Fixes spelling errors and strange method names. Also fixes Lua index off-by-one error that prevented getting cutscene at position 0 because Lua starts at 1. Allows getting a cutscene by name or index now and adds isValid() to match other Lua Indexers. Also prevents crash if accessing an out of bounds cutscene index.
Note that the spelling error, while printed to the scripting.html, is not actually used by scripts, so these changes should be backwards compatible.
> Cleanup ui cutscene api

- code/graphics/2d.cpp
- code/graphics/2d.h
- code/osapi/dialogs.cpp
There were a few cases that didn't account for the newer in-game option when checking for Windowed mode. This PR resolves that which fixes the issue where the in-game option wasn't accounted for at start up or when creating dialog prompts.
> Properly check if we're running in a windowed mode

- code/osapi/osapi.cpp
- freespace2/freespace.cpp
Similar to windowed mode, this was another case of an in-game option that needed a few more checks added to make sure we respect the correct user setting.
I removed the commandline check in osapi opting to keep all the pause globals in freespace.cpp that osapi doesn't have access to. So rather than more includes we can just return early from the pause/unpause functions.
> Pause the UI properly based on user settings

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
- .github/workflows/cache-master.yaml
- .github/workflows/test-pull_request.yaml
- .github/workflows/weekly-coverity-scan.yaml
- ci/linux/configure_cmake.sh
Upgrades to Ubuntu 20.04 to fix Node v20 problem.
Bumps compiler to gcc-9.
NOTE: This breaks support in official builds for Linux distros older than Ubuntu 20.04
> switch to new linux build image

- code/ai/aibig.cpp
`ai_get_weapon` is not guaranteed to return a valid `wip`, so check for that here.  This should now cover all uses of `ai_get_weapon` in the codebase.
Fixes an Event Horizon crash reported in Discord.  Follow-up to #5842, commit 8dbe0e7.
> Third gravity fix

- freespace2/freespace.cpp
Was playing on the latest nightly after #5955 was merged when I realized my UI paused when unfocused. Thought I fixed that... well turns out this ran into the same issue as lightshafts in #5689 where the compiler was entirely optimizing out the global in non-Debug builds. So let's do the same thing here and instead of referencing the global directly, we'll get at it through the OptionsManager.
> Prevent compiler optimization

- fred2/customstringsdlg.cpp
- fred2/customstringsdlg.h
Fix assert caused by the listbox not having an item selected when checking for duplicates, something that only needs to happen on update rather than add.
> Fix assert when adding custom strings

- code/parse/sexp.cpp
SEXP helps should let the FREDder know whether a given ship argument needs to be already in-mission for the SEXPression to operate. Update the helps to include (ship needs to be in-mission) or (ship does not need to be in-mission) or other relevant helpful information.
> Clarify which SEXPS work on ships not arrived

- code/parse/sexp.cpp
In #5649 / b6c0e8b, the ship registry was updated to take ship death rolls into account.  There was one small wrinkle that it did not account for, however: SEXP operators that return numeric values had previously (i.e. before the introduction of the ship registry) checked the mission log for ship destruction, but after #5649 the EXITED status was not set until after the ship had completely exploded, resulting in certain SEXPs having their conditions slightly modified.  The equivalent of checking the mission log for ship destruction is now checking the ship status for DEATH_ROLL, so it is necessary to make that change for the numeric SEXPs to behave as they did before.
The motivating result for all this is to fix SEXPs like `hits-left` firing after a ship has been destroyed but before it …
> be mindful of death rolls when checking for ship stats

- code/fireball/fireballs.cpp
- code/ship/shipfx.cpp
- code/ship/shipfx.h
Properly set the warp durations when ships arrive and depart, so that the warp animation can open and close smoothly without any discontinuities.
~~In draft pending additional tests.~~  Tested by myself and Gamma39er.
> fix warp time durations

- code/def_files/data/effects/main-f.sdr
Turns out that #5055 had an edge case in which performance for AMD cards with shadows enabled dropped off a cliff.
This has several reasons and fixes, some of them to be addressed in a followup PR after this.
But most of all, this is due to the AMD shader compiler, apparently, not correctly optimizing away the huge swath of unneeded lighting code after the return in the ``#ifdef FLAG_SHADOW_MAP``.
As the code is always dead in this configuration, it's no difficulty to just ifdef it out in that case, approximately tripling FPS on AMD cards with shadows enabled. With this, performance is still significantly lower than before #5055, but no longer downright unplayable.
> Fix faulty / missing optimization for AMD shader compilation

- code/cfile/cfile.cpp
Old Volition bug where the original directory is pushed onto a stack before the chdir() call. If that call fails then the stack is left with a used entry that won't be removed until restart and can cause the stack to fill up. Now it's added only if the chdir() call succeeds.
Also take the opportunity to make Cfile_stack dynamic.
> fix error handling in cfile_push_chdir()

- code/cmdline/cmdline.cpp
The result of this special parsing should produce a mod string identical to the string passed on the command line with the following exceptions:
directory name case, directory separators
Should address the following:
- no fundamental difference in modlist compared to Windows
- no errors or warnings that are not produced on Windows
- do not remove mods from list if missing
- verify mod directory is accessible and actually a directory
- do minimum amount of work to see if mod directory is valid
- fix bug with trainling slashes
> refactor unix modlist handling to fix serveral issues

- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
I was fighting a UI bug where the weapons were rendering way closer to the camera than they should have been in SCPUI. Once I started digging further I found these hardcoded zoom multipliers. I'm sure I copied these from the retail UI code but that no longer makes sense here and it's poor design.
So this exposes the zoom multiplier with a default value of what it is currently. Additionally this fixes a small error in the scripting.html documentation.
While this one walks the line between feature and fix, and BtA can release without it, we'd love to be able to have this fix in 24.0.0 since it's pretty well contained to the scripting API.
> Unhardcode renderSelectModel zoom value

- code/starfield/starfield.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
This fixes the several bugs listed in issue #5980, as follows:
1. Only display the background angle warning once per session, instead of every time FRED automatically autosaves and for every background.
2. Instead of removing all blank backgrounds and then re-adding one, remove all but one blank background.  This preserves any flag changes made on that background.
3. Always save background angles in the old, uncorrected format if the save format is not set to Standard.  Previously angles would be saved in the corrected format, which would be interpreted by retail as a completely different set of angles.
Tested and ready for review.
> address issue 5980

- code/model/modelinterp.cpp
- code/model/modelreplace.cpp
This fixes four issues that became apparent with virtual pofs recently:
- It used the wrong filename, which meant that unless it was replacing a pof, it would complain. Adding a new virtual pof was bugged.
- It didn't consider the renaming options for copying submodels when checking for name conflicts, which meant that renaming a submodel that conflicted didn't resolve the check as it should have
- When replacing submodel numbers, it would replace already replaced numbers again, potentially corrupting the hierarchy
- When replacing textures, it incremented the wrong poly count, causing potentially corrupted geometry and meshes
> Virtual POF fixes

- code/globalincs/pstypes.h
- code/missionui/missionweaponchoice.cpp
- code/model/modelread.cpp
- code/ship/ship.cpp
- code/weapon/shockwave.cpp
- code/weapon/weapons.cpp
The general expectation is that model filenames can be specified as 'none' or '<none>' for no model, but as discovered by no tea, this was not consistent across the code base.  For example, `$Model File: none` was handled as expected but `$External Model File: none` was not.  This PR makes the handling consistent for all ship, weapon, and shockwave POF files, and also adds some extra checks when models are loaded.
> make model file checks consistent

- code/asteroid/asteroid.cpp
- code/debris/debris.cpp
- code/hud/hudartillery.cpp
There were a few instances of `Random::next()` being called without ensuring its arguments couldn't trip an assertion. This should hopefully catch them all.
> Add some security to avoid invalid `Random::next()` calls.

- code/camera/camera.cpp
- code/gamehelp/contexthelp.cpp
- code/graphics/2d.h
- code/graphics/render.cpp
- code/graphics/render.h
- code/graphics/software/font.cpp
- code/hud/hudmessage.cpp
- code/menuui/credits.cpp
- code/missionui/missionweaponchoice.cpp
- code/osapi/DebugWindow.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/scripting/api/libs/graphics.cpp
This refactors the `str_wrap_to_width` function into one that returns string offsets and lengths rather than newly constructed strings.  The algorithm is unchanged (except for one minor bugfix), but the performance is improved because the function no longer copies and re-copies the strings.  This also takes advantage of the optional parameters in `gr_string` and `gr_get_string_size` that provide a string length.
This also fixes an edge case in string wrapping where a word that fits exactly on the border no longer rapidly flips between one line and the next.
As a secondary cleanup, by using `size_t` in the right places, it is no longer necessary to cast a whole bunch of `size_t` parameters to `int`.  This allows a bunch of casts to be removed at the cost of adding one cast of `int` to …
> str_wrap_to_width followup

- code/scripting/api/objs/parse_object.cpp
Previously, Team was an attribute available on ships, but not parsed ships.
> add Team virtvar to parse objects

- code/mission/missionparse.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/parse/sexp.cpp
- code/parse/sexp.h
This is a new argument provider that lists all the subsystems of a ship, optionally restricted to one or more subsystem types.
> add for-subsystems

- code/parse/sexp.cpp
Since its creation, the `is-in-mission` sexp operator has only checked for ships.  But mission designers might assume this also works for wings, leading to a situation where the sexp always returns false because no ship can have the same name as a wing.  Fortunately wing functionality can be added to this sexp without affecting ship functionality.
> make is-in-mission work for wings

- code/scripting/api/objs/ship.cpp
PRs #6009 and #5995 passed CI checking independently of each other, but compilation broke after merging.  This patches things.
> reconcile isValid between PRs

- code/ship/ship.cpp
There was an extra check during ship class parsing that prevented a ship class's type from being set if it had been set already.  This dates back to commit 5f3a6ec7 and was added as a parsing safeguard rather than as part of any modular table checks.  Since the parsing has changed, this extra check is no longer applicable.  Removing the check allows a ship class with a different type to be created using an existing ship class as a template.
> allow a ship class's type to be set more than once

- code/math/floating.cpp
- code/math/floating.h
Change the casts used in the convenience #defines in floating.h.  Since these #defines are used pretty widely, this should reduce the count of C-style casts in the codebase by quite a bit.
Also change the casts in floating.cpp while we're at it, and remove some obsolete or unused code.
> use C++ casts for floating.h and floating.cpp

- code/hud/hudtarget.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
This is a streamlining of functionality, that makes it so one doesn't need to hit a second key to select the subsystem under the reticule.  Instead once you have the capital ship selected, hit Target Under Reticule and it will target a subsystem under the reticule if the feature is enabled and there isn't a new target under the reticule.
> allow targeting subsystems on already targeted ship under reticule

- code/gamesnd/gamesnd.h
- code/globalincs/vmallocator.h
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/background_element.cpp
- code/starfield/starfield.cpp
- code/starfield/starfield.h
This adds Lua API methods for getting suns and bitaps by index, as well as modifying their scale and position.  This removes the need to completely add and remove a background element that only needs to be modified.
> add extra ways to modify background elements in missions

- qtfred/src/mission/dialogs/CommandBriefingDialogModel.cpp
This fixes command briefing data apparently disappearing.  The ui was not being properly initialized because model_changed was being called before the ui was initialized, leading to default values.
This also fixes a few other minor issues.
Fix is tested and works as expected.
> Fix "missing" command brief data

- code/iff_defs/iff_defs.cpp
- code/iff_defs/iff_defs.h
Before this commit, `IFF_COLOR_SELECTION`, `IFF_COLOR_MESSAGE`, and `IFF_COLOR_TAGGED` were hardcoded indices into the `Iff_colors` vector. This could cause problems if any of these three colors were set to the same RGB values (since `iff_init_color()` doesn't create a new entry if the color already exists in the vector), and if a modular table tried to change any of these colors nothing would happen (since it would just create a new entry in `Iff_colors` without doing anything to the hardcoded indices).
This commit instead changes the `#define`s into `extern int`s, and assigns the return value of `iff_init_color()` to those global variables upon parsing the special color values, meaning that any combination of the three can be set to the same color without causing issues, and modular …
> Change special IFF color `#define`s into `extern int`s.

- code/scripting/api/objs/techroom.cpp
Allows scripts to arbitrarily lock/unlock cutscenes which will allow for mods to lock/unlock cutscenes at times outside of playing campaign missions if they desire.
> Allow lua to lock/unlock cutscenes

- code/scripting/api/objs/model.cpp
- code/scripting/api/objs/model.h
- code/scripting/api/objs/ship_bank.cpp
- code/scripting/api/objs/ship_bank.h
- code/scripting/api/objs/sound.cpp
- code/scripting/api/objs/sound.h
Several handle types in the scripting API used inheritance where composition would be more appropriate.  This refactors those types, as well as removing the various handle types that were just aliases for `model_h`.  These are just the C++-side types; all the Lua types remain as-is.
This also refactors `sound_h` to move the previous `isSoundValid` to `isValid` so that `ade_set_args` will work properly for sounds with the `Lua_API_returns_nil_instead_of_invalid_object` flag.  The subclassing from `sound_entry_h` was removed and the "full validity check" was moved to `isValidWithEntry`.  The Lua side remains unaffected, but additional documentation was added to clarify the usage.
Follow-up to #6009 and prerequisite to #6006 due to the `isValid` refactor for `sound_h`.
Depends on #6009; ~~in …
> scripting refactor to compose handle types

- freespace2/resources.cmake
- freespace2/resources/mac/Info.plist.in
- freespace2/resources/mac/InfoPlist.strings.in
- Set app name properly per Apple docs
- Use correct "FreeSpace Open" name
- Set version properly per Apple docs
- Add bundle identifier
- Update copyright date
- Remove localized strings since they are all English already
> clean up and update macOS bundle info

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/scripting/ade.h
- code/scripting/ade_args.h
- code/scripting/api/libs/base.cpp
A design choice very early in FSO's scripting development established that invalid results return invalid objects.  By using a game_settings.tbl flag, this allows invalid results to return nil instead.
~~This also standardizes on `isValid()` (versus capitalized versions) and makes validity member functions `const`.~~  See #6009 
Thanks to Lafiel for help with the template stuff.
> allow invalid arguments to be nil

- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- code/parse/sexp/LuaSEXP.cpp
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
Exactly that. Adds Custom String as a return type that lua sexps can require. The return is a table value containing the three elements of the custom string exactly as if it was accessed by mn.CustomStrings.
> Add opf custom string as a lua sexp return type

- code/model/modelcollide.cpp
- code/object/collidedebrisship.cpp
- code/object/collideshipship.cpp
- code/object/collideshipweapon.cpp
- code/object/objcollide.cpp
- code/object/objcollide.h
- code/scripting/api/objs/model.cpp
- code/scripting/api/objs/object.cpp
- code/scripting/global_hooks.cpp
- code/weapon/beam.cpp
In the first commit:
* Expose NoCollide and NoCollideThisOnly as virtual variables for submodels
* Allow submodels to be optionally specified in object:checkRayCollision
* Be sure to calculate ship-to-ship hit position before the override collision hook is called, in case the hook needs this value.  (The other collision hooks already calculate the hit position before the override hook.)
And in the second:
* Add the submodel that was hit to the On Ship Collision scripting hook.  (This will only be non-nil if the ship was the "heavy object".)
* Add a `getModel()` function to the scripted submodel object.
* Fix some incorrect documentation in `OnShipCollision`.
These will enhance the movement script in Star Fox: Event Horizon.
> enhancements for submodel collisions

- code/ai/aicode.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/network/multi_ingame.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/wing.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
Turn `Parse_names` into a vector and add SCP_string overloads of ship registry functions.  Refactor calling code to use registry as appropriate.  Remove an unused overload of `mission_parse_get_parse_object`.
> some parse upgrades

- code/menuui/optionsmenu.cpp
- code/menuui/optionsmenu.h
- code/menuui/optionsmenumulti.cpp
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
#5895 turned `Using_in_game_options` on by default. This caused FSO to load all options from the new Options Manager values rather than the old registry values. Since retail obviously doesn't use SCPUI, we need to make sure that we then properly save retail options values to Options Manager also.
> Fix retail options not saving

- code/missionui/chatbox.cpp
- code/missionui/chatbox.h
A cleanup/refresh of storing and displaying team chat lines using a struct/SCP_list instead of an array of char arrays where various message parameters were stored and parsed out of the string itself.
> Convert multi team chat to use a struct/list setup

- code/graphics/2d.cpp
They are broken in nebulas anyway... See #5460
> Default framebuffer effects to off

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
When a ship is ordered to guard another ship that is stationary and not incredibly large, the AI will fly to a position then turn and face away from the targeted ship. This behavior is not ideal in various scenarios, including both blockade style formations and overall visuals.
The PR adds a flag that tells the AI to align to the target ship it is guarding once the AI has reached it's guarding position in this situation, which allows all the guarding ships to have the same orientation and look much better and work better for directional defenses.
Tested and works as expected. Also changed some `NULL` to `nullptr` in this function for cleanup.
> Add AI Flag to `align to target when guarding stationary ship`

- code/hud/hud.cpp
- code/hud/hud.h
- code/scripting/api/libs/hud.cpp
- code/starfield/starfield.cpp
Adds a hu.HUDHighContrast virtvar.  Also renames `HUD_contrast` to `HUD_high_contrast` for clarity and makes it a boolean.
> add a HUD virtvar for contrast

- code/scripting/api/libs/graphics.cpp
We already have `gr.getStringWidth()`, but these functions are useful too.
> add getStringHeight and getStringSize

- code/menuui/mainhallmenu.cpp
A simple flag to skip starting mainhall parsing with the retail defaults. This allows things like completely disabling Quick Start for mainhalls that have < 7 clickable areas defined.
> Allow skipping using retail mainhall defaults

- code/object/collideshipship.cpp
- code/scripting/global_hooks.cpp
Since the On Ship Collision hook can potentially be called twice, with the ships reversed, it is necessary for both parameters to have submodels specified.  Otherwise +Override would not be able to handle both cases.
Followup to #6035.
> add ShipBSubmodel to ship collisions

- code/ai/aicode.cpp
When waypoint start index and direction were added in #5698 / 42fc989 et seq., the `Fix_ai_path_order_bug` flag needed to be updated to account for those new options.  This fixes that.
Fixes #6052.  ~~In draft pending testing.~~  Fix confirmed by Durandal.
> update Fix_ai_path_order_bug for new waypoint options

- code/parse/sexp.cpp
`ship-create` has had a preloader for many years, but `weapon-create` and `beam-create` did not.  This remedies that.
> add weapon preloader

- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/opengl/gropenglpostprocessing.cpp
- code/lighting/lighting.cpp
- code/lighting/lighting.h
- code/missionui/missionscreencommon.cpp
- code/ship/shipfx.cpp
- code/ship/shipfx.h
- code/starfield/starfield.cpp
- freespace2/freespace.cpp
There was confusion in the lighting code between light indexes and sun indexes.  These are usually the same, but not always.  This makes several changes to fix light/sun handling.
1. Clarify the distinction between lights and suns and add a `sun_index` field
2. Add a flags field and assign the `dual_cone` boolean to it, as well as a new glare flag
3. Determine light glare by checking the light flag, not the sun (which never worked in the first place as the `stars_sun_has_glare` function checked bitmaps rather than suns)
> fix a few lighting bugs

- code/parse/sexp/sexp_lookup.cpp
In #5894, in the `add_dynamic_sexp` function in sexp_lookup.cpp, a call to `sexp->getHelpText()` was moved to the bottom of the function.  Normally this would be fine, except that this occasion caused the `sexp` variable to be accessed after a `std::move`.  The crash can be avoided by moving the last access of the `sexp` variable just a little bit earlier.
> fix crash caused by using a moved variable

- code/localization/localize.cpp
- code/sound/ds.cpp
- code/sound/openal.cpp
- code/sound/openal.h
Adds EAX and Audio Device selection to the in-game options. All currently require a restart but it may be possible to remove that requirement in the future.
There are lot of options PRs pending with XSTR changes so this will just be set as draft until those are merged and I can update this one's XSTRs, but otherwise the code is complete.
> Basic implementation of some audio options in-game

- code/camera/camera.cpp
- code/camera/camera.h
- code/cmdline/cmdline.cpp
- code/localization/localize.cpp
Adds Cockpit FOV as an in-game option along with a global to toggle using it, per discussion with Lafiel. Also sets a define for the default FOV of 0.75 that is used in multiple places. There are lot of options PRs pending with XSTR changes so this will just be set as draft until those are merged and I can update this one's XSTRs, but otherwise the code is complete.
> Cockpit fov option

- code/lighting/lighting.cpp
- freespace2/freespace.cpp
Fix a minor oversight from #6014; in the ship lab, there are sometimes no suns at all, so remove the assertion.  The lighting check is only needed for supernovas anyway, so make that clear.
Additionally, add further clarification for the distinction between suns, lights, and variables used only for the supernova.  Finally fix one more sun/light discrepancy that escaped notice from #6014.
Fixes an assertion in the ship lab.  Follow-up to #6014.
> additional lighting fixes

- code/model/model_flags.h
- code/ship/ship.cpp
- code/ship/shiphit.cpp
With the `$Damage Impacted Subsystem First:` game_settings flag, weapons will damage submodels over subsystems, even if the subsystem is closer.  Yet occasionally this is not the correct behavior (e.g. for the Rahu's engines).  The new subsystem flag allows this behavior to be selectively overridden.
> add "override submodel impact" subsystem flag

- code/mission/missionparse.h
- fred2/campaigntreewnd.cpp
- fred2/freddoc.cpp
- fred2/management.cpp
- fred2/management.h
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
Thanks to @notimaginative's detective work, nearly all of the FRED stalling when saving a mission can be avoided by simply not calling `model_free_all()`.  By checking a flag in `clear_mission()`, multiple situations can avoid this slowdown, including reload-after-save and import-FSM.
> speed up FRED reloading with this one weird trick

- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/campaigntreewnd.cpp
- fred2/fred.cpp
- fred2/fred.rc
- fred2/fredrender.cpp
- fred2/fredrender.h
- fred2/fredview.cpp
- fred2/fredview.h
- fred2/resource.h
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/mission/EditorViewport.h
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/ui/FredView.ui
Add a routine to the sexp syntax checker that also checks for potential issues.  These are not definitive errors, but situations that might trip up mission designers.  Currently there is one issue checked: the destruction of a wing that has multiple waves and arrives from a docking bay.
> check for potential issues in FRED missions

- code/ai/ai_profiles.cpp
- code/mod_table/mod_table.cpp
The ai_profiles.tbl options can already be read in any order, so it is modder-friendly to extend this capability to game_settings.tbl as well.  This also updates the "unrecognized parameter" log statement to indicate the filename.
Note that this commit should be viewed while ignoring whitespace changes.
> allow game_settings options to be read in any order

- code/mission/missiongoals.cpp
If the goals are marked complete, a mission log entry should be added as well.  Fixes some goal weirdness first noticed by DAK on Discord.
> mission goal cheat fix

- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
- freespace2/freespace.cpp
Mission loading during Multi Mission Sync does not change game-state after the load completes, which is the traditional way to know when loading has finished. This is a simple hook that runs when loading completes regardless of game state and solves that problem.
> On loading complete hook

- code/missionui/chatbox.cpp
- code/missionui/chatbox.h
- code/network/multiui.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/multi_objects.cpp
- code/scripting/api/objs/multi_objects.h
This PR reorganizes the API slightly, putting them roughly in top->bottom order as you'd progress through the UIs. It also moves Netgame, NetPlayer, Status Text, and Info Text up into the newer MultiGeneral category since they apply to more places than just MultiHostSetup or MultiJoinGame. While doing so it implements some additional validation for if those are accessed outside of proper Multi game states.
Finally this PR also implements `MultiGeneral.getChat()` and `.sendChat()`.
Be aware that for reviewing purposes, ui.cpp looks like a large diff but is actually nearly unchanged with the exception of the added code for MultiGeneral's getChat(), sendChat(), quitGame() and setPlayerState(). The rest of the changes that github is showing is just re-organized but unchanged code.
> Multi general api

- fred2/customdatadlg.cpp
- fred2/customdatadlg.h
Trying to add custom data with nothing selected in the dialog box caused a ctd. I apparently had a plan in place to check this but never finished it. This fixes the crash and properly validates the keys so that none are duplicated. If updating a pair then it allows that "duplication" to pass.
> Properly validate mission custom data keys

- code/bmpman/bmpman.cpp
- code/ddsutils/bcdec.h
- code/ddsutils/ddsutils.cpp
- code/ddsutils/ddsutils.h
- code/graphics/opengl/gropengl.cpp
- code/graphics/opengl/gropengltexture.cpp
Adds bcdec lib to convert compressed DDS textures to RGBA based on what the system supports. BC7 if BPTC extension not supported, DXT? if S3TC extension not supported.
Should support cubemaps and volume textures but those were not tested.
Addtional changes:
- remove indexed DDS support since it had bugs but didn't work anyway (R8 should be used instead)
- fix issues with volume textures (nothing to test with)
- remove old compression support flags as they are now obsolete
Fixes #4920
> add support for decompression of DDS textures

- code/network/multiui.cpp
- code/ui/inputbox.cpp
- code/ui/ui.h
Fix multiple buffer out-of-bounds issues with INPUTBOX text. Change get_text() to use safer calling methods and use strncpy() in set_text() to avoid issue with incoming text being longer than what is allocated for the control.
> fix issues with get_text() and set_text() for INPUTBOX

- code/missionui/chatbox.cpp
When attempting to add a chat message which is all whitespace the split_str() function will produce no lines. The strcpy() that follows will then crash due to an attempt to copy a nullptr.
> fix crash when chatbox message is all whitespace

- code/parse/sexp.cpp
- code/parse/sexp.h
- code/scripting/api/libs/mission.cpp
- code/starfield/starfield.cpp
- code/starfield/starfield.h
- qtfred/src/mission/Editor.cpp
This allows the skybox orientation and alpha to be accessed and changed through Lua virtvars, and also adds a sexp to change the alpha.
Unfortunately, changing the alpha has no perceptible effect on the skybox.  This will need the attention of a graphics coder to figure out what might need updating.
> add skybox alpha, and add scripted functions for alpha and orientation

- code/menuui/mainhallmenu.cpp
Previously, there was a 175 millisecond delay when hovering over a mainhall animation before it triggered. This PR makes that value settable via the mainhall table.
Tested and works as expected. Now custom mainhalls have much more of a spring int their step.
Thanks Lafiel and MJN!
> Improve Mainhall Button Responsiveness

- code/network/multi_pxo.cpp
- code/ui/inputbox.cpp
- code/ui/ui.h
The recent fixes to InputBox handling exposed a different issue with SCPUI and logging into PXO. During the login process the method `multi_pxo_process_common()` is run, but since it's run by FSO and not the LUA API it correctly has `api_access` set to false. Thus is also runs `multi_pxo_chat_process()` which expects the chat InputBox to have non null data.
However since SCPUI has already overridden the ui creation at this point the InputBox does not get created. I thought through a number of ways to fix this, but in the end I decided a simple method to test if an InputBox is valid was the simplest.
> Check if inputbox is valid

- code/network/multiteamselect.cpp
- code/network/multiteamselect.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/shipwepselect.cpp
- code/scripting/api/objs/shipwepselect.h
Adds everything that should be needed for multiplayer loadout selection. Adds the ship/weapon packet sending and disallows directly setting wss slots if in multiplayer mode.
Also fixes a few small issues and adds stopMainhallMusic because in multi it needs to be stopped manually.
> Team Loadout API for SCPUI

- code/mission/missionparse.cpp
- code/mission/missionparse.h
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Allows ships and wings to arrive behind a ship, to complement 'In front of ship'.  In fact, the arrival code is nearly identical, with just a small tweak to distinguish ahead from behind.
Since the new arrival location represents a change in mission format, this also adds code to detect for its usage and set the mission format to 24.1.  Most missions can continue to be saved as version 23.1.
> add 'In back of ship' arrival location

- code/scripting/api/objs/ship.cpp
The checkVisibility function did not check its arguments' validity, leaving open the possibility of a null pointer access.
> fix checkVisibility

- code/hud/hud.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/wing.cpp
- code/scripting/hook_conditions.h
- code/ship/ship.cpp
- code/ship/ship.h
- fred2/fredview.cpp
- fred2/missionsave.cpp
- fred2/shipeditordlg.cpp
- fred2/wing_editor.cpp
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditorDialogModel.h
- qtfred/src/mission/missionsave.cpp
- qtfred/src/ui/dialogs/ShipEditorDialog.cpp
To enforce type safety for arrival and departure locations, this converts them to enum classes.  Various casts are added when appropriate to convert between the indexed and enum values.
> convert arrival/departure locations to enum classes

- code/network/multimsgs.cpp
- code/ship/ship.cpp
Remarkable that we're still finding bugs in fighter beams after 20 years...
Since field-of-fire angles are specified in degrees, and `cosf` accepts radians, the angle needs to be converted (and then halved, per usage elsewhere).  Although this is a bugfix, this should technically not affect fighter beam behavior because fighter beams always fire down their normals.
> fix fighter beam FOV calculation

- code/scripting/api/objs/ship_bank.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/weapon/weapons.cpp
This allows a scripter to override the 'fof cooldown' i.e. where in between its regular fof and its max fof it is at the moment, this way they can make it be based on whatever, instead of just spread and reset rate. As part of this +Max Fof no longer requires spread rate, since it's harmless to provided a max fof but no engine builtin way for it to reach that max.
> Allow for more field of fire cooldown shenanigans

- code/hud/hudescort.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
As a follow-up to #5523, some mods use callsigns for their ships but prefer not to display the callsigns in the escort list.  In lieu of a more flexible way to configure escort lists, a simple flag is sufficient to implement the desired behavior.
It is recommended to ignore whitespace changes when reviewing this PR.
> add flag to not show callsigns in escort list

- code/parse/sexp.cpp
Set the bad node to the ship node, so that the FREDder can see which ship is receiving the invalid order.  Without this change, the bad node would point to the last value parsed, which is typically the goal priority.
Fixes a misleading error dialog reported in Discord.
> fix bad node identification for certain SEXP errors

- code/parse/sexp.cpp
- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
Hides the `key-reset` operator in FRED and elaborates on the help descriptions for both it and `key-reset-multiple`.  Implements #6076.
> hide key-reset

- code/ai/ai_flags.h
- code/ai/aicode.cpp
- code/ship/ship.cpp
- code/ship/ship_flags.h
Ships in a wing automatically getting into formation with their wing leader when they share the same waypoint order is nice, but can surprise and frustrate fredders in certain circumstances, #6056 and $fix ai path order bug being good examples of this. They were genuine bugs which deserved fixing anyway, but sometimes its more hassle to the fredder than its worth, so this lets them turn it on and off at will.
> Add waypoints-no-formation flag

- code/scripting/api/libs/graphics.cpp
Allow the resize mode to be specified to `gr_set_clip()` without changing the active graphics-wide resize mode.  Along with `drawStringResized`, this provides a shorthand to allow text to be drawn at different sizes, with the appropriate clipping regions, without requiring access to the `CurrentResizeMode` virtvar.
> setClip enhancement

- code/asteroid/asteroid.cpp
- code/fireball/fireballs.cpp
- code/fireball/fireballs.h
- code/hud/hudartillery.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/parse/sexp.cpp
- code/scripting/api/libs/tables.cpp
- code/scripting/api/objs/fireballclass.cpp
- code/ship/ship.cpp
- code/weapon/weapons.cpp
- fred2/sexp_tree.cpp
- fred2/warpparamsdlg.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
As requested by Event Horizon, this removes the limit on fireball types.  The fixed array has been replaced with a vector and the relevant code updated accordingly.  There is also a new version of `stuff_int_list()` to parse ints into a vector.
This also adds bounds checking for explosion animations that are parsed for ship classes, ship types, and asteroids, since previously there was no guarantee that the indexes would be in range.
Tested by myself and Ice Cream Man.
> make fireball types dynamic

- code/weapon/weapon.h
- code/weapon/weapons.cpp
Makes it so that laser glows can be scaled relative to their laser bitmaps, for length, head, and tail.
> Make laser glow scaling configurable.

- code/sound/sound.cpp
There is an absolute volume threshold of 5% after all volume concerns, most sounds will not play if they are below that threshold. While this seems reasonable, it's quite easy to hit that threshold under modest conditions. With effects volume at the second pip (1/9 volume) and the prometheus' tabled volume of 0.4, *you cannot hear your shots firing at all*.
Remember that setting some of those volume sliders rather low may be necessary for the user to achieve the desired *relative* levels among effects, voice, music, etc and that a user can turn up their system volume to make any setting, no matter how low, sound normal.
All sounds already have tabled limits and a priority system in place specifically in order to ensure the audio environment functions as desired.
> Reduce absolute volume threshold

- code/radar/radardradis.cpp
- code/radar/radardradis.h
- code/radar/radarsetup.cpp
- code/radar/radarsetup.h
- code/scripting/api/libs/base.cpp
- freespace2/freespace.h
Several improvements and fixes to the DRADIS radar, one of which (tracking blip expiration) dates back to the original implementation.
1. Convert `sweep_duration` from seconds to milliseconds to work correctly with the timestamp system.  Also clarify use of `game_get_overall_frametime()`, especially with `ba.getFrametimeOverall()`; and add `ba.getSecondsOverall()` to do what `ba.getFrametimeOverall()` allegedly did.
2. Fix a bug where blips expired immediately every frame; they now track their expiration by object
3. Store object numbers rather than object pointers
4. Clamp both the high bound and the low bound of alpha values
5. Change sweep_percent field to sweep_angle to be more accurate
6. Remove some obsolete commented code
Follow-up to #5839.  Fixes blips immediately fading out in …
> Fix DRADIS blips

- code/parse/sexp.cpp
- code/parse/sexp.h
This is a follow-up to #2942.  That PR solved most of the short-circuiting issues with nested conditionals under when-argument, but it was still possible for the code to incorrectly short-circuit on a nested conditional that had `<argument>` in an action operator but not a condition operator.  The cleanest way to fix this is to not short-circuit on *any* nodes that are part of a when-argument tree.
> don't short-circuit eval_sexp on any nodes in a when-argument tree

- code/cmdline/cmdline.cpp
- code/cmdline/cmdline.h
- code/io/keycontrol.cpp
This provides a command-line argument to restrict the time compression range to the classic 1x - 4x.  Implements #6075.
I'm not entirely satisfied with `-orig_speedx_range` but it's the best I came up with that fit into the 19-character limit.  I'd be open to other suggestions.
> allow restriction to vanilla time compression range

- code/missionui/missiondebrief.cpp
Fixes an issue where SCPUI Debrief would accidentally unload whatever's in the first 2 bitmap slots, usually fonts
I couldn't decide whether to init `Background_bitmaps` to -1, set it to -1 if loading is skipped, or just skip unloading. All would work. I opted for skipping unloading to match how the API does everything else.
> Do not unload debrief bitmaps in API mode

- code/ai/aicode.cpp
Follow-up to #6047. This method better accounts for matching the guardee ship orientation when using the new AI flag.
Tested and works as expected. Thanks @BMagnu!
> Update `Align to target when guarding still`

- code/mission/missionbriefcommon.cpp
- fred2/management.cpp
- freespace2/freespace.cpp
- qtfred/src/mission/management.cpp
Make the initialization sequence consistent so that FSO, FRED, and qtFRED call their initialization functions in the same order.  Most of the changes involve bringing FRED and qtFRED into sync with FSO.  This fixes fireball prerequisites for the ship types table, applies the script initialization fixes from #5946 to FRED, and generally removes the possibility of any surprises due to FRED differing from FSO.
Also remove the empty `brief_init_colors()` function.
> make initialization consistent among FSO, FRED, and qtFRED

- code/ai/aiturret.cpp
- code/ship/shipfx.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
In weapons.tbl, there is now an option to, instead of defining a retail-style muzzle flash, set a tabled particle effect to activate when the weapon is fired.
The effect's source velocity is set to the parent object's velocity (usually the firing ship), so using +Parent velocity factor will allow the muzzle effect to stay with a moving ship rather than quickly falling behind. It would be useful to also have the option of parenting the particle effect to the ship, but if that functionality is ever added to particle effects, it should as far as I can tell be simple to slot it into the implementation I have here.
Addressing the possible argument that this should be done via the events system instead: I agree that the events system will be useful for certain types of very complex muzzle …
> Adds muzzle effect functionality.

- code/weapon/weapon.h
- code/weapon/weapons.cpp
Adds an option in weapons.tbl to offset the rendered position of a laser bolt relative to the position of the weapon object, according to a vector.
The behavior of offsets along the z axis (the direction the laser is pointing) is intuitive; however, the orientation of the x and y axes are determined by the rotational orientation of the weapon -- which by default seems to match the orientation of the firing ship, but which would change if the weapon rotates for some reason. I plan to clearly explain this in wiki documentation, and recommend that modders typically only use z offset.
> Laser bolt offset

- code/ai/aiturret.cpp
- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
- code/particle/ParticleSourceWrapper.cpp
- code/particle/ParticleSourceWrapper.h
This makes it so that the functions for setting up a particle effect, which don't need non-const data, take consts. This way they'll be easier to use when the data you have is a const.
> Changes particle effect functions to take consts.

- code/hud/hudtarget.cpp
- code/parse/sexp.cpp
- code/ship/ship.cpp
- code/ship/ship_flags.h
What it says on the tin.  This supersedes PR #2917, as it puts the flag check in the proper function and uses a ship flag rather than a mission flag.
> add ship flag to disable message scrambling when EMP is active

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/physics/physics.cpp
The three functions `physics_apply_whack`, `physics_apply_shock`, and `physics_collide_whack` limited speed after the physics had been applied, but they limited absolute speed, not the speed due to the physics.  This modifies the process to limit the change in speed.  It also adds an AI profiles flag to disable the limit if desired.
This also tweaks the three functions (by editing comments and moving lines) to be more consistent, since all three are doing very similar calculations near the end.
> refine process for capping speed due to physics whack/shock/collide

- code/mission/missionmessage.cpp
- code/sound/sound.cpp
When messages are distorted due to EMP effects, the voice volume should be controlled by the voice setting, not the effects setting.  Fixes a bug noticed by @skdKitsune, a portion of which dates back to the original public source release.
Also, when volume is adjusted in `snd_set_volume`, make sure the correct voice volumes are used.  Fixes a copy-paste bug from #5694.
> properly distinguish between adjusting voice and effects volume

- lib/discord/thirdparty/rapidjson/document.h
Turns out the rapidjson lib that's shipped with our version of the discord rich presence library does not compile under GCC14.
Reason being that one of the string types allows reassignment, which is illegal as the underlying data is marked const.
The reason this didn't error earlier is, I suspect, that this is a template class, so only stuff that's actually used is instantiated. As the reassignment function was never used, this wasn't an issue. GCC14 however seems to notice the error and complains despite the function not being used.
So, to fix it, just delete the reassignment operator.
> Fix compilation with GCC14

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/scripting/api/libs/base.cpp
Considering that we have `ba.createRandomVector()`, we should have `ba.createRandomOrientation()` too.  This is based on an algorithm devised by @Baezon.
> add createRandomOrientation

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/scripting/api/libs/base.cpp
Follow-up to #6152. Forgot that `vm_vec_rand_vec` still uses the 'cube' method instead of the one in `vm_vec_random_in_sphere` which actually uses spherically uniform points. I thought about updating createRandomVector this way, and then updating `vm_vec_rand_vec` this way, and well maybe that's better for a separate PR.
> Better rand vec for createRandomorientation

- code/asteroid/asteroid.cpp
- code/debris/debris.cpp
- code/hud/hudshield.cpp
- code/hud/hudtargetbox.cpp
- code/model/model.h
- code/model/modelrender.cpp
- code/model/modelrender.h
- code/scripting/api/objs/cockpit_display.cpp
- code/scripting/api/objs/modelinstance.cpp
- code/scripting/api/objs/modelinstance.h
- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/ship.h
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- code/starfield/starfield.cpp
- code/weapon/weapons.cpp
- fred2/fredrender.cpp
- qtfred/src/mission/FredRenderer.cpp
Texture replace on a per-instance level was previously reserved for ships only. And for no good reason, given that the model_render parameters could take replacement lists for any model. As such, this PR refactors the whole code for replacement textures, and moves it to a member of polymodel_instance. In addition, this PR properly feeds the new replacement textures to the renderer for any applicable rendering of modelinstances.
At the same time, I've used the opportunity to clean up the code, and most importantly, replace the randomly malloc'd int array with a managed smart pointer that alloc's a fixed sized array (which also takes care of -1 initialization by itself).
> Refactor replacement texture to a modelinstance parameter

- code/ship/ship.cpp
Follow-up to #4757. Fixes #6164. If the effect timestamp is valid and not yet elapsed, then the cloak flag should be off. Only a fully completed, `disables_rendering` effect gets the 'cloak' flag.
> Fix for 'decloaking' effect

- code/weapon/weapon.h
- code/weapon/weapons.cpp
While working on another feature that involves weapon spawning, I discovered that the lifetime of spawned weapons is automatically increased or decreased by a hardcoded random factor bounded at 0.2 in either direction, and began screaming.
@Baezon pointed out that the proper way to approach this would be to make it configurable, so I did that. I think it's sort of a tossup whether it's better to have it be a parameter on the parent weapon or on the child weapon, but I went with child. I also made it so that the parameter can be arbitrarily large, but the resulting random multiplier for lifetime is bounded at 0.01.
Also, I'm 100% open to suggestions for the parameter name, because this one sucks.
> Makes random life factor of children configurable.

- code/weapon/beam.cpp
Previously, type 5 endpoint randomness was set using the values for the startpoint, and the endpoint values specified by the modder weren't used. This fixes that.
> Sets type 5 end point rand to use correct values.

- code/controlconfig/controlsconfig.cpp
- code/hud/hudsquadmsg.cpp
- code/io/key.cpp
- code/io/key.h
- code/io/keycontrol.cpp
- code/menuui/credits.cpp
- code/model/modelinterp.cpp
- code/network/multi_voice.cpp
- code/playerman/playercontrol.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
- code/scripting/hook_conditions.cpp
- code/scripting/hook_conditions.h
- code/scripting/scripting.cpp
- code/scripting/scripting.h
- code/ui/checkbox.cpp
- code/ui/radio.cpp
Closes #4533.
This PR makes the On Key Pressed hook overridable.
Overriding a keypress will make the press basically non-existent to FSO. The only thing that the keypress will have an effect on apart from the override itself is that an On Key Released hook will still fire once the respective key is released.
This allows scripts as requested in the linked issue, such as the following to catch all escape's while in the scripting state:
```
$State: GS_STATE_SCRIPTING
$Raw KeyPress: Esc
$On Key Pressed: [
]
+Override: [
return true
]
```
In order to achieve this, a bit of code-cleanup was needed. Key-Down checks now entirely run through function calls as opposed to reading the raw key array. The underlying data structures were cleaned, with unused ones removed and tidied. All data was moved …
> Allow overriding low-level keypresses

- code/options/Option.cpp
Really, fixing category comparison, allowing importance to be used. When options are displayed, they are sorted first by their category, and then by the supplied 'importance' value. But the category comparison was done directly, using direct pointer values, in effect never comparing equal and never using importance.
> Fix option manager importance

- code/weapon/weapons.cpp
Previously, the transition state between main and headon bitmaps was calculated independently for a laser's laser bitmap and its glow bitmap. Sometimes, this caused the glow bitmap to change earlier than the laser bitmap, or vice versa. This is undesirable behavior; the state of the glow bitmap should always exactly match the state of the laser bitmap in this regard.
I altered the logic so that glow headon rendering uses the alpha multiplier already calculated for the main bitmap, ensuring that they will always be the same. As a bonus, this approach should be some amount more performant, since we only have to do the alpha-determination math one time instead of twice.
Note: if there is no laser bitmap rendered, the headon transition math for it will never be run, and the alpha multiplier …
> Make headon transition behavior consistent between laser and glow bitmaps

- code/cfile/cfile.h
- code/cfile/cfilesystem.cpp
- fred2/freddoc.cpp
- fred2/freddoc.h
- fred2/management.cpp
- fred2/management.h
- fred2/missionsave.cpp
- fred2/missionsave.h
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/mission/missionsave.cpp
- qtfred/src/mission/missionsave.h
- qtfred/src/mission/util.cpp
- qtfred/src/mission/util.h
- qtfred/src/ui/FredView.cpp
FRED will periodically autosave the mission to a series of Backup.NNN files in %APPDATA%, but this is not widely known, and in any case the user typically must restore the file himself in the event of a crash.  This PR adds code to the File -> Open routine that will automatically check all of the autosaved files whenever the user opens the mission.  If an autosaved file has the same creation date but a newer modification time than the desired file, FRED will prompt the user to open the autosave instead.
This PR adds equivalent code to qtFRED as well, but the autosaving of Backup.NNN files has not been implemented in qtFRED yet.
Implements #6118.
> Fred autorecover

- code/scripting/api/objs/model.cpp
- code/scripting/api/objs/model.h
Indexes are a more robust way than pointers to manage model and submodel handles, and in the event that models are made dynamic in the future, indexes will be necessary anyway.
> convert model_h and submodel_h to use indexes

- code/scripting/api/objs/ship.cpp
There's already a sexp that does this, but having the script version for ships is quite useful, too. For example, scripters can set impact damage types for just the player at various difficulties.
> Expose Impact Damage Type to Scripting

- code/graphics/opengl/gropenglopenxr.cpp
- code/math/floating.h
- code/network/multi_log.cpp
- code/weapon/weapons.cpp
Fixes the few remaining compilation warnings in the current codebase.  Also adds comments to the various casting macros for clarity.
> fix compilation warnings

- code/particle/ParticleSource.cpp
- code/particle/ParticleSourceWrapper.h
Previously, particle effects spawned from beams had their source velocity set once at the initiation of the effect, which meant that particles that continuously spawned from a slashing beam would inherit their velocity from the beam's *starting* state, such that the direction would be wrong as soon as the beam moved. I've fixed that by making beam-sourced particles get their velocity from the beam's current direction vector (it might actually be the last frame's; I'm not sure. Either way, it's close enough.), multiplied by its weapon speed.
I am somewhat concerned about performance here -- I don't have much frame of reference for how much it costs to look up these values. In particular, multiplying the vel by the beam's max_speed is only there to make things slightly more intuitive for …
> Fix beam particle velocity

- code/ai/ai_profiles.cpp
- code/ship/ship.cpp
- code/weapon/beam.cpp
- code/weapon/weapons.cpp
A few fixes here
- Fighters use a fake turret for fighter beams including filling in `turret_fov`, possibly based on the weapon's field of fire. `turret_fov` is *only* used by the beam code in order to prematurely terminate a beam that has gone out of the turret's fov. This should *never* apply to fighter beams, because it makes no sense.
The fake turret should have an fov of -1 (for 360 coverage) and the code that checks against the fov shouldn't bother with checking fighter beams in any case.
- `beam_aim` early returns for non-targeting beams without coordinates or a target. This would apply to omni beams fired without a target, which is perfectly fine! Nor should `beam_get_binfo` early return in similar circumstances.
- Relatedly, the `Force_beam_turret_fov` is really important! …
> Assorted beam fixes

- code/globalincs/utility.h
- code/parse/sexp.cpp
- code/scripting/api/objs/ship.cpp
Inspired by #6178, this moves the existing `count_items_with_name()` functions into utility.h and adds additional functions for finding specific items with a given `.name` or, more generally, a given field.  The `Damage_types` search has been converted to illustrate how these functions can be used.
> utility functions for counting and searching

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/mission/missionparse.cpp
- fred2/asteroideditordlg.cpp
- fred2/dumpstats.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
- qtfred/src/mission/missionsave.cpp
Currently asteroid fields save the asteroid types and the debris types in the same array within the asteroid field struct. See code example below. This PR moves asteroid types into their own array, `field_asteroid_type` that's a bool instead of an int. This will allow another feature I'm working on later; unlimited debris types rather than debris being limited to three types. You can then create a really nice field of space junk!
This also slightly adjusts usage of MAX_ACTIVE_DEBRIS_TYPES and NUM_ASTEROID_SIZES to match the newer handling. This will be further adjusted in future PRs where MAX_ACTIVE_DEBRIS_TYPES is entirely removed in favor of `Asteroid_field.field_debris_type.size()`
Old & Crusty
```
if (Asteroid_field.debris_genre == DG_ASTEROID) {
Asteroid_field.field_debris_type[0] = …
```
> Split up debris and asteroid types

- code/hud/hudtarget.cpp
- code/hud/hudtargetbox.cpp
- code/hud/hudtargetbox.h
- code/localization/localize.cpp
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/playerman/player.h
- code/playerman/playercontrol.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/ship_flags.h
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Are you tired of remembering whether you need Scannable to get cargo names to appear? Or maybe you're sick of Toggle Subsystem Scanning having different effects based on the ship type? Did you once want to have a mission where a transport wasn't scannable at all? Then have I got the PR for you!
This PR introduces a game_settings flag to unify scanning behavior. When enabled, all ships, no matter the ship class, will react the same way to all the scanning ship flags.
1) They are not scannable by default
2) Settings Scannable makes them.. uh.. scannable and cargo will be revealed by default
3) A new flag available with alter-ship-flag, called no-scanned-cargo, changes the behavior to scanned/unscanned instead of revealing the cargo
4) Toggle Subsystem Scanning must be enabled to swap …
> Scanning is chaos, let's make it sane

- code/localization/localize.cpp
- code/menuui/playermenu.cpp
- code/options/OptionsManager.cpp
- code/osapi/osregistry.cpp
- code/osapi/osregistry.h
This PR fixes #5697 by changing how in-game settings are saved and loaded. The key thing Wookie and I wanted here was to have these settings saved in a way that's specific to each mod but agnostic of mod versions (as far as Knossos/Nebula goes). The challenge there is that different mod versions are entirely unique mods to FSO even though Knossos knows better.
The solution this PR offers is a new ini file saved to `%appdata/HardLightProductions\FreeSpaceOpen\data`. This file is titled based on the `Cmdline_mod` parameter (`retail_fs2_settings.ini` if it's nullptr) by trimming a mod folder's version data off of it. For example, `MPVS-4.7.2` becomes `MVPS_settings.ini` and will work for all version of the MediaVPs.
There's almost certainly room for improvement here but this needs to be …
> Ingame options respect mods

- code/menuui/optionsmenu.cpp
- code/menuui/optionsmenu.h
- code/menuui/optionsmenumulti.cpp
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
- code/pilotfile/csg.cpp
- code/pilotfile/plr.cpp
This PR moves the methods to set the serialized values for options into OptionsManager for more global use. Then it removes the check for `Using_in_game_options` from csg.cpp and plr.cpp and instead always loads the player or campaign options and then runs those OptionsManager methods to make sure the serialized values are kept in sync for the UI.
I know @notimaginative was concerned about multi options, but the only one I could definitively find that's saved to the player file was the Local Broadcast setting. Let me know if I missed one, though, and I can add it here.
> Allow player-specific options even when using In-Game Options

- code/scripting/lua.cpp
Increases overall safety by preventing lua from executing malicious code.
We actually do this kind of securing for the os library already, but the io library has similar issues.
We don't want to disable all io though, so apply some fairly restrictive filtering as to what can be opened.
Tested to work with scripts that use the io lib
> Increase Lua safety

- code/ai/aiturret.cpp
- code/parse/sexp.cpp
- code/ship/ship.cpp
- code/weapon/beam.cpp
This makes it so that the $Shots parameter, normally used for multishot weapons like shotguns (not to be confused with +shots, a beam info parameter used for antifighter beams), works correctly for beam weapons.
Multishot beams now work properly if they're fired normally from turrets, fired using the fire-beam SEXP, or fired as fighter primaries.
For Type 5 beams, the +burst rotation pattern will advance for each shot fired simultaneously, in addition to advancing between shots in a burst, allowing a modder to have beams which fire several shots in a pattern. This was previously possible using beams spawned as submunitions or from subspace, but now it works for beams fired normally. (This was the main reason I wanted this feature.)
I also modified the use of the burst rotation pattern so …
> Make the $Shots parameter work for beams.

- code/def_files/data/effects/msaa-f.sdr
In rare cases before a background with a position value of 0,0,0 (i.e., model-less, emissive background), the MSAA shader could produce unwanted glints.
This was mostly apparent when using cockpits with deferred lighting and MSAA, as the entire background scene was rendered as a model-less emissive.
Previously, the shader would just hard-set the texel weight to 1 when the median distance was 0 to actually render-in background at dist 0, but evidently, it cannot set the weight to 1 for texels that don't conform to that median. By making sure that this only applies to texels whose individual distance is 0, similar to the median distance, this problem is avoided.
Also fix that the alpha channel of the normal buffer, used for gloss, should obviously not be part of the normalization process …
> Fix edge case in MSAA shader

- code/menuui/mainhallmenu.cpp
Fixes #6008 by moving the log warning out of main_hall_do and into main_hall_init
> Prevent printing a warning every frame

- code/hud/hudmessage.cpp
- code/mission/missionlog.cpp
- code/mission/missionlog.h
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/missionlog.cpp
- code/scripting/api/objs/missionlog.h
Change the mission log from a static array to a dynamic vector.  This removes any chance of the mission log running into a limit (as regularly happened with the last mission of Shepherds before the limit bump) and also prevents strange mission bugs caused by culling obsolete entries.
This also unifies the API a bit by renaming the public `message_log_` function prefixes to `mission_log_`, removing the redundant `Num_log_lines` variable, and removing `Log_scrollback_vec` from the header.
Implements #5878.
> make mission log dynamic

- code/def_files/data/tables/objecttypes.tbl
The new `ai-disable-ship-tactical` and `ai-disarm-ship-tactical` goals were inadvertently omitted from the ship type default table, causing these goals to not be available in the Event Editor drop-down menu or Ship Editor initial orders.  Testing did not catch this because testing was done using the HUD squad message system which assigned the new goal (if the flag is enabled) without explicitly checking the validity.
Follow-up to #5512.  Fixes #6189.
Also add the attack-ship-class goal as valid for player orders in the places where it is valid for regular orders.
> make sure 'tactical' variants of disable and disarm are allowed

- code/cfile/cfilesystem.cpp
Always log the possible shadow if:
1) it's a critical file
2) it's in the same root
Otherwise log it behind a debug filter ("CFileSystem").
> limit debug log spam from file shadows

- code/scripting/api/objs/model.cpp
- code/scripting/api/objs/model.h
Previously, a model API existed for glow points mounted on thrusters, but not glow points mounted on glow point banks.  This adds glow point bank support.  Also, this refactors and cleans up the implementation of the model API a bit.
Depends on #6100; ~~in draft until that is merged.~~
> add API for glow point banks

- code/network/gtrack.cpp
- code/network/gtrack.h
Should allow for most games, even those behind CG-NAT, to work without having to set up port forwarding. This set of changes is only needed for game servers to work with the new feature. No special handling is required for clients, so any build from the last few years should work for them.
> add support for PXO's UDP hole punch feature

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/model/model.h
- code/network/multi_ingame.cpp
- code/network/multi_interpolate.cpp
- code/network/multi_interpolate.h
- code/network/multi_obj.cpp
- code/network/multi_obj.h
- code/object/collideshipship.cpp
- code/object/object.cpp
- code/object/object.h
- code/object/waypoint.cpp
- code/physics/physics_state.cpp
- code/physics/physics_state.h
- code/ship/ship.cpp
- code/source_groups.cmake
- freespace2/freespace.cpp
This creates a (very small) api for linear interpolation between two recorded positions, velocitites, and desired velocities and moves multiplayer over to that system.  Now that it is generalized, other games systems (esp. weapons fire) can now use this code to temporarily set an object's position to what it would be between frames.
In draft pending testing.
> Generalize linear interpolation

- code/network/gtrack.cpp
The header length from the tracker is 1 byte larger than the size calculated by the client due to psnet removing that byte internally. The header length is adjusted to compensate for this, but only *after* the deserialization process, so we have to use the received packet size instead.
> fix data length bug in PXO hole punch packet

- code/mission/missionparse.cpp
Break when you've found a match, instead of just mindlessly comparing the rest.
This is technically just an optimization and safety change, but if the inner and outer loops had been switched, it would have set the wrong flag if two copies of the same flag were listed in the mission file.
> Simplify logic here

- code/def_files/data/effects/volumetric-f.sdr
- code/globalincs/pstypes.h
- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/util/uniform_structs.h
- code/nebula/volumetrics.cpp
- code/nebula/volumetrics.h
- code/tracing/categories.cpp
- code/tracing/categories.h
Since voluemtrics are starting to see some actual use, it's time to grab some of the low-hanging fruit for performance.
Notably, previous volumetrics would raymarch until the opacity of the nebula trended towards maximum.
That is evidently bad for any pixel that is outside of the actual nebula, but within the area where the nebula needs to be tested for. These parts would require many, many samples, so especially sparse nebula that needed many steps were really really slow.
This improves on this by supplying the shader with an unsigned distance function of the volumetrics. Essentially, the shader is able to increase its nebula query step-size to x if it knows, that the nebula will not change within this distance x. 
In addition, as this makes the stepsize dynamic, it allows to fix the …
> Improve Volumetrics Performance

- code/menuui/playermenu.cpp
- code/osapi/osregistry.cpp
Fixes #6193 by adding a bool check for if the popup has been displayed and fixes #6194 by adding a null check. If the file couldn't be created then default to the old fs2_open.ini instead.
> Fix ingame options init bugs

- code/asteroid/asteroid.cpp
The Unlimited Asteroid/Debris Field Types & Subtypes PR (#6021) updated to using vectors to allow for unlimited asteroid and debris types. That update removed the count field, `num_used_field _debris_types`, which counted both asteroids and debris pieces (even though the name only has debris in it). The counter variable was removed in favor of `.size()` but now both asteroid and debris field sizes needed to be checked, so this PR updates the code to account for that. Allows asteroid fields to properly pass the count check and properly again spawn in mission.
Tested on asteroid fields passive and active along with debris fields (both created from sexps and the asteroid mission editor) and everything now works as expected. Also tested on missions with no fields and those also still work as …
> Follow-up to asteroids update #6021

- code/mission/missionparse.cpp
When a new mission is loaded, clear the parse names vector, in lieu of the old `Num_parse_names = 0;` line.  This fixes a bug where FRED will complain about nonexistent ships when loading a different mission.  Follow-up to #5937.
> clear Parse_names on mission init

- code/graphics/2d.cpp
This is kind of an ugly hack by forcing a backbuffer copy. The performance cost should be more or less negligible.
No idea _why_ it is a problem for us to directly render to the backbuffer, but it seems to be one.
As far as we're aware, the problem is limited to Win11 and possibly nvidia cards.
Similarly, _any_ sort of buffer between our rendering and the final thing that gets sent to the screen seems to fix the issue as well. This includes a buffer by the window compositor when FSO is windowed, a buffer for overlays by renderdoc and similar tools, our own buffering, etc.
Fixes #6197.
> Prevent SCPUI flicker on Win11

- freespace2/freespace.cpp
This is another instance where our internal options system is prone to having things optimized out by the compiler if referencing the controlling global variable directly. So we have to go through the options system to retrieve the value instead.
Fixes #6167
> Fix screenshudder option issue

- code/ship/ship.cpp
#6187 fixed transparency for cockpits, but the positioning for deferred lighting alas fell through the cracks. This PR fixes that and allows deferred lighting in cockpits to once again work as intended.
Tested and fix works as expected.
> Followup to #6187

- code/mission/missionmessage.cpp
Fixes #6168 by adding an explicit check for paused messages. If they are paused then we shouldn't kill them.
> Don't kill paused messages

- code/gamesnd/gamesnd.cpp
- code/scripting/api/objs/sound.cpp
Patches the gamesnd system in several ways to properly fix the bug identified in #6196.  Due to the way the new sound system was written, sounds with numeric IDs were not necessarily added in their indexed location, even though the code assumed (even prior to #6112) that this would be the case.  The code now uses the proper index for both old *and* new style sounds.  This is done by ensuring, in `gamesnd_parse_entry()`, that the vector contains an entry for the specified numeric ID before doing a search for that ID.
Due to the slightly modified population of the gamesnd vectors, the `Snds_iface_handle` vector is now populated after parsing the various sounds.tbl files rather than during parsing.
Separately, this makes consistent the handling of the `sound_entries` vector which could …
> properly handle game sounds with numeric IDs

- code/io/keycontrol.cpp
- code/mission/missionmessage.cpp
- code/mission/missionmessage.h
I originally wanted to do this in #6207 but decided to keep that PR trim.. so now I'm back to finish the job and satisfy my OCD a little bit.
This fixes #6208 by generally cleaning up the code surrounding message_kill_all; Change it to bool from int parameter, remove most checks for `Num_messages_playing` before calling `message_kill_all` now that it can just return instead of assert. There are a few places where I left in the additional checks to `Num_messages_playing` because they serve as nice optimization points to skip a whole bunch of other stuff that wouldn't be needed if no messages are playing; all of them part of `message_queue_process` in missionmessage.cpp.
> Cleanup message_kill_all

- code/mission/missionparse.cpp
When loading a legacy mission that contains a debris field, FSO will try to index into an empty vector, causing an out-of-bounds exception.  This can be seen by loading Derelict mission dl1-08, "The Horror in the Deep".
The `// Obsolete and only for backwards compatibility` code added in #6021 properly handles asteroid fields, but not debris fields; so the fix is simply to apply the logic to debris fields as well.
> another follow-up to #6021

- code/weapon/weapon.h
- code/weapon/weapons.cpp
This introduces a feature that allows weapons to have specialized impact particle effects that play only under particular conditions. Each conditional impact has an armor type for which it plays, and may also have minimum and maximum thresholds for health and hit angle. It can also be set as a dinky impact, to only play if the weapon isn't armed. On hit, all conditional impacts whose requirements are met will be played. Iff no conditional impacts are played, the normal impact effect or explosion will be played.
See demonstration:
[https://www.youtube.com/watch?v=WobH_JkeMAo](url)
Notes:
I use a short-circuiting logical AND to check whether the hit object exists and is a ship. If the hit object doesn't exist -- which is to say, it's a nullptr -- trying to access it (by checking whether …
> Adds conditional impact functionality.

- code/parse/parselo.cpp
- code/parse/parselo.h
This will be useful for situations where a missing lookup entry is not valid but nevertheless does not merit a warning.
> enhance stuff_int_list to allow turning off the warning

- code/io/keycontrol.cpp
- code/io/keycontrol.h
- code/parse/sexp.cpp
- code/playerman/player.h
- code/playerman/playercontrol.cpp
- freespace2/freespace.cpp
Adds an optional argument to the `lock-perspective` sexp to allow locking of the 'free look' or 'padlock' view.  This prevents the player from looking around which might not be desired in certain forced perspective situations.
> enhance lock-perspective to also lock slew mode

- code/cmdline/cmdline.cpp
- code/cmdline/cmdline.h
- code/fireball/warpineffect.cpp
- code/graphics/post_processing.cpp
- code/starfield/starfield.cpp
- code/weapon/shockwave.cpp
- code/weapon/shockwave.h
- freespace2/freespace.cpp
24.2 introduces the in-game options menu officially and as long as we are retraining our player base we might as well rip the band-aid clean off.
This PR deprecates many of the commandlines in favor of using the in-game options menu. This only affects options that do not require a restart. Notably this PR also fixes a couple options that claimed to need a restart but actually don't.
Warp Flash and Motion Debris worked right away without requiring a restart. 3D Shockwave required a slight alteration to make sure the next mission doesn't use the previously loaded values and instead loads the new ones.
Fixes #6205
> Deprecate some commandlines and make some options not require restart

- code/hud/hud.cpp
- code/hud/hud.h
- code/hud/hudparse.cpp
- code/parse/sexp.cpp
- code/ship/ship.cpp
Adds a method to assign HUD gauge configs in ships.tbl for each ship rather than using the $Ships() setting in hud_gauges.tbl. This has the distinct advantage of being more modular and a little more clear to how we generally table things in FSO.
Also fixes a sexp error checking bug that would flag any custom gauge not assigned to the player ship as possibly invalid despite the fact that the player ship could change during loadout. Here we should just validate that the gauge exists at all, not that it's assigned to a specific ship.
> Assign hud in ships.tbl

- .github/workflows/weekly-coverity-scan.yaml
Per @notimaginative, change the `compiler` variable to uppercase to match its usage in the rest of the file.  This should allow the coverity task to start running again.
> fix coverity task

- code/nebula/neb.cpp
Follow-up to #6072. Zero vec, the default, means no alignment, and random directions. I just.. it's been... 
I don't want to talk about it anymore.
> fix poof alignment

- code/pilotfile/csg.cpp
In current master, the debug log commonly shows `CSG => Warning: (0x0011) Short read, information may have been lost!`.
Thanks to @notimaginative for pointing the following issue out: The function `pilotfile::csg_read_redalert()` returns if `ship_list_size` is zero, but it still needs to check the `wing_list_size` a bit below that. This has likely not caused data loss issues ATM, because it's reasonable to assume that if `ship_list_size` is zero then so is `wing_list_size`. But it's still a bug and should be fixed before it does cause some real data loss.
This PR moves the relevant read sections to within each respective if-block. That way the function is capable of checking both `ship_list_size` and `wing_list_size` on every load (even if `ship_list_size` is zero).
> Fix `short read` error with red alert csg file reading

- code/asteroid/asteroid.cpp
- code/cfile/cfilesystem.cpp
- code/controlconfig/controlsconfigcommon.cpp
- code/cutscene/ffmpeg/SubtitleDecoder.cpp
- code/decals/decals.cpp
- code/gamesnd/gamesnd.cpp
- code/globalincs/undosys.cpp
- code/hud/hudparse.cpp
- code/lab/dialogs/lab_ui.cpp
- code/lab/dialogs/lab_ui.h
- code/math/curve.cpp
- code/mission/missionparse.cpp
- code/mission/missiontraining.cpp
- code/parse/parselo.cpp
- code/parse/sexp.cpp
- code/parse/sexp/sexp_lookup.cpp
- code/particle/ParticleManager.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/model.cpp
- code/scripting/scripting.cpp
- code/scripting/util/LuaValueSerializer.cpp
- code/ship/awacs.cpp
- code/ship/ship.cpp
- code/stats/scoring.cpp
- code/weapon/beam.cpp
- code/weapon/weapons.cpp
Fix, or mark as false positive, several issues flagged by Coverity.
* using `std::move` instead of copying, and change some parameters from value to reference
* fix or mark potential copy-paste mistakes
* various checking of parameter and return values
* miscellaneous fixes, and change some 'intentional' markers to 'false positive' markers
> Several coverity fixes

- ci/linux/clang_tidy.sh
It has since broken due to git permission shenanigans.
> Fix clang-tidy

- .clang-tidy
- ci/linux/clang_tidy.sh
We also need to update the actual version we're calling.
In accordance to this, this PR also disables a few warnings that were added since clang-tidy 9 that are potentially problematic / annoying for the SCP without large-scale refactoring of how we do things.
Also removes deprecated AnalyzeTemporaryDtors key.
> Fix clang tidy again

- code/sound/ds.cpp
- code/sound/ds.h
- code/sound/sound.cpp
Our sound code is extremely confusing, so it's no wonder that the author of these functions could not find snd_get_sound_id, which is the handle into the Sounds vector.  And it's no wonder that it was missed in review either.
Also some cleanup in the main function that was causing #5899 
Fixes #5899 
EDIT: By the way, I would love if someone could double check my tests and make sure doors are working as they are supposed to.
> Fix unreliable Sounds index retrieval

- code/globalincs/systemvars.cpp
- code/graphics/2d.cpp
- code/nebula/neb.cpp
In `strings.tbl` the graphics settings localization IDs are as follows: 1160, "Low"
1161, "Medium"
1162, "High"
1163, "Very High"
These values are used throughout the code, but in some cases with SCPUI upgrades, the IDs got off by 1. This PR fixes those incorrect IDs.
> Fix Settings Localization IDs

- code/globalincs/utility.h
- code/math/curve.cpp
- code/particle/ParticleEffect.h
- code/particle/ParticleManager.cpp
- code/particle/ParticleManager.h
- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/VolumeEffect.cpp
- code/particle/effects/VolumeEffect.h
- code/particle/particle.cpp
- code/particle/util/ParticleProperties.cpp
- lib/antlr4-cpp-runtime/runtime/src/tree/xpath/XPathLexer.cpp
- parsers/action_expression/generated/ActionExpressionLexer.cpp
- parsers/action_expression/generated/ActionExpressionParser.cpp
- parsers/arg_parser/generated/ArgumentListLexer.cpp
- parsers/arg_parser/generated/ArgumentListParser.cpp
I took a close look at the code involved in parsing particle tables.  There is no smoking gun, but there are several ways to polish the code which I have implemented here.  The most likely culprits for the slowdown, IMO, are the repeated conversions between SCP_string and C-string, especially in `ParticleManager::getEffectByName()`; followed by the omission of `std::move` in several places.
Addresses #6010.
> address 6010

- code/hud/hudtarget.cpp
- code/hud/hudtargetbox.cpp
- code/jumpnode/jumpnode.cpp
- code/lab/renderer/lab_renderer.cpp
- code/menuui/techmenu.cpp
- code/missionui/missionscreencommon.cpp
- code/missionui/missionscreencommon.h
- code/model/model.h
- code/model/modelinterp.cpp
- code/model/modelrender.cpp
- code/model/modelrender.h
- code/ship/ship.cpp
- code/ship/ship_flags.h
- code/ship/shipfx.cpp
- code/starfield/starfield.cpp
- code/starfield/starfield.h
- code/weapon/weapons.cpp
- fred2/fredrender.cpp
- qtfred/src/mission/FredRenderer.cpp
Add a ship flag and an MR flag to turn rendering on and off.  Also standardize the type for MR flags to be uint64_t so that the new flag will fit.
Fixes #6062 
Note: (1<<32) and above causes UB, so I just put the value and put the bitshift in the comments.
> Fix Insignia Checkbox in the Lab

- code/object/collideweaponweapon.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Follow-up to #5595. As flagged by coverity, the previous PR took two conditions, one using `max_lifetime - lifeleft` and the other using `lifetime - lifeleft` and merged them into a single case `Missiontime - time_created`, which as mentioned there *is* more robust but in practice mostly matches the behavior of `max_lifetime - lifeleft`. What is the difference between `max_lifetime` and `lifetime`? It was removed in #5753 but it was very simple and not used for much
```
if (wip->is_locked_homing()) {
// locked homing missiles have a much longer lifespan than the AI think they do
wip->max_lifetime = wip->lifetime * LOCKED_HOMING_EXTENDED_LIFE_FACTOR; // this is 1.2f
}
```
Essentially, original handling was that bomb invulnerability time was extended by 20% of the weapon's lifetime. So in …
> Bug fix for aspect invulnerability timing... again

- .github/workflows/weekly-coverity-scan.yaml
This prevents Coverity from running on any forked repository, by default; both because the workflow will fail, and also because the workflow's results would be identical.  (Any forked repository can, of course, change this within its own scope.)
> only run the Coverity workflow on the SCP repository

- code/popup/popup.cpp
- code/popup/popup.h
In retail, the processing of certain keys during a popup, in the `popup_process_keys()` function, was dependent upon the `PF_ALLOW_DEAD_KEYS` flag.  This flag was never used in retail, causing the if() block to be marked as dead code.  In a4e623db23, the dead code warning was addressed by removing the dependency on `PF_ALLOW_DEAD_KEYS`, which is incorrect.  The "dead keys" should only be processed during the "dead popup".  Since the "dead popup" was moved to its own de[a]dicated "popupdead" section, the "dead keys" processing can be entirely removed from the "normal popup".
Fixes a bug noticed by @PremiumColt where certain keys, especially the time compression keys, were processed while the ESC popup was active.
> fix incorrect processing of keys during ESC popup

- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/ai/aicode.cpp
The somewhat modern AI flag for `Require_exact_los` is extremely useful in multiple different situations, for example making large capital ship weapons not fire into friendly surrounding ships on accident. When the feature was added, the `check_los` function was provided with a default value of `10.0` meters for minimum radius detection. This PR exposes that value to modders so they can set it to a reasonable value depending on the ship sizes of their specific needs (for example, modders may not want to incur the cost of checking LoS on every small ship that is zipping around and instead use the LoS check only to avoid firing if a large capitial ship is in the firing path). And as a note, the los value just uses a simple numerical comparison check, so the los detection could be set to a …
> Expose Minimum LoS Detection Radius

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
Since guards going after a ship which is threatening their charge is an implicit attack order, it should be subject to the protected flag like all other similar situations, otherwise they'll chase but not fire (protected also stops firing) at the ship. 
This is definitely a bug, and an uncommon one, which is almost certainly not present in retail, but better to err on the side of caution with AI so I made it a flag targeting new versions.
> Ensure guards ignore protected attackers

- code/io/timer.cpp
- code/scripting/api/objs/subsystem.cpp
Changes `NextFireTimestamp` to work as advertised.  Fixes #6256.
EDIT: Also handles special timestamp values in `timestamp_until()` and `timestamp_since()`.
> fix `NextFireTimestamp`

- code/hud/hudtarget.cpp
- code/math/vecmat.cpp
- code/math/vecmat.h
- code/render/3ddraw.cpp
- code/render/3dmath.cpp
According to DahBlount:
> Most atan2 implementations for a long time had problems when the inputs were close to machine epsilon or when x was less than or equal to 0
And according to z64555:
> Modern versions of C++ should have an atan2() that works correctly when the inputs are at 0 or near epsilon of the floating point specification, meaning Volition's workaround shouldn't be needed anymore.
So this removes `atan2_safe` and changes all instances to `atan2`.  Consequently, the angle range in FRED now shows as [-180, 180] as expected.
Fixes #3730.
> change atan2_safe to atan2

- code/io/timer.cpp
The time since an invalid timestamp should be INT_MIN, not INT_MAX.  Follow up to #6258.
> fix copy-paste error in timestamp_since

- code/menuui/barracks.cpp
- code/menuui/barracks.h
- code/scripting/api/libs/ui.cpp
There are some actions in SCPUI barracks menu that can cause Player to get set to nullptr and there's currently no way to accept a player without also returning to the mainhall. This should never have been a combined action but m!m didn't have that kind of foresight in 2018.. so here we are.
An optional parameter that allows skipping returning to the mainhall as part of this function which is only used by the API. This will allow me to fix a bug in SCPUI where Player gets left as nullptr.
I should clarify that the only code that runs `barracks_accept_pilot` is the Lua API. The retail UI runs `barracks_pilot_accepted` instead.
> Allow accepting a pilot without changing gamestate

- code/object/object_flags.h
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/ship_flags.h
- code/weapon/weapon.h
- code/weapon/weapons.cpp
This adds per-weapon convergence features, notably allowing per-weapon autoaim + convergence. I moved the autoaim flags to Object:: from Ship:: so they could be reused. Seemed the most sensible place.. but could go elsewhere if there's a better spot.
While technically a new feature, this allows BtA to fix an issue with one of our weapons.. so really hoping to get this in for 24.2.
Fixes #4947
> Per weapon auto convergence

- code/scripting/doc_html.cpp
- code/scripting/doc_json.cpp
- code/scripting/lua.cpp
- code/scripting/scripting_doc.h
What it says on the tin. Prints in-game options title, key, & description to scripting.html and scripting.json
Fixes #6222
> Print in game options data to scripting output files

- .clang-tidy
As seen in #6265, our SEXP tree is evidently implemented as a recursive tree iterator, and clang just flags any change to that as a result.
> Disable clang misc-no-recursion

- lib/SDL2.cmake
The pkg-config name for SDL 2 is lowercase 'sdl2', and it was passed in upper-case so the proper library was never detected on Linux (and it would fall back to downloading the prebuilt version). Fix the name.
> Fix SDL2 pkg-config name

- code/sound/sound.cpp
Reported and fix tested by FotG team:
Missing this logic and assignment in the sound code would cause a crash in specific circumstances.  When a sound file was used more than once in the Sounds table, the sound entry was not being populated with the index to the `Sounds` array.  Later on, when we attempted to access the `Sounds` array to play the sound, the unpopulated index entry was found, triggering an assert.
AFAICT, this buggy behavior was exposed when other sound code was fixed and started accessing the correct field which again, is that same index into the `Sounds` array.
> Fix a sound crash

- code/globalincs/pstypes.h
- code/object/object.h
- code/parse/sexp.h
- code/scripting/ade_api.h
- code/scripting/ade_external_serializer.h
- code/scripting/api/objs/bytearray.h
- code/scripting/api/objs/enums.h
- code/scripting/api/objs/gameevent.h
- code/scripting/api/objs/gamestate.h
- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/oswpt.cpp
- code/scripting/api/objs/parse_object.h
- code/scripting/api/objs/subsystem.h
- code/scripting/api/objs/vecmath.cpp
- code/scripting/api/objs/vecmath.h
- code/source_groups.cmake
Previously, RPC serialization methods were picked as follows:
1. If the lua object is marked as NO_MULTI (which is sensible for things that aren't synchronized on each client), don't allow serialization
2. Does the underlying C-type of the specific lua object have a ``serialize`` method, if so, use it.
3. Is the underlying C-type a fundamental type, then use builtin fundamental serializers.
4. If no serializer is available, don't allow serialization.
This had some issues for types that needed to be serializable, but were not constrained to the scripting code. These types, such as vec3d, the oswpt type, or object_h (which probably _should_ be constrained to the scripting code, but that's another can of worms), needed to have an ugly, scripting-API-specific serializer method.
This PR …
> Slightly clean up RPC API

- code/model/model.h
- code/model/modelread.cpp
Model textures that are too long will cause a very unfriendly and hard-to-track down "ERANGE: String" error.  The situation can be greatly improved by checking the string length ahead of time, printing a friendly Warning, and truncating the filename.  This will alert the modder to the source of the problem while also allowing gameplay to continue.
> improve model texture parsing

- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/SingleParticleEffect.cpp
- code/particle/effects/VolumeEffect.cpp
- code/particle/util/EffectTiming.cpp
- code/particle/util/EffectTiming.h
Previously, particle effects from -part.tbm could be spawned more than once per frame, but this would only result in the particles clumping up at the spawner's position each frame. Smoothly spawning many particles along a fast-moving object's path was impossible. This PR makes it so that particles spawned between frames are placed partway along the spawner's trajectory in accordance with spawn timing, with millisecond precision.
Limitations:
- For now, this applies only to the "object" source type, so it won't affect particles spawned from beams or as trails from other particles. I intend to extend it to beams in the future, but that will be slightly more complicated so I'm leaving it off for now. I'm not sure it's even worth doing for the particle source type -- particles don't store …
> Interpolate particle spawning positions for moving spawner objects

- code/object/collideweaponweapon.cpp
- code/weapon/weapons.cpp
This is a follow up to [#6218](https://github.com/scp-fs2open/fs2open.github.com/pull/6218), and makes a few changes.
First, I switched the ordering of a couple of the table lines. Previously, the armor type came first, then the effect name, then the other conditions. However, the armor type is a condition, whereas the effect is what happens when the conditions are met, and I thought that each of those things should be clustered. So now, the effect name goes at the end.
This is modder-facing, but the feature was merged like a week ago and I would be very surprised if anyone had used it yet, so I expect it'll be fine.
Second, I added support for conditional impacts when hitting weapons (such as bombs). This got a little thornier than I anticipated, and required making a significant change …
> Conditional Impacts followup

- code/mission/missiontraining.cpp
Fix units are denominated in seconds, while timestamp units are denominated in milliseconds.  This fixes the directive timing check which, after the timestamp upgrade, would time out after 5 and 7 milliseconds instead of 5 and 7 seconds.
Follow-up to #4633.
> fix a minor bug with directive marking

- code/parse/sexp.cpp
- code/parse/sexp.h
As noted on Discord, there was previously no `is-species` operator.  Now there is.
As a bonus, this also fixes a bug where the pre-existing `is-iff` operator did not work with wings that had not yet arrived.
Tested and handles all possibilities.
> add is-species SEXP operator

- code/scripting/api/objs/wing.cpp
There was scripting support for wing arrival/departure delays, but not for wave delays.  Now there is.
> add scripting support for wing wave min/max delay

- code/hud/hudtarget.cpp
This fixes an edge case in the Average and Multiple modes, where secondary lead indicator rendering was skipped by continue statements when the primary weapons were out of range.   I also added some comments that help people actually understand what this function does as it is very confusing.
Also this remove the return on the else.  I have looked over this function for a long time.  It doesn't need the return because that return will be reached when there are no valid primary weapons, but everything after it only has to do with secondary weapon indicator rendering.
I did test it, but I could use some independent verification that this didn't break any indicator behavior, although it really shouldn't.
Fixes #5088
> Fix renderLeadCurrentTarget

- code/ai/aibig.cpp
- code/ai/aiturret.cpp
- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
- code/particle/ParticleSourceWrapper.cpp
- code/particle/ParticleSourceWrapper.h
- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/SingleParticleEffect.cpp
- code/particle/effects/VolumeEffect.cpp
- code/particle/util/ParticleProperties.cpp
- code/particle/util/ParticleProperties.h
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- code/weapon/beam.cpp
- code/weapon/weapons.cpp
This allows modders to specify a three-dimensional offset for a tabled particle effect, whereupon the position of the effect will be modified accordingly. This should work for effects spawned from objects, particles, vectors, and beams.
The offset is relative to the spawner's orientation. Unfortunately, this only works fully for objects. Other spawner types have a direction vector, but not a full orientation matrix, so in those cases the x and y axes are undefined. (In practice this seems to mean that they end up sort of pointed toward the global orientation to the extent that's possible.) This includes weapon hit effects, which are spawned from vectors, not the weapon object.
In future I would like to address this by adding an optional orientation field to SourceOrigin, which can then be …
> Add offset for tabled particle effects

- code/scripting/ade_external_serializer.h
- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/oswpt.cpp
- code/scripting/api/objs/vecmath.cpp
Prevent compiler warnings caused by the `value` parameter of the external serializers hiding the `value` member of `std::integral_constant`.
Follow-up to #6276.
> parameter deconfliction

- code/globalincs/utility.h
- code/osapi/dialogs.cpp
- code/scripting/ade.cpp
- code/scripting/ade.h
- code/scripting/ade_args.cpp
- code/scripting/ade_args.h
- code/scripting/api/libs/base.cpp
- code/scripting/api/objs/file.cpp
The return value of `lua_tostring()` is NULL if (and only if) the string conversion failed.  Many places in the code did not check for this situation, which led to the crash in #6290.
Fixes #6290.
> safety check for lua_tostring()

- code/hud/hudtarget.cpp
Under some very odd scenarios the math for doing an offscreen indicator might not get a valid position, but there's 0 reason to `int3()` about it.
Users *have* run into it, and I have not investigated it, but Mjn has to some extent: "This is something with 4k resolution. I suspect an actual engine bug. Something about BtA is causing xpos in the HudGaugeOffscreen::calculatePosition to be larger than 0.. at least in my reproductions.. and that is not expected."
But if this is a matter of an errant frame or two, I'm not sure trying to keep this around is worth the hassle. In both cases, the function will simply abort and not render the indicator.
> Remove some int3s from offscreen indicator drawing

- code/lighting/lighting.cpp
It requires restart to change, so even checking it every frame would be excessive. Added a comment to document this issue if deferred lighting is switched to a runtime changeable value.
Effectively resolves #6287 entirely, from the data I see so far.
> Stop constantly rechecking the options value for deferred lighting

- code/options/Option.cpp
- code/options/Option.h
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
This cleans up an old TODO and addresses(partially) #6287. Exceptions are no longer routine for unset options, but other exception sources are possible in getting options so the handling is still present.
I have run the game with these changes and it still appears to function properly in general and respect my options and defaults, but if there's any in-depth stress testing of the options manager that should be undertaken to verify it I am unsure what it would be.
> Switch options manager from signaling empty keys with exceptions to use optional<> 

- code/mission/missiontraining.cpp
FSO should, based on code comments and common sense, display the five must current directives. But, if there are directives older then that which are still active, then these should be preferred over the oldest directives that are already completed and still shown.
Unfortunately, the logic to do that has been bugged since retail, but since you need an active directive that's sixth oldest or older to notice the issue, it probably slipped past so far.
The issues with the prior logic were:
- Usage of an incorrect loop iterator variable, resulting in replacement of the n-th shown directive in order to display the n-th older-but-active directive, regardless of the state of shown directives.
- Since the directive that is shown instead of the replaced directive is older than all other …
> Fix sorting of older but active directives

- code/weapon/weapons.cpp
On current master I was hitting a CTD when firing a weapon with a shockwave at close range (ie player is within the shockwave zone). This code is part of the new friendly fire feature from #6265. The minidump showed `other_obj` was `null`, so this PR adds some safety checks.
Tested and this fixes the crashes.
> Fixes CTD with new Friendly Fire Feature

- code/graphics/2d.cpp
Fix several compilation warnings related to templates by properly casting these values.  See also the existing example that uses casts in cmdline.cpp.
> fix template warnings when compiling 2d.cpp

- code/math/vecmat.cpp
- code/particle/effects/GenericShapeEffect.h
- Normal-based particle effects being spawned in a situation with no normal is a totally expected situation with a totally reasonable fall back. For instance, a weapon impact effect which spawns a particle as though it were 'bouncing' off its target would generate this warning everytime it detonated without hitting anything.
- Null vectors being normalized was definitely more a concern the developers had while developing, now, scripters can call this function directly, so it can certainly not be assumed and once again, has reasonable (and obvious, to a possibly concerned scripter) fallback
Most importantly of all, both of these situations can happen numerous times, and can REALLY clutter the log. I'm open to `nprintf` instead, but I don't think they're necessary.
> Remove some overzealous prints

- code/weapon/weapon.h
- code/weapon/weapons.cpp
Per discussion in #6302, this PR renames `other_obj` to `impacted_obj` to minimize confusion
> Cleanup variable name in `weapon_do_area_effect` function

- code/scripting/api/objs/weaponclass.cpp
`SwarmInfo` was trying to return `SwarmWait` as a float, when it was actually an integer, tripping an assertion.
> Fix WeaponClass.SwarmInfo

- fred2/fredview.cpp
When the Show Waypoints option is toggled, the marking was not updated as it was for the other options (Show Ships, Show Starts, Show IFFs).  Fix this by calling `correct_marking()`.
> fix waypoint marking

- code/menuui/readyroom.cpp
This is an error that existed all the way back in retail.  Each line in the simulator room (i.e. each mission name in the list) is also a "button" in the sense that clicking on it will highlight the line and set some values.  The maximum number of buttons is `LIST_BUTTONS_MAX`, but the maximum number of `sim_room_lines` was a different #define, `MAX_LINES`.  This was set to 200, a far higher value than the `LIST_BUTTONS_MAX` value of 42.  The code responsibly checked the limit, but the limit was incorrect.
(This had not been seen in previous mods because the number of lines was never high enough to reach 42.  BWO happened to use a font that was small enough to fit that many lines in the mission simulator screen.  This explains why removing fonts.tbl prevented the bug from occurring.)
Thus …
> fix the mysterious crash in BWO

- code/object/object_flags.h
- fred2/fred.rc
- fred2/fredrender.cpp
- fred2/fredview.cpp
- fred2/fredview.h
- fred2/resource.h
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/mission/EditorViewport.cpp
- qtfred/src/ui/FredView.cpp
- qtfred/src/ui/FredView.h
- qtfred/ui/FredView.ui
Add options to the Edit menu to lock and unlock objects.  Locked objects cannot be selected or dragged.  They can still be edited in the various editors (e.g. Ships, Objects) but not in the main viewing area.
Also add the Selection Lock option to the Edit menu.  It was previously available in the toolbar but this provides another way to access it.
> add option in FRED to lock objects from being edited

- code/io/timer.cpp
- code/io/timer.h
- code/network/multi_obj.cpp
1. Make sure the legacy `timestamp_until()` and `timestamp_since()` functions check for any type of invalid timestamp
2. Add a useful `isFinite()` function
3. A timestamp delta on an immediate timestamp is more properly the actual delta, rather than another immediate timestamp
> some timestamp refinements

- code/decals/decals.cpp
- code/decals/decals.h
- code/gamesnd/gamesnd.cpp
- code/math/curve.cpp
- code/math/curve.h
- code/nebula/neb.cpp
- code/nebula/neb.h
- code/particle/effects/ConeShape.h
- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/SingleParticleEffect.cpp
- code/particle/effects/SingleParticleEffect.h
- code/particle/effects/VolumeEffect.cpp
- code/particle/effects/VolumeEffect.h
- code/particle/util/EffectTiming.cpp
- code/particle/util/EffectTiming.h
- code/particle/util/ParticleProperties.cpp
- code/particle/util/ParticleProperties.h
- code/sound/sound.h
- code/utils/RandomRange.h
This PR 1. adds support for probability distributions defined by curves and 2. allows all tabled instances of uniform random ranges to use uniform, normal, or curve-based ranges (without breaking backwards-compatibility, of course).
@Baezon will probably want to see this.
> Generic random distributions, including curve-based

- code/iff_defs/iff_defs.cpp
- code/iff_defs/iff_defs.h
- code/localization/localize.cpp
Adds a feature BtA wanted that I completely forgot about until today. This enables an new in-game option to enable Accessibility colors for IFFs. The colors are basically overrides of the normal colors and are defined in the iff_defs.tbl in the same way as regular colors. If Accessibility Colors are enabled then those are the colors returned whenever an IFF color is requested from anywhere.
This requires mods to opt-in and fully support the feature. As such, there is a global toggle `$Accessibility Supported:` in the iff_defs.tbl. This is false by default and if it is false the Accessibility option will not even show in the in-game options menu. It must be explicitly enabled and colors defined.
> Accessibility IFF colors

- code/missionui/redalert.cpp
- code/ship/ship.cpp
Fixes part of the cause of a crash reported on discord.  This is now very unlikely to happen, but everywhere else in this function checks that `p_objp` is not null before dereferencing.  Also, while working on this, goober and I saw that the current wave was sometimes exceeding the wave count of the second mission, so fix that as well.
Tested on the data that originally crashed FSO, and it no longer does.  Ships also properly show up as Gamma 5, Gamma 6, etc
> Fix: Always check for nullptrs and make red-alert respect cur_waves from last mission

- code/controlconfig/controlsconfig.cpp
- code/menuui/readyroom.cpp
- code/mission/missionhotkey.cpp
The BWO fix in PR #6317 was not quite the correct fix.  The `sim_room_lines` array contains the maximum number of scrollable lines, not the maximum number of lines on the screen at one time.  This partially reverts commit 20338ff28b0f483491a7bd297eb4d6293d083ef8 and implements a new fix that allows the full `MAX_LINES` but also properly checks the list button limit.  Additionally, this adds the list button limit check to other vulnerable code sections.
Fixes the tech room being limited to a single page of missions after #6317.  Testing confirms that the BWO crash is still fixed with this update.
> follow-up to BWO crash fix

- code/mission/missionhotkey.cpp
- code/mission/missionhotkey.h
- code/scripting/api/libs/ui.cpp
`Hotkey_lines` is populated whenever the screen is started, both in retail and SCPUI, so we should clear the array before we do so to make sure it's not polluted with data from past missions.
> Reset hotkey lines before populating 

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/parse/sexp.cpp
- code/parse/sexp.h
- fred2/sexp_tree.cpp
- fred2/sexp_tree.h
- qtfred/src/ui/widgets/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.h
Follow-up to #6021 which enhanced asteroid/debris fields to allow more than three types to be active at once. This PR replaces the older set-asteroid-field and set-debris-field SEXPs with the newer config-asteroid-field and config-debris-field sexps that allow selecting more than three types to be active.
One core difference here is that the sexp for Active Asteroid Fields no longer sets the field targets within the same SEXP. A new config-field-targets SEXP has been added that allows adding/removing field targets arbitrarily which actually ends up being kind of a nice side-effect upgrade to the whole system.
The old SEXPs are deprecated and hidden, but still function as they used to according to my tests.
> Upgraded Asteroid Field SEXPs

- code/ship/ship.cpp
Per the comment earlier in this function, both -1 and -2 are expected values for sound indexes.  Update the sound validity check accordingly.  Fixes an assertion in `obj_snd_delete()` encountered by FotG when a sound index was -2.
> fix deletion of looping sounds

- code/gamesnd/gamesnd.cpp
- code/math/curve.cpp
- code/math/curve.h
- code/nebula/neb.h
- code/particle/effects/GenericShapeEffect.h
- code/particle/effects/VolumeEffect.cpp
- code/particle/effects/VolumeEffect.h
Fix the inadvertent swapping of the two utility functions for parsing sounds.  While we're at it, streamline a few lines, remove a few C-style casts, and remove an unused function prototype.
Follow-up to #6314.  Fixes a crash encountered by Inferno on 24.2-RC1.
> follow-up to probability curves

- code/mission/missionbriefcommon.cpp
I'm honestly not sure if this code was meant to cull icons outside the screen from being rendered or what, exactly. However at 4k resolution in SCPUI it's possible to validly have icons well outside the `gr_screen.max_w_unscaled` boundaries so we shouldn't return here in that case or those icons won't be rendered.
In fact, I don't think we should ever try and cull icons in this step because `gr_aa_bitmap()` already does that when it checks for clipping.
This may not be the right fix.. we could compare to the actual screen width and height but a lot of this code is uncommented and I'm not sure what it's all doing other than trying to scale the icon coordinates. That said, I tested this in both SCPUI and retail with icons in the middle of the map, all 4 corners and outside the map bounds in …
> Fix Briefing Icons at 4K in SCPUI

- code/mission/missionbriefcommon.cpp
Fade icons did not always match the scaling or mirror setting of their parent icon, so let's fix that.
Yes I know I add `float scale_factor` here that's not strictly necessary. However that will be used in my next PR that will create a user setting to arbitrarily scale icons up or down.
> Fix fade icons not matching parent

- code/mission/missionparse.cpp
Looking at the log of missionsave.cpp, the presence of a ship or subsystem cargo title will necessitate a minimum version of 24.1.
> update detection of save version

- code/gamesnd/gamesnd.cpp
Fix a small oversight from #6112.  In the empty/placeholder indexed sound situation, although the sound should not be appended (since it indexed), it should still be treated as a new sound, in order for all the first-parse and first-initialize logic to run properly.  Set the right value and add some comments to illuminate the logic.
> fix sound initialization

- code/gamesnd/gamesnd.cpp
1) Proactively set placeholder sounds to invalid so that SEXPs or scripts that may reference invalid sounds won't cause a crash.
2) Ensure that named sounds, whose indexes do not matter, are filled into the placeholder sound slots.  This prevents sounds from being appended into unnecessary extra indexes.  Sounds are now filled in as they were before, while retaining the previous fix of not overwriting reserved slots.
Follow-up to #6112.
> further refinement of sound fixes

- code/lighting/lighting.cpp
- code/options/Option.cpp
- code/options/Option.h
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
Similar issue to #5966.
This now provides a way to ask the option for its value instead of relying on a side effect assignment.
At the same time, this is now cached for set-once options, allowing for fast querying.
Furthermore, it gets rid of some really really ugly code throwing around raw pointers and kind of illegally managing memory in favor of shared_ptr's, as there's a good chance that that was part of why the compiler mis-identified the optimization in the first place.
Should fix #6344 
This should probably be tested in release mode by someone with an MSVC compiler.
To be frank, this is a hotfix only.
A more permanent refactor of the ingame options will be needed for 25.0 to a) optimize lookup performance, while b) not relying on side-effect access to variables that the compiler …
> Fix deferred lighting Option

- code/hud/hud.cpp
- code/parse/sexp/LuaSEXP.cpp
- code/scripting/api/objs/hudgauge.cpp
1. The `Player_ship` variable can sometimes be NULL, especially in FRED, so revise the conditional to check for this.
2. Since the `OPF_ANY_HUD_GAUGE` type checks for any default or custom HUD gauge in regular SEXP operators, it should do so in scripted SEXP operators as well.
> two HUD fixes

- code/gamesnd/gamesnd.cpp
The warning for mismatched names-and-indexes implicitly assumed that retail-style sounds would only be added with numeric indexes.  Since adding named sounds in the retail style is, in fact, allowed, update the logic to not warn in that case.
Fixes #6354.
> retail-style warning fix

- code/gamesnd/gamesnd.cpp
- code/sound/sound.h
Make sounds that are specified as "empty" or "none" in sounds.tbl ineligible for treatment as placeholder sounds.  Resolves #6350.
> allow explicitly empty sounds

- code/menuui/playermenu.cpp
Make this popup not feel like an error because it isn't one but still nudge the player to verify their settings. Fixes #6351
> Clarify options popup message text

- code/scripting/api/objs/weaponclass.cpp
Apparently virtvars can only return one value.  This deprecates the virtvars and adds function equivalents for getting weapon class swarm info and corkscrew info.  Fixes a bug reported by Woolie Wool in Discord.
(I tested both `getSwarmInfo()` and `getCorkscrewInfo()` with Woolie Wool's script.  Both work as expected and a regex search shows no other multiple-return virtvars in the codebase.)
> use functions for getting swarm info and corkscrew info

- code/def_files/data/tables/objecttypes.tbl
- code/ship/ship.cpp
The "stealth" and "fighter/bomber" ship class flags are not actual ship types, so they should never have been added to objecttypes.tbl.  Remove them from the built-in table.
Additionally, if a mod *does* use "stealth" in its own objecttypes.tbl, remove it.  This prevents the invalid "stealth" type from overriding a valid existing type, which fixes #6366.
> remove bogus ship types from objecttypes.tbl

- code/weapon/shockwave.cpp
This makes it so that the "3D"/"2D" display is actually respected in the in-game options menu, rather than just having an ambiguous checkbox labelled "Shockwaves".
It gave it the "fix" tag because it makes the in-game options menu actually respect the option's display function, the lack of which was causing users some confusion.
> Make Shockwaves in-game option force multi-value selection.

- code/model/modelcollide.cpp
TMAP2 chunks do these errors, so the TMAP case should be helpful when it happens for them too.
> Have TMAP chunks report >25 verts polygon error as well

- code/mission/missionparse.cpp
- code/ship/ship.cpp
This adds several missing initializations of cargo titles for both ships and subsystems.  Note that `Subsys_status` initialization needs to happen in `allocate_subsys_status()`, because subsystems can be allocated in red-alert or in the `ship-copy-damage` SEXP, not just parsing.
Follow-up to #6000.  Fixes a rather insidious ERANGE error in Inferno.
> properly initialize cargo titles

- code/graphics/shadows.cpp
The XSTR entry 1779 (strings.tbl) is used for two different texts:
"Disabled" in shadows.cpp;
"Toggle Auto Pilot" in controlsconfigcommon.cpp;
"Disabled" is already assigned to XSTR 413. ATM I have this set to shadow's usage (even though 413 is related to Disabled ships). Alternatively I would be happy to use `"Off", 1693`, which is what the other graphic settings use (though the actual value in the code would still remain `Disabled` of course).
Fixes #6380.
> Fix overlappig XSTRs

- code/def_files/data/tables/objecttypes.tbl
A few missions used the fighter/bomber ship type, so this adds the type back to make those missions work again.
Temporary fix for #6388.  A more proper fix will be applied after the official 24.2 release.
> add the fighter/bomber type back to objecttypes.tbl

- code/scripting/api/libs/parse.cpp
Skip to string's Lua API is currently not really usable because it returns true both if the string is found and if the string is not found. So this makes it so we only return true if it's found, otherwise return false.
> Return false if skip to string can't find the string

- code/parse/sexp.cpp
- freespace2/freespace.cpp
The enhanced controls and flags in #4552 were intended to allow the camera to shudder in all views, not just the cockpit view.  And indeed, the shudder does apply in all other views... except for cutscene cameras, due to the `VM_FREECAMERA` check in `game_render_frame()`.  So, add a separate check for cutscene cameras when shuddering everywhere.  The cutscene camera can be jittered just like the cockpit camera, but the rotation should not be modified or it will produce feedback.
Follow-up to #4552.  Also removes an unused variable that was made obsolete in #5656.
> fix camera shudder

- code/cutscene/cutscenes.cpp
- code/cutscene/movie.cpp
- code/cutscene/movie.h
- code/mission/missioncampaign.cpp
- code/missionui/missionscreencommon.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
- freespace2/freespace.cpp
Add an `$On Movie About To Play:` hook to match `$On Intro About To Play:`.  Also make the two hooks overridable, since that might be useful.
Additionally, change a few (nonexhaustive) `name` parameters to `filename` to make it clearer that the string is a filename.
> add pre-movie hook

- code/osapi/osapi.cpp
- code/osapi/osregistry.cpp
- code/osapi/osregistry.h
As i commented in #6392 in Windows during a completely new install on a clean pc FSO will default to legacy config this is because old_config_exists is set to true and never checked, contrary to linux were it checks if there is a config file name or not.
What i found is that if neither the registry keys and cmdline_fso.cfg exists the old_config_time will be 0 as thats is the default "not found" error value for both get_file_modification_time() and os_registry_get_last_modification_time().
But it is not perfect because if you install Freespace 2 from Steam and try to run it, even trought it dosent work, it creates the registry entries, this may be true with the retail cds as well. But it is not the case for the gog version.
But technically the registry entry is there so i dont think i can …
> Set old_config_exists to false in Windows if the registry key are not present

- code/scripting/api/objs/weaponclass.cpp
- code/weapon/shockwave.cpp
- code/weapon/shockwave.h
- code/weapon/weapons.cpp
If a weapon's shockwave damage has not been specified via table, `ShockwaveDamage` should return -1 instead of 0, and otherwise return the value set via table, allowing scripts to disambiguate explicitly 0 and unspecified. Additionally, a few parsing changes to ensure shockwave damage can never genuinely be negative (all damage handling is already doing this so this will have no gameplay effects). 
This is an explicit, unflagged change to the specification of this script value, but it's really not worth a flag, and a very niche case for which backwards compatibility concerns would surely be negligible.
> Disambiguate `ShockwaveDamage` cases

- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/parse_object.cpp
- code/scripting/api/objs/team.cpp
- code/scripting/api/objs/wing.cpp
There are a few places in the Lua script API where a variable could be some type of "object" or something that is not an "object" but is still useful - one example is the return value from oswpt:get().  With this function, scripts will be able to tell what the variable is without risking an exception.
> adds getBreedName() in a few places

- code/def_files/data/tables/objecttypes.tbl
- code/parse/sexp.cpp
- code/parse/sexp.h
- code/ship/ship.cpp
- code/ship/ship.h
- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
This fixes the fighter/bomber type which had been broken ever since the objecttypes.tbl upgrade in https://github.com/scp-fs2open/fs2open.github.com/commit/246cfcfa655ae58159161011ff1f95dd79d68357: the fighter/bomber type is again treated as a union of fighters and bombers, not a unique type of its own.  This requires special handling for the `OPF_SHIP_TYPE` SEXP argument type, and all four SEXPs that use `OPF_SHIP_TYPE` have been modified to check for the special case.  The explicit fighter/bomber type has again been removed from the built-in objecttypes.tbl.
The requirements for "fighter/bomber" to be valid are 1) there is no explicit "fighter/bomber" type in the mod; 2) a "fighter" type exists; 3) a "bomber" type exists.  If any of these conditions is not met, the special case behavior …
> proper fix for fighter/bomber

- code/localization/localize.cpp
- code/mission/missionbriefcommon.cpp
- code/mission/missionbriefcommon.h
- code/missionui/missionbrief.cpp
Adds a user option to scale icons down to as small as 0.2* the current size or as large as 4*. Includes the code in #6328 .
> Optional icon scaling

- code/localization/localize.cpp
- code/parse/parselo.cpp
1. Tweak the API of `error_display` so that an error level of 2 displays a `ReleaseWarning`.
2. Use this error level for the malformed XSTR warnings in the localization code.
Resolves #6374.
> make malformed XSTR a release warning

- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
Hide these SEXP operators to reduce confusion for FREDders.  They still work, but using them properly requires a certain amount of knowledge of the inner workings of variables, and the operators can break if new variables are added causing the list to be re-indexed.
Implements half of #6400.
> hide variable -index SEXP operators in FRED

- code/io/timer.h
Change `timestamp_valid()` to also catch the common case of -1 being used for invalid as well as the "official" 0.
This addresses a few Coverity defects, but due to the widespread use of this function and on @Baezon 's recommendation, I am deferring it until after the stable build.
> refine timestamp_valid

- code/network/multi_options.cpp
- code/network/multiutil.cpp
- code/network/psnet2.cpp
- code/network/psnet2.h
1. Use a sensible default for the connection speed
2. Remove the `Psnet_connection` variable which is now obsolete: "its only purpose now is to change the default object update value for a player if it's set to dialup, and that's easily done in-game already"
The "You must define your connection speed" popup will now no longer appear unless it has been explicitly set to an invalid value.
Applies recommendations from, and fixes, #6402.
> handle connection speed in a user-friendly way

- code/ai/ai.h
- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/ai/aigoals.h
- code/autopilot/autopilot.cpp
- code/autopilot/autopilot.h
- code/mission/missiontraining.cpp
- code/mission/missiontraining.h
- code/network/multi_obj.cpp
- code/object/waypoint.cpp
- code/object/waypoint.h
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/order.cpp
- code/scripting/api/objs/waypoint.cpp
- code/scripting/api/objs/waypoint.h
- code/ship/ship.cpp
- freespace2/freespace.cpp
Several locations in the code (notably `ai_info` and `waypoint_h`) previously stored pointers for waypoints and waypoint lists that need to be valid for more than one frame.  Since both waypoint lists and waypoint paths may change size, resulting in vector reallocation, the information should be stored as indexes instead.
Fixes #6353.
> replace waypoint pointers with waypoint indexes

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
PR #6335 did not update actions/upload-artifact; both upload and download need to use the same major version number.
Also move from v4.1.7 to just v4 because that appears to be the common practice.
> sync upload and download artifacts

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/object/collideshipship.cpp
Basic cleanup of `asteroid_subtype_info` to remove the pointer. We already save the model number in the same place so prefer using `model_get()` wherever the pointer was used.
> Remove model_pointer in favor of using model_number

- code/graphics/software/font.cpp
The next step in getting built-in fonts to work for all screen resolutions...
This adds an optional flag for a font to automatically scale for the current screen resolution. The formula here is meant to get a font size for the current screen that'd be roughly equivalent to the defined font size if it were on a 1080p screen (the most popular screen resolution currently, according to Steam, and the one that's pretty close to what FSO has been targeting for years.
This is the same formula that SCPUI uses and with this in place SCPUI can have a single font slider in Options that affects all fonts game-wide should mods setup a compatible font system.
This will only work for TTF/OTF fonts and not the old bitmap fonts.
> Auto size font for screen resolutions

- code/object/collideshipweapon.cpp
- code/weapon/beam.cpp
This was motivated by the recent Coverity report.  Coverity noticed that a few of the copy assignments could be replaced by move assignments, but on further investigation one copy each in `ship_weapon_check_collision()` and `beam_collide_ship()` can be entirely removed, another either/or copy in each can be replaced with an either/or pointer assignment, and a few copies can be done only when needed.  Another vec3d copy can be replaced with a vec3d pointer since there is no longer a need to keep a local copy.
> optimize collision code a bit

- code/mission/missioncampaign.cpp
- code/parse/sexp.cpp
When a player tries to skip a mission during a campaign, all goals and events are marked true.  Thus it's possible for the campaign condition to unexpectedly *not* evaluate to the next mission (e.g. `if is-previous-goal-false` or `is-previous-event-false` is used without the optional argument).  So add a failsafe check, with a warning, to handle this case.  Also update the documentation to clarify that the optional argument is checked for the mission-skipped case.
Fixes an endless skip-to-the-same-mission loop discovered by ShivanSlayer in Shrouding the Light.
> make mission skipping more robust

- code/parse/sexp.cpp
- code/parse/sexp.h
This adds a sexp to allow any boolean condition, or series of conditions, to be evaluated not only instantaneously, but also for a period of time.  For example, this can be used with `is-facing` to check if a ship has been facing another ship for a specified duration.  Previously this had to be done through scripting or through a group of sexps.
Implements #5754.
> add is-true-for-duration sexp

- code/menuui/mainhallmenu.cpp
- code/menuui/mainhallmenu.h
Allows mainhalls to decide whether or not to render the FSO game version and the current mod title on the mainhall.
> Define whether or not to render the game strings on the mainhall

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
The FreeSpace AI includes behavior to run away from shockwaves to try to avoid explosion damage.  This is implemented for both ships and missiles, although the missile implementation has been buggy ever since retail.  There are several issues:
1. The AI attempts to evade a weapon immediately upon launch.  Many missiles have a period of free flight before they start homing on their target.  During the free flight period, the homing position is not set.  Consequently, the AI will not know the position to avoid and will make assumptions.
2. The AI assumes the shockwave-producing weapon will detonate at the center of the ship it is targeting, although missiles detonate on the surface.  A capital ship is likely to be significantly larger than the weapon's blast radius, leading the AI to …
> fix ai behavior when avoiding ship and weapon shockwaves

- code/gamesnd/gamesnd.cpp
- code/gamesnd/gamesnd.h
- code/menuui/mainhallmenu.cpp
- code/menuui/mainhallmenu.h
Adds a new `+Ambient Sound:` field to mainhall.tbl, allowing any interface sound (or even no interface sound) to be used for the main hall ambient sound.  The default ambient sound, as well as the sound played on the pilot select screen, is interface sound 12.
Implements #6421.
> allow ambient sound to be specified on a per-main-hall basis

- code/cmdline/cmdline.cpp
- fred2/fredview.cpp
1. Fix some memory leaks and make the application name detection slightly more reliable.
2. Takes the command-line arguments used to launch FRED and reuses them to launch FSO.
3. As part of this, slightly refactor the `cmdline_print_cmdline_multi()` function so that it calls a new `cmdline_build_string()` function.
This restores full functionality of the Run FreeSpace option so that it behaves as expected.
> revise Run FreeSpace menu option

- code/model/model.h
- code/ship/ship.cpp
The recent cycle expansion PR (#6364) causes a CTD when change-ship-type is used. This PR fixes that crash by using `pm->n_guns` instead of 'MAX_SHIP_PRIMARY_BANKS' and clarifies the definition comment for the `pm->n_guns` to help avoid this kind of quandary in the future (thanks @Baezon!).
Note, renaming the `n_guns` variable would touch so many files that this PR was focused more on applying the CTD hotfix.
> Fix CTD from recent cycle expansion

- code/mission/missionparse.cpp
If the mission is edited in a text editor, and a ship is given too many weapon banks, this can cause issues in the weapon firing code.  Protect against this by checking the number of banks when the ship is created.
> protect against weapon bank overflow

- code/ship/ship.cpp
In #6364, I erroneously left out the code that would increment the pattern index when parsing what firing patterns are allowed for a ship. This fixes that.
> Fixes pattern_index oversight.

- fred2/addvariabledlg.cpp
- fred2/bgbitmapdlg.cpp
- fred2/briefingeditordlg.cpp
- fred2/campaigneditordlg.cpp
- fred2/cmdbrief.cpp
- fred2/createwingdlg.cpp
- fred2/debriefingeditordlg.cpp
- fred2/eventeditor.cpp
- fred2/messageeditordlg.cpp
- fred2/missioncutscenesdlg.cpp
- fred2/missiongoalsdlg.cpp
- fred2/missionnotesdlg.cpp
- fred2/modifyvariabledlg.cpp
- fred2/shipeditordlg.cpp
Any DDV (Dialog Data Validation) routine must appear immediately after the field it validates in order for the enforcement to work in real-time.  If the DDV_ routine is not linked to the field, it will perform validation after-the-fact by displaying a dialog box and returning an error.  This is an alternate way of handling validation, but in order for the dialog box not to generate an endless loop, it would be necessary to check the return value of every `UpdateData(TRUE)` call in the FRED codebase (or at least the first `UpdateData(TRUE)` in a pair of them) and then, if the return value is `FALSE`, doing an early return from the enclosing function.
Fixes #6427 as well as all similar cases in FRED.
> fix DDV_ validation in FRED, especially DDV_MaxChars

- code/globalincs/pstypes.h
- code/missionui/missionweaponchoice.cpp
When clicking on a weapon bank, mark the weapons as enabled or disabled according to their compatibility for that bank.  Do not actually prevent the weapons from being selected and dragged, as they may be dropped on a bank that isn't selected.
Also add a new `TriStateBool` for situations where the value is true, false, or unknown.
Fixes #6398.
> enable or disable weapon icons according to bank compatibility

- code/missionui/missionweaponchoice.cpp
- code/parse/sexp.cpp
- code/ship/ship.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
1. Don't set the `can_use_for_bank` flag to FALSE if the bank is primary but the weapon is secondary, or vice versa
2. Make sure to only restrict the weapons by bank if the ship has per-bank restrictions
In support of this, add `is_primary()` and `is_secondary()` helper functions to `weapon_info` and use them in logical places.
Follow-up to #6434.  Fixes a few subtle bugs from that PR.
> improve bank-compatibility check

- fred2/fred.cpp
FRED has code to keep track of whether the main window should be rerendered on each frame.  It looks like this was accidentally removed at some point.
(Discovered by comparing FRED source files while investigating #5568.)
> re-add Update_window tracking

- .clang-tidy
- code/graphics/software/FSFont.cpp
- code/graphics/software/FSFont.h
- code/graphics/software/FontManager.cpp
- code/graphics/software/FontManager.h
- code/graphics/software/NVGFont.cpp
- code/graphics/software/NVGFont.h
- code/graphics/software/VFNTFont.cpp
- code/graphics/software/font.cpp
- code/graphics/software/font.h
- code/scripting/api/libs/graphics.cpp
- code/scripting/api/objs/font.cpp
- code/scripting/api/objs/font.h
- code/scripting/api/objs/hudgauge.cpp
- code/ui/window.cpp
- fred2/sexp_tree.cpp
- qtfred/src/ui/widgets/sexp_tree.cpp
This refactors FontManager to improve it in several ways:
1. Change all the dynamic memory management to use `new`, rather than mixing `new` and `vm_malloc`
2. Change the current font to use an index rather than a pointer
3. Take advantage of more C++11 features to avoid redundant lookups
4. Use case-insensitive name comparison
5. Avoid overflowing the `fnt->filename` field
6. Use `Warning` rather than `Error` in a non-critical error situation
Motivated by #6313 but does not fix the crash.
> fix memory management in FontManager

- code/ship/shiphit.cpp
I considered having shockwaves do this too, but having "esuck" missiles suddenly start draining double the amount is probably not a good idea... so a problem for later.
Additionally, this removes the `Beams_use_damage_factors` check from `shiphit_get_damage_weapon`, the purpose of that function is to return the wip_index of the provided object, not to withhold it based on a specific usage. All locations in the code where this would be relevant already check this flag, or have been made to do so by this PR (indeed some unrelated feature, like "vampiric" have been inadvertently trapped behind this flag as a result).
> Allow beams to do energy leeching

- code/hud/hudparse.cpp
- code/missionui/missionbrief.cpp
- code/nebula/neblightning.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
A potpourri of tweaks based on several recent requests for mod support.
1. allow `$Distance Unit Multiplier:` as a synonym for `$Length Unit Multiplier:`
2. enhance help text for script functions that do weapon category checks
3. fix distinction between lasers and beams in several places
4. clean up `weapon_sort_by_type()` by removing unnecessary `Verify`s and using `std::move` for sorting
5. fix compile warnings for briefing icon scaling
6. fix lightning bolt texture checks, needed for TBP
Each item is self-contained in its own commit.
> several small fixes

- code/graphics/render.cpp
- code/graphics/software/FSFont.cpp
- code/graphics/software/FSFont.h
- code/graphics/software/FontManager.cpp
- code/graphics/software/FontManager.h
- code/graphics/software/NVGFont.cpp
- code/graphics/software/NVGFont.h
- code/graphics/software/VFNTFont.h
- code/graphics/software/font.cpp
- code/graphics/software/font.h
- code/localization/localize.cpp
- freespace2/freespace.cpp
Adds an in-game option to scale the internal fonts. Only works with TTF fonts so after the font table is parsed we check. If there are no scaling-allowed TTF fonts then we remove the option.
Scaling fonts is explicitly opt-in so that mods can control what can scale.. thinking mostly of HUDs with this. I have a plan of attack for allowing HUDs to scale in a later PR.
> Ttf font scaling option

- code/missionui/missionweaponchoice.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
As requested by Woolie Wool. Default colors are set, copying the colors they were originally set to from `Icon_colors`.
> Allow defining custom overhead line colors

- code/mission/missionmessage.cpp
- code/mission/missionmessage.h
- fred2/fred.rc
- fred2/resource.h
- fred2/voiceactingmanager.cpp
- fred2/voiceactingmanager.h
Augments the voice acting manager to handle non-wingman as well as wingman personas, plus limit operations to a specific persona.  This also modifies the editor to only increment the number of modifications when something *is* modified, not merely when something *could be* modified but is currently the expected value.
Resolves #6379.  ~~In draft pending acceptance from the requestor.~~
> allow voice acting manager to handle non-wingman personas

- code/cmdline/cmdline.cpp
- code/osapi/osapi.cpp
The idea is to truly allow FSO to be portable along with Knet launcher, with being able to set a custom folder for the pilots and settings it is possible to have a folder stucture where the knossos library is portable along with the the knossos executable and still reading the pilots and saving settings to a portable location inside the library itself instead of the appdata folder.
The older portable mode is not enoght for this (i was wrong, it still works, it just that due to the argument parsing order the wrong pref_path is printed on "-get_flags json_v1", but this should not affect functionallity).
But it is not adecuate for this as the old portable mode will use the current working folder to save pilots, settings and pickup the inis, so it dosent work in the same way as the appdata …
> Support custom preferences path

- code/ship/ship.cpp
In #6364, I overlooked a behavior where type 3 beams do firepoint cycling automatically. This is now fixed. Dynamic primary linking will now override type 3 (where before #6364, I believe, it just didn't work for beams at all), but type 3 will override firing patterns, to remain consistent with the previous behavior where type 3 was higher priority than the 'cycle' flag.
As it stands this is a bit ugly. I might want to come back later and clean up some of the control flow, for example by making it so that a type 3 beam will have firing pattern CYCLE FORWARD by default, and we can ditch some of the special casing. But this'll fix the problem for now.
> Beam cycle fix

- code/parse/sexp.cpp
- code/ship/ship.cpp
- code/ship/ship.h
Many SEXP operators that work on subsystems use very similar code.  This new function allows the operator implementations to be streamlined and makes future modifications easier.  For example, the `change-ai-class` operator now works with names such as `<all turrets>` as well as specific subsystems.
Inspired by #6210 although not a direct implementation of it.
> create a `process_ship_subsystems` routine for subsystem operations

- code/hud/hudtargetbox.cpp
- code/scripting/api/objs/subsystem.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/ship/ship.h
A recent-ish FSO feature, `$Turret Name:`, allows turrets to be displayed differently on the HUD depending on the weapon they carry.  It is useful for scripts to be aware of this, so this PR adds a `TurretName` virtvar for weapon classes, as well as a `NameOnHUD` virtvar for subsystems.  The `NameOnHUD` virtvar shares exactly the same code as the HUD uses, so any future HUD modifications will be reflected in scripting as well.  This required a small amount of refactoring: changing `get_turret_subsys_name()` to return a value rather than stuffing a string, renaming it to `ship_subsys_get_name_on_hud()`, and moving it to ship.cpp.
> add scripting support for weapon class "turret names"

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.h
- qtfred/src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.h
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
- qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.h
- qtfred/ui/ShipCustomWarpDialog.ui
Not much to say on this one. Functions almost exactly the same as the oldFRED one. 
Only changes are not showing lines irrelevant to the selected warp type and additional warnings if game sounds don't not exist.
Also visually shows the Hyperspace warp type as "Star Wars" for clearer useability but does not change the backend.
> QtFRED: Custom Warp Dialog

- code/ship/ship.h
This reset function was not actually used anywhere, so declaring and emplacing back these things, they were getting `tex_id`s of 0, not -1. So if the texture parsing failed, the rendering would later try to render tex_id 0 (since it only skips rendering if the id is < 0) and corrupt everything. So I just turned the reset into a constructor.
> Fix maneuvering thruster initialization

- code/network/multiutil.cpp
A connection speed of "None" is really just the default used by launchers if the user hasn't explicitly set the speed yet.  Additionally, `CONNECTION_SPEED_NONE` isn't really used by the engine except for error checking.  So, fall back to the default connection speed even when the speed has been set to "None".
Follow-up to #6402.
> default the connection speed to Fast even if it has been set to None

- code/parse/sexp.cpp
Due to broken node iteration, the `sexp_ship_deal_with_subsystem_flag()` function incorrectly treated the first sexp node as a subsystem, but previous versions of the function would fail silently and ignore it, and subsequent nodes would work as expected.  With the new `process_ship_subsystems()` function, this error is properly flagged (and the incorrect node is again bypassed).  So, fix the error by fixing the node iteration.
Follow-up to #6221.
> fix sexp_ship_deal_with_subsystem_flag()

- code/object/objectdock.cpp
- code/object/objectdock.h
- code/scripting/api/objs/ship.cpp
- code/ship/shipfx.cpp
As described in #6445, the `warpIn()` script function did not work correctly for docked ships because the dock leader flag was not set.  So, set the flag, but make sure to set it only for the first ship for which `warpIn()` is called.  And make sure the flag is removed after the ship finishes arriving.
Also remove an `Int3()` in `shipfx_warpin_start()`.  (This Int3() was not actually in the original Volition source code release.)
Fixes #6445.
> fix ship:warpIn() behavior for docked ships

- code/osapi/osapi.cpp
Turns out that we incorrectly used ImGUI's flags for the request for exclusive input handling to determine whether to send ImGUI any input _at all_.
On Windows and X11, this seems to work regardless since the respective flags seem incorrectly set / not used on these platforms, but it prevented any input on wayland.
Fixes #6431.
I'd appreciate someone on windows giving this a test run at some point!
> Fix ImGUI input flag handling

- code/scpui/RocketDecorators.cpp
- code/scpui/RocketDecorators.h
- code/scpui/RocketDecoratorsInstancer.cpp
- code/scpui/RocketDecoratorsInstancer.h
- code/scpui/rocket_ui.cpp
- code/source_groups.cmake
Adds two new custom decorators for librocket/scpui.
The first adds the ability to underline RML elements in SCPUI which is a workable solution to font underlining which neither the internal FSO font system or librocket's font system officially support. To be clear, this underlines an element, not a line of text. It's meant for short bits of underlining special words similar to how colors are used in briefings. Implementing full underlining would take significant work and modifications to the librocket library itself so I've decided to forgo that effort in hopes of maybe converting to RmlGUI sometime in the future. See #5364 .
```
.underlined-element {
test-decorator: underline;
test-thickness: 2.0px;
test-style: dashed;
test-length: 10.0px;
test-space: 5.0px;
test-color-setting: element; …
```
> Add underlining as a custom decorator

- CMakeLists.txt
- code/CMakeLists.txt
- code/graphics/opengl/gropenglopenxr.cpp
- code/graphics/openxr.cpp
- code/graphics/openxr_internal.h
- lib/CMakeLists.txt
* Windows and Linux default to ON
* macOS defaults to OFF
* User can override default on the command line
Example usage:
```
cmake -DFSO_BUILD_WITH_OPENXR=OFF
```
> Add FSO_BUILD_WITH_OPENXR cmake option

- code/hud/hudmessage.cpp
- code/mission/missionmessage.cpp
- code/mission/missionmessage.h
This adds two new features to head anis to simplify and expand their handling.
First it adds `$Always loop head anis:` option to messages.tbl. This will cause all heads to loop until the message audio is finished. It doesn't look great with the retail anims because they aren't meant to loop so your mileage may vary. It's meant to be used with the new feature below but was simple enough to make it be its own flag for better customization.
Second it adds `$Use newer head ani suffix features:` which abandons the old `a`, `b`, `c` method of selecting heads in favor of `-reg` and `-death`. In this mode all heads will have `-reg` appended to the filename unless they are a death scream and not command. (This explicitly allows large ship personas to have death screams, btw) in which case `-death` …
> Upgrade head ani handling

- code/graphics/color.cpp
- code/graphics/color.h
- code/object/object.cpp
Fixes an error with converting between 0.0-1.0 floats and 0-255 ints, introduced in #6319, that caused weapon lights to have a color of 0, 0, 0.
> Weapon light bugfix

- code/menuui/mainhallmenu.cpp
- code/menuui/mainhallmenu.h
There were several bugs and design issues in the Vasudan headz cheat, probably due to being coded in a hurry right before release:
1. Although the cheat activated on the main hall, it was not immediately apparent, requiring the player to switch screens and come back
2. The detection of whether the main hall is Vasudan did not work after the cheat was activated, due to the background filename changing (this one is actually not Volition's fault)
3. The implementation of the cheat was actually in the wrong section of code, resulting in some confusion
These are now fixed.  The cheat can be enabled or disabled from one function, the graphics are reloaded properly, and the main hall detection includes the cheat-active version of the main hall.  Also, the door sounds have been slightly …
> fix a few bugs in the Vasudan heads cheat

- code/exceptionhandler/exceptionhandler.cpp
- code/globalincs/windebug.cpp
- code/menuui/readyroom.cpp
- code/mission/missioncampaign.cpp
- code/model/modelread.cpp
- code/osapi/dialogs.cpp
- code/pilotfile/csg.cpp
- code/scripting/api/objs/player.cpp
- code/utils/string_utils.h
- code/windows_stub/stubs.cpp
As discovered by WouterSmits, campaigns with periods in their filenames caused issues with FSO's campaign handling.  Specifically, in The Babylon Project, the EA-Minbari war v1.0.fc2 campaign would not save progress because FSO expected EA-Minbari war v1.fc2 in certain places.  This is because the `_splitpath()` function attempted to remove an extension from a filename that already had it removed.  For most campaigns this did not matter, but WouterSmits found a campaign where it did.
To solve this, there is now a new `util::get_file_part()` function to remove the path without removing the extension.  This replaces `_splitpath()` for campaign files, as well as the similar `clean_filename()` and `GetFilePart()` functions in other places.  All code paths were inspected for any chance of …
> improve campaign file extension handling

- code/ai/aigoals.cpp
- code/ai/aigoals.h
- code/parse/sexp.cpp
- freespace2/freespace.cpp
1. Allow the goal priority to be an evaluated number, not just a literal number.  This allows the goal priority to be obtained from operators or calculations.
2. Since the priority can now be evaluated, it can be NaN.  In that case, default to the max priority.
3. Consolidate `CDR(CDR(...))` to `CDDR()` in the aigoal implementation
4. Clarify that `remove-goal` removes the first goal of a given type and priority, not necessarily the first fully matching goal.
5. Enhance `remove-goal` to remove all goals matching the constraints, not just the first goal.
6. Allow `remove-goal` to disregard priority when checking for matching goals.
> enhance the add-goal and remove-goal sexps

- code/osapi/osapi.cpp
If the user launches FSO with a `FSO_PREFERENCES_PATH` value that does not end with a path separator (Linux `/`, Windows `\`), FSO will create a `fs2_open.ini` file in the wrong location.
**Example:**
Given: `FSO_PREFERENCES_PATH='./config' fs2_open`
Path is: `'./config'`
INI file path becomes: `./configfs2_open.ini`
This PR ensures that the custom preferences path ends with a path separator, resulting in the `fs2_open.ini` file being created in the expected location.
**Example with PR:**
Given: `FSO_PREFERENCES_PATH='./config' fs2_open`
Path becomes: `'./config/'`
INI file path becomes: `./config/fs2_open.ini`
Extends #6387.
> Ensure custom preferences path ends with path separator

- code/sound/sound.cpp
Make some modifications to the adjust-audio-volume infrastructure:
1. Add an `aav_volume` array for ease of access to all three volume variables.  Refactor `snd_adjust_audio_volume()` to use this array to avoid duplicating code.
2. Move `update_looping_sound_volumes()` to be handled in parallel with `audiostream_set_volume_all()`, and for the same reason: avoid setting the sound volume for every looping sound on every frame if the volume has not changed.
3. If the volume is to be adjusted immediately, apply the relevant changes without waiting for `snd_do_frame()` to be called on the next frame.  Resolves #6291.
4. Fix some edge cases in `adjust_volume_on_frame()`.
> adjust-audio-volume adjustments

- code/fireball/warpineffect.cpp
Fixes the warp flash option being optimized out of retail builds. Similar to #5689 and #6204
Fixes #6263
> Fix warp flash option

- code/mission/missionparse.cpp
- code/mission/missionparse.h
- code/parse/sexp.cpp
- fred2/freddoc.cpp
- fred2/fredrender.cpp
- fred2/fredrender.h
- fred2/fredview.cpp
- fred2/management.cpp
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/EditorViewport.h
When a mission is loaded in FRED the "immobile" flag is migrated to "don't-change-position" and "don't-change-orientation".  So, notify the FREDder that this is happening, and add checks to the "potential issues" checker to guard against mixing the old and new flags.
Follow-up to #6304.  Resolves #6489.
> add safeguards to the "immobile" flag migration

- code/cmdline/cmdline.cpp
- code/cmdline/cmdline.h
- code/mission/missioncampaign.cpp
The `-campaign` cmdline option allows the current campaign to be set on FSO launch so that the player isn't interrupted by the "The currently active campaign cannot be found" dialog when changing mods.
Example usage:
```
fs2_open -campaign freespace -mod fsport
```
When `-campaign` is set to a valid campaign name, the following dialog will not pop up when changing mods.
> Add '-campaign' cmdline option to set current campaign

- lib/antlr4-cpp-runtime/CMakeLists.txt
- lib/antlr4-cpp-runtime/runtime/CMakeLists.txt
The deprecation warning that required changes:
* [CMP0054: Only interpret `if()` arguments as variables or keywords when unquoted.](https://cmake.org/cmake/help/latest/policy/CMP0054.html)
The deprecation warnings that did NOT require changes as those features were not used:
* [CMP0026: Disallow use of the `LOCATION` property for build targets.](https://cmake.org/cmake/help/latest/policy/CMP0026.html)
* [CMP0042: `MACOSX_RPATH` is enabled by default.](https://cmake.org/cmake/help/latest/policy/CMP0042.html)
* [CMP0045: Error on non-existent target in `get_target_property`.](https://cmake.org/cmake/help/latest/policy/CMP0045.html)
* [CMP0059: Do not treat `DEFINITIONS` as a built-in directory property.](https://cmake.org/cmake/help/latest/policy/CMP0059.html)
Output of deprecation …
> Fix antlr4 CMake deprecation warnings

- code/hud/hudwingmanstatus.cpp
- code/hud/hudwingmanstatus.h
- code/math/floating.h
- code/parse/sexp.cpp
- code/parse/sexp.h
This allows the wingman status gauge to be changed to display new wings or a different set of wings.  Quoting the help description:
> Sets the wings displayed on the squadron HUD display.  By default these are Alpha, Beta, Gamma, Delta, and Epsilon.  The squadron status will be updated to the current status of the wings, but note that if any ships in those wings have previously been destroyed, the HUD display may look different than expected.  (Specifically, destroyed ships may be indicated as missing or may cause other ships in the same wing to appear in different positions.)  However, any wings that are shared between one display and the next will be preserved.
Implements the request in #5872.
> add set-squadron-wings sexp

- code/io/mouse.cpp
In the In-game options for `mouse_mode` the XSTR index for "Mouse" was set to 1774, which is already used for "Glide When Pressed". Luckily "Mouse" XSTR already exists with Index 1373, so this PR changes it to that.
> Fix `Mouse` XSTR Index in In-game options

- code/scripting/api/objs/message.cpp
- code/scripting/api/objs/ship.cpp
Adds a lua func to get a ship's persona as a persona handle. Pretty straightfoward.
There is already a virtvar to get a ship's persona index which can used to iterate through the mission's personas but this is faster and simpler. I thought about deprecating the virtvar but if anyone is using it to set a ship's persona then I'd have to add a setShipPersona() func and we're back to having two functions again.
I also considered having the virtvar optionally return the persona directly but it's specifically called PersonaIndex which I felt confused the matter a bit.
Open to opinions if there's a better way to organize this.
> Func to get a ship's persona directly

- code/graphics/2d.cpp
- code/graphics/2d.h
- code/mission/missionbriefcommon.cpp
- code/mission/missionbriefcommon.h
- code/mission/missionparse.cpp
- code/mission/missionparse.h
- fred2/briefingeditordlg.cpp
- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Allows setting a custom grid color for each briefing stage with
```$grid_color: (r, g, b, a)```
For now there's no UI because this is decidedly niche and would be much easier to do in qt with a full color picker.
> Allow per-stage briefing grid colors

- code/controlconfig/controlsconfig.cpp
The Popup Dialog for `Confirm Control Preset Overwrite` has the Yes and No buttons order switched compared to what they are usually set as. This means the images appear offset and do not look sharp against the background of the dialog box image. This PR switches the order to match and remove that visual bug. Albeit a very minor bug, but one I have heard from a few folks and noticed myself as well.
PR is tested and works as expected.
> Fix offset dialog option image with controls preset confirmation

- code/scripting/api/libs/globals.cpp
- code/scripting/api/libs/globals.h
- code/scripting/api/libs/ui.cpp
- code/scripting/lua.cpp
- code/source_groups.cmake
Adds a new library for access global variables and defines.
I wanted max ship primary and secondary banks and couldn't decide if that should go in base, ui, tables, or somewhere else. Having it accessible as part of ShipClasses wasn't great because you'd need to access it as part of an existing ship class.
I also wanted access to a couple other global defines and so I decided a global variables library made sense. I could take or leave it if there's a better place to put these, though, as this is purely an organizational question. Actual code access to these values is trivial... they just needed a home.
> Add Lua global variables library

- code/nebula/volumetrics.cpp
If the volumetrics model cannot be loaded, fail gracefully by warning and not generating volumetrics.  This prevents a hard exit in the event of a model problem, particularly when a mission is being edited in FRED.
> gracefully fail if volumetrics model is not found

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/ai/aibig.cpp
Many mods change ship velocities and damp values, but this commonly leads to poor behaviors attacking large ships within strafe mode (which is the main method for attacking big ships in a sustained way). As an example, FotG has damp and velocity values that are higher than base FS, thus the defined strafe values result in behavior where fighters never can complete a sustained firing pass against a large ship unless they are sitting and parking (which does not fit our goals to match the movie).
The values for dictating how strafe behavior occurs are easily editable by changing some key values, which this PR exposes to modders. Furthermore, mods may give large ships very long range weapons, so being able to set how far away a ship should do a strafe run begins is very valuable.
In testing …
> Allow Modders to Tune Strafing

- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/asteroid/asteroid.cpp
- code/globalincs/systemvars.cpp
- code/globalincs/systemvars.h
- code/graphics/2d.cpp
- code/menuui/optionsmenu.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/model/modelinterp.cpp
- code/model/modelrender.cpp
- code/nebula/neb.cpp
- code/nebula/volumetrics.cpp
- code/network/multi_pinfo.cpp
- code/options/Option.h
- code/options/OptionsManager.cpp
- code/options/OptionsManager.h
- code/options/default_settings_table.cpp
- code/options/default_settings_table.h
- code/particle/particle.cpp
- code/pilotfile/plr.cpp
- code/playerman/managepilot.cpp
- code/source_groups.cmake
- code/starfield/starfield.cpp
- code/utils/string_utils.cpp
- code/utils/string_utils.h
- freespace2/freespace.cpp
Implements an FR from the FOTG team; specifically it creates a `default_settings.tbl` that changes the default settings that various options will have before trying to load the player's values from the player file or INI file. Parsing is relatively straightforward.
Many thanks to @wookieejedi for testing and finding the right insert point during game initialization that this can be done safely.
The following example (not recommended for use) will set PostProcessing to default OFF instead of ON. Additionally it will enforce the value to always be false. More on that below.
```
+Option Key: Graphics.PostProcessing
+Value: false
+Enforce
```
The idea is to give game creators using FSO the ability to set reasonable default values for settings based on their mod's data. In some cases it may be …
> Default settings tbl

- code/sound/sound.cpp
- code/utils/id.h
Now that `snd_do_frame()` has been tightened up to specifically only adjust audio for the adjust-audio-volume sexp (in #6488), the redundancy-avoiding code in `snd_set_volume()` is obsolete.  So, set the sound volume immediately, even if it is a looping sound.
This is a two-for-one fix; the proper setting of volume fixes both #6504 and #6507.
Also, change `currentlyLoopingSoundInfos` and `currentlyLooping3dSoundInfos` from lists to maps.  The data structure should keep track of the volumes currently, as opposed to historically, associated with each sound handle.
Since the map requires `util::ID` and its derivatives to be hashable, add `util::ID_Hash`.
> fix volume updates for looping sounds

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/object/objectsort.cpp
- code/ship/ship.cpp
- code/ship/shipfx.cpp
- code/weapon/beam.cpp
FotG uses cockpits and 'show ship', and also provides a way for players to toggle off cockpits. Unfortunately, if the player disables cockpits, 'show ship' still appears and looks very odd (since it appears the player is flying a ship with a hole in the center where the cockpit would be). Other mods have made entire ships with their cockpits, but FotG needs to use 'show ship' to match team colors and moving external ship animations.
This PR adds a game_settings option that allows mods to set to only use 'show ship' if cockpits are enabled.
> Add Mod Option to Limit 'Show Ship' when Toggling Cockpits

- code/debris/debris.cpp
- code/scripting/api/objs/modelinstance.cpp
- code/scripting/api/objs/ship.cpp
Debris chunks that use the same texture as the actual hull model are not updated when `texture-replace` methods are used. For example, a clean grey base textures that has texture replace via table or FRED is changed to red/brown. But when the ship is destroyed the debris objects are using the original lighter texture instead of the newer darker one.
#6154 provided the groundwork to fix this, but one step fell through the cracks; setting the debris hull textures to what the parent ship used.
This PR sets the debris texture replacements when debris is created to fix this (and fixes #2462).
Fix is tested and works as expected.
> Fixes Debris not inheriting parent ship texture replacements

- code/camera/camera.cpp
- code/gamehelp/contexthelp.cpp
- code/graphics/2d.h
- code/graphics/render.cpp
- code/graphics/render.h
- code/graphics/software/FSFont.cpp
- code/graphics/software/FSFont.h
- code/graphics/software/FontManager.cpp
- code/graphics/software/NVGFont.cpp
- code/graphics/software/NVGFont.h
- code/graphics/software/VFNTFont.cpp
- code/graphics/software/VFNTFont.h
- code/graphics/software/font.cpp
- code/graphics/software/font.h
- code/hud/hudmessage.cpp
- code/menuui/credits.cpp
- code/menuui/techmenu.cpp
- code/missionui/fictionviewer.cpp
- code/missionui/missionbrief.cpp
- code/missionui/missioncmdbrief.cpp
- code/missionui/missionweaponchoice.cpp
- code/osapi/DebugWindow.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/scripting/api/libs/graphics.cpp
Adds two features for string handling:
First it adds scaling ability to Volition fonts which brings them into parity with TTF fonts. In doing so it made sense to move the font scale option out of the TTF font cpp file and into the general font cpp file. Notably, allowing players to scale fonts is currently opt-in. Now that all font types can scale, there's possibly an argument to make them opt-out. I could go either way, personally.
Second it adds a scale multiplier to gr_string(). This will be used for the HUD Config upgrade and it basically allows a gr_string() call to multiply the user's font scale up or down by a percentage. Think of it like a C++ version of CSS's `em` font size capability. This did change the signature of gr_string() because I felt `scaleMultiplier` had more utility …
> Add scaling for vfnts and scale multipler to gr_string()

- code/graphics/2d.cpp
- code/graphics/2d.h
- code/graphics/render.cpp
- code/graphics/render.h
This PR adds scaling and mirror parameters to a few more bitmap drawing methods. These are required for the upcoming HUD Config overhaul.
I also took the opportunity to document what the parameters of some of these functions do after I spent a lot of time figuring it out the hard way.
> Add scaling features to additional bitmap drawing methods

- code/popup/popup.cpp
- code/popup/popupdead.cpp
- code/scripting/global_hooks.cpp
There was one conditional popup that did not work with the `OnDialogFrame` hook and this fixes that. This one is most easily tested by going to the PXO lobby. This also adds the `Text` HV variable to `OnDialogFrame` because the text can change each frame here.
Additionally it adds `gr_flip()` to the conditional dialog frame hooks because otherwise they will never render until the hook is completed and the game renders the frame after that.
> Add missed popup for on dialog frame and add text hook var

- code/missionui/missionweaponchoice.cpp
Inferno reported a bug where the unavailability of weapon A could result in weapon B being assigned to a particular weapon bank, even if weapon B was disallowed for that bank.  Add a per-bank restriction check to fix this.
> fix player weapon precedence to include per-bank restriction

- code/controlconfig/controlsconfig.cpp
- code/controlconfig/controlsconfig.h
- code/controlconfig/presets.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/control_config.cpp
First, add a boolean to allow SCPUI to overwrite presets.
Second change the warning about duplicate presets to an in-ui popup if we're actually in the control config game state. The popup is also triggered during the FSO splash screen, so that's why it checks the game state first.
> Some minor Control Config UI changes for SCPUI

- code/menuui/mainhallmenu.cpp
- code/menuui/mainhallmenu.h
- code/scripting/api/libs/ui.cpp
Provides a method for lua to set the current mainhall. If used in the mainhall menu then the menu will change immediately. If used outside the mainhall menu then enforce must be set to true to make sure the request is honored. As a bonus you can enforce a mainhall indefinitely if desired.
> Lua set mainhall

- code/actions/types/MoveToSubmodel.cpp
- code/actions/types/ParticleEffectAction.cpp
- code/actions/types/PlaySoundAction.cpp
- code/camera/camera.cpp
- code/debris/debris.cpp
- code/decals/decals.cpp
- code/hud/hudtargetbox.cpp
- code/model/modelread.cpp
- code/model/modelrender.cpp
- code/network/multimsgs.cpp
- code/object/object.cpp
- code/object/object.h
- code/object/objectdock.cpp
- code/scripting/api/objs/object.cpp
- code/ship/ship.cpp
- code/weapon/weapons.cpp
Make these convenient functions even more convenient:
1. Change `object_get_model()` to `object_get_model_num()` and `object_get_model_instance()` to `object_get_model_instance_num()` to more accurately reflect what they do
2. Add new `object_get_model()` and `object_get_model_instance()` functions to return `polymodel*` and `polymodel_instance*` values.
> tweak object model/instance convenience functions

- fred2/fred.cpp
At some point between 2002 and 2006, the Update_window code was removed, but since we don't have FRED history from that period, we don't know the exact rationale.  However, since FRED appears to have no difficulty rendering every frame, and since there may be parts of FRED that don't set Update_window when they need to (for example, the background editor), let's keep this disabled.
Follow-up to #6435.  Fixes the background not updating when a bitmap is moved in the background editor.
> re-remove Update_window check

- code/ai/aicode.cpp
Kamikaze ships entering broadside mode (`ai_cruiser_chase()`) would always point toward the center of the ship.  With this fix, they will point toward a subsystem if attacking one.
~~An ai_profiles flag enables this fix.~~ Turns out, the flag is not needed because capships normally can't be issued the attack-subsystem order.
> fix kamikaze attack of subsystems

- code/mission/missiongoals.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
Adds an overridable On Mission Objectives Changed hook that runs when an objective is failed or completed. Overriding the hook only overrides display and music methods. The objective state still gets added to the mission log and all background logic continues.
> Mission goals hook

- code/graphics/render.cpp
PR #6481 added scaling ability to VFonts but got lucking in its clipping checks in that almost all `gr_string()` calls occur while the clip region is set to the screen size. There are a few edge cases that set the clip region to a specific bounding box. So we have to do our clipping checks before we do the coordinate offsets.
Took the opportunity to just cleanup the `gr_string_old()` function a touch while I was at it again; moved variable declarations to where they are actually used.
Fixes #6531
I'll add that I did a full dive into the original clipping code that was present and have again concluded it's not necessary. Much of it was intended to display only partial characters if part of the character was clipped. It would do this by adjusting the UV coordinates from which to get the …
> Fix input text string rendering

- code/scripting/api/libs/mission.cpp
Looking through all places in the scripting API where `l_Object.Set()` is called, here is one where we might want to know about the object's breed.
(Normally we would return the result of `ade_set_object_with_breed()`, but the `testLineOfSight_internal()` function has multiple return arguments.)
> make line-of-sight objects aware of its subclasses

- fred2/eventeditor.cpp
- qtfred/src/ui/dialogs/EventEditorDialog.cpp
The `query_modified()` function in FRED did not correctly check whether messages were modified, although interestingly, it did so in qtFRED.  Even in qtFRED, there were a few minor omissions.  Overall, this fixes FRED and syncs up the FRED and qtFRED versions.
Fixes #6528.
> fix event editor modification check

- code/menuui/mainhallmenu.cpp
`On Dialog Start` (used in SCPUI and within `popup_init`) reads popup options by affirmative or negative flags, and the popup for exiting the Mainhall did not set these flags. Notably, most popups that use `POPUP_NO` or `POPUP_YES`  already, so this PR sets those flags for this popup. Now `On Dialog Start` within `popup_init` has access to the correct flags.
PR tested and works as expected, both in retail UI and SCPUI
> Ensure that Ext Game Popup sends Affirmative and Negative Flags

- code/controlconfig/controlsconfig.cpp
- code/controlconfig/presets.cpp
There were 2 popup dialogs that were missing an `Affirmative` flag, which mean the button was not in the right position and thus showed a visual misalignment. This PR fixes that and in tests works as expected. Follow up to #6502 .
> Fix more Popup Button Alignments

- code/hud/hudets.cpp
- code/object/object.cpp
- code/object/object.h
- code/object/objectshield.cpp
- code/object/objectshield.h
- code/parse/sexp.cpp
- code/scripting/api/objs/ship.cpp
- code/ship/ship.cpp
- code/ship/shiphit.cpp
There is a rather large design flaw in FreeSpace debriefings... debriefing SEXPs can refer to in-mission ship data, while all ships (and all objects) are deleted as soon as the mission completes.  Specifically, `obj_delete()` is called which sets all objects to `OBJ_NONE` and marks them as freed, although the data still exists in the various arrays.  This is the use-after-free problem, but applied to the in-game object system, rather than memory accessed by pointers.
It's probably best to defer fixes to an as-needed basis.  As for hitpoint SEXPs, this change updates them to use the object and ship references from the ship registry, since the ship registry is not cleared by the time the debriefing is loaded.  (Using `objp->instance` and `shipp->objnum` at this point would be problematic.) …
> make hitpoint sexps safer to use in debriefing

- code/controlconfig/controlsconfig.cpp
- code/graphics/2d.cpp
- code/graphics/opengl/gropengltexture.cpp
This PR does a few very minor but useful cleanups to defaults. (Alas, a lot of text for very simple PR)
1) In Controls Config, the text asking users to type a new preset name specifies early on that the name should not be a default preset (this is just an extra 4 works in the string message, but useful and still easily fits in the box).
2) Allows the new `default_settings.tbl` to parse `WindowMode`. Overall this just means mods can set defaults for windowmode themselves if using the new in-game options and the new `default_settings.tbl`. This option was previously commented out, but it was found quite useful to have it actually be accessible to modders.
3) Set the defaults for the new in-game options to Trilinear instead of Bilinear and do now allow the MSAA to be 16x since even on …
> Cleanup few In-game Defaults

- code/parse/sexp.cpp
Any NaN encountered in the evaluation of `functional-if-then-else` should be isolated to the branch on which it occurs.  Fixes #6536.
Also improve some help text for clarity.
> fix NaN for functional-if-then-else

- code/parse/sexp.cpp
If we have a child enum and we don't have a defined parameter index then the code returns the last parameter index used for $repeat situations. (You could have multiple child enums all referencing sexp parameter 1 for example. However, parameter index can validly be "-1" which means get the sexp parameter just before this one.
In the case of repeat this was erroneously returning the "-1" directly when it should copy the method above instead.
And then since I knew Clang was gonna complain about things here I just went ahead and rewrote the whole thing to use an iterator and const auto references instead.
> Fix child enums in lua sexps

- code/parse/sexp_container.cpp
Fix a few issues with map containers:
1. `add-to-map` wasn't replacing data if the key already existed in the map, despite the documentation saying that it would.
2. `remove-from-map` displays a warning if the key isn't in the map, when printing to the log would be sufficient.
3. Disallow all attempts to use `add-to-map` on a map container while it is being used in a special argument SEXP.
Fixes Issue #6549.
> Fix map container mutation issues

- code/pilotfile/csg.cpp
- code/pilotfile/pilotfile.h
I somehow ended up with a player campaign file that had me on mission 29/6. That ended up causing the game to try and load things like the mainhall from an invalid mission reference in the Campaign array. We already have pretty good handling downstream of this issue so this PR simply activates the invalid mission data bool that was previously unused. It will cause a popup warning of bad campaign data, prompting the player to choose a different campaign, a different mod, or reset the campaign.
> Check for invalid player progress

- code/ai/aibig.cpp
This function call checked the acceleration of the targeted object, rather than the active object as it should have.  Fix it to check the active object.  For mods that use `$Random Sidethrust Percent:` (such as Inferno), this fixes a bug that could cause an invalid memory access in situations where the targeted object is -1.
> fix random sidethrust call

- code/graphics/render.cpp
- code/graphics/software/FSFont.cpp
- code/graphics/software/FSFont.h
- code/graphics/software/font.cpp
Further align functionality between Volition fonts and TrueType fonts with auto scaling. VFNTs don't save their size in quite the same way as TTFs so we have to calculate the auto scale at draw time instead.
Also make sure that fonts do not auto scale in FRED.
> Allow VFNTs to auto scale and disallow auto scaling in FRED

- code/ai/ai.h
- code/ai/aicode.cpp
- code/ai/aiturret.cpp
- code/fireball/fireballs.cpp
- code/globalincs/pstypes.h
- code/graphics/2d.cpp
- code/graphics/opengl/gropenglbmpman.cpp
- code/graphics/render.cpp
- code/jumpnode/jumpnode.cpp
- code/menuui/techmenu.cpp
- code/missionui/missionweaponchoice.cpp
- code/model/animation/modelanimation.cpp
- code/model/model.h
- code/model/modelread.cpp
- code/model/modelrender.cpp
- code/model/modelreplace.cpp
- code/model/modelreplace.h
- code/nebula/volumetrics.cpp
- code/object/collideshipship.cpp
- code/playerman/playercontrol.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/ship/shiphit.cpp
- code/starfield/starfield.cpp
- code/starfield/supernova.cpp
- code/tracing/FrameProfiler.cpp
- qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
Several changes related to the volumetrics model fix:
1. Update the `model_load()` prototype with better parameter names, including a new `ErrorType` enum defined in pstypes.h
2. Update the `MIN`, `MAX`, and `CLAMP` macros, all of which were susceptible to performance issues because they duplicated their tokens.  This could cause functions or calculations to be re-run unnecessarily.  Since the codebase is now on C++17, `std::clamp()` can be used.
3. Update the rest of the codebase to fix any associated issues.
~~Currently in draft as this depends on #6505.~~
> a few pstypes changes and refinements

- code/parse/parselo.cpp
- code/parse/parselo.h
- code/parse/sexp/LuaSEXP.cpp
This type for subsystems is analogous to the shipname type for ships.  Sometimes it is useful to refer to a subsystem even if its parent ship is not present.  Whereas the subsystem object would be invalid, the subsystemname string still contains the string that the mission designer specified.
Relatedly, upgrade the parsing of `+Parent Parameter Index:` to be checked on both parented and non-parented parameters.  This will help both modders who put the field in the wrong place and programmers who may want to add a parented parameter in the future.
> add subsystemname scripted sexp type

- code/hud/hudparse.cpp
Adds parsing for the "Active by default:" flag that custom gauges have to scripted gauges so they can be off until enabled via sexp.
> Allow scripted gauges to be off by default

- code/mission/missionparse.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Adds a game_settings.tbl flag to force preloading models used for briefing icons. This runs in mission post-process so it only loads models used for icons that haven't already been loaded for the mission.
This is useful for SCPUI's where hovering over an icon shows the model without having to click on it and the stutter when it loads models not used in mission is super obvious and a poor player experience.
> Allow preloading briefing icons

- .gitmodules
Use the repository URLs, rather than @asarium's user-specific URLs.  Follow-up to #6552.
> update .gitmodules references

- code/missionui/fictionviewer.cpp
- code/missionui/missioncmdbrief.cpp
- code/missionui/missionweaponchoice.cpp
- code/missionui/missionweaponchoice.h
Use the existing definitions to improve code readability.
Also rename _SETTINGS to _LAYOUTS for some definitions as it's more descriptive.
> reduce magic numbers in missionweaponchoice

- code/debris/debris.cpp
- code/model/modelread.cpp
- code/model/modelrender.cpp
- code/object/collideshipweapon.cpp
- code/particle/EffectHost.h
- code/particle/ParticleEffect.h
- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
- code/particle/hosts/EffectHostObject.cpp
- code/particle/hosts/EffectHostObject.h
- code/particle/hosts/EffectHostSubmodel.cpp
- code/particle/hosts/EffectHostSubmodel.h
- code/particle/hosts/EffectHostVector.cpp
- code/particle/hosts/EffectHostVector.h
- code/ship/ship.cpp
- code/ship/shipfx.cpp
- code/utils/modular_curves.h
- code/weapon/beam.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
A followup to #6465.
Note: This is _not_ a behavioural change wrt. to 24.2, but it is a small change to current nightly. As such, it'd be great to include it in 25.0 as to avoid needing a flag to guard the behaviour change.
The main change, apart from a few tiny bugfixes, is that this PR will properly "parent" particle sources to things.
For example, impact spew and other similar particles were just anchored in space, rather than at the ship that was spewing. This has multiple detrimental effects:
1. Modular curves don't have access to the ship data
2. If your particle source has a lifetime > 0, your particles are in  the wrong place as the emitting ship will have moved (this also applies to rotating submodels, which'll now be accounted for when a spawner is attached to one)
4. You cannot …
> Unify Particle Attachment

- fred2/createwingdlg.cpp
- fred2/management.cpp
- fred2/management.h
- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/mission/dialogs/FormWingDialogModel.cpp
When forming a wing, if there is a name conflict but the ship will actually be used in the wing, don't report the conflict.  Fixes #6572.
> fix wing creation dialog

- code/globalincs/utility.h
- code/parse/sexp.cpp
- fred2/OperatorComboBox.cpp
Allow `stringcost()` to use a specified function to check equality, and provide both case-sensitive and case-insensitive sample functions.  Use case-insensitive checks for sexp operator lookup.
> allow stringcost to be case-insensitive

- code/mission/missiongoals.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Previously, directive counts were not shown if the value was <= 1. This PR adds a flag to always show the value, and tests work as expected. It also fullfills a longstanding statement from Mage
```
given that, aside from directive-value, all the code involving Directive_count seems to be volition:-original, it really is past time for a flag skipping this > 1 check
```
> Allow mods to Always Show Directive Value Count

- code/object/collideshipweapon.cpp
As discovered by PDFCommand and tracked down by Asteroth, there was another "missed target" check in `ship_weapon_check_collision()`, in addition to the more comprehensive check in `weapon_home()`.  Since the check is redundant and there is an existing `$Fixed Missile Detonation:`, skip the check if the flag is active.
> addendum to fixed missile detonation

- code/hud/hudsquadmsg.cpp
- code/missionui/missionshipchoice.cpp
- code/parse/sexp/LuaSEXP.cpp
- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/waypoint.cpp
- code/ship/ship.cpp
- code/ship/ship.h
1. Change `ship_get_type` to return its string directly, to avoid the need for a temporary variable
2. Add `tostring()` functionality for additional objects besides ships and weapons, to aid in script debugging
3. For an `OPF_POINT` scripted parameter, return it directly.  Since it is always a single specific type, it should not be wrapped in OSWPT.
Item 3 is a minor breaking change, as scripts now access the waypoint directly rather than unwrapping it with a `:get()` call.
> misceallaneous small fixes and tweaks

- code/ai/ai.h
- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/ai/aigoals.h
- code/scripting/api/objs/order.cpp
- code/scripting/api/objs/ship.cpp
- code/scripting/api/objs/waypoint.cpp
Allow waypoint orders to target a specific waypoint and go in reverse.  Add script access to waypoints and waypoint lists belonging to orders.
Fix assignment of targets and goal start times.  Assign targets when they are different (and thus need to be assigned), not when they are the same.
> update script API for AI orders

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
`$AI Shield Manage Delay:` can be set in the AI profiles, but also set for AI specific classes. Currently, The values set for the specific AI class are only used `if (iff_x_attacks_y(Player_ship->team, Ships[objp->instance].team))`, otherwise the values in the AI profile are used.
Being able to have the shield delay work in a unified way according to the AI class values is very useful, especially for friendly wingmen that you want have different shield manage delays.
This PR adds a AI profiles flag to unify Shield Manage Delay behavior, so that it always works in the same way regardless of AI team conditions.
> Unify AI Usage of Shield Manage Delay

- code/menuui/optionsmenu.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
It would be very useful to know which options tab is active (IE Options, Multi, Detail) but it's all under one single Game State `GS_STATE_OPTIONS_MENU`.
This PR creates a hook,  'On Options Menu Tab Changed'  that returns the value of the newly switched to options tab. Lafiel and I both discussed making this an ENUM, but the ENUM list is already quite bloated and this integer value seems like the cleanest solution.
> Create scripting hook: 'On Options Menu Tab Changed'

- code/camera/camera.cpp
- code/gamesnd/eventmusic.cpp
- code/globalincs/systemvars.cpp
- code/graphics/opengl/gropengltexture.cpp
- code/graphics/post_processing.cpp
- code/graphics/shadows.cpp
- code/lighting/lighting.cpp
- code/nebula/neb.cpp
- code/playerman/playercontrol.cpp
- code/sound/sound.cpp
- code/starfield/starfield.cpp
- code/weapon/shockwave.cpp
- freespace2/freespace.cpp
Now that default_settings.tbl is merged, this PR adds parsers to many of the in-game options so that they can be set by it. There are a few others that could probably be added in the future if anyone wants them, but these are the important ones, I think.
> Add many options to default settings table

- code/io/joy-sdl.cpp
Are you tired of having to restart FSO each time you change your joystick/controllers in-game? Well be tired no more, because now joysticks/controllers can be set and changed without having to restart FSO! 
Massive thanks to @MjnMixael for all his help collaborating on this quality-of-life enhancement (and to @BMagnu for addressing our questions).  Overall, the ability to set joysticks within FSO not only helps folks tuning controls but also creates a much more streamlined and modern process for new players. Previously, new players would start the game, have to set joysticks, and then restart the game before they could play and use their controls. Now, players can launch the game, setup their controls with as much iteration as they want and directly play the game right away. 
Tested and …
> Update in-game joystick settings to work without restarting FSO

- code/lighting/lighting.cpp
- code/lighting/lighting.h
- code/localization/localize.cpp
- code/ship/ship.cpp
After testing and consideration, this PR adds the Cockpit Deferred setting to the in-game options. Also adds a parser to the new default_settings.tbl.
> Make Cockpit Deferred an In-game Option

- code/ship/ship.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Follow-up to #5803. Adds another firing loop sound specifically for when primaries are linked. Requires a few extra cases in `ship_primary_changed` to handle linkage status changing while firing.
> add linked loop firing sounds

- code/particle/ParticleParse.cpp
Turns out, in this specific case, the name of the main (i.e. front) particle wasn't correctly set (but rather taken from the source effect), as such giving the particle an incorrect name in this case.
Followup to #6465.
> Fix particle name assignment when using legacy-type composite effects that address child effects by name

- code/menuui/optionsmenu.cpp
- code/menuui/optionsmenumulti.cpp
- code/menuui/optionsmenumulti.h
- code/network/multi_options.cpp
- code/network/multi_pxo.cpp
- code/pilotfile/plr.cpp
Follow-up to #6595. 
Currently there are many options that do not get discarded/reverted when pressing the escape button while in the options menu (all other screens I tested properly discarded changes when pressing escape). I had thought I would have to make a backup function for every slider and value that was not getting properly discard, but it turns out the reason they were not getting properly discarded is b/c the rest of the on frame function was setting them after the escape button section.
Tested and works as expected. 
EDIT: This PR does a few things
1) Makes all discard behavior consistent with the options tabs using the following protocols: Escape will close the screen and discard changes by default (just as it has been for most options). Pressing a button to navigate to any …
> Fix changes to Options not properly discarding when escape key pressed

- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- code/ship/shiphit.cpp
1. Refactor `num_hits` to `num_sparks` and `MAX_SHIP_HITS` to `MAX_SHIP_SPARKS` to be consistent with their current (since FS1 pre-release) usage.
2. Remove the unused `HP_SCALE`.
3. Always initialize at least one spark pair.  If `choose_next_spark()` was entered when `num_sparks` was 1, `num_spark_pairs` would be 0 and none of the spark pairs would be initialized.  Consequently, accessing the pair at index 0 would return garbage data.
4. Iterate through `num_spark_pairs` when counting the indexes, rather than the hardcoded (and incorrect) magic number 6.
Fixes a crash discovered by Dawnesya that can only occur when a ship has both the "fighter" and "cruiser" flags.  Normally, fighters never enter the `choose_next_spark()` function and 'big' ships always have at least 3 sparks.
> several fixes to ship sparks

- code/camera/camera.cpp
- code/hud/hudtargetbox.cpp
- code/observer/observer.cpp
- code/observer/observer.h
- code/physics/physics.cpp
- code/playerman/playercontrol.cpp
- code/radar/radarsetup.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- freespace2/freespace.cpp
1. Allow `ship_get_eye` to be used for any objects, not just ships
2. Remove the unused `from_origin` parameter and change it to `local_reference_frame`
3. Simplify the implementation and take advantage of upgrades to `model_instance_local_to_global_*` functions
4. Consolidate `ship_get_eye_local` into `ship_get_eye`
This is a prerequisite to an upcoming PR by LuytenKy.
> refactor ship_get_eye

- code/menuui/optionsmenu.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
Complements #6591. This PR creates a hook, 'On Options Menu Closed' that provides a hook variable of `hv.OptionsAccepted` which is true if the options are accepted/saved, false if the options are discarded and not accepted/saved.
Happy to refine text/names however folks might want.
> Create scripting hook: 'On Options Menu Closed'

- code/controlconfig/controlsconfig.cpp
- code/localization/localize.cpp
There were two rather prominent strings shown in popup windows related to the more modern control presets that were never localized. This PR localizes them to allow for proper translation support.
> Localize a missing Controls Popup text string

- code/controlconfig/controlsconfig.cpp
- code/hud/hudconfig.cpp
- code/scripting/global_hooks.cpp
- code/scripting/global_hooks.h
Completes the full set of options screens with regards to scripting hooks by adding `On HUD Config Menu Close` and `On Control Config Menu Close`. Complements #6604.
> Create scripting hooks HUD and Control Config Close

- code/gamesnd/eventmusic.cpp
- code/gamesnd/gamesnd.cpp
When searching to see if there is an extension mismatch for a soundtrack audio file, go ahead and substitute the mismatched extension if found.  Matching extensions is important, so continue to display a Warning; but for the benefit of players and out-of-maintenance mods, it is more friendly to play the mismatched file even if the audio data is inaccurate.
Also clarify which sound type is being parsed when warning about retail-style sounds.
> audio QoL update

- code/hud/hud.cpp
- code/hud/hud.h
Adds config rendering methods to the gauges contained in hud.cpp.
The general process for config rendering:
1. Convert the gauge coordinates and scale to the hud config coordinate system (which can be any coords and scale with the lua API rendering methods).
2. Use those values to get the size of the gauge, often from the assigned bitmap info, and pass that to HUD Config to check when the mouse is over that particular gauge.
3. Adjust the rendering method to skip code that requires a valid mission to be running and/or a valid mission object and instead fill in the various data with stand-in values.
4. Pass everything to the render methods.
Some gauges got commented out updates in case HUD Config is upgraded in the future to allow configuration of more than the base 30 or so gauges that …
> HUD Config Rendering Methods PR 1/7

- code/hud/hudconfig.cpp
- code/hud/hudconfig.h
- code/hud/hudescort.cpp
- code/hud/hudescort.h
- code/hud/hudets.cpp
- code/hud/hudets.h
- code/hud/hudlock.cpp
Adds config rendering methods to the escort and est gauges; preliminary support for the lock gauge.
The general process for config rendering:
1. Convert the gauge coordinates and scale to the hud config coordinate system (which can be any coords and scale with the lua API rendering methods).
2. Use those values to get the size of the gauge, often from the assigned bitmap info, and pass that to HUD Config to check when the mouse is over that particular gauge.
3. Adjust the rendering method to skip code that requires a valid mission to be running and/or a valid mission object and instead fill in the various data with stand-in values.
4. Pass everything to the render methods.
Some gauges got commented out updates in case HUD Config is upgraded in the future to allow configuration of more …
> HUD Config Rendering Methods PR 2/7

- code/controlconfig/controlsconfigcommon.cpp
- code/localization/localize.cpp
There were rather prominent strings shown for joysticks that were never localized. This PR localizes them to allow for proper translation support.
> Fixes missing XSTRs for Joysticks

- code/gamehelp/gameplayhelp.cpp
If a control is disabled it does not appear to players in the Controls Configure screen, thus it should also not appear to players in the F1 Gameplay Help screen.  This PR adds a simple early return within `gameplay_help_init_control_line` to fix this issue.
> Hide Disabled Controls in the F1 Screen

- code/camera/camera.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Original issue post https://github.com/scp-fs2open/fs2open.github.com/issues/6509. This flag controls if set-camera-host sexp uses the model's eyepoint for the camera position and orientation when no submodel is specified.
Without the flag, the camera will use the model's origin position and orientation.
> Model eyepoint for set camera host flag

- code/model/modelread.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
1. Trim trailing whitespace on any property values, just as leading whitespace is trimmed.  All places where `get_user_prop_value()` is used implicitly or explicitly require this.
2. Warn the user if an invalid `$special` value is parsed.  This would have caught #1, and will now catch related errors, such as misspellings, in the future.
3. Enhance `string_lookup()` with the ability to print the list being searched, if desired.  Remove an unused version of `string_lookup()`.
4. Check for lower-detail submodels being recognized as subsystems.
> enhance detection of model property errors

- freespace2/freespace.cpp
Currently, the cursor does not revert correctly after visiting F3 options screen or lab due to IMGUI unsetting the FSO cursor image.
This PR reloads the FSO cursor image when those screens end. Fixes #6436.
> Fixes cursor not restoring when exiting IMU GUI

- code/radar/radar.cpp
- code/radar/radar.h
- code/radar/radardradis.cpp
- code/radar/radarorb.cpp
- code/radar/radarorb.h
- code/radar/radarsetup.cpp
- code/radar/radarsetup.h
Adds config rendering methods to the orb and standard radar gauges.
The general process for config rendering:
1. Convert the gauge coordinates and scale to the hud config coordinate system (which can be any coords and scale with the lua API rendering methods).
2. Use those values to get the size of the gauge, often from the assigned bitmap info, and pass that to HUD Config to check when the mouse is over that particular gauge.
3. Adjust the rendering method to skip code that requires a valid mission to be running and/or a valid mission object and instead fill in the various data with stand-in values.
4. Pass everything to the render methods.
Some gauges got commented out updates in case HUD Config is upgraded in the future to allow configuration of more than the base 30 or so gauges that …
> HUD Config Rendering Methods PR 7/7

- code/ai/ai.h
- code/globalincs/pstypes.h
- code/globalincs/utility.h
- code/graphics/opengl/gropengltexture.cpp
- code/graphics/shadows.cpp
- code/menuui/techmenu.cpp
- code/mission/missionparse.h
- code/missionui/missionshipchoice.cpp
- code/missionui/missionweaponchoice.cpp
- code/network/multiteamselect.cpp
- code/object/object.h
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/playerman/playercontrol.cpp
- code/scripting/api/objs/shipclass.cpp
- code/scripting/api/objs/weaponclass.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/weapon/weapon.h
- code/weapon/weapons.cpp
Use `std::unique_ptr` rather than `vm_malloc` and `vm_free` to handle optional strings in ship classes.  This makes the code more robust and increases memory safety.  This also allows several string variables to be consolidated in the ship class and weapon class script APIs.
Also add new `stuff_string()` overloads and a new `F_TRIMMED` string parsing type to handle the new fields and the string trimming done inside `stuff_malloc_string()`.
> std::unique_ptr refactoring

- code/parse/parselo.cpp
- code/parse/parselo.h
Upgrade `parse_get_line` to detect all three EOL types: CR, LF, and CRLF.  The function is now more robust against line ending mismatches and will now also warn the modder if a file contains mixed line endings.
Fixes #6395.  Tested with various strings, files, line endings, and lengths; all cases work as expected.
> upgrade line parsing and end-of-line checks

- code/hud/hudwingmanstatus.cpp
Fixes wingmen conditional check, thanks for Goober for catching this.
For reference, original check was
```
for (i = 0; i < MAX_SQUADRON_WINGS; i++) {
if ( !(HUD_wingman_status[i].used) || (HUD_wingman_status[i].ignore) ) {
continue;
}
renderDots(i, count, num_wings_to_draw);
count++;
}
```
> Update conditional check for wingmen dots

- code/nebula/neb.cpp
- code/nebula/neb.h
- qtfred/src/mission/missionsave.cpp
1. `Neb2_poof_flags` is a ubyte array, and so should be of type ubyte[], not ubyte
2. Save the substitute main hall in qtFRED
> a few minor fixes

- code/hud/hudshield.cpp
The HUD table allows modders to set a filename for the HUD Mini Shields Gauge. FSO will parse this and load in the bitmap on game initiation, but this custom named animation ends up not being used b/c there is another `bm_load_animation` call within `hud_shield_level_init`. It seems back in 2010 "Antipodes 7 Merge: HUD Overhaul" Swifty set this as a hardcoded name. Ultimately though, the HUD gauges have been updated since then, specifically with `HudGaugeShieldMini::pageIn()`, and there is no longer a need to page in bitmaps at the start of each level (other gauges also no longer do this properly). This PR removes that relic page-in call, adds a comment for clarification.
> Fix mini-shield custom filename

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/hud/hudets.cpp
Mods such as FotG disable the controls for transferring energy between the shields and weapons for multiple reasons (such as being very difficult to balance, especially with varying weapon recharge rates). Even with the player having that ability disabled, the AI still currently is able to do this.
This PR creates a AI profiles flag to also prevent the AI from using the energy transfer ability. Note, it is set as a AI profiles flag since it's a higher order option related to if mods overall allow this ability or not.
> Allows mods to fully disable energy transfering

- code/scripting/api/objs/subsystem.cpp
Currently if you try to set a subsystem's hit points via scripting it only sets the value to 0 b/c of what was likely a copy paste bug. This 1 line PR fixes that. Tested and fix works as expected.
> Fix script setting of subsystem hitpoints max

- .github/workflows/weekly-coverity-scan.yaml
Coverity hasn't run since September 27.  A close look at the log shows that the workflow makes it almost all the way through but fails on the "Upload to Coverity" step:
`fatal: detected dubious ownership in repository at '/__w/fs2open.github.com/fs2open.github.com'`
There are various questionable ways that people have tried to fix this, but it might be possible to completely avoid the issue by not using `git` in that step.  So let's try to get the commit hash from GitHub context rather than by running `git rev-parse HEAD`.
> attempt to fix Coverity

- code/hud/hudets.cpp
- code/hud/hudshield.cpp
- code/mission/missionparse.cpp
- code/network/multi_ingame.cpp
- code/network/multi_obj.cpp
- code/network/multimsgs.cpp
- code/object/object.cpp
- code/object/object.h
- code/object/objectshield.cpp
- code/parse/sexp.cpp
- code/scripting/api/objs/multi_objects.cpp
- code/scripting/api/objs/object.cpp
- code/scripting/api/objs/shields.cpp
- code/ship/shield.cpp
- code/ship/ship.cpp
- code/ship/shiphit.cpp
Remove the `n_quadrants` field because it is entirely redundant to the size of `shield_quadrant`.  Also, be more rigorous about the difference between `shield_get_quad(i)` (which can fluctuate) and `shield_quadrant[i]` (which gives the exact quadrant strength).  Finally add some C++ casts and move some checks to better places.
> some refinement of shield quadrants

- code/parse/parselo.cpp
When an orientation matrix is constructed using one or more vectors, all such vectors must be normalized.  Previously, the code did not enforce this for matrices parsed from a mission or table file.  Although FRED will use correct matrices, it also truncates floating point values to six decimal places, so non-normalized vectors might be written to the mission file as happened in #6632.  And there is always the possibility that someone could manually edit the mission file to corrupt the matrices.
While we're at it, per suggestions from Asteroth and qazwsxal, make sure the matrix is orthogonal as well.  The `vm_fix_matrix` function handles all relevant calculations.
Fixes #6632.  Follow-up to #6596.
> ensure matrices are well-behaved

- code/scripting/api/objs/shipclass.cpp
Actually return the correct value in the function.
Followup to #6607, fixes #6635.
> Fix Ship Class Scripting API

- code/hud/hud.cpp
- code/hud/hud.h
- code/hud/hudconfig.cpp
- code/hud/hudconfig.h
- code/hud/hudescort.cpp
- code/hud/hudets.cpp
- code/hud/hudlock.cpp
- code/hud/hudmessage.cpp
- code/hud/hudobserver.cpp
- code/hud/hudparse.cpp
- code/hud/hudreticle.cpp
- code/hud/hudshield.cpp
- code/hud/hudsquadmsg.cpp
- code/hud/hudtarget.cpp
- code/hud/hudtargetbox.cpp
- code/hud/hudwingmanstatus.cpp
- code/localization/localize.cpp
- code/mission/missiontraining.cpp
- code/parse/sexp.cpp
- code/pilotfile/csg.cpp
- code/pilotfile/plr.cpp
- code/radar/radar.cpp
- code/radar/radarorb.cpp
- code/scripting/api/libs/hud.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/hudconfig.cpp
- code/scripting/api/objs/hudconfig.h
This is the final step of the HUD Config Overhaul. This sets up the HUD Config menu to render the gauges using their native draw methods rather than the built-in placeholders. Much of the old hardcoded data has been removed. This comes with upgrades to the UI API as well.
This is a bare-bones overhaul for the moment. No new features other than utilizing the native rendering code with the exception of being able to preview multiple HUDs with the LEFT and RIGHT keys. A later follow-up PR is planned that will allow custom coloring individual custom gauges and possibly unique coloring per-HUD for each player.
Setting as draft because this PR relies on #6573, #6574, #6575, #6576, #6577, #6578, #6579 . No sense in reviewing this until those are merged.
> Hud config upgrades

- code/hud/hudreticle.cpp
Fixes a bug where the fire-point and flight cursor position components of the center reticle were improperly calculated. Also fixes bug where the fire-point component was missing an argument for `renderCircle`.
Tested and fixes work as expected.
> Fix fire-point and flight cursor positions

- code/fireball/fireballs.cpp
- code/fireball/fireballs.h
- code/fireball/warpineffect.cpp
- freespace2/freespace.cpp
With @Gamma39er 's recent enhancements to allow much more customization of how warps look it felt like it was as good a time as any to move these options into the tables for designers to make use of.
Players who want to override designer settings can use the _override folder added in #4711 as it was designed for.
> Move warp options to tables

- code/model/modelrender.cpp
Fixes #6606.
The Skybox has to be rendered additively because it will not be fogged afterwards.
The alpha setting code however was overriding the blend mode if set.
> Fix fog and skybox with alpha interaction

- cmake/toolchain-gcc.cmake
`-m64` is a x86-only gcc flag and breaks configure/compile on other architectures, so move it to the appropriate section.
> fix compilation on linux arm64

- code/mission/missionparse.cpp
If the player starting ship name does not refer to an actual ship, gracefully fail to load the mission instead of crashing.
> handle starting shipname mismatch

- code/localization/localize.cpp
- code/menuui/mainhallmenu.cpp
- code/mission/missioncampaign.cpp
- code/mission/missioncampaign.h
- code/popup/popup.cpp
- code/popup/popup.h
- code/scripting/api/libs/mission.cpp
Improve skipmemymissionyo in several ways, based on RedMageJoe's recent experience:
1. Allow spaces to be accepted in the mission prompt
2. If the requested mission can't be found, just abort rather than restarting the entire campaign
3. Clarify that the prompt needs a filename and add a message if the mission can't be found
4. Improve handling of the .fs2 extension
5. Fix a bounds check in `popup_input`
> skipmemymissionyo fixes

- code/actions/types/ParticleEffectAction.cpp
- code/ai/aicode.cpp
- code/ai/aiturret.cpp
- code/camera/camera.cpp
- code/camera/camera.h
- code/hud/hudtarget.cpp
- code/hud/hudtargetbox.cpp
- code/math/staticrand.cpp
- code/math/vecmat.cpp
- code/model/modelread.cpp
- code/playerman/playercontrol.cpp
- code/render/3ddraw.cpp
- code/scripting/api/objs/subsystem.cpp
Although normalized vectors in FSO are supposed to stay normalized, occasionally small floating point errors can pop up.  In most cases these do not cause a problem, but in certain cases these errors can rapidly accumulate and corrupt an otherwise well-behaved matrix.  This can most easily be seen with daisy-chained dock sequences or docked ships with angled dockpoints.
This PR audits the usage of `vm_vector_2_matrix_norm` to re-normalize vectors in cases where floating point errors could accumulate.  There are also a few new Assertions for extra vigilance.
Follow-up to #6596.  Fixes #6634.
> fix normalized vector handling

- code/render/3d.h
- code/render/3ddraw.cpp
- code/starfield/starfield.cpp
Fixes #5990.
This was caused because when rendering the sun, we used a function for 2d billboard rendering.
This function would adjust the size based on z-distance to the camera.
While possibly sensible for true billboard particles, when rendering the sun, we don't want it to appear larger as it approaches the screen edge (where it has a lower z distance, as it's always a unit-vector far away, including x and y measured from the screen center). Especially not since we don't actually check whether it's offscreen (so that the sun can go slightly offscreen, but have parts of the bitmap still shown), so when it's just shy of 90° it'll be rendered at a very large size which can cover the entire screen. Not sure why this is not happening in non-VR gameplay, but oh well.
To fix this, for objects …
> Fix VR sun popups

- code/decals/decals.cpp
- code/decals/decals.h
- code/graphics/opengl/ShaderProgram.cpp
- code/graphics/opengl/ShaderProgram.h
- code/graphics/opengl/gropenglshader.cpp
- code/graphics/opengl/gropenglshader.h
- code/io/cursor.cpp
- code/io/cursor.h
- code/io/joy-sdl.cpp
- code/model/animation/modelanimation.cpp
- code/model/animation/modelanimation.h
- code/object/object.cpp
- code/object/object.h
- code/scripting/api/objs/player.cpp
- code/scripting/api/objs/streaminganim.cpp
- code/scripting/api/objs/texture.cpp
- code/scripting/lua/LuaReference.cpp
- code/utils/event.h
For every move and move-assignment constructor, do the following:
1. Make it default if possible
2. Add or delete where appropriate
3. Check for move-onto-self
4. Apply `std::move` where needed
Also fix problematic moves in `player_h`
> audit move semantics in the codebase

- code/options/default_settings_table.cpp
In-game options may be removed/inaccessible, such as VR mode removing the Window, but still valid for listing in the `default_settings.tbl` table.
In other words, we don't want error messages displaying if a player is playing  in VR mode (which will remove the Window option for that instance) but the window option is listed in the table.
Thus, downgrade the error to a debug print for options within the `default_settings.tbl`. As MJN stated, the table itself controls the parser here, so downgrading the warning is the best choice.
> Tune how the `default_settings.tbl` handles options it cannot find

- code/model/modelrender.cpp
Previously, FSO did not show normal, AO, or misc maps at LODs 3 or higher. This was  a relic from original retail days, so this PR allows players to see those textures if the model detail level is at 3 or 4. I put this under the model slider because it is related to LODs, and b/c changing the model slider is something folks actually use compared to the other hardware tex slider which really makes things look ancient if turned to anything other than the max.
Fixes maps having a visual pop effect when changing between LODs and overall helps improved visuals of distant ships since all maps are being used.
> Allow normal, AO, and misc maps at higher detail settings

- code/missionui/redalert.cpp
Ships that red-alerted, but that departed before red-alert was triggered, would have 0 weapons on the subsequent mission.  Since exited ships do not store weapon information, that information was never saved in the red-alert status, and so `num_primary_banks` and `num_secondary_banks` would inadvertently be set to 0.  This bug has been around since the pilotfile upgrade in 2013, and apparently was common knowledge among several players, but was never reported. :-/  The fix is easy enough: skip setting weapon information if that information is not saved in red-alert status.  (We should also skip setting subsystem information in the same circumstances, although that did not cause any subsystem misbehavior.)
I recommend viewing changes with whitespace comparison turned off.
> fix a subtle red-alert weapon bug

- code/parse/md5_hash.cpp
- code/parse/md5_hash.h
- code/parse/parselo.cpp
- code/source_groups.cmake
Didn't want to step on @BMagnu 's toes but this seemed like some low-hanging fruit I could tackle quickly using the already-implemented md5 library to hash check retail's strings.tbl and weapons.tbl to downgrade warnings based on the discussion in 4723. Fixes #4723 .
> Hash check retail strings and weapons tables

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
- .github/workflows/test-pull_request.yaml
The official 1.2.1 release of humbletim/setup-vulkan-sdk was recently published.  Update the repo version and, incidentally, also the vulkan version.  See https://github.com/humbletim/setup-vulkan-sdk
Follow-up to #6582.
> update workflows to use official release of setup-vulkan-sdk

- code/hud/hudconfig.cpp
- code/hud/hudconfig.h
- code/hud/hudparse.cpp
- code/pilotfile/csg.cpp
- code/pilotfile/plr.cpp
- code/playerman/managepilot.cpp
- code/scripting/api/libs/ui.cpp
- code/scripting/api/objs/hudconfig.cpp
- code/scripting/api/objs/hudconfig.h
Instead of hardcoding the Config color presets to Green, Blue, and Amber this PR makes them definable via table and also adds a way for SCPUI to know what the colors are and what they are named.
Small change to also not hardcode the default preset file that will be used if found, also allowing it to be set via a table flag.
> Better color preset handling

- code/io/joy-sdl.cpp
- code/io/joy.h
- code/io/joy_ff-sdl.cpp
- code/io/joy_ff.h
- code/osapi/osapi.cpp
Update haptic code with changes from icculus.org tree which optimizes effect loading to better support low-memory devices and no longer requires full support of every haptic effect type. Additionally...
- avoids attempting FF init for non-haptic devices
- avoids attempting FF init for gamepads
- properly resets FF when device is hot-plugged
- better start/stop/update of effects
- avoid stopping effects unless really needed
- use timestamp for dir effect restarts instead of sys calls
- avoid playing FF effects when window is in background
- general code cleanup
> update and fix force feedback code

- code/model/animation/modelanimation.cpp
- code/model/animation/modelanimation.h
- code/model/animation/modelanimation_segments.cpp
- code/model/animation/modelanimation_segments.h
- code/utils/id.h
So, turns out not stopping a sound for the next one if its set to loop indefinitely is a bad idea.
This fix is kinda hacky in the sense that we'd really like to "stop the sound after the next loop", but that seems like we currently cannot reasonably do so.
But this can be a todo for another time.
> Fix SoundDuring animation segments with the loop flag set

- code/scpui/rocket_ui.cpp
Linux iconv does not support "UCS-2-INTERNAL" and conversion will fail if SDL is compiled with native iconv support. SDL version 2.32.2 fixed this by changing the macro to use "UCS-2" instead. Unfortunately in my tests this worked perfectly in Linux but was broken on Mac in the rocket_ui code. However simply using proper endianess appears to work on all test platforms.
Additionally this fixes a bad memory leak as SDL_iconv_string() allocates it's return string and this was never free'd before. So every character of text input resulted in a memory leak of 6+ bytes.
> fix text input crash on Linux, and plug memory leak

- code/autopilot/autopilot.cpp
- code/mission/missionparse.cpp
- code/parse/sexp.cpp
- code/playerman/player.h
- code/playerman/playercontrol.cpp
When the player's ship is under AI control and assigned a guard goal, this information would persist when the ship was returned to player control.  This would cause the player's target to be randomly reassigned.  To fix this, the AI state should be cleared when player AI is turned off.
Also change the `Player_use_ai` variable from `int` to `bool`.
Fixes a bug in Series Resurrecta, as well as potentially other bugs with other AI modes.
> fix chaotic player targeting in rare situations

- code/hud/hudwingmanstatus.cpp
- code/ship/ship.cpp
Previously, the custom wingmen dots did not update if a ship class was changed via loadout changes or hip class sexp/script changes, so this PR fixes that. It also cleans up redundancy with the wingmen dot override setting.
> Fix wingmen custom dot for ship changes

- code/ship/ship.cpp
- fred2/fredstubs.cpp
- fred2/missionsave.cpp
- freespace2/freespace.cpp
- qtfred/src/fredstubs.cpp
- qtfred/src/mission/missionsave.cpp
- test/src/test_stubs.cpp
Enhance shield checks to consider shield strength in addition to the `Intrinsic_no_shields` ship flag.  Avoid saving the no-shields flag if a ship has intrinsic no-shields.
Also make sure `Pre_player_entry` is initialized and fix a negative array access in autoaim.
> refine intrinsic_no_shields behavior

- code/def_files/data/scripts/cfile_include.lua
- code/def_files/data/scripts/forwarders.lua
- code/scripting/lua.cpp
- code/source_groups.cmake
Most mods that have used scripting in the last decade have included the same z_load_first-sct.tbm file. I honestly forgot about that file, but even BtA uses it. So I took and look and thought we should really just build all this in to increase the QoL of our scripters.
The basic forwarders like `print()` -> `ba.print()` just make too much sense not to have. I could take or leave the Globals table but it's nice to have.
I then also added Nuke's `include()` method. I'm not sure that's really necessary since we have m!m's built-in `require()` forwarder that forwards Lua's require to our cfile system already. But it can't really hurt to have it and it's likely some mods have used it.
> Build in the common z load first methods and forwarders

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/particle/ParticleEffect.cpp
- code/particle/hosts/EffectHostParticle.cpp
- code/particle/particle.cpp
This was discovered thanks to the new assertions from #6596.  For particles with 0 velocity, the code would attempt to normalize a 0,0,0 vector with predictably undesirable results.  So, pick the global `z` vector in these cases, while normalizing in the usual case.
> fix bogus direction vector in particle code

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- ci/linux/create_dist_pack.sh
- ci/post/nebula.py
- ci/post/release.mako
Github runners for Linux arm64 are now in public beta with the same free limits as normal github runners. Our Linux build images already have arm64 support so this finally enables it as part of the official workflow.
> add arm64 Linux builds to workflow

- code/hud/hudsquadmsg.cpp
- code/hud/hudsquadmsg.h
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/scripting/api/objs/comm_order.cpp
Adds a game_settings option to hide/disable the Rearm/Repair commands in the Squad Message Gauge. FotG does not use repair ships, so it is somewhat confusing to players to always see the `Rearm/Repair` order options (IE 5. Rearm/Repair Subsys and 6. Abort Rearm) and never be able to use them.
I wanted to make this PR as surgical as possible, while still giving some degree of generality, thus I went with the solution to use `active` as a true integer instead of simply an old int in the bool style. Now -1 is hidden, 0 is greyed out, and 1 is bright.
> Allow mods to hide main Rearm/Repair items in Message Gauge

- code/hud/hudparse.cpp
- code/hud/hudsquadmsg.cpp
- code/hud/hudsquadmsg.h
- code/hud/hudwingmanstatus.cpp
- code/hud/hudwingmanstatus.h
This PR adds a few assorted HUD updates/quality of life enhancements. FotG will be using these, though they are relatively general and are likely useful to most other mods, too.
1) Adds a `Ship Name Max Width:` to the Squad Message Gauge (following the same logic as the Escort Gauge). The Escort Gauge will truncate display names of ships if they are too long, that way all the text fits in the gauge without spilling over. It would also be very useful to do this with the Squad Message Gauge, as long display names can overflow out of the gauge's boundaries currently.
2) Adds `Wingname Align Mode:` to the Wingmen Gauge, which allows modders to set how the wing names are aligned. Currently they are centered on the calculated x-position, though this PR also adds right and left justification …
> Wingmen and Squad Message QoL Updates

- code/hud/hudmessage.cpp
Fixes #6679 by making sure scrollback renders even if the msg vector size is 1. The code specifically checked against 1 instead of 0 which must have been a specific choice I made but I can't remember why. Maybe I was trying to avoid rendering debug's `Game difficulty set to *medium*` message that's always added? I honestly can't remember and that wouldn't have really worked anyway. So just set this to 0 to make sure log works even with 1 message in the list.
> Display scrollback with even one message

- code/hud/hud.cpp
- code/hud/hudets.cpp
- code/hud/hudreticle.cpp
Drop shadow rendering would pollute the color context by setting the color to `gauge_color` rather than the previously calculated color. This PR saves the current color before setting it to black to render the drop shadow and then sets it back to the saved color.
Fixes #6680
Further context copied from the issue:
> Basically, each gauge's render method sets up everything for the render call and that includes setting the color using a special function to select the color based on gauge settings and that's where using IFF color comes in. Sometime after that is when the gauge will call the render method in hud.cpp, for example HudGauge::renderString().
> 
> In the render method is where the dropshadow is handled by first setting the color to black, rendering the string, and then here is …
> Make sure drop shadows don't pollute the color context

- code/def_files/data/scripts/forwarders.lua
The `println` function is a semi-recent addition to zLoadFirst-sct.tbm, while the `Globals` table should have the vector and orientation values.  The `string.starts` and `string.ends` functions were in the original version of zLoadFirst-sct.tbm but were not included in #6545, and `string.ends` is required by cfile_include.lua.
> add supplemental code to forwarders.lua

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ship/ship.cpp
- code/weapon/weapon_flags.h
- code/weapon/weapons.cpp
Though the source code for freespace 1 is not available, using some comments and lots of testing by Goober, a fairly convincing facsimile of it can be approximated. The main eventual algorithm (-1x lag pursuit, starting at 1 second out) ended up both quite close to the observed behavior and is rather simple and involves minimal changes from the existing code, making it a likely contender for what they used.
Also included are a few other observed miscellaneous changes to free flight time, the missile's speed, and early detonation conditions.
Freespace 1:
https://github.com/user-attachments/assets/d1f9f9a5-02b4-4d7d-92a3-3cf95e11f1cf
FSO, with this flag active:
https://github.com/user-attachments/assets/86c79c80-3d64-437d-934a-75766a7f9657
For reference, by default in Freespace 2, aspect …
> Add freespace 1 style missile behavior

- code/model/modelread.cpp
#6598 will now attempt to normalize and use the main eye point normal, so after parsing, before the context of this being an eye normal is lost, normalize right away and set it to forward Z if it fails. Additionally, a negative parent is normal and valid, it was mainly garbage positive parent values causing FSO issues, and also in that case set it to be positive forward, instead of right.
Fixes #6693
> Some fixes to eye point normals

- code/scripting/api/objs/animation_handle.cpp
Most of the functions in ship.cpp that operate on submodel animations are mirrored in animation_handle.cpp, but `setAnimationSpeed` was overlooked.  Add this function so it can be called from a submodel animation handle.
> add setSpeed for animations

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/ship/ship.cpp
PR #6598 caused eyepoint normals to be used for viewing direction, whereas previously the host object's orientation was used for viewing direction.  Since this could cause compatibility issues, return to the previous behavior and make the new behavior depend on a flag that is set in post-25.0 builds.  (This only applies to eyepoint normals; eyepoint *positions* were respected both before and after #6598).
> add flag to control model eyepoint normal usage

- freespace2/freespace.cpp
`VM_CAMERA_LOCKED` is true by default (i.e. primary controls move the ship, not the camera), and so should not be considered 'special' and kick the player out of top down mode. Fixes #6485
> Fix for 2d mission camera

- code/render/3d.h
- code/render/3dsetup.cpp
- code/scripting/api/libs/graphics.cpp
- code/scripting/api/objs/vecmath.cpp
For displaying things in a scene, because the eye position is not necessarily the ship position.
> add a few eye virtvars

- code/hud/hudconfig.cpp
- code/hud/hudconfig.h
- code/hud/hudescort.cpp
- code/hud/hudparse.cpp
- code/hud/hudshield.cpp
- code/hud/hudshield.h
Implement's @wookieejedi 's request to define the player and target shield icons separately for HUD Config.
This updates the logic slightly to ensure a sensible fallback hierarchy in the following priority order:
1. Local HUD-defined ship player or target
2. Global defined default ship layer or target
3. GTF Myrmidon (for retail since Myrmidon is not the first ship in retail)
4. First available shielded ship (If the selected ship can't be found)
5. If we still have nothing then return and don't draw
Finally I changed the SHIELD_HIT_PLAYER and SHIELD_HIT_TARGET defines to an enum for better safety and code clarity rather than passing around raw ints. I also renamed them to better reflect what they represent.
> Allow defining separate player and target shield icons for config

- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Both the hull and shield save conditions have had benign bugs since the original retail release.  Fix the conditions and use the `fl2i` macro.
> fix hull/shield checks in missionsave

- code/globalincs/utility.h
- code/ship/ship.cpp
If a ship changes class, the dockpoints on the new model may not match the dockpoints on the old model.  This is most likely to happen when changing a docked ship in FRED to an incompatible ship class, but it can also happen when using the `change-ship-class` SEXP.  So check the dockpoints, update them if they should be updated, and undock them if they can't.
> check dockpoints when changing ship class

- code/ai/aiturret.cpp
- code/ship/shipfx.cpp
The Input of `Trigger Radius` for curves within new particle effects was never hooked up for muzzle flashes, so this PR adds in the necessary lines to get it working. This allows modders to make a muzzle effect that can scale to the weapon radius through curves, and thus modders can simply make one curve scaled muzzle flash and avoid making a many muzzle flashes for each sized weapon that uses the same base effect.
> Allow Trigger Radius curve input to work with muzzle effects

- code/hud/hud.cpp
- code/hud/hud.h
- code/hud/hudsquadmsg.cpp
- code/scripting/api/objs/hudconfig.cpp
- code/scripting/api/objs/hudgauge.cpp
I needed a way to stop the comm menu hud gauge from rendering from Lua and it, notably, does not respect the enable/disable gauge sexp. So this adds a full scripting override boolean to gauges that the comm menu does respect. It's a fairly niche use-case but whatever method I came up with to handle this would be niche and this is at least generalized enough to maybe be more broadly useful.
This also includes a slight fix to the hud gange handle getter. BtA's HUD setup is fully ship based so `default_hud_gauges` array is empty which meant we had no way to get the comm menu gauge handle from lua, so this adds a way to get the player ship's hud gauges if all else fails to try and find the requested gauge. Honestly I hate the way we store gauges as part of the Ship_Info. HUDs and their gauges …
> Add a few hud lua methods

- code/model/modelread.cpp
Some QoL improvements:
1. Update `$fvec` and `$uvec` parsing to also allow parsing `$rvec` and to allow only `$fvec` to be specified; also make parsing more robust against failure
2. Allow `$fvec` and `$uvec` to specify the "facing" direction if `$look_at_offset` is not specified
3. Add a few additional warnings for incomplete or invalid POF data
> enhance look_at

- code/sound/ds.cpp
The `continue` statement in these error checks had no effect because the error checks are macros implemented in a `do` ... `while (false)` loop.  So, use `goto`.  There is precedent with other instances of `OpenAL_ErrorCheck` in the code.
This may fix the issue where sound would occasionally randomly stop, requiring a pause or a screen change to get it back.  This would be difficult to verify though.
Thanks to Coverity for flagging this situation!
> goto considered useful

- code/ai/aicode.cpp
- code/object/waypoint.cpp
- code/object/waypoint.h
- code/parse/sexp.cpp
- code/scripting/api/libs/mission.cpp
1. Add an explicit `mn.createWaypointList` function
2. Allow `mn.createWaypoint` to be used with an empty waypoint list
3. Update documentation of `mn.createWaypoint` to clarify optional arguments
> improve scripting support for waypoint lists

- code/weapon/swarm.cpp
Missed this in #6703. If there is no target (in the `no_tracking_object` case), don't make a pointer and try to get the signature. In terms of final behavior it's still fine because it only ever checks the signature if it actually has a >= 0 `enemy_objnum`
> Small fix for turret swarm stuff

- code/hud/hud.cpp
- code/hud/hudconfig.cpp
- code/hud/hudconfig.h
- code/hud/hudobserver.cpp
- code/pilotfile/csg.cpp
- code/pilotfile/plr.cpp
- code/pilotfile/plr_hudprefs.cpp
- code/pilotfile/plr_hudprefs.h
- code/scripting/api/objs/hudconfig.cpp
- code/source_groups.cmake
This PR adds 90% of the support needed for Custom Gauges in HUD Config. Custom gauges can now be individually colored to the user's preference. This also adds a new .hdp file to save the player's HUD color preferences. I felt this was a better way forward than trying to add it directly in the player file and having to bump the player file version causing a cascade of changes needed. The new file will be used if present, otherwise it will use the data from the player file.
Also added here is framework for custom gauge Visibility and Popup toggles but those are currently unimplemented and will need further table flags, testing, and for Popup, some kind of way to trigger when they should popup. Might really only be useful for Scripted gauges? I haven't planned that all out yet. That will be …
> Support Custom Gauges in HUD Config UI

- code/missionui/missionscreencommon.cpp
- code/missionui/missionshipchoice.cpp
- code/missionui/missionshipchoice.h
- code/missionui/missionweaponchoice.cpp
This PR fixes a loadout screen icon highlighting issue.
Currently there is a nice orange coloration of the player ship icon in the Ship Selection wing loadout. This immediately shows the player which ship is theirs, but this usefulness does not translate to the Weapon Loadout screen.  The player must select another ship, besides the player ship, to have the player ship show up as orange. This PR adds a bool `always_highlight_ply` which is specifically for the weapon `draw_wing_block` function when called as as part of the weapon loadout routine.
> Fix highlighting color discrepancy for player ship in loadout screen

- code/localization/localize.cpp
- code/missionui/missionscreencommon.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
Currently, if a mission is set as scramble then there is no visual way for the player to see that the Ship Selection and Weapon Loadout screens are locked, instead the player has to click on the buttons and hear the fail sounds or assess that the hover states are not triggering. This PR adds a text line right below the words Weapons Loadout that states "Ships/Weapons Locked" (XSTR 749) if the mission is scramble thus the player can easily see this right away and not have to check the buttons on every mission.
Tested and works as expected. Happy to put behind a flag if desired.
> Extra Visual Indication for `Scramble` Missions

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
- code/hud/hudets.cpp
- code/hud/hudets.h
- code/model/animation/modelanimation_driver.cpp
- code/parse/sexp.cpp
- code/ship/afterburner.cpp
Two updates to the energy transfer system.
1. Previously, for fighters missing a system (e.g. shields), the energy would be treated as if all energy from that system was routed to the other systems.  So, for example, a fighter's typical speed would be faster without shields than with shields.  A new AI profile flag now treats the other systems as if the energy had not been transferred.
2. At some point in development, Volition intended the `$Power Output` ships.tbl field to affect ETS.  A new AI profile flag now treats the power output as a factor of energy applied to energy systems.
~~In draft pending testing.~~
> ETS updates

- code/weapon/weapons.cpp
This just moves a couple things around to reduce the number of modular curves we need to query in cases where we're not going to render the laser anyway.
> Tiny optimization to laser culling.

- code/math/vecmat.cpp
- code/math/vecmat.h
- code/particle/ParticleEffect.cpp
- code/particle/ParticleEffect.h
- code/particle/ParticleParse.cpp
- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
Exposes the noise framework FSO uses for volumetrics to the particle system.
This allows particles to behave in noised-but-not-frame-independent-random ways.
As with volumetrics, it uses the DSL of the noise library to parse noise definitions.
While very flexible, this is also quite cumbersome and hard to visualize. I intend to eventually build a small utility program that can quickly visualize these noise patterns.
As an example, the following is a table that uses the new noise:
```
#Particle Effects
$Effect: NoiseTest
+Filename: AVMuzzle
+Radius: 1
+Lifetime: 8
+Duration: 20
+Spawns per second: 10
+Particle Count Per Spawn: 1
+Velocity Noise: color(scale(valueBasis(3,0),6), scale(valueBasis(3,1),6),0, 0)
+Velocity Noise Scale: 10
+Velocity Inherit: 0.9
#End
```
> Allow using seeded noise for particle velocity and spawn position offset

- code/ai/ai.h
- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aicode.cpp
- code/object/collideshipweapon.cpp
- code/object/objectshield.cpp
This PR adds one fix and one enhancement to AI shield behavior.
1) Fix: Testing, especially in FotG, revealed an edge-case bug with shield management where the AI will not direct shield energy to a quadrant if it was hit when that quadrant was down. In other words, if a shield quadrant is knocked down to 0 and continues to be shot the AI will not realize it needs to direct energy to that quadrant. This is because `quadrant` is set to -1 if a shield segment is down. This ensures that the resulting effects and damage calculations properly ignore that quadrant downstream, but it also results in `aip->last_hit_quadrant` being set to -1. This PR adds a fix to properly record which shield was actually hit, so that the AI knows to direct energy to that quadrant.
2) Enhancement: In combat …
> One fix and one enhancement to AI shield behavior

- code/weapon/weapons.cpp
Followup to #6652.
Since that PR branched, there was a change to master which caused a type mismatch in the max function, failing the cross-compile build again.
No idea why it didn't fail the normal builds, as it at least should have complained about a loss of precision in a warning.
> Fix type mismatch

- code/math/curve.cpp
- code/math/curve.h
- code/model/animation/modelanimation.cpp
- code/parse/parselo.cpp
- code/parse/parselo.h
- code/particle/ParticleParse.cpp
- code/utils/RandomRange.h
- code/utils/modular_curves.h
- code/weapon/weapons.cpp
This allows simple curves to be tabled inline wherever they are used, instead of forcing individual curve table entries.
Inline curves notably support only a much smaller subset of features, but that is perfectly sufficient for a large number of curves.
This can be used everywhere where curves are currently addressed by name in parsing.
An example table with inline curves would look as follows:
```
#Primary Weapons
$Name:                            @Subach HL-7
+nocreate
$Lifetime Curve:
+Input: Lifetime
+Output: Laser Radius Mult
+Curve Name: (0,0) -- (0.5,1000) -- (1,0)
$Lifetime Curve:
+Input: Lifetime
+Output: Laser Glow R Mult
+Curve Name: (0,0) -- (0.5,1000) -- (1,0)
#End
```
Note, that this will prevent curves from having a name that starts with an opening parenthesis.
For now, …
> Allow curves to be tabled inline

- code/object/object.cpp
Fix one copy-paste error (for `Object_Flags::Collides`), and update the other descriptions as these flags can apply to any object, not just ships.
> update object flag documentation

- code/object/objectsort.cpp
Objects are not rendered if they are outside the visible area. To roughly determine whether an object is inside the visible area, FSO uses the object's radius. Normally this works well, but the radius of a laser is equal to its head radius, and often lasers are much longer than they are wide. This causes ugly pop-in or pop-out as long lasers interact with the edge of the screen.
To fix this, we just check whether we're looking at a laser, and if so, figure out its length and use that instead of the radius.
> Fix laser frustum culling

- code/ai/aicode.cpp
A.k.a. homeworld-style jumps, bsg-style jumps, etc. They do not need to move, so there is no need to try and avoid any collisions.
~~Also rearranges the star wars hypserspace collision check (previously, if the 'short distance' check succeeded, then it would've skipped the 'long distance' check for hyperspace).~~ Since this check did not work, and some mods may be relying on it not working, we've opted to simply remove it.
> Stationary jump types should not try to avoid collision

- code/mission/missioncampaign.h
- code/missionui/missionshipchoice.cpp
- code/pilotfile/csg.cpp
- code/scripting/scripting.cpp
Fix spelling of `Initialization` in debug log and also mitigate the log complaining about invalid pilot data if it has not loaded an actual campaign yet.
EDIT: also fix erroneous debug log when selecting ships in the loadout view. `Couldn't load model file in missionshipchoice.cpp ... `Found it was line 1750 missionshipchoice.cpp. From looking through the code paths it appears `ship->model_num` has not yet been loaded but is rather loaded later, so it's supposed to be `ShipSelectModelNum `. The code did originally set `sip->model_num` but it was changed to using the `ShipSelectModelNum` variable instead and that debug message check didn't get updated (been that way since 2003 :D ).
Everything works as expected.
> Very small debug log cleanup

- .github/workflows/build-nightly.yaml
- .github/workflows/build-release.yaml
- .github/workflows/build-test.yaml
- .github/workflows/cache-master.yaml
- .github/workflows/test-pull_request.yaml
- .github/workflows/weekly-coverity-scan.yaml
- ci/linux/clang_tidy.sh
- code/graphics/vulkan/RenderFrame.cpp
- code/graphics/vulkan/VulkanRenderer.cpp
In 133b033ea0083c7c8115ee4b55c3e4abc063ee63, `SCP_vector` was made into a subclass, so direct assignment from the vulkan-hpp result isn't possible anymore. Use an intermediate vector.
> Fix Vulkan build issues, enable Vulkan build in CI

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/ship/shield.cpp
Mods like FotG do not use the FS style shield hit effects, and simply disabling the shield rendering and checking is useful with one simple global variable.
> Mod setting to disable shield effects

- code/parse/sexp.cpp
We have debug commands for sexps, so here are a few for scripts.  These will be very useful for script developers to perform diagnostics and troubleshooting.
Also revise existing documention (on the sexp commands) for clarity and correctness.
> add a few debug console commands for running scripts

- code/graphics/opengl/gropengl.cpp
- code/graphics/opengl/gropenglstate.cpp
- code/graphics/opengl/gropenglstate.h
As it turns out, a few things were trying to read from incorrect buffers when window_res was active, causing OpenGL error messages and possibly unintended behaviour in some parts.
Fix these by reading from the correct buffer when window_res is used.
This is especially important as it appears that newer SDL versions (SDL3 through SDL2compat is definitely affected, possibly older versions as well) exhibit some sort of cleanup effect on the front buffer, which results in bad reads and incorrect rendering of pause frames and other dialogs. To fix this, a followup PR should likely enable window_res at all times (as is done for fullscreen at the momemt), and for that, window_res needs to function reliably and without OpenGL errors.
Also harden the GL state handling, by querying whether the GL …
> Fix window_res related bugs and harden OpenGL state

- code/scripting/api/libs/graphics.cpp
Turns out, audio works in scripted movies just fine.  So, add a parameter to the Lua API to allow movies to play audio.
> enable audio in movie files with this one simple trick

- code/math/curve.cpp
- code/particle/ParticleEffect.cpp
Make it so that curve-based random ranges will properly detect the optional min and max values, rather than interpreting them as part of the curve name. Also, fix the 'reflected' direction for particle effects.
> A couple of particle-related fixes

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/lab/dialogs/lab_ui.cpp
- code/lab/dialogs/lab_ui.h
- code/lab/dialogs/lab_ui_helpers.cpp
- code/lab/dialogs/lab_ui_helpers.h
- code/lab/labv2.h
- code/lab/manager/lab_manager.cpp
- code/lab/manager/lab_manager.h
- code/lab/renderer/lab_renderer.cpp
Adds the ability to view asteroids/debris in the F3 lab. Depends on #6704 but wanted to get it up so that it can be accounted for heading into RC.
I should say this includes a small fix to an asteroid parsing bug I found to prevent duplicate asteroids from being created as asteroid subtypes.
> Lab asteroid viewer

- code/graphics/2d.cpp
With modern SDL, notably SDL3-compat for SDL2 API, but possibly also slightly newer SDL2 versions, reading from the frontbuffer just doesn't work and just yields zeroes.
Unfortunately, screenshots and pause dialogs rely on that feature.
However, if we route things through an intermediate buffer (as we already need to do to fix fullscreen weirdness of Windows 11), this isn't an issue.
As such, just unconditionally enable this through window_res.
> Fix SDL3_compat-caused flicker

- code/ship/shiphit.cpp
Turns out, a parameter was missed when giving ship_damage access to the hit-dot, causing the game to instead set wash_damage to true and printing the corresponding death reason message
> Fix players always being killed by hit washes

- code/weapon/weapons.cpp
Small change that makes the `Laser Anim State Add` output for weapon lifetime curves add by frames, rather than by fraction of the animation's length. This produces behavior which is _much_ more intuitive and much more useful in this output's central use case.
This is a (small) behavioral change, but this curve output has never been in stable.
> Improve 'laser anim state add' curve output

- code/ship/ship.cpp
Looks like when `+Debris Density` got added it never accounted for a colon like the other fields
> Allow `+Debris Density:`

- code/hud/hudsquadmsg.cpp
- code/localization/localize.cpp
This PR adds two new localization strings, which allow modders to change how the numbers in the comms menu are displayed, and it incorporates styling for the comms selection controls from #6736, too.
> Allow modders to tune Comms Styling

- code/controlconfig/controlsconfig.cpp
- code/io/mouse.h
From #6777: Binding the mouse wheel to a control of type `CC_TYPE_TRIGGER`, such as `Cycle Primary Weapon Forward` does not work in game. IE, scroll the mouse wheel up will not trigger then control. The mouse wheel does seem to work for controls with type `CC_TYPE_CONTINUOUS` though.
This is because `mouse_down` and `joy_down` were only checked within the if-block for `item.type == CC_TYPE_CONTINUOUS` within the function `check_control_used`.
This PR fixes #6777 by using `joy_down/mouse_down` and  `joy_down_count/mouse_down_count` for any controls, not just those of `CC_TYPE_CONTINUOUS`.
Tested and everything works as expected, and being able to use the mouse wheel for all controls now greatly enhances the configurable controls and overall gameplay experience IMO as a mainly …
> Allow Mouse Wheel to work with trigger type controls

- code/ai/aicode.cpp
- code/ai/aigoals.cpp
- code/ai/aigoals.h
- code/hud/hudsquadmsg.cpp
Fixes a few issues in the handling of the stay-near orders:
1. Allow "Stay near me" and "Stay near my target" to work even if the teams do not match
2. Allow "Stay near my target" to be issued regardless of team
3. Avoid divide-by-zero errors when running `ai_stay_near()`
Additionally, when issuing the stay-near-target order via hud squad message, default to a distance of 300, the same as the sexp.
Fixes #6475.
> fix STAY_NEAR_TARGET_ITEM

- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/object/objectsnd.cpp
- code/ship/ship.cpp
- code/ship/ship_flags.h
On current master, destroyed engines still make noise and the `Engine Minimum Volume` is not used by big ships. This PR makes two new game settings flags which allow mods to mitigate those issues (`$Unify minimum engine sound:` and `$Disabled engines are silent:`).
Tested and works as expected. Note, I also renamed `Engines_on` flag to `Engine_sound_on` to better reflect what it does (it is only used by engine noised when the ship dies and stutters). I did evaluate using that flag and always setting it with `Disabled` but that would introduce maintaining two separate flags that overly complicated the code IMO. 
I also added both of these to the 25.0 default, but happy to alter however.
> Two Sound Updates

- code/ai/aigoals.h
- code/scripting/api/objs/order.cpp
- fred2/shipgoalsdlg.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipGoalsDialogModel.cpp
The new enum class collection of AI goal modes did not handle the superposition of states that could occur when multiple ships were selected in FRED.  Add a special FRED-only state for this purpose.
EDIT: Tested with @LuytenKy's original bug scenario, as well as the usual single-set and multi-set scenarios with and without the superposition
> schroedinger AI goals

- code/mission/missiongoals.cpp
The `Always_show_directive_value_count` flag from #6584 needs to not show the directive if that special `DIRECTIVE_WING_ZERO` value is temporarily being used.
> Edge case fix for Always_show_directive_value_count

- code/scripting/api/objs/order.cpp
Several refinements:
1. Make the case labels consistent between the setting and getting of the virtvar, for ease of comparison and troubleshooting.
2. Consolidate CHASE_WING and GUARD_WING for setting, like they already are for getting.
3. Consolidate STAY_STILL for getting, using one simple trick.
4. Remove the KEEP_SAFE_DISTANCE goal, since it has no target. Fixes #6761
5. Fix CHASE_SHIP_CLASS which put the getting case in the setting section, and consequently did not handle setting.
Tested the KEEP_SAFE_DISTANCE and CHASE_SHIP_CLASS fixes; both work as expected
> clean up Target virtvar in order.cpp

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/ai/aibig.cpp
- code/ship/ship.cpp
This PR does 2 things.
1) Cleanup `ship_subsystem_in_sight` so it properly returns a bool, which is the return type of the function. Also update `ai_big_maybe_follow_subsys_path` to be a bool instead of int.
~~2) Adds `+subsystem attack pathing extra distance:` for use within `"$improved subsystem attack pathing:"`. FotG found, especially with the new strafing values we use, could really use the ability to set at what distance `ai_new_maybe_reposition_attack_subsys()` determines if it wants to pick a new point or not. By default the value was 2000.~~ (Turns out this is not needed, per discussion below). 
3) In FotG we started using the `standard_strafe` mode more now thanks to #6511, but we have now discovered some inherit issues with it, namely that it will prematurely trigger …
> AI Cleanup and Flag Fixes

- code/hud/hud.cpp
Fixes #6774.
For posterity as to what happened here:
The first thing the graphics API initializes is NanoVG, the thing that also renders fonts.
NanoVG creates a texture on slot 0 that it uses for font storage and so on.
If you scale a font large enough (which typically happens for screens of a sufficient resolution), this texture is no longer sufficiently large.
As such, NanoVG will allocate a new texture that's larger, and free the old texture afterwards.
This happens usually a second or so into the first mission that uses the larger font, leaving texture slot 0 unoccupied.
The next call requesting a new (single) texture will end up in that slot. If the next mission you load in a campaign uses no other ship textures, this means that this slot will stay open.
Cockpit RTT textures are …
> Fix bmpman corruption for > 1080p resolutions

- code/hud/hudsquadmsg.cpp
Within `hud_squadmsg_run_order_issued_hook` it is possible for the calling code to pass `nullptr` as the target parameter, which would cause memory problems with the several instances of `Objects[target->objnum]`. This PR mitigates that potential while testing of  `hud_squadmsg_run_order_issued_hook` still works as expected.
> Prevent Potential Memory Problems with squadmsg hook function

- code/graphics/software/font.cpp
I just finished helping a modder debug his mod, and it would have saved him a lot of time and trouble if this WarningEx had been a Warning.
> change this WarningEx to a Warning

- qtfred/src/mission/Editor.cpp
- qtfred/src/mission/Editor.h
- qtfred/src/ui/FredView.cpp
Fix a qtFRED memory access bug when checking for autosaved files.  Passing a temporary variable to a function as a reference, then returning it, led to a dangling reference access.  Rewrite the `maybeUseAutosave` function to avoid this.
> fix qtfred memory corruption

- code/parse/sexp.cpp
These sexp operators can be enhanced to allow multiline scripts while retaining backwards compatibility, so do so.
Both tested and work as expected.
> make script-eval-num and script-eval-bool multiline

- code/globalincs/pstypes.h
- code/model/model.h
- code/model/modelcollide.cpp
- code/model/modelinterp.cpp
- code/model/modelread.cpp
- code/model/modelsinc.h
- code/render/3d.h
- code/render/3ddraw.cpp
Add assertions to the model parsing macros to guard against accessing out-of-bounds memory.  Patch the model parsing routines to avoid going out of bounds, even if the out of bounds situations are temporary and benign.
> memory safety for model parsing

- fred2/missionsave.cpp
- fred2/missionsave.h
- qtfred/src/mission/missionsave.cpp
- qtfred/src/mission/missionsave.h
Ever since retail, when encountering a comment, FRED would add an extra newline and mix `\r` with `\r\n`, often causing other bugs.  The reason for this is subtle.  C and C++ library functions will automatically convert `\n` to `\r\n` and back again when reading and writing in text mode, but FRED mission files are read in binary mode and written in text mode.  Normally the parsing code can accommodate reading raw newlines of any type, but comments are copied verbatim from what is read to what is written.  A comment ending in `\r\n` will therefore be written as `\r\r\n` which will add an extra incompatible newline.
At one point (in commit a988f5eab22b2c2316bce389e24c5eee4aad7903) a fix was made for this, but it only applied to multiline comments, not all comments.  Therefore, this PR moves …
> fix broken newline behavior when FRED saves missions

- fred2/missionsave.cpp
- qtfred/src/mission/missionsave.cpp
Applies a stable sort to the keys of a map container before saving the container to the mission file.  The underlying container is not modified.  Implements #6803.
(Lists are not sorted because the mission designer might have a particular order in mind for them.)
Tested with a mission containing a list and map container; works as expected.
> sort map keys before saving a container

- code/debris/debris.cpp
- code/debris/debris.h
- code/network/multimsgs.cpp
- code/object/collidedebrisweapon.cpp
- code/object/collideshipweapon.cpp
- code/object/collideweaponweapon.cpp
- code/ship/shiphit.cpp
- code/ship/shiphit.h
- code/weapon/beam.cpp
- code/weapon/weapon.h
- code/weapon/weapons.cpp
This PR adds a suite of new options to the conditional impacts system, including:
- support for subsystem armor as a condition
- special cases for asteroids, debris, and empty space
- a system to detect cases where a long laser is overpenetrating its impact point, and spawn an additional effect at the laser's head to help conceal the overpenetration
- options for conditioning an effect on the ratio between damage dealt and hitpoints left
- a few other boolean options for controlling when effects can or can't play
This required a certain amount of moving things around, but I'm pretty sure I got all the code paths and behavior will not be changed given the same tables.
> Enhanced functionality for conditional impacts

- code/radar/radarorb.cpp
Fixes #6823.
We need to make sure that we call g3_end_frame before leaving the function.
> Fix orb radar in config mode

- code/parse/sexp.cpp
Some SEXP help did not have newlines separating what should be separate lines of text, or spaces separating what should be separate words.  Add newlines or spaces where appropriate.  (Regexes are A-1 SUPAR.)
> ensure SEXP help has appropriate newlines or spaces

- code/def_files/data/effects/decal-f.sdr
- code/def_files/data/effects/decal-v.sdr
On macOS the new decal shaders (#6813) fail to compile with the following message: "interpolation qualifier 'flat' must precede storage qualifiers".
> fix decal shader compile error

- code/utils/threading.cpp
Based on my tests with up to 16 threads and informal testing by @MjnMixael using 64 threads, there seems to be a current sweetspot between work sharing and overhead around 8-ish cores.
So limit the autodetected threadcount to 8.
Note that it is still possible to manually specific a larger threadcount. This is intended, both for testing purposes as well as if this assumption might not hold true for all CPU's or architectures.
> Limit the number of threads spawned

- code/utils/threading.cpp
Turns out, properly reading the docs helps.
We have to check against the error code being false for an error, and not check it for being non-zero.
> Fix Thread Count Detection on Windows

- code/utils/threading.cpp
macOS has an easy way to get the physical cpu count so let's use it. Also with Apple Silicon there are performance and efficiency cores so we need to make sure we ignore those low-perf cores when getting the count.
> get proper number of physical cpu cores on macOS

- code/def_files/data/effects/post-f.sdr
- code/def_files/data/tables/post_processing.tbl
- code/graphics/opengl/gropenglpostprocessing.cpp
- code/graphics/post_processing.cpp
- code/graphics/post_processing.h
- code/graphics/util/uniform_structs.h
Post processing effects such as tint or dithering have their uniforms hardcoded, which means the only want to create new post-process effects for a mod is to overwrite an existing effect.
Requested for DEM2, this PR creates 4 blank slots for mods to create new post processing effects--2 floats and 2 vec3. This approach to create blank slots for modders follows the successful strategy used for Custom_Controls 1-5.
Note, this PR also adds `tint` to the default `post_processing.tbl` which had it missing (even though tint is a valid effect with a valid uniform buffer already).
Happy to discuss more or edit however (including if this is a bad idea or will result in performance loss, very much want to avoid any 'gotchas' and can close if deemed not feasible).
> Slots for custom post processing effects

- code/parse/sexp.cpp
Since this sexp was implemented, there has been a bug that prevented multiple variable-controlled audio streams from working.  One default and one variable-controlled stream could coexist, but any subsequent variable-controlled stream would reuse a previous stream's handle if the variable's current value was a valid handle.  This adjusts the code to properly create a new handle for every invocation of the sexp with a variable.
The following cases have been tested and now all work properly:
1. The default handle by itself
2. One variable handle by itself
3. One variable handle with one default handle
4. Multiple variable handles
5. Multiple variable handles with one default handle
Follow-up to #2115.
> fix play-sound-from-file with multiple variable-controlled streams

- code/weapon/weapons.cpp
So, in #6808, I mistakenly read the pspew scale being applied three times to the actual size of the effect as "scale * 3", when it should have compounded multiplicatively instead of additively.
> Fix default PSPEW scale

- code/nebula/neb.cpp
This allows the first half of a modular -neb.tbm to be skipped, allowing just poofs to be specified without the need for a preceding empty bitmap section.  It's a follow-up to #5128 which allowed just bitmaps to be specified without the need for a subsequent empty poof section.
> allow modular nebula tables to not define bitmaps

- code/hud/hudshield.cpp
- code/mod_table/mod_table.cpp
- code/mod_table/mod_table.h
- code/object/objectshield.cpp
- code/object/objectshield.h
- code/ship/shield.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shiphit.cpp
- code/weapon/weapons.cpp
FSO logic dictates that shields collisions and any related sound or visuals related to shields are skipped if the shields are under 10%. This is rather unintuitive especially for mods, so this PR creates a game setting value that allows mods to set this value.
Also, this PR fixes a bug where the HUD shield gauge would try and incorporate this feature but did not do it correctly. Specifically, the gauge skips shield segment rendering if the raw shield strength was 0.1 not the percent. Incorrectly using the raw value results in HUD shields being rendered (albeit faintly) even if the damage was skipping the shield and directly damaging the hull. In other words, if the shield segment was 8%, the shield segment would show faintly even the shield is skipping damage.
Tested and works as …
> Allow mods to set threshold at which shield stops taking damage

- code/mission/missionparse.cpp
Found a very interesting edge case bug with `$Preload briefing icon models:.`
Situation: Mission 1 has a briefing which has a ship class A as the class (and thus loads the model), but the ship class A is not actually in that mission so no subsystems are loaded. Then in mission 2, the ship class A is actually in the mission but FSO tries to reuse the slot that was loaded, but realizes no subsystems were loaded and makes an error message. I that is because the preload code for the briefing icons on `missionparse.cpp` line 6664 just calls `model_load` but does not specify the subsystem argument.
I've also attached a retail mod reproducible campaign (2 missions, first is 5 seconds long). When the second mission loads the incorrect subsystem warning appears. …
> Fix Edge-case with `$Preload briefing icon models:`

- code/ship/shiphit.cpp
- code/ship/shiphit.h
If a ship's shield is hit with more than enough damage to deplete it completely, the remaining damage will be sent to the hull. This triggers hull conditional impacts, which then proceed to spawn at the location of the shield impact and potentially look very strange, if they were designed specifically for hull impacts. Previously, this would have been very rare, because the 10% shield skip percentage meant that a shot hitting the shield and doing overkill damage would have been difficult. However, setting the skip percentage to 0 via #6847, as FotG has recently done, reveals the issue dramatically, as shields on certain ships begin regenerating immediately after depletion and therefore most hits are against shields with very little health.
To fix this, we simply make sure not to pass in …
> Fix odd-looking hull impacts spawning when the shield is hit

- code/ship/ship.cpp
Small one-line fix that follows up #6849. That PR removed the `!(Viewer_mode & VM_EXTERNAL))` check within a section of `ship_render_player_ship` to optimize insignia rendering, but turns out that check is needed to ensure `show-ship` properly works. This PR restores that check to fix this bug, and ideally the thoughts about slightly optimizing insignias can be considered later.
> Fix 'show-ship` not working

- code/scripting/api/libs/options.cpp
Will allow SCPUI to error early since in-game options is required.
> Lua func to check if in game options are enabled

- code/scripting/api/objs/texture.cpp
- code/scripting/api/objs/texture.h
The bug that was observed before this fix abbreviates to roughly the following sequence of events.
A lua variable is held, containing an animated texture.
A `gr.drawImage` call is used to draw a specific frame of that animation by indexing into the above variable.
This leaves the temporary returned from indexing with a newer last-used timestamp than the actual animation-holding variable.
It is now possible that the animation-holding variable is unloaded or garbage collected. This frees the according slots in bmpman, allowing them to be filled with other data.
At the same time, the temporary is not yet garbage collected. Once that happens (e.g. in the forced garbage collection pass during mission load) the subframe temporary will try to deallocate itself in bmpman. But now, that slot is …
> Prevent lua from Garbage Collecting possibly-stale Subframes

- code/model/modelrender.cpp
- code/model/modelrender.h
- code/particle/ParticleEffect.cpp
- code/utils/RandomRange.h
- code/weapon/weapons.cpp
This fixes two things:
1. The general `convert_distance_and_diameter_to_pixel_size` function, which conflagrated horizontal fov with screen height and seemed to be missing a tan in the trigonometry (which I redid from scratch just to be safe).
2. RandomRange reporting of the expected value when in constant value mode, which was what caused the radius of the muzzleflashes to be reported incorrectly to the scaling curves.
OVerall, this PR fixes the oversized muzzleflashes in exile.
> Fix calculation of apparent size

- code/asteroid/asteroid.cpp
Standalone doesn't create particles so these checks will always fail.
> fix particle related standalone error

- code/mission/missioncampaign.cpp
- code/mission/missioncampaign.h
- code/mission/missionparse.cpp
- code/network/multi_options.cpp
- code/network/multiui.cpp
- code/playerman/managepilot.cpp
- code/scripting/api/libs/mission.cpp
A minor bug in #6077 resulted in a crash loading campaigns on the multi ui. The bug itself was not fatal, however it triggered a cascade of poor error handling which led to a crash. A lot of these issues date back to retail. This fixes the minor bug, and hopefully adds enough error handling to preemptively squash a repeat of the crash problem.
> fix multi crash loading campaigns

- code/weapon/weapons.cpp
#6808 converted all Pspews to use the new particle effects, though that in turn lead to a fun little visual bug. Overall, particles on weapons will only be rendered if they are valid, and the is valid check included a `weapon_state == m_weaponstate` check (IE states had to match between what the weapon object held and what the particle held. When a weapon switches to homing that particle state was never updated, b/c before 6808 it never needed to be. This lead to the particle effects from pspews not rendering when a missile was in homing mode.
This PR fixes that issue by also updating the particle host status whenever the weapon state changes (uses the same logic as when the particle spawns the first time).
> Fix p-spew with homing weapons

- code/particle/ParticleParse.cpp
- code/scripting/api/libs/graphics.cpp
1. Change some settings for the scripted particles to ensure that lua-provided velocity is properly forwarded to the particle system
2. Error out when no bitmap is tabled. This happens for example when the string list is malformed, and will later cause invalid accesses into the bitmap list.
> Minor Particle Fixes

- code/asteroid/asteroid.cpp
- code/asteroid/asteroid.h
- code/parse/sexp.cpp
Turns out using config-debris-field or config-asteroid-field with many active types of debris or asteroids can bring missions to a grinding halt so that the models can be loaded. So this PR utilizes the framework other SEXPs use, such as change-ship-class, to preload any asteroids or debris that are listed in one of those sexps.
A bonus optimization is that the list of asteroid subtypes is now a static variable return so we can skip running that the whole function after we've already done it once.
> Preload asteroids and debris when config-field SEXPs are used

- code/network/multimsgs.cpp
Dumbfire missiles are client fired for rollback purposes. However players would see their missiles fire twice due to the server also sending a fire packet back to the player. So we need to prevent the player that fired the missile in question from getting that extra packet.
> fix double dumbfire missiles for multi clients

- code/object/collideshipship.cpp
- code/physics/physics.cpp
- code/physics/physics.h
- code/ship/ship.cpp
- code/ship/ship.h
The `+Rotation Factor:` value in the ship collide section of the ships table has been around for many years, but raising that value beyond the default of 0.2 results in ship collisions that can result in the colliding ship spinning at ludicrous rotational velocities that last for over 10 seconds (this is especially evident with long ships with high speeds).
This PR adds a field after `+Rotation Factor:` called `+Rotation Magnitude Maximum:` which serves as a maximum for the resulting rotational velocity from a ship collision in degrees per second. By default this is -1 and thus disabled.
Tested and works as expected, and now properly allows mods to have ships spin out if they have collision while not spinning out at wild speeds that look immersion breaking.
> Allow mods to cap rotational velocity from collisions

- code/osapi/osapi.cpp
SDL 1.2 had an issue using SDL_Delay() on Mac where it caused bad stuttering and freezes. A hack was added to avoid this, but it causes 100% CPU usage when it should be a sleep state, so it wasn't ideal.
With SDL 2 this issue was resolved with the underlying code being unified for all *NIX variants and that problematic Mac-specific code was removed. So now we can remove the hack to offer a little better performance on Macs.
> remove old os_sleep() hack for Mac

- code/graphics/opengl/gropengltexture.cpp
The if statement wouldn't trigger as defined which caused the incorrect data offsets to be used. This resulted in corrupted textures and invalid memory reads of uncompressed textures if the hardware texture detail slider was set to anything other than max.
> fix mipmap resizing bug

- code/ai/aigoals.h
- code/lab/manager/lab_manager.cpp
- code/ship/ship.cpp
PR #6715 added the ability to test docking and undocking the lab which required initializing the ai subsystem in the Lab as well. Doing that had a side effect of causing the current ship to move around on it's own. To solve that a Play-Dead order was issued. That had a side effect of causing subsystem rotations/translations to stop running as that is a design of Play-Dead.
Stay-Still didn't really work well on fighters in the Lab because they still wiggled around. So the options were to either constantly reset the current object's orientation every frame or just carve out a special case for the Lab to still run subsystem animations even during Play-Dead. The latter turned out to be the easiest and less hacky.
Fixes #6897
> Still allow subsystem animations in the lab

- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
Fix more standalone crashes from particles by "allowing the code to create particles, and just silently quit if in standalone. I.e., accept an invalid effect handle if in standalone and that'll just quit out the source on its first frame of processing." Thanks to @Bmagnu for the fix! Putting here to allow taylor and chief to more easily test.
> Another particle fix for standalones

- code/ai/aicode.cpp
- code/ai/aigoals.h
- code/lab/dialogs/lab_ui.cpp
- code/lab/dialogs/lab_ui.h
- code/lab/manager/lab_manager.cpp
- code/lab/manager/lab_manager.h
Fixes a handful of things I found while doing another PR.
- Turrets need a similar carveout as #6898 to make sure their animations get reset during test firing
- Only reset the collisions global when we leave the lab not when we run cleaning while changing ships
- Make sure all animation trigger buttons have a string assigned so they can actually be triggered
- Add missing Docked animation trigger
- The reset animations button was trying to undo any triggered animations but with lots of clicks and lots of animations it didn't seem to be fully accurate. I thought it'd be easier to just reload the current ship and call it good.
> Misc Lab Fixes

- code/lab/manager/lab_manager.cpp
- code/lab/renderer/lab_renderer.cpp
- code/model/modelrender.cpp
- code/model/modelrender.h
Draws the current detail level being rendered to the screen. Very useful for testing and debugging detail distance settings.
I tried to do this with a member var of the lab with a setter but it caused build issues with FRED as including any methods from the lab in modelrender started requiring symbols that FRED doesn't have but FSO does. So in the end I decided this was the simplest way to do this.
> Show current detail level in the lab

- qtfred/src/mission/util.cpp
This allows the model to decide on the workflow based on the results of any internal validator.
Cancel -> Yes Keep Changes -> Validator warns of a problem -> Do not close the dialog (return false)
Cancel -> Yes Keep Changes -> Validator does not return issues -> Close dialog (return true)
Note that _model->apply() already has a function signature that returns a bool. Some dialogs may not make use of this yet but I'll fix that as I go down the list.
> Let the model decide if the apply was successful and should close

- code/network/gtrack.cpp
- code/network/psnet2.cpp
- code/network/psnet2.h
- code/network/ptrack.cpp
- code/network/valid.cpp
The socket is a value to be assigned, not an index to be used. As such there is no safety check to be done here and doing so just breaks things.
Fixes networking on Windows.
> remove "safe" versions of FD_SET/FD_ISSET

- code/ship/ship.cpp
- code/weapon/shockwave.cpp
- code/weapon/shockwave.h
- code/weapon/weapons.cpp
Add a weapon parameter to make it so that the shockwave's orientation will be oriented locally rather than globally. The manual orientation offset still works, but is now relative. Also, fix some issues with weapons not inheriting as much parent orientation as they could under a few different circumstances.
> Allow shockwave orientations to be relative to their parents

- code/network/multimsgs.cpp
- code/network/multimsgs.h
- code/ship/ship.cpp
- code/weapon/weapon.h
Multiple issues were discovered to be from improper targeting data in multi tracing back to the addition of multi-lock. This was due to differences in how targeting works in single/multi and de-sync of this info between server and client. Collecting accurate targeting data on the server and making sure that the client will use that data resolves the tracking and sync issues.
> fix series of bugs due to improper multi targeting

- qtfred/src/main.cpp
- qtfred/src/ui/dialogs/LoadoutDialog.cpp
Fixes #6456 by commenting out the application display name. It's unnecessary anyway.
Also fixes the Loadout Editor Dialog crashing the application byt changing any .toStdString()'s to creating a temp SCP_string using the constData() char data directly. This is similar to #6917 and long term we probably need to figure out why .toStdString() causes a heap error when it deallocates but for now this gets us up and running.
> Qt fred misc bugs

- code/starfield/starfield.cpp
From discussion with VR players, it appears that being able to toggle off the skybox/starfield/planet background is very useful to some players to prevent motion sickness. Currently, FSO has the toggle in the Graphics Options window for `Planets/Backgrounds` but it only turns off planet bitmaps. 
This 3 line PR suggests it should be expanded into an accessibility role for players, and properly turn off all background elements--so planets, plus skybox rendering (especially now since most mods also use skyboxes as backgrounds, whereas in early days this was not primarily the case).
Happy to discuss and/or add as a flag if folks think that would be needed.
> Allow background option to completely work (VR useful)

- code/particle/ParticleEffect.h
Background:
Many mods, especially Event Horizon, have highlighted how versatile and useful using nebula are for creating a wide variety of immersive effects beyond just nebula, including weather, volcanic ash, specialty debris falling from the sky, and more. In addition volumetric nebula have opened another realm of possibilities for modders to creatively utilize. Furthermore, modders can not leverage the powerful updates to the particle system to create a wide diversity of effects, which can be also utilized within nebula (or any mission) by making weapons with those effects and then spawning those weapons with scripts/sexps. Just one creative example is exploding rock debris from a volcano (like in Event Horizon). The visuals of nebula poof though are of course spawned in density …
> Add 'Nebula Usage Score' curve input

- code/network/multimsgs.cpp
- code/network/multimsgs.h
- code/parse/sexp.cpp
A previous attempt to fix the end-mission sexp in multi such that it wouldn't trigger the jump out sequence was horribly broken. Notable safety checks, state changes and server/client syncing was skipped over. This caused, as one particular bug, a standalone server to stop communicating with the game host. When this happened stats couldn't be accepted/tossed and you were stuck at the debrief screen, being forced to disconnect from the standalone in order to continue.
A proper fix for this is to use multi sexps to tell clients to enter a debrief state before the standard end mission request is handled. This will allow it the bypass the actual warp out animation for players while still doing the normal end of mission handling.
NOTE: This is a breaking, but not fatal, multi change and should …
> fix end-mission sexp in multi

- code/io/joy-sdl.cpp
Set the joystick combo boxes in the in-game settings to be in the correct order, allowing space between them for possible future options as well (per-device haptic/rumble, etc.).
> force proper ordering of joystick options

- code/ui/button.cpp
UI elements with custom mouse cursors wouldn't show them due to the cursor being reset at the start of each frame. To fix this we need to be sure that we only reset when the element is no longer active.
> fix custom mouse cursors

- code/controlconfig/controlsconfig.cpp
Fixes fail sound due to the control set not changing between calls.
> remove extra config bind on joystick axes

- code/particle/ParticleEffect.cpp
- code/particle/ParticleEffect.h
- code/particle/ParticleSource.cpp
- code/particle/ParticleSource.h
Adds a particle source curve input that is the particle's width as a fraction of the screen's width. Also, renames the existing "Apparent Visual Size At Emitter" input to "Pixel Size At Emitter", for disambiguation and clarity.
> Add apparent size input for particle source curve

- code/parse/sexp.cpp
Broken in #6948 but the original didn't work properly either due to conversion to int32_t and the resulting size limit.
Big assist from Goober5000 for noticing the bug and helping to sort out the wonky values.
> fix conversion of Missiontime to milliseconds

- code/debris/debris.cpp
- code/model/model.h
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- code/ship/shipfx.h
Allows modders to define particle effects to be used when debris explodes, disabling the default fireball. Also allows specification of flame-trail effects for subsystem debris, on both a default and a per-subsystem basis. All of these effects, including the preexisting flame trails for normal debris, now distinguish between 'debris' (an actual chunk of the hull) and 'shrapnel' (a generic shard of material), and allow specification of different effects for each.
In order to properly distinguish subsystem-based debris from non-subsystem debris under certain circumstances, it was necessary for me to add a subsystem pointer passed into `shipfx_blow_up_model()`. This produces one change to existing behavior: the velocity of shrapnel spawned during subsystem destruction will now take the …
> Particle effect hooks for subsystem debris trails and debris explosions

- code/model/modelread.cpp
Fields like `uvec` and `fvec` allow for properly parsing colons, so ensure that fields like `fov` do as well. That way entries like '$fov:190' work as expected. Doing this since I spent far too long trying to figure out why a ship's turrets were not firing...
> Spare future modders

- code/model/model.h
- code/particle/ParticleSource.cpp
- code/ship/ship.cpp
- code/ship/ship.h
- code/ship/shipfx.cpp
- code/ship/shipfx.h
- code/ship/shiphit.cpp
Adds the ability to spawn particle effects when a ship subsystem is destroyed. A default can be set for the entire ship, and subsystem-specific effects can also be defined. If a subsystem's death is spawning a particle effect, none of the retail fireballs for it will be spawned.
> Particle effect hooks for subsystem destruction

- code/math/vecmat.cpp
Fixes a bug noticed by wookieejedi which affects the `rotationalInterpolate` script function, and some multi rollback code apparently, but this function is not used elsewhere.
Note the order of these arguments in `vm_angular_move_matrix`, where this code is derived from:
https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/math/vecmat.cpp#L2056
```
// otherwise rotate orient by theta along rot_axis
vm_quaternion_rotate(&Mtemp1, theta, &rot_axis);
Assert(is_valid_matrix(&Mtemp1));
vm_matrix_x_matrix(next_orient, curr_orient, &Mtemp1);
```
> Fix a bug with `vm_interpolate_matrices`

- code/object/object.cpp
Tiny check to make sure that if deferred lighting is off (which will mean that object lights don't do anything), we don't execute the code block that adds point lights to weapons, since, with modular curves, it can potentially have significant performance impact.
> Don't bother doing the work to add weapon lights if deferred lighting is off

- code/object/object.cpp
Fixes an incorrect value usage in #6997 which caused weapon lights to never appear.
> Fix new deferred check

- code/graphics/opengl/gropengldeferred.cpp
- code/graphics/opengl/gropengldeferred.h
- code/lighting/lighting_profiles.cpp
- code/lighting/lighting_profiles.h
- code/object/object.cpp
Adds a set of adjustments to lighting profiles for cockpit light intensity, to match the existing one for cockpit light radius. Also, fixes an incorrect value usage in #6997 which caused weapon lights to never appear no matter what.
> Cockpit-specific light intensity adjustment for lighting profiles

- code/parse/parselo.cpp
Parse errors that are actually errors should use `error_display(1, ...)`, rather than merely logging them (which doesn't abort parsing) or using `Error` (which omits the line number and file name).
Fixes #7002.  Tested with a modified script file that produces the same error.
> fix some parse error handling

- fred2/briefingeditordlg.cpp
- fred2/eventeditor.cpp
- fred2/initialstatus.cpp
- fred2/jumpnodedlg.cpp
- fred2/missiongoalsdlg.cpp
- fred2/missionsave.cpp
- fred2/shipeditordlg.cpp
- qtfred/src/mission/dialogs/JumpNodeEditorDialogModel.cpp
- qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipEditorDialogModel.cpp
- qtfred/src/mission/dialogs/ShipEditor/ShipInitialStatusDialogModel.cpp
- qtfred/src/mission/missionsave.cpp
- qtfred/src/ui/dialogs/EventEditorDialog.cpp
Any place in FRED that uses XSTR is susceptible to double quotes interfering with the standard XSTR format, not just the expected briefing, debriefing, messages, etc.  This PR adds `lcl_fred_replace_stuff()` - which handles not only quotes but semicolons and slashes as well - to the other places where XSTR is used.
(Note that quotes are handled just fine in non-XSTR fields.  Semicolons will still truncate non-XSTR fields, but addressing that is beyond the scope of this PR as it would require editing every text field in FRED.  Fortunately, errant semicolons merely modify the text as opposed to corrupting the mission file.)
Fixes #7005 in both FRED and qtFRED; tested in both.  Caveat aedificator: the briefing editor is not yet implemented in qtFRED, so the relevant fixes to briefing icon …
> add additional double quote conversion to FRED and qtFRED

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/BackgroundEditorDialogModel.cpp
- qtfred/src/mission/dialogs/BackgroundEditorDialogModel.h
- qtfred/src/ui/dialogs/BackgroundEditorDialog.cpp
- qtfred/src/ui/dialogs/BackgroundEditorDialog.h
- qtfred/ui/BackgroundEditor.ui
Fully implements the background editor with updating backgrounds and everything. There's a couple remaining TODOs that I will handle in a follow up once we know the main render view is working properly.
Another note is that while FRED does use intermediary variables and saves everything on close, the Background Editor does not come with standard OK/Cancel buttons so I chose to fire the middle man for simplicity. The model works directly on the mission data.
Fixes #1688 
Fixes #2963
> QtFRED Background Editor Dialog

- code/ai/ai_profiles.cpp
- code/ai/ai_profiles.h
- code/ai/aicode.cpp
The attack-any order is extremely useful and utilized order, and there was one aspect that was ripe for exposure to modders: the `CHASE_CIRCLE_DIST` that was used to determine how big of a circle to fly around while the AI waited for new hostiles to arrive. For ships with high speeds, like FotG and others, the default radius of 200 m was a bit on the small side, which lead to ships flying in tight circles. This was was counterproductive to goals of tuning the AI to have a more cinematic style, such as where AI would fly around in large distances while waiting for enemies to arrive. Fortunately, this value is easy to expose with just a few lines, and overall it allows modders the ability to tune the already useful 'attack-any' order while idling with just a single new ai_profiles value. …
> Expose value of idle circling with 'attack-any'

- code/graphics/vulkan/VulkanRenderer.cpp
This fixes two build issues:
- `vk::PFN_DebugReportCallbackEXT` takes `vk::DebugReport*EXT` not C type `VkDebugReport*EXT` since version 1.3.304. (KhronosGroup/Vulkan-Hpp@d5a18dc87efbcc291bbd50a892187af4cbb60285)
- `vk::ObjectDestroy` was moved to namespace `vk::detail` in version 1.3.301. (KhronosGroup/Vulkan-Hpp@6e5489fcd96ba1e2cf994ebe3e4d1f5f4f690f4b)
Guard them with version checks, so that compiling with older verions of the Vulkan-Hpp headers keeps working.
Closes #6416.
> Fix build issues with Vulkan SDK 1.3.301+

- code/weapon/beam.cpp
- code/weapon/weapon_flags.h
- code/weapon/weapons.cpp
This makes it so that direct fire beams aim only once when warming up, and lead their target when doing so, this way you can sort of 'dodge' a beam. I thought of various ways of parameterizing all of this, the lead scalar, different kinds of beams, but it would it a lot more complicated, doesn't really make any sense on certain beams, and even if so, having a single simple flag to enable this sort of thing is still useful.
> Add 'direct fire lead target' beam flag

- code/ship/ship.cpp
Allows `$Thruster Effect:` by fixing copy-paste bug. Tested and fix confirms to work.
> Fix for modern Thruster Particles

- code/weapon/weapons.cpp
If a pspew specifies a single-frame image, be sure that it is loaded correctly.  Fixes a particle crash in Inferno.
> make legacy particle spews more robust

- qtfred/src/mission/dialogs/MissionEventsDialogModel.cpp
The double quote conversions added in #7008 were removed in #6961, probably inadvertently due to the branch merge.  This adds them back.
> restore double quote conversion in event editor

- code/fireball/fireballs.cpp
Small and subtle fix: move the CINEMATIC options inside the preceding if() block in the same way that the flare style options are inside their preceding if() block.  This prevents the CINEMATIC options from being reset to their default values in subsequent modular table parsing.  Followup to https://github.com/scp-fs2open/fs2open.github.com/pull/6500.
This PR should be reviewed using the "ignore whitespace" option.
> modular table fix for cinematic warp

- code/weapon/beam.cpp
Beams in general, and slash beams most likely, can collide with the edge of a model, which will cause a non-normalized vector assertion when particle effects are created.  So comment out the normal assignment until a more comprehensive fix can be coded.
> fix null vector assertion in slash beam collisions

- .clang-tidy
- code/particle/ParticleEffect.cpp
- code/particle/ParticleEffect.h
- code/particle/ParticleManager.cpp
- code/particle/ParticleParse.cpp
- code/particle/ParticleSource.h
- code/particle/hosts/EffectHostParticle.cpp
- code/particle/particle.cpp
- code/particle/particle.h
- code/utils/modular_curves.h
Followup to #6465.
The particles having access to their static table data is an important enhancement for a lot of particle use cases.
Explicitly, this PR closes #3052 by ways of modular curves that are now possible, and it will facilitate both #3046 and #6863 in followup PRs.
As a side effect, this PR gives modular curves the ability to call global functions that use the previously received value as an argument.
This PR also cleans out the old particle spawn logic, which is no longer necessary with the new particle system being the only source of particles.
Even though every particle has to access the particle manager and query it for the particle effect, this PR had no measurable performance difference on a 300k particle stress test.
> Give Particles Access to Their Spawner Effect

- cmake/globals.cmake
I found that when thying to crosscompile for android armeabi-v7a that the armv7 cpus (32 bits) were considered as x86 and triggering a cascade of different errors on diferent places.
Making sure IS_X86 is never set to true on this case avoids all of that and compiles OK.
> Do not set IS_X86 when target cpu is armv7

- code/model/modelcollide.cpp
- code/weapon/beam.cpp
Now, you may be asking, "how can an edge have a sensible normal".
In FSO, we have a lot of places that expect to get a valid normal for every collision. So what to do in the case of an edge hit? In most cases, especially for VFX, it's enough to get a normal that's sufficiently close and contiguous compared to surrounding normals. As such, returning the normal of any of the faces that an edge belongs to is likely going to be a sufficient approximation.
There's a few places that still calculate manual normals in case of an edge hit with a different strategy, but as these don't rely on the value returned by the collision code, we can ignore them here.
This fixes several particle related bugs where a proper normal was expected, and restores normal-alignment functionality for beams that was …
> Supply normals for edge hits

- code/particle/particle.cpp
From Sept 15 onward in fast debug I hit this error when using weapon create ASSERTION: "cur_frame < part->nframes" at particle.cpp:371
Assert: "cur_frame < part->nframes"
File: particle.cpp
Line: 371
Thanks to lafiel, `that assert should have an `|| (part->nframes == 0 && cur_frame == 0) appended beaause while we need to stay inbounds for animations, frame 0 for both is valid for static images`
> Update to #7023

- code/particle/ParticleEffect.cpp
- code/particle/ParticleEffect.h
- code/particle/ParticleParse.cpp
- code/particle/particle.cpp
Closes #3046.
The light has three modes:
1. Point light at the position of the particle
2. Tube light from the particles position last frame to its current position
3. a "particle native" mode, where point particles have a point light source, and where particles with a length have a tube light source along their length
> Particles can now emit light

- code/particle/ParticleEffect.cpp
- code/particle/particle.cpp
Particle bitmaps weren't correctly initialized in the last few nightlies because the init was gated behind an if-check that relied on particle_info default values that now no longer exist. But since that check was always true since the particle rework, just remove it now.
Also, fix a copy-paste error with the wrong curve being picked for the new radius curve implementation
> Small particle copy-paste fixes

- code/ai/ai_flags.h
- code/ai/ai_profiles.cpp
- code/ai/aigoals.cpp
By default, the player's wing will be issued a form-on-wing order at the beginning of the mission if the wing has no other initial goals.  Wings in the "starting wings" list that are not the player's wing will also be issued this goal if they arrive after mission start and have no other initial goals.  This PR adds a flag to disable this behavior.
> add ai_profiles flag to disable form-on-wing at mission start

- code/asteroid/asteroid.cpp
- code/hud/hudets.h
- code/model/model.h
- code/object/object_instance.h
- code/particle/ParticleEffect.h
- code/particle/ParticleManager.h
- code/particle/ParticleSource.cpp
- code/particle/particle.cpp
- code/source_groups.cmake
- code/utils/modular_curves.h
- code/weapon/muzzleflash.cpp
This now properly adds all that is required to do thruster effects. As such, closes #5727.
To get to this effect, this PR had to do a little bit of cleanup of includes, in order to avoid unnecessary include loops.
Furthermore, modular curves had some missing edge cases included, such as functions returning optional values.
Finally, a new convenience function was added to get an object instance of the correct type from an objp, if that object has the correct type, and an empty optional if not. This can be used to easily query for ship data in modular curves if only an objp is available.
> Particle Curves with access to host object & ship properties

- code/localization/localize.cpp
Adds the necessary XSTRs for language names in the options menu
> Localize language names for SCPUI

- qtfred/source_groups.cmake
- qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp
- qtfred/src/mission/dialogs/CampaignEditorDialogModel.h
- qtfred/src/ui/dialogs/CampaignEditorDialog.cpp
- qtfred/src/ui/dialogs/CampaignEditorDialog.h
- qtfred/src/ui/widgets/CampaignMissionGraph.cpp
- qtfred/src/ui/widgets/CampaignMissionGraph.h
- qtfred/src/ui/widgets/SimpleListSelectDialog.cpp
- qtfred/src/ui/widgets/SimpleListSelectDialog.h
- qtfred/ui/CampaignEditorDialog.ui
Revises and completes the Campaign Editor dialog. Implements a flexible node graph editing flow that seems to work with all campaigns I've thrown at it so far including BP2 and JAD 2.23. Saving is not accurate as QtFRED's missionsave.cpp is outdated. That will need to be fixed in a follow-up as noted in #7028 .
Fixes #1693
> QtFRED Campaign Editor

- code/particle/ParticleManager.cpp
- code/particle/ParticleManager.h
- code/scripting/api/libs/tables.cpp
- code/scripting/api/objs/particle.cpp
- code/scripting/api/objs/particle.h
Closes #5264.
This PR exposes the new-style particle effects as tabled, allows creating a particle source from that effect, and then to attach or place that source as desired.
One thing to note is that, by nature of the particle system, sources are not designed to be kept around, so source handles invalidate basically immediately, and must be used within the same frame as they are created.
An example script to use the new particle system is as follows:
```lua
local effect = tb.ParticleEffects['particle_name']
local source = effect:createSource()
source:createOnCoordinates(ba.createVector(0, 0, 50), ba.createOrientation())
```
> Particle Scripting API

- code/asteroid/asteroid.cpp
Zero initialize the string so garbage data doesn't accidentally bypass VALID_FNAME().
> Fix Asteroid Table Parsing

- code/model/animation/modelanimation.cpp
Anim executables need to respect wraparounds properly, otherwise that'll incorrectly trigger the entire animation on wraparound
> Fix anim executables when animations wrap around
